### ISSUE TITLE
Code duplication in the TkSlf4j.java

### ISSUE THREAD

**Issue by pal548** [yegor256/takes#1002]
Hello everyone, I accidentally found some code duplication in TkSlf4j.
I made some refactoring, please welcome to check PR.

**Comment by 0crat** [comment]
@paulodamaso[/z](https://www.0crat.com/u/paulodamaso) please, pay attention to this issue

**Comment by 0crat** [comment]
@pal548[/z](https://www.0crat.com/u/pal548) this project will fix the problem faster if you donate a few dollars to it; just [click here](https://www.0crat.com/contrib/C3FFK3YAY) and pay via Stripe, it's very fast, convenient and appreciated; thanks a lot!

**Comment by pal548** [comment]
But I`m not sure of the design, maybe someone could help me improve it. Thanks

**Comment by fanifieiev** [comment]
@paulodamaso Please take a look at the issue. I do not agree with that.

**Comment by yegor256** [comment]
@pal548 we still have this issue or it's time to close the ticket?

**Comment by pal548** [comment]
@yegor256  yes, closing it

**Comment by 0crat** [comment]
Job `gh:yegor256/takes#1002` is not assigned, can't get performer
