### ISSUE TITLE
Transform.java:34-37: Please remove this class and also...

### ISSUE THREAD

**Issue by 0pdd** [yegor256/takes#1014]
The puzzle `998-179b06ba` from #998 has to be resolved: 

https://github.com/yegor256/takes/blob/47805287af4df195dfb51c8633e232e7725cc442/src/main/java/org/takes/misc/Transform.java#L34-L37

The puzzle was created by @fanifieiev on 29-Nov-19. 

Estimate: 30 minutes,  role: DEV. 

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0crat** [comment]
@paulodamaso[/z](https://www.0crat.com/u/paulodamaso) please, pay attention to this issue

**Comment by 0crat** [comment]
Job [#1014](https://github.com/yegor256/takes/issues/1014) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
The job [#1014](https://github.com/yegor256/takes/issues/1014) assigned to @fanifieiev[/z](https://www.0crat.com/u/fanifieiev), here is [why](https://www.0crat.com/footprint/C3FFK3YAY/9d5e11b4-5ac7-41d9-95a0-8ae4170dc6a5); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be no monetary reward for this job

**Comment by 0pdd** [comment]
The puzzle `998-179b06ba` has disappeared from the source code, that's why I closed this issue.

**Comment by 0crat** [comment]
@sereshqua[/z](https://www.0crat.com/u/sereshqua) please review this job completed by @fanifieiev[/z](https://www.0crat.com/u/fanifieiev), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by sereshqua** [comment]
@0crat quality good
