### ISSUE TITLE
Utf8OutputStreamContent.java:33-36: Please remove this...

### ISSUE THREAD

**Issue by 0pdd** [yegor256/takes#1017]
The puzzle `998-37169ad0` from #998 has to be resolved: 

https://github.com/yegor256/takes/blob/47805287af4df195dfb51c8633e232e7725cc442/src/main/java/org/takes/misc/Utf8OutputStreamContent.java#L33-L36

The puzzle was created by Fevzi Anifieiev on 29-Nov-19. 

Estimate: 30 minutes,  role: DEV. 

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0crat** [comment]
@paulodamaso[/z](https://www.0crat.com/u/paulodamaso) please, pay attention to this issue

**Comment by 0crat** [comment]
Job [#1017](https://github.com/yegor256/takes/issues/1017) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
The job [#1017](https://github.com/yegor256/takes/issues/1017) assigned to @fanifieiev[/z](https://www.0crat.com/u/fanifieiev), here is [why](https://www.0crat.com/footprint/C3FFK3YAY/702d3bf3-4949-430c-a2bb-e6cf6e8ceee6); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be no monetary reward for this job

**Comment by 0pdd** [comment]
The puzzle `998-37169ad0` has disappeared from the source code, that's why I closed this issue.

**Comment by fanifieiev** [comment]
@0crat status

**Comment by paulodamaso** [comment]
@0crat out

**Comment by 0crat** [comment]
> @0crat status ([here](https://github.com/yegor256/takes/issues/1017#issuecomment-618446285))

@fanifieiev This is what I know about this job in C3FFK3YAY, as in [§32](http://www.zerocracy.com/policy.html#32):

  * The job [#1017](https://github.com/yegor256/takes/issues/1017) is [in scope](http://www.zerocracy.com/policy.html#14) for 3mon
  * The role is `DEV`
  * The job is assigned to @fanifieiev[/z](https://www.0crat.com/u/fanifieiev) for [1mon](http://www.zerocracy.com/policy.html#8)
  * There is no monetary reward attached, it's a [free](http://www.zerocracy.com/policy.html#2) job
  * The job doesn't have any [impediments](http://www.zerocracy.com/policy.html#9)
  * The [budget](http://www.zerocracy.com/policy.html#4) is 30 minutes/points
  * These users are banned and won't be assigned:
    * @0pdd[/z](https://www.0crat.com/u/0pdd): This user reported the ticket
  * Job [footprint](https://www.0crat.com/footprint/C3FFK3YAY?q=%7Bjob%3A%27gh%3Ayegor256%2Ftakes%231017%27%2Ctype%3A%7B%24not%3A%2F%5ENotify%2F%7D%7D) (restricted area)

**Comment by 0crat** [comment]
@sereshqua[/z](https://www.0crat.com/u/sereshqua) please review this job completed by @fanifieiev[/z](https://www.0crat.com/u/fanifieiev), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by sereshqua** [comment]
@0crat quality good
