### ISSUE TITLE
FkHost.java:51-55: Use {@link org.cactoos.scalar.Ternary}...

### ISSUE THREAD

**Issue by 0pdd** [yegor256/takes#1019]
The puzzle `998-08523712` from #998 has to be resolved: 

https://github.com/yegor256/takes/blob/47805287af4df195dfb51c8633e232e7725cc442/src/main/java/org/takes/facets/fork/FkHost.java#L51-L55

The puzzle was created by Fevzi Anifieiev on 02-Dec-19. 

Estimate: 30 minutes,  role: DEV. 

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0crat** [comment]
@paulodamaso[/z](https://www.0crat.com/u/paulodamaso) please, pay attention to this issue

**Comment by 0crat** [comment]
Job [#1019](https://github.com/yegor256/takes/issues/1019) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
The job [#1019](https://github.com/yegor256/takes/issues/1019) assigned to @fanifieiev[/z](https://www.0crat.com/u/fanifieiev), here is [why](https://www.0crat.com/footprint/C3FFK3YAY/2b6de802-6f0e-45a7-a2db-79a904bcfc0d); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be no monetary reward for this job

**Comment by 0pdd** [comment]
The puzzle `998-08523712` has disappeared from the source code, that's why I closed this issue.

**Comment by paulodamaso** [comment]
@0crat out

**Comment by 0crat** [comment]
@sereshqua[/z](https://www.0crat.com/u/sereshqua) please review this job completed by @fanifieiev[/z](https://www.0crat.com/u/fanifieiev), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by sereshqua** [comment]
@0crat quality good
