### ISSUE TITLE
TsLogged not implemented

### ISSUE THREAD

**Issue by dmzaytsev** [yegor256/takes#102]
I expect TsLogged can log basic parameters of methods called, but it not implemented.

**Comment by yegor256** [comment]
There is no `TsLogged` class in the source code... this ticket looks like a duplicate of #28

**Comment by yegor256** [comment]
@dmzaytsev you should use PDD puzzles for what you're trying to achieve, not tickets

**Comment by dmzaytsev** [comment]
@yegor256 I referenced this issue from the puzzle.
I should use `@todo` without ticket number in the puzzle in such cases, right ?

**Comment by yegor256** [comment]
@dmzaytsev nope, you can't make a puzzle without a ticket number. Let's discuss this in the task where you make that puzzles
