### ISSUE TITLE
It's horrible naming convention, I don't understand shortcut names. It's a bad practice. 

### ISSUE THREAD

**Issue by Guseyn** [yegor256/takes#1022]

**Comment by 0crat** [comment]
@paulodamaso[/z](https://www.0crat.com/u/paulodamaso) please, pay attention to this issue

**Comment by 0crat** [comment]
@guseyn[/z](https://www.0crat.com/u/guseyn) this project will fix the problem faster if you donate a few dollars to it; just [click here](https://www.0crat.com/contrib/C3FFK3YAY) and pay via Stripe, it's very fast, convenient and appreciated; thanks a lot!

**Comment by rusefi** [comment]
+1

**Comment by paulodamaso** [comment]
@Guseyn the reasons are explained in https://www.yegor256.com/2020/03/03/prefixed-naming.html

**Comment by 0crat** [comment]
Job `gh:yegor256/takes#1022` is not assigned, can't get performer
