### ISSUE TITLE
Invalid request line for RqFake

### ISSUE THREAD

**Issue by g4s8** [yegor256/takes#1024]
The first request line in `RqFake` is not correct. According to [RFC2616](https://www.w3.org/Protocols/rfc2616/rfc2616-sec5.html) the request line should be:
```txt
Request-Line   = Method SP Request-URI SP HTTP-Version CRLF
```
But `new RqFake()` returns: `GET /` ("Method SP Request-URI CRLF"), it means `HTTP-Version` component is missing. The correct default request line could be: `GET / HTTP/1.1` or any other valid request line.

**Comment by 0crat** [comment]
@paulodamaso[/z](https://www.0crat.com/u/paulodamaso) please, pay attention to this issue

**Comment by paulodamaso** [comment]
@0crat in

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 point(s) just awarded to @g4s8[/z](https://www.0crat.com/u/g4s8)

**Comment by 0crat** [comment]
@baudoliver7[/z](https://www.0crat.com/u/baudoliver7) resigned from [#1024](https://github.com/yegor256/takes/issues/1024), since the job is not in scope anymore
