### ISSUE TITLE
Handling exceptions for unknown requests.

### ISSUE THREAD

**Issue by Abhijith-m13894** [yegor256/takes#1032]
I am unable to send HTTP Status codes ( like 404 Not Found ) with a custom message. Instead and Exception is shown when I send a request using Postman. 

Is there any provision to handle the exception and add a custom message in case of unknown requests for takes server ?
![Capture](https://user-images.githubusercontent.com/61135970/74701657-79482a80-522d-11ea-81ec-60a3b4812647.PNG)

**Comment by 0crat** [comment]
@paulodamaso[/z](https://www.0crat.com/u/paulodamaso) please, pay attention to this issue

**Comment by 0crat** [comment]
@abhijith-m13894[/z](https://www.0crat.com/u/abhijith-m13894) this project will fix the problem faster if you donate a few dollars to it; just [click here](https://www.0crat.com/contrib/C3FFK3YAY) and pay via Stripe, it's very fast, convenient and appreciated; thanks a lot!

**Comment by Abhijith-m13894** [comment]
Figured out the solution


private static Take HandleException(final Take take) {
    return new TkFallback(
            take,
            new FbChain(
                    new FbStatus(
                            HttpURLConnection.HTTP_NOT_FOUND,
                            new RsWithStatus(
                                    new RsText("Path not found"),
                                    HttpURLConnection.HTTP_NOT_FOUND
                            )
                    ),
                    new FbStatus(
                            HttpURLConnection.HTTP_BAD_REQUEST,
                            new RsWithStatus(
                                    new RsText("Bad or Incorrect request"),
                                    HttpURLConnection.HTTP_BAD_REQUEST
                            )
                    ),
            )
    );
}


Adding TkFallback gives provision to add FbChain where unhandled exceptions can be handled.

**Comment by 0crat** [comment]
Job `gh:yegor256/takes#1032` is not assigned, can't get performer

**Comment by 0crat** [comment]
This job is not in scope
