### ISSUE TITLE
New Cactoos version dependency required

### ISSUE THREAD

**Issue by fanifieiev** [yegor256/takes#1049]
Please have Takes updated with newer version of Cactoos

**Comment by 0crat** [comment]
@paulodamaso[/z](https://www.0crat.com/u/paulodamaso) please, pay attention to this issue

**Comment by paulodamaso** [comment]
@0crat in

**Comment by yegor256** [comment]
@fanifieiev check takes `1.24.3`, it uses the latest Cactoos `0.54.0`

**Comment by 0crat** [comment]
Job [#1049](https://github.com/yegor256/takes/issues/1049) is not in the agenda of @baudoliver7[/z](https://www.0crat.com/u/baudoliver7), can't set title

**Comment by 0crat** [comment]
Job [#1049](https://github.com/yegor256/takes/issues/1049) is not in the agenda of @baudoliver7[/z](https://www.0crat.com/u/baudoliver7), can't set title

**Comment by 0crat** [comment]
@sereshqua[/z](https://www.0crat.com/u/sereshqua) please review this job completed by @baudoliver7[/z](https://www.0crat.com/u/baudoliver7), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed
