### ISSUE TITLE
CcGzip

### ISSUE THREAD

**Issue by yegor256** [yegor256/takes#105]
Let's create new `Codec` decorator, which will compress data with GZIP and uncompress them back. I'm expecting to use it like this (for example):

```
Codec codec = new CcGzip(new CcPlain());
```

**Comment by davvd** [comment]
@yegor256 sure, thanks, I added bug tag to it

**Comment by davvd** [comment]
@yegor256 thanks for the ticket, your account was topped for 15 mins, payment 000-3b9ea00c

**Comment by davvd** [comment]
@yegor256 I set milestone here to `1.0`, let me know if it is wrong

**Comment by davvd** [comment]
@eg04lt3r this ticket is yours now, please proceed, and keep in mind [this](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html). Any technical questions you should ask right here

This task's budget is **30 mins**. This is exactly how much will be paid when the problem explained above is solved. See [this](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html) for more information

**Comment by eg04lt3r** [comment]
@yegor256 fixed in #214  pull request.

**Comment by eg04lt3r** [comment]
@yegor256 please, find someone for review. Maybe, should I ask @davvd for this?

**Comment by eg04lt3r** [comment]
@yegor256 please, close task if ok.

**Comment by yegor256** [comment]
@eg04lt3r thanks!

**Comment by davvd** [comment]
@elenavolokhova review this ticket please, for compliance with our [quality rules](http://www.teamed.io/qa.html)

**Comment by elenavolokhova** [comment]
@davvd Looks good!

**Comment by davvd** [comment]
> @davvd Looks good!

@elenavolokhova thanks!

**Comment by davvd** [comment]
@eg04lt3r I added 10 mins to @elenavolokhova (for QA review) in transaction 56931005; Thanks so much! Your account was topped up for **30 mins** (transaction ID is `56931028`, the task took 335 hours and 47 mins); +30 added to your rating, current score is: [-112](http://www.netbout.com/b/35234?open=rating)
