### ISSUE TITLE
Internal exception trying to return response with status code 203

### ISSUE THREAD

**Issue by wizzu** [yegor256/takes#1050]
Hello,

When I'm trying to create an response with http status code 203 I get a resul of this kind of stack trace:

java.lang.IllegalArgumentException: first line of HTTP response "HTTP/1.1 203 Non-Authoritative Information" doesn't match "HTTP/1\.1 \d{3} [a-zA-Z ]+" regular expression, but it should, according to RFC 7230
    at org.takes.rs.RsPrint.printHead(RsPrint.java:153)
    at org.takes.rs.RsPrint.printHead(RsPrint.java:137)
    at org.takes.rs.RsPrint.print(RsPrint.java:126)
    at org.takes.http.BkBasic.print(BkBasic.java:127)
    at org.takes.http.BkBasic.accept(BkBasic.java:103)
    at org.takes.http.BkSafe$1.accept(BkSafe.java:49)
    at org.takes.http.BkWrap.accept(BkWrap.java:51)
    at org.takes.http.FtBasic.loop(FtBasic.java:114)
    at org.takes.http.FtBasic.start(FtBasic.java:100)
...

I used this kind of code (I used actually RsJson() but the RsEmpty() should do it as well):

return new RsWithStatus(new RsEmpty(), 203);

The problem is that the regexp in RsPrint.java#L63 is too simplistic.
RFC 7230 allows "all printing characters" for the first line (in addition to space), which is not just a-zA-Z.  For the 203 status the default description includes a hyphen "-" which is not allowed by the regexp, and results in the exception. The correct character range would be %x21-7E. See here: https://stackoverflow.com/questions/52336695/what-are-visible-ascii-characters

**Comment by 0crat** [comment]
@paulodamaso[/z](https://www.0crat.com/u/paulodamaso) please, pay attention to this issue

**Comment by paulodamaso** [comment]
@0crat in

**Comment by rusefillc** [comment]
How about https://github.com/yegor256/takes/pull/1059/

**Comment by wizzu** [comment]
The #1059 change will fix this immediate issue. Thanks.

If you want to stick by the RFC 7230, the change is not sufficient. The current list of more-or-less-official names for the status codes doesn't seem to include other non-alphabetic characters beyond space and the minus, so from that point of view it's fine. If custom messages are ever supported, then this pattern will become problematic.

Personally I don't care overly much, so whatever.

**Comment by 0pdd** [comment]
@wizzu the puzzle [#1062](https://github.com/yegor256/takes/issues/1062) is still not solved.

**Comment by paulodamaso** [comment]
@0crat assign @andreoss

**Comment by paulodamaso** [comment]
@0crat status

**Comment by 0crat** [comment]
> @0crat status ([here](https://github.com/yegor256/takes/issues/1050#issuecomment-719948588))

@paulodamaso This is what I know about this job in C3FFK3YAY, as in [§32](http://www.zerocracy.com/policy.html#32):

  * The job [#1050](https://github.com/yegor256/takes/issues/1050) is [in scope](http://www.zerocracy.com/policy.html#14) for 5mon
  * The role is `DEV`
  * The job is assigned to @andreoss[/z](https://www.0crat.com/u/andreoss) for [16days](http://www.zerocracy.com/policy.html#8)
  * There is no monetary reward attached, it's a [free](http://www.zerocracy.com/policy.html#2) job
  * The job doesn't have any [impediments](http://www.zerocracy.com/policy.html#9)
  * The [budget](http://www.zerocracy.com/policy.html#4) is 30 minutes/points
  * These users are banned and won't be assigned:
    * @wizzu[/z](https://www.0crat.com/u/wizzu): This user reported the ticket
  * Job [footprint](https://www.0crat.com/footprint/C3FFK3YAY?q=%7Bjob%3A%27gh%3Ayegor256%2Ftakes%231050%27%2Ctype%3A%7B%24not%3A%2F%5ENotify%2F%7D%7D) (restricted area)

**Comment by 0crat** [comment]
@sereshqua[/z](https://www.0crat.com/u/sereshqua) please review this job completed by @andreoss[/z](https://www.0crat.com/u/andreoss), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by sereshqua** [comment]
@rusefillc please make sure you start all your comments with the name of the user they are referred to, [see](https://github.com/yegor256/takes/issues/1050#issuecomment-663871849)

**Comment by sereshqua** [comment]
@0crat quality acceptable

**Comment by 0pdd** [comment]
@wizzu the only puzzle [#1062](https://github.com/yegor256/takes/issues/1062) is solved here.
