### ISSUE TITLE
RsPrint.java:48-52: Extract printHead and printBody in...

### ISSUE THREAD

**Issue by 0pdd** [yegor256/takes#1054]
The puzzle `984-c7848b91` from #984 has to be resolved: 

https://github.com/yegor256/takes/blob/ef29898cc602dcffc7a52498b59cce7dbdea3917/src/main/java/org/takes/rs/RsPrint.java#L48-L52

The puzzle was created by andreoss on 23-Jun-20. 

Estimate: 30 minutes,  role: DEV. 

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0crat** [comment]
@paulodamaso[/z](https://www.0crat.com/u/paulodamaso) please, pay attention to this issue

**Comment by 0crat** [comment]
The job [#1054](https://github.com/yegor256/takes/issues/1054) assigned to @fabriciofx[/z](https://www.0crat.com/u/fabriciofx), here is [why](https://www.0crat.com/footprint/C3FFK3YAY/d10b1520-fc23-4473-a06c-7e0a30cacf45); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be no monetary reward for this job

**Comment by fabriciofx** [comment]
@0crat wait for REV

**Comment by fabriciofx** [comment]
@paulodamaso ping

**Comment by 0pdd** [comment]
The puzzle `984-c7848b91` has disappeared from the source code, that's why I closed this issue.

**Comment by 0pdd** [comment]
@0pdd 3 puzzles [#1073](https://github.com/yegor256/takes/issues/1073), [#1074](https://github.com/yegor256/takes/issues/1074), [#1075](https://github.com/yegor256/takes/issues/1075) are still not solved.

**Comment by 0pdd** [comment]
@0pdd the puzzle [#1073](https://github.com/yegor256/takes/issues/1073) is still not solved; solved: [#1074](https://github.com/yegor256/takes/issues/1074), [#1075](https://github.com/yegor256/takes/issues/1075).

**Comment by 0pdd** [comment]
@0pdd all 3 puzzles are solved here: [#1073](https://github.com/yegor256/takes/issues/1073), [#1074](https://github.com/yegor256/takes/issues/1074), [#1075](https://github.com/yegor256/takes/issues/1075).
