### ISSUE TITLE
RqPrint.java:41-43: This class should implement Text in...

### ISSUE THREAD

**Issue by 0pdd** [yegor256/takes#1055]
The puzzle `984-b6700210` from #984 has to be resolved: 

https://github.com/yegor256/takes/blob/ef29898cc602dcffc7a52498b59cce7dbdea3917/src/main/java/org/takes/rq/RqPrint.java#L41-L43

The puzzle was created by andreoss on 23-Jun-20. 

Estimate: 30 minutes,  role: DEV. 

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0crat** [comment]
@paulodamaso[/z](https://www.0crat.com/u/paulodamaso) please, pay attention to this issue

**Comment by 0pdd** [comment]
The puzzle `984-b6700210` has disappeared from the source code, that's why I closed this issue.

**Comment by 0crat** [comment]
Job `gh:yegor256/takes#1055` is not assigned, can't get performer
