### ISSUE TITLE
TkMethods

### ISSUE THREAD

**Issue by yegor256** [yegor256/takes#106]
Let's create two new decorators in `org.takes.facets.fork` package: `TsMethods` and `TkMethods`. They should be used like this:

```java
new TsMethods(takes, "GET");
new TsMethods(takes, "PUT,POST");
new TkMethods(take, "OPTIONS");
```

They should allow only specified methods to get through. I would suggest to implement them internally by means of `TsFork` and `FkMethods`.

Let's not forget about proper Javadoc documentation and unit tests.

**Comment by davvd** [comment]
@yegor256 sure, thanks, I added bug tag to it

**Comment by davvd** [comment]
@yegor256 thanks for the ticket, your account was topped for 15 mins, payment 000-46749037

**Comment by erimerturk** [comment]
@yegor256 can you assign it to me ?

**Comment by davvd** [comment]
@cyberone please go ahead with this task, it's yours

**Comment by cyberone** [comment]
@yegor256 three more questions:

1. Did you mean TkFork? 
2. What is the diffarence between TsMethods and TkMethods?
3. May I use varargs constructor?

**Comment by yegor256** [comment]
1. yes, 2. there is no TsMethods any more, it's deprecated, only TkMethods. 3. sure

**Comment by cyberone** [comment]
@davvd please review https://github.com/yegor256/takes/pull/235

**Comment by cyberone** [comment]
@yegor256 close please. The PR is merged.

**Comment by yegor256** [comment]
@cyberone thanks!

**Comment by davvd** [comment]
@elenavolokhova please, review this task for compliance with our [quality rules](http://www.teamed.io/qa.html)

**Comment by elenavolokhova** [comment]
@cyberone Do I understand correctly and issue description still states that deprecated methods should be implemented? If it is so, please, fix it.

**Comment by cyberone** [comment]
@elenavolokhova I have no permission to edit an issue. Ask @yegor256 please.

**Comment by yegor256** [comment]
@cyberone keep in mind that you, as a performer of the ticket, is responsible for its quality. So, it's your job to ask me (ticket reporter) to fix the description. That's why @elenavolokhova is asking you. You should ask me and make sure I do the necessary fixes.

**Comment by cyberone** [comment]
@yegor256 fix the description please.

**Comment by yegor256** [comment]
@cyberone fixed

**Comment by cyberone** [comment]
@elenavolokhova re-check please

**Comment by elenavolokhova** [comment]
@yegor256 @cyberone Thank you!

**Comment by elenavolokhova** [comment]
@davvd Quality is acceptable here.

**Comment by davvd** [comment]
> @davvd Quality is acceptable here.

@elenavolokhova thank you, let's try to make it "good" next time

**Comment by davvd** [comment]
@cyberone I added 10 mins to @elenavolokhova (for QA review) in transaction 56929016. Thanks so much! Your account was topped up for **30 mins** (transaction ID is `56929025`, the task took 296 hours and 9 mins). +30 to your rating, your total score is [+173](http://www.netbout.com/b/35076?open=rating)
