### ISSUE TITLE
RqPrint.java:51-54: Text lacks a decorator for caching...

### ISSUE THREAD

**Issue by 0pdd** [yegor256/takes#1062]
The puzzle `1050-5153da16` from #1050 has to be resolved: 

https://github.com/yegor256/takes/blob/6c01e7414b5ddd886d8b9cefc4346a147c02c6ec/src/main/java/org/takes/rq/RqPrint.java#L51-L54

The puzzle was created by andreoss on 26-Jul-20. 

Estimate: 30 minutes,  role: DEV. 

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0crat** [comment]
The job [#1062](https://github.com/yegor256/takes/issues/1062) assigned to @fabriciofx[/z](https://www.0crat.com/u/fabriciofx), here is [why](https://www.0crat.com/footprint/C3FFK3YAY/7d02565c-3a14-4d71-a0a6-f91d1f9f0345); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be no monetary reward for this job

**Comment by fabriciofx** [comment]
@andreoss I think we should wait for [#cactoos/1423](https://github.com/yegor256/cactoos/issues/1423). WDYT?

**Comment by fabriciofx** [comment]
@0crat wait for yegor256/cactoos#1423

**Comment by fabriciofx** [comment]
@0crat refuse

**Comment by 0crat** [comment]
> @0crat refuse ([here](https://github.com/yegor256/takes/issues/1062#issuecomment-686813508))

@fabriciofx The user @fabriciofx[/z](https://www.0crat.com/u/fabriciofx) resigned from [#1062](https://github.com/yegor256/takes/issues/1062), please stop working. Reason for job resignation: Order was cancelled

**Comment by andreoss** [comment]
@0crat in

**Comment by 0crat** [comment]
> @0crat in  ([here](https://github.com/yegor256/takes/issues/1062#issuecomment-799135222))

@andreoss You can't do "Add job to WBS", unless you have one of these roles: `ARC`, `PO`; current roles of @andreoss[/z](https://www.0crat.com/u/andreoss) are: `DEV`, `REV`

**Comment by paulodamaso** [comment]
@0crat in

**Comment by 0crat** [comment]
> @0crat in ([here](https://github.com/yegor256/takes/issues/1062#issuecomment-812116983))

@paulodamaso Job [#1062](https://github.com/yegor256/takes/issues/1062) is already in scope

**Comment by 0pdd** [comment]
The puzzle `1050-5153da16` has disappeared from the source code, that's why I closed this issue.
