### ISSUE TITLE
Move to github actions

### ISSUE THREAD

**Issue by fabriciofx** [yegor256/takes#1067]
Let's replace travis with github actions, once this is done, we can continue with also running tests on windows.

See also llorllale/cactoos-matchers#83 for some similar issue.

**Comment by fabriciofx** [comment]
@paulodamaso `cactoos-matchers` already moved from Travis to GitHub Actions. You can see/use [this PR](https://github.com/llorllale/cactoos-matchers/pull/174/files) as reference.

**Comment by andreoss** [comment]
@0crat assign me

**Comment by 0crat** [comment]
> @0crat assign me ([here](https://github.com/yegor256/takes/issues/1067#issuecomment-715649205))

@andreoss You can't do "Request order start", unless you have one of these roles: `ARC`, `PO`; current roles of @andreoss[/z](https://www.0crat.com/u/andreoss) are: `DEV`, `REV`

**Comment by paulodamaso** [comment]
@0crat assign @andreoss

**Comment by 0pdd** [comment]
@fabriciofx the puzzle [#1088](https://github.com/yegor256/takes/issues/1088) is still not solved.

**Comment by paulodamaso** [comment]
@fabriciofx seems that this puzzle has been already solved in https://github.com/yegor256/takes/pull/1085, please close

**Comment by 0crat** [comment]
@sereshqua[/z](https://www.0crat.com/u/sereshqua) please review this job completed by @andreoss[/z](https://www.0crat.com/u/andreoss), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by sereshqua** [comment]
@0crat quality good

**Comment by sereshqua** [comment]
@0crat quality good

**Comment by 0crat** [comment]
> @0crat quality good ([here](https://github.com/yegor256/takes/issues/1067#issuecomment-760442862))

@sereshqua There is no quality review for [#1067](https://github.com/yegor256/takes/issues/1067), no performer

**Comment by 0pdd** [comment]
@fabriciofx the puzzle [#1112](https://github.com/yegor256/takes/issues/1112) is still not solved; solved: [#1088](https://github.com/yegor256/takes/issues/1088).

**Comment by 0pdd** [comment]
@fabriciofx all 2 puzzles are solved here: [#1088](https://github.com/yegor256/takes/issues/1088), [#1112](https://github.com/yegor256/takes/issues/1112).
