### ISSUE TITLE
TkConsumes, TsConsumes

### ISSUE THREAD

**Issue by yegor256** [yegor256/takes#107]
Let's create two new decorators in `org.takes.facets.fork` package: `TsConsumes` and `TkConsumes`. They should be used like this:

```java
new TsConsumes(takes, "application/json");
new TsMethods(takes, "text/*");
new TkMethods(take, "text/xml,application/xml");
```

They should allow only request with certain `Content-Type` to get through. I would suggest to implement them internally by means of `TsFork` and `FkTypes`.

Let's not forget about proper Javadoc documentation and unit tests.

**Comment by davvd** [comment]
@yegor256 thanks, I added the "bug" tag

**Comment by davvd** [comment]
@celezar this task is for you, keep [these principles](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html) in mind, and don't hesitate to ask any technical questions. **30 mins** is the budget of the task. This is exactly how much will be paid when the problem is [solved](http://www.xdsd.org/2014/04/15/definition-of-done.html) (no matter how much time you will actually spend). See [this](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html) for more information

**Comment by davvd** [comment]
@yegor256 many thanks, **15 mins** added to your acc for reporting this bug, pmt ID `000-4b12a3f7`

**Comment by celezar** [comment]
@davvd @yegor256 Is this task affected by changes made in #133? Since we don't have Takes anymore.

**Comment by yegor256** [comment]
@celezar yes, indeed, we need to create only `TkConsumes`

**Comment by celezar** [comment]
Please assign this task to someone else.

**Comment by yegor256** [comment]
@davvd give this to somebody else pls

**Comment by davvd** [comment]
> @davvd give this to somebody else pls

@yegor256 someone else will help in this task, no problem at all

**Comment by davvd** [comment]
@yegor256 attached this issue to milestone "1.0" (let me know if this is wrong)

**Comment by davvd** [comment]
@ikhvostenkov the task is yours please proceed

**Comment by davvd** [comment]
@ikhvostenkov you're working with this issue for 15 days already; -30 added to your rating, current score is: [+61](http://www.netbout.com/b/35232?open=rating)

**Comment by ikhvostenkov** [comment]
@davvd PR has been accepted 5 days ago, but due to https://github.com/yegor256/takes/issues/253 merge is not possible. We need to wait until https://github.com/yegor256/takes/issues/253 will be fixed.

**Comment by yegor256** [comment]
@ikhvostenkov the problem in #253 was suppressed by `@Ignore` two days ago. we can merge now without problems

**Comment by ikhvostenkov** [comment]
@davvd https://github.com/yegor256/takes/pull/215 resolves this issue. Fix has been successfully merged.

**Comment by yegor256** [comment]
@ikhvostenkov I'm a reporter here, you should ask me to close it, not @davvd

**Comment by ikhvostenkov** [comment]
@yegor256 Could you please close this one if no comments from your site and you are satisfied with solution in https://github.com/yegor256/takes/pull/215

**Comment by yegor256** [comment]
@ikhvostenkov sure, thanks!

**Comment by davvd** [comment]
@ikhvostenkov Much appreciated! **38 mins** was added to your account, payment ID `57307234`, time spent is 455 hours and 13 mins. age=2944, that's why a bonus here for fast delivery. added +38 to your rating, now it is equal to [+115](http://www.netbout.com/b/35232?open=rating)
