### ISSUE TITLE
Test resources filtering true or false?

### ISSUE THREAD

**Issue by fabriciofx** [yegor256/takes#1071]
In `pom.xml`:
```
    <testResources>
      <testResource>
        <filtering>true</filtering>
        <directory>${project.basedir}/src/test/resources</directory>
        <excludes>
          <exclude>org/takes/http/keystore</exclude>
        </excludes>
      </testResource>
      <testResource>
        <filtering>false</filtering>
        <directory>${project.basedir}/src/test/resources</directory>
        <includes>
          <include>org/takes/http/keystore</include>
        </includes>
      </testResource>
    </testResources>
```
The same configuration, but just changing filtering from `true` to `false`? Is it correct or was a bad copy and paste?

**Comment by paulodamaso** [comment]
@0crat in

**Comment by yegor256** [comment]
@fabriciofx I added some explanation in 3789ae37b

**Comment by 0crat** [comment]
@sereshqua[/z](https://www.0crat.com/u/sereshqua) please review this job completed by @baudoliver7[/z](https://www.0crat.com/u/baudoliver7), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed
