### ISSUE TITLE
HeadPrint.java:42-44: Develop tests for {@link HeadPrint}...

### ISSUE THREAD

**Issue by 0pdd** [yegor256/takes#1075]
The puzzle `1054-a8efe282` from #1054 has to be resolved: 

https://github.com/yegor256/takes/blob/7d155276c74a68a14c0d2b93b4205e845131dd22/src/main/java/org/takes/rs/HeadPrint.java#L42-L44

The puzzle was created by Fabrício Cabral on 11-Sep-20. 

Estimate: 30 minutes,  role: DEV. 

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0pdd** [comment]
The puzzle `1054-a8efe282` has disappeared from the source code, that's why I closed this issue.

**Comment by 0crat** [comment]
@sereshqua[/z](https://www.0crat.com/u/sereshqua) please review this job completed by @baudoliver7[/z](https://www.0crat.com/u/baudoliver7), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by sereshqua** [comment]
@0crat quality good
