### ISSUE TITLE
Update Qulice to 0.18.19

### ISSUE THREAD

**Issue by andreoss** [yegor256/takes#1077]
Outdated Qulice prevents migration to Junit 5, since it gives a lot of false positive `PMD.DefaultScope`.

**Comment by andreoss** [comment]
@paulodamaso Can you put it in scope?

**Comment by andreoss** [comment]
@0crat assign @andreoss

**Comment by 0crat** [comment]
> @0crat assign @andreoss ([here](https://github.com/yegor256/takes/issues/1077#issuecomment-708065916))

@andreoss You can't do "Request order start", unless you have one of these roles: `ARC`, `PO`; current roles of @andreoss[/z](https://www.0crat.com/u/andreoss) are: `DEV`, `REV`

**Comment by paulodamaso** [comment]
@0crat assign @andreoss

**Comment by andreoss** [comment]
Done in #1086

**Comment by 0crat** [comment]
@sereshqua[/z](https://www.0crat.com/u/sereshqua) please review this job completed by @andreoss[/z](https://www.0crat.com/u/andreoss), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by sereshqua** [comment]
@andreoss Problem reporter and problem solver are the same person

**Comment by sereshqua** [comment]
@0crat quality acceptable
