### ISSUE TITLE
Badges in the README are confusing

### ISSUE THREAD

**Issue by binkley** [yegor256/takes#1079]
(META remark &mdash; your issue form has a checklist, but does not take advantage of markdown checkboxes)

I load the GitHub site, and look over the `README.md`.  Badges are one of the first recommendations in [Elegant READMEs](https://www.yegor256.com/2019/04/23/elegant-readme.html), and that post directs me to the Takes project as an example.  I find the badges presented _confusing_ and _seemingly duplicative_.

![image](https://user-images.githubusercontent.com/186421/95583059-34157a80-0a01-11eb-9871-345bb64f2d8f.png)

I see:
- Zerocrat is referenced multiple times.  I went to the link for the first Zerocrat badge, and was presented with a screen unrelated to the project (donations; please log in, no indication of project &mdash; this might be a Zerocrat issue)
- According to the badges, the build is _both_ passing and failing
- The badge I care most about, how to download (Maven central), is near the bottom
- I see version "1.19" spread out: these should be together visually
- The "jpeek" number looks just random (note: the badge updated while I was writing this issue; the screenshot does not reflect that)
- There seems no rhyme nor reason to the ordering of the badges

I do not want to harsh on Takes.  I'm trying to understand this project in the context of "Elegant READMEs".

**Comment by yegor256** [comment]
@binkley fixed, thanks!

**Comment by 0crat** [comment]
Job `gh:yegor256/takes#1079` is not assigned, can't get performer
