### ISSUE TITLE
TsProduces, TkProduces

### ISSUE THREAD

**Issue by yegor256** [yegor256/takes#108]
Let's create two new decorators in `org.takes.facets.fork` package: `TsProduces` and `TkProduces`. They should be used like this:

```java
new TsProduces(takes, "application/json");
new TsProduces(takes, "text/xml");
new TkProduces(take, "text/xml,application/xml");
```

They should allow only request with certain `Accept` header to get through. I would suggest to implement them internally by means of `TsFork` and `FkTypes`.

Let's not forget about proper Javadoc documentation and unit tests.

**Comment by davvd** [comment]
@yegor256 sure, thanks, I added bug tag to it

**Comment by davvd** [comment]
@ekondrashev this task is yours, please help (see our key [principles of work](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html)). If you have any technical questions, don't hesitate to ask right here; Budget here is **30 mins** (keep [this principle](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html) in mind)

**Comment by davvd** [comment]
@yegor256 thanks a lot for reporting, **15 mins** added to your acc, pmt ID `000-ce2017f5`

**Comment by ekondrashev** [comment]
@yegor256 Could you please describe the reason for <prefix>Produces naming?
Is "Produces" should be considered as a verb or noun?

**Comment by yegor256** [comment]
@ekondrashev I took it from JAX-RS: http://docs.oracle.com/javaee/6/api/javax/ws/rs/Produces.html

**Comment by ekondrashev** [comment]
@yegor256 Could you please elaborate on the reason to put those classes at `org.takes.facets.fork` package considering they(`TsProduces`, `TkProduces`) implement `Takes` and `Take` accordingly, but not a `Fork`?

**Comment by ekondrashev** [comment]
@yegor256 After doing some investigation on existing codebase I found several blockers on this task to be implemented:
##### As for `TsProduces` 
Currently `FkTypes` implements `Fork.AtResponse` interface, but `TsFork` expects `Fork.AtTake` instances, so it is not possible to make use of `FkType` in order to implement `TsProduces`. 
If `TsFork` would accept instances of `FkTypes` i’d consider implementation like this:
```java
public class TsProduces implements Takes {
	
	private final String accept;
	private final Takes takes;
    /**
     * Ctor.
     *
     * @param takes Original takes
     * @param acpt headers
     */
    public TsProduces(final Takes tks, final String acpt) {
    	this.takes = tks;
        this.accept = acpt;
    }
    
    public Take route(Request request) throws IOException {
    	final FkTypes types = new FkTypes(accept, takes.route(request));
    	return new TsFork(types).route(request);
    }

}
```
I’d suggest to create a separate issue for implementing similar to `FkTypes` to deal with `Take` instances. Please let me know if I missed something. 

##### As for `TkProduces` being used as 
```java
new TkProduces(take, "text/xml,application/xml”);
```
this usage contract reduces usage `Request` object which make it impossible to figure out what was the Accept header. I was looking into `TkGzip` class as an example:
```java
@EqualsAndHashCode(callSuper = true)
public final class TkGzip extends TkWrap {

    public TkGzip(final Take take, final Request request) {
        super(
            new Take() {
                @Override
                public Response act() throws IOException {
                    final Response response = take.act();
                    return new RsFork(
                        request,
                        new FkEncoding("gzip", new RsGzip(response)),
                        new FkEncoding("", response)
                    );
                }
            }
        );
    }

}
``` 

so the `TkProduces` can be implemented like this:
```java
@EqualsAndHashCode(callSuper = true)
public final class TkProduces extends TkWrap {

    public TkProduces(final Take take, final Request request, final String types) {
        super(
            new Take() {
                @Override
                public Response act() throws IOException {
                    final Response response = take.act();
                    return new RsFork(
                        request,
                        new FkTypes(types, response)
                    );
                }
            }
        );
    }

}
```
But this requires passing request object. Please let me know if this contract is ok for you or if I missed something.

**Comment by yegor256** [comment]
@ekondrashev please update your local branch from `master`. We have made some major changes recently.

**Comment by davvd** [comment]
@yegor256 milestone set to `1.0` (correct me if I am wrong)

**Comment by davvd** [comment]
@ekondrashev check this ["no obligations principle"](http://www.xdsd.org/2014/04/13/no-obligations-principle.html).. This task is on your name for at least 15 days. If you can't close it within the next 48 hours I will have to assign someone else to it. [This article](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html) should help if you're stuck. -30 added to your rating, current score is: [-45](http://www.netbout.com/b/35260?open=rating)

**Comment by ekondrashev** [comment]
@davvd the PR was closed already I just do not know what is the next correct step in ticket lifecycle
https://github.com/yegor256/takes/pull/164

**Comment by yegor256** [comment]
@ekondrashev you should ask ticket reporter to close it, see http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html

**Comment by ekondrashev** [comment]
@yegor256 please close the ticket the solution is provided at https://github.com/yegor256/takes/pull/164

**Comment by yegor256** [comment]
@ekondrashev thanks!

**Comment by davvd** [comment]
@elenavolokhova please, review this task for compliance with our [quality rules](http://www.teamed.io/qa.html)

**Comment by elenavolokhova** [comment]
@davvd This ticket looks good!

**Comment by davvd** [comment]
> @davvd This ticket looks good!

@elenavolokhova thanks for the review

**Comment by davvd** [comment]
@ekondrashev 10 mins was added to the account of @elenavolokhova (for QA review), in transaction 55960899... thanks, paid, **38 mins** to your account, payment ID is `55960928`, task took 407 hours and 24 mins to complete... the bonus for fast delivery (age=2945)... +38 to your rating, your total score is [+31](http://www.netbout.com/b/35260?open=rating)
