### ISSUE TITLE
Replace `org.takes.misc.Concat` with `org.cactoos.iterable.Joined`

### ISSUE THREAD

**Issue by andreoss** [yegor256/takes#1081]
`misc.Concat` and its internal `ConcatInterator` duplicate `Joined` classes from cactoos

**Comment by paulodamaso** [comment]
@0crat assign @andreoss

**Comment by andreoss** [comment]
Done in #1084

**Comment by 0crat** [comment]
@sereshqua[/z](https://www.0crat.com/u/sereshqua) please review this job completed by @andreoss[/z](https://www.0crat.com/u/andreoss), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by sereshqua** [comment]
@andreoss issue creator and issue performer is the same person, sorry

**Comment by sereshqua** [comment]
@0crat quality acceptable
