### ISSUE TITLE
PRs do not trigger CI

### ISSUE THREAD

**Issue by andreoss** [yegor256/takes#1083]
The CI is not triggered when a PR submitted.

For example:
1) https://github.com/yegor256/takes/pull/1082 
2) https://github.com/yegor256/takes/pull/1076

Related to https://github.com/yegor256/takes/issues/1067

**Comment by paulodamaso** [comment]
@0crat in

**Comment by paulodamaso** [comment]
@0crat assign @yegor256

**Comment by paulodamaso** [comment]
@yegor256 could you please check takes permissions in https://travis-ci.com/ ?

**Comment by 0crat** [comment]
Job was finished in 0 hours, bonus for fast delivery is possible (see [§36](http://www.zerocracy.com/policy.html#36))
