### ISSUE TITLE
Why is JsonStructure required when it is part of Java EE?

### ISSUE THREAD

**Issue by leroneb** [yegor256/takes#1089]
![image](https://user-images.githubusercontent.com/7648662/105096508-2e561900-5a75-11eb-937d-e869182c82de.png)
The unimplemented method the error is talking about is:  JsonStructure toJson() throws IOException;

I am trying to build a Json response but I can't get past this phase when implementing RsJson.Source. Is there a right way to do this?

**Comment by andreoss** [comment]
@leroneb It's likely due to the way `takes` handles dependencies. 
https://github.com/yegor256/takes/blob/master/pom.xml#L92

`javax.*` dependencies are marked `provided` as well (should they be?)

**Comment by yegor256** [comment]
@leroneb indeed, we expect Json Java implementation to be provided by your classpath. Just add these two dependencies to your POM and you will be fine:

```
    <dependency>
      <groupId>javax.json</groupId>
      <artifactId>javax.json-api</artifactId>
      <version>1.1.4</version>
    </dependency>
    <dependency>
      <groupId>org.glassfish</groupId>
      <artifactId>javax.json</artifactId>
      <version>1.1.4</version>
    </dependency>
```

**Comment by 0crat** [comment]
Job `gh:yegor256/takes#1089` is not assigned, can't get performer
