### ISSUE TITLE
CharSequence instead of String

### ISSUE THREAD

**Issue by yegor256** [yegor256/takes#109]
Let's make sure all constructors in `org.takes.rs` package accept `CharSequence` instead of `String`, for higher flexibility

**Comment by davvd** [comment]
@yegor256 thanks, I added the "bug" tag

**Comment by davvd** [comment]
@d-molotchko this task is for you, keep [these principles](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html) in mind, and don't hesitate to ask any technical questions. Task's budget is **30 mins** (see [this](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html) for explanation)

**Comment by davvd** [comment]
@yegor256 thanks for the ticket, your account was topped for 15 mins, payment 000-b43ea349

**Comment by YamStranger** [comment]
I can do it with https://github.com/yegor256/takes/issues/110

**Comment by d-molotchko** [comment]
@davvd please reassign this task to another dev. thanks.

**Comment by YamStranger** [comment]
I can do this task )

**Comment by yegor256** [comment]
@davvd please assign @YamStranger to this

**Comment by davvd** [comment]
> @davvd please assign @YamStranger to this

@yegor256 yep, done. @yamstranger it is your task now

**Comment by YamStranger** [comment]
@davvd  please look at pull request #181 and assign reviewer

**Comment by YamStranger** [comment]
@yegor256 please close issue

**Comment by yegor256** [comment]
@YamStranger thanks!

**Comment by davvd** [comment]
@yegor256 there is no milestone yet, so I set it to `1.0`

**Comment by davvd** [comment]
@elenavolokhova please, let us know what do you think about this ticket, according to our [QA rules](http://www.teamed.io/qa.html)

**Comment by elenavolokhova** [comment]
@YamStranger 
>YamStranger commented 11 days ago
I can do this task )

According to our [quality rules](http://www.teamed.io/qa.html):
 > Messages in a ticket always start with a name of a user they are addressed to.
  
 Please avoid such issues in future and confirm that everything is clear and you have no questions regarding this approach.

**Comment by YamStranger** [comment]
@elenavolokhova  fixed. Thanks

**Comment by elenavolokhova** [comment]
@YamStranger Thank you!

**Comment by elenavolokhova** [comment]
@davvd Quality is acceptable.

**Comment by davvd** [comment]
> @davvd Quality is acceptable.

@elenavolokhova thank you, let's try to make it "good" next time

**Comment by YamStranger** [comment]
@davvd please share details of payment for this issue

**Comment by davvd** [comment]
@yamstranger just added 10 mins to @elenavolokhova (for QA), payment ID is `55958139`

I just added **1 hour** to your account, many thanks for your contribution.. 55958180 spent here

the bonus for fast delivery (age=8)

added +60 to your rating, now it is equal to [+136](http://www.netbout.com/b/35267?open=rating)
