### ISSUE TITLE
RsJson Useless from version 1.11 to 1.19

### ISSUE THREAD

**Issue by leroneb** [yegor256/takes#1090]
https://github.com/yegor256/takes#rsjson

I tried setting up a class using RsJson but createObjectBuilder() no longer works. I think it would be useful to say what version of the code the documentation is referring to.

**Comment by yegor256** [comment]
@leroneb should be OK now, since we upgraded all dependencies to the latest versions, including `json`

**Comment by 0crat** [comment]
Job `gh:yegor256/takes#1090` is not assigned, can't get performer
