### ISSUE TITLE
PsTwitter

### ISSUE THREAD

**Issue by yegor256** [yegor256/takes#11]
Let's create a new `Pass` for Twitter OAuth authentication, call it `PsTwitter`, similar to `PsGithub` we already have

**Comment by davvd** [comment]
@yegor256 got it, tag `bug` is here

**Comment by davvd** [comment]
@yegor256 many thanks for the bug report, I added 15 mins to your acc, transaction `000-88c6467f`

**Comment by davvd** [comment]
@popprem can you please help? Keep in mind [this](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html). If you have any technical questions, don't hesitate to ask right here... The cost of this task is **30 mins** (this is exactly how much will be paid, not less not more), when the task is [done](http://www.xdsd.org/2014/04/15/definition-of-done.html)

**Comment by popprem** [comment]
@davvd waiting till #148 is fixed to run the build in windows.

**Comment by YamStranger** [comment]
@yegor256. @davvd you can not wait for me. You can do next: set global .gitattributes file(download it from my commits,  "git config --global core.attributesfile file_path") -it will apply to all repositories, where .gitattributes file not exists. Next time when you clone (may for checkout too, I am not sure) git will apply correct end line char (\n) to repository, and files on them and gulice will be happy.

**Comment by davvd** [comment]
@popprem you're holding this ticket for 18 days already. If it is not finished (and closed) in the next 40 hours, it will be re-assigned to someone else, see [No Obligations](http://www.xdsd.org/2014/04/13/no-obligations-principle.html) principle ([this article](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html) should help if you're stuck). -30 to your rating, your total score is [-120](http://www.netbout.com/b/35169?open=rating)

**Comment by popprem** [comment]
@davvd already fixed and pull request #175 created for the same. Waiting for the review.

**Comment by davvd** [comment]
@yegor256 I added milestone `1.0` to this issue, let me know if there has to be something else

**Comment by davvd** [comment]
@popprem this task is taking too long, I have to change the performer, sorry. Please stop working with it right now. See our [no obligations](http://www.xdsd.org/2014/04/13/no-obligations-principle.html) principle

added -60 to your rating, now it is equal to [-180](http://www.netbout.com/b/35169?open=rating)

**Comment by davvd** [comment]
@erimerturk this task is for you, keep [these principles](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html) in mind, and don't hesitate to ask any technical questions; The budget of this task is **30 mins**. This is exactly how much time will be compensated, when the task is completed. Read about our [Definition of Done](http://www.xdsd.org/2014/04/15/definition-of-done.html)

**Comment by erimerturk** [comment]
@davvd this issue fix have already merged to master. I think it is fixed. Could you check this issue please.

**Comment by davvd** [comment]
@yegor256 the code made here contains a puzzle `11-790c0445`, which will be resolved soon

**Comment by popprem** [comment]
@davvd As mentioned before PR #175 is for this issue and it has been closed already.

**Comment by erimerturk** [comment]
@yegor256 can you review and close it , if it is acceptable ?

**Comment by yegor256** [comment]
@erimerturk thanks

**Comment by davvd** [comment]
@elenavolokhova please, let us know what do you think about this ticket, according to our [QA rules](http://www.teamed.io/qa.html)

**Comment by elenavolokhova** [comment]
@yegor256 @davvd This issue is assigned to incorrect person. @popprem fixed it and created PR. No work was done by @erimerturk. Please fix the assignment or advise what should be done here to fix the situation.

**Comment by yegor256** [comment]
@davvd quality is bad here

**Comment by elenavolokhova** [comment]
@yegor256 Thank you!

**Comment by erimerturk** [comment]
@yegor256  as @elenavolokhova  said i didn't do anything for this issue. I have already asked to @davvd  11 days ago. Can you fix the assignment confusion please ?

**Comment by yegor256** [comment]
@erimerturk it's OK, you won't get a payment here

**Comment by erimerturk** [comment]
@yegor256 i am worrying about my rating not payment :) thank you

**Comment by davvd** [comment]
> @davvd quality is bad here

@yegor256 thanks a lot, noticing bad quality is what makes us better

**Comment by elenavolokhova** [comment]
@yegor256 Should QA review be paid for this one?

**Comment by yegor256** [comment]
@davvd pls add extra 10 mins to @elenavolokhova

**Comment by davvd** [comment]
> @davvd pls add extra 10 mins to @elenavolokhova 

@yegor256 I've sent 10 mins extra to @elenavolokhova in transaction ID "57686658"

**Comment by davvd** [comment]
@yegor256 the last puzzle `11-790c0445`/#230 originated from here solved
