### ISSUE TITLE
CharSequence instead of String for request parsers

### ISSUE THREAD

**Issue by yegor256** [yegor256/takes#110]
Let's make sure all methods in classes in `org.takes.rq` package accept `CharSequence` instead of `String`, for higher flexibility

**Comment by davvd** [comment]
@yegor256 got it, tag `bug` is here

**Comment by davvd** [comment]
@yamstranger could you please pick this up? This [article](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html) explains how we work. Any technical questions you may ask right here; Total fixed cost of this task is **30 mins** (see [this](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html) for more info)

**Comment by YamStranger** [comment]
@davvd yes, thanks

**Comment by davvd** [comment]
@yegor256 many thanks for the bug report, I added 15 mins to your acc, transaction `000-5b878e8e`

**Comment by YamStranger** [comment]
@yegor256 fix is ready. I created pull request

**Comment by yegor256** [comment]
@YamStranger for convenience, please post the number of pull request here

**Comment by YamStranger** [comment]
@yegor256 pull request #128

**Comment by YamStranger** [comment]
@yegor256 issue delivered

**Comment by yegor256** [comment]
@YamStranger thanks!

**Comment by davvd** [comment]
@elenavolokhova please, let us know what do you think about this ticket, according to our [QA rules](http://www.teamed.io/qa.html)

**Comment by elenavolokhova** [comment]
@davvd Ticket passed QA review. It looks good.

**Comment by davvd** [comment]
> @davvd Ticket passed QA review. It looks good.

@elenavolokhova thank you, good quality is always good :)

**Comment by davvd** [comment]
@yamstranger 10 mins was added to the account of @elenavolokhova (for QA review), in transaction 55062896... Much obliged! I have added **38 mins** to your account in payment "55062930", 64 hours and 21 mins spent... age=2945, that's why a bonus here for fast delivery... +38 added to your rating, at the moment it is: [+38](http://www.netbout.com/b/35267?open=rating)
