### ISSUE TITLE
CopyBytesUntilBoundaryTest.java:49-51: We introduced a...

### ISSUE THREAD

**Issue by 0pdd** [yegor256/takes#1108]
The puzzle `997-5bcbe378` from #997 has to be resolved: 

https://github.com/yegor256/takes/blob/622eeefe0909a21ebe4ae0aed3e39d6bc3b09176/src/test/java/org/takes/rq/multipart/CopyBytesUntilBoundaryTest.java#L49-L51

The puzzle was created by Olivier B. OURA on 17-Apr-21. 

Estimate: 30 minutes,  role: DEV. 

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0pdd** [comment]
The puzzle `997-5bcbe378` has disappeared from the source code, that's why I closed this issue.

**Comment by 0crat** [comment]
@sereshqua[/z](https://www.0crat.com/u/sereshqua) please review this job completed by @baudoliver7[/z](https://www.0crat.com/u/baudoliver7), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed
