### ISSUE TITLE
Frequent releases help fixing issue(s) that doesn't work

### ISSUE THREAD

**Issue by piotrkot** [yegor256/takes#1109]
Can you make releases more frequent? The most recent one is from on Jan 26, 2019 while you regularly fix bugs on weekly basis.

**Comment by piotrkot** [comment]
Or maybe you could even make one, say, now?

**Comment by yegor256** [comment]
@piotrkot duly noted! will release more frequently

**Comment by 0crat** [comment]
Job `gh:yegor256/takes#1109` is not assigned, can't get performer
