### ISSUE TITLE
Fix AppVeyor ci

### ISSUE THREAD

**Issue by baudoliver7** [yegor256/takes#1111]
AppVeyor ci fails because [maven link](http://www.us.apache.org/dist/maven/maven-3/3.2.5/binaries/apache-maven-3.2.5-bin.zip) is no more available.

The current available link is : https://repo.maven.apache.org/maven2/org/apache/maven/apache-maven/3.2.5/apache-maven-3.2.5-bin.zip

**Comment by baudoliver7** [comment]
@yegor256 please, could you assign to me this issue ?

**Comment by 0crat** [comment]
Are you speaking to me or about me [here](https://github.com/yegor256/takes/issues/1111#issuecomment-983076532); you must always start your message with my name if you want to address it to me, see [§1](http://www.zerocracy.com/policy.html#1)

**Comment by yegor256** [comment]
@0crat assign @baudoliver7
