### ISSUE TITLE
pom.xml:317-319: There are 18 tests that fail now, mostly...

### ISSUE THREAD

**Issue by 0pdd** [yegor256/takes#1113]
The puzzle `1110-00e4d7db` from #1110 has to be resolved: 

https://github.com/yegor256/takes/blob/72f09dd348a86f566fd627681e7d30489f83c148/pom.xml#L317-L319

The puzzle was created by @yegor256 on 14-Nov-21. 

Estimate: 60 minutes,  role: DEV. 

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0pdd** [comment]
The puzzle `1110-00e4d7db` has disappeared from the source code, that's why I closed this issue.

**Comment by 0crat** [comment]
Job `gh:yegor256/takes#1113` is not assigned, can't get performer
