### ISSUE TITLE
RqMultipart is not tested properly

### ISSUE THREAD

**Issue by yegor256** [yegor256/takes#112]
Let's add more unit test methods into `RqMultipartTest` with some edge cases, in order to make sure the class works properly in "all" possible situations.

**Comment by davvd** [comment]
@yegor256 sure, thanks, I added bug tag to it

**Comment by davvd** [comment]
@ekondrashev this task is for you, keep [these principles](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html) in mind, and don't hesitate to ask any technical questions. This task's budget is **30 mins**. This is exactly how much will be paid when the problem explained above is solved. See [this](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html) for more information

**Comment by ekondrashev** [comment]
@davvd could you please let me know how to proceed with this issue? 
Is creation of pull request enough from my side?
https://github.com/yegor256/takes/pull/118

**Comment by davvd** [comment]
@yegor256 many thanks for the report, I topped your account for 15 mins, transaction 000-be425d22

**Comment by davvd** [comment]
@yegor256 I added milestone `1.0` to this issue, let me know if there has to be something else

**Comment by davvd** [comment]
@ekondrashev you're holding this ticket for 15 days already. If it is not finished (and closed) in the next 48 hours, it will be re-assigned to someone else, see [No Obligations](http://www.xdsd.org/2014/04/13/no-obligations-principle.html) principle ([this article](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html) should help if you're stuck); -30 added to your rating, current score is: [-15](http://www.netbout.com/b/35260?open=rating)

**Comment by ekondrashev** [comment]
@davvd could you please let me know what should I do next after the PR is close for the initial task?
PR https://github.com/yegor256/takes/pull/118

**Comment by yegor256** [comment]
@ekondrashev you should ask ticket reporter to close it

**Comment by ekondrashev** [comment]
@yegor256 please close the ticket the solution is provided at https://github.com/yegor256/takes/pull/118

**Comment by yegor256** [comment]
@ekondrashev thanks!

**Comment by davvd** [comment]
@elenavolokhova please, review this task for compliance with our [quality rules](http://www.teamed.io/qa.html)

**Comment by elenavolokhova** [comment]
@davvd This issue is good.

**Comment by davvd** [comment]
> @davvd This issue is good.

@elenavolokhova thanks for the review

**Comment by davvd** [comment]
@ekondrashev just added 10 mins to @elenavolokhova (for QA), payment ID is `55950410`. Thanks so much! Your account was topped up for **38 mins** (transaction ID is `55950439`, the task took 408 hours and 56 mins). there is a bonus for fast delivery (age=2970). +38 to your rating, your total score is [-7](http://www.netbout.com/b/35260?open=rating)
