### ISSUE TITLE
RsWithHeaders must reuse RsWithHeader

### ISSUE THREAD

**Issue by yegor256** [yegor256/takes#113]
Decorator `RsWithHeaders` must NOT implement header adding from scratch. Instead, it has to use `RsWithHeader`. Let's refactor it accordingly.

**Comment by davvd** [comment]
@yegor256 sure, thanks, I added bug tag to it

**Comment by davvd** [comment]
@eg04lt3r could you please pick this up? This [article](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html) explains how we work. Any technical questions you may ask right here... Budget here is **30 mins** (keep [this principle](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html) in mind)

**Comment by davvd** [comment]
@yegor256 many thanks, **15 mins** added to your acc for reporting this bug, pmt ID `000-f35bf996`

**Comment by eg04lt3r** [comment]
@yegor256 Should i refactor others classes which using this decorator?

**Comment by yegor256** [comment]
@eg04lt3r as far as I see, they won't be affected anyhow. you just change the internal implementation of `RqWithHeaders`. none of its clients will know about this refactoring

**Comment by eg04lt3r** [comment]
@yegor256 please, clarify what should I do, cause this class allow setup headers as strings and using them in internal method head. According to your last comment i should not change constructor arguments.

**Comment by yegor256** [comment]
@eg04lt3r we should change the implementation of `RsWithHeaders`, not its interface. All ctors should stay the same, but the way we implement this extension of Response object should be changed. At the moment, there is an obvious code duplication in `RsWithHeader` and `RsWithHeaders`, I'm sure you see it. We should get rid of that and make sure `RsWithHeaders` is calling `RsWithHeader` to actually extend the `Response` object.

**Comment by davvd** [comment]
@yegor256 attached this issue to milestone "1.0" (let me know if this is wrong)

**Comment by davvd** [comment]
@eg04lt3r the task is your hands for the last 15 days.. keep in mind that if it's not closed in the next 48 hours, it will be re-assigned to someone else, see [No Obligations](http://www.xdsd.org/2014/04/13/no-obligations-principle.html) principle. [This article](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html) should help if you're stuck; -30 to your rating, your total score is [-22](http://www.netbout.com/b/35234?open=rating)

**Comment by eg04lt3r** [comment]
@yegor256 fixed in #207 pull request. Please, find someone to review. Thanks.

**Comment by davvd** [comment]
@eg04lt3r you've been working with this task for too long. I'm sorry, but I'll assign someone else. Please stop working with it. See our [no obligations](http://www.xdsd.org/2014/04/13/no-obligations-principle.html) principle; added -60 to your rating, now it is equal to [-142](http://www.netbout.com/b/35234?open=rating)

**Comment by davvd** [comment]
@dmzaytsev the task is yours please proceed

**Comment by dmzaytsev** [comment]
@davvd the PR for this task here #210
Please find someone for review. Thanks

**Comment by dmzaytsev** [comment]
@davvd we need more time [see details here](https://github.com/yegor256/takes/pull/210#issuecomment-97664820)

**Comment by davvd** [comment]
> @davvd we need more time [see details here](https://github.com/yegor256/takes/pull/210#issuecomment-97664820)
> 

@dmzaytsev sure, thanks for telling me, take your time

**Comment by dmzaytsev** [comment]
@yegor256 the PR #210 has been merged. 
please close the task

**Comment by yegor256** [comment]
@dmzaytsev thanks!

**Comment by davvd** [comment]
@elenavolokhova please, let us know what do you think about this ticket, according to our [QA rules](http://www.teamed.io/qa.html)

**Comment by elenavolokhova** [comment]
@davvd It looks good!

**Comment by davvd** [comment]
> @davvd It looks good!

@elenavolokhova thanks, got it, great to see high-quality tickets here

**Comment by davvd** [comment]
@dmzaytsev just added 10 mins to @elenavolokhova (for QA), payment ID is `56870843`... **38 mins** added to your account (payment number `56870848`), many thanks for your contribution! 278 hours and 1 min spent here.... age=2970, that's why a bonus here for fast delivery... +38 to your rating, your total score is [+1250](http://www.netbout.com/b/35166?open=rating)
