### ISSUE TITLE
RsWithHeader doesn't validate header correctness

### ISSUE THREAD

**Issue by yegor256** [yegor256/takes#114]
`RsWithHeader` must validate header validity, through some regular expression. At the moment, we let any header to go into the response, which is error-prone. We should validate it, using some regular expression, according to the proper RFC.

**Comment by davvd** [comment]
@yegor256 right, I added the `bug` tag

**Comment by davvd** [comment]
@yamstranger this ticket is yours now, please proceed, and keep in mind [this](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html). Any technical questions you should ask right here... **30 mins** is the budget of the task. This is exactly how much will be paid when the problem is [solved](http://www.xdsd.org/2014/04/15/definition-of-done.html) (no matter how much time you will actually spend). See [this](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html) for more information

**Comment by YamStranger** [comment]
Do we have any documentation about this? Or some rules?

**Comment by yegor256** [comment]
@YamStranger all we have is in README.md file. If any questions, don't hesitate to ask, but remember: http://www.yegor256.com/2015/02/16/it-is-not-a-school.html

**Comment by davvd** [comment]
@yegor256 thanks for the report, I topped your acc for 15 mins, payment ID `000-2f91ca68`

**Comment by YamStranger** [comment]
@yegor256 I take it, Thanks

**Comment by YamStranger** [comment]
@yegor256 please look at pull request #143

**Comment by YamStranger** [comment]
@yegor256 As I see pull request #143  merged long time ago, but this issue is still open. Is some problem with it?

**Comment by YamStranger** [comment]
@yegor256 please close this issue

**Comment by yegor256** [comment]
@YamStranger thanks!

**Comment by davvd** [comment]
@yegor256 since there is no milestone yet I set it to "1.0"

**Comment by davvd** [comment]
@elenavolokhova please, review this ticket for compliance with our [QA rules](http://www.teamed.io/qa.html)

**Comment by elenavolokhova** [comment]
@YamStranger 
>YamStranger commented 17 days ago
Do we have any documentation about this? Or some rules?

Please, fix this comment. It should mention the person you are talking to.

**Comment by YamStranger** [comment]
@elenavolokhova done

**Comment by elenavolokhova** [comment]
@YamStranger Thank you!

**Comment by elenavolokhova** [comment]
@davvd Ticket passed QA review. Quality is acceptable.

**Comment by davvd** [comment]
> @davvd Ticket passed QA review. Quality is acceptable.

@elenavolokhova thank you, let's try to make it "good" next time

**Comment by davvd** [comment]
@yamstranger just added 10 mins to @elenavolokhova (for QA), payment ID is `55839514`... thanks, paid, **38 mins** to your account, payment ID is `55839570`, task took 352 hours and 28 mins to complete... the bonus for fast delivery (age=2970)... +38 to your rating, your total score is [+76](http://www.netbout.com/b/35267?open=rating)
