### ISSUE TITLE
RqMultipart may lead to out-of-memory

### ISSUE THREAD

**Issue by yegor256** [yegor256/takes#115]
Current implementation of `RqMultipart` can easily lead to out-of-memory situation, if big files will be uploaded by many users at the same time. The class is consuming an entire request into memory and then parses it. Let's try to fix that and use something else, maybe a temp file instead.

**Comment by davvd** [comment]
@yegor256 thanks, I added the "bug" tag

**Comment by davvd** [comment]
@d-molotchko could you please pick this up? This [article](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html) explains how we work. Any technical questions you may ask right here. Total fixed cost of this task is **30 mins** (see [this](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html) for more info)

**Comment by davvd** [comment]
@yegor256 many thanks, **15 mins** added to your acc for reporting this bug, pmt ID `000-803cee63`

**Comment by d-molotchko** [comment]
@davvd please reassign this task to another dev. thanks.

**Comment by yegor256** [comment]
@davvd give this to somebody else

**Comment by davvd** [comment]
> @davvd give this to somebody else

@yegor256 all right, we'll find someone else for this task

**Comment by davvd** [comment]
@yegor256 there is no milestone yet, so I set it to `1.0`

**Comment by davvd** [comment]
@erimerturk this task is for you, keep [these principles](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html) in mind, and don't hesitate to ask any technical questions. The cost of this task is **30 mins** (this is exactly how much will be paid, not less not more), when the task is [done](http://www.xdsd.org/2014/04/15/definition-of-done.html)

**Comment by yegor256** [comment]
@erimerturk I will implement this myself, if you don't mind

**Comment by yegor256** [comment]
@davvd assign me to this ticket pls

**Comment by yegor256** [comment]
@rultor release, tag is `0.14.1`

**Comment by erimerturk** [comment]
@yegor256 why did you reopen ?

**Comment by davvd** [comment]
> @davvd assign me to this ticket pls

@yegor256 right, this task is yours, whoever worked before, please stop right now

**Comment by yegor256** [comment]
@erimerturk by mistake, it's solved indeed

**Comment by davvd** [comment]
@elenavolokhova please, review this ticket for compliance with our [QA rules](http://www.teamed.io/qa.html)

**Comment by elenavolokhova** [comment]
@yegor256
 According to our [quality rules](http://www.teamed.io/qa.html):
 >Problem reporter and problem solver are two different persons.
 
 This was not a case in this ticket. 
 Please confirm that you will avoid fixing your own issues.

**Comment by elenavolokhova** [comment]
@yegor256 I still need your acknowledgement to close this ticket.

**Comment by yegor256** [comment]
@elenavolokhova yes, you're right, I did it wrong. I understand. thanks.

**Comment by elenavolokhova** [comment]
@davvd Quality is acceptable.

**Comment by davvd** [comment]
> @davvd Quality is acceptable.

@elenavolokhova thanks for the review, we'll try better next time

**Comment by davvd** [comment]
@yegor256 I added 10 mins to @elenavolokhova (for QA review) in transaction 56869543; I added **45 mins** to your account, many thanks for working with the project! The completion time here was 000-1f78195a.; there is a bonus for fast delivery (m=1470); +45 added to your rating, current score is: [+8814](http://www.netbout.com/b/35008?open=rating)
