### ISSUE TITLE
TsLogged.java:38-42: This class not implemented yet,...

### ISSUE THREAD

**Issue by davvd** [yegor256/takes#119]
Puzzle `28-4e517112` in `src/main/java/org/takes/facets/slf4j/TsLogged.java:38-42` has to be resolved: This class not implemented yet, but has to be. Please implement it like TkLogged and don't forget about unit tests. In addition, need to be implement classes BkLogged, FtLogged, PsLogged which will make loggable interfaces Back, Front, Pass. They should all be implemented also like TkLogged.... The puzzle was created by Dmitry Zaytsev on 1-Apr-2015.

If you have any technical questions, don't ask me, submit new tickets instead

**Comment by davvd** [comment]
@dmzaytsev the task is yours, please go ahead

**Comment by davvd** [comment]
I'm closing the issue...

**Comment by davvd** [comment]
@dmzaytsev I'm not sure who actually completed this task, since there were no messages from you above (correct me if I'm wrong)

**Comment by dmzaytsev** [comment]
@davvd I referenced the PR #122 above...
@yegor256 [said](https://github.com/yegor256/takes/pull/122#issuecomment-89841751) that this ticket will be closed automatically so I don't asked to close the task here. I'll keep in mind in the future ask to close a task in any case.

**Comment by dmzaytsev** [comment]
@davvd According to our [quality rules](http://www.teamed.io/qa.html):
>Messages in a ticket always start with a name of a user they are addressed to.

please fix your messages, thank you

**Comment by davvd** [comment]
@dmzaytsev fixed, see above

**Comment by dmzaytsev** [comment]
@davvd could you please schedule QA review for the task? thank you

**Comment by yegor256** [comment]
@davvd please add extra 30 mins to @dmzaytsev

**Comment by davvd** [comment]
> @davvd please add extra 30 mins to @dmzaytsev 

@yegor256 I've paid 30 mins to @dmzaytsev in transaction `55563585`
