### ISSUE TITLE
PsLinkedin

### ISSUE THREAD

**Issue by yegor256** [yegor256/takes#12]
Let's create a new `Pass` for LinkedIn authentication, call it `PsLinkedin`, similar to `PsGithub` we already have

**Comment by davvd** [comment]
@yegor256 thanks, I added the "bug" tag

**Comment by yegor256** [comment]
@davvd assign this to me

**Comment by davvd** [comment]
> @davvd assign this to me

@yegor256 of course, the task is yours, go ahead

**Comment by davvd** [comment]
> @davvd assign this to me

@yegor256 in the future, try to avoid assigning yourself to your own tasks

**Comment by davvd** [comment]
@yegor256 thanks for the report, I topped your acc for 15 mins, payment ID `000-67068c64`

**Comment by yegor256** [comment]
@davvd assign someone else pls

**Comment by yegor256** [comment]
we can use this class as an example: https://github.com/yegor256/rexsl/blob/master/src/main/java/com/rexsl/page/auth/LinkedIn.java

**Comment by davvd** [comment]
> @davvd assign someone else pls

@yegor256 got it, someone else will be assigned soon

**Comment by davvd** [comment]
@dmzaytsev please go ahead with this task, it's yours

**Comment by dmzaytsev** [comment]
@yegor256  the PR #116 merged
take a look at the changes, if you accept it, close the task please, thank you

**Comment by yegor256** [comment]
thanks!

**Comment by davvd** [comment]
there is a puzzle in this code `12-159d303e`, we'll resolve it later

**Comment by davvd** [comment]
@elenavolokhova please, let us know what do you think about this ticket, according to our [QA rules](http://www.teamed.io/qa.html)

**Comment by elenavolokhova** [comment]
@yegor256 @davvd Please don't forget to address your comments.

**Comment by elenavolokhova** [comment]
@dmzaytsev 
>davvd commented 4 days ago
there is a puzzle in this code 12-159d303e, we'll resolve it later

>yegor256 commented 5 days ago
thanks!

>yegor256 commented 8 days ago
we can use this class as an example: https://github.com/yegor256/rexsl/blob/master/src/main/java/com/rexsl/page/auth/LinkedIn.java

 According to our [quality rules](http://www.teamed.io/qa.html):
 > Messages in a ticket always start with a name of a user they are addressed to.
 
 As far as you are the performer of this ticket you are responsible for its quality. Please make sure that everyone follows this rule in your tickets in the future.
 
 Please confirm that everything is clear and you have no questions regarding this approach.

**Comment by dmzaytsev** [comment]
@elenavolokhova I confirm

**Comment by dmzaytsev** [comment]
@davvd @yegor256 According to our [quality rules](http://www.teamed.io/qa.html):
>Messages in a ticket always start with a name of a user they are addressed to.

please fix your messages, thank you

**Comment by elenavolokhova** [comment]
@dmzaytsev Your confirmation is enough here. Let's prevent this in the future. Thank you!

**Comment by elenavolokhova** [comment]
@davvd Ticket passed QA review. Quality is acceptable.

**Comment by davvd** [comment]
> @davvd Ticket passed QA review. Quality is acceptable.

@elenavolokhova thanks for the QA review, we'll work better next time

**Comment by davvd** [comment]
@dmzaytsev 10 mins was added to the account of @elenavolokhova (for QA review), in transaction 55479416

**38 mins** added to your account (payment number `55479447`), many thanks for your contribution! 65 hours and 53 mins spent here.

the bonus for fast delivery (age=2970)

+38 added to your rating, current score is: [+392](http://www.netbout.com/b/35166?open=rating)

**Comment by davvd** [comment]
@yegor256 the last puzzle `12-159d303e`/#158 originated from here solved
