### ISSUE TITLE
RqFake equals does not work as expected 

### ISSUE THREAD

**Issue by ekondrashev** [yegor256/takes#120]
When several RqFake objects inited with the same head and body they return false on equals call, please see the test

```
package org.takes.rq;

import com.google.common.base.Joiner;
import org.junit.Assert;
import org.junit.Test;
import java.util.Arrays;
import java.util.List;

/**
 * Created by ekondrashev on 4/4/15.
 */
public class RqFakeTest {
    
    
    @Test
    public void equalsTrue() {
        List<String> head = Arrays.asList(
                "POST /h?a=3 HTTP/1.1",
                "Host: www.example.com",
                "Content-Type: multipart/form-data; boundary=AaB03x",
                "Content-Length: 10000"
        );
        String body = Joiner.on("\r\n").join(
                "--AaB03x",
                "Content-Disposition: form-data; name=\"address\"",
                "",
                "440 N Wolfe Rd, Sunnyvale, CA 94085",
                "--AaB03x",
                // @checkstyle LineLength (1 line)
                "Content-Disposition: form-data; name=\"data\"; filename=\"a.bin\"",
                "Content-Transfer-Encoding: utf-8",
                "",
                "\r\t\n\u20ac\n\n\n\t\r\t\n\n\n\r\nthe end",
                "--AaB03x--"
        );
        Assert.assertEquals(new RqFake(head, body), new RqFake(head, body));
    }
}
```

Result
```
java.lang.AssertionError: 
Expected :org.takes.rq.RqFake@364e3420
Actual   :org.takes.rq.RqFake@4821fa36
```

**Comment by davvd** [comment]
I will find a developer for the task soon...

**Comment by davvd** [comment]
@dmzaytsev please proceed, it's yours

**Comment by dmzaytsev** [comment]
@davvd assign someone else please

**Comment by davvd** [comment]
> @davvd assign someone else please

@dmzaytsev I will ask somebody else to pick this up

**Comment by davvd** [comment]
@d-molotchko this ticket is yours now, please proceed, and keep in mind [this](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html). Any technical questions you should ask right here... Total fixed cost of this task is **30 mins** (see [this](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html) for more info)

**Comment by davvd** [comment]
@ekondrashev thanks a lot for reporting, **15 mins** added to your acc, pmt ID `54711363`

**Comment by d-molotchko** [comment]
@davvd please reassign this task to another dev. thanks.

**Comment by ekondrashev** [comment]
@yegor256 
This is actually a generic problem having anonymous classes passed as origin to the wrap-like classes.

I wrote a little test for `TkWithTypeTest` which actually implemented with anonymous class underneath also:
```java
/**
 * Test case for {@link Class}.
 *
 * @author Eugene Kondrashev (eugene.kondrashev@gmail.com)
 * @version $Id$
 * @since 0.31.1
 */
public final class TkWithTypeTest {

    /**
     * TkWithType can satisfy equals contract.
     * @throws IOException if some problem inside
     */
    @Test
    public void satisfiesEqualsContract() throws IOException {
        final TkEmpty take = new TkEmpty();
        final String type = "image/gif";
        MatcherAssert.assertThat(
                new TkWithType(take, type),
                Matchers.equalTo(new TkWithType(take, type))
        );
    }
}
```

The class itself:
```java
@EqualsAndHashCode(callSuper = true)
public final class TkWithType extends TkWrap {

    /**
     * Ctor.
     * @param take Original take
     * @param type Content type
     */
    public TkWithType(final Take take, final String type) {
        super(
            new Take() {
                @Override
                public Response act(final Request req) throws IOException {
                    return new RsWithType(take.act(req), type);
                }
            }
        );
    }

}
```

**Comment by yegor256** [comment]
@davvd assign me here pls

**Comment by davvd** [comment]
> @davvd assign me here pls

@yegor256 of course, the task is yours, go ahead

**Comment by davvd** [comment]
@ekondrashev I set milestone here to `1.0`, let me know if it is wrong

**Comment by yegor256** [comment]
@davvd assign someone else pls

**Comment by davvd** [comment]
> @davvd assign someone else pls

@yegor256 I deducted 30 points from your rating

**Comment by davvd** [comment]
> @davvd assign someone else pls

@yegor256 no problem, I will try to find somebody else

**Comment by davvd** [comment]
@bdragan this ticket is yours now, please proceed, and keep in mind [this](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html). Any technical questions you should ask right here... Total fixed cost of this task is **30 mins** (see [this](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html) for more info)

**Comment by bdragan** [comment]
@davvd PR #404 created and ready for review.

**Comment by bdragan** [comment]
@davvd This resolution of this issue is currently blocked by #403.

**Comment by davvd** [comment]
> @davvd PR #404 created and ready for review.

@bdragan thnaks

**Comment by bdragan** [comment]
@davvd PR #404 has been merged to master.

**Comment by davvd** [comment]
> @davvd @ekondrashev PR #404 has been merged to master.

@bdragan you should ask ticket author to close it, see http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html

**Comment by ekondrashev** [comment]
@bdragan the solution you've provided works for this particular case. But there are bunch of places where the same issue is relevant(basically each time anonymous class is created). I'd suggest creating separate defect to handle this issue. 
@davvd wdyt?

**Comment by bdragan** [comment]
@ekondrashev I agree in general. This issue fixes only `RqFake` case because it is meant to be used in tests, and checks for equality relying on `equals` method are a convenient way to perform assertions in the tests. I also find this a valid use case you reported in this issue.

However, it does not make sense to compare all `Request`s with each other. For example, checking for equality of two `RqSimple` instances would probably involve comparing the two contained `InputStream`s, which is of no practical value imho.

**Comment by ekondrashev** [comment]
@bdragan it is not about `Request`, but rather about the situation when we pass any anonymous class and expect equals/hashCode to work properly. So it is an issue that can appear anytime one uses a combinationof lombok and anonymous classes. This issue is dangerous enough doe to having this common nature, see?

**Comment by bdragan** [comment]
@ekondrashev Agree, issue #408 created. Please review it and close this issue if you feel that it provides a solution for the use case described here.

**Comment by ekondrashev** [comment]
@bdragan thank you!

**Comment by davvd** [comment]
@elenavolokhova please, review this issue for QA compliance, as per [par.24](http://www.teamed.io/policy.html#24)

**Comment by elenavolokhova** [comment]
@bdragan 
 According to our [quality rules](http://www.teamed.io/qa.html):
 >The ticket describes one specific problem and provides a single solution.
 
 Two PRs were created for this issue. Please try to follow this rule in your tickets in the future.
 
 Please confirm that everything is clear and you have no questions regarding this approach.

**Comment by bdragan** [comment]
@elenavolokhova Only PR #404 were created for this issue. Which is the other one?

**Comment by elenavolokhova** [comment]
@bdragan You are right. Sorry, I missed that #408 is an issue, not a PR.

**Comment by elenavolokhova** [comment]
@davvd Quality is good here.

**Comment by davvd** [comment]
> @davvd Quality is good here.

@elenavolokhova thank you

**Comment by davvd** [comment]
@bdragan I added 10 mins to @elenavolokhova (for QA review) in transaction 67492743... Many thanks! **38 mins** were added to your account in Transaction ID `67492758` (task took 197 hours and 16 mins)... age=4129, that's why a bonus here for fast delivery... +38 added to your rating, current score is: [+83](http://www.netbout.com/b/35709?open=rating)
