### ISSUE TITLE
String representation of the Request

### ISSUE THREAD

**Issue by dmzaytsev** [yegor256/takes#121]
I expect implementations of the Request interface will be able convert itself to a loggable string but they don't have this feature

**Comment by davvd** [comment]
@yegor256 please pay attention to this issue

**Comment by yegor256** [comment]
@dmzaytsev we'll implement `toString` in all of them

**Comment by davvd** [comment]
@dmzaytsev milestone set to `1.0` (correct me if I am wrong)

**Comment by davvd** [comment]
@adko-pl this ticket is yours now, please proceed, and keep in mind [this](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html). Any technical questions you should ask right here

Task's budget is **30 mins** (see [this](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html) for explanation)

**Comment by davvd** [comment]
@dmzaytsev thanks for this report, I added 15 mins to your account, in transaction `59387637`

**Comment by paulodamaso** [comment]
@dmzaytsev The requested feature was already implemented in `RqPrint`, please take a look.
