### ISSUE TITLE
Href should use undecoded query for URI creation

### ISSUE THREAD

**Issue by krzyk** [yegor256/takes#126]
Currently Href uses following code for extracting server+path from URL:
```
final URI link = URI.create(txt);
final String query = link.getQuery();
...
final String href = link.toString();
this.uri = URI.create(
    href.substring(0, href.length() - query.length() - 1)
);
```
(see https://github.com/yegor256/takes/blob/b536a61c7631d6d1b8bda6d1675eb6b823311528/src/main/java/org/takes/misc/Href.java#L73)

The above code works when query part has only standard not encoded elements, but when the URL is like: `http://localhost:8080/doc/read?file=%5B%5D%28%29.txt` it breaks because `query` contains already decoded data (in this case: `file=[]().txt`) but `href` has stil encoded data, so doing substring on it leads to `http://localhost:8080/doc/read?file=%5`, while it should be `http://localhost:8080/doc/read`.

This can be fixed if instead of `link.getQuery()` one will use `link.getRawQuery()`.

**Comment by davvd** [comment]
we will find someone to do this task, soon

**Comment by davvd** [comment]
@dmzaytsev it's yours, please go ahead

**Comment by davvd** [comment]
@krzyk many thanks for the bug report, I added 15 mins to your acc, transaction `54712240`

**Comment by dmzaytsev** [comment]
@krzyk  #127 is fixing this issue, please close if that's all here, thank you

**Comment by krzyk** [comment]
@dmzaytsev thanks

**Comment by krzyk** [comment]
@yegor256 could you release new version of takes with this bugfix?

**Comment by yegor256** [comment]
@rultor release, tag is `0.13.1`

**Comment by yegor256** [comment]
@rultor release, tag is `0.13.1`

**Comment by yegor256** [comment]
@krzyk done, 0.13.1 is there

**Comment by davvd** [comment]
@elenavolokhova review this ticket please, for compliance with our [quality rules](http://www.teamed.io/qa.html)

**Comment by dmzaytsev** [comment]
@davvd According to our [quality rules](http://www.teamed.io/qa.html):
>Messages in a ticket always start with a name of a user they are addressed to.

please fix your messages, thank you

**Comment by davvd** [comment]
@dmzaytsev fixed, see above

**Comment by elenavolokhova** [comment]
@davvd @dmzaytsev Thank you all! Quality is good here.

**Comment by davvd** [comment]
> @davvd @dmzaytsev Thank you all! Quality is good here.

@elenavolokhova thanks a lot :)

**Comment by davvd** [comment]
@dmzaytsev just added 10 mins to @elenavolokhova (for QA), payment ID is `55487761`. **38 mins** was added to your account, many thanks for your contribution! The task took 55487810.. age=2964, that's why a bonus here for fast delivery. added +38 to your rating, now it is equal to [+468](http://www.netbout.com/b/35166?open=rating)
