### ISSUE TITLE
PsCookie doesn't set HttpOnly

### ISSUE THREAD

**Issue by yegor256** [yegor256/takes#129]
At the moment `PsCookie` doesn't set `HttpOnly` flag to the authenticating cookie and it's a security threat. Let's fix.

**Comment by davvd** [comment]
this task will get someone's attention soon

**Comment by davvd** [comment]
@dmzaytsev please go ahead with this task, it's yours

**Comment by davvd** [comment]
@yegor256 thanks for the report, I topped your acc for 15 mins, payment ID `000-d9b94023`

**Comment by dmzaytsev** [comment]
@yegor256 #131 is fixing this issue, please close  if that's all here, thank you

**Comment by yegor256** [comment]
@dmzaytsev thanks!

**Comment by yegor256** [comment]
@rultor release, tag is `0.12.1`

**Comment by davvd** [comment]
@elenavolokhova please, review this task for compliance with our [quality rules](http://www.teamed.io/qa.html)

**Comment by elenavolokhova** [comment]
@dmzaytsev 
>davvd commented 5 days ago
this task will get someone's attention soon

 According to our [quality rules](http://www.teamed.io/qa.html):
 > Messages in a ticket always start with a name of a user they are addressed to.
 
 As far as you are the performer of this ticket you are responsible for its quality. Please make sure that everyone follows this rule in your tickets in the future.
 
 Please confirm that everything is clear and you have no questions regarding this approach.

**Comment by dmzaytsev** [comment]
@elenavolokhova what I had to do in this case? asked him to change his  comment?

**Comment by dmzaytsev** [comment]
@elenavolokhova I confirm

**Comment by dmzaytsev** [comment]
@davvd According to our [quality rules](http://www.teamed.io/qa.html):
>Messages in a ticket always start with a name of a user they are addressed to.

please fix your messages, thank you

**Comment by elenavolokhova** [comment]
@dmzaytsev Your confirmation is enough here. Let's prevent this in the future. Thank you!

**Comment by elenavolokhova** [comment]
@davvd Ticket passed QA review. Quality is acceptable.

**Comment by davvd** [comment]
> @davvd Ticket passed QA review. Quality is acceptable.

@elenavolokhova thank you, let's try to make it "good" next time

**Comment by davvd** [comment]
@dmzaytsev I added 10 mins to @elenavolokhova (for QA review) in transaction 55493706; **1 hour** sent to your balance (ID `55493730`), many thanks! It took 25 hours and 25 mins.; the bonus for fast delivery (age=0); +60 to your rating, your total score is [+528](http://www.netbout.com/b/35166?open=rating)
