### ISSUE TITLE
socket information is not present in request

### ISSUE THREAD

**Issue by yegor256** [yegor256/takes#130]
When `Request` gets into a take, it doesn't have any information about the socket it came from. We're missing a lot of useful information, which is present in Java servlets, for example, like IP address of the client, etc.

Let's add extra custom headers to each request, inside `BkBasic`. Something like `X-Takes-LocalAddress`, `X-Takes-LocalPort`, etc. As much information as we can get from a `Socket`.

Then, let's create a class `RqSocket`, which will help to extract that information from the request, like:

```java
final class RqSocket extends RqWrap {
  InetAddress localAddress();
  int localPort();
  InetAddress remoteAddress();
  int remotePort();
  // etc.
}
```

**Comment by davvd** [comment]
@yegor256 got it, tag `bug` is here

**Comment by davvd** [comment]
@d-molotchko please pick this up, and keep in mind [these instructions](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html). Any technical questions - ask right here

This task's budget is **30 mins**. This is exactly how much will be paid when the problem explained above is solved. See [this](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html) for more information

**Comment by davvd** [comment]
@yegor256 thanks a lot for reporting, **15 mins** added to your acc, pmt ID `000-a435c29b`

**Comment by d-molotchko** [comment]
@davvd please reassign this task to another dev. thanks.

**Comment by yegor256** [comment]
@davvd give this to somebody else

**Comment by davvd** [comment]
> @davvd give this to somebody else

@yegor256 no problem, I will try to find somebody else

**Comment by davvd** [comment]
@yegor256 milestone set to `1.0` (correct me if I am wrong)

**Comment by davvd** [comment]
@cyberone can you please help? Keep in mind [this](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html). If you have any technical questions, don't hesitate to ask right here

Total fixed cost of this task is **30 mins** (see [this](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html) for more info)

**Comment by cyberone** [comment]
@davvd assign somebody else please

**Comment by davvd** [comment]
> @davvd assign somebody else please

@cyberone 30 points deducted from your rating

**Comment by davvd** [comment]
> @davvd assign somebody else please

@cyberone right, I will find someone else, no problem

**Comment by davvd** [comment]
@ikhvostenkov it's yours,please go ahead

**Comment by carlosmiranda** [comment]
@davvd Waiting for #225.

**Comment by davvd** [comment]
> @davvd Waiting for #225.

@carlosmiranda sure, let's wait for #225

**Comment by davvd** [comment]
> @davvd Waiting for #225.

@carlosmiranda sure, let's wait for #225

**Comment by davvd** [comment]
> @davvd Waiting for #225.

@carlosmiranda agreed, we'll wait for #225

**Comment by davvd** [comment]
> @davvd Waiting for #225.

@carlosmiranda sure, let's wait for #225

**Comment by davvd** [comment]
> @davvd Waiting for #225.

@carlosmiranda yes, right, let's wait for #225

**Comment by ikhvostenkov** [comment]
@yegor256 Can we close this? Fix has been successfully merged.

**Comment by yegor256** [comment]
@ikhvostenkov thanks!

**Comment by davvd** [comment]
@elenavolokhova review this ticket please, for compliance with our [quality rules](http://www.teamed.io/qa.html)

**Comment by elenavolokhova** [comment]
@davvd This issue looks good!

**Comment by davvd** [comment]
> @davvd This issue looks good!

@elenavolokhova thank you, good quality is always good :)
