### ISSUE TITLE
CcXOR is not strong enough

### ISSUE THREAD

**Issue by yegor256** [yegor256/takes#132]
`CcXOR` codec is not strong enough. It's a very primitive encrypting technique. We should introduce something stronger, using some other algorithm, from JVM.

**Comment by davvd** [comment]
@yegor256 sure, thanks, I added bug tag to it

**Comment by davvd** [comment]
@yegor256 thanks for the ticket, your account was topped for 15 mins, payment 000-e301751f

**Comment by davvd** [comment]
@super132 could you please pick this up? This [article](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html) explains how we work. Any technical questions you may ask right here. Total fixed cost of this task is **30 mins** (see [this](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html) for more info)

**Comment by super132** [comment]
@yegor256 , may I know do you intend to change the implementation of ```ccXOR``` class or creating a new codec class for it? Thanks.

**Comment by yegor256** [comment]
@super132 I want a new class, of course. `CcXOR` is fine for primitive cases, but we need something else, more strong

**Comment by super132** [comment]
AES encryption implementation is submitted. Please check if it is fine. Thanks.

**Comment by davvd** [comment]
@yegor256 since there is no milestone yet I set it to "1.0"

**Comment by super132** [comment]
@yegor256 please check if this issue can be closed if there is no problem. Thanks.

**Comment by yegor256** [comment]
@super132 in which pull request it was solved? please post its number here

**Comment by super132** [comment]
@yegor256 , it is PR #186. Thanks.

**Comment by yegor256** [comment]
@super132 thanks!

**Comment by davvd** [comment]
@elenavolokhova please, review this task for compliance with our [quality rules](http://www.teamed.io/qa.html)

**Comment by elenavolokhova** [comment]
@super132 
>super132 commented 12 days ago
AES encryption implementation is submitted. Please check if it is fine. Thanks.

 According to our [quality rules](http://www.teamed.io/qa.html):
 > Messages in a ticket always start with a name of a user they are addressed to.
 
 As far as you are the performer of this ticket you are responsible for its quality. Please don't forget to address all your comments and make sure that everyone follows this rule in your tickets in the future. 
 
 Please confirm that everything is clear and you have no questions regarding this approach.

**Comment by super132** [comment]
@elenavolokhova , I have fixed the comment which got problem. Thanks.

**Comment by elenavolokhova** [comment]
@super132 Thank you!

**Comment by elenavolokhova** [comment]
@davvd Quality is acceptable.

**Comment by davvd** [comment]
> @davvd Quality is acceptable.

@elenavolokhova thank you, let's try to make it "good" next time

**Comment by davvd** [comment]
@super132 10 mins was added to the account of @elenavolokhova (for QA review), in transaction 56373225; Thanks for your contribution, **38 mins** was added to your account, payment ID is `AP-3Y993606RW804571U`, 237 hours and 1 min spent total; age=4209, that's why a bonus here for fast delivery; +38 added to your rating, at the moment it is: [+38](http://www.netbout.com/b/35282?open=rating)
