### ISSUE TITLE
merge Takes and Take interfaces

### ISSUE THREAD

**Issue by yegor256** [yegor256/takes#133]
Looks like we don't need them both. Just `Take` will be enough.

**Comment by davvd** [comment]
@yegor256 it's yours,budget is 30 mins,please go ahead

**Comment by davvd** [comment]
@yegor256 thanks for tis bug, I topped your account for 15 mins, transaction `000-b8cd9ed3`

**Comment by yegor256** [comment]
done

**Comment by yegor256** [comment]
@rultor release, tag is `0.12`

**Comment by yegor256** [comment]
@rultor release, tag is `0.12`

**Comment by davvd** [comment]
@elenavolokhova please, let us know what do you think about this ticket, according to our [QA rules](http://www.teamed.io/qa.html)

**Comment by elenavolokhova** [comment]
@yegor256
According to our [quality rules](http://www.teamed.io/qa.html): 
>Problem reporter and problem solver are two different persons.

Try to avoid such issue next time.

**Comment by elenavolokhova** [comment]
@davvd Ticket passed QA review. Quality is acceptable.

**Comment by davvd** [comment]
> @davvd Ticket passed QA review. Quality is acceptable.

@elenavolokhova thanks a lot, next time everybody should try to make it better

**Comment by davvd** [comment]
@yegor256 I added 10 mins to @elenavolokhova (for QA review) in transaction 55080707; Many thanks! **1 hour** were added to your account in Transaction ID `000-d293f0cc` (task took 15 hours and 36 mins); the bonus for fast delivery (age=21); added +60 to your rating, now it is equal to [+9261](http://www.netbout.com/b/35008?open=rating)
