### ISSUE TITLE
RqForm must be an interface

### ISSUE THREAD

**Issue by yegor256** [yegor256/takes#135]
`RqForm` must be an interface and its implementation must be in its nested class `RqForm.Base`. Let's refactor it accordingly. The interface should look like:

```java
public interface RqForm extends Request {
  Iterable<String> param(String name);
  Iterable<String> names();
}
```

**Comment by davvd** [comment]
@yegor256 thanks, I added the "bug" tag

**Comment by davvd** [comment]
@yegor256 thanks for the ticket, your account was topped for 15 mins, payment 000-e3486a4b

**Comment by davvd** [comment]
@cyberone please go ahead, it's your task now, keep [this](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html) in mind, and don't hesitate to ask any technical questions you may have

The cost of this task is **30 mins** (this is exactly how much will be paid, not less not more), when the task is [done](http://www.xdsd.org/2014/04/15/definition-of-done.html)

**Comment by cyberone** [comment]
@davvd please review https://github.com/yegor256/takes/pull/179

**Comment by cyberone** [comment]
@yegor256 the PR is merged, close the task please.

**Comment by yegor256** [comment]
@cyberone thanks!

**Comment by davvd** [comment]
@yegor256 I added milestone `1.0` to this issue, let me know if there has to be something else

**Comment by davvd** [comment]
@elenavolokhova please, review this ticket for compliance with our [QA rules](http://www.teamed.io/qa.html)

**Comment by elenavolokhova** [comment]
@davvd Ticket passed QA review. It looks good.

**Comment by davvd** [comment]
> @davvd Ticket passed QA review. It looks good.

@elenavolokhova thanks for the review

**Comment by davvd** [comment]
@cyberone 10 mins was added to the account of @elenavolokhova (for QA review), in transaction 55987502. Thanks a lot, I just topped your account for **1 hour**, transaction ID `55987550`, total time was 68 hours and 35 mins. the bonus for fast delivery (age=1). added +60 to your rating, now it is equal to [+150](http://www.netbout.com/b/35076?open=rating)
