### ISSUE TITLE
takes/src/main/java/org/takes/rq/CapInputStream.java null checking 

### ISSUE THREAD

**Issue by Akvadevka** [yegor256/takes#1368]
@yegor256 
In all read() methods, there is no null check for the buf input array if an empty array is passed. 

https://github.com/yegor256/takes/blob/2f7bc6ca2810b25b1f475eb410722085592e9c63/src/main/java/org/takes/rq/CapInputStream.java#L68

**Comment by yegor256** [comment]
@Akvadevka it's an internal class, we don't expect users to instantiate it directly, that's why no checks
