### ISSUE TITLE
RqMultipart must be an interface

### ISSUE THREAD

**Issue by yegor256** [yegor256/takes#138]
`RqMultipart` must be an interface and its implementation must be in its nested class `RqMultipart.Base`. Let's refactor it accordingly. The interface should look like:

```java
public interface RqMultipart extends Request {
  Iterable<Request> part(String name);
  Iterable<String> names();
}
```

**Comment by davvd** [comment]
@yegor256 OK, I labeled it as `bug`

**Comment by davvd** [comment]
@yegor256 thanks for this report, I added 15 mins to your account, in transaction `000-0a5504bb`

**Comment by davvd** [comment]
@ndbroadbent this task is for you, keep [these principles](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html) in mind, and don't hesitate to ask any technical questions; The budget here is **30 mins**, which is exactly how much time will be paid for, when the task is [completed](http://www.xdsd.org/2014/04/15/definition-of-done.html)

**Comment by ndbroadbent** [comment]
@davvd - Here is the pull request: #178

**Comment by davvd** [comment]
@rultor don't close it, ask @yegor256 to do do it, since he created it, thanks!

**Comment by davvd** [comment]
@yegor256 there is no milestone yet, so I set it to `1.0`

**Comment by ndbroadbent** [comment]
Hello @yegor256, please close this issue since it is now completed.

**Comment by yegor256** [comment]
@ndbroadbent thanks!

**Comment by davvd** [comment]
@ndbroadbent you're holding this ticket for 15 days already. If it is not finished (and closed) in the next 48 hours, it will be re-assigned to someone else, see [No Obligations](http://www.xdsd.org/2014/04/13/no-obligations-principle.html) principle ([this article](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html) should help if you're stuck)

added -30 to your rating, now it is equal to [-30](http://www.netbout.com/b/35281?open=rating)

**Comment by ndbroadbent** [comment]
Hi @davvd , I'm pretty confused, this ticket should have been closed a very long time ago...

**Comment by ndbroadbent** [comment]
@yegor256 - can you please close this ticket

**Comment by yegor256** [comment]
@ndbroadbent closed

**Comment by davvd** [comment]
@elenavolokhova please, let us know what do you think about this ticket, according to our [QA rules](http://www.teamed.io/qa.html)

**Comment by elenavolokhova** [comment]
@davvd It looks good.

**Comment by davvd** [comment]
> @davvd It looks good.

@elenavolokhova thank you, good quality is always good :)

**Comment by davvd** [comment]
> @davvd It looks good.

@elenavolokhova thanks a lot :)

**Comment by davvd** [comment]
> @davvd It looks good.

@elenavolokhova thank you :)

**Comment by davvd** [comment]
> @davvd It looks good.

@elenavolokhova thank you

**Comment by davvd** [comment]
> @davvd It looks good.

@elenavolokhova thank you

**Comment by ndbroadbent** [comment]
@davvd I think your script is broken :)

**Comment by davvd** [comment]
> @davvd It looks good.

@elenavolokhova thanks for the review

**Comment by davvd** [comment]
> @davvd It looks good.

@elenavolokhova thanks!

**Comment by davvd** [comment]
@ndbroadbent I added 10 mins to @elenavolokhova (for QA review) in transaction 56813626... thanks, I just added **1 hour** to your account, payment `AP-2DC814547C481642K`, 370 hours and 10 mins spent... there is a bonus for fast delivery (age=1)... added +60 to your rating, now it is equal to [+30](http://www.netbout.com/b/35281?open=rating)
