### ISSUE TITLE
RqHref must be an interface

### ISSUE THREAD

**Issue by yegor256** [yegor256/takes#139]
`RqHref` must be an interface and its implementation must be in its nested class `RqHref.Base`. Let's refactor it accordingly. The interface should look like:

```java
public interface RqHref extends Request {
  Href href();
}
```

**Comment by davvd** [comment]
@yegor256 OK, I labeled it as `bug`

**Comment by davvd** [comment]
@yegor256 thank you for the ticket reported, I topped your account for 15 mins, transaction `000-209e260b`

**Comment by davvd** [comment]
@dmzaytsev please go ahead with this task,it's yours

**Comment by dmzaytsev** [comment]
@yegor256 #165  is fixing this issue, please close if that's all here, thank you

**Comment by yegor256** [comment]
@dmzaytsev thanks!

**Comment by davvd** [comment]
@elenavolokhova please, review this ticket for compliance with our [QA rules](http://www.teamed.io/qa.html)

**Comment by elenavolokhova** [comment]
@davvd This one looks good.

**Comment by davvd** [comment]
> @davvd This one looks good.

@elenavolokhova thanks a lot :)

**Comment by davvd** [comment]
@dmzaytsev 10 mins was added to the account of @elenavolokhova (for QA review), in transaction 55564369... Thanks so much! Your account was topped up for **1 hour** (transaction ID is `55564384`, the task took 10 hours and 45 mins)... there is a bonus for fast delivery (age=1)... +60 added to your rating, at the moment it is: [+618](http://www.netbout.com/b/35166?open=rating)
