### ISSUE TITLE
RqCookies must be an interface

### ISSUE THREAD

**Issue by yegor256** [yegor256/takes#140]
`RqCookies` must be an interface and its implementation must be in its nested class `RqCookies.Base`. Let's refactor it accordingly. The interface should look like:

```java
public interface RqCookies extends Request {
  Iterable<String> cookie(String name);
  Iterable<String> names();
}
```

**Comment by davvd** [comment]
@yegor256 thanks, I added the "bug" tag

**Comment by davvd** [comment]
@yegor256 many thanks for the report, I topped your account for 15 mins, transaction 000-ac9d227c

**Comment by YamStranger** [comment]
Can I take this task?

**Comment by davvd** [comment]
@dmzaytsev the task is yours,please go ahead

**Comment by MohandAndel** [comment]
Ohh I am sorry , I didn't know this task has been assigned , and I don't know how to remove my commit .

**Comment by dmzaytsev** [comment]
@YamStranger @MohandAndel 
According to our [quality rules](http://www.teamed.io/qa.html):
>Messages in a ticket always start with a name of a user they are addressed to.

please fix your messages, thank you

**Comment by dmzaytsev** [comment]
@yegor256 #162  is fixing this issue, please close  if that's all here, thank you

**Comment by yegor256** [comment]
@dmzaytsev thanks!

**Comment by dmzaytsev** [comment]
@davvd could you please schedule QA review for the task, thank you

**Comment by davvd** [comment]
@elenavolokhova please, review this task for compliance with our [quality rules](http://www.teamed.io/qa.html)

**Comment by elenavolokhova** [comment]
@dmzaytsev Thank you for work on the quality of this ticket, but it is still not perfect. Not all comments contain user name. Be more persistent next time.

**Comment by elenavolokhova** [comment]
@davvd Quality is acceptable.

**Comment by dmzaytsev** [comment]
@elenavolokhova @yegor256 how I can fulfill the requirements of quality, except ask someone to change a comment? What should I do if someone does not comply with the request?

**Comment by davvd** [comment]
> @davvd Quality is acceptable.

@elenavolokhova thanks a lot, next time everybody should try to make it better

**Comment by davvd** [comment]
@dmzaytsev just added 10 mins to @elenavolokhova (for QA), payment ID is `55983587`; **45 mins** sent to your balance (ID `55983615`), many thanks! It took 157 hours and 39 mins.; the bonus for fast delivery (age=1469); +45 added to your rating, current score is: [+896](http://www.netbout.com/b/35166?open=rating)
