### ISSUE TITLE
RsFlash ctor must accept exception object

### ISSUE THREAD

**Issue by yegor256** [yegor256/takes#145]
We should be able to do something like this:

```java
} catch(IOException ex) { 
  throw new RsForward(
    new RsFlash(ex)
  );
}
```

**Comment by davvd** [comment]
@yegor256 OK, I labeled it as `bug`

**Comment by davvd** [comment]
@dmzaytsev it's yours, please go ahead

**Comment by davvd** [comment]
@yegor256 thanks for tis bug, I topped your account for 15 mins, transaction `000-949e3d8c`

**Comment by dmzaytsev** [comment]
@yegor256 RsFlash has the ctor with Throwable in the master branch
```
    public RsFlash(final Throwable err) throws IOException {
        this(err.getLocalizedMessage(), Level.SEVERE);
    }
```
do you mean some another ctor?

**Comment by yegor256** [comment]
@dmzaytsev hm... strange. thanks

**Comment by davvd** [comment]
@elenavolokhova please, review this ticket for compliance with our [QA rules](http://www.teamed.io/qa.html)

**Comment by elenavolokhova** [comment]
@davvd There was no solution provided it this ticket, so it shouldn't be paid. Quality of such one is bad.

**Comment by yegor256** [comment]
@davvd quality is bad I confirm

**Comment by davvd** [comment]
> @davvd quality is bad I confirm

@yegor256 thank you very much

**Comment by davvd** [comment]
@dmzaytsev 10 mins was added to the account of @elenavolokhova (for QA review), in transaction 55580035... **1 hour** was added to your account, many thanks for your contribution! The task took 55580067.... the bonus for fast delivery (age=2)... +60 to your rating, your total score is [+678](http://www.netbout.com/b/35166?open=rating)
