### ISSUE TITLE
Build failed on windows with lots of EOL violations

### ISSUE THREAD

**Issue by longtimeago** [yegor256/takes#148]
Looks like we need to add ```.gitattributes``` to force EOL of the repo.
See how it was done here https://github.com/jcabi/jcabi-aether/pull/59/files

**Comment by YamStranger** [comment]
Its great idea!!! (as here https://github.com/yegor256/takes/pull/128)

**Comment by davvd** [comment]
we will find someone to do this task, soon

**Comment by davvd** [comment]
@yamstranger please pick this up, and keep in mind [these instructions](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html). Any technical questions - ask right here... Budget here is **30 mins** (keep [this principle](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html) in mind)

**Comment by davvd** [comment]
@longtimeago thank you for the ticket reported, I topped your account for 15 mins, transaction `55000221`

**Comment by YamStranger** [comment]
@davvd Thanks, I take it.

**Comment by YamStranger** [comment]
@davvd fix in pull request #156. Please look at it

**Comment by YamStranger** [comment]
@davvd As I see pull request #156 merged long time ago, but this issue is still open. Is some problem with it?

**Comment by longtimeago** [comment]
@YamStranger sorry for that. It's the responsibility of issue reporter to close it and I missed that event. Don't hesitate to ping the issue reporter in such case :)

**Comment by davvd** [comment]
@elenavolokhova please, review this ticket for compliance with our [QA rules](http://www.teamed.io/qa.html)

**Comment by elenavolokhova** [comment]
@YamStranger 
>YamStranger commented 12 days ago
Its great idea!!! (as here #128)

>davvd commented 12 days ago
we will find someone to do this task, soon

According to our [quality rules](http://www.teamed.io/qa.html):
 > Messages in a ticket always start with a name of a user they are addressed to.
 
 As far as you are the performer of this ticket you are responsible for its quality. Please make sure that everyone follows this rule in your tickets in the future. Ask them to fix issues before closing the ticket.
 
 Please confirm that everything is clear and you have no questions regarding this approach.

**Comment by longtimeago** [comment]
@elenavolokhova everything is clear

**Comment by elenavolokhova** [comment]
@longtimeago Thank you, but this one is not yours :)

**Comment by YamStranger** [comment]
@elenavolokhova fixed, thanks

**Comment by elenavolokhova** [comment]
@davvd Ticket passed QA review. Quality is acceptable.

**Comment by davvd** [comment]
> @davvd Ticket passed QA review. Quality is acceptable.

@elenavolokhova thanks for the QA review, we'll work better next time

**Comment by YamStranger** [comment]
@davvd please share details of payment for this issue

**Comment by davvd** [comment]
@yamstranger 10 mins was added to the account of @elenavolokhova (for QA review), in transaction 55988887... thank you, added **38 mins** to your acc, payment num is `55988911`, 184 hours and 28 mins spent in total to complete... there is a bonus for fast delivery (age=2915)... added +38 to your rating, now it is equal to [+174](http://www.netbout.com/b/35267?open=rating)
