### ISSUE TITLE
Estimate project size

### ISSUE THREAD

**Issue by davvd** [yegor256/takes#149]
There is no estimate in the project yet. We have to create one as explained [here](https://github.com/teamed/est)

**Comment by davvd** [comment]
@yegor256 attached this issue to milestone "1.0" (let me know if this is wrong)

**Comment by davvd** [comment]
@ikhvostenkov it's yours,please go ahead

**Comment by ikhvostenkov** [comment]
Could you, please, assign someone else or postpone this task until 8th of June, I will be out until this for personal reasons?

**Comment by yegor256** [comment]
@karato give this to someone else pls

**Comment by davvd** [comment]
@ikhvostenkov you're holding this ticket for 15 days already. If it is not finished (and closed) in the next 48 hours, it will be re-assigned to someone else, see [No Obligations](http://www.xdsd.org/2014/04/13/no-obligations-principle.html) principle ([this article](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html) should help if you're stuck)

-30 to your rating, your total score is [-5](http://www.netbout.com/b/35232?open=rating)

**Comment by davvd** [comment]
@yegor256 We are done here, thanks all

**Comment by davvd** [comment]
@ikhvostenkov I added **30 mins** to your account, many thanks for working with the project! The completion time here was 59038973.

+30 added to your rating, current score is: [+25](http://www.netbout.com/b/35232?open=rating)

**Comment by pinaf** [comment]
@yegor256 should this be closed?
