### ISSUE TITLE
CcStrict validation works incorrectly.

### ISSUE THREAD

**Issue by ikhvostenkov** [yegor256/takes#153]
```Java
new CcStrict(new CcPlain()).encode(
                    new Identity.Simple("urn:test-domain-org:valid:1")
                )
```
returns ```DecodingException```. According with [RFC2141](https://www.ietf.org/rfc/rfc2141.txt) ```urn:test-domain-org:valid:1``` is a valid URN.

**Comment by davvd** [comment]
this task will get someone's attention soon

**Comment by davvd** [comment]
@dmzaytsev the task is yours, please go ahead

**Comment by davvd** [comment]
@ikhvostenkov thanks for this report, I added 15 mins to your account, in transaction `55065728`

**Comment by dmzaytsev** [comment]
@ikhvostenkov #157 is fixing this issue, please close if that's all here, thank you

**Comment by dmzaytsev** [comment]
@davvd According to our [quality rules](http://www.teamed.io/qa.html):
>Messages in a ticket always start with a name of a user they are addressed to.

please fix your messages, thank you

**Comment by dmzaytsev** [comment]
@ikhvostenkov please close the task if you have no comments

**Comment by ikhvostenkov** [comment]
Works good. Closed than.

**Comment by dmzaytsev** [comment]
@ikhvostenkov According to our [quality rules](http://www.teamed.io/qa.html):
>Messages in a ticket always start with a name of a user they are addressed to.

please fix your messages, thank you

**Comment by dmzaytsev** [comment]
@davvd please fix your message, thank you

> this task will get someone's attention soon

**Comment by davvd** [comment]
@dmzaytsev fixed

**Comment by dmzaytsev** [comment]
@davvd could you please schedule QA review for the task?  thank you

**Comment by davvd** [comment]
@elenavolokhova please, review this task for compliance with our [quality rules](http://www.teamed.io/qa.html)

**Comment by elenavolokhova** [comment]
@dmzaytsev Thank you for fixing quality issues in this ticket!

**Comment by elenavolokhova** [comment]
@davvd This one looks good :)

**Comment by davvd** [comment]
> @davvd This one looks good :)

@elenavolokhova thanks for the review and a good remark

**Comment by davvd** [comment]
@dmzaytsev just added 10 mins to @elenavolokhova (for QA), payment ID is `55580878`

Thanks so much! Your account was topped up for **38 mins** (transaction ID is `55580905`, the task took 181 hours and 45 mins)

the bonus for fast delivery (age=2915)

+38 added to your rating, current score is: [+716](http://www.netbout.com/b/35166?open=rating)
