### ISSUE TITLE
Corrections in documenation (README.md)

### ISSUE THREAD

**Issue by mgooty** [yegor256/takes#154]
Following are the issues in documentation:

In **A Bigger Example** section:
1. `ts` stands for "take" - typo error, it should be `tk` instead of `ts`
2. In `act()` method of `TkIndex` class, there is a typo error. The class name should be `RsHTML` instead of `RsHtml`
3. In the example showing the use of `TkFork`, `act()` method needs to have throws clause, `throws IOException`

**Comment by Bertram25** [comment]
@yegor256 
Hi,
While looking for open tasks, I fell on this one. Isn't it done already?
Best regards,

**Comment by yegor256** [comment]
@mgooty looks like this ticket should be closed, since it's fixed already. please close it. @Bertram25 thanks!
