### ISSUE TITLE
PsLinkedinTest.java:42-48: This class not implemented yet,...

### ISSUE THREAD

**Issue by davvd** [yegor256/takes#158]
Puzzle `12-159d303e` in `src/test/java/org/takes/facets/auth/social/PsLinkedinTest.java:42-48` has to be resolved: This class not implemented yet, but has to be. Please implement it. Mocked OAuth server is one of the possible solutions. In this case, we could use some library like WireMock (see http://www.wiremock.org), which allows make stub for web service. We'll need to make some changes in PsLinkedin, that allow to change API url, and use local stubbed http server during unit test.... The puzzle was created by Dmitry Zaystev on 4-Apr-2015.

If you have any technical questions, don't ask me, submit new tickets instead

**Comment by ikhvostenkov** [comment]
@davvd I can take this issue if no one does not mind

**Comment by yegor256** [comment]
@davvd pls assign @ikhvostenkov

**Comment by ikhvostenkov** [comment]
@yegor256 I do not think this is good idea here to use WireMock or similar staff due to this will be not unit test but already integration test. I've looked other classes ```PsGithub``` and ```PsGoogle``` and there is the same method ```fetch``` in it, I suggest to extract this code in separate class and after that we can mock this class and after that very simple create tests for social auth. There is other way just to mock ```fetch``` method call inside class under test with ```NonStrictExpectations```, but IMHO first approach is better due to we will also remove code duplication. How do you think?

**Comment by yegor256** [comment]
@ikhvostenkov well, the idea is good, but I doubt we can technically do this. all these `fetch()` methods are different in each `Ps*` class. I don't see how you can generalize them. But feel free to try, I like the idea.

**Comment by davvd** [comment]
@yegor256 I set milestone here to `1.0`, let me know if it is wrong

**Comment by davvd** [comment]
@celezar This task is yours, please go ahead keeping in mind [this](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html). If any questions, don't hesitate to ask right here... Task's budget is **30 mins** (see [this](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html) for explanation)

**Comment by davvd** [comment]
> @davvd pls assign @ikhvostenkov 

@yegor256 yes, done, @ikhvostenkov is at the task, please start! whoever worked with this task before, please stop immediately

**Comment by davvd** [comment]
> @davvd pls assign @ikhvostenkov 

@yegor256 sure! @ikhvostenkov the task is yours, please go ahead

**Comment by davvd** [comment]
> @davvd pls assign @ikhvostenkov 

@yegor256 done, @ikhvostenkov is a new assignment at the task, please go on. whoever worked with this task before, please stop right now

**Comment by yegor256** [comment]
@davvd looks like we need more time here

**Comment by davvd** [comment]
> @davvd looks like we need more time here

@yegor256 right, take your time and thanks for informing

**Comment by davvd** [comment]
@yegor256 I am closing it, thanks all

**Comment by davvd** [comment]
@elenavolokhova please, review this ticket for compliance with our [QA rules](http://www.teamed.io/qa.html)

**Comment by elenavolokhova** [comment]
@ikhvostenkov
 According to our [quality rules](http://www.teamed.io/qa.html):
 > Some of ticket messages must mention all pull requests where the problem was actually fixed.
 
 There is no link to related PR in comments. Several PR's have links to this issue and it is not clear which one solves the problem. Please add this info and follow this rule in your tickets in the future.

**Comment by ikhvostenkov** [comment]
@elenavolokhova PR which resolves this issue is not finished, I do not know why this ticket has been closed.
@davvd Why did you close this ticket?

**Comment by yegor256** [comment]
@ikhvostenkov the ticket was closed because the puzzle disappeared from the source code... make sense?

**Comment by ikhvostenkov** [comment]
@yegor256 this make sense. But the question is why did puzzle disappear? Due to someone else resolve this? Why we have to identical tasks? What shall I do with this task then?

**Comment by yegor256** [comment]
@ikhvostenkov it happens sometimes, you just got lucky here, no need to do anything

**Comment by elenavolokhova** [comment]
@yegor256 So should I mark this issue as bad? Finally there is no solution provided.

**Comment by yegor256** [comment]
@elenavolokhova yeah, it's a good candidate for a "bad" mark

**Comment by elenavolokhova** [comment]
@davvd As per discussion above quality is bad.

**Comment by davvd** [comment]
> @davvd As per discussion above quality is bad.

@elenavolokhova thanks for paying attention, the performer of this ticket won't be paid

**Comment by davvd** [comment]
@ikhvostenkov I added 10 mins to @elenavolokhova (for QA review) in transaction 57286878. I added **38 mins** to your account, many thanks for working with the project! The completion time here was 57286885.. age=48 hours and 31 mins, that's why a bonus here for fast delivery. +38 to your rating, your total score is [+77](http://www.netbout.com/b/35232?open=rating)
