### ISSUE TITLE
RsMatchStatus

### ISSUE THREAD

**Issue by yegor256** [yegor256/takes#166]
Let's create a new class `RsMatchStatus`, for unit testing mostly:

```java
public void returnsCorrectStatusCode() {
  MatcherAssert.assertThat(
    new TkIndex().act(new RqFake())
    new RsMatchStatus(Matchers.equalTo(200))
  );
}
```

`RsMatchStatus` should implement `Matcher` interface from Hamcrest. Let's place it into `org.takes.facets.hamcrest` package.

**Comment by davvd** [comment]
@yegor256 I tagged this as "bug"

**Comment by davvd** [comment]
@erimerturk could you please pick this up? This [article](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html) explains how we work. Any technical questions you may ask right here. The budget of this issue is **30 mins**, which is exactly how much will be paid when the task is *done* (see [this](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html) for explanation)

**Comment by davvd** [comment]
@yegor256 thanks a lot for reporting, **15 mins** added to your acc, pmt ID `000-88cdbdf6`

**Comment by erimerturk** [comment]
@yegor256 I couldn't find TkIndex class. Is just a test sample ? If not how can how can i find TkIndex class ? And Matcher interface is deprecated i am planning to use org.hamcrest.TypeSafeMatcher .

**Comment by yegor256** [comment]
@erimerturk yeah, `TkIndex` is just an example. You can do this instead:

```java
public void returnsCorrectStatusCode() {
  MatcherAssert.assertThat(
    new TkEmpty().act(new RqFake())
    new RsMatchStatus(Matchers.equalTo(200))
  );
}
```

**Comment by yegor256** [comment]
@erimerturk I agree, we should use `TypeSafeMatcher`

**Comment by erimerturk** [comment]
@yegor256 can you close issue please ?

**Comment by yegor256** [comment]
@erimerturk looks like you've done it wrong. using your implementation we can't do what my example above is requiring. you shouldn't encapsulate a status code, but instead encapsulate another matcher. this is how I want to use it (I renamed the class, `Hm` means Hamcrest Matcher):

```java
public void returnsCorrectStatusCode() {
  MatcherAssert.assertThat(
    new TkIndex().act(new RqFake())
    new HmRsStatus(
      Matchers.allOf(
        Matchers.greaterThan(200),
        Matchers.lessThan(300)
      )
    )
  );
}
```

**Comment by erimerturk** [comment]
@yegor256 i refactored after your comments, what should i do now ? i pushed to code again. Should I create pull request ?

**Comment by yegor256** [comment]
@erimerturk yes, sure, just make a new pull request

**Comment by erimerturk** [comment]
@yegor256 i created PR #212 . Will you accept and close this issue ?

**Comment by davvd** [comment]
@erimerturk check this ["no obligations principle"](http://www.xdsd.org/2014/04/13/no-obligations-principle.html).. This task is on your name for at least 16 days. If you can't close it within the next 48 hours I will have to assign someone else to it. [This article](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html) should help if you're stuck. -30 to your rating, your total score is [-30](http://www.netbout.com/b/35280?open=rating)

**Comment by erimerturk** [comment]
@davvd i have already done it. It is merged. @yegor256 can you check and close it please

**Comment by yegor256** [comment]
@erimerturk thanks!

**Comment by erimerturk** [comment]
@davvd can you rollback negative rating please?

**Comment by yegor256** [comment]
@erimerturk here is how we understand "done": http://www.yegor256.com/2014/04/15/definition-of-done.html This means that even if you merged a pull request, it's not done yet. Only when the ticket is closed by its author the task is done. So, your negative rating here is pretty valid.

**Comment by erimerturk** [comment]
@yegor256 i mean my pull request merged 2 days ago but you didn't close this task until now. you can see details #212 . maybe it is my fault i should remind you to close task.

**Comment by yegor256** [comment]
@erimerturk yes, it's your responsibility to make sure the ticket is closed. No matter why it's not closed, it's your fault, see http://www.teamed.io/policy.html#7

**Comment by erimerturk** [comment]
@yegor256 i see, it was blocked because of #212 .  Last question will i get payment ?

**Comment by yegor256** [comment]
@erimerturk sure, you just lost some rating points, but the task is still yours, you didn't lose it. now it's closed and you will be paid soon

**Comment by davvd** [comment]
@elenavolokhova please, review this task for compliance with our [quality rules](http://www.teamed.io/qa.html)

**Comment by elenavolokhova** [comment]
@davvd Looks good.

**Comment by davvd** [comment]
> @davvd Looks good.

@elenavolokhova thanks, got it, great to see high-quality tickets here

**Comment by davvd** [comment]
> @davvd Looks good.

@elenavolokhova thanks for the review

**Comment by davvd** [comment]
> @davvd Looks good.

@elenavolokhova thank you, good quality is always good :)

**Comment by davvd** [comment]
> @davvd Looks good.

@elenavolokhova thank you, good quality is always good :)

**Comment by davvd** [comment]
> @davvd Looks good.

@elenavolokhova thanks a lot

**Comment by davvd** [comment]
> @davvd Looks good.

@elenavolokhova thank you

**Comment by erimerturk** [comment]
@davvd when will you pay for this  ticket? It was already closed.

**Comment by davvd** [comment]
> @davvd Looks good.

@elenavolokhova thanks for the review and a good remark

**Comment by davvd** [comment]
@erimerturk just added 10 mins to @elenavolokhova (for QA), payment ID is `56847006`. Thanks a lot, I just topped your account for **1 hour**, transaction ID `AP-2R596474XB221070H`, total time was 407 hours and 42 mins. there is a bonus for fast delivery (age=2). +60 added to your rating, current score is: [+30](http://www.netbout.com/b/35280?open=rating)
