### ISSUE TITLE
Href no-arg ctor is missing

### ISSUE THREAD

**Issue by yegor256** [yegor256/takes#167]
Would be convenient to have a new no-arg ctor in `Href`

**Comment by davvd** [comment]
@yegor256 this task is yours, go ahead

**Comment by davvd** [comment]
@yegor256 thanks for tis bug, I topped your account for 15 mins, transaction `000-6c518313`

**Comment by yegor256** [comment]
@rultor deploy

**Comment by yegor256** [comment]
@rultor release, tag is `0.13.2`

**Comment by davvd** [comment]
@elenavolokhova review this ticket please, for compliance with our [quality rules](http://www.teamed.io/qa.html)

**Comment by elenavolokhova** [comment]
@yegor256 
 According to our [quality rules](http://www.teamed.io/qa.html):
 >Problem reporter and problem solver are two different persons.
 
 This was not a case in this ticket. Please avoid fixing your own issues.
 
 Please confirm that everything is clear and you have no questions regarding this approach.

**Comment by yegor256** [comment]
@elenavolokhova you're right, my bad, thanks for noticing

**Comment by elenavolokhova** [comment]
@davvd Quality is acceptable. Thanks.

**Comment by davvd** [comment]
> @davvd Quality is acceptable. Thanks.

@elenavolokhova thanks a lot, next time everybody should try to make it better

**Comment by davvd** [comment]
@yegor256 just added 10 mins to @elenavolokhova (for QA), payment ID is `56000227`... Much appreciated! **1 hour** was added to your account, payment ID `000-b056ecdc`, time spent is 117 hours and 52 mins... there is a bonus for fast delivery (age=4)... +60 added to your rating, at the moment it is: [+9262](http://www.netbout.com/b/35008?open=rating)
