### ISSUE TITLE
TkLogged.java:74-79: I expect implementations of Response...

### ISSUE THREAD

**Issue by davvd** [yegor256/takes#174]
Puzzle `101-0be068b8` in `src/main/java/org/takes/facets/slf4j/TkLogged.java:74-79` has to be resolved: I expect implementations of Response and Take interfaces will be able convert itself to a loggable string but they don't have this feature. See details here https://github.com/yegor256/takes/issues/101 We will use toConsole() in this way this.target.log("...", this.origin.toConsole(), resp.toConsole, ...)... The puzzle was created by Dmitry Zaystev on 3-Apr-2015.

If you have any technical questions, don't ask me, submit new tickets instead

**Comment by davvd** [comment]
@yegor256 I set milestone here to `1.0`, let me know if it is wrong

**Comment by m4solutions** [comment]
If no one disagree, @davvd  could you assign this one to me?

**Comment by yegor256** [comment]
@davvd pls assign @m4solutions to this task

**Comment by davvd** [comment]
> @davvd pls assign @m4solutions to this task

@yegor256 done. @m4solutions the task is yours, please go ahead

**Comment by davvd** [comment]
@m4solutions you're holding this ticket for 18 days already. If it is not finished (and closed) in the next 24 hours, it will be re-assigned to someone else, see [No Obligations](http://www.xdsd.org/2014/04/13/no-obligations-principle.html) principle ([this article](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html) should help if you're stuck); as a reminder, don't forget to remove the `@todo` puzzle from the source code; -30 to your rating, your total score is [-30](http://www.netbout.com/b/35292?open=rating)

**Comment by marcuss** [comment]
sorry @davvd I didn't know how to manage the workflow on this, because this ticket is still open since there is another ticket Issues https://github.com/yegor256/takes/issues/199  asking for details on how to finish this one, @yegor256 is assigned to that one.

if this ticket should be close meanwhile, please do it.

**Comment by marcuss** [comment]
@davvd as my understanding this ticket should not be assigned to me, instead should be unassigned, or assigned to @yegor256  until this  https://github.com/yegor256/takes/issues/199 other issue is solved.

**Comment by yegor256** [comment]
@davvd assign me to this pls

**Comment by davvd** [comment]
> @davvd assign me to this pls

@yegor256 right, this task is yours, whoever worked before, please stop right now

**Comment by davvd** [comment]
@yegor256 The task is closed, thanks everybody

**Comment by davvd** [comment]
@elenavolokhova please, review this task for compliance with our [quality rules](http://www.teamed.io/qa.html)

**Comment by elenavolokhova** [comment]
@yegor256 Could you please clarify, why this ticket was closed? Was there any solution provided or not? It is not mentioned in any comment.

**Comment by yegor256** [comment]
@elenavolokhova the puzzle just disappeared from the source code. This ticket is definitely bad, we just close it.

**Comment by elenavolokhova** [comment]
@yegor256 Thank you!

**Comment by elenavolokhova** [comment]
@davvd Quality is bad here.

**Comment by elenavolokhova** [comment]
@davvd @yegor256 Will this QA review be paid?
