### ISSUE TITLE
Readme is unclear regarding FkRegex pattern syntax

### ISSUE THREAD

**Issue by longtimeago** [yegor256/takes#18]
There is an example in README
```java
new TsFork(
  new FkRegex(
    "/file/(?<path>[^/]+)",
    ...
)
```
but it's unclear what is the part of regex and what is not. For example, why do we need parentheses? Why question mark at the beginning?

**Comment by yegor256** [comment]
It's just a Java7 regular expression with a named groups, see http://stackoverflow.com/questions/415580/regex-named-groups-in-java

This `<path>` is the name of the group. Later, you can use this group like this: `matcher.group("path")`

**Comment by longtimeago** [comment]
@yegor256 you are right. Really forgot about that. Thanks!

**Comment by longtimeago** [comment]
@yegor256 by the way, I see that path can't contain ```/``` symbols.
But how in that case can we specify file path with dir and subdir?
For example, root path is ```/api/file```. Relative file path is ```foo/bar/some_file.txt```
Is there any way to match following url:
```/api/file/foo/bar/some_file.txt```
Github uses this way to point to the files and I'd like to use same approach for nerodesk

**Comment by yegor256** [comment]
Sure, try this regex:

```
/file/(?<path>.+)
```

**Comment by longtimeago** [comment]
Cool, thanks!
