### ISSUE TITLE
Iterator is a wrong concept for Fork.route()

### ISSUE THREAD

**Issue by yegor256** [yegor256/takes#187]
Let's replace it with something more appropriate, probably a custom interface `org.takes.misc.Opt`:

```java
interface Opt<T> {
  T get();
  boolean has();
}
```

**Comment by davvd** [comment]
@yegor256 added "bug" tag to this issue

**Comment by davvd** [comment]
@yegor256 milestone set to `1.0` (correct me if I am wrong)

**Comment by davvd** [comment]
@dmzaytsev it's yours,please go ahead

**Comment by davvd** [comment]
@yegor256 thanks for this report, I added 15 mins to your account, in transaction `000-dbcf3942`

**Comment by dmzaytsev** [comment]
@davvd I created the PR #188 for this task. Could you please find someone to review ?

**Comment by dmzaytsev** [comment]
@yegor256 #188 is fixing this issue, please close if that's all here, thank you

**Comment by yegor256** [comment]
@dmzaytsev thanks!

**Comment by davvd** [comment]
@elenavolokhova please, let us know what do you think about this ticket, according to our [QA rules](http://www.teamed.io/qa.html)

**Comment by elenavolokhova** [comment]
@davvd This ticket looks good.

**Comment by davvd** [comment]
> @davvd This ticket looks good.

@elenavolokhova thanks a lot :)

**Comment by davvd** [comment]
@dmzaytsev just added 10 mins to @elenavolokhova (for QA), payment ID is `56013672`... paid, thanks, added **38 mins** to your account, payment `56013684`, 55 hours and 35 mins was spent... there is a bonus for fast delivery (age=3243)... +38 to your rating, your total score is [+994](http://www.netbout.com/b/35166?open=rating)
