### ISSUE TITLE
Invalid LinkedIn id type is used in PsLinkedin

### ISSUE THREAD

**Issue by ikhvostenkov** [yegor256/takes#194]
When we parse response json in ```PsLinkedin``` we expect linkedin id as int, but this is alphanumeric according with https://developer-programs.linkedin.com/thread/2352:
```Java
return new Identity.Simple(
            String.format("urn:linkedin:%d", json.getInt("id")), props
        );
```
I've checked some IDs and all of them have only numbers, however I was not able to find any official information that ID is numeric value. Also in API examples ID is string:
```

sample api response

{
  "id": "1R2RtA",
  "numConnections": 42,
  "pictureUrl": "https://media.licdn.com/mpr/mprx/…"
}

```

**Comment by davvd** [comment]
@ikhvostenkov this task will get someone's attention soon

**Comment by davvd** [comment]
@ikhvostenkov I added milestone `1.0` to this issue, let me know if there has to be something else

**Comment by davvd** [comment]
@eg04lt3r this task is yours, please help (see our key [principles of work](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html)). If you have any technical questions, don't hesitate to ask right here... This task's budget is **30 mins**. This is exactly how much will be paid when the problem explained above is solved. See [this](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html) for more information

**Comment by davvd** [comment]
@ikhvostenkov thanks for tis bug, I topped your account for 15 mins, transaction `55871169`

**Comment by eg04lt3r** [comment]
@ikhvostenkov fixed in #203 pull request. Please, find someone to review this one. Thanks. 
And there is internal exception in Travis CI build: java.lang.NoClassDefFoundError: org/codehaus/plexus/util/DirectoryScanner

**Comment by ikhvostenkov** [comment]
@davvd Comment above should be addressed to you, I think.

**Comment by eg04lt3r** [comment]
@davvd please, close this task if ok.

**Comment by yegor256** [comment]
@eg04lt3r this task can be closed only by @ikhvostenkov , see http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html#1.-keep-it-one-on-one

**Comment by eg04lt3r** [comment]
@ikhvostenkov please,  close the task

**Comment by davvd** [comment]
@eg04lt3r the task is your hands for the last 19 days.. keep in mind that if it's not closed in the next 8 hours, it will be re-assigned to someone else, see [No Obligations](http://www.xdsd.org/2014/04/13/no-obligations-principle.html) principle. [This article](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html) should help if you're stuck

-30 to your rating, your total score is [-142](http://www.netbout.com/b/35234?open=rating)

**Comment by eg04lt3r** [comment]
@davvd I wrote to @ikhvostenkov to close the task. It's done 2 days ago. How I could close this task by myself?

**Comment by yegor256** [comment]
@eg04lt3r keep this in mind: http://www.teamed.io/policy.html#7

**Comment by eg04lt3r** [comment]
@yegor256 ok
11 мая 2015 г. 23:08 пользователь "Yegor Bugayenko" <
notifications@github.com> написал:

**Comment by davvd** [comment]
@eg04lt3r the task is overdue, and I have to re-assign it to someone else. Please, stop working with it immediately. In general, we're against overdue tasks, check [this page](http://www.xdsd.org/2014/04/13/no-obligations-principle.html)... added -60 to your rating, now it is equal to [-202](http://www.netbout.com/b/35234?open=rating)

**Comment by eg04lt3r** [comment]
@davvd ok, no problem.

**Comment by eg04lt3r** [comment]
@davvd  and please remove my code from repository, cause ticket is not closed yet.

**Comment by davvd** [comment]
@dmzaytsev please proceed, it's yours

**Comment by dmzaytsev** [comment]
@davvd @yegor256
the task has been performed already.
the issue has been resolved in PR #203 and merged.
I don't quite understand what I can to do here.

**Comment by yegor256** [comment]
@dmzaytsev there is nothing left, you're right, except the closing step, which hasn't been done yet. The task is still open and we have to ask @ikhvostenkov to accept it. You have to.

**Comment by dmzaytsev** [comment]
@ikhvostenkov close the task please

**Comment by ikhvostenkov** [comment]
@dmzaytsev Accepted and closed.

**Comment by eg04lt3r** [comment]
@ikhvostenkov thanks, man.

**Comment by davvd** [comment]
@elenavolokhova please, review this task for compliance with our [quality rules](http://www.teamed.io/qa.html)

**Comment by elenavolokhova** [comment]
@davvd According to our QA rules quality is good...

**Comment by davvd** [comment]
> @davvd According to our QA rules quality is good...

@elenavolokhova thank you

**Comment by davvd** [comment]
@dmzaytsev I added 10 mins to @elenavolokhova (for QA review) in transaction 57287915; thank you, added **1 hour** to your acc, payment num is `57287922`, 20 hours and 13 mins spent in total to complete; there is a bonus for fast delivery (m=1213); +60 added to your rating, current score is: [+1513](http://www.netbout.com/b/35166?open=rating)
