### ISSUE TITLE
Wrong json linkedin user fields are used

### ISSUE THREAD

**Issue by ikhvostenkov** [yegor256/takes#195]
According with linkedin API [example](https://developer.linkedin.com/docs/signin-with-linkedin)

```
Sample API response

{
  "firstName": "Frodo",
  "headline": "2nd Generation Adventurer",
  "id": "1R2RtA",
  "lastName": "Baggins",
  "siteStandardProfileRequest": {
    "url": "https://www.linkedin.com/profile/view?id=…"
  }
}
```
```firstName``` and ```lastName``` should be camel-case, we expect underscored:

```Java
 private static Identity parse(final JsonObject json) {
        final String fname = "first_name";
        final String lname = "last_name";
```

**Comment by davvd** [comment]
@ikhvostenkov we will find someone to do this task, soon

**Comment by davvd** [comment]
@ikhvostenkov there is no milestone yet, so I set it to `1.0`

**Comment by davvd** [comment]
@dmzaytsev it's yours, please go ahead

**Comment by davvd** [comment]
@ikhvostenkov thanks for tis bug, I topped your account for 15 mins, transaction `55870013`

**Comment by dmzaytsev** [comment]
@davvd I created the PR #202 for this task. Could you please find someone to review ?

**Comment by dmzaytsev** [comment]
@davvd we are wating for #158

please see details [here] (https://github.com/yegor256/takes/pull/202#issuecomment-96025759)

> @dmzaytsev let's wait for that task first? and when it's done, you add your test for this particular problem

**Comment by dmzaytsev** [comment]
@davvd we are wating #202

**Comment by dmzaytsev** [comment]
@yegor256 The issue resolved in  PR #202 
please close the task

**Comment by yegor256** [comment]
@dmzaytsev thanks!

**Comment by davvd** [comment]
@yegor256 please don't close it.. @ikhvostenkov could you please close it, if it is done?

**Comment by dmzaytsev** [comment]
@yegor256 my mistake, it should be addressed to @ikhvostenkov

 @ikhvostenkov #202 is fixing this issue, please close  if that's all here, thank you

**Comment by davvd** [comment]
@dmzaytsev this task is in your hands for 19 days already. added -30 to your rating, now it is equal to [+1355](http://www.netbout.com/b/35166?open=rating)

**Comment by dmzaytsev** [comment]
@davvd I wrote [16 days ago](https://github.com/yegor256/takes/issues/195#issuecomment-96125437)
>@davvd we are wating for #158

@yegor256  According [the policy ](http://www.teamed.io/policy.html#11) I informed the manager.
What's wrong ?

**Comment by dmzaytsev** [comment]
@ikhvostenkov close the task please

**Comment by yegor256** [comment]
@davvd we're waiting for #158 here

**Comment by davvd** [comment]
@dmzaytsev this task is not yours any more (took too long), please stop. I'll give you something else. -60 to your rating, your total score is [+1400](http://www.netbout.com/b/35166?open=rating)

**Comment by dmzaytsev** [comment]
@yegor256 I know about this http://www.teamed.io/policy.html#7 . The reporter has been asked  to close the task only three times... Seems I should have been more insistent...
So now I am talking about penalties. Twice I had warned @davvd about the delay however I was fined. I believe that 90 points should be added to my rating.
Seems @davvd never accept my requests without your confirmation, perhaps I shall ask you too in a future requests.

**Comment by davvd** [comment]
> @davvd we're waiting for #158 here

@yegor256 issue #158 is closed already

**Comment by davvd** [comment]
@komaz this task is yours, please help (see our key [principles of work](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html)). If you have any technical questions, don't hesitate to ask right here

The budget of this task is **30 mins**. This is exactly how much time will be compensated, when the task is completed. Read about our [Definition of Done](http://www.xdsd.org/2014/04/15/definition-of-done.html)

**Comment by komaz** [comment]
@davvd I don't understand what is left to be done here. For me it looks like @dmzaytsev did all required work in pull request [#202](https://github.com/yegor256/takes/pull/202) – fields are renamed, test is added, and all changes are already merged in master.

**Comment by yegor256** [comment]
@davvd please assign this back to @dmzaytsev

**Comment by yegor256** [comment]
@davvd assign @dmzaytsev to this

**Comment by davvd** [comment]
> @davvd assign @dmzaytsev to this

@yegor256 done, @dmzaytsev is a new assignment at the task, please go on. whoever worked with this task before, please stop right now

**Comment by dmzaytsev** [comment]
@ikhvostenkov could you please close the task ? thank you

**Comment by ikhvostenkov** [comment]
@dmzaytsev closed.

**Comment by davvd** [comment]
@dmzaytsev Much appreciated! **1 hour** was added to your account, payment ID `57307237`, time spent is 46 mins; m=46, that's why a bonus here for fast delivery; +60 added to your rating, at the moment it is: [+1573](http://www.netbout.com/b/35166?open=rating)
