### ISSUE TITLE
stream reading is too slow

### ISSUE THREAD

**Issue by yegor256** [yegor256/takes#205]
At the moment, in `RqPrint`, `RsPrint`, `RqMultipart` and in a few other places we're using `InputStream#read()`. This method reads the stream byte by byte. There is nothing wrong in this method, but it's slow on large streams. Let's replace that with `read(byte[])`.

Full list of places:

```
Searching 296 files for ".read()" (case sensitive)

/Volumes/ssd2/code/takes/src/main/java/org/takes/rq/RqLengthAware.java:
  127          public int read() throws IOException {
  128              --this.more;
  129:             return this.origin.read();
  130          }
  131      }

/Volumes/ssd2/code/takes/src/main/java/org/takes/rq/RqLive.java:
   64          final ByteArrayOutputStream baos = new ByteArrayOutputStream();
   65          while (true) {
   66:             final int data = input.read();
   67              if (data < 0) {
   68                  break;
   69              }
   70              if (data == '\r') {
   71:                 if (input.read() != '\n') {
   72                      throw new IOException("");
   73                  }

/Volumes/ssd2/code/takes/src/main/java/org/takes/rq/RqMultipart.java:
  149              RqMultipart.Base.skip(body, boundary.length - 2);
  150              while (body.available() > 0) {
  151:                 if (body.read() == '-') {
  152                      break;
  153                  }
  ...
  194              throws IOException {
  195              for (int idx = 0; idx < skip; ++idx) {
  196:                 stream.read();
  197              }
  198          }
  ...
  235              final ByteArrayOutputStream buf = new ByteArrayOutputStream();
  236              while (body.available() > 0) {
  237:                 final int data = body.read();
  238                  if (data < 0) {
  239                      break;

/Volumes/ssd2/code/takes/src/main/java/org/takes/rq/RqPrint.java:
  120          final InputStream input = new RqLengthAware(this).body();
  121          while (input.available() > 0) {
  122:             final int data = input.read();
  123              if (data < 0) {
  124                  break;

/Volumes/ssd2/code/takes/src/main/java/org/takes/rs/RsGzip.java:
   79          try {
   80              while (true) {
   81:                 final int data = input.read();
   82                  if (data < 0) {
   83                      break;

/Volumes/ssd2/code/takes/src/main/java/org/takes/rs/RsPrint.java:
  159          try {
  160              while (body.available() > 0) {
  161:                 final int data = body.read();
  162                  if (data < 0) {
  163                      break;

/Volumes/ssd2/code/takes/src/main/java/org/takes/rs/RsXSLT.java:
  170          final ByteArrayOutputStream baos = new ByteArrayOutputStream();
  171          while (true) {
  172:             final int data = input.read();
  173              if (data < 0) {
  174                  break;
```

**Comment by davvd** [comment]
@yegor256 I will find a developer for the task soon...

**Comment by davvd** [comment]
@yegor256 attached this issue to milestone "1.0" (let me know if this is wrong)

**Comment by davvd** [comment]
@cyberone the task is for you now, follow [these guidelines](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html). Don't hesitate to ask any technical questions right here

This task's budget is **30 mins**. This is exactly how much will be paid when the problem explained above is solved. See [this](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html) for more information

**Comment by davvd** [comment]
@yegor256 thanks for the report, I topped your acc for 15 mins, payment ID `000-55008c77`

**Comment by cyberone** [comment]
@davvd assign someone else please

**Comment by cyberone** [comment]
@davvd please assign this issue to someone else.

**Comment by davvd** [comment]
> @davvd please assign this issue to someone else. 

@cyberone -30 points to your rating

**Comment by davvd** [comment]
> @davvd please assign this issue to someone else. 

@cyberone I will assign somebody else to this issue

**Comment by davvd** [comment]
@ikhvostenkov the task is yours, please go ahead

**Comment by ikhvostenkov** [comment]
@yegor256 What is your opinion, if we use ```BufferedInputStream``` instead of ```read(byte[])```?

**Comment by yegor256** [comment]
@ikhvostenkov we already have `RqBuffered` and `RsBuffered` for that, but this is not a solution. Still, making 1000 calls to `read()` (even if through buffered input stream) is way slower than a single call to `read(byte[])`

**Comment by ikhvostenkov** [comment]
@yegor256 I've tried solution with ```read(byte[])``` and faced with problem in ```RqLive``` class. If we read stream in array and parse headers, after that we pass stream to ```body()```, but stream is already read and closed, so after that in ```RqPrint``` ```printBody``` we are not able to read stream. What will be solution here?

**Comment by yegor256** [comment]
@ikhvostenkov that's a good question, but it's your ticket :) find a solution and suggest it.

**Comment by ikhvostenkov** [comment]
@yegor256 I have only one idea here - use ```PushbackInputStream```, but this will not increase speed, can even make worse. So I prefer to give up here.

**Comment by ikhvostenkov** [comment]
@davvd Could you please assign someone else here.

**Comment by davvd** [comment]
> @davvd Could you please assign someone else here.

@ikhvostenkov 30 points deducted from your rating

**Comment by davvd** [comment]
> @davvd Could you please assign someone else here.

@ikhvostenkov right, I will find someone else, no problem

**Comment by davvd** [comment]
@dmzaytsev please go ahead with this task, it's yours

**Comment by dmzaytsev** [comment]
@davvd  take a look PR #283 please

**Comment by dmzaytsev** [comment]
@yegor256 PR #283 fixed the issue. please close if alright.

**Comment by yegor256** [comment]
@dmzaytsev thanks!

**Comment by davvd** [comment]
@dmzaytsev **1 hour** added to your account (payment number `57307248`), many thanks for your contribution! 21 hours and 34 mins spent here.... the bonus for fast delivery (m=1294)... added +60 to your rating, now it is equal to [+1633](http://www.netbout.com/b/35166?open=rating)
