### ISSUE TITLE
Travis-CI build failing for java 8

### ISSUE THREAD

**Issue by erimerturk** [yegor256/takes#213]
travis-ci build is failling because of ClassNotfound exception. You can find see exception detail from given url.

https://travis-ci.org/yegor256/takes/jobs/60197872

**Comment by m4solutions** [comment]
Also saw the same problem when working on my issue, you can see the logs here:
https://travis-ci.org/yegor256/takes/jobs/61089833

fails only for java 8.

**Comment by Bertram25** [comment]
According to Travis-ci builds, the build also fails for openJDK6:
https://travis-ci.org/yegor256/takes/jobs/61287612
First error lines:
`[ERROR] pool-1-thread-5 com.jcabi.aspects.aj.MethodValidator: JSR-303 validator thrown during initialization: java.lang.UnsupportedClassVersionError: javax/el/ExpressionFactory : Unsupported major.minor version 51.0`

**Comment by davvd** [comment]
@erimerturk this task will get someone's attention soon

**Comment by davvd** [comment]
@erimerturk since there is no milestone yet I set it to "1.0"

**Comment by davvd** [comment]
@dmzaytsev the task is yours plz proceed

**Comment by dmzaytsev** [comment]
@erimerturk I believe it's outside of scope of Takes
There is a qulice issue. It would be better to create a ticket [here](https://github.com/teamed/qulice)

https://travis-ci.org/yegor256/takes/jobs/60197872 line 3672
>[ERROR] Failed to execute goal com.qulice:qulice-maven-plugin:0.12:check (jcabi-check) on project takes: Execution jcabi-check of goal com.qulice:qulice-maven-plugin:0.12:check failed: A required class was missing while executing com.qulice:qulice-maven-plugin:0.12:check: org/codehaus/plexus/util/DirectoryScanner

@yegor256 what do you think ?

**Comment by yegor256** [comment]
@dmzaytsev I think you're right, feel free to create a ticket in qulice

**Comment by dmzaytsev** [comment]
@yegor256 ok, I  will create a ticket.
what shall we do with this task ?

**Comment by yegor256** [comment]
@dmzaytsev put it on hold, until that ticket in qulice is resolved

**Comment by dmzaytsev** [comment]
@davvd we are waiting teamed/qulice#431

**Comment by yegor256** [comment]
@davvd put this on hold pls, until that qulice issue is solved

**Comment by davvd** [comment]
> @davvd put this on hold pls, until that qulice issue is solved

@yegor256 of course, take your time

**Comment by erimerturk** [comment]
@dmzaytsev i agree to you, it is about qulice.

**Comment by erimerturk** [comment]
@davvd will you pay for this bug ? i think, it is releated to [bugs wellcome] (http://www.yegor256.com/2014/04/13/bugs-are-welcome.html).

**Comment by yegor256** [comment]
@erimerturk definitely

**Comment by yegor256** [comment]
@davvd pls add extra 15 mins to @erimerturk

**Comment by davvd** [comment]
> @davvd pls add extra 15 mins to @erimerturk 

@yegor256 15 mins extra was just paid to @erimerturk, transaction `AP-2B936415TY740462G`

**Comment by davvd** [comment]
@erimerturk thank you for the ticket reported, I topped your account for 15 mins, transaction `AP-6UX74103FB0627624`

**Comment by dmzaytsev** [comment]
@erimerturk I guess it already fixed 
see https://github.com/yegor256/takes/commit/e3f1155574929fd02e79a7f0b5f1493984950d13

please close the ticket

**Comment by davvd** [comment]
@ypshenychka please, check this issue for QA compliance, as per [par.24](http://www.teamed.io/policy.html#24)

**Comment by ypshenychka** [comment]
@davvd Quality is good.

**Comment by davvd** [comment]
> @davvd Quality is good.

@ypshenychka thank you ;)

**Comment by davvd** [comment]
@dmzaytsev added 10 mins to @ypshenychka, for QA review, payment code is `67817503`. thanks, I just added **30 mins** to your account, payment `67817508`, 3952 hours and 30 mins spent. +30 added to your rating, current score is: [+1417](http://www.netbout.com/b/35166?open=rating)
