### ISSUE TITLE
RsWithType duplicates headers

### ISSUE THREAD

**Issue by yegor256** [yegor256/takes#217]
If I do like this:

```
new RsWithType(new RsWithType("text/xml"), "text/plain");
```

I will get:

```
HTTP/1.1 200 OK
Content-Type: text/xml
Content-Type: text/plain
```

Let's use `RsWithoutHeader` to prevent this from happening.

**Comment by m4solutions** [comment]
If i get this task, is about changing wherever the project use 
``new RsWithType(new RsWithType(``
To decorate a response we should use RsWithoutHeader instead, right?

**Comment by Bertram25** [comment]
@yegor256 
Sorry for pinging. :) It seems @m4solutions didn't add a username as the start of his message. Thus, I'm humbly doing it now so we have an answer and maybe he can start working on this issue.
Best regards,

**Comment by yegor256** [comment]
@m4solutions yes, `RsWithType` should use do `RsWithoutHeader` first and then `RsWithHeader`

**Comment by davvd** [comment]
@yegor256 this task will get someone's attention soon

**Comment by davvd** [comment]
@yegor256 milestone set to `1.0` (correct me if I am wrong)

**Comment by davvd** [comment]
@bertram25 please pick this up, and keep in mind [these instructions](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html). Any technical questions - ask right here; The cost of this task is **30 mins** (this is exactly how much will be paid, not less not more), when the task is [done](http://www.xdsd.org/2014/04/15/definition-of-done.html)

**Comment by davvd** [comment]
@yegor256 thanks for the ticket, your account was topped for 15 mins, payment 000-007e8d89

**Comment by Bertram25** [comment]
I'm on it :)

@yegor256 Sorry for disturbing. I need some info:
> yes, RsWithType should use do RsWithoutHeader first and then RsWithHeader

If I understand well, you want to see RsWithType decorated so that it auto-selects RsWith/WithoutHeader, right? (Not just plain search and replace in the code where  `new RsWithType(new RsWithType())` is found.)

If so, can you confirm that what you want in the given use case is this: 
```
...
new rsWithType(new RsWithType("Y"), "X");
-> 'Content-Type: Y'. (or first given header content-type only.)
```

What about such a use case? Should it be handled?
```
new rsWithType(new RsText(new RsWithType("Y"), "URL"), "X");
-> ...
'Content-Type: Y'.
...
```

Thanks for your answer and best regards,

**Comment by yegor256** [comment]
@Bertram25 I'm expecting this:

```
...
new RsWithType(new RsWithType("Y"), "X");
-> 'Content-Type: X'. (or last given content-type header only.)
```

Every time I use `RsWithType`, the content type is changed and previous one is removed. Make sense?

**Comment by Bertram25** [comment]
@yego256 Make sense. Perfect, thanks.

**Comment by Bertram25** [comment]
@yegor256 Hi,
This issue is now fixed and can be closed.
Best regards,

**Comment by yegor256** [comment]
@Bertram25 thanks!

**Comment by davvd** [comment]
@elenavolokhova please, review this ticket for compliance with our [QA rules](http://www.teamed.io/qa.html)

**Comment by elenavolokhova** [comment]
@Bertram25 There is some mess with comments.
This one is not addressed:
>marcuss commented 18 days ago
If i get this task, is about changing wherever the project use ...

This one should start with the user name:
>Bertram25 commented 4 days ago
I'm on it :)
@yegor256 Sorry...

Typo here (should be yegor256 instead of yego256):
>Bertram25 commented 4 days ago
@yego256 Make sense. Perfect, thanks.

 According to our [quality rules](http://www.teamed.io/qa.html):
 > Messages in a ticket always start with a name of a user they are addressed to.
 
 As far as you are the performer of this ticket you are responsible for its quality. Please make sure that everyone follows this rule in your tickets in the future. Ask them to fix issues before closing the ticket.
 
 Please confirm that everything is clear and you have no questions regarding this approach.

**Comment by Bertram25** [comment]
@elenavolokhova 
Sorry but I won't. I've just been thrown away, you'll have to find someone else to "clean the mess".

**Comment by elenavolokhova** [comment]
@davvd Quality is acceptable here.

**Comment by Bertram25** [comment]
@elenavolokhova Hi again,
I've been talking with @yegor256 this morning and it seems I'm still part of the team after all. I thus apologize for earlier refusing the task.
If you accept to give me another hour, I'll do what's requested.
Just tell me. Thanks and best regards,

**Comment by elenavolokhova** [comment]
@Bertram25 Good to hear that! Yes, sure. Please fix your comments and don't forget to review your ticket next time. Thanks.

**Comment by Bertram25** [comment]
@elenavolokhova Thanks a lot!

> Please confirm that everything is clear and you have no questions regarding this approach.

I understand the rule and will review my tickets before closing next time. (Sorry, it was my first time here.)

There is one of your comments I'm sure to fully understand though:

>This one is not addressed:

>> marcuss commented 18 days ago
If i get this task, is about changing wherever the project use ...

Does this mean I should answer the question, or ask the author to add a @ name at the first line to whom he was speaking with, or both?

Regards,

**Comment by elenavolokhova** [comment]
@Bertram25 Just ask to add the name in such case next time. It is important to do it before ticket is closed and make sure that all issues from our QA rules are fixed.

**Comment by Bertram25** [comment]
@elenavolokhova Understood. I will do it now.

**Comment by Bertram25** [comment]
@marcuss 

> If i get this task, is about changing wherever the project use
new RsWithType(new RsWithType(
To decorate a response we should use RsWithoutHeader instead, right?

Could you add the person's @ name your were asking to in your aforementioned issue comment (as comment start)?

Thanks in advance.

**Comment by davvd** [comment]
> @davvd Quality is acceptable here.

@elenavolokhova thanks for the review, we'll try better next time

**Comment by davvd** [comment]
@bertram25 10 mins was added to the account of @elenavolokhova (for QA review), in transaction 57368646

Much obliged! I have added **30 mins** to your account in payment "AP-53H758682S572415U", 192 hours and 58 mins spent

+30 added to your rating, current score is: [+30](http://www.netbout.com/b/35317?open=rating)
