### ISSUE TITLE
BkBasic and BkParallel are not tested

### ISSUE THREAD

**Issue by m4solutions** [yegor256/takes#220]
BkBasic and BkParallel are not tested, even when they have 100+ lines of code.
and that BkBasic is used in the BkTimeable Test

**Comment by davvd** [comment]
@m4solutions I am aware of the task, give me some time to find a developer...

**Comment by davvd** [comment]
@m4solutions there is no milestone yet, so I set it to `1.0`

**Comment by davvd** [comment]
@m4solutions thanks for tis bug, I topped your account for 15 mins, transaction `56368001`

**Comment by davvd** [comment]
@dmzaytsev it's yours, please go ahead

**Comment by dmzaytsev** [comment]
@m4solutions the PR #223 has been merged. Could you close the task please ?

**Comment by m4solutions** [comment]
Close

**Comment by dmzaytsev** [comment]
@m4solutions you should close the issue
type a comment e.g. @dmzaytsev thank you :) 
and click the button "close and comment"

**Comment by dmzaytsev** [comment]
@m4solutions According to our [quality rules](http://www.teamed.io/qa.html):
>Messages in a ticket always start with a name of a user they are addressed to.

please fix your message, thank you

**Comment by m4solutions** [comment]
@dmzaytsev thank you

**Comment by davvd** [comment]
@m4solutions the code made here contains a puzzle `220-30ba5607`/#227, which will be resolved soon

**Comment by davvd** [comment]
@elenavolokhova please, review this task for compliance with our [quality rules](http://www.teamed.io/qa.html)

**Comment by elenavolokhova** [comment]
@davvd Quality is good here!

**Comment by davvd** [comment]
> @davvd Quality is good here!

@elenavolokhova thanks a lot

**Comment by davvd** [comment]
> @davvd Quality is good here!

@elenavolokhova thanks for the review and a good remark

**Comment by davvd** [comment]
> @davvd Quality is good here!

@elenavolokhova many thanks

**Comment by davvd** [comment]
> @davvd Quality is good here!

@elenavolokhova thanks!

**Comment by davvd** [comment]
> @davvd Quality is good here!

@elenavolokhova thanks for the review and a good remark

**Comment by davvd** [comment]
> @davvd Quality is good here!

@elenavolokhova thanks a lot

**Comment by davvd** [comment]
> @davvd Quality is good here!

@elenavolokhova thanks for the review and a good remark

**Comment by davvd** [comment]
@dmzaytsev I added 10 mins to @elenavolokhova (for QA review) in transaction 56875162. Thanks for your contribution, **45 mins** was added to your account, payment ID is `56875171`, 31 hours and 48 mins spent total. the bonus for fast delivery (m=1908). +45 added to your rating, at the moment it is: [+1295](http://www.netbout.com/b/35166?open=rating)

**Comment by davvd** [comment]
@marcuss last puzzled solved `220-30ba5607`/#227
