### ISSUE TITLE
Basic Authentication

### ISSUE THREAD

**Issue by dmzaytsev** [yegor256/takes#221]
We have not a Pass implementation for Basic Authentication(RFC-2617). I believe it has to be.
This class should  have  BasicAuth as one of a Ctor parameters.
Something like this
```
interface BasicAuth {
  Identity fetch(String user, String passwd);
}
```

**Comment by yegor256** [comment]
@dmzaytsev totally agree, but I would call it `PsBasic`

**Comment by davvd** [comment]
@dmzaytsev this task will get someone's attention soon

**Comment by davvd** [comment]
@dmzaytsev milestone set to `1.0` (correct me if I am wrong)

**Comment by davvd** [comment]
@dmzaytsev thanks for this report, I added 15 mins to your account, in transaction `56387869`

**Comment by davvd** [comment]
@cyberone it's yours,please go ahead

**Comment by cyberone** [comment]
@davvd please assign someone else. Too busy.

**Comment by davvd** [comment]
> @davvd please assign someone else. Too busy. 

@cyberone 30 points deducted from your rating

**Comment by davvd** [comment]
> @davvd please assign someone else. Too busy. 

@cyberone OK, I will try to assign someone else

**Comment by davvd** [comment]
> @davvd please assign someone else. Too busy. 

@cyberone I deducted 30 points from your rating

**Comment by davvd** [comment]
> @davvd please assign someone else. Too busy. 

@cyberone someone else will help in this task, no problem at all

**Comment by davvd** [comment]
> @davvd please assign someone else. Too busy. 

@cyberone 30 points deducted from your rating

**Comment by davvd** [comment]
> @davvd please assign someone else. Too busy. 

@cyberone I will assign somebody else to this issue

**Comment by davvd** [comment]
> @davvd please assign someone else. Too busy. 

@cyberone I deducted 30 points from your rating

**Comment by davvd** [comment]
> @davvd please assign someone else. Too busy. 

@cyberone got it, someone else will be assigned soon

**Comment by davvd** [comment]
> @davvd please assign someone else. Too busy. 

@cyberone -30 points to your rating

**Comment by davvd** [comment]
> @davvd please assign someone else. Too busy. 

@cyberone I will assign somebody else to this issue

**Comment by cyberone** [comment]
@davvd I've got 5 times -30 to my rating, refund 4 of them please.

**Comment by davvd** [comment]
> @davvd please assign someone else. Too busy. 

@cyberone -30 points to your rating

**Comment by davvd** [comment]
> @davvd please assign someone else. Too busy. 

@cyberone I will ask somebody else to pick this up

**Comment by davvd** [comment]
@celezar could you please pick this up? This [article](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html) explains how we work. Any technical questions you may ask right here

Budget here is **30 mins** (keep [this principle](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html) in mind)

**Comment by celezar** [comment]
@davvd please reasign this task to someone else. i also requested in netbout not to get more tasks because i don't have time to work on it.

**Comment by yegor256** [comment]
@davvd assign this to someone else pls

**Comment by davvd** [comment]
> @davvd assign this to someone else pls

@yegor256 30 points was deducted from your rating

**Comment by davvd** [comment]
> @davvd assign this to someone else pls

@yegor256 I will assign somebody else to this issue

**Comment by davvd** [comment]
@ekondrashev please proceed,it's yours

**Comment by davvd** [comment]
@antonini can you please help? Keep in mind [this](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html). If you have any technical questions, don't hesitate to ask right here

This task's budget is **30 mins**. This is exactly how much will be paid when the problem explained above is solved. See [this](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html) for more information

**Comment by antonini** [comment]
I didn't understood how to implement the Interface. Or is to add the interface to the source?

**Comment by antonini** [comment]
@davvd I didn't understood what need to be done. Is just to create an interface or need to be implemented?

**Comment by yegor256** [comment]
@dmzaytsev could you please help here as an author of the ticket?

**Comment by dmzaytsev** [comment]
@antonini 
* you have to  create class `org.takes.facets.auth.PsBasic` as an implementation of the `Pass` interface like already implemented classes in `org.takes.facets.auth.*`
* you have to create the interface 'Entry' inside this class `PsBasic`

like this
```
public final class PsBasic implements Pass {
    public final PstBasic(PsBasic.Entry entry){
    }
....
    public static interface Entry{
        boolean check(String user, String pwd);
    }
}

**Comment by antonini** [comment]
@davvd PR #327 is available and waiting for review.

**Comment by davvd** [comment]
@antonini the task is your hands for the last 15 days.. keep in mind that if it's not closed in the next 48 hours, it will be re-assigned to someone else, see [No Obligations](http://www.xdsd.org/2014/04/13/no-obligations-principle.html) principle. [This article](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html) should help if you're stuck; added -30 to your rating, now it is equal to [+76](http://www.netbout.com/b/35346?open=rating)

**Comment by antonini** [comment]
@davvd I understood about the No Obligations principle, but It took 8 days to someone answer my question. I think this should be taken into account.

**Comment by dmzaytsev** [comment]
@antonini FYI http://www.teamed.io/policy.html#10

**Comment by antonini** [comment]
@dmzaytsev Need more time. Solving the code that was reviewed.

**Comment by dmzaytsev** [comment]
@antonini I'm just the ticket reporter here :)
@davvd is the project manager. Ask him

**Comment by antonini** [comment]
@dmzaytsev Ops... @davvd Need more time. Solving the code that was reviewed.

**Comment by yegor256** [comment]
@davvd we need more time here

**Comment by davvd** [comment]
> @davvd we need more time here

@yegor256 yes, take your time, thanks for letting me know

**Comment by dmzaytsev** [comment]
@antonini  is there any progress on the ticket ?

**Comment by antonini** [comment]
@dmzaytsev I've received some reviews from @yegor256 and I'm working on it.

**Comment by dmzaytsev** [comment]
@antonini thanks!

**Comment by dmzaytsev** [comment]
@antonini thanks

**Comment by dmzaytsev** [comment]
@yegor256 please release it

**Comment by davvd** [comment]
@ypshenychka please, let us know what do you think about this ticket, according to our [QA rules](http://www.teamed.io/qa.html)

**Comment by ypshenychka** [comment]
@davvd Quality is good here.

**Comment by davvd** [comment]
> @davvd Quality is good here.

@ypshenychka thank you

**Comment by davvd** [comment]
@antonini I added 10 mins to @ypshenychka (for QA review) in transaction 59121414; Thanks for your contribution, **30 mins** was added to your account, payment ID is `AP-8ET854868R895722R`, 627 hours and 3 mins spent total; +30 added to your rating, at the moment it is: [+166](http://www.netbout.com/b/35346?open=rating)
