### ISSUE TITLE
RqMultipart doesn't provide size of file uploaded

### ISSUE THREAD

**Issue by krzyk** [yegor256/takes#226]
`RqMultipart` interface doesn't provide a way to get the real (uncompressed, without multipart headers/footers) file size uploaded by the user.
It should provide such method get each file size as it already reads the whole stream.

Basically when `RqMultipart` is used on a request which uploads a file of size e.g. 100 bytes, there has to be a method that provides a long value `100`.

**Comment by yegor256** [comment]
@krzyk how about this:

```
new RqMultipart(req).part("file").iterator().next().body().available()
```

**Comment by krzyk** [comment]
@yegor256 yes, that works :)

**Comment by yegor256** [comment]
@krzyk well, it works, but only with files smaller than 2Gb :(

**Comment by yegor256** [comment]
@krzyk up to `Integer.MAX_VALUE`, to be precise
