### ISSUE TITLE
BkParallelTest.java:32-34: This unit test not implemented...

### ISSUE THREAD

**Issue by davvd** [yegor256/takes#227]
Puzzle `220-30ba5607` in `src/test/java/org/takes/http/BkParallelTest.java:32-34` has to be resolved: This unit test not implemented but has to be. E.g. you could pass your own a ExecutorService implementation to the ctor and verify execute() calls. But feel free to try another way.... The puzzle was created by Dmitry Zaytsev on 29-Apr-2015.

If you have any technical questions, don't ask me, submit new tickets instead

**Comment by davvd** [comment]
@cyberone please proceed, it's yours

**Comment by davvd** [comment]
@yegor256 since there is no milestone yet I set it to "1.0"

**Comment by cyberone** [comment]
@davvd please review https://github.com/yegor256/takes/pull/246

**Comment by cyberone** [comment]
@davvd reassign please

**Comment by yegor256** [comment]
@davvd assign someone else here pls

**Comment by davvd** [comment]
> @davvd reassign please

@cyberone deducted 30 from your rating :(

**Comment by davvd** [comment]
> @davvd reassign please

@cyberone right, I'll try to find someone else for this task

**Comment by davvd** [comment]
> @davvd assign someone else here pls

@yegor256 -30 points to your rating :(

**Comment by davvd** [comment]
> @davvd assign someone else here pls

@yegor256 got it, someone else will be assigned soon

**Comment by yegor256** [comment]
@davvd where we are here?

**Comment by davvd** [comment]
@komaz the task is for you now, follow [these guidelines](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html). Don't hesitate to ask any technical questions right here; Task's budget is **30 mins** (see [this](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html) for explanation)

**Comment by komaz** [comment]
@davvd fixed in pull request [#282](https://github.com/yegor256/takes/pull/282), pull request is merged, please close the issue

**Comment by davvd** [comment]
@yegor256 We are done here, thanks all

**Comment by davvd** [comment]
@elenavolokhova review this ticket please, for compliance with our [quality rules](http://www.teamed.io/qa.html)

**Comment by elenavolokhova** [comment]
@davvd Looks good.

**Comment by davvd** [comment]
> @davvd Looks good.

@elenavolokhova thanks, got it, great to see high-quality tickets here

**Comment by davvd** [comment]
@komaz I added 10 mins to @elenavolokhova (for QA review) in transaction 57288706

Much obliged! I have added **30 mins** to your account in payment "AP-7P4398199J5420904", 87 hours and 58 mins spent

added +30 to your rating, now it is equal to [+30](http://www.netbout.com/b/35322?open=rating)
