### ISSUE TITLE
PsGithub sends invalid POST request

### ISSUE THREAD

**Issue by dmzaytsev** [yegor256/takes#229]
PsGithub puts POST-parameters into the request uri
```
POST /login/oauth/access_token?code=11111&redirect_uri=http%3A%2F%2Fwww.example.com%2F%3Fcode%3DGitHubCode&client_secret=key&client_id=app HTTP/1.1
Accept: application/xml
Host: localhost:50804
Connection: keep-alive
Content-type: application/x-www-form-urlencoded
Content-Length: 0

```

instead the request body

```
POST /login/oauth/access_token HTTP/1.1
Accept: application/xml
Host: localhost:50804
Connection: keep-alive
Content-type: application/x-www-form-urlencoded

code=11111&redirect_uri=http%3A%2F%2Fwww.example.com%2F%3Fcode%3DGitHubCode&client_secret=key&client_id=app
```

Github accepts such request but it is undocumented feature I  believe  we should use valid POST requests

**Comment by davvd** [comment]
@dmzaytsev I am aware of the task, give me some time to find a developer...

**Comment by davvd** [comment]
@dmzaytsev since there is no milestone yet I set it to "1.0"

**Comment by davvd** [comment]
@dmzaytsev thanks for the ticket, your account was topped for 15 mins, payment 56417115

**Comment by davvd** [comment]
@cyberone please go ahead with this task,it's yours

**Comment by cyberone** [comment]
@davvd please review https://github.com/yegor256/takes/pull/238

**Comment by cyberone** [comment]
@dmzaytsev the corresponding PR is merged. You may close the ticket.

**Comment by dmzaytsev** [comment]
@cyberone thanks

**Comment by davvd** [comment]
@dmzaytsev the code made here contains a puzzle `229-401562da`/#243, which will be resolved soon

**Comment by davvd** [comment]
@elenavolokhova please, review this ticket for compliance with our [QA rules](http://www.teamed.io/qa.html)

**Comment by elenavolokhova** [comment]
@davvd This ticket is good

**Comment by davvd** [comment]
> @davvd This ticket is good

@elenavolokhova thanks a lot

**Comment by davvd** [comment]
> @davvd This ticket is good

@elenavolokhova thank you

**Comment by davvd** [comment]
> @davvd This ticket is good

@elenavolokhova thanks for the review

**Comment by davvd** [comment]
> @davvd This ticket is good

@elenavolokhova thank you, good quality is always good :)

**Comment by davvd** [comment]
> @davvd This ticket is good

@elenavolokhova thanks for the review

**Comment by davvd** [comment]
> @davvd This ticket is good

@elenavolokhova thanks!

**Comment by davvd** [comment]
> @davvd This ticket is good

@elenavolokhova thanks a lot

**Comment by davvd** [comment]
@cyberone I added 10 mins to @elenavolokhova (for QA review) in transaction 56878068... I just added **45 mins** to your account, many thanks for your contribution.. 56878073 spent here... m=1468, that's why a bonus here for fast delivery... +45 added to your rating, current score is: [+83](http://www.netbout.com/b/35076?open=rating)

**Comment by davvd** [comment]
@dmzaytsev the last puzzle `229-401562da`/#243 originated from here solved
