### ISSUE TITLE
How to test org.takes.ts.fork.Target implementation?

### ISSUE THREAD

**Issue by longtimeago** [yegor256/takes#23]
I'm faced with a problem trying to test this code
```java
public final class TkGetFile implements Target<RqRegex> {
...
    @Override
    public Take route(final RqRegex req)
        throws IOException {
        return new TkHTML(
            this.storage.get(
                req.matcher().group("path")
            )
        );
    }
}
```
In test to call ```route``` I need to provide a ```RqRegex```. Unfortunately, I can't mock it, because ```RqRegex.matcher()``` returns ```java.util.regex.Matcher``` which is final and can't be mocked.
So, the only way I've found is to create real Matcher (yees, using Pattern) but this is really overkill :(

Is there any other possible way?

**Comment by yegor256** [comment]
Well, there are two options to test this class. First one:

```java
final RqRegex req = new RqRegex() {
  @Override
  public Matcher matcher() {
    return Pattern.compile("(?<path>.*)").match("/a/b/c.txt");
  }
};
final Take take = new TkGetFile().route(new RqRegex());
// your test code
```

Second one:

```java
final Take take = new TsFork(
  new FkRegex("(?<path>.*)", new TkGetFile())
).route(new RqFake("GET", "/a/b/c.txt"));
// your test code
```

Whichever you prefer :)

**Comment by longtimeago** [comment]
The first approach is not very suitable, as we also have to implement 2 methods from ```Request``` interface :(

Second one is also not a solution, because ```Take.route()``` expects ```RqRegex```, not a ```Request```. So, ```RqFake``` can't be used there ...

**Comment by yegor256** [comment]
`Take.route()` can't expect anything except `Request`... what do you mean?

**Comment by longtimeago** [comment]
My fault. I'm talking about ```Target.route()```, not ```Take.route()```
Please, take a look at the code in the issue description.

**Comment by yegor256** [comment]
@longtimeago yes, I noticed that. that's why I'm suggesting to wrap it into `FkRegex` for this test:

```
final Take take = new TsFork(
  new FkRegex("(?<path>.*)", new TkGetFile())
).route(new RqFake("GET", "/a/b/c.txt"));
// your test code
```

`FkRegex` will convert your `RqFake` into `RqRegex` required by `TkGetFile`

**Comment by longtimeago** [comment]
@yegor256 looks like overkill ... anyway, thanks!
