### ISSUE TITLE
PsTwitterTest.java:42-47: Test to be implemented for...

### ISSUE THREAD

**Issue by davvd** [yegor256/takes#230]
Puzzle `11-790c0445` in `src/test/java/org/takes/facets/auth/social/PsTwitterTest.java:42-47` has to be resolved: Test to be implemented for PsTwitter using a oauth mock library (eg:wiremock). Need to modify PsTwitter to accept url from configurations, so that url can be changed for test and real env accordingly. Response to be stubbed for both token and verify_credentials calls and assertions to be performed for the values returned.... The puzzle was created by Prasath Premkumar on 20-Apr-2015.

If you have any technical questions, don't ask me, submit new tickets instead

**Comment by davvd** [comment]
@ikhvostenkov please go ahead with this task,it's yours

**Comment by davvd** [comment]
@yegor256 there is no milestone yet, so I set it to `1.0`

**Comment by ikhvostenkov** [comment]
@davvd Could you please assign someone else to this task?

**Comment by davvd** [comment]
> @davvd Could you please assign someone else to this task?

@ikhvostenkov 30 points deducted from your rating

**Comment by davvd** [comment]
> @davvd Could you please assign someone else to this task?

@ikhvostenkov got it, someone else will be assigned soon

**Comment by davvd** [comment]
@yamstranger please go ahead with this task, it's yours

**Comment by YamStranger** [comment]
@davvd Thanks

**Comment by YamStranger** [comment]
@davvd Please help me. I don't understand this words "Puzzle 11-790c0445" what is "11-790c0445"? Is this some id of puzzle specification, of something else?

**Comment by yegor256** [comment]
@YamStranger yes, it's just an id of the puzzle

**Comment by YamStranger** [comment]
@yegor256 Can I get some info about this puzzle, by this id? Where can I find this info, if it is possible?

**Comment by yegor256** [comment]
@YamStranger what kind of info do you need? everything you need (and we have) is in the Java file

**Comment by YamStranger** [comment]
@yegor256 Thanks. It was info what I need. This is just id, and it will be not useful for me (I cant use it any way)

**Comment by YamStranger** [comment]
@davvd , @yegor256. As wrote @alice, I am not with your team any more. So please assign ticket to someone else. Thanks

**Comment by davvd** [comment]
> @davvd , @yegor256. As wrote @alice, I am not with your team any more. So please assign ticket to someone else. Thanks

@yamstranger OK, I will try to assign someone else

**Comment by davvd** [comment]
@adko-pl please proceed, it's yours

**Comment by adko-pl** [comment]
@davvd Can I get an extension on this ticket? I need to fix code review comments.

**Comment by yegor256** [comment]
@davvd give us more time here pls

**Comment by davvd** [comment]
> @davvd give us more time here pls

@yegor256 of course, thanks for letting me know, take your time

**Comment by adko-pl** [comment]
@davvd the code has been merged, please close this ticket

**Comment by davvd** [comment]
@yegor256 Thanks, closed

**Comment by davvd** [comment]
@ypshenychka please, review this task for compliance with our [quality rules](http://www.teamed.io/qa.html)

**Comment by ypshenychka** [comment]
@adko-pl 
According to our [QA Rules](http://www.teamed.io/qa.html):
>Some of ticket messages must mention all pull requests where the problem was actually fixed.

Please indicate in any of your messages link to corresponding PR.

**Comment by adko-pl** [comment]
@ypshenychka I fixed the QA issues in this ticket

**Comment by ypshenychka** [comment]
@adko-pl Thanks!

**Comment by ypshenychka** [comment]
@davvd Quality is acceptable.

**Comment by davvd** [comment]
> @davvd Quality is acceptable.

@ypshenychka thanks for the QA review, we'll work better next time

**Comment by davvd** [comment]
@adko-pl just added 10 mins to @ypshenychka (for QA), payment ID is `59387582`. Thank you, I have added **30 mins** to your account in payment/transaction "`AP-6Y065313U9637230D`", time consumed: 604 hours and 34 mins. +30 added to your rating, at the moment it is: [-150](http://www.netbout.com/b/35150?open=rating)
