### ISSUE TITLE
FtRemote hides TkFork response status

### ISSUE THREAD

**Issue by dmzaytsev** [yegor256/takes#231]
Access to invalid url returns 500 error instead 404
however  TkFork returns 404  (see TkFork.java:104)

```
new FtRemote(new TkFork(
            new FkRegex("/path/a", new TkText("a")),
            new FkRegex("/path/b", new TkText("b"))
        )).exec(
            new FtRemote.Script() {
                @Override
                public void exec(final URI home) throws IOException {
                    new JdkRequest(String.format("%s/path/c", home))
                        .fetch()
                        .as(RestResponse.class)
                        .assertStatus(HttpURLConnection.HTTP_NOT_FOUND);
                }
            }
        );
```

```
java.lang.AssertionError: HTTP response status is not equal to 404:
500 Internal Error [http://localhost:60934/path/c]
Content-Length: 453
Content-Type: text/plain
```
I think FtRemote should return a valid response status

**Comment by yegor256** [comment]
@dmzaytsev it's a bug in `BkBasic`, not in `TkFork`. `BkBasic` doesn't understand `HttpException` and treats it like any other exception, but it should treat it differently and understand it's `code()`

**Comment by davvd** [comment]
@dmzaytsev I am aware of the task, give me some time to find a developer...

**Comment by davvd** [comment]
@dmzaytsev there is no milestone yet, so I set it to `1.0`

**Comment by davvd** [comment]
@dmzaytsev thanks for tis bug, I topped your account for 15 mins, transaction `56430640`

**Comment by davvd** [comment]
@cyberone the task is yours, please go ahead

**Comment by cyberone** [comment]
@davvd please review https://github.com/yegor256/takes/pull/261

**Comment by cyberone** [comment]
@yegor256 the PR is merged, close the issue please.

**Comment by yegor256** [comment]
@cyberone it's not my ticket

**Comment by dmzaytsev** [comment]
@cyberone thanks!

**Comment by davvd** [comment]
@elenavolokhova please, review this task for compliance with our [quality rules](http://www.teamed.io/qa.html)

**Comment by elenavolokhova** [comment]
@cyberone
 According to our [quality rules](http://www.teamed.io/qa.html):
 > Ticket title and description clearly state what is broken and what kind of fix is expected.

This ticket has incorrect or not full title and description as per comment:
>yegor256 commented 14 days ago
@dmzaytsev it's a bug in BkBasic, not in TkFork. BkBasic doesn't understand HttpException and treats it like any other exception, but it should treat it differently and understand it's code(). 

As far as you are the performer of this ticket you are responsible for its quality. Please ask to fix this and make sure that all tickets you are responsible for have correct titles and descriptions.

**Comment by cyberone** [comment]
@dmzaytsev please change the ticket totle to `BkBasic doesn't understand HTTPException response code`

**Comment by dmzaytsev** [comment]
@elenavolokhova @cyberone 
I believe both the ticket title and description is correct. The snippet in the description shows what is broken and I wrote `Access to invalid url returns 500 error instead 404`. I expected `FtRemote` returns a valid response status.

`FtRemote` calls `BkBasic` inside and @yegor256  just pointed right way for a future performer, made his work a bit easier

@yegor256 correct me if I wrong

**Comment by yegor256** [comment]
@dmzaytsev I think you're right

**Comment by elenavolokhova** [comment]
@dmzaytsev Thank you for clarification!

**Comment by elenavolokhova** [comment]
@davvd Quality is good.

**Comment by elenavolokhova** [comment]
@davvd It looks good.

**Comment by davvd** [comment]
> @davvd It looks good.

@elenavolokhova thanks!

**Comment by davvd** [comment]
@cyberone I added 10 mins to @elenavolokhova (for QA review) in transaction 57686790... Thank you, I have added **30 mins** to your account in payment/transaction "`57686797`", time consumed: 285 hours and 55 mins... +30 added to your rating, at the moment it is: [+203](http://www.netbout.com/b/35076?open=rating)
