### ISSUE TITLE
Take validation

### ISSUE THREAD

**Issue by dmzaytsev** [yegor256/takes#236]
I think we need to create a new decorator which will check a original Take.
something like this 
```
class TkVerify implements Take {
Take assertStatus(Matcher<Integer> matcher) {
   MatcherAssert.assertThat("response status is not equal to..",....);
   return this;
}
Take assertRqMethod(Matcher<String> matcher)
Take assertRqHeader(String name, Matcher<String> matcher)
Take assertRsHeader(String name, Matcher<String> matcher)
Take assertRqQuery(String name, Matcher<String> matcher)
Take assertRqForm(String name, Matcher<String> matcher)
Take assertRqBody(Matcher<String> matcher)
Take assertRsBody(Matcher<String> matcher)
}
```
I believe this will simplify unit tests.

**Comment by yegor256** [comment]
@dmzaytsev the idea is correct, but the design you propose is not. We already have `org.takes.facets.hamcrest` package, where all these classes will reside. We need classes, not methods. See this: https://github.com/yegor256/takes/issues/166
