### ISSUE TITLE
PMD error in the master branch

### ISSUE THREAD

**Issue by dmzaytsev** [yegor256/takes#237]
PMD reports the error in different PRs
> \src\main\java\org\takes\http\BkTimeable.java[59-59]: If you run in Java5 or newer and have concurrent access, you should use the ConcurrentHashMap implementation (UseConcurrentHashMap) 

seems a change has been made without the qulice check

**Comment by yegor256** [comment]
fixed already in ebb3dfbf18d729ea35450bb376ff4058979689df
