### ISSUE TITLE
PsLinkedin passes the request parameters to the URI.

### ISSUE THREAD

**Issue by dmzaytsev** [yegor256/takes#239]
PsLinkedin passes the request parameters to the URI instead of the body.
```
POST /uas/oauth2/accessToken?grant_type=authorization_code&client_id=clnid&redirect_uri=http%3A%2F%2Fwww.example.com%2F&client_secret=secret&code=xxxx HTTP/1.1
Accept: application/xml
Host: localhost:50809
Connection: keep-alive
Content-type: application/x-www-form-urlencoded
Content-Length: 0
```
but should be 
```
POST /uas/oauth2/accessToken HTTP/1.1
Accept: application/xml
Host: localhost:50809
Connection: keep-alive
Content-type: application/x-www-form-urlencoded

grant_type=authorization_code&client_id=clnid&redirect_uri=http%3A%2F%2Fwww.example.com%2F&client_secret=secret&code=xxxx
```
Linkedin accepts such request but it is undocumented feature 
I think we should use valid POST requests

**Comment by davvd** [comment]
@dmzaytsev this task will get someone's attention soon

**Comment by davvd** [comment]
@dmzaytsev attached this issue to milestone "1.0" (let me know if this is wrong)

**Comment by davvd** [comment]
@dmzaytsev many thanks for the report, I topped your account for 15 mins, transaction 56454744

**Comment by davvd** [comment]
@super132 the task is for you now, follow [these guidelines](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html). Don't hesitate to ask any technical questions right here

The budget here is **30 mins**, which is exactly how much time will be paid for, when the task is [completed](http://www.xdsd.org/2014/04/15/definition-of-done.html)

**Comment by super132** [comment]
@yegor256 PR #245 fixes this issue and merged successfully. Would you please close this ticket? Thanks.

**Comment by yegor256** [comment]
@super132 thanks!

**Comment by davvd** [comment]
@yegor256 only @dmzaytsev can close this issue, since he opened it

**Comment by dmzaytsev** [comment]
@super132 thanks!

**Comment by davvd** [comment]
@elenavolokhova please, review this ticket for compliance with our [QA rules](http://www.teamed.io/qa.html)

**Comment by elenavolokhova** [comment]
@davvd Looks good!

**Comment by davvd** [comment]
> @davvd Looks good!

@elenavolokhova thank you

**Comment by davvd** [comment]
@super132 just added 10 mins to @elenavolokhova (for QA), payment ID is `57249565`. Thanks for your contribution, **30 mins** was added to your account, payment ID is `AP-2P310357XU3079602`, 215 hours and 25 mins spent total. +30 added to your rating, at the moment it is: [+113](http://www.netbout.com/b/35282?open=rating)
