### ISSUE TITLE
PsGithub.java:54-56: There is currently no unit...

### ISSUE THREAD

**Issue by davvd** [yegor256/takes#243]
Puzzle `229-401562da` in `src/main/java/org/takes/facets/auth/social/PsGithub.java:54-56` has to be resolved: There is currently no unit test in PsGithubTest that checks that the request parameters are passed to the request body, instead of the URI. Let's add this test.... The puzzle was created by cyberone on 1-May-2015.

If you have any technical questions, don't ask me, submit new tickets instead

**Comment by davvd** [comment]
@dmzaytsev the task is yours,please go ahead

**Comment by dmzaytsev** [comment]
@davvd I will resolve the puzzle in the PR #228

**Comment by davvd** [comment]
@yegor256 since there is no milestone yet I set it to "1.0"

**Comment by yegor256** [comment]
@davvd waiting for #253

**Comment by dmzaytsev** [comment]
@davvd the #PR 228 has been merged. Please close the task

**Comment by davvd** [comment]
> @davvd waiting for #253

@yegor256 right, let's wait for #253

**Comment by dmzaytsev** [comment]
@davvd you can see pull request #228 that is fixing this issue, if that's all here please close.

**Comment by dmzaytsev** [comment]
@davvd please close the task

**Comment by davvd** [comment]
@yegor256 Closing..

**Comment by davvd** [comment]
@elenavolokhova please, let us know what do you think about this ticket, according to our [QA rules](http://www.teamed.io/qa.html)

**Comment by elenavolokhova** [comment]
@davvd Quality is good.

**Comment by davvd** [comment]
> @davvd Quality is good.

@elenavolokhova many thanks

**Comment by davvd** [comment]
@dmzaytsev just added 10 mins to @elenavolokhova (for QA), payment ID is `57168002`. thank you, added **30 mins** to your acc, payment num is `57168022`, 169 hours and 42 mins spent in total to complete. +30 to your rating, your total score is [+1460](http://www.netbout.com/b/35166?open=rating)
