### ISSUE TITLE
RqMultipart.Base is too slow with big requests

### ISSUE THREAD

**Issue by yegor256** [yegor256/takes#248]
When request length is over 10Mb (see `RqMultipartTest.returnsCorrectPartLength()`), parsing takes rather big amount of time. This is what I see on my laptop:

```
length=10_000_000 time=1s
length=50_000_000 time=7s
length=100_000_000 time=14s
```

This is too slow, I believe. Would be great to find a way to make this parsing faster.

**Comment by davvd** [comment]
@yegor256 I will find a developer for the task soon...

**Comment by davvd** [comment]
@yegor256 I added milestone `1.0` to this issue, let me know if there has to be something else

**Comment by davvd** [comment]
@yegor256 thanks for reporting! I topped your account for 15 mins, transaction 000-2a91a3da

**Comment by davvd** [comment]
@dmzaytsev the task is yours please proceed

**Comment by dmzaytsev** [comment]
@yegor256 I see the related commit e6e0b72 
Is this task completed?

**Comment by yegor256** [comment]
@dmzaytsev no, it's not. I tried to experiment a bit, but no luck :(

**Comment by yegor256** [comment]
@dmzaytsev I actually don't know whether this problem is solvable in general or not. We have a stream of 100m bytes and we should find the first occurrence of the "boundary", which is also an array of bytes. We have to go byte by byte and compare them. There is no way around this, right? So, we have to make 100m iterations... I'm curious how this is solved in other frameworks.

**Comment by dmzaytsev** [comment]
@yegor256 I think what I can do

**Comment by dmzaytsev** [comment]
@davvd  please find someone to do code review PR #255

**Comment by dmzaytsev** [comment]
@davvd PR #255 fixes this issue and waiting for the review already 6 days!
I lost my fast delivery bonus and my delivery speed is reduced.
I have a risk to be penalized for the delay after 3 days.
We need more time here.

@yegor256 please confirm my request.

**Comment by yegor256** [comment]
@davvd give us more time here pls

**Comment by davvd** [comment]
> @davvd give us more time here pls

@yegor256 of course, take your time

**Comment by dmzaytsev** [comment]
@yegor256 PR #255 fixes this issue and merged, 
please close the ticket

**Comment by yegor256** [comment]
@dmzaytsev thanks!

**Comment by yegor256** [comment]
@rultor release tag is `0.16.9`

**Comment by yegor256** [comment]
@rultor release tag is `0.16.9`

**Comment by davvd** [comment]
@ypshenychka please, review this ticket for compliance with our [QA rules](http://www.teamed.io/qa.html)

**Comment by ypshenychka** [comment]
@davvd Quality is good here.

**Comment by davvd** [comment]
> @davvd Quality is good here.

@ypshenychka thanks, got it, great to see high-quality tickets here

**Comment by davvd** [comment]
@dmzaytsev I added 10 mins to @ypshenychka (for QA review) in transaction 57333103. **30 mins** sent to your balance (ID `57333108`), many thanks! It took 254 hours and 53 mins.. added +30 to your rating, now it is equal to [+1693](http://www.netbout.com/b/35166?open=rating)
