### ISSUE TITLE
hit-refresh is not implemented

### ISSUE THREAD

**Issue by yegor256** [yegor256/takes#25]
`TsHitRefresh` is not implemented, let's create it

**Comment by davvd** [comment]
@yegor256 sure, thanks, I added bug tag to it

**Comment by yegor256** [comment]
@davvd assign this to me

**Comment by yegor256** [comment]
@rultor release, tag is `0.9`

**Comment by davvd** [comment]
> @davvd assign this to me

@yegor256 this task is yours now, please proceed

**Comment by davvd** [comment]
> @davvd assign this to me

@yegor256 keep in mind that assigning yourself to your own ticket is a bad practice

**Comment by davvd** [comment]
@yegor256 done, I added **30 mins** in payment `000-6789b0dd`; +30 to your rating, your total score is [+8216](http://www.netbout.com/b/35008?open=rating)
