### ISSUE TITLE
RqWithHeaderTest tests nothing

### ISSUE THREAD

**Issue by ikhvostenkov** [yegor256/takes#251]
```Java
@Test
    public void addsHttpHeaders() throws IOException {
        MatcherAssert.assertThat(
            new RqPrint(
                new RqWithHeader(
                    new RqFake(),
                    "Host", "www.example.com"
                )
            ).print(),
            Matchers.containsString("Host: www.example.com")
        );
    }
```
Change it to 
```Java
@Test
    public void addsHttpHeaders() throws IOException {
        MatcherAssert.assertThat(
            new RqPrint(new RqFake()).print(),
            Matchers.containsString("Host: www.example.com")
        );
    }
```
get test passed.
Reason is inside ```RqFake``` 
```Java
public RqFake(final CharSequence method, final CharSequence query,
        final CharSequence body) {
        this(
            Arrays.asList(
                String.format("%s %s", method, query),
                "Host: www.example.com"
            ),
            body
        );
    }
```

**Comment by yegor256** [comment]
@ikhvostenkov true, good catch, thanks

**Comment by davvd** [comment]
@ikhvostenkov I will find a developer for the task soon...

**Comment by davvd** [comment]
@ikhvostenkov attached this issue to milestone "1.0" (let me know if this is wrong)

**Comment by davvd** [comment]
@cyberone please proceed, it's yours

**Comment by davvd** [comment]
@ikhvostenkov thanks a lot for reporting, **15 mins** added to your acc, pmt ID `56730773`

**Comment by cyberone** [comment]
@davvd please review https://github.com/yegor256/takes/pull/267

**Comment by davvd** [comment]
> @davvd please review https://github.com/yegor256/takes/pull/267

@cyberone thanks, I'll take a look

**Comment by davvd** [comment]
@lautarobock the task is for you now, follow [these guidelines](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html). Don't hesitate to ask any technical questions right here; Total fixed cost of this task is **30 mins** (see [this](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html) for more info)

**Comment by cyberone** [comment]
@davvd the task is done, see PR. Assign it back please and give the payment

**Comment by cyberone** [comment]
@ikhvostenkov close please, the PR is merged

**Comment by yegor256** [comment]
@davvd assign @cyberone to this pls

**Comment by davvd** [comment]
> @davvd assign @cyberone to this pls

@yegor256 OK. @cyberone the ticket is yours, please proceed

**Comment by ikhvostenkov** [comment]
Fixed.

**Comment by davvd** [comment]
@elenavolokhova please, review this ticket for compliance with our [QA rules](http://www.teamed.io/qa.html)

**Comment by elenavolokhova** [comment]
@davvd Quality is good here.

**Comment by davvd** [comment]
> @davvd Quality is good here.

@elenavolokhova thank you :)

**Comment by davvd** [comment]
@cyberone 10 mins was added to the account of @elenavolokhova (for QA review), in transaction 57753076. Thanks for your contribution, **1 hour** was added to your account, payment ID is `57753085`, 13 hours and 21 mins spent total. m=801, that's why a bonus here for fast delivery. added +60 to your rating, now it is equal to [+233](http://www.netbout.com/b/35076?open=rating)
