### ISSUE TITLE
RqMultipart.Fake

### ISSUE THREAD

**Issue by yegor256** [yegor256/takes#252]
Let's create a new class `RqMultipart.Fake`, which will do what is now we're doing in `RqMultipartTest.request()` method. It will help us to create a fake request with multi-part encoded content. I think it should have this ctor:

```java
new RqMultipart.Fake(
  new RqFake(),
  "Content-Disposition: form-data; name=\"data\"; filename=\"a.bin\"\r\ncontent",
  "Content-Disposition: form-data; name=\"address\"\r\n440 N Wolfe Rd., Sunnyvale, CA"
);
```

Without such a class, the tests in `RqMultipartTest`  are very verbose and difficult to understand. Also, in real applications it would be easier to use this fake request builder.

And let's get rid of `RqMultipartTest.request()`

**Comment by davvd** [comment]
@yegor256 I just added bug tag here

**Comment by davvd** [comment]
@yegor256 there is no milestone yet, so I set it to `1.0`

**Comment by davvd** [comment]
@erimerturk the task is for you now, follow [these guidelines](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html). Don't hesitate to ask any technical questions right here; **30 mins** is the budget of the task. This is exactly how much will be paid when the problem is [solved](http://www.xdsd.org/2014/04/15/definition-of-done.html) (no matter how much time you will actually spend). See [this](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html) for more information

**Comment by davvd** [comment]
@yegor256 thanks for this report, I added 15 mins to your account, in transaction `000-ee18df31`

**Comment by erimerturk** [comment]
@yegor256 why do you need Request on Fake constructor. Is it acceptable for you without request on constuctor ?

```
new RqMultipart.Fake(
  "Content-Disposition: form-data; name=\"data\"; filename=\"a.bin\"\r\ncontent",
  "Content-Disposition: form-data; name=\"address\"\r\n440 N Wolfe Rd., Sunnyvale, CA"
);
```
If you need request, can you explain why do you need ?

**Comment by yegor256** [comment]
@erimerturk well, I may want to do this:

```java
new RqMultipart.Fake(
  new RqWithHeader(
    new RqFake("POST", "/my-form"),
    "Accept", "text/plain"
  ),
  "Content-Disposition: form-data; name=\"data\"; filename=\"a.bin\"\r\ncontent",
  "Content-Disposition: form-data; name=\"address\"\r\n440 N Wolfe Rd., Sunnyvale, CA"
);
```

**Comment by erimerturk** [comment]
@yegor256 Should it implement Request or RqMultipart interface ? Will you pass it to RqMultipart.Base(...) or use it directly as RqMultipart request ?

**Comment by yegor256** [comment]
@erimerturk good question... I think `RqMultipart.Fake` should implement `RqMultipart`

**Comment by davvd** [comment]
@marcuss it's yours, please go ahead

**Comment by erimerturk** [comment]
@davvd i have already fixed this and it is waiting on CR #262  .  @yegor256  you know @alice blocked and removed my account and i couldn't go on, my account activated just today. Could you make something, please ?

**Comment by yegor256** [comment]
@davvd please assign @erimerturk to this issue

**Comment by davvd** [comment]
> @davvd please assign @erimerturk to this issue

@yegor256 OK. @erimerturk the ticket is yours, please proceed

**Comment by erimerturk** [comment]
@yegor256 please check it and close if it is OK, thank you

**Comment by yegor256** [comment]
@erimerturk thanks!

**Comment by davvd** [comment]
@ypshenychka please, review this task for compliance with our [quality rules](http://www.teamed.io/qa.html)

**Comment by ypshenychka** [comment]
@davvd Quality is good.

**Comment by davvd** [comment]
> @davvd Quality is good.

@ypshenychka thanks!

**Comment by davvd** [comment]
@yegor256 the code made here contains a puzzle `252-d7f3c72e`/#323, which will be resolved soon

**Comment by davvd** [comment]
@erimerturk 10 mins was added to the account of @ypshenychka (for QA review), in transaction 58210307... Much appreciated! **30 mins** was added to your account, payment ID `AP-0BJ111980B927493N`, time spent is 205 hours and 32 mins... +30 added to your rating, at the moment it is: [+90](http://www.netbout.com/b/35280?open=rating)

**Comment by davvd** [comment]
@yegor256 the last puzzle `252-d7f3c72e`/#323 originated from here solved
