### ISSUE TITLE
RqMultipart.Base.make() leaves temporary files until the VM terminates

### ISSUE THREAD

**Issue by dmzaytsev** [yegor256/takes#254]
RqMultipart.Base.make() uses deleteOnExit() option for temporary files. It means such files be deleted when the virtual machine terminates. We will get a large number of temporary files with heavy use applications. 
I believe we need to use another method for deletion these temporary files. Since temp files in this method uses as buffer for a large requests we could try collect names and force to delete the files every some time interval

**Comment by yegor256** [comment]
@dmzaytsev totally agree, thanks for catching this

**Comment by davvd** [comment]
@dmzaytsev I will find a developer for the task soon...

**Comment by davvd** [comment]
@dmzaytsev there is no milestone yet, so I set it to `1.0`

**Comment by davvd** [comment]
@louzar please go ahead, it's your task now, keep [this](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html) in mind, and don't hesitate to ask any technical questions you may have

This task's budget is **30 mins**. This is exactly how much will be paid when the problem explained above is solved. See [this](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html) for more information

**Comment by davvd** [comment]
@dmzaytsev thanks for the ticket, your account was topped for 15 mins, payment 56894648

**Comment by davvd** [comment]
@bertram25 this ticket is yours now, please proceed, and keep in mind [this](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html). Any technical questions you should ask right here... Total fixed cost of this task is **30 mins** (see [this](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html) for more info)

**Comment by Bertram25** [comment]
@dmzaytsev Hi, :)

What kind of method would be the most suitable to you?

Proposal: Collect the files in an iterable and add a method to make those cleanable at the application scope (as you requested), leave the deleteOnExit(); statement in place, and add a finalize() method cleaning the file handles, so that we are sure the temp files are either deleted when the gc triggers the parent request object deletion or at least (and still) when the VM stops.

Quick-made Example:
```java
// In RqMultipart.Base class
// ...
    // file handler collection
    private final Iterable<File> files;
    private void cleanTempFiles() {
        for(File file : files) {
            // TODO: Check for file existence before deleting it
            // if we're going to keep deleteOnExit() in make()
            // add try catch
            file.delete();
         }
    }

    // Handles the deletion of files when the object is cleaned up.
    @Override
    protected void finalize() throws Throwable
    {
        try {
            cleanTempFiles();
        } catch (Throwable t) {
            throw t;
        } finally {
            super.finalize();
        }
    }
```

**Comment by dmzaytsev** [comment]
@Bertram25 hi,
According to the [Javadoc](http://docs.oracle.com/javase/7/docs/api/java/lang/Object.html#finalize%28%29)
>Called by the garbage collector on an object when garbage collection determines that there are no more references to the object.

We don't know when the garbage collector will call `finalize()` It may happen that we will have a large number of temporary files until the garbage collector will do its job

**Comment by yegor256** [comment]
@dmzaytsev @Bertram25 I think the best place to delete the file is in `close()` method of `InputStream` we return at `body()` of our "parts".  Here is the scenario:

```java
Request req = // .. incoming request
final Request part = new RqMultipart.Base(req).part("file").iterator().next();
final InputStream body = part.body();
final byte[] content = new byte[1_000_000];
body.read(content);
body.close(); // boom! here we delete the file
```

make sense?

**Comment by dmzaytsev** [comment]
@yegor256 @Bertram25 Let's try, I agree

**Comment by Bertram25** [comment]
@yegor256 @dmzaytsev Thanks for the hints!
Here is a preliminary commit made for review: https://github.com/Bertram25/takes/commit/b1b92c8afbecb80dc3334cb3441180425287a05b

Am I doing it the right way? If so, and you agree to give me one or two more days, I'll finish this commit with proper style and an unit test.

Best regards,

**Comment by dmzaytsev** [comment]
@Bertram25 Why do we need `TempReadableByteChannel`?
let's implement Yegor's suggestion

I think you should use a decorator for InputStream here
https://github.com/yegor256/takes/blob/master/src/main/java/org/takes/rq/RqMultipart.java#L253

this decorator have to use `CapInputStream` and `File` in its constructor
and override `close()` to close the file as  written in the Yegor's comment above

@yegor256 correct me if I wrong

**Comment by yegor256** [comment]
@Bertram25 I'm with @dmzaytsev on this

**Comment by Bertram25** [comment]
@yegor256 @dmzaytsev Indeed! Please accept my apologize for my own lack of sleep and coffee. :)
The PR #318 should now be ready for review.

Thanks for all the advice.

**Comment by Bertram25** [comment]
@davvd Hi, As said above, the PR #318 is now ready for review.

Best regards,

**Comment by Bertram25** [comment]
@davvd Hi again!

I may need a bit more time on this issue while the review phase is processed.

Best regards,

**Comment by yegor256** [comment]
@davvd give us more time here pls

**Comment by davvd** [comment]
> @davvd give us more time here pls

@yegor256 sure, take your time

**Comment by exper0** [comment]
@yegor256 @davvd It seems this is not fixed. I encounter a lot of problems(hundreds of thousands temporary files) because of this issue. Also it leads to bugs in Netbout in production. There are too much time since last update on this issue, maybe it's worth reassigning it.

**Comment by yegor256** [comment]
@exper0 make sense, thanks

**Comment by yegor256** [comment]
@Bertram25 are you planning to finish this one or we should re-assign?

**Comment by Bertram25** [comment]
@yegor256 IMHO, you should reassign as I don't have any time for such tasks atm. (Very sorry about it.)

**Comment by yegor256** [comment]
@davvd please, assign someone else here

**Comment by davvd** [comment]
> @davvd please, assign someone else here

@yegor256 right, I will find someone else, no problem

**Comment by exper0** [comment]
@yegor256 @davvd I can finish this

**Comment by davvd** [comment]
@alexey-krylov can you please help? Keep in mind [this](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html). If you have any technical questions, don't hesitate to ask right here... The budget of this task is **30 mins**. This is exactly how much time will be compensated, when the task is completed. Read about our [Definition of Done](http://www.xdsd.org/2014/04/15/definition-of-done.html)

**Comment by alexey-krylov** [comment]
@davvd sorry, i think i have not enough knowledge of 'takes' to fix that in this time. Find someone else please.

**Comment by exper0** [comment]
@davvd let me finish it.

**Comment by davvd** [comment]
> @davvd sorry, i think i have not enough knowledge of 'takes' to fix that in this time. Find someone else please.

@alexey-krylov deducted 30 from your rating :(

**Comment by davvd** [comment]
> @davvd sorry, i think i have not enough knowledge of 'takes' to fix that in this time. Find someone else please.

@alexey-krylov all right, we'll find someone else for this task

**Comment by davvd** [comment]
> @davvd let me finish it.

@exper0 you should ask @yegor256 to assign you, he is the architect (I assign developers randomly, always)

**Comment by davvd** [comment]
@exper0 the task is yours please proceed

**Comment by exper0** [comment]
@dmzaytsev PR #536 merged and closed. Please close request

**Comment by dmzaytsev** [comment]
@exper0 thanks!

**Comment by dmzaytsev** [comment]
@yegor256 could you make a new release ? thanks

**Comment by exper0** [comment]
@dmzaytsev just in case - in scope of this task the problem with temporary files / file descriptors is not fully solved. There are a couple of puzzles created in scope of this task. Briefly - in order to clean the file and close actual file descriptor `close` should be called on request body stream. However, the code is designed in such a way that it's quite difficult to say where is the right place for `close`.

**Comment by dmzaytsev** [comment]
@exper0 thanks, I hadn't saw the puzzles
@yegor256 we will wait until the puzzles will be completed

**Comment by davvd** [comment]
@dmzaytsev 2 puzzles were created here: `254-d68bc52e`, `254-40a8e0fe`

**Comment by davvd** [comment]
@ypshenychka please, let us know what do you think about this ticket, according to our [QA rules](http://at.teamed.io/qa.html)

**Comment by ypshenychka** [comment]
@davvd Quality is good.

**Comment by davvd** [comment]
> @davvd Quality is good.

@ypshenychka thanks a lot ;)

**Comment by davvd** [comment]
@exper0 added 10 mins to @ypshenychka, for QA review, payment code is `76615934`... Thank you, I have added **30 mins** to your account in payment/transaction "`AP-2LK10084ED737235F`", time consumed: 348 hours and 30 mins... +30 added to your rating, current score is: [+603](http://www.netbout.com/b/36185?open=rating)

**Comment by davvd** [comment]
@dmzaytsev the last puzzle `254-40a8e0fe`/#576 solved
