### ISSUE TITLE
Cache service for internal usage

### ISSUE THREAD

**Issue by dmzaytsev** [yegor256/takes#256]
I believe would be useful to create a simple cache service for internal usage.

* Cache should allow to set a storage policy. Objects smaller than the specified size should be stored in memory, and for larger objects  should use temporary files. I understand objects must be serializable in this case, but basically I talking about streams and channels.
* Cache should allow to set an eviction policy. Cache items must be removed with specified delay after write time and after access time. Also would be useful to remove objects after specified access count. Cache.Base must use single eviction monitor thread for all instances.

something llike this
```
public interface CacheLoader<K,V> {
V load(K key);
}

public interface Cache<K,V> {
    void put(K key,V value);
    Opt<V> get(K);
class Base implements Cache {   
  public Base()
  public Base(CacheLoader loader)
  public Base withLimit(int limit)
  public Base afterWrite(long duration, TimeUint unit)
  public Base afterAccess(long duration, TimeUint unit)
  public Base afterAccess(long count)
}
```

**Comment by yegor256** [comment]
@dmzaytsev where will this be used? I'm not sure I understand your idea here....

**Comment by dmzaytsev** [comment]
@yegor256 mostly this idea was inspired by RqMultipart.Base. In this class the cache has implemented manually and might be improved. At the moment all parts we save into the files but small parts we can store in memory and average response time will be smaller, isn't it ?
Second reason is your article "Constructors Must Be Code-Free",  we have some classes with heavy load ctors e.g. RqMultipart.Base, RqForm.Base, RqLive... If we will move the logic from ctors to methods so the cache is also will be useful here.

**Comment by dmzaytsev** [comment]
@yegor256 yet we can postpone this idea
this is not the priority task as far I understand

**Comment by yegor256** [comment]
@dmzaytsev yes, now I understand. But we should not ask for a cache implementation in this ticket, but for a cached classes implementation. For example: `RqForm.Cached`. This class will have to use some caching layer and we'll implement it. So, the caching is just a tool, the real goal is that `RqForm.Cached` class.

**Comment by dmzaytsev** [comment]
@yegor256 I have understood the idea.
I close the task.
Thanks!

**Comment by yegor256** [comment]
@dmzaytsev feel free to create tickets for that `*.Cached` classes, I like the idea

**Comment by dmzaytsev** [comment]
@yegor256  e.g. if we want  make lightweight ctor in the RqForm.Base. We need cached  RqForm.Base.param() and RqForm.Base.names()
what should be in RqForm.Cached ?

**Comment by yegor256** [comment]
@dmzaytsev it will decorate an instance of `RqForm

**Comment by dmzaytsev** [comment]
@yegor256 I understand it,  but where the cache will be implemented ?
I guess in `org.takes.misc` am i right?
we shall create ticket for RqForm.Cached and make puzzle for org.takes.misc.Cache ?

**Comment by yegor256** [comment]
@dmzaytsev I think we should discuss this case by case, in other tickets
