### ISSUE TITLE
RqWithHeader/RqWithHeaders optimization

### ISSUE THREAD

**Issue by dmzaytsev** [yegor256/takes#257]
I believe will be better move the implementation from RqWithHeader to RqWithHeaders and call RqWithHeaders from RqWithHeader.
I think it will be more efficient.

**Comment by davvd** [comment]
@dmzaytsev this task will get someone's attention soon

**Comment by davvd** [comment]
@dmzaytsev I set milestone here to `1.0`, let me know if it is wrong

**Comment by davvd** [comment]
@louzar this task is for you, keep [these principles](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html) in mind, and don't hesitate to ask any technical questions. Budget here is **30 mins** (keep [this principle](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html) in mind)

**Comment by davvd** [comment]
@dmzaytsev thanks for tis bug, I topped your account for 15 mins, transaction `57126324`

**Comment by louzar** [comment]
@davvd I just get notified 2 days ago that I'm on this project, does this issue still for me

**Comment by louzar** [comment]
@davvd I just get notified 2 days ago that I'm on this project, does this issue still for me

**Comment by davvd** [comment]
@ekondrashev please go ahead with this task, it's yours

**Comment by ekondrashev** [comment]
@dmzaytsev please close this ticket, solution is  provided with #315 PR.

**Comment by dmzaytsev** [comment]
@ekondrashev thanks!

**Comment by davvd** [comment]
@ypshenychka review this ticket please, for compliance with our [quality rules](http://www.teamed.io/qa.html)

**Comment by ypshenychka** [comment]
@davvd Quality is good here.

**Comment by davvd** [comment]
> @davvd Quality is good here.

@ypshenychka thanks, got it, great to see high-quality tickets here

**Comment by davvd** [comment]
@ekondrashev 10 mins was added to the account of @ypshenychka (for QA review), in transaction 58649509... Thanks for your contribution, **30 mins** was added to your account, payment ID is `58649514`, 229 hours and 12 mins spent total... +30 added to your rating, at the moment it is: [+181](http://www.netbout.com/b/35260?open=rating)
