### ISSUE TITLE
Hamcrest matcher to verify a request parameter

### ISSUE THREAD

**Issue by dmzaytsev** [yegor256/takes#259]
Takes doesn't has a Hamcrest matcher to verify a request parameter. I think it has to be.
Both query and form parameters need to be verified.

something like this
```
public final class HmRqQueryParam extends TypeSafeMatcher<Request> {
    public HmRqQueryParam(final Matcher<? extends Map<String,String>> mtchr)
}

public final class HmRqFormParam extends TypeSafeMatcher<Request> {
    public HmRqFormParam(final Matcher<? extends Map<String,String>> mtchr)
}
```

**Comment by yegor256** [comment]
@dmzaytsev right, thanks

**Comment by davvd** [comment]
@dmzaytsev I am aware of the task, give me some time to find a developer...

**Comment by davvd** [comment]
@dmzaytsev I set milestone here to `1.0`, let me know if it is wrong

**Comment by davvd** [comment]
@yamstranger the task is yours plz proceed

**Comment by davvd** [comment]
@dmzaytsev thanks a lot for reporting, **15 mins** added to your acc, pmt ID `56931065`

**Comment by YamStranger** [comment]
@davvd thanks

**Comment by YamStranger** [comment]
@davvd , @yegor256. As wrote @alice, I am not with your team any more. So please assign ticket to someone else. Thanks

**Comment by davvd** [comment]
> @davvd , @yegor256. As wrote @alice, I am not with your team any more. So please assign ticket to someone else. Thanks

@yamstranger I deducted 30 points from your rating

**Comment by davvd** [comment]
> @davvd , @yegor256. As wrote @alice, I am not with your team any more. So please assign ticket to someone else. Thanks

@yamstranger got it, someone else will be assigned soon

**Comment by davvd** [comment]
@ekondrashev it's yours, please go ahead

**Comment by ekondrashev** [comment]
@yegor256 @dmzaytsev I believe we have the same situation as for #260 .
We need to clarify the requirements on following cases:
1. assert that param is not present at all
2. assert that param has one value
3. assert that param has many values

**Comment by ekondrashev** [comment]
@davvd I afraid we are blocked here

**Comment by yegor256** [comment]
@ekondrashev I think this ticket is not really feasible... @dmzaytsev what do you think about this:

```java
MatcherAssert.assertThat(
  new RqHref(new RqFake("GET", "/a?foo=123")).href().param("foo"),
  Matchers.hasItem("123")
);
```

This is simple enough, we don't need anything else on top of built-in Hamcrest matchers.

**Comment by dmzaytsev** [comment]
@yegor256 what about a form param ?

**Comment by yegor256** [comment]
@dmz like this:

```java
MatcherAssert.assertThat(
  new RqForm.Base(new RqFake("GET", "/", "a=test")).param("a"),
  Matchers.hasItem("test")
);
```

**Comment by dmzaytsev** [comment]
@yegor256 I got it, thanks

@davvd @ekondrashev I'm closing the ticket

**Comment by davvd** [comment]
@elenavolokhova review this ticket please, for compliance with our [quality rules](http://www.teamed.io/qa.html)

**Comment by elenavolokhova** [comment]
@davvd There was no code change in this ticket and nothing to be paid for. Quality is bad.

**Comment by davvd** [comment]
> @davvd There was no code change in this ticket and nothing to be paid for. Quality is bad.

@elenavolokhova thanks a lot, noticing bad quality is what makes us better

**Comment by davvd** [comment]
@ekondrashev I added 10 mins to @elenavolokhova (for QA review) in transaction 57754472; thanks, paid, **45 mins** to your account, payment ID is `57754496`, task took 45 hours and 30 mins to complete; the bonus for fast delivery (m=2730); added +45 to your rating, now it is equal to [+181](http://www.netbout.com/b/35260?open=rating)
