### ISSUE TITLE
RqForm.Base is unextendable

### ISSUE THREAD

**Issue by dmzaytsev** [yegor256/takes#263]
At the moment RqForm.Base is hard to extend. Its constructor contains more than 20 lines code. I believe we shall move the code from the constructor into the class methods. Also we shall cache the class methods to prevent performance impact when we will re-use them.

**Comment by yegor256** [comment]
@dmzaytsev agree, thanks

**Comment by davvd** [comment]
@dmzaytsev I will ask someone to take care of this task soon

**Comment by davvd** [comment]
@dmzaytsev milestone set to `1.0` (correct me if I am wrong)

**Comment by davvd** [comment]
@zshamrock it's yours now, please proceed keeping in mind [our principles](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html). Feel free to ask any technical questions right here in the ticket... Task's budget is **30 mins** (see [this](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html) for explanation)

**Comment by davvd** [comment]
@dmzaytsev thanks for this report, I added 15 mins to your account, in transaction `57160510`

**Comment by davvd** [comment]
@zshamrock check this ["no obligations principle"](http://www.xdsd.org/2014/04/13/no-obligations-principle.html).. This task is on your name for at least 15 days. If you can't close it within the next 48 hours I will have to assign someone else to it. [This article](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html) should help if you're stuck. -30 added to your rating, at the moment it is: [-60](http://www.netbout.com/b/35316?open=rating)

**Comment by davvd** [comment]
@zshamrock this task is taking too long, I have to change the performer, sorry. Please stop working with it right now. See our [no obligations](http://www.xdsd.org/2014/04/13/no-obligations-principle.html) principle. -60 to your rating, your total score is [-180](http://www.netbout.com/b/35316?open=rating)

**Comment by yegor256** [comment]
@davvd yeah give it to some body else

**Comment by davvd** [comment]
@lautarobock the task is for you now, follow [these guidelines](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html). Don't hesitate to ask any technical questions right here. Budget here is **30 mins** (keep [this principle](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html) in mind)

**Comment by lautarobock** [comment]
@yegor256 
1) Can I include jcabi-aspect for cache? 
2) If I move code to methods, the problem will be Exceptions for parsing request. `names` and `param` do not throws any kind of exception. What do you think? if error returns empty map?

**Comment by yegor256** [comment]
@lautarobock 1) no, we can't use any dependencies here. 2) you can make them throw `IOException`, it's OK

**Comment by lautarobock** [comment]
@yegor256  not even guava cache? (guava is in test scope now).
Without dependencies I'll must use anti-pattern like lazy-loading or create a kind of `SimpleCache` class to perform it. Do you thinks that is necessary here to create a `SimpleCache`?

**Comment by zshamrock** [comment]
@lautarobock why lazy-loading is considered as anti-pattern. Just curious, could you, please, share a reference to it?

**Comment by lautarobock** [comment]
@zshamrock in a similar situation `But please don't make CachedName mutable and lazily loaded — it's an anti-pattern, which I've discussed before in Objects Should Be Immutable.`
ref: http://www.yegor256.com/2015/05/07/ctors-must-be-code-free.html

**Comment by yegor256** [comment]
@lautarobock @zshamrock lazy-loading will make us use NULL, which is a very bad idea (http://www.yegor256.com/2014/05/13/why-null-is-bad.html). See how that "caching" is implemented in `TkForward.Safe`

**Comment by zshamrock** [comment]
@yegor256 I think the problem here with the naming :) I completely agree that NULL is bad, but I would call it postponed/delayed initialization rather than lazy-loading, as the cache example (as well as Guava loading cache) they are kind of lazy/on-demand loading. And it perfectly fine fits the OOP concept - behavior, not data from your article where you postpone/lazy the actual action until it is asked by the client.

**Comment by yegor256** [comment]
@zshamrock yes, the lazy-loading is not against OOP at all, but NULL is a bad thing. So, if we need to do it, let's do it how `TkForward.Safe` is doing it.

**Comment by lautarobock** [comment]
@yegor256 ok

**Comment by lautarobock** [comment]
PR #340 is ready for review

**Comment by davvd** [comment]
> @davvd PR #340 is ready for review

@lautarobock thank you, I will check it

**Comment by lautarobock** [comment]
@davvd #340 is merged. Do you need something else?

**Comment by dmzaytsev** [comment]
@lautarobock thanks!

**Comment by davvd** [comment]
@elenavolokhova review this ticket please, for compliance with our [quality rules](http://www.teamed.io/qa.html)

**Comment by elenavolokhova** [comment]
@davvd Quality is good here.

**Comment by davvd** [comment]
> @davvd Quality is good here.

@elenavolokhova thank you :)

**Comment by davvd** [comment]
@lautarobock I added 10 mins to @elenavolokhova (for QA review) in transaction 59512367

Many thanks! **30 mins** were added to your account in Transaction ID `AP-80288945911246939` (task took 317 hours and 50 mins)

+30 added to your rating, at the moment it is: [+150](http://www.netbout.com/b/35344?open=rating)
