### ISSUE TITLE
RsWithHeaders.java:55-60: To implement the concatenation and...

### ISSUE THREAD

**Issue by davvd** [yegor256/takes#268]
Puzzle `160-f5eebf68` in `src/main/java/org/takes/rs/RsWithHeaders.java:55-60` has to be resolved: To implement the concatenation and transformation with conjunction of Concat class and Transform class to get rid of the use of List.add() in the anonymous Response class head() method. That is, we are going to do something like this: return new Concat(res.head(), new Transform(headers, new Trim()))... The puzzle was created by super132 on 8-May-2015.

If you have any technical questions, don't ask me, submit new tickets instead

**Comment by davvd** [comment]
@yegor256 attached this issue to milestone "1.0" (let me know if this is wrong)

**Comment by davvd** [comment]
@ekondrashev the task is yours plz proceed

**Comment by ekondrashev** [comment]
@davvd this task is blocked by #275

**Comment by davvd** [comment]
> @davvd this task is blocked by #275 

@ekondrashev sure, we'll wait for #275

**Comment by davvd** [comment]
@yegor256 we waited for #275, it is closed already

**Comment by davvd** [comment]
@yegor256 Closing this issue now...

**Comment by davvd** [comment]
@elenavolokhova please, review this ticket for compliance with our [QA rules](http://www.teamed.io/qa.html)

**Comment by elenavolokhova** [comment]
@ekondrashev
 According to our [quality rules](http://www.teamed.io/qa.html):
 > Some of ticket messages must mention all pull requests where the problem was actually fixed.
 
 There is no link to related PR in comments. Please fix this issue and try to follow this rule in your tickets in the future.

**Comment by ekondrashev** [comment]
@elenavolokhova Sorry, but I did not have a chance to ask to close this ticket. David made a decision basing on #275 defect resolution, so I just was "too slow".
But anyway, the PR is #279.

**Comment by elenavolokhova** [comment]
@ekondrashev Thank you!

**Comment by elenavolokhova** [comment]
@davvd Quality is acceptable.

**Comment by davvd** [comment]
> @davvd Quality is acceptable.

@elenavolokhova thanks a lot, next time everybody should try to make it better

**Comment by davvd** [comment]
@ekondrashev just added 10 mins to @elenavolokhova (for QA), payment ID is `57307220`. Thanks so much! Your account was topped up for **45 mins** (transaction ID is `57307264`, the task took 40 hours and 40 mins). m=2440, that's why a bonus here for fast delivery. +45 to your rating, your total score is [+91](http://www.netbout.com/b/35260?open=rating)
