### ISSUE TITLE
160-f5eebf68 puzzle outdated and does not take into account validation

### ISSUE THREAD

**Issue by ekondrashev** [yegor256/takes#275]
The puzzle was created by super132 on 8-May-2015.
`160-f5eebf68` puzzle for `RsWithHeaders` described at #268 states:

```
To implement the concatenation and transformation with conjunction of Concat class and Transform 
class to get rid of the use of List.add() in the anonymous Response class head() method. 
That is, we are going to do something like this: 
return new Concat(res.head(), new Transform(headers, new Trim()))
```
but 
* the code no longer uses List.add, instead it iterates over each header and creates decorator `RsWithHeader` instance
* proposed resolution does not take into account validation that is encapsulated in `RsWithHeader` class

**Comment by super132** [comment]
@ekondrashev right, the puzzle was created to solve an issue in the old code which doe a trimming action. However, in the latest code, it is now using `RsWithHeader` to do header concatenation. I think this puzzle is not longer valid.

**Comment by ekondrashev** [comment]
@super132 thanks for your comments. I agree that the puzzle is no longer valid and can be safely removed.

@davvd please, close this issue.

**Comment by yegor256** [comment]
@ekondrashev I'm closing it
