### ISSUE TITLE
RsWithStatus.java:97-101: To implement concatenation and selection...

### ISSUE THREAD

**Issue by davvd** [yegor256/takes#276]
Puzzle `160-fc7f658c` in `src/main/java/org/takes/rs/RsWithStatus.java:97-101` has to be resolved: To implement concatenation and selection with the conjunction Concat and Select class to get rid of List.add() between line 118 to line 127. That is, replacing the block using something like this: return new Concat(head,new Select(origin.head(),new FilterFirstCond()))... The puzzle was created by super132 on 8-May-2015.

If you have any technical questions, don't ask me, submit new tickets instead

**Comment by davvd** [comment]
@dmzaytsev the task is yours, please go ahead

**Comment by dmzaytsev** [comment]
@davvd please see PR #280

**Comment by davvd** [comment]
@yegor256 I set milestone here to `1.0`, let me know if it is wrong

**Comment by davvd** [comment]
> @davvd please see PR #280 

@dmzaytsev thanks, will take a look

**Comment by dmzaytsev** [comment]
@davvd PR #280 fixes this issue and merged successfully. Could you please close this ticket? Thanks.

**Comment by dmzaytsev** [comment]
@davvd close the task please

**Comment by davvd** [comment]
@yegor256 It is closed now

**Comment by davvd** [comment]
@dmzaytsev Thanks for your contribution, **30 mins** was added to your account, payment ID is `57310622`, 86 hours and 18 mins spent total

+30 to your rating, your total score is [+1663](http://www.netbout.com/b/35166?open=rating)
