### ISSUE TITLE
Pass.enter() must return Opt

### ISSUE THREAD

**Issue by yegor256** [yegor256/takes#278]
`Pass.enter()` must return `Opt`, instead of `Iterator`, let's refactor it.

**Comment by davvd** [comment]
@yegor256 tagged this issue with "bug"

**Comment by davvd** [comment]
@yegor256 since there is no milestone yet I set it to "1.0"

**Comment by davvd** [comment]
@yegor256 thank you for reporting this, I added 15 mins to your acc, transaction `000-5e53a59b`

**Comment by davvd** [comment]
@yamstranger it's yours,please go ahead

**Comment by YamStranger** [comment]
@davvd Thanks, I take it

**Comment by YamStranger** [comment]
@davvd , @yegor256. As wrote @alice, I am not with your team any more. So please assign ticket to someone else. Thanks

**Comment by davvd** [comment]
> @davvd , @yegor256. As wrote @alice, I am not with your team any more. So please assign ticket to someone else. Thanks

@yamstranger I deducted 30 points from your rating

**Comment by davvd** [comment]
> @davvd , @yegor256. As wrote @alice, I am not with your team any more. So please assign ticket to someone else. Thanks

@yamstranger I will ask somebody else to pick this up

**Comment by davvd** [comment]
@antonini the task is for you now, follow [these guidelines](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html). Don't hesitate to ask any technical questions right here; Budget here is **30 mins** (keep [this principle](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html) in mind)

**Comment by antonini** [comment]
Before accepting, I want to confirm, is it to change the signture method from: 

    public interface Pass {
        Iterator<Identity> enter(Request request) throws IOException;
        // ...
    }

to:

    public interface Pass {
        Opt<Iterator<Identity>> enter(Request request) throws IOException;
        // ...
    }

Or is it to overload and deprecate the old version? My suggestion is to overload to don't created backward compatibility problem. So it will be:

    public interface Pass {
        @Deprecated
        Iterator<Identity> enter(Request request) throws IOException;
        Opt<Iterator<Identity>> enter(Request request) throws IOException;
        // ...
    }

**Comment by antonini** [comment]
Forget what I said. This is impossible! I just forgot that I can't change override the method with the same name and parameters but returning different object. Really noob.

**Comment by antonini** [comment]
@davvd Assign this to me!

**Comment by yegor256** [comment]
@antonini it's yours already, go ahead :)

**Comment by antonini** [comment]
PR #301.

**Comment by antonini** [comment]
@yegor256 Merged.

**Comment by yegor256** [comment]
@antonini thanks!

**Comment by yegor256** [comment]
@rultor release, tag is `0.18`

**Comment by davvd** [comment]
@ypshenychka please, let us know what do you think about this ticket, according to our [QA rules](http://www.teamed.io/qa.html)

**Comment by ypshenychka** [comment]
@antonini 
According to our [QA Rules](http://www.teamed.io/qa.html):
>Messages in a ticket always start with a name of a user they are addressed to.

Please always indicate a person you're referring too in the beginning of the comment/message.

Please confirm that everything is clear and you have no questions regarding this approach.

**Comment by antonini** [comment]
@ypshenychka Fixed.

**Comment by ypshenychka** [comment]
@antonini Thank you. Please keep in mind this rule in future.

**Comment by ypshenychka** [comment]
@davvd Quality is acceptable.

**Comment by davvd** [comment]
> @davvd Quality is acceptable.

@ypshenychka thanks for the QA review, we'll work better next time

**Comment by davvd** [comment]
@antonini 10 mins was added to the account of @ypshenychka (for QA review), in transaction 58183578... **30 mins** sent to your balance (ID `AP-1NY79909BL291733N`), many thanks! It took 197 hours and 23 mins.... +30 added to your rating, current score is: [+68](http://www.netbout.com/b/35346?open=rating)
