### ISSUE TITLE
SLF4J logging

### ISSUE THREAD

**Issue by yegor256** [yegor256/takes#28]
Let's create a collection of wrappers in `org.takes.facets.slf4j` for our basic interface (`Takes`, `Take`, `Fork`, etc), which will log basic parameters of methods called.

We should use them like this:

```java
new TsLogged(
  new TsFork(
    // my config...
  )
);
```

That should be enough to see everything that's going on with this takes.

**Comment by davvd** [comment]
@yegor256 got it, tag `bug` is here

**Comment by davvd** [comment]
@yegor256 many thanks, **15 mins** added to your acc for reporting this bug, pmt ID `000-bac20427`

**Comment by yegor256** [comment]
we need at lease these classes:

```
TsLogged
BkLogged
FtLogged
TkLogged
PsLogged
```

**Comment by davvd** [comment]
@dmzaytsev it's yours now, please proceed keeping in mind [our principles](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html). Feel free to ask any technical questions right here in the ticket

The budget here is **30 mins**, which is exactly how much time will be paid for, when the task is [completed](http://www.xdsd.org/2014/04/15/definition-of-done.html)

**Comment by dmzaytsev** [comment]
@yegor256 could I use @com.jcabi.aspects.Loggable ?
It will be looks like this

    public final class TsLogged implements Takes {
       private final transient Takes origin;
       public TsLogged(final Takes takes) {
           this.origin = takes;
       }

       @Override
       @Loggable
       public Take route(final Request request) throws IOException {
           return this.origin.route(request);
       }
   }

**Comment by yegor256** [comment]
@dmzaytsev no, we can't add any third-party libraries here... we should work directly with SLF4J API

**Comment by dmzaytsev** [comment]
@yegor256 
TsLogged for Takes
BkLogged for Back ?
FtLogged for Front ?
TkLogged for Take
PsLogged for Pass 

right ?

**Comment by yegor256** [comment]
@dmzaytsev exactly

**Comment by dmzaytsev** [comment]
@yegor256 could you explain please how to make right ticket for puzzle ?
e.g. in this task I need to implement a few Loggers, I will make only one and create a puzzle for others. How to make right `@todo` and create a task (s) for other classes?

**Comment by yegor256** [comment]
@dmzaytsev you create what you think you can create in the available time frame and all the rest mark leave un-implemented and add puzzles there like this:

```java
/**
 * @todo #28:30min/DEV This feature is not implemented yet, but has to be. Please
 *  implement it and don't forget about unit test. Bla-bla-bla...
 */
```

`#28:30min/DEV` is what is important. `#28` is the ticket you're working on right now. `30min` is how much time you think this implementation should take (it will become a budget of the new task). `DEV` is the role to be assigned to this task (always use `DEV`).

**Comment by dmzaytsev** [comment]
@yegor256  #89 is fixing this issue, please close  if that's all here, thank you

**Comment by yegor256** [comment]
@dmzaytsev many thanks!

**Comment by davvd** [comment]
the code made here contains a puzzle `28-4e517112`, which will be resolved soon

**Comment by davvd** [comment]
@elenavolokhova please, review this task for compliance with our [quality rules](http://www.teamed.io/qa.html)

**Comment by elenavolokhova** [comment]
@davvd This ticket looks good! :)

**Comment by davvd** [comment]
> @davvd This ticket looks good! :)

@elenavolokhova thanks for the review

**Comment by davvd** [comment]
@dmzaytsev 10 mins was added to the account of @elenavolokhova (for QA review), in transaction 54709336. I just added **38 mins** to your account, many thanks for your contribution.. 54709363 spent here. the bonus for fast delivery (age=3005). added +38 to your rating, now it is equal to [+324](http://www.netbout.com/b/35166?open=rating)

**Comment by davvd** [comment]
@yegor256 the last puzzle `28-4e517112`/#119 solved
