### ISSUE TITLE
org.takes.misc.Condition improvement

### ISSUE THREAD

**Issue by dmzaytsev** [yegor256/takes#281]
At the moment `org.takes.misc.Condition` hasn't some useful decorators. I believe `Condition.Regexp` and `Condition.Skip` has to be.

```
/**
  Apply for an item which matches given regular expression.
*/
class Regexp implements Condition<String> {
        public Regexp(Condition<String> origin, String regexp)
}

/**
   Skip items.
*/
class Skip<T> implements Condition<T> {
        public Skip(Condition<T> origin, int num)
        public Skip(Condition<T> origin, int from, int count)
}

```

It would also be useful to have `Condition.True`

```
class True implements Condition<T> {
...
    @Override
    public boolean fits(final T element) {
         return true;
    }
}

```

These classes, we can use like this

```
return new Concat<String>(
    Collections.singletonList(
         String.format("HTTP/1.1 %d %s", status, reason)
    ),
    new Select<String>(
        origin.head(),
        new Condition.Regexp(new Condition.True(), ""HTTP/1\\.1 \\d{3} [a-zA-Z ]+"")
    )
);
```

or 

```
return new Concat<String>(
    Collections.singletonList(
         String.format("HTTP/1.1 %d %s", status, reason)
    ),
    new Select<String>(
        origin.head(),
        new Condition.Skip(new Condition.True(), 1)
    )
);
```

**Comment by super132** [comment]
@dmzaytsev , what about make a `Range` condition and use with the combination of `Not` ?

For example:

```java
return new Concat<String>(
    Collections.singletonList(
         String.format("HTTP/1.1 %d %s", status, reason)
    ),
    new Select<String>(
        origin.head(),
        new Condition.Not(new Condition.Range(0))
    )
);
```

To skip a range:
```java
return new Concat<String>(
    Collections.singletonList(
         String.format("HTTP/1.1 %d %s", status, reason)
    ),
    new Select<String>(
        origin.head(),
        //skip the first 4 elements
        new Condition.Not(new Condition.Range(0, 3))
    )
);
```

**Comment by davvd** [comment]
@yegor256 please pay attention to this issue

**Comment by yegor256** [comment]
@0crat in

**Comment by 0crat** [comment]
> @0crat in ([here](https://github.com/yegor256/takes/issues/281#issuecomment-322124970))

@yegor256 Job `gh:yegor256/takes#281` is in scope.

**Comment by 0crat** [comment]
Job `gh:yegor256/takes#281` assigned to @caarlos0, please go ahead ([policy](http://datum.zerocracy.com/pages/policy.html)).

**Comment by 0crat** [comment]
@caarlos0 this job was assigned to you 8 days ago.
It will be taken away from you after 10 days from start (this is our policy).

**Comment by 0crat** [comment]
Oops! Job `gh:yegor256/takes#281` is not assigned to anyone.

**Comment by 0crat** [comment]
Oops! Job `gh:yegor256/takes#281` is not assigned to anyone.

**Comment by 0crat** [comment]
Oops! Job `gh:yegor256/takes#281` is not assigned to anyone.

**Comment by 0crat** [comment]
The job [#281](https://github.com/yegor256/takes/issues/281) assigned to @t-izbassar[/z](https://www.0crat.com/u/t-izbassar). The budget is 30 minutes, see [§4](http://datum.zerocracy.com/pages/policy.html#4). Please, read [§8](http://datum.zerocracy.com/pages/policy.html#8) and [§9](http://datum.zerocracy.com/pages/policy.html#9). If the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html).

**Comment by t-izbassar** [comment]
@0crat waiting #773

**Comment by 0crat** [comment]
> @0crat waiting #773  ([here](https://github.com/yegor256/takes/issues/281#issuecomment-359938891))

@t-izbassar The impediment for [#281](https://github.com/yegor256/takes/issues/281) was registered successfully by @t-izbassar[/z](https://www.0crat.com/u/t-izbassar)

**Comment by t-izbassar** [comment]
@0crat waiting #773

**Comment by 0crat** [comment]
> @0crat waiting #773  ([here](https://github.com/yegor256/takes/issues/281#issuecomment-361019224))

@t-izbassar Job [#281](https://github.com/yegor256/takes/issues/281) is already on hold

**Comment by t-izbassar** [comment]
@dmzaytsev can you close this one? #773 was merged.

**Comment by 0crat** [comment]
Order was successfully finished: +30 points just awarded to @t-izbassar[/z](https://www.0crat.com/u/t-izbassar), total is [+30](https://www.0crat.com/u/t-izbassar)

**Comment by 0crat** [comment]
The job [#281](https://github.com/yegor256/takes/issues/281) is now out of scope
