### ISSUE TITLE
multi-line HTTP headers are not supported

### ISSUE THREAD

**Issue by yegor256** [yegor256/takes#285]
[RFC 2616](https://www.ietf.org/rfc/rfc2616.txt) says (section 4.1): 

> Header fields can be extended over multiple lines by preceding each extra line with at least one SP or HT

In other words, this HTTP request is perfectly legal:

```
GET / HTTP/1.1
X-Foo: this is a test
 header for you
```

We should get this:

```java
new RqHeaders.Smart(new RqHeaders.Base(new RqLive(body))).single("X-Foo").equals(
  "this is a test header for you"
);
```

At the moment `RqLive` doesn't work like this.

**Comment by davvd** [comment]
@yegor256 added "bug" tag to this issue

**Comment by davvd** [comment]
@yegor256 there is no milestone yet, so I set it to `1.0`

**Comment by super132** [comment]
@davvd, could I take this task? Thanks.

**Comment by davvd** [comment]
@yamstranger the task is yours,please go ahead

**Comment by davvd** [comment]
@yegor256 many thanks, **15 mins** added to your acc for reporting this bug, pmt ID `000-7696baf9`

**Comment by YamStranger** [comment]
@davvd , @yegor256. As wrote @alice, I am not with your team any more. So please assign ticket to someone else. Thanks

**Comment by davvd** [comment]
> @davvd , @yegor256. As wrote @alice, I am not with your team any more. So please assign ticket to someone else. Thanks

@yamstranger 30 points deducted from your rating

**Comment by davvd** [comment]
> @davvd , @yegor256. As wrote @alice, I am not with your team any more. So please assign ticket to someone else. Thanks

@yamstranger right, I'll try to find someone else for this task

**Comment by davvd** [comment]
@lautarobock it's yours now, please proceed keeping in mind [our principles](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html). Feel free to ask any technical questions right here in the ticket; **30 mins** is the budget of the task. This is exactly how much will be paid when the problem is [solved](http://www.xdsd.org/2014/04/15/definition-of-done.html) (no matter how much time you will actually spend). See [this](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html) for more information

**Comment by lautarobock** [comment]
@davvd PR#300 is ready for review

**Comment by lautarobock** [comment]
@yegor256 do you need something else for close the issue?

**Comment by yegor256** [comment]
@lautarobock thanks!

**Comment by lautarobock** [comment]
@yegor256 what about my paid?

**Comment by davvd** [comment]
@ypshenychka please, let us know what do you think about this ticket, according to our [QA rules](http://www.teamed.io/qa.html)

**Comment by lautarobock** [comment]
@davvd ups, sorry, still missing QA step

**Comment by lautarobock** [comment]
@davvd but, why the bug was closed?

**Comment by yegor256** [comment]
@lautarobock I close it because it was fixed

**Comment by lautarobock** [comment]
@yegor256 Is not supposed that QA is previous to close issue?

**Comment by ypshenychka** [comment]
@davvd Quality is good.

**Comment by davvd** [comment]
> @davvd Quality is good.

@ypshenychka many thanks

**Comment by davvd** [comment]
@lautarobock I added 10 mins to @ypshenychka (for QA review) in transaction 58142983... Thanks so much! Your account was topped up for **30 mins** (transaction ID is `AP-7AD525207T301840C`, the task took 175 hours and 57 mins)... +30 to your rating, your total score is [+30](http://www.netbout.com/b/35344?open=rating)
