### ISSUE TITLE
TkGzipTest.compressesOnDemandOnly() doesn't work

### ISSUE THREAD

**Issue by yegor256** [yegor256/takes#286]
`TkGzipTest.compressesOnDemandOnly()` doesn't work, for some reason. Let's find out what the problem is (it's something in the design) and fix it.

**Comment by davvd** [comment]
@yegor256 added "bug" tag to this issue

**Comment by davvd** [comment]
@yegor256 since the ticket has no milestone I set it to 1.0

**Comment by super132** [comment]
@davvd, could I take this task? Thanks.

**Comment by davvd** [comment]
@ekondrashev please proceed, it's yours

**Comment by davvd** [comment]
@yegor256 thanks for the ticket, your account was topped for 15 mins, payment 000-ee292cfb

**Comment by ekondrashev** [comment]
@davvd this issue is blocked by #290

**Comment by davvd** [comment]
> @davvd this issue is blocked by #290 

@ekondrashev yes, of course, we'll wait for #290

**Comment by davvd** [comment]
@yegor256 FYI, issue #290 is already closed, and we were waiting for it..

**Comment by yegor256** [comment]
@ekondrashev we can continue, I guess, #290 is fixed

**Comment by ekondrashev** [comment]
@davvd #422 PR is created to handle this issue.

**Comment by davvd** [comment]
> @davvd #422 PR is created to handle this issue.

@ekondrashev thanks

**Comment by davvd** [comment]
@rultor @yegor256 please look at this issue, rultor closed it automatically

**Comment by ekondrashev** [comment]
@yegor256 please take a look if we can close this - the #422 PR was merged

**Comment by yegor256** [comment]
@ekondrashev thanks!

**Comment by davvd** [comment]
@ypshenychka review this ticket please, for compliance with our [quality rules](http://www.teamed.io/qa.html)

**Comment by ypshenychka** [comment]
@davvd Quality is good.

**Comment by davvd** [comment]
> @davvd Quality is good.

@ypshenychka thank you

**Comment by davvd** [comment]
@ekondrashev just added 10 mins to @ypshenychka (for QA), payment ID is `69090693`; done, I added **30 mins** in payment `69090696`, 273 hours and 2 mins spent to complete this; +30 to your rating, your total score is [+690](http://www.netbout.com/b/35260?open=rating)
