### ISSUE TITLE
XeTwitterLink is absent

### ISSUE THREAD

**Issue by yegor256** [yegor256/takes#287]
Similar to other "social" `Xe*Link` classes we should have `XeTwitterLink`, but it's absent at the moment. Let's create one.

**Comment by davvd** [comment]
@yegor256 tagged this issue with "bug"

**Comment by davvd** [comment]
@yegor256 attached this issue to milestone "1.0" (let me know if this is wrong)

**Comment by davvd** [comment]
@yamstranger it's yours,please go ahead

**Comment by davvd** [comment]
@yegor256 thanks for the report, I topped your acc for 15 mins, payment ID `000-70cbb012`

**Comment by YamStranger** [comment]
@davvd , @yegor256. As wrote @alice, I am not with your team any more. So please assign ticket to someone else. Thanks

**Comment by davvd** [comment]
> @davvd , @yegor256. As wrote @alice, I am not with your team any more. So please assign ticket to someone else. Thanks

@yamstranger deducted 30 from your rating :(

**Comment by davvd** [comment]
> @davvd , @yegor256. As wrote @alice, I am not with your team any more. So please assign ticket to someone else. Thanks

@yamstranger right, I will find someone else, no problem

**Comment by davvd** [comment]
@ikhvostenkov please proceed, it's yours

**Comment by davvd** [comment]
@ikhvostenkov this task is in your hands for 15 days already; -30 added to your rating, at the moment it is: [+85](http://www.netbout.com/b/35232?open=rating)

**Comment by davvd** [comment]
@ikhvostenkov this task is not yours any more (took too long), please stop. I'll give you something else

-60 added to your rating, current score is: [+25](http://www.netbout.com/b/35232?open=rating)

**Comment by davvd** [comment]
@ekondrashev the task is yours, please go ahead

**Comment by ekondrashev** [comment]
@davvd I understand you policy, but there is a PR #305 available pending @yegor256 comments.
@ikhvostenkov did provide an implementation for that defect, but the review took more time then expected, so I believe he missed a chance to ask for more time on this. 
So, @davvd can you perhaps give @ikhvostenkov another chance to complete this considering all said?

If I take this task, I'll be still pending @yegor256 comments for #305.

**Comment by yegor256** [comment]
@davvd please assign @ikhvostenkov back to this task

**Comment by davvd** [comment]
> @davvd please assign @ikhvostenkov back to this task

@yegor256 done! @ikhvostenkov the task is yours, please proceed

**Comment by ikhvostenkov** [comment]
@yegor256 I've closed PR for this ticket due to current Twitter OAuth mechanism should be redone. If you do not have any comments here, could you please close this then.

**Comment by yegor256** [comment]
@ikhvostenkov indeed, this is closed, thanks for the attempt

**Comment by davvd** [comment]
@elenavolokhova please, let us know what do you think about this ticket, according to our [QA rules](http://www.teamed.io/qa.html)

**Comment by elenavolokhova** [comment]
@ikhvostenkov 
 According to our [quality rules](http://www.teamed.io/qa.html):
 > The ticket is closed only when the reported problem is solved.
 
 This ticket was closed with no final solution provided.

@yegor256 Could you please help here? Should it be paid?

**Comment by ikhvostenkov** [comment]
@elenavolokhova This ticket was closed due to this ticket not actual any more because of some problem on the upper level. So not actual ticket - no solution.

**Comment by elenavolokhova** [comment]
@ikhvostenkov Thank you for clarification!

**Comment by elenavolokhova** [comment]
@davvd Quality is bad here.

**Comment by davvd** [comment]
> @davvd Quality is bad here.

@elenavolokhova thank you very much

**Comment by davvd** [comment]
@ikhvostenkov I added 10 mins to @elenavolokhova (for QA review) in transaction 59102833
