### ISSUE TITLE
It is not clear from the Response.java documentation if head and body calls should be ordered 

### ISSUE THREAD

**Issue by ekondrashev** [yegor256/takes#290]
`org.takes.Response` documentation misses information whether `head` and `body` calls should be ordered or not. For example, if `body` call should be forwarded by `head` call or vice versa or those calls should be completely independent and it is safe to call them in whatever order.

If it depends on the implementation - it is also should be stated.

**Comment by davvd** [comment]
@ekondrashev milestone set to `1.0` (correct me if I am wrong)

**Comment by davvd** [comment]
@yegor256 this is yours, pls go ahead

**Comment by davvd** [comment]
@ekondrashev thank you for reporting this, I added 15 mins to your acc, transaction `57288754`

**Comment by yegor256** [comment]
@davvd assign someone else pls

**Comment by davvd** [comment]
> @davvd assign someone else pls

@yegor256 -30 points to your rating

**Comment by davvd** [comment]
> @davvd assign someone else pls

@yegor256 right, I will find someone else, no problem

**Comment by davvd** [comment]
@kpbird please pick this up, and keep in mind [these instructions](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html). Any technical questions - ask right here. The budget of this task is **30 mins**. This is exactly how much time will be compensated, when the task is completed. Read about our [Definition of Done](http://www.xdsd.org/2014/04/15/definition-of-done.html)

**Comment by davvd** [comment]
@bdragan it's yours now, please proceed keeping in mind [our principles](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html). Feel free to ask any technical questions right here in the ticket. The budget of this task is **30 mins**. This is exactly how much time will be compensated, when the task is completed. Read about our [Definition of Done](http://www.xdsd.org/2014/04/15/definition-of-done.html)

**Comment by bdragan** [comment]
@ekondrashev PR #409 has been merged successfully. Please review the solution and close this issue if you find the solution acceptable.

**Comment by ekondrashev** [comment]
@bdragan nice! thank you.

**Comment by davvd** [comment]
@elenavolokhova please, review this ticket for compliance with our [QA rules](http://www.teamed.io/qa.html)

**Comment by elenavolokhova** [comment]
@davvd Looks good!

**Comment by davvd** [comment]
> @davvd Looks good!

@elenavolokhova thank you :)

**Comment by davvd** [comment]
@bdragan 10 mins was added to the account of @elenavolokhova (for QA review), in transaction 68334673

Thank you, I have added **30 mins** to your account in payment/transaction "`68334683`", time consumed: 167 hours and 33 mins

added +30 to your rating, now it is equal to [+83](http://www.netbout.com/b/35709?open=rating)
