### ISSUE TITLE
FbStatus without second argument

### ISSUE THREAD

**Issue by yegor256** [yegor256/takes#292]
Let's create a new ctor in `FbStatus`, with a single `int` argument. When being used like this:

```java
new FbStatus(404);
```

It should return a response, which looks like this:

```
HTTP/1.1 404 Not Found
Content-Type: text/plain

404 Not Found: <exception message>
```

Where `<exception message>` is the message of the exception from `RqFallback`

**Comment by davvd** [comment]
@yegor256 I tagged this as "bug"

**Comment by davvd** [comment]
@yegor256 since there is no milestone yet I set it to "1.0"

**Comment by davvd** [comment]
@komaz the task is for you now, follow [these guidelines](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html). Don't hesitate to ask any technical questions right here; Total fixed cost of this task is **30 mins** (see [this](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html) for more info)

**Comment by davvd** [comment]
@yegor256 thank you for reporting this, I added 15 mins to your acc, transaction `000-dc409047`

**Comment by komaz** [comment]
@davvd can I take this issue back?

**Comment by yegor256** [comment]
@davvd assign @komaz to this task pls

**Comment by davvd** [comment]
> @davvd assign @komaz to this task pls

@yegor256 no problem, @komaz is already assigned to this task, please go on

**Comment by komaz** [comment]
@yegor256 the mapping from status code to explanation message is currently defind in private static map `RsWithStatus::REASONS`. Is it ok to extract this map into a separate class `Status`, so that both `RsWithStatus` and `FbStatus` would use `new Status(code).message()`? 

Actually I did all changes in [my branch](https://github.com/komaz/takes/commit/72bc42eda24786510ed62cee79d241d4d41a9b20), but as it depends on #295 fix, I'm not submitting a pull request yet.

**Comment by yegor256** [comment]
@komaz I don't think it's a good idea. in `FbStatus` you have an instance of `Response` already. you can extract that status line from it. Right?

**Comment by komaz** [comment]
@yegor256 I think if instantiate `FbStatus` only with `code`argument, all I have is `RqFallback` instance. Indeed, I can instantiate `RsWithStatus(code)`, take a `head()` from it, strip `HTTP 1.1 ` from the first line, and use the rest as the prefix for response body, but I thought it would be a leak of abstraction here and relying on the fact that `RsWithStatus` forms the first line of response head correctly. Am I missing something?

**Comment by yegor256** [comment]
@komaz yes, that's what I have in mind. I don't think it's a leak of abstraction. It's a HTTP request, which is supposed to be well-formed.

**Comment by komaz** [comment]
@yegor256 thanks, that makes sense. I'll implement it in suggested way tomorrow.

**Comment by komaz** [comment]
@yegor256 fixed in pull request #303, please close the issue

**Comment by yegor256** [comment]
@komaz thanks!

**Comment by davvd** [comment]
@ypshenychka please, let us know what do you think about this ticket, according to our [QA rules](http://www.teamed.io/qa.html)

**Comment by ypshenychka** [comment]
@davvd Quality is good.

**Comment by davvd** [comment]
> @davvd Quality is good.

@ypshenychka thank you :)

**Comment by davvd** [comment]
@komaz just added 10 mins to @ypshenychka (for QA), payment ID is `58060807`. Thank you, I have added **30 mins** to your account in payment/transaction "`AP-2BH486317W298141R`", time consumed: 168 hours and 26 mins. added +30 to your rating, now it is equal to [+165](http://www.netbout.com/b/35322?open=rating)
