### ISSUE TITLE
RsWithCookie must combine cookies

### ISSUE THREAD

**Issue by yegor256** [yegor256/takes#293]
At the moment, if I do this:

```java
new RsWithCookie(
  new RsWithCookie(
    new RqFake(),
    "foo", "test1"
  ),
  "bar", "test2"
);
```

I'm getting this:

```
HTTP/1.1 200 OK 
Set-Cookie: foo=test1
Set-Cookie: bar=test2
```

This is not correct and browsers will only read the first `Set-Cookie`. Cookie `bar` won't be set.

Proper response should look like this:

```
HTTP/1.1 200 OK 
Set-Cookie: foo=test1,bar=test2
```

**Comment by davvd** [comment]
@yegor256 I tagged this as "bug"

**Comment by davvd** [comment]
@yegor256 attached this issue to milestone "1.0" (let me know if this is wrong)

**Comment by davvd** [comment]
@bertram25 the task is for you now, follow [these guidelines](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html). Don't hesitate to ask any technical questions right here. The budget here is **30 mins**, which is exactly how much time will be paid for, when the task is [completed](http://www.xdsd.org/2014/04/15/definition-of-done.html)

**Comment by davvd** [comment]
@yegor256 many thanks for the bug report, I added 15 mins to your acc, transaction `000-2a911432`

**Comment by Bertram25** [comment]
@davvd I'll commit the PR fixing this issue in one or two hours (It is working locally but still need static analysis fixes.). I may have to need more time for the review and the ticket cleanup, though. Can you give me one more day, in case I need it?

**Comment by Bertram25** [comment]
@davvd PR #314 ready for review. :)

**Comment by carlosmiranda** [comment]
@davvd Need a bit more time

**Comment by davvd** [comment]
> @davvd Need a bit more time

@carlosmiranda OK, take your time

**Comment by Bertram25** [comment]
@yegor256 Hi, :)

Should I wait for QA review here, as the PR was merged and comments are following the requested standard, or should I explicitly request it?

Best regards,

**Comment by yegor256** [comment]
@Bertram25 first, you should make sure the author of the ticket closed it, see http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html

**Comment by Bertram25** [comment]
@yegor256 Thanks. In that case, the PR fixing this issue is merged and the issue comments are clean. Could you close the issue?

**Comment by yegor256** [comment]
@Bertram25 thanks!

**Comment by davvd** [comment]
@elenavolokhova please, review this task for compliance with our [quality rules](http://www.teamed.io/qa.html)

**Comment by elenavolokhova** [comment]
@davvd Looks good!

**Comment by davvd** [comment]
> @davvd Looks good!

@elenavolokhova many thanks

**Comment by davvd** [comment]
@bertram25 just added 10 mins to @elenavolokhova (for QA), payment ID is `59104702`

Many thanks! **30 mins** were added to your account in Transaction ID `AP-0C5107568A596262E` (task took 643 hours and 56 mins)

+30 added to your rating, at the moment it is: [+60](http://www.netbout.com/b/35317?open=rating)
