### ISSUE TITLE
Fallback.route() should return Iterable instead of Iterator

### ISSUE THREAD

**Issue by super132** [yegor256/takes#294]
`Fallback.route()` now returns an `Iterator` as a collection of `Response`. However, from design and semantic perspective it should return an `Iterable` for better representation of a list of `Response`.

**Comment by super132** [comment]
From the use cases of `Fallback` interface, the implementations always look for one single value from the `Iterator` returned from `route()`. It could be better to use `Opt` instead of iterables.

**Comment by yegor256** [comment]
@super132 yes, should be `Opt`

**Comment by davvd** [comment]
@super132 I will find a developer for the task soon...

**Comment by davvd** [comment]
@super132 I set milestone here to `1.0`, let me know if it is wrong

**Comment by davvd** [comment]
@ekondrashev please go ahead with this task,it's yours

**Comment by davvd** [comment]
@super132 thanks for reporting! I topped your account for 15 mins, transaction AP-2CE90578J63113255

**Comment by ekondrashev** [comment]
@yegor256 `FbStatus` actually requires all the Fallbacks that match the check condition. I afraid `Opt` would not work here.
@super132 Am I missing something?

**Comment by super132** [comment]
@ekondrashev , if you take a closer look in `FbStatus`, the codes actually checks the first element returned from the iterator from `Fallback`, not loop through the iterable until no elements are found. I extract the codes here for easy reference. And now all the `Fallback` implementations return only an iterator with only one element, which is why `Opt` is better suit for `Iterator`

```java
public FbStatus(final FbStatus.Check check, final Fallback fallback) {
        super(
            new Fallback() {
                @Override
                public Iterator<Response> route(final RqFallback req)
                    throws IOException {
                    final Collection<Response> rsp = new ArrayList<Response>(1);
                    if (check.fits(req.code())) {
                        final Iterator<Response> iter = fallback.route(req);
                        if (iter.hasNext()) {
                            rsp.add(iter.next());
                        }
                    }
                    return rsp.iterator();
                }
            }
        );
    }
```

**Comment by ekondrashev** [comment]
@super132 my bad, overlooked that there is no loop, thx!

**Comment by ekondrashev** [comment]
@davvd the PR is on review stage, not sure how to speedup the process(waiting for 2d already)

**Comment by yegor256** [comment]
@ekondrashev just ping the author time to time.. that's the best you can do

**Comment by davvd** [comment]
@ekondrashev this task is in your hands for 15 days already... -30 added to your rating, at the moment it is: [+151](http://www.netbout.com/b/35260?open=rating)

**Comment by ekondrashev** [comment]
@yegor256 @davvd 
I'm wondering why it is only myself responsible for the delay when the process also depends on reviewer?  Originally PR was created 13d ago and first comment on it I got almost a week after. Something is wrong here.

**Comment by yegor256** [comment]
@ekondrashev check this: http://www.teamed.io/policy.html#10 and this: http://www.teamed.io/policy.html#11

**Comment by ekondrashev** [comment]
@davvd waiting for PR #304 review to be completed.

**Comment by davvd** [comment]
> @davvd waiting for PR #304 review to be completed. 

@ekondrashev we can't call #304 an impediment, it's a pull request

**Comment by ekondrashev** [comment]
@davvd need more time on #294 since it takes more time to review the #304 PR then expected.

**Comment by davvd** [comment]
> @davvd need more time on #294 since it takes more time to review the #304 PR then expected.

@ekondrashev right, take your time and thanks for informing

**Comment by ekondrashev** [comment]
@davvd this one is blocked by #333 
It prevents the #304 PR to be merged

**Comment by ekondrashev** [comment]
@davvd after merge retry problematic test passed, no block here.
@super132 please close this ticket, you can solution at PR #304

**Comment by super132** [comment]
@ekondrashev thanks.

**Comment by davvd** [comment]
@elenavolokhova please, review this task for compliance with our [quality rules](http://www.teamed.io/qa.html)

**Comment by elenavolokhova** [comment]
@davvd Looks good!

**Comment by davvd** [comment]
> @davvd Looks good!

@elenavolokhova thanks a lot :)

**Comment by davvd** [comment]
@ekondrashev I added 10 mins to @elenavolokhova (for QA review) in transaction 58704465; Thanks so much! Your account was topped up for **30 mins** (transaction ID is `58704479`, the task took 501 hours and 9 mins); +30 added to your rating, at the moment it is: [+226](http://www.netbout.com/b/35260?open=rating)
