### ISSUE TITLE
FbStatus.Check can be replaced by org.take.msic.Condition

### ISSUE THREAD

**Issue by super132** [yegor256/takes#295]
`FbStatus.Check` interface is perform exactly the same job as `org.take.misc.Condition`. I think we should replace 'FbStatus.Check` by `Condition<Integer>`.

**Comment by yegor256** [comment]
@super132 totally agree

**Comment by davvd** [comment]
@super132 we will find someone to do this task, soon

**Comment by davvd** [comment]
@super132 I set the milestone to 1.0 since there is nothing set yet

**Comment by davvd** [comment]
@komaz please pick this up, and keep in mind [these instructions](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html). Any technical questions - ask right here... Task's budget is **30 mins** (see [this](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html) for explanation)

**Comment by davvd** [comment]
@super132 thanks a lot for reporting, **15 mins** added to your acc, pmt ID `AP-2WU555980T275231V`

**Comment by komaz** [comment]
@davvd can I take this issue as it was on me previously?

**Comment by yegor256** [comment]
@davvd pls assign @komaz to this ticket

**Comment by davvd** [comment]
> @davvd pls assign @komaz to this ticket

@yegor256 done, @komaz is assigned to this task, and is already working on it, AFAIK

**Comment by komaz** [comment]
@super

**Comment by super132** [comment]
@komaz thanks!

**Comment by davvd** [comment]
@elenavolokhova please, let us know what do you think about this ticket, according to our [QA rules](http://www.teamed.io/qa.html)

**Comment by elenavolokhova** [comment]
@komaz 
 According to our [quality rules](http://www.teamed.io/qa.html):
 > Some of ticket messages must mention all pull requests where the problem was actually fixed.
 
 There is no link to related PR in comments. Please fix this issue and try to follow this rule in your tickets in the future.

**Comment by komaz** [comment]
@elenavolokhova thank you for pointing to this. Here's the link to pull request where the issue has been fixed: #297

**Comment by elenavolokhova** [comment]
@komaz Thank you!

**Comment by elenavolokhova** [comment]
@davvd Quality is acceptable here.

**Comment by davvd** [comment]
> @davvd Quality is acceptable here.

@elenavolokhova thanks for the review, we'll try better next time

**Comment by davvd** [comment]
@komaz just added 10 mins to @elenavolokhova (for QA), payment ID is `57697366`; Thank you, I have added **45 mins** to your account in payment/transaction "`AP-3KP61285XF178741B`", time consumed: 24 hours and 25 mins; m=1465, that's why a bonus here for fast delivery; +45 added to your rating, current score is: [+90](http://www.netbout.com/b/35322?open=rating)
