### ISSUE TITLE
RsPrettyXML

### ISSUE THREAD

**Issue by yegor256** [yegor256/takes#296]
Let's create `RsPrettyXML` class, which will re-format response body to make it look "pretty" indented:

```java
System.out.println(
  new RsPrint(
    new RsPrettyXML(
      new RsWithBody(
        "<test><a>foo</a></test>"
      )
    )
  ).printBody()
);
```

I expect this result:

```
<test>
  <a>foo</a>
</test>
```

**Comment by davvd** [comment]
@yegor256 tagged this issue with "bug"

**Comment by davvd** [comment]
@yegor256 since there is no milestone yet I set it to "1.0"

**Comment by davvd** [comment]
@yegor256 thank you for reporting this, I added 15 mins to your acc, transaction `000-ceb43c29`

**Comment by davvd** [comment]
@ikhvostenkov the task is yours, please go ahead

**Comment by ikhvostenkov** [comment]
@yegor256 Issue has been fixed with https://github.com/yegor256/takes/pull/308. If you do not have any comments here, could you please close this.

**Comment by yegor256** [comment]
@ikhvostenkov thanks!

**Comment by yegor256** [comment]
@rultor release, tag is `0.17`

**Comment by yegor256** [comment]
@rultor release, tag is `0.17`

**Comment by davvd** [comment]
@ypshenychka please, review this task for compliance with our [quality rules](http://www.teamed.io/qa.html)

**Comment by ypshenychka** [comment]
@davvd Ticket should have assignee. Please assign @ikhvostenkov to this task.

**Comment by ypshenychka** [comment]
@davvd I see there is a corresponding label on the ticket. Please ignore my previous message.

**Comment by ypshenychka** [comment]
@davvd Quality is good here.

**Comment by davvd** [comment]
> @davvd Quality is good here.

@ypshenychka many thanks

**Comment by davvd** [comment]
@ikhvostenkov just added 10 mins to @ypshenychka (for QA), payment ID is `57788744`. I added **30 mins** to your account, many thanks for working with the project! The completion time here was 57788756.. added +30 to your rating, now it is equal to [+145](http://www.netbout.com/b/35232?open=rating)
