### ISSUE TITLE
RsWithType overrides status code

### ISSUE THREAD

**Issue by komaz** [yegor256/takes#298]
`RsWithType` wraps given response into `RsWithStatus` internally, hence overriding an existing status (if set). Here's modified snippet from `org.takes.Response` javadoc (I just did a seemingly safe replacement from `RsWithHeader` to `RsWithType`):
```java
final Response response = new RsWithType(
   new RsWithBody(
     new RsWithStatus(500),
     "hello, world!"
   ),
   "text/html"
 );
```
As a result, the response status will be 200, not 500.

This as well affects `RsText(Response)` ctor – besides just setting content type to `text/plain`, it changes response code to 200.

**Comment by yegor256** [comment]
@davvd this is definitely a bug

**Comment by davvd** [comment]
> @davvd this is definitely a bug

@yegor256 added "bug" tag to this issue

**Comment by davvd** [comment]
@komaz I set the milestone to 1.0 since there is nothing set yet

**Comment by davvd** [comment]
@komaz thank you for the ticket reported, I topped your account for 15 mins, transaction `AP-7DU45288RK7657840`

**Comment by davvd** [comment]
@ekondrashev please go ahead with this task, it's yours

**Comment by ekondrashev** [comment]
@komaz please close the ticket, the fix can be found at #299

**Comment by komaz** [comment]
@ekondrashev thank you

**Comment by davvd** [comment]
@ypshenychka please, review this task for compliance with our [quality rules](http://www.teamed.io/qa.html)

**Comment by ypshenychka** [comment]
@davvd Quality is good.

**Comment by davvd** [comment]
> @davvd Quality is good.

@ypshenychka thank you

**Comment by davvd** [comment]
@ekondrashev just added 10 mins to @ypshenychka (for QA), payment ID is `57724542`... **45 mins** was added to your account, many thanks for your contribution! The task took 57724559.... m=2624, that's why a bonus here for fast delivery... +45 to your rating, your total score is [+136](http://www.netbout.com/b/35260?open=rating)
