### ISSUE TITLE
The system may throw an UnsupportedOperationException

### ISSUE THREAD

**Issue by antonini** [yegor256/takes#302]
Due the issue #278 and the PR #301 is possible that the system throw an UnsupportedOperationException.

Those are the related Classes: PsByFlag (line 111), PsChain (line 74) and TkAuth (line 89) Is possible that the system throws an UnsupportedOperationException.

It was not possible to implement any validation without breaking any Checkstyle rule.

**Comment by yegor256** [comment]
@antonini I didn't get what the bug is about? the build is clean, as I understand. how can I reproduce the problem you're writing about? see this: http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html#5.-report-when-it-is-broken

**Comment by yegor256** [comment]
@antonini I would suggest to close this ticket if you can't explain the problem better

**Comment by antonini** [comment]
Issue cancelled.
