### ISSUE TITLE
BkParallelTest#requestsAreParallel is not stable

### ISSUE THREAD

**Issue by yegor256** [yegor256/takes#309]
see http://www.rultor.com/t/3825-104206767

```
requestsAreParallel(org.takes.http.BkParallelTest) Time elapsed: 60.011 sec <<< FAILURE! java.lang.AssertionError: Expected: <0L> but: was <1L> at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20) at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:8) at org.takes.http.BkParallelTest.requestsAreParallel(BkParallelTest.java:123) at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57) at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) at java.lang.reflect.Method.invoke(Method.java:606) at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50) at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12) at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47) at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17) at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325) at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78) at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57) at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290) at org.apache.maven.surefire.junitcore.pc.Scheduler$1.run(Scheduler.java:318) at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471) at java.util.concurrent.FutureTask.run(FutureTask.java:262) at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145) at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615) at java.lang.Thread.run(Thread.java:745)
```

Looks like this test is not stable enough, let's fix

**Comment by davvd** [comment]
@yegor256 tag "bug" added

**Comment by davvd** [comment]
@yegor256 I set milestone here to `1.0`, let me know if it is wrong

**Comment by davvd** [comment]
@yegor256 thanks a lot for reporting, **15 mins** added to your acc, pmt ID `000-5b09e1d5`

**Comment by davvd** [comment]
@lautarobock This task is yours, please go ahead keeping in mind [this](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html). If any questions, don't hesitate to ask right here. Total fixed cost of this task is **30 mins** (see [this](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html) for more info)

**Comment by lautarobock** [comment]
@yegor256 sorry, but this change https://github.com/yegor256/takes/commit/b410f18c49f068107c608f5454be1dfca29505c0#diff-2c4573ba2da139758fe825e6e708de8eL57 doesn't increase the number of threads instead of decrease?

**Comment by yegor256** [comment]
@lautarobock I think this change increases the number of threads. it multiplies them by 4

**Comment by lautarobock** [comment]
@yegor256 but, commit comment says "--threads", so I thought that you want to decrease it

**Comment by lautarobock** [comment]
@yegor256 I think the instability of this test is caused by using 4 times `Runtime.getRuntime().availableProcessors()` . do you think is right?

**Comment by yegor256** [comment]
@lautarobock I don't know... but the test has to work (stable enough) with any amount of threads.

**Comment by lautarobock** [comment]
@davvd PR #316 is ready for review

**Comment by lautarobock** [comment]
@davvd PR #316 is ready for review again

**Comment by lautarobock** [comment]
@yegor256 Should we wait few builds just for checking stability?

**Comment by yegor256** [comment]
@lautarobock I'll close, thanks. If we have similar problem in the future, I'll open a new ticket. Thanks!

**Comment by lautarobock** [comment]
@yegor256 ok

**Comment by davvd** [comment]
@elenavolokhova please, let us know what do you think about this ticket, according to our [QA rules](http://www.teamed.io/qa.html)

**Comment by elenavolokhova** [comment]
@davvd Quality is good here.

**Comment by davvd** [comment]
> @davvd Quality is good here.

@elenavolokhova thanks a lot :)

**Comment by davvd** [comment]
@lautarobock just added 10 mins to @elenavolokhova (for QA), payment ID is `58668929`

Thanks so much! Your account was topped up for **30 mins** (transaction ID is `AP-5YG1163722219383N`, the task took 186 hours and 4 mins)

+30 added to your rating, at the moment it is: [+120](http://www.netbout.com/b/35344?open=rating)
