### ISSUE TITLE
RsText overrides status code

### ISSUE THREAD

**Issue by komaz** [yegor256/takes#310]
Whatever you wrap into `RsText`, you get status 200.
```java
        MatcherAssert.assertThat(
            new RsPrint(
                new RsText(
                    new RsWithStatus(HttpURLConnection.HTTP_NOT_FOUND),
                    "something not found"
                )
            ).printHead(),
            Matchers.containsString(
                Integer.toString(HttpURLConnection.HTTP_NOT_FOUND)
            )
        );
```
Fails with:
````
java.lang.AssertionError: 
Expected: a string containing "404"
     but: was "HTTP/1.1 200 OK
Content-Length: 19
Content-Type: text/plain
```

**Comment by komaz** [comment]
I guess the root reason for this issue is making it possible to use a simple `new RsText(String)` constructor to create a complete response with a status

**Comment by yegor256** [comment]
@komaz definitely a bug, thanks

**Comment by davvd** [comment]
@komaz this task will get someone's attention soon

**Comment by davvd** [comment]
@komaz milestone set to `1.0` (correct me if I am wrong)

**Comment by davvd** [comment]
@komaz many thanks for the report, I topped your account for 15 mins, transaction AP-24K9560902440405A

**Comment by davvd** [comment]
@mbarbieri This task is yours, please go ahead keeping in mind [this](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html). If any questions, don't hesitate to ask right here. The budget here is **30 mins**, which is exactly how much time will be paid for, when the task is [completed](http://www.xdsd.org/2014/04/15/definition-of-done.html)

**Comment by mbarbieri** [comment]
@davvd PR #324 ready to be reviewed

**Comment by davvd** [comment]
@rultor rultor closed it (automatically), @komaz please take a look

**Comment by komaz** [comment]
@mbarbieri thanks

**Comment by davvd** [comment]
@elenavolokhova please, review this ticket for compliance with our [QA rules](http://www.teamed.io/qa.html)

**Comment by elenavolokhova** [comment]
@mbarbieri 
> komaz commented 15 days ago
I guess the root reason for this issue is making it possible to use a simple new RsText(String) constructor to create a complete response with a status

 According to our [quality rules](http://www.teamed.io/qa.html):
 > Messages in a ticket always start with a name of a user they are addressed to.
 
 As far as you are the performer of this ticket you are responsible for its quality. Please make sure that everyone follows this rule in your tickets in the future. Ask them to fix issues before closing the ticket.
 
 Please confirm that everything is clear and you have no questions regarding this approach.

**Comment by mbarbieri** [comment]
@komaz please fix your comment 
```
komaz commented 15 days ago
I guess the root reason for this issue is making it possible to use a simple new RsText(String) constructor to create a complete response with a status
```
Thanks

**Comment by mbarbieri** [comment]
@elenavolokhova everything is clear, thanks.

**Comment by komaz** [comment]
@mbarbieri done

**Comment by elenavolokhova** [comment]
@mbarbieri @komaz Thank you!

**Comment by elenavolokhova** [comment]
@davvd Quality is acceptable.

**Comment by davvd** [comment]
> @davvd Quality is acceptable.

@elenavolokhova thank you, let's try to make it "good" next time

**Comment by davvd** [comment]
@mbarbieri 10 mins was added to the account of @elenavolokhova (for QA review), in transaction 58669368

**30 mins** sent to your balance (ID `AP-4K77953469720220R`), many thanks! It took 156 hours and 44 mins.

+30 added to your rating, at the moment it is: [+68](http://www.netbout.com/b/35357?open=rating)
