### ISSUE TITLE
RsPrettyJSON

### ISSUE THREAD

**Issue by yegor256** [yegor256/takes#312]
Let's create class `RsPrettyJSON` similar to `RsPrettyXML` (see #296), to format JSON nicely

**Comment by davvd** [comment]
@yegor256 tagged this issue with "bug"

**Comment by davvd** [comment]
@yegor256 I set milestone here to `1.0`, let me know if it is wrong

**Comment by davvd** [comment]
@yegor256 many thanks for the report, I topped your account for 15 mins, transaction 000-08a1988c

**Comment by davvd** [comment]
@marcuss the task is for you now, follow [these guidelines](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html). Don't hesitate to ask any technical questions right here; This task's budget is **30 mins**. This is exactly how much will be paid when the problem explained above is solved. See [this](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html) for more information

**Comment by davvd** [comment]
@ekondrashev it's yours,please go ahead

**Comment by ekondrashev** [comment]
@davvd thanks!

**Comment by ekondrashev** [comment]
@yegor256 please close this one, solution provided with #332 .

**Comment by yegor256** [comment]
@rultor release, tag is `0.21`

**Comment by yegor256** [comment]
@ekondrashev thanks!

**Comment by davvd** [comment]
@elenavolokhova review this ticket please, for compliance with our [quality rules](http://www.teamed.io/qa.html)

**Comment by elenavolokhova** [comment]
@davvd Quality is good here!

**Comment by davvd** [comment]
> @davvd Quality is good here!

@elenavolokhova many thanks

**Comment by davvd** [comment]
@ekondrashev I added 10 mins to @elenavolokhova (for QA review) in transaction 59105794

thanks, paid, **30 mins** to your account, payment ID is `59105815`, task took 167 hours and 40 mins to complete

+30 to your rating, your total score is [+256](http://www.netbout.com/b/35260?open=rating)
