### ISSUE TITLE
TkReturn and RsReturn

### ISSUE THREAD

**Issue by yegor256** [yegor256/takes#317]
Let's introduce `org.takes.facets.ret.*` classes, which will help us to return to some page after login. See more details in https://github.com/yegor256/netbout/issues/609 and https://github.com/yegor256/netbout/issues/646

**Comment by davvd** [comment]
@yegor256 this task will get someone's attention soon

**Comment by davvd** [comment]
@yegor256 milestone set to `1.0` (correct me if I am wrong)

**Comment by davvd** [comment]
@komaz it's yours,budget is 30 mins,please go ahead

**Comment by davvd** [comment]
@yegor256 thanks for reporting! I topped your account for 15 mins, transaction 000-f053c61a

**Comment by komaz** [comment]
@yegor256 fixed in pull request #325

**Comment by yegor256** [comment]
@komaz thanks!

**Comment by yegor256** [comment]
@rultor release, tag is `0.20`

**Comment by davvd** [comment]
@elenavolokhova please, review this task for compliance with our [quality rules](http://www.teamed.io/qa.html)

**Comment by elenavolokhova** [comment]
@davvd Quality is good here.

**Comment by davvd** [comment]
> @davvd Quality is good here.

@elenavolokhova thanks for the review and a good remark

**Comment by davvd** [comment]
@komaz just added 10 mins to @elenavolokhova (for QA), payment ID is `58670087`

done, I added **30 mins** in payment `AP-4F19210001430823G`, 161 hours and 15 mins spent to complete this

+30 to your rating, your total score is [+390](http://www.netbout.com/b/35322?open=rating)
