### ISSUE TITLE
RqFake should allow form params

### ISSUE THREAD

**Issue by krzyk** [yegor256/takes#321]
When testing a form processing `Take` there is no clean way of adding form params (URL or body) to the request, one has to do manual encoding and creation of the appropriate string.
Please add such processing to `RqFake` (or maybe other class if appropriate), and describe it in the README section regarding unit tests.

**Comment by yegor256** [comment]
@krzyk maybe something like this:

```java
new RqForm.Fake(
  new RqFake(),
  "foo", "value-1",
  "bar", "value-2"
)
```

What do you think?

**Comment by krzyk** [comment]
@yegor256 yes, looks good

**Comment by davvd** [comment]
@krzyk we will find someone to do this task, soon

**Comment by davvd** [comment]
@krzyk I set milestone here to `1.0`, let me know if it is wrong

**Comment by davvd** [comment]
@krzyk thanks for the ticket, your account was topped for 15 mins, payment 58531652

**Comment by davvd** [comment]
@mbarbieri this task is yours, please help (see our key [principles of work](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html)). If you have any technical questions, don't hesitate to ask right here... This task's budget is **30 mins**. This is exactly how much will be paid when the problem explained above is solved. See [this](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html) for more information

**Comment by mbarbieri** [comment]
@yegor256 @krzyk I see that ```RqForm`` has 
```
Iterable<String> param(CharSequence name)
```
that can return a list of values for the same name.
How should they be separated in the constructor?
Like this:
```
new RqForm.Fake(
  new RqFake(),
  "foo", "value-1,value-11",
)
```
or maybe like this:
```
new RqForm.Fake(
  new RqFake(),
  "foo", "value-1",
  "foo", "value-11"
)
```

**Comment by yegor256** [comment]
@mbarbieri I think like this:

```
new RqForm.Fake(
  new RqFake(),
  "foo", "value-1",
  "foo", "value-11"
)
```

**Comment by mbarbieri** [comment]
@davvd PR #334 is ready to be reviewed.

**Comment by mbarbieri** [comment]
@krzyk @yegor256 can this issue be closed?

**Comment by krzyk** [comment]
@mbarbieri thanks

**Comment by davvd** [comment]
@ypshenychka please, review this task for compliance with our [quality rules](http://www.teamed.io/qa.html)

**Comment by ypshenychka** [comment]
@krzyk 
According to our [QA Rules](http://www.teamed.io/qa.html):
>The ticket is closed only when the reported problem is solved, see.

If I am not mistaken, the correponding PR is not yet closed as far as there are some major design concerns. 
Please do a reopen and close the issue only when reported problem is solved and code is successfully merged.

**Comment by krzyk** [comment]
@ypshenychka you are right, I didn't check the merge status correctly, sorry for that

**Comment by ypshenychka** [comment]
@krzyk Thank you! Let's wait for PR #334 to be finished and then we will come back to this ticket.

**Comment by davvd** [comment]
@mbarbieri you're working with this issue for 15 days already... -30 added to your rating, current score is: [+113](http://www.netbout.com/b/35357?open=rating)

**Comment by davvd** [comment]
@mbarbieri this task is not yours any more (took too long), please stop. I'll give you something else; -60 added to your rating, current score is: [+53](http://www.netbout.com/b/35357?open=rating)

**Comment by davvd** [comment]
@erimerturk please go ahead with this task, it's yours

**Comment by erimerturk** [comment]
@davvd another people is working on this issue, what should i do ?

**Comment by yegor256** [comment]
@erimerturk ignore them, it's your task, do it

**Comment by erimerturk** [comment]
@davvd i need more time for this task i couldn't started it because another people was working on it, thank you

**Comment by davvd** [comment]
> @davvd i need more time for this task i couldn't started it because another people was working on it, thank you 

@erimerturk no problem, thanks for letting me know

**Comment by erimerturk** [comment]
@krzyk please see PR #358

**Comment by erimerturk** [comment]
@krzyk please close if it is acceptable for u, thank u

**Comment by krzyk** [comment]
@erimerturk thanks

**Comment by ypshenychka** [comment]
@davvd Quality is acceptable because of above remark.

**Comment by davvd** [comment]
> @davvd Quality is acceptable because of above remark.

@ypshenychka thanks for the review, we'll try better next time

**Comment by davvd** [comment]
@erimerturk just added 10 mins to @ypshenychka (for QA), payment ID is `60765586`; thank you, added **30 mins** to your acc, payment num is `AP-4V060928V60132405`, 326 hours and 42 mins spent in total to complete; added +30 to your rating, now it is equal to [+150](http://www.netbout.com/b/35280?open=rating)
