### ISSUE TITLE
RqMultipart.java:404-424: New ctor should be created...

### ISSUE THREAD

**Issue by davvd** [yegor256/takes#323]
Puzzle `252-d7f3c72e` in `src/main/java/org/takes/rq/RqMultipart.java:404-424` has to be resolved: New ctor should be created and expect instances of Request as dispositions. Dispositions should be multipart request body holder. New ctor should call {@code RqMultipart.Base}. {@code Fake.fakebody} method should be refactored and Fake(final Request req, final String... dispositions) ctor should call new constructor using dispositions like {@code this( req, new RqWithHeader( req, // @checkstyle LineLength (1 line) new RqLive(req.head().iterator().next() + "\r\n" + "Content-Disposition", "form-data; name=\"address\"") ), new RqWithHeader( req, // @checkstyle LineLength (1 line) new RqLive(req.head().iterator().next() + "\r\n" + "Content-Disposition", "form-data; name=\"file\"") ) ); }... The puzzle was created by erim erturk on 27-May-2015.

If you have any technical questions, don't ask me, submit new tickets instead

**Comment by davvd** [comment]
@erimerturk it's yours now, please proceed keeping in mind [our principles](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html). Feel free to ask any technical questions right here in the ticket

The budget here is **30 mins**, which is exactly how much time will be paid for, when the task is [completed](http://www.xdsd.org/2014/04/15/definition-of-done.html)

**Comment by davvd** [comment]
@yegor256 since the ticket has no milestone I set it to 1.0

**Comment by erimerturk** [comment]
@yegor256 i am planing to remove <code> public Fake(final Request req, final String... dispositions) </code> ctor. What do you think ? We will have <code> public Fake(final Request req, final Request... dispositions) </code> ctor and it will be good enough, i think we should just have this version.

**Comment by yegor256** [comment]
@erimerturk well, what happened to the idea of giving users the ability to pass Strings too? I think it was a good one. Why not?

**Comment by erimerturk** [comment]
@yegor256 we can keep this ability but i thought that input type restriction is better than string. I mean we are using request as input type in everywhere so i thought we might remove string version.  just a suggestion

**Comment by yegor256** [comment]
@erimerturk yes, I think you're right, let's do it

**Comment by erimerturk** [comment]
@yegor256 thank you :)

**Comment by erimerturk** [comment]
@davvd @yegor256 can you check and close it please

**Comment by davvd** [comment]
@yegor256 It is closed now

**Comment by davvd** [comment]
@elenavolokhova please, let us know what do you think about this ticket, according to our [QA rules](http://www.teamed.io/qa.html)

**Comment by elenavolokhova** [comment]
@erimerturk 
 According to our [quality rules](http://www.teamed.io/qa.html):
 > Some of ticket messages must mention all pull requests where the problem was actually fixed.
 
 There is no link to related PR in comments. Please fix this issue and follow this rule in your tickets in the future.

**Comment by erimerturk** [comment]
@elenavolokhova what do you mean ? could you explain it please ?

**Comment by elenavolokhova** [comment]
@erimerturk Sure! You should add a comment to issue ticket and put the PR number to it. See [example](https://github.com/teamed/xockets-hadoop-transport/issues/674). It contains: 
>pinaf commented 2 days ago
@alex-palevsky see PR #681

**Comment by erimerturk** [comment]
@elenavolokhova i see, thank you so much :) ! please see PR #328

**Comment by elenavolokhova** [comment]
@erimerturk Thank you :)

**Comment by elenavolokhova** [comment]
@davvd Quality is acceptable here.

**Comment by erimerturk** [comment]
@elenavolokhova i have an question for you. You said <b>Quality is acceptable</b> . Can you give me suggestions how can i improve quality ? For example what should i do for quality is good or better ? You don't have to give answer but if you give answer it will be good for future works. thank you

**Comment by elenavolokhova** [comment]
@erimerturk 
First of all you should review all our [quality rules](http://www.teamed.io/qa.html). If you see that anyone doesn't follow any rule in your ticket, ask him to fix it before the ticket is closed and goes to QA review. Be persistent if someone doesn't fix the issue. 
Quality is good if ticket is perfect. In this case performer gets a bonus :)
If any issues are still present I can ask for fix or for acknowledgement that performer is aware of the rule and will try to follow it in the future. In this case quality is acceptable. Performer gets payment but don't get a bonus for quality.
I hope it will help you :)

**Comment by erimerturk** [comment]
@elenavolokhova i see, thank you so much for your comments, i will take care next time.

**Comment by davvd** [comment]
> @davvd Quality is acceptable here.

@elenavolokhova thank you, let's try to make it "good" next time

**Comment by davvd** [comment]
@erimerturk 10 mins was added to the account of @elenavolokhova (for QA review), in transaction 58670446; Thank you, I have added **30 mins** to your account in payment/transaction "`AP-38168822VC646592R`", time consumed: 141 hours and 3 mins; +30 added to your rating, current score is: [+120](http://www.netbout.com/b/35280?open=rating)
