### ISSUE TITLE
RqMultipart.Base incorrect handles non-printable ASCII characters

### ISSUE THREAD

**Issue by dmzaytsev** [yegor256/takes#331]
RqMultipart.Base incorrect handles non-printable ASCII characters
to reproduce it just make a small changes in `RqMultipartTest.handlesRequestInTime()`
https://github.com/yegor256/takes/blob/master/src/test/java/org/takes/rq/RqMultipartTest.java#L357

change 
```
for (int ind = 0; ind < length; ++ind) {
            bwr.write("X");
}
```
to
```
Random rnd = new Random();
for (int ind = 0; ind < length; ++ind) {
    bwr.write(String.format("%c", rnd.nextInt(128)));         
}
```

`bwr.write(String.format("%c", rnd.nextInt(108)+20));` will work fine.
so problem in the non-printable characters from 0 to 19

**Comment by davvd** [comment]
@dmzaytsev I will ask someone to take care of this task soon

**Comment by davvd** [comment]
@dmzaytsev since the ticket has no milestone I set it to 1.0

**Comment by davvd** [comment]
@dmzaytsev many thanks for the bug report, I added 15 mins to your acc, transaction `58631336`

**Comment by davvd** [comment]
@lautarobock this task is yours, please help (see our key [principles of work](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html)). If you have any technical questions, don't hesitate to ask right here... The budget here is **30 mins**, which is exactly how much time will be paid for, when the task is [completed](http://www.xdsd.org/2014/04/15/definition-of-done.html)

**Comment by dmzaytsev** [comment]
@lautarobock It would better to create a new test for this issue. Also please add a hash calculation for input and output data and compare them.

**Comment by dmzaytsev** [comment]
@lautarobock any progress here ?

**Comment by yegor256** [comment]
@dmzaytsev let me fix it myself, will be faster. assign it to me pls

**Comment by dmzaytsev** [comment]
@davvd assign this ticket to @yegor256 please

**Comment by yegor256** [comment]
@dmzaytsev maybe you can fix it? I have no idea why it's happening. I only managed to reproduce it in a test, just like you suggested:

**Comment by dmzaytsev** [comment]
@yegor256 ok, I'll try, assign it to me pls

**Comment by yegor256** [comment]
@davvd assign @dmzaytsev to this task pls

**Comment by davvd** [comment]
> @davvd assign @dmzaytsev to this task pls

@yegor256 of course! @dmzaytsev it's your ticket now, please go ahead

**Comment by yegor256** [comment]
@dmzaytsev any luck?

**Comment by dmzaytsev** [comment]
@yegor256 I found exactly where the bug, but it was too late. today I will
fix it.

**Comment by dmzaytsev** [comment]
@davvd please see PR #335 
@yegor256 fixed

**Comment by yegor256** [comment]
@rultor release, tag is `0.20.1`

**Comment by yegor256** [comment]
@rultor release, tag is `0.20.1`

**Comment by dmzaytsev** [comment]
@davvd  PR #335 fixed the issue, I'm closing the ticket

**Comment by yegor256** [comment]
@dmzaytsev thanks!

**Comment by davvd** [comment]
@elenavolokhova please, review this task for compliance with our [quality rules](http://www.teamed.io/qa.html)

**Comment by elenavolokhova** [comment]
@davvd Quality is good here!

**Comment by davvd** [comment]
> @davvd Quality is good here!

@elenavolokhova thanks a lot :)

**Comment by davvd** [comment]
@dmzaytsev just added 10 mins to @elenavolokhova (for QA), payment ID is `59023368`

Thanks for your contribution, **1 hour** was added to your account, payment ID is `59023379`, 14 hours and 15 mins spent total

the bonus for fast delivery (m=855)

+60 added to your rating, at the moment it is: [+2480](http://www.netbout.com/b/35166?open=rating)
