### ISSUE TITLE
RsPrettyXML is losing <!DOCTYPE html>

### ISSUE THREAD

**Issue by erimerturk** [yegor256/takes#339]
RsPrettyXML must keep <!DOCTYPE html> on result.

<b>given input</b>

```
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en">
   <head>
    ...
   </head>
   <body>
    ...
   </body>
</html>
```
<b>expected output</b>

```
<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml" lang="en">
   
   <head> 
     ...
      
   </head>
   
   <body>
     ...
     
   </body>
   
</html>
```

<b>current output</b>

```
<html xmlns="http://www.w3.org/1999/xhtml" lang="en">
   
   <head>
      ...
   </head>
   
   <body>
    ...
   </body>
   
</html>
```

**Comment by yegor256** [comment]
@erimerturk thanks for the bug. I think we can reproduce this bug with smaller XML/HTML page, right?

**Comment by erimerturk** [comment]
@yegor256 of course  this one is enough
``` 
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en">
   <head>
     ...
   </head>
   <body>
    ...
   </body>
</html>
```

**Comment by yegor256** [comment]
@erimerturk would be convenient if you update the description of the ticket, to make is simpler. Now it's too complex and makes the problem less obvious. I need to read too much, so to speak

**Comment by erimerturk** [comment]
@yegor256  description updated

**Comment by davvd** [comment]
@erimerturk I will find a developer for the task soon...

**Comment by davvd** [comment]
@erimerturk since there is no milestone yet I set it to "1.0"

**Comment by davvd** [comment]
@mbarbieri please pick this up, and keep in mind [these instructions](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html). Any technical questions - ask right here

The budget of this issue is **30 mins**, which is exactly how much will be paid when the task is *done* (see [this](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html) for explanation)

**Comment by davvd** [comment]
@erimerturk thanks for the report, I topped your acc for 15 mins, payment ID `AP-7Y444500LW5068013`

**Comment by mbarbieri** [comment]
@erimerturk @yegor256 it seems that Java transformer is not supporting it directly (see [here](https://stackoverflow.com/questions/10748531/how-to-create-an-empty-doctype-using-w3c-dom-in-java)), but based on [this](http://www.w3.org/html/wg/drafts/html/master/syntax.html#doctype-legacy-string) we can have:
```xml
<!DOCTYPE html SYSTEM "about:legacy-compat" >
<html xmlns="http://www.w3.org/1999/xhtml" lang="en">
   <head>
     ...
   </head>
   <body>
    ...
   </body>
</html>
```
is it fine?

**Comment by erimerturk** [comment]
@mbarbieri sorry what is the question, i couldn't understand. And another thing  i can't use <code> "about:legacy-compat" </code> because saxon 9.1 is not accepting it.

**Comment by mbarbieri** [comment]
@davvd PR #348 is ready.

**Comment by davvd** [comment]
@mbarbieri the ticket is with you for 15 days already. If it is not finished in the next 48 hours, it will be re-assigned to someone else, see [No Obligations](http://www.xdsd.org/2014/04/13/no-obligations-principle.html) principle, [this article](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html) should help if you're stuck

-30 to your rating, your total score is [-7](http://www.netbout.com/b/35357?open=rating)

**Comment by mbarbieri** [comment]
@davvd I'm sorry I'm not able to complete this... can you please reassign it to someone else?

**Comment by davvd** [comment]
> @davvd I'm sorry I'm not able to complete this... can you please reassign it to someone else?

@mbarbieri 30 points was deducted from your rating

**Comment by davvd** [comment]
> @davvd I'm sorry I'm not able to complete this... can you please reassign it to someone else?

@mbarbieri right, I will find someone else, no problem

**Comment by davvd** [comment]
@suseika please proceed, it's yours

**Comment by Suseika** [comment]
@davvd Please assign someone else.

**Comment by davvd** [comment]
> @davvd Please assign someone else.

@suseika 30 points deducted from your rating

**Comment by davvd** [comment]
> @davvd Please assign someone else.

@suseika got it, someone else will be assigned soon

**Comment by davvd** [comment]
@bilalyasar this task is yours, please help (see our key [principles of work](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html)). If you have any technical questions, don't hesitate to ask right here... The budget of this task is **30 mins**. This is exactly how much time will be compensated, when the task is completed. Read about our [Definition of Done](http://www.xdsd.org/2014/04/15/definition-of-done.html)

**Comment by davvd** [comment]
@bilalyasar check this ["no obligations principle"](http://www.xdsd.org/2014/04/13/no-obligations-principle.html).. This task is on your name for at least 15 days. If you can't close it within the next 48 hours I will have to assign someone else to it. [This article](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html) should help if you're stuck; added -30 to your rating, now it is equal to [-120](http://www.netbout.com/b/35406?open=rating)

**Comment by davvd** [comment]
@bilalyasar you've been working with this task for too long. I'm sorry, but I'll assign someone else. Please stop working with it. See our [no obligations](http://www.xdsd.org/2014/04/13/no-obligations-principle.html) principle

added -60 to your rating, now it is equal to [-180](http://www.netbout.com/b/35406?open=rating)

**Comment by davvd** [comment]
@dimonn12 this task is yours, please help (see our key [principles of work](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html)). If you have any technical questions, don't hesitate to ask right here... Task's budget is **30 mins** (see [this](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html) for explanation)

**Comment by dimonn12** [comment]
@davvd see https://github.com/yegor256/takes/pull/381

**Comment by davvd** [comment]
> @davvd see https://github.com/yegor256/takes/pull/381 

@dimonn12 OK will take a look, thanks

**Comment by davvd** [comment]
@dimonn12 you're holding this ticket for 15 days already. If it is not finished (and closed) in the next 48 hours, it will be re-assigned to someone else, see [No Obligations](http://www.xdsd.org/2014/04/13/no-obligations-principle.html) principle ([this article](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html) should help if you're stuck). -30 to your rating, your total score is [-30](http://www.netbout.com/b/35589?open=rating)

**Comment by davvd** [comment]
@dimonn12 the task is overdue, and I have to re-assign it to someone else. Please, stop working with it immediately. In general, we're against overdue tasks, check [this page](http://www.xdsd.org/2014/04/13/no-obligations-principle.html)

-60 to your rating, your total score is [-120](http://www.netbout.com/b/35589?open=rating)

**Comment by davvd** [comment]
@bdragan the task is for you now, follow [these guidelines](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html). Don't hesitate to ask any technical questions right here... This task's budget is **30 mins**. This is exactly how much will be paid when the problem explained above is solved. See [this](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html) for more information

**Comment by bdragan** [comment]
@davvd This issue has already been fixed in the PR #381. Please, close it.

**Comment by davvd** [comment]
> @davvd This issue has already been fixed in the PR #381. Please, close it.

@bdragan you should ask ticket author (@erimerturk) to close it, see http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html

**Comment by bdragan** [comment]
@davvd Thanks!

@erimerturk Please, close this issue because it has already been fixed in the PR #381.

**Comment by yegor256** [comment]
@bdragan if the author doesn't close in the next few days, message me, I'll close myself

**Comment by erimerturk** [comment]
@bdragan thank you

**Comment by davvd** [comment]
> @davvd Thanks!
> 
> @erimerturk Please, close this issue because it has already been fixed in the PR #381.

@bdragan np :)

**Comment by davvd** [comment]
@elenavolokhova please, review this task for compliance with our [quality rules](http://www.teamed.io/qa.html)

**Comment by elenavolokhova** [comment]
@davvd Looks good!

**Comment by davvd** [comment]
> @davvd Looks good!

@elenavolokhova thanks a lot

**Comment by davvd** [comment]
@bdragan just added 10 mins to @elenavolokhova (for QA), payment ID is `68513381`

Thanks a lot, I just topped your account for **30 mins**, transaction ID `68513386`, total time was 256 hours and 54 mins

+30 added to your rating, current score is: [+173](http://www.netbout.com/b/35709?open=rating)
