### ISSUE TITLE
PsGoogle creates incorrect oauth link

### ISSUE THREAD

**Issue by yegor256** [yegor256/takes#341]
Line 165:

```
new Href(this.gauth).path("o/oauth2/token").toString()
```

must be:

```
new Href(this.gauth).path("o").path("oauth2").path("token").toString()
```

**Comment by davvd** [comment]
@yegor256 I will find a developer for the task soon...

**Comment by davvd** [comment]
@yegor256 I set milestone here to `1.0`, let me know if it is wrong

**Comment by davvd** [comment]
@adko-pl the task is for you now, follow [these guidelines](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html). Don't hesitate to ask any technical questions right here... The budget of this task is **30 mins**. This is exactly how much time will be compensated, when the task is completed. Read about our [Definition of Done](http://www.xdsd.org/2014/04/15/definition-of-done.html)

**Comment by davvd** [comment]
@yegor256 many thanks, **15 mins** added to your acc for reporting this bug, pmt ID `000-ffbaa473`

**Comment by dmzaytsev** [comment]
@yegor256 assign this to me please
I would close the linked issue in Netbout

**Comment by yegor256** [comment]
@davvd assign @dmzaytsev pls to this issue

**Comment by davvd** [comment]
> @davvd assign @dmzaytsev pls to this issue

@yegor256 done, @dmzaytsev is a new assignment at the task, please go on. whoever worked with this task before, please stop right now

**Comment by dmzaytsev** [comment]
@yegor256 fixed in #378 
close the ticket please

**Comment by yegor256** [comment]
@dmzaytsev thanks!

**Comment by dmzaytsev** [comment]
@yegor256  release please

**Comment by yegor256** [comment]
@rultor release, tag is `0.23.3`

**Comment by davvd** [comment]
@ypshenychka please, review this task for compliance with our [quality rules](http://www.teamed.io/qa.html)

**Comment by ypshenychka** [comment]
@davvd Quality is good here.

**Comment by davvd** [comment]
> @davvd Quality is good here.

@ypshenychka thanks a lot

**Comment by davvd** [comment]
@dmzaytsev I added 10 mins to @ypshenychka (for QA review) in transaction 64002112; Thanks so much! Your account was topped up for **1 hour** (transaction ID is `64002119`, the task took 19 hours and 48 mins); m=1188, that's why a bonus here for fast delivery; +60 to your rating, your total score is [+1854](http://www.netbout.com/b/35166?open=rating)
