### ISSUE TITLE
TkCORS.java:82-87: RqHeaders.Smart should have a `single(string,...

### ISSUE THREAD

**Issue by davvd** [yegor256/takes#342]
Puzzle `258-12a59dfa` in `src/main/java/org/takes/tk/TkCORS.java:82-87` has to be resolved: RqHeaders.Smart should have a `single(string, string)` method. That method should be similar to the method found in `RqHref.Smart`). The first parameter is the key that you are looking for and the second one is the default value if it was not found. Don't forget to remove the checkstyle comment.... The puzzle was created by Endrigo Antonini on 6-Jun-2015.

If you have any technical questions, don't ask me, submit new tickets instead

**Comment by davvd** [comment]
@yegor256 I set milestone here to `1.0`, let me know if it is wrong

**Comment by davvd** [comment]
@erimerturk the task is yours, please go ahead

**Comment by erimerturk** [comment]
@antonini please see detail on PR #343

**Comment by antonini** [comment]
@erimerturk I made a comment on your PR.

**Comment by erimerturk** [comment]
@antonini issue description saying nothing about <code>try catch</code> block. next time please note it at PDD. thank you

**Comment by antonini** [comment]
@erimerturk I didn't write about `try catch` block because it was there just because of the method that was been called (that it could throw an exception). As the new method doesn't throw an exception if not found, the `try catch` block is not needed any more.

**Comment by erimerturk** [comment]
@antonini please check and close if it is acceptable for you, thank you

**Comment by antonini** [comment]
@erimerturk That's ok.

**Comment by antonini** [comment]
@davvd The issue is ok. Can you close it?

**Comment by davvd** [comment]
@yegor256 Closing, thanks all

**Comment by davvd** [comment]
@elenavolokhova please, let us know what do you think about this ticket, according to our [QA rules](http://www.teamed.io/qa.html)

**Comment by elenavolokhova** [comment]
@davvd Looks good!

**Comment by davvd** [comment]
> @davvd Looks good!

@elenavolokhova thanks!

**Comment by davvd** [comment]
@erimerturk I added 10 mins to @elenavolokhova (for QA review) in transaction 59534716

Much appreciated! **30 mins** was added to your account, payment ID `AP-2DP99794EG0584313`, time spent is 144 hours and 14 mins

+30 added to your rating, current score is: [+150](http://www.netbout.com/b/35280?open=rating)
