### ISSUE TITLE
travis-ci build failling for jdk6

### ISSUE THREAD

**Issue by erimerturk** [yegor256/takes#345]
You can see full details from [here] (https://travis-ci.org/yegor256/takes/jobs/66991273)

exception detail

<code>
[ERROR] pool-1-thread-41 com.jcabi.aspects.aj.MethodValidator: JSR-303 validator thrown during initialization: java.lang.UnsupportedClassVersionError: javax/el/ExpressionFactory : Unsupported major.minor version 51.0
</code>

**Comment by yegor256** [comment]
@erimerturk it's not a failure, but just a log message. The build failed for another reason.
