### ISSUE TITLE
RSJson must close the JsonWriter to flush it's content into the ByteArrayOutputStream

### ISSUE THREAD

**Issue by GilraenBurland** [yegor256/takes#346]
Hi there,

I am currently writing a small web app based on the Takes Framework.
I want to return a JSON response and I noticed that the content of a RsJSON.Source is not correctly written to the ByteArrayOutputStream.

After some testing I found the possible solution:

```
private static byte[] print(final RsJSON.Source src) throws IOException {
        final ByteArrayOutputStream baos = new ByteArrayOutputStream();
        Json.createWriter(baos).write(src.toJSON());
        return baos.toByteArray();
}
```

must include a call to the JsonWriter.close() to flush the write to the underlying BAOS.

```
private static byte[] print(final RsJSON.Source src) throws IOException {
        final ByteArrayOutputStream baos = new ByteArrayOutputStream();
        JsonWriter writer = Json.createWriter(baos)
        writer.write(src.toJSON());
        writer.close()
        return baos.toByteArray();
}
```

**Comment by yegor256** [comment]
@GilraenBurland thanks for reporting, it's definitely a bug, we'll try to fix soon

**Comment by davvd** [comment]
@gilraenburland this task will get someone's attention soon

**Comment by davvd** [comment]
@gilraenburland I set the milestone to 1.0 since there is nothing set yet

**Comment by davvd** [comment]
@dmzaytsev it's yours, budget is 30 mins, please go ahead

**Comment by dmzaytsev** [comment]
@davvd please see PR #347

**Comment by davvd** [comment]
> @davvd please see PR #347 

@dmzaytsev I will take a look, thanks

**Comment by yegor256** [comment]
@rultor release, tag is `0.20.3`

**Comment by dmzaytsev** [comment]
@GilraenBurland the issue resolved in PR #347 please close the ticket

**Comment by davvd** [comment]
@ypshenychka please, review this task for compliance with our [quality rules](http://www.teamed.io/qa.html)

**Comment by ypshenychka** [comment]
@davvd Quality is good.

**Comment by davvd** [comment]
> @davvd Quality is good.

@ypshenychka thanks a lot ;)

**Comment by davvd** [comment]
@dmzaytsev 10 mins was added to the account of @ypshenychka (for QA review), in transaction 59536664. **1 hour** was added to your account, many thanks for your contribution (payment 59536667)! The task took 17 hours and 18 mins.. the bonus for fast delivery (m=1038). +60 added to your rating, at the moment it is: [+2840](http://www.netbout.com/b/35166?open=rating)
