### ISSUE TITLE
PsBasic misses Default Entry implementation

### ISSUE THREAD

**Issue by ekondrashev** [yegor256/takes#349]
Recently it was introduced Basic Authentication `Pass` implementations with #221 called `PsBasic`. As part of implementation `PsBasic.Entry` interface was introduced with `PsBasic.Fake` and `PsBasic.Empty` implementations.

I think `PsBasic` misses the `Default` implementation in order to be able to use this `Pass` implementation having real username/password pairs.

**Comment by davvd** [comment]
@ekondrashev I am aware of the task, give me some time to find a developer...

**Comment by davvd** [comment]
@ekondrashev I set the milestone to 1.0 since there is nothing set yet

**Comment by davvd** [comment]
@lautarobock it's yours,please go ahead

**Comment by davvd** [comment]
@ekondrashev thank you for reporting this, I added 15 mins to your acc, transaction `59519453`

**Comment by lautarobock** [comment]
PR#357 is ready for review

**Comment by davvd** [comment]
@lautarobock the task is your hands for the last 15 days.. keep in mind that if it's not closed in the next 48 hours, it will be re-assigned to someone else, see [No Obligations](http://www.xdsd.org/2014/04/13/no-obligations-principle.html) principle. [This article](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html) should help if you're stuck

-30 to your rating, your total score is [-180](http://www.netbout.com/b/35344?open=rating)

**Comment by lautarobock** [comment]
@davvd I'm waiting for review.

**Comment by davvd** [comment]
@lautarobock it takes too long. Usually, we expect any task to be finished in less than a week. I'll assign someone else. Please stop working with it right now. See our [no obligations](http://www.xdsd.org/2014/04/13/no-obligations-principle.html) principle... added -60 to your rating, now it is equal to [-240](http://www.netbout.com/b/35344?open=rating)

**Comment by davvd** [comment]
@suseika please go ahead with this task, it's yours

**Comment by Suseika** [comment]
@davvd I need more time with this task

**Comment by davvd** [comment]
> @davvd I need more time with this task

@suseika sure, take your time

**Comment by Suseika** [comment]
@ekondrashev Closed with #365, please see.

**Comment by ekondrashev** [comment]
@Suseika thx!

**Comment by davvd** [comment]
@elenavolokhova review this ticket please, for compliance with our [quality rules](http://www.teamed.io/qa.html)

**Comment by davvd** [comment]
@rultor rultor closed it by mistake, @ekondrashev please take a look

**Comment by ekondrashev** [comment]
@davvd it is ok, I've already took a look, thx

**Comment by elenavolokhova** [comment]
@davvd Looks good!

**Comment by davvd** [comment]
> @davvd Looks good!

@elenavolokhova thanks for the review and a good remark

**Comment by davvd** [comment]
@suseika 10 mins was added to the account of @elenavolokhova (for QA review), in transaction 62123503. Thanks so much! Your account was topped up for **30 mins** (transaction ID is `AP-7H760314TP408643K`, the task took 357 hours and 42 mins). +30 added to your rating, current score is: [+503](http://www.netbout.com/b/35381?open=rating)
