### ISSUE TITLE
PsAll is missing

### ISSUE THREAD

**Issue by ekondrashev** [yegor256/takes#350]
Takes misses `Pass` implementation that will require each provided `Pass` to success in order to the target `Pass` to success. 
The concept is similar to python [all](https://docs.python.org/2/library/functions.html#all) builtin.

The contract could be like this:
```java
public PsAll(final Iterable<Pass> list, final int index)
```

The `index` parameter will indicate which `Identity` to return once all suceeded.

**Comment by yegor256** [comment]
@ekondrashev I can't imagine where such a class may be useful. Can you give a real life example?

**Comment by ekondrashev** [comment]
@yegor256 Sure, for example in scope of [netbout#685](https://github.com/yegor256/netbout/issues/685) there is an need in so called `PsTwice` which is actually the corner case of `PsAll`.
Here is the quote:
>PsTwice which use two a Pass instances. Inside PsTwice.enter() we have to check the first Pass and if it passed succesfully then continue with second Pass and return Identity from it.

**Comment by yegor256** [comment]
@ekondrashev hm.. make sense, thanks

**Comment by davvd** [comment]
@ekondrashev I am aware of the task, give me some time to find a developer...

**Comment by davvd** [comment]
@ekondrashev I set milestone here to `1.0`, let me know if it is wrong

**Comment by davvd** [comment]
@ekondrashev thanks a lot for reporting, **15 mins** added to your acc, pmt ID `59564195`

**Comment by davvd** [comment]
@lautarobock please proceed, it's yours

**Comment by lautarobock** [comment]
PR#350 is ready for review

**Comment by davvd** [comment]
@lautarobock you're holding this ticket for 15 days already. If it is not finished (and closed) in the next 48 hours, it will be re-assigned to someone else, see [No Obligations](http://www.xdsd.org/2014/04/13/no-obligations-principle.html) principle ([this article](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html) should help if you're stuck). -30 added to your rating, current score is: [-270](http://www.netbout.com/b/35344?open=rating)

**Comment by davvd** [comment]
@suseika please proceed,it's yours

**Comment by Suseika** [comment]
@davvd I need more time.

**Comment by davvd** [comment]
> @davvd I need more time.

@suseika of course, take your time

**Comment by davvd** [comment]
@rultor @ekondrashev please take a look, rultor closed it automatically

**Comment by ekondrashev** [comment]
@Suseika thank you!

**Comment by Suseika** [comment]
@davvd Closed with #366

**Comment by davvd** [comment]
@elenavolokhova please, review this ticket for compliance with our [QA rules](http://www.teamed.io/qa.html)

**Comment by elenavolokhova** [comment]
@davvd Looks good!

**Comment by davvd** [comment]
> @davvd Looks good!

@elenavolokhova thanks for the review and a good remark

**Comment by davvd** [comment]
@suseika I added 10 mins to @elenavolokhova (for QA review) in transaction 61671588... thank you, added **30 mins** to your acc, payment num is `AP-1JC27519LF7076547`, 208 hours and 34 mins spent in total to complete... added +30 to your rating, now it is equal to [+413](http://www.netbout.com/b/35381?open=rating)
