### ISSUE TITLE
RsXSLT not working correctly

### ISSUE THREAD

**Issue by GilraenBurland** [yegor256/takes#351]
Using the RsXSLT is not working correctly if the xls file path is given as a plain string.

Example:

```
new RsPrint(
    new RsXSLT(
        new RsXembly(
            new XeStylesheet("/xsl/config.xsl"),
            new XeAppend("test", "test")
        )
    )
).printBody(System.out);
```

This results in:

`Caused by: java.io.FileNotFoundException: /xsl/config.xsl (No such file or directory)`

The cause seems to be somewhere in the input source. 
It references the xls file as '/xsl/config.xsl' and not with the complete path which results in following path:

`file:///xsl/config.xsl`

Using the XeStylesheet like the following results in expected behaviour:

`new XeStylesheet(getClass().getResource("/xsl/config.xsl")`

**Comment by yegor256** [comment]
@GilraenBurland this is by design. It's not a file path, but a resource name, which is at the same must be a web page available through HTTP. I will add this text now to the Javadoc

**Comment by yegor256** [comment]
@GilraenBurland see  e9954c3

**Comment by GilraenBurland** [comment]
Yeah that's what I expected and it is working when I am just using RsXembly because the browser loads the xls file as expected.

But RsXSLT should load it from classpath without me defining `getClass().getResource()` right?
That's not working as it seems that the RsXSLT.InClasspath URIResolver is not being called.

**Comment by yegor256** [comment]
@GilraenBurland I think I know what is the problem. You should use Saxon instead of default XSLT processor. See how it's done in, for example, rultor: https://github.com/yegor256/rultor/blob/1.55/pom.xml#L308-L327

**Comment by GilraenBurland** [comment]
Hi Yegor,

I placed the dependencies in my pom.xml but it seems it is not grabbing them at runtime. Do I have to do something more?

**Comment by yegor256** [comment]
@GilraenBurland not sure.. you should investigate what XSL transformer is used in runtime.  check this: http://stackoverflow.com/questions/11314604/how-to-set-saxon-as-the-xslt-processor-in-java

**Comment by GilraenBurland** [comment]
Thanks for the help! Now it is working :)

**Comment by yegor256** [comment]
@GilraenBurland you're welcome :) thanks for using the framework
