### ISSUE TITLE
Add Opt constructor that checks for null

### ISSUE THREAD

**Issue by mbarbieri** [yegor256/takes#352]
While working with 3rd party libraries I think it can be useful to have a constructor in `Opt` that checks for null and create a proper `Opt.Empy` or `Opt.Single` accordingly.

Similar to what `Optional.ofNullable` is doing in Java 8.
So that we don't have to do nullchecks manually like:

``` java
if(x == null) {
  return new Opt.Empty();
}
return new Opt.Single(x);
```

**Comment by yegor256** [comment]
@mbarbieri where exactly will this help us? Can you show an example where this code exists?

**Comment by essobedo** [comment]
@yegor256 Here you have an example https://github.com/yegor256/takes/blob/master/src/main/java/org/takes/facets/auth/PsBasic.java#L286

**Comment by yegor256** [comment]
@essobedo I still don't understand what exactly is proposed in this ticket... also, keep this in mind: http://www.yegor256.com/2016/01/26/defensive-programming.html In other words, I'm against checking for null

**Comment by essobedo** [comment]
@yegor256 as far as I understand from the description, he would like to add a new implementation of Opt that would do something like that:
```
   final class Nullable<T> implements Opt<T> {
        
        private final transient Opt<T> opt;
        
        public Nullable(final T orgn) {
            if (orgn == null) {
                this.opt = new Empty<T>();
            } else {
                this.opt = new Single<T>(orgn);
            }
        }
        @Override
        public T get() {
            return opt.get();
        }
        @Override
        public boolean has() {
            return opt.has();
        }
    }
```
But if you are against checking for null it is clearly not applicable

**Comment by a--v--k** [comment]
@yegor256: what do you think about factory methods? Guava/Java8 libraries use it to hide internal details of Optional implementation.

**Comment by yegor256** [comment]
@a--v--k I'm against factory methods in general. Good old `new` is all we need in OOP, I believe

**Comment by yegor256** [comment]
@0crat in

**Comment by 0crat** [comment]
> @0crat in ([here](https://github.com/yegor256/takes/issues/352#issuecomment-322125052))

@yegor256 Thanks for your contribution, @mbarbieri[/z](https://www.0crat.com/u/mbarbieri)! If you would be a member of [the project](https://www.0crat.com/p/C3FFK3YAY), you would now earn +15 reputation points, as explained in [§29](http://www.zerocracy.com/policy.html#29). You can join and apply to it, see [§2](http://www.zerocracy.com/policy.html#2).

**Comment by paulodamaso** [comment]
@0crat out

**Comment by 0crat** [comment]
> @0crat out ([here](https://github.com/yegor256/takes/issues/352#issuecomment-442041754))

@paulodamaso Job `gh:yegor256/takes#352` is not assigned, can't get performer

**Comment by 0crat** [comment]
> @0crat out ([here](https://github.com/yegor256/takes/issues/352#issuecomment-442041754))

@paulodamaso The job [#352](https://github.com/yegor256/takes/issues/352) is now out of scope

**Comment by 0crat** [comment]
Job `gh:yegor256/takes#352` is not assigned, can't get performer

**Comment by 0crat** [comment]
This job is not in scope

**Comment by g4s8** [comment]
@0crat status

**Comment by 0crat** [comment]
> @0crat status ([here](https://github.com/yegor256/takes/issues/352#issuecomment-442136033))

@g4s8 This is what I know about this job in [C3FFK3YAY](https://www.0crat.com/p/C3FFK3YAY), as in [§32](http://www.zerocracy.com/policy.html#32):

  * The job [#352](https://github.com/yegor256/takes/issues/352) is not in scope
  * Job [footprint](https://www.0crat.com/footprint/C3FFK3YAY?q=%7Bjob%3A%27gh%3Ayegor256%2Ftakes%23352%27%2Ctype%3A%7B%24not%3A%2F%5ENotify%2F%7D%7D) (restricted area)
