### ISSUE TITLE
RsReturn should validate the location

### ISSUE THREAD

**Issue by dmzaytsev** [yegor256/takes#353]
right now RsReturn accepts any string as the `location` parameter
I believe `location` value should be validated for a valid url and rejected any other values

**Comment by davvd** [comment]
@dmzaytsev we will find someone to do this task, soon

**Comment by davvd** [comment]
@dmzaytsev there is no milestone yet, so I set it to `1.0`

**Comment by davvd** [comment]
@dmzaytsev thanks a lot for reporting, **15 mins** added to your acc, pmt ID `59909343`

**Comment by davvd** [comment]
@erimerturk please go ahead with this task, it's yours

**Comment by erimerturk** [comment]
@davvd  i have an preterm baby yesterday, please reassign my issue someone else, thank you

**Comment by davvd** [comment]
> @davvd  i have an preterm baby yesterday, please reassign my issue someone else, thank you

@erimerturk -30 points to your rating

**Comment by davvd** [comment]
> @davvd  i have an preterm baby yesterday, please reassign my issue someone else, thank you

@erimerturk OK, I will try to assign someone else

**Comment by davvd** [comment]
@adko-pl this ticket is yours now, please proceed, and keep in mind [this](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html). Any technical questions you should ask right here. The cost of this task is **30 mins** (this is exactly how much will be paid, not less not more), when the task is [done](http://www.xdsd.org/2014/04/15/definition-of-done.html)

**Comment by yegor256** [comment]
@0crat in

**Comment by 0crat** [comment]
> @0crat in ([here](https://github.com/yegor256/takes/issues/353#issuecomment-322125076))

@yegor256 Job `gh:yegor256/takes#353` is in scope.

**Comment by 0crat** [comment]
Job `gh:yegor256/takes#353` assigned to @caarlos0, please go ahead ([policy](http://datum.zerocracy.com/pages/policy.html)).

**Comment by 0crat** [comment]
@caarlos0 this job was assigned to you 8 days ago.
It will be taken away from you after 10 days from start (this is our policy).

**Comment by 0crat** [comment]
Oops! Job `gh:yegor256/takes#353` is not assigned to anyone.

**Comment by 0crat** [comment]
Oops! Job `gh:yegor256/takes#353` is not assigned to anyone.

**Comment by 0crat** [comment]
Oops! Job `gh:yegor256/takes#353` is not assigned to anyone.

**Comment by 0crat** [comment]
Job `gh:yegor256/takes#353` assigned to [@t-izbassar](http://www.0crat.com/u/t-izbassar}). The budget is [fixed](http://datum.zerocracy.com/pages/policy.html#4) and it is 30 minutes. Please, read [§4](http://datum.zerocracy.com/pages/policy.html#4), [§8](http://datum.zerocracy.com/pages/policy.html#8), and [§9](http://datum.zerocracy.com/pages/policy.html#9). If the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html).

**Comment by 0crat** [comment]
> @0crat waiting ([here](https://github.com/yegor256/takes/issues/353#issuecomment-357306867))

@t-izbassar The impediment was registered successfully

**Comment by t-izbassar** [comment]
@yegor256 I believe this one could be closed as PR is merged. Thanks.

**Comment by yegor256** [comment]
@t-izbassar ask ticket reporter, see http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html

**Comment by t-izbassar** [comment]
@dmzaytsev can you close this one?

**Comment by dmzaytsev** [comment]
@t-izbassar thanks

**Comment by 0crat** [comment]
@t-izbassar[/z](http://www.0crat.com/u/t-izbassar) resigned from [#353](https://github.com/yegor256/takes/issues/353), since the job is not in scope anymore

**Comment by 0crat** [comment]
The job [#353](https://github.com/yegor256/takes/issues/353) is now out of scope

**Comment by 0crat** [comment]
Job `gh:yegor256/takes#353` is not assigned, can't get start time
