### ISSUE TITLE
Incorrect setting the expiration date for a cookies

### ISSUE THREAD

**Issue by dmzaytsev** [yegor256/takes#354]
There are 3 classes using setting the expiration date for a cookies: RsFlash, PsCookie, RsReturn. All of them use the following code for expiration date calculation :

``` java
 String.format(
                Locale.ENGLISH,
                "Expires=%1$ta, %1$td %1$tb %1$tY %1$tT GMT",
                new Date(
                    System.currentTimeMillis()
                        + TimeUnit.HOURS.toMillis(1L)
                )
            )
```

the expiration date declared as GMT but the value uses local timezone. As result we have incorrect expiration date for a cookies. It is really can be seen if the server and the client are located in different time zones. I believe the expiration date must be converted to GMT before using in `String.format()`

**Comment by yegor256** [comment]
@dmzaytsev and it's an obvious code duplication, we should resolve it, you're right

**Comment by davvd** [comment]
@dmzaytsev I will find a developer for the task soon...

**Comment by davvd** [comment]
@dmzaytsev attached this issue to milestone "1.0" (let me know if this is wrong)

**Comment by davvd** [comment]
@dmzaytsev many thanks, **15 mins** added to your acc for reporting this bug, pmt ID `60018802`

**Comment by davvd** [comment]
@adko-pl please pick this up, and keep in mind [these instructions](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html). Any technical questions - ask right here... The cost of this task is **30 mins** (this is exactly how much will be paid, not less not more), when the task is [done](http://www.xdsd.org/2014/04/15/definition-of-done.html)

**Comment by dmzaytsev** [comment]
@yegor256 It seems this ticket needs to be reassigned

**Comment by yegor256** [comment]
@davvd assign someone else pls

**Comment by davvd** [comment]
> @davvd assign someone else pls

@yegor256 no problem, I will try to find somebody else

**Comment by davvd** [comment]
@danff it's yours, please go ahead

**Comment by danff** [comment]
@davvd PR #562 has been creating to fix this issue.

**Comment by davvd** [comment]
> @davvd PR #562 has been creating to fix this issue.

@danff thank you!

**Comment by danff** [comment]
@davvd need more time waiting for PR to be merged

**Comment by davvd** [comment]
> @davvd need more time waiting for PR to be merged

@danff yes, take your time, thanks for letting me know

**Comment by yegor256** [comment]
@0crat in

**Comment by t-izbassar** [comment]
@yegor256 can you assign this issue to me? I've already created PR and this issue is a blocker for my other issue.

**Comment by 0crat** [comment]
> @0crat in ([here](https://github.com/yegor256/takes/issues/354#issuecomment-322125097))

@yegor256 Job [#354](https://github.com/yegor256/takes/issues/354) is now in scope, role is `DEV`

**Comment by t-izbassar** [comment]
@0crat status

**Comment by 0crat** [comment]
> @0crat status ([here](https://github.com/yegor256/takes/issues/354#issuecomment-361486791))

@t-izbassar This is what I know about this job, as in [§32](http://datum.zerocracy.com/pages/policy.html#32):

  * The job [#354](https://github.com/yegor256/takes/issues/354) is [in scope](http://datum.zerocracy.com/pages/policy.html#14) for 3days
  * The role is `DEV`
  * The job is not assigned to anyone
  * The [budget](http://datum.zerocracy.com/pages/policy.html#4) is 30 minutes
  * These users are banned and won't be assigned:
    * @dmzaytsev[/z](https://www.0crat.com/u/dmzaytsev): This user reported the ticket

**Comment by t-izbassar** [comment]
@dmzaytsev this can be closed as PR #777 was merged,

**Comment by 0crat** [comment]
Job `gh:yegor256/takes#354` is not assigned, can't get start time

**Comment by 0crat** [comment]
The job [#354](https://github.com/yegor256/takes/issues/354) is now out of scope
