### ISSUE TITLE
missing a location in the parameters of the RsFailure constructor

### ISSUE THREAD

**Issue by dmzaytsev** [yegor256/takes#355]
Right now RsFailure doesn't allow to set a redirection location, it uses RsForward with the default parameter value  '/'  for the location . 
It would be great to implement  a new ctor for RsFailure which allow to set the redirection location.

**Comment by yegor256** [comment]
@rultor release, tag is `0.21`

**Comment by dmzaytsev** [comment]
@yegor256  thanks!
