### ISSUE TITLE
Using a RsFork results in calling the take twice

### ISSUE THREAD

**Issue by GilraenBurland** [yegor256/takes#359]
I am trying to implement a RsFork.
Currently it looks like this:

```
return new RsFork(
    req,
    new FkMethods("GET", new TkGET()),
    new FkMethods("POST", new TkPOST())
)
```

After provoking an exception and debugging the called take I can see that it is called twice.
Furthermore if this take is using a `RqPrint` then the second call to `printBody()` freezes the whole application as it is using the same input stream as on the first call.

When I do the forking like this:

```
String method = new RqMethod.Base(req).method();
switch (method) {
    case "GET": return new TkGETServices(name, environment, this.source).act(req);
    case "POST": return new TkPOSTServices(name, environment, this.source).act(req);
    default: throw new UnsupportedOperationException();
}
```

There are no problems.

**Comment by yegor256** [comment]
@GilraenBurland can you show a unit test that reproduces the problem?

**Comment by GilraenBurland** [comment]
@yegor256 take a look at this: https://github.com/GilraenBurland/roster/blob/master/server/src/main/java/de/sl/roster/server/services/TkServices.java

Uncommenting the lines (and commenting out the return beforehand) and
after you start the local server via the Entry class and then post a request like this: 

`curl -XPOST http://localhost:8080/example-service/dev --data 'test'`

 the TkPOSTServices is called twice. 

And if I remove the `assertServiceDoesNotExist();`call then it freezes after calling `String address = new RqPrint(req).printBody();` the second time

**Comment by yegor256** [comment]
@GilraenBurland I just added a test in f141050 and it doesn't fail. I suspect that you need to use `RqGreedy`, because you're reading your requests a few times and of course only the first attempt succeeds... I need more details about your case to help more. Can you create a unit test that will fail?

**Comment by GilraenBurland** [comment]
@yegor256 It seems I can not recreate the problem in a unit test.
I debugged some more and it seems that it has something to do with my fallback chain.
If I remove the whole `TkFallback` the Take is only called once.
So my first guess was my usage of a RsFork in the error handling, but after removing that it still is called twice.

I'm at a loss for the moment :disappointed:

**Comment by GilraenBurland** [comment]
Hi @yegor256 I tested some more and created a unit test which tested my `TkRoot`.
Using the unit test showed me that the `TkPOSTServices` is called only once.
Testing again against the whole application resulted in two calls again.

Do you think it has something to do with my `Entry` or `App` classes?
https://github.com/GilraenBurland/roster/blob/master/server/src/main/java/de/sl/roster/server/Entry.java
https://github.com/GilraenBurland/roster/blob/master/server/src/main/java/de/sl/roster/server/App.java

**Comment by yegor256** [comment]
@GilraenBurland they both look correct to me. There is something wrong in your "takes". Try to create a unit test for `TkRoot` and reproduce the problem. Always reproduce in a test, don't debug.

**Comment by GilraenBurland** [comment]
HI @yegor256 
After refactoring my application quite a bit I do not have this problem anymore. I will close this ticket as it could not be reproduced even by myself.
