### ISSUE TITLE
TsSecure is not tested

### ISSUE THREAD

**Issue by yegor256** [yegor256/takes#36]
There is no unit test for `TsSecure` class, let's create one

**Comment by davvd** [comment]
@yegor256 sure, thanks, I added bug tag to it

**Comment by davvd** [comment]
@yegor256 thank you for the ticket reported, I topped your account for 15 mins, transaction `000-16ba3603`

**Comment by davvd** [comment]
@dmzaytsev please go ahead, it's your task now, keep [this](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html) in mind, and don't hesitate to ask any technical questions you may have; Budget here is **30 mins** (keep [this principle](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html) in mind)

**Comment by dmzaytsev** [comment]
@davvd I created the PR #86 for this issue

**Comment by dmzaytsev** [comment]
@davvd the PR #86 merged

**Comment by yegor256** [comment]
@dmzaytsev I'm the reporter of this ticket, you should ask me to close it, not @davvd  :)

**Comment by yegor256** [comment]
@dmzaytsev thanks!

**Comment by dmzaytsev** [comment]
@yegor256 somebody told me I should inform project manager every time I finished task

**Comment by yegor256** [comment]
@dmzaytsev yes, that's true, but you should close the task first, before you inform the project manager. The task is finished/closed only when the ticket is closed by the opener, see http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html#2.-close-it!

**Comment by davvd** [comment]
@elenavolokhova please, review this ticket for compliance with our [QA rules](http://www.teamed.io/qa.html)

**Comment by elenavolokhova** [comment]
@davvd Ticket passed QA review. It looks good!
