### ISSUE TITLE
Class RqHeaders.Smart has a generic, non-meaningful name

### ISSUE THREAD

**Issue by Suseika** [yegor256/takes#361]
The name and class-level javadoc of class `RqHeaders.Smart` doesn't explain its purpose, which is to fetch a single header. Lets rename the class and update its javadoc.

**Comment by yegor256** [comment]
@Suseika it's not only for fetching a single header. there will be more features in the future. this design is similar to the one we're using in jcabi-github: http://github.jcabi.com/apidocs-0.23/com/jcabi/github/package-summary.html
