### ISSUE TITLE
Combine username and password in a single object wherever they're passed together

### ISSUE THREAD

**Issue by Suseika** [yegor256/takes#362]
There are many methods with parameters `String user` and `String password`. Username and passowrd are generally passed around and created together. Lets encapsulate username and password in a `User` or `Credentials` or whatever named interface like this:

```java
interface User {
  String login();
  String password();
}
```

and replace `String user, String password` parameters with a `User` object, for example in `PsBasic.Entry#enter(String, String)` method. As the first implementation of `User` interface, lets extract a class named like `UserFromRequest` from the first half of `PsBasic#enter()` long method where username/password pair is obtained from a request.

**Comment by yegor256** [comment]
@Suseika but it's the only place where we have that, right? in `PsBasic.Entry`.. or there are other places?

**Comment by Suseika** [comment]
@yegor256 There is also `PsBasicTest#generateAuthenticateHead`.

I was wrong when I said that there are "many methods". But I think that in future, when there are more clients of `PsBasic.Entry`, we would benefit from passing username and password together, because those are usually obtained together (i.e. from database or registration form) and those are highly related concepts (one usually doesn't make sense without the other).

**Comment by yegor256** [comment]
@Suseika I see your point, but I disagree for now. If there would be 4+ parameters, this grouping would make sense. But just two... We may let them stay separately. Remember, objects/classes are not data bags/holders.
