### ISSUE TITLE
FtCLI new param --port=/tmp/foo.txt

### ISSUE THREAD

**Issue by yegor256** [yegor256/takes#364]
Let's make it possible to run `FtCLI` with this param:

```
--port=/tmp/foo.txt
```

If port is not a number, it has to be treated as file name. If this file is present, we read the port number from there. If it's not present, we allocate a new random port and save it into the file.

The main reason for this is to make `FtCLI` more thread/process safe.

**Comment by yegor256** [comment]
@rultor release, tag is `0.22`

**Comment by yegor256** [comment]
@rultor release, tag is `0.22`

**Comment by davvd** [comment]
@yegor256 milestone set to `1.0` (correct me if I am wrong)
