### ISSUE TITLE
RqMultipartTest#handlesRequestInTime fails sometimes on my machine

### ISSUE THREAD

**Issue by Suseika** [yegor256/takes#367]
`RqMultipartTest#handlesRequestInTime` seems to actually be a performance test. I don't think we should test performance during Maven build because it makes the build environment-dependent. For instance, on my machine this test finishes in too long time because my computer has to swap quite a lot in order to do a Maven build. Instead of required 3000 ms it runs for about 2000-10000 ms, and that causes a build to fail most of the time with a message like this:

```
Failed tests: 
  RqMultipartTest.handlesRequestInTime:379 
Expected: a value less than <3000L>
     but: <5099L> was greater than <3000L>

Tests run: 255, Failures: 1, Errors: 0, Skipped: 3
```

I think we should either get rid of this test, or to rewrite it to test something other than performance.

**Comment by davvd** [comment]
@yegor256 please do something about this issue

**Comment by yegor256** [comment]
@Suseika makes total sense, thanks

**Comment by davvd** [comment]
@suseika milestone set to `1.0` (correct me if I am wrong)

**Comment by davvd** [comment]
@suseika thanks for tis bug, I topped your account for 15 mins, transaction `AP-65M04576K5382373T`

**Comment by davvd** [comment]
@mstzn36 the task is for you now, follow [these guidelines](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html). Don't hesitate to ask any technical questions right here

Task's budget is **30 mins** (see [this](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html) for explanation)

**Comment by mstzn36** [comment]
@davvd we can't get rid of this test because we need to test that a big request can handle in an acceptable time.But also this test is environment dependent.
I think we need to create a new maven profile which runs performance tests such as RqMultipartTest#handlesRequestInTime.And this maven profile should be run in deploymen/build machine. 
Is this solution acceptable ?  What do you think about that?

**Comment by davvd** [comment]
> @davvd we can't get rid of this test because we need to test that a big request can handle in an acceptable time.But also this test is environment dependent.
> I think we need to create a new maven profile which runs performance tests such as RqMultipartTest#handlesRequestInTime.And this maven profile should be run in deploymen/build machine. 
> Is this solution acceptable ?  What do you think about that? 

@mstzn36 @yegor256 what do you think?

**Comment by yegor256** [comment]
@mstzn36 I agree with your idea, let's create a special profile for performance tests

**Comment by mstzn36** [comment]
@davvd PR https://github.com/yegor256/takes/pull/380 ready to review

**Comment by davvd** [comment]
> @davvd PR https://github.com/yegor256/takes/pull/380 ready to review

@mstzn36 OK, will take a look

**Comment by davvd** [comment]
@mstzn36 the ticket is with you for 15 days already. If it is not finished in the next 48 hours, it will be re-assigned to someone else, see [No Obligations](http://www.xdsd.org/2014/04/13/no-obligations-principle.html) principle, [this article](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html) should help if you're stuck... added -30 to your rating, now it is equal to [-45](http://www.netbout.com/b/35470?open=rating)

**Comment by davvd** [comment]
@rultor rultor closed it (automatically), @Suseika please take a look

**Comment by Suseika** [comment]
@mstzn36 Thanks

**Comment by mstzn36** [comment]
@Suseika @davvd why added -30 to my rating :( I sent my PR 4 days ago.

**Comment by Suseika** [comment]
@mstzn36 Your task is done not when your PR is merged, but when the author of a task accepts your PR. When your PR is merged, it is your responsibility to report that to the author of the task. An author of a task (that would be me in this case) only gets notifications from that task's thread, and not from any threads linked to it (as your PR is). So when your PR is merged, you should inform the author of a task about that so he will close the issue. If you would have written me when your PR had been merged, I would have closed the task and you wouldn't have gotten the penalty.

**Comment by mstzn36** [comment]
@Suseika @davvd I thought rultor closes the task automatically when PR is merged :( And I did not read anything  from http://www.yegor256.com/  about it is my responsibility to report to the author of task that PR is merged. Anyway I did not know about it. Can we revert -30 points for this time please? Next time i will be more careful about it.

**Comment by Suseika** [comment]
@mstzn36 I suggest you read carefully the link from the first message you recevied in Netbout, so there won't be any misunderstanding next time. Everything is explained there.

**Comment by davvd** [comment]
@ypshenychka review this ticket please, for compliance with our [quality rules](http://www.teamed.io/qa.html)

**Comment by ypshenychka** [comment]
@davvd Quality is good.

**Comment by davvd** [comment]
> @davvd Quality is good.

@ypshenychka thank you :)

**Comment by davvd** [comment]
@mstzn36 I added 10 mins to @ypshenychka (for QA review) in transaction 64430511; thanks, paid, **30 mins** to your account, payment ID is `AP-17066064VF2167110`, task took 364 hours and 47 mins to complete; +30 added to your rating, at the moment it is: [-15](http://www.netbout.com/b/35470?open=rating)
