### ISSUE TITLE
RqAuth is not tested

### ISSUE THREAD

**Issue by yegor256** [yegor256/takes#37]
There is no unit test for `RqAuth` class, let's create one

**Comment by davvd** [comment]
@yegor256 got it, tag `bug` is here

**Comment by davvd** [comment]
@yegor256 thanks for tis bug, I topped your account for 15 mins, transaction `000-5aef22f8`

**Comment by davvd** [comment]
@dmzaytsev the task is for you now, follow [these guidelines](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html). Don't hesitate to ask any technical questions right here... The budget here is **30 mins**, which is exactly how much time will be paid for, when the task is [completed](http://www.xdsd.org/2014/04/15/definition-of-done.html)

**Comment by dmzaytsev** [comment]
@yegor256 the PR has been merged
could you close the issue please

**Comment by yegor256** [comment]
@dmzaytsev thanks!

**Comment by dmzaytsev** [comment]
@davvd  I've created the PR #84 which has been merged

**Comment by davvd** [comment]
@dmzaytsev Thanks a lot, I just topped your account for **30 mins**, transaction ID `54285554`, total time was 42 hours and 39 mins; +30 added to your rating, current score is: [+195](http://www.netbout.com/b/35166?open=rating)
