### ISSUE TITLE
Application crashes when Response pipe is broken

### ISSUE THREAD

**Issue by carlosmiranda** [yegor256/takes#373]
I am trying to write a small monitoring application using Takes. Right now I'm having issues, because the application keeps crashing with the following error printed to the output:

```
Exception in thread "main" java.net.SocketException: Broken pipe
        at java.net.SocketOutputStream.socketWrite0(Native Method)
        at java.net.SocketOutputStream.socketWrite(SocketOutputStream.java:113)
        at java.net.SocketOutputStream.write(SocketOutputStream.java:159)
        at java.io.BufferedOutputStream.flushBuffer(BufferedOutputStream.java:82)
        at java.io.BufferedOutputStream.flush(BufferedOutputStream.java:140)
        at sun.nio.cs.StreamEncoder.implFlush(StreamEncoder.java:297)
        at sun.nio.cs.StreamEncoder.flush(StreamEncoder.java:141)
        at java.io.OutputStreamWriter.flush(OutputStreamWriter.java:229)
        at org.takes.rs.RsPrint.printHead(RsPrint.java:148)
        at org.takes.rs.RsPrint.print(RsPrint.java:110)
        at org.takes.http.BkBasic.print(BkBasic.java:104)
        at org.takes.http.BkBasic.accept(BkBasic.java:77)
        at org.takes.http.FtBasic.loop(FtBasic.java:105)
        at org.takes.http.FtBasic.start(FtBasic.java:91)
        at com.adecco.sam.util.aspire.CheckAvailability.main(CheckAvailability.java:119)
```

Line 119 is a call to `FtBasic.start()`. I don't think the application should crash when the response tries to write to the output, which means either this is definitely a bug or I'm doing something wrong.

**UPDATE**: Upon further investigation, it appears that the solution to this is to wrap the `Take` into a `BkSafe` before sending it to `FtBasic`. This is what `FtCLI` does. However, there's no clear documentation on how to use `BkSafe`  or `Back`, which is confusing to people who are building applications using this framework.

Thus, I propose a couple of things:
1. Document `Back` usage in `README`
2. Use `BkSafe` by default when using `FtBasic`, or provide an implementation `FtSafe` which does this and use it in the `README` examples.

This way developers won't be wondering why their app keeps crashing when the response pipe gets disconnected...

**Comment by yegor256** [comment]
@carlosmiranda makes sense, thanks!

**Comment by davvd** [comment]
@carlosmiranda this task will get someone's attention soon

**Comment by davvd** [comment]
@carlosmiranda since there is no milestone yet I set it to "1.0"

**Comment by davvd** [comment]
@carlosmiranda thank you for the ticket reported, I topped your account for 15 mins, transaction `61755338`

**Comment by carlosmiranda** [comment]
@yegor256 just a side note... I like the way that I'm actually able to use our open-source projects during my day job. :)

**Comment by yegor256** [comment]
@carlosmiranda that's what they are for :) and I'm sure you're not alone

**Comment by davvd** [comment]
@adko-pl this task is for you, keep [these principles](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html) in mind, and don't hesitate to ask any technical questions... The budget here is **30 mins**, which is exactly how much time will be paid for, when the task is [completed](http://www.xdsd.org/2014/04/15/definition-of-done.html)

**Comment by yegor256** [comment]
@0crat in

**Comment by 0crat** [comment]
> @0crat in ([here](https://github.com/yegor256/takes/issues/373#issuecomment-322125118))

@yegor256 Job `gh:yegor256/takes#373` is in scope.

**Comment by 0crat** [comment]
Job `gh:yegor256/takes#373` assigned to @caarlos0, please go ahead ([policy](http://datum.zerocracy.com/pages/policy.html)).

**Comment by 0crat** [comment]
@caarlos0 this job was assigned to you 8 days ago.
It will be taken away from you after 10 days from start (this is our policy).

**Comment by 0crat** [comment]
Oops! Job `gh:yegor256/takes#373` is not assigned to anyone.

**Comment by 0crat** [comment]
Oops! Job `gh:yegor256/takes#373` is not assigned to anyone.

**Comment by 0crat** [comment]
Oops! Job `gh:yegor256/takes#373` is not assigned to anyone.

**Comment by 0crat** [comment]
The job [#373](https://github.com/yegor256/takes/issues/373) assigned to @t-izbassar[/z](https://www.0crat.com/u/t-izbassar). The budget is 30 minutes, see [§4](http://datum.zerocracy.com/pages/policy.html#4). Please, read [§8](http://datum.zerocracy.com/pages/policy.html#8) and [§9](http://datum.zerocracy.com/pages/policy.html#9). If the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html).

**Comment by t-izbassar** [comment]
@0crat waiting for #776

**Comment by 0crat** [comment]
> @0crat waiting for #776  ([here](https://github.com/yegor256/takes/issues/373#issuecomment-360803748))

@t-izbassar The impediment for [#373](https://github.com/yegor256/takes/issues/373) was registered successfully by @t-izbassar[/z](https://www.0crat.com/u/t-izbassar)

**Comment by t-izbassar** [comment]
@carlosmiranda can you close this one? PR #776 was merged.

**Comment by carlosmiranda** [comment]
@t-izbassar thanks!

**Comment by 0crat** [comment]
Order was successfully finished: +30 points just awarded to @t-izbassar[/z](https://www.0crat.com/u/t-izbassar), total is [+60](https://www.0crat.com/u/t-izbassar)

**Comment by 0crat** [comment]
The job [#373](https://github.com/yegor256/takes/issues/373) is now out of scope
