### ISSUE TITLE
TkProxy

### ISSUE THREAD

**Issue by pinaf** [yegor256/takes#377]
A decorator class `TkProxy` would be useful. It would pass along requests received in `.act` to a different destination (internally handling body, headers, etc for the new request)  and also proxy back responses.

**Comment by pinaf** [comment]
@yegor256 what do you think about this one?

**Comment by davvd** [comment]
@yegor256 please dispatch this issue

**Comment by Suseika** [comment]
@yegor256 I support the idea, too.

**Comment by yegor256** [comment]
@pinaf yeah, good idea, thanks

**Comment by davvd** [comment]
@pinaf milestone set to `1.0` (correct me if I am wrong)

**Comment by davvd** [comment]
@pinaf thanks for this report, I added 15 mins to your account, in transaction `AP-00L05667MK3382931`

**Comment by davvd** [comment]
@tiaped this ticket is yours now, please proceed, and keep in mind [this](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html). Any technical questions you should ask right here; The budget of this task is **30 mins**. This is exactly how much time will be compensated, when the task is completed. Read about our [Definition of Done](http://www.xdsd.org/2014/04/15/definition-of-done.html)

**Comment by tiaped** [comment]
Hi, I have no idea of what to put in 
 * @version $Id: 9357c24e802b82a9275a1f58d2ff0d2d4eb69397 $
 * @since 0.20

Could please help?
Are you ok with abstract classes?
I think I will make preAct and postAct methods.

**Comment by tiaped** [comment]
I want also to be sure that the aim of the issue is to update request before acting and update reponse before returning.
Am I right?

**Comment by tiaped** [comment]
FYI I have some issues on qulice with maven 3.0.5. Everything was fine with maven 3.3.3.

**Comment by Suseika** [comment]
@tiaped Qulice doesn't work with Maven older than 3.2.5. And please address all your comments. If you're not sure to whom you should address them, read the work policy.

`$Id: 9357c24e802b82a9275a1f58d2ff0d2d4eb69397 $` is for https://stackoverflow.com/questions/384108/moving-from-cvs-to-git-id-equivalent. You basically don't touch it (it will be replaced with just `$Id$` automatically by git) and put `$Id$` in `@version` tags of your new classes.

**Comment by tiaped** [comment]
@Suseika Thanks a lot

**Comment by tiaped** [comment]
@davvd PR #377 is ready for review

**Comment by davvd** [comment]
> @davvd PR #377 is ready for review

@tiaped thanks, I'll take a look

**Comment by tiaped** [comment]
I have a question.
Is there a way to know the method of a request?
I think I can deal with other things.
I'll come back for other questions

**Comment by Suseika** [comment]
@tiaped
Here is a decorator for obtaining a method:
https://github.com/yegor256/takes/blob/master/src/main/java/org/takes/rq/RqMethod.java
How it is supposed to be used:
http://www.yegor256.com/2015/02/26/composable-decorators.html

And I have to remind you again to address every single comment to someone, i.e. comments should start with @ username, that's our rule.

**Comment by tiaped** [comment]
@davvd please reassign the task.

 I think that the issue is more complicated than expected.
I am going to use jcabi http request and response. But In my opinion, in order to handle every kind of requests (specificaly POST method with various ways of passing parameters or providing files) and handle every kind of responses (use the correct class to handle correctly (HTML, JSON, REST, others...) it could take some time.

**Comment by pinaf** [comment]
@tiaped you don't have to handle each of those cases individually. All you have to do is pass along all headers and the body. That's all that exists in any HTTP message.

**Comment by davvd** [comment]
@hs3180 this ticket is yours now, please proceed, and keep in mind [this](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html). Any technical questions you should ask right here... Total fixed cost of this task is **30 mins** (see [this](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html) for more info)

**Comment by davvd** [comment]
@hs3180 you're holding this ticket for 15 days already. If it is not finished (and closed) in the next 48 hours, it will be re-assigned to someone else, see [No Obligations](http://www.xdsd.org/2014/04/13/no-obligations-principle.html) principle ([this article](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html) should help if you're stuck)

added -30 to your rating, now it is equal to [-112](http://www.netbout.com/b/35610?open=rating)

**Comment by davvd** [comment]
@hs3180 it takes too long. Usually, we expect any task to be finished in less than a week. I'll assign someone else. Please stop working with it right now. See our [no obligations](http://www.xdsd.org/2014/04/13/no-obligations-principle.html) principle. -60 added to your rating, current score is: [-232](http://www.netbout.com/b/35610?open=rating)

**Comment by davvd** [comment]
@bdragan could you please pick this up? This [article](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html) explains how we work. Any technical questions you may ask right here. Task's budget is **30 mins** (see [this](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html) for explanation)

**Comment by bdragan** [comment]
@davvd There was a slight misunderstanding about the requirements. Please approve a bit more time for this issue. Thank you!

**Comment by davvd** [comment]
> @davvd There was a slight misunderstanding about the requirements. Please approve a bit more time for this issue. Thank you!

@bdragan of course, thanks for letting me know, take your time

**Comment by bdragan** [comment]
@pinaf PR #421 has been merged. The issue can be closed.

**Comment by pinaf** [comment]
@bdragan thanks!

**Comment by pinaf** [comment]
@yegor256 can we get a release with this new class?

**Comment by yegor256** [comment]
@rultor release, tag is `0.28`

**Comment by davvd** [comment]
@pinaf once `377-e6ce369a`/#458 puzzle is resolved (later, in another ticket), this ticket will be fully complete

**Comment by davvd** [comment]
@ypshenychka please, review this task for compliance with our [quality rules](http://at.teamed.io/qa.html)

**Comment by ypshenychka** [comment]
@tiaped 
According to our [QA Rules](http://www.teamed.io/qa.html):
>Messages in a ticket always start with a name of a user they are addressed to.

Please correct all your messages by indicating an addressee in the beginning.

**Comment by ypshenychka** [comment]
@tiaped ping

**Comment by ypshenychka** [comment]
@davvd Quality is acceptable.

**Comment by davvd** [comment]
> @davvd Quality is acceptable.

@ypshenychka thanks for the review, we'll try better next time

**Comment by davvd** [comment]
@bdragan added 10 mins to @ypshenychka, for QA review, payment code is `73869743`

I just added **30 mins** to your account, many thanks for your contribution (73869763).. 1221 hours and 45 mins spent here

+30 added to your rating, current score is: [+391](http://www.netbout.com/b/35709?open=rating)

**Comment by davvd** [comment]
@pinaf the last puzzle `458-ca123cf9`/#656 originated from here solved
