### ISSUE TITLE
PsGoogle creates incorrect  UserInfo link

### ISSUE THREAD

**Issue by dmzaytsev** [yegor256/takes#383]
PsGoogle creates incorrect  UserInfo link

https://github.com/yegor256/takes/blob/master/src/main/java/org/takes/facets/auth/social/PsGoogle.java#L146

`final String uri = new Href(this.gapi).path("oauth2/v1/userinfo")`
must be
`final String uri = new Href(this.gapi).path("oauth2").path("v1").path("userinfo")`

**Comment by yegor256** [comment]
@dmzaytsev thanks! we fixed something similar in 8eb99ecc0f72c3b30a170bc56f19a00588bab985

**Comment by davvd** [comment]
@dmzaytsev we will find someone to do this task, soon

**Comment by davvd** [comment]
@dmzaytsev attached this issue to milestone "1.0" (let me know if this is wrong)

**Comment by davvd** [comment]
@dmzaytsev thanks for tis bug, I topped your account for 15 mins, transaction `65405704`

**Comment by davvd** [comment]
@tiaped can you please help? Keep in mind [this](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html). If you have any technical questions, don't hesitate to ask right here

The cost of this task is **30 mins** (this is exactly how much will be paid, not less not more), when the task is [done](http://www.xdsd.org/2014/04/15/definition-of-done.html)

**Comment by yegor256** [comment]
@davvd assign someone else pls

**Comment by yegor256** [comment]
@davvd this is urgent

**Comment by davvd** [comment]
> @davvd assign someone else pls

@yegor256 no problem, I will try to find somebody else

**Comment by davvd** [comment]
> @davvd this is urgent

@yegor256 thanks, I added "urgent" label

**Comment by davvd** [comment]
@kpbird can you please help? Keep in mind [this](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html). If you have any technical questions, don't hesitate to ask right here... **30 mins** is the budget of the task. This is exactly how much will be paid when the problem is [solved](http://www.xdsd.org/2014/04/15/definition-of-done.html) (no matter how much time you will actually spend). See [this](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html) for more information

**Comment by dmzaytsev** [comment]
@yegor256 @kpbird  when can we expect fixing of the issue?
I have provided the fix in the ticket description already. There will be simple PR I guess. 

There is simliar case with unit test https://github.com/yegor256/takes/pull/378

**Comment by yegor256** [comment]
@dmzaytsev it seems that the problem is solved and we should just release a new version, right?

**Comment by dmzaytsev** [comment]
@yegor256 in which commit the problem is solved ?
I see same line in master branch..
https://github.com/yegor256/takes/blob/master/src/main/java/org/takes/facets/auth/social/PsGoogle.java#L146

**Comment by yegor256** [comment]
@dmzaytsev my bad, I thought that #378 solved the problem. Let me assign this to someone else

**Comment by yegor256** [comment]
@davvd assign this to @ekondrashev pls

**Comment by davvd** [comment]
> @davvd assign this to @ekondrashev pls

@yegor256 yes, done, @ekondrashev is at the task, please start! whoever worked with this task before, please stop immediately

**Comment by ekondrashev** [comment]
@dmzaytsev please see #405 PR.

**Comment by dmzaytsev** [comment]
@ekondrashev I'm sure the architect will ask you about the unit test...
see similar case here https://github.com/yegor256/takes/pull/378

**Comment by ekondrashev** [comment]
@dmzaytsev done, thx

**Comment by dmzaytsev** [comment]
@yegor256 could you release a new version?

**Comment by davvd** [comment]
@rultor rultor closed it (automatically), @dmzaytsev please take a look

**Comment by dmzaytsev** [comment]
@ekondrashev thanks!

**Comment by davvd** [comment]
@ypshenychka please, let us know what do you think about this ticket, according to our [QA rules](http://www.teamed.io/qa.html)

**Comment by ypshenychka** [comment]
@davvd Quality is good.

**Comment by davvd** [comment]
> @davvd Quality is good.

@ypshenychka thanks!

**Comment by davvd** [comment]
@ekondrashev 10 mins was added to the account of @ypshenychka (for QA review), in transaction 67472702; I added **30 mins** to your account, many thanks for working with the project! The completion time here was 67472711.; +30 added to your rating, at the moment it is: [+1049](http://www.netbout.com/b/35260?open=rating)

**Comment by dmzaytsev** [comment]
@yegor256 please release if possible

**Comment by dmzaytsev** [comment]
@yegor256 ping

**Comment by yegor256** [comment]
@rultor release, tag is `0.24.1`
