### ISSUE TITLE
document pom file is based on jcabi-parent

### ISSUE THREAD

**Issue by hs3180** [yegor256/takes#388]
I had no idea why maven does a lot of **implicit tasks** when I was to add my integration tests.
finally, I found that the `pom.xml` was based on the [jcabi-parent](https://github.com/jcabi/jcabi-parent/blob/master/pom.xml) and understood where are the **implicit tasks** from.

plz add some explanation about jcabi-parent to the [README#how-to-contribute](https://github.com/yegor256/takes#how-to-contribute)

**Comment by davvd** [comment]
@yegor256 please do something about this issue

**Comment by yegor256** [comment]
@hs3180 fixed in 447b20a thanks!
