### ISSUE TITLE
AppITCase is always skipped

### ISSUE THREAD

**Issue by hs3180** [yegor256/takes#389]
takes.port is always `null`.
seems that `AppITCase` should use `takes.home` instead of `take.port`

**Comment by davvd** [comment]
@yegor256 please do something about this issue

**Comment by davvd** [comment]
@hs3180 there is no milestone yet, so I set it to `1.0`

**Comment by davvd** [comment]
@hs3180 many thanks for the bug report, I added 15 mins to your acc, transaction `AP-7T076912CB8708117`

**Comment by davvd** [comment]
@bdragan please go ahead with this task,it's yours

**Comment by bdragan** [comment]
@hs3180 `takes.port` is a system property, so it is `null` when the property is not set. Also, using `takes.home` instead of it as parameter in the `assumeNotNull` method would make the port part of the request URL invalid if the port is `null`.

Could you please provide more details about reproducing the issue?

**Comment by hs3180** [comment]
@bdraganjust run tests and see the failsafe report.it will tell you that AppITCase was skipped.the 'takes.port' is always null if you output it.

**Comment by bdragan** [comment]
@hs3180 You're right, thanks! PR submitted.

**Comment by bdragan** [comment]
@hs3180 PR #435 has been merged. The issue can be closed.

**Comment by hs3180** [comment]
@bdragan thanks a lot.
@davvd this puzzle has been solved.

**Comment by davvd** [comment]
@elenavolokhova please, review this task for compliance with our [quality rules](http://at.teamed.io/qa.html)

**Comment by elenavolokhova** [comment]
@davvd Looks good!

**Comment by davvd** [comment]
> @davvd Looks good!

@elenavolokhova thanks for the review and a good remark

**Comment by davvd** [comment]
@bdragan just added 10 mins to @elenavolokhova (for QA), payment ID is `69602381`

done, I added **30 mins** in payment `69602386`, 148 hours and 37 mins spent to complete this

added +30 to your rating, now it is equal to [+263](http://www.netbout.com/b/35709?open=rating)
