### ISSUE TITLE
PsChain is not tested

### ISSUE THREAD

**Issue by yegor256** [yegor256/takes#39]
There is no unit test for `PsChain` class, let's create one

**Comment by davvd** [comment]
@yegor256 OK, I labeled it as `bug`

**Comment by davvd** [comment]
@yegor256 thanks for the report, I topped your acc for 15 mins, payment ID `000-34106f0d`

**Comment by davvd** [comment]
@eg04lt3r This task is yours, please go ahead keeping in mind [this](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html). If any questions, don't hesitate to ask right here... **30 mins** is the budget of the task. This is exactly how much will be paid when the problem is [solved](http://www.xdsd.org/2014/04/15/definition-of-done.html) (no matter how much time you will actually spend). See [this](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html) for more information

**Comment by eg04lt3r** [comment]
Please, check second commit and review code. Thanks.

**Comment by eg04lt3r** [comment]
How should i run maven build? Cause when i check "qulice" profile, it's successfuly build.

**Comment by yegor256** [comment]
@eg04lt3r just run `mvn clean install -Pqulice` on command line

**Comment by eg04lt3r** [comment]
Thanks.

2015-03-30 10:46 GMT+03:00 Yegor Bugayenko <notifications@github.com>:

**Comment by eg04lt3r** [comment]
Also i have question about code analyse with qulice. It's failure build,
cause First sentence in a comment should start with a capital letter
(RegexpMultilineCheck), but i have just start of javadoc block /**. Also
second error for this line is "First sentence should end with a period.
(JavadocStyleCheck)". How should I prevent these issues and resolve in my
case? Thanks.


2015-03-30 11:05 GMT+03:00 Alexey Aleksey <eg04lt3r@gmail.com>:

**Comment by eg04lt3r** [comment]
Fixed. Please, try build with last commit.

**Comment by yegor256** [comment]
@eg04lt3r see http://www.yegor256.com/2015/02/16/it-is-not-a-school.html

**Comment by eg04lt3r** [comment]
Understand what you are talking about, i just establish workflow in new
project.

2015-03-30 21:12 GMT+03:00 Yegor Bugayenko <notifications@github.com>:

**Comment by eg04lt3r** [comment]
Can it be closed?

**Comment by yegor256** [comment]
@eg04lt3r was it fixed? In which pull request? Also, it's a good practice to address your comments by placing the name of the person in front of them. Otherwise, it's not clear who are you talking to.

**Comment by eg04lt3r** [comment]
@yegor256 #83 pull request

**Comment by yegor256** [comment]
@eg04lt3r thanks!

**Comment by elenavolokhova** [comment]
@davvd Ticked passed QA review. Quality is acceptable. A lot of small issues in following our process were addressed and clarified by @yegor256 here.

**Comment by yegor256** [comment]
@davvd I confirm, the quality is acceptable here

**Comment by davvd** [comment]
> @davvd I confirm, the quality is acceptable here

@yegor256 thanks, got it

**Comment by davvd** [comment]
@eg04lt3r just added 10 mins to @elenavolokhova (for QA), payment ID is `54692010`; Much appreciated! **38 mins** was added to your account, payment ID `54692045`, time spent is 130 hours and 25 mins; there is a bonus for fast delivery (age=2900); added +38 to your rating, now it is equal to [+38](http://www.netbout.com/b/35234?open=rating)
