### ISSUE TITLE
RqLive doens't fail when the input stream is empty

### ISSUE THREAD

**Issue by hs3180** [yegor256/takes#391]
`org.takes.rq.RqLive` will return an empty request when receive an empty input stream.

    Request req = new RqLive(new ByteArrayInputStream(new byte[0]));

I think it should throw an exception.

**Comment by yegor256** [comment]
@hs3180 good catch, thanks

**Comment by davvd** [comment]
@hs3180 we will find someone to do this task, soon

**Comment by davvd** [comment]
@hs3180 milestone set to `1.0` (correct me if I am wrong)

**Comment by davvd** [comment]
@hs3180 thanks for tis bug, I topped your account for 15 mins, transaction `AP-2NY50858CU066131T`

**Comment by davvd** [comment]
@hdouss it's yours now, please proceed keeping in mind [our principles](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html). Feel free to ask any technical questions right here in the ticket; Budget here is **30 mins** (keep [this principle](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html) in mind)

**Comment by HDouss** [comment]
Is it ok to just throw an IOException with a "Empty request" message in this case ?

**Comment by HDouss** [comment]
@davvd @hs3180 If empty requests should not be accepted, Tests on `org.takes.http.FtSecureTest` will fail. All requests (`com.jcabi.http.request.JdkRequest.JdkRequest` requests) sent in `org.takes.http.FtSecureTest` are empty.

**Comment by HDouss** [comment]
@davvd : waiting on decision whether to accept empty requests, or open an issue to fix tests on `org.takes.http.FtSecureTest`

**Comment by hs3180** [comment]
@HDouss this ticket is not talking about *request with empty header and body* but **a tcp connection that says nothing**.

a request with no content is acceptable. We should reject request that doesn't meet the [http specification](http://www.w3.org/Protocols/rfc2616/rfc2616-sec5.html#sec5.1), including a request with only a EOF. Every request should start with a start-line.

**Comment by HDouss** [comment]
@hs3180 I agree. That's what I meant. JdkRequest is sending a request with an EOF onFtSecureTest

**Comment by HDouss** [comment]
@hs3180 I was wrong. I was confused by the fact that `inputStream.available` returned 0. The `inputStream` was not empty, and so was not the `JdkRequest`.

**Comment by hs3180** [comment]
@HDouss inputStream.available tells you how many bytes in buffer. [inputStream.read will return -1 if meets EOF](http://docs.oracle.com/javase/7/docs/api/java/io/InputStream.html#read())

**Comment by HDouss** [comment]
@hs3180 PR #447  has been merged to master. The issue can be closed.

**Comment by hs3180** [comment]
@HDouss thanks!

**Comment by davvd** [comment]
@ypshenychka please, help us to evaluate quality here, as per [par.24](http://at.teamed.io/policy.html#24)

**Comment by ypshenychka** [comment]
@davvd Quality is good.

**Comment by davvd** [comment]
> @davvd Quality is good.

@ypshenychka many thanks

**Comment by davvd** [comment]
@hdouss just added 10 mins to @ypshenychka (for QA), payment ID is `71307443`. **30 mins** sent to your balance (ID `71307447`), many thanks! It took 312 hours and 8 mins.. +30 added to your rating, at the moment it is: [+30](http://www.netbout.com/b/36032?open=rating)
