### ISSUE TITLE
RqMethod corrects format

### ISSUE THREAD

**Issue by hs3180** [yegor256/takes#392]
RqMethod just read first field in headers, and split it with spaces.
It should check the header format according to HTTP specification.

**Comment by yegor256** [comment]
@hs3180 make sense, thanks for the catch

**Comment by davvd** [comment]
@hs3180 I will ask someone to take care of this task soon

**Comment by davvd** [comment]
@hs3180 attached this issue to milestone "1.0" (let me know if this is wrong)

**Comment by davvd** [comment]
@hs3180 thanks for the report, I topped your acc for 15 mins, payment ID `AP-7DJ20956U6273802U`

**Comment by davvd** [comment]
@bdragan it's yours, please go ahead

**Comment by bdragan** [comment]
@hs3180 The current implementation of `RqMethod` already reads the method according to HTTP spec. What exactly do you have in mind? Is it validation (that it must be one of `GET`, `POST`..., exactly one space between method, URL and protocol version and ends with CRLF)?

**Comment by hs3180** [comment]
@bdragan yes, let's do a validation according to http://www.w3.org/Protocols/rfc2616/rfc2616-sec5.html

**Comment by bdragan** [comment]
@hs3180 Thanks, PR submitted.

**Comment by hs3180** [comment]
@bdragan you should accept methods which are not in default methods. treat them as `extension-method`

**Comment by bdragan** [comment]
@hs3180 Thanks for the remark. What are `extension-method`s?

**Comment by hs3180** [comment]
@bdragan

       Method         = "OPTIONS"                ; Section 9.2
                      | "GET"                    ; Section 9.3
                      | "HEAD"                   ; Section 9.4
                      | "POST"                   ; Section 9.5
                      | "PUT"                    ; Section 9.6
                      | "DELETE"                 ; Section 9.7
                      | "TRACE"                  ; Section 9.8
                      | "CONNECT"                ; Section 9.9
                      | extension-method
       extension-method = token

       token          = 1*<any CHAR except CTLs or separators>

## \*rule
The character "\*" preceding an element indicates repetition. The full form is "\<n\>\*\<m\>element" indicating at least \<n\> and at most \<m\> occurrences of element. Default values are 0 and infinity so that "\*(element)" allows any number, including zero; "1\*element" requires at least one; and "1\*2element" allows one or two.

**Comment by bdragan** [comment]
@hs3180 Thanks, I missed that one. New changes submitted.

**Comment by bdragan** [comment]
@hs3180 PR #451 has been merged. The issue can be closed.

**Comment by davvd** [comment]
@bdragan you're working with this issue for 15 days already... -30 added to your rating, at the moment it is: [+346](http://www.netbout.com/b/35709?open=rating)

**Comment by hs3180** [comment]
@bdragan thanks

**Comment by hs3180** [comment]
@davvd this puzzle has been solved before 3 days ago

**Comment by davvd** [comment]
> @davvd this puzzle has been solved before 3 days ago

@hs3180 thanks

**Comment by davvd** [comment]
@elenavolokhova please, review this task for compliance with our [quality rules](http://at.teamed.io/qa.html)

**Comment by elenavolokhova** [comment]
@davvd Looks good!

**Comment by davvd** [comment]
> @davvd Looks good!

@elenavolokhova thanks a lot :)

**Comment by davvd** [comment]
@bdragan added 10 mins to @elenavolokhova, for QA review, payment code is `71892975`... thank you, added **30 mins** to your acc, payment num is `71892982`, 421 hours and 54 mins spent in total to complete... added +30 to your rating, now it is equal to [+376](http://www.netbout.com/b/35709?open=rating)
