### ISSUE TITLE
unit tests with side effects

### ISSUE THREAD

**Issue by hs3180** [yegor256/takes#396]
there are many unit tests using true file system, true threads and true sockets.

For example, `BkTimeableTest` creates a temporary folder, starts up a threads.Within the threads, it sleeps in real time and makes a http request using jcabi-http which sets up a real socket connection.

Are they designed to be like this? Or they are actually integration tests.

**Comment by yegor256** [comment]
@hs3180 good point. I think that sockets, files and threads are native components of JDK and they are allowed to be used in unit tests. Integration tests are for something that is outside of JDK, like web services, databases, etc.
