### ISSUE TITLE
PsByFlag is not tested

### ISSUE THREAD

**Issue by yegor256** [yegor256/takes#40]
There is no unit test for `PsByFlag` class, let's create one

**Comment by davvd** [comment]
@yegor256 right, I added the `bug` tag

**Comment by davvd** [comment]
@yegor256 thanks for the report, I topped your acc for 15 mins, payment ID `000-02320972`

**Comment by davvd** [comment]
@ikhvostenkov it's yours now, please proceed keeping in mind [our principles](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html). Feel free to ask any technical questions right here in the ticket... The budget of this issue is **30 mins**, which is exactly how much will be paid when the task is *done* (see [this](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html) for explanation)

**Comment by ikhvostenkov** [comment]
@davvd I've done with the test. I have 3 questions:
1. Do you have any coding rules convention doc? I was trying to follow coding rules in other tests, but could be not perfect.
2. JUnit is absent in pom.xml. Tests will not run without this dependency. I do not understand how it works for instance on building machine. I've just added dependency locally in my IDE to run it.
 3. Shall I open pull request with my changes?

**Comment by ikhvostenkov** [comment]
One more point: actually test was already created and covered ~60%, I've modified it to reach 100% coverage.

**Comment by yegor256** [comment]
@ikhvostenkov just run `mvn clean install -Pqulice` on command line and you will see our coding conventions (we use qulice.com for that). JUnit is coming from parent pom, see http://www.yegor256.com/2015/02/05/jcabi-parent-maven-pom.html

Yes, just submit a pull request when you're ready, see http://www.yegor256.com/2014/04/15/github-guidelines.html

**Comment by davvd** [comment]
@ikhvostenkov the task is your hands for the last 15 days.. keep in mind that if it's not closed in the next 48 hours, it will be re-assigned to someone else, see [No Obligations](http://www.xdsd.org/2014/04/13/no-obligations-principle.html) principle. [This article](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html) should help if you're stuck. -30 added to your rating, at the moment it is: [+0](http://www.netbout.com/b/35232?open=rating)

**Comment by ikhvostenkov** [comment]
@yegor256 Could you please close it if you do not have any comments, due to pull request has been successfully merged?

**Comment by yegor256** [comment]
@ikhvostenkov many thanks!

**Comment by davvd** [comment]
@elenavolokhova please, review this ticket for compliance with our [QA rules](http://www.teamed.io/qa.html)

**Comment by elenavolokhova** [comment]
@ikhvostenkov 
>ikhvostenkov commented 24 days ago
One more point: actually test was already created and covered ~60%, I've modified it to reach 100% coverage.

 According to our [quality rules](http://www.teamed.io/qa.html):
 > Messages in a ticket always start with a name of a user they are addressed to.

Try to avoid such issues in future.

 Please confirm that everything is clear and you have no questions regarding this approach.

**Comment by ikhvostenkov** [comment]
@elenavolokhova confirmed. Everything is absolutely clear.

**Comment by elenavolokhova** [comment]
@ikhvostenkov Thank you.

**Comment by elenavolokhova** [comment]
@davvd Quality is acceptable.

**Comment by davvd** [comment]
> @davvd Quality is acceptable.

@elenavolokhova thanks, got it. everybody, please try to make it good next time

**Comment by davvd** [comment]
@ikhvostenkov 10 mins was added to the account of @elenavolokhova (for QA review), in transaction 55871054... thank you, added **38 mins** to your acc, payment num is `55871122`, 496 hours and 59 mins spent in total to complete... the bonus for fast delivery (age=3853)... +38 to your rating, your total score is [+61](http://www.netbout.com/b/35232?open=rating)
