### ISSUE TITLE
RsPrettyXML causes NPE

### ISSUE THREAD

**Issue by dmzaytsev** [yegor256/takes#400]
The code below causes null pointer exception
I believe the issue has to be fixed
```
new RsPrettyXML(
    new RsWithBody(                        
        "<!DOCTYPE html SYSTEM \"about:legacy-compat\"><html><head></head><body></body></html>"
    )
)
```
>java.lang.NullPointerException
	at java.util.Hashtable.put(Hashtable.java:459)
	at java.util.Properties.setProperty(Properties.java:166)
	at net.sf.saxon.jaxp.IdentityTransformer.setOutputProperty(IdentityTransformer.java:293)
	at org.takes.rs.RsPrettyXML.prepareDocType(RsPrettyXML.java:171)
	at org.takes.rs.RsPrettyXML.transform(RsPrettyXML.java:135)
	at org.takes.rs.RsPrettyXML.make(RsPrettyXML.java:105)
	at org.takes.rs.RsPrettyXML.body(RsPrettyXML.java:91)
	at org.takes.rs.RsWrap.body(RsWrap.java:63)
	at org.takes.rs.RsPrint.printBody(RsPrint.java:157)
	at org.takes.rs.RsPrint.printBody(RsPrint.java:88)
	at org.takes.rs.RsPrettyXMLTest.formatsHtml5DoctypeBody(RsPrettyXMLTest.java:74)

**Comment by davvd** [comment]
@dmzaytsev I will ask someone to take care of this task soon

**Comment by davvd** [comment]
@dmzaytsev since the ticket has no milestone I set it to 1.0

**Comment by davvd** [comment]
@dmzaytsev thanks a lot for reporting, **15 mins** added to your acc, pmt ID `66391594`

**Comment by davvd** [comment]
@xupyprmv This task is yours, please go ahead keeping in mind [this](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html). If any questions, don't hesitate to ask right here

The budget here is **30 mins**, which is exactly how much time will be paid for, when the task is [completed](http://www.xdsd.org/2014/04/15/definition-of-done.html)

**Comment by dmzaytsev** [comment]
@yegor256  please release if possible

**Comment by davvd** [comment]
@rultor rultor closed it (automatically), @dmzaytsev please take a look

**Comment by dmzaytsev** [comment]
@xupyprmv I would suggest ask me to close the ticket and mention the PR that fixed the issues

**Comment by xupyprmv** [comment]
@dmzaytsev Thanks for advise. #400 was fixed by PR #464. Please close this ticket if you have no more remarks.

**Comment by dmzaytsev** [comment]
@xupyprmv thanks!

**Comment by dmzaytsev** [comment]
@yegor256 please release if possible

**Comment by yegor256** [comment]
@rultor release, tag is `0.28.2`

**Comment by davvd** [comment]
@ypshenychka please, let us know what do you think about this ticket, according to our [QA rules](http://at.teamed.io/qa.html)

**Comment by ypshenychka** [comment]
@davvd Quality is good.

**Comment by davvd** [comment]
> @davvd Quality is good.

@ypshenychka thanks for the review

**Comment by davvd** [comment]
@xupyprmv just added 10 mins to @ypshenychka (for QA), payment ID is `72513860`; I added **30 mins** to your account, many thanks for working with the project! The completion time here was AP-9W591330AG839052C.; +30 added to your rating, current score is: [+0](http://www.netbout.com/b/35999?open=rating)
