### ISSUE TITLE
rultor merge fails

### ISSUE THREAD

**Issue by bdragan** [yegor256/takes#401]
rultor merge fails with:

`Caused by: java.lang.ClassNotFoundException: net.sourceforge.cobertura.coveragedata.TouchCollector`

Full log available [here](http://www.rultor.com/t/5303-144853990).

The issue appeared when merging PR #398.

**Comment by davvd** [comment]
@yegor256 please do something about this issue

**Comment by yegor256** [comment]
@bdragan if master branch is not broken, it's not a bug. It's a problem in your particular pull request, you have to solve it yourself.

**Comment by yegor256** [comment]
@bdragan this link may help you: http://www.yegor256.com/2015/02/16/it-is-not-a-school.html

**Comment by bdragan** [comment]
@yegor256 Thank you for the feedback. However, in my environment the same issue also appears on master with: `mvn clean site -Psite`.

I will appreciate any advice on how to proceed.

**Comment by yegor256** [comment]
@bdragan in that case, submit a new ticket, with a proper description of the problem. Explain what is broken in master and how can I reproduce it. See this: http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html

**Comment by bdragan** [comment]
@yegor256 Issue #403 created.
