### ISSUE TITLE
FtBasic should fail fast and exit if Address is already in use

### ISSUE THREAD

**Issue by longtimeago** [yegor256/takes#402]
Currently,
If the port we are trying to run a taks is busy `FtBasic` is definitely can't do anything with it. 
But it is still spinning around the exit condition.

IMHO, it's better to fail fast in this case.
Port is busy -> fail and exit.

**Comment by yegor256** [comment]
@longtimeago I don't think you're right... can you show the code which will prove it?

**Comment by longtimeago** [comment]
@yegor256 you are right ... that was another issue
