### ISSUE TITLE
Maven site phase execution fails

### ISSUE THREAD

**Issue by bdragan** [yegor256/takes#403]
`mvn clean site -Psite` fails:

`Caused by: java.lang.ClassNotFoundException: net.sourceforge.cobertura.coveragedata.TouchCollector`

Full log available [here](http://www.rultor.com/t/5303-144853990).

**Comment by davvd** [comment]
@bdragan I will find a developer for the task soon...

**Comment by davvd** [comment]
@bdragan since there is no milestone yet I set it to "1.0"

**Comment by davvd** [comment]
@bdragan many thanks for the report, I topped your account for 15 mins, transaction 66774882

**Comment by yegor256** [comment]
@bdragan I'll fix it in a few hours

**Comment by davvd** [comment]
@yegor256 it's yours,please help,budget is 30 mins

**Comment by yegor256** [comment]
@bdragan I believe it's fixed in 5ecfaf0, please confirm

**Comment by yegor256** [comment]
@bdragan my bad, this one fixes it for sure: f134f34

**Comment by bdragan** [comment]
@davvd @yegor256 It works now, thanks!

**Comment by davvd** [comment]
> @davvd @yegor256 It works now, thanks!

@bdragan no problem ;)

**Comment by davvd** [comment]
@ypshenychka please, review this task for compliance with our [quality rules](http://www.teamed.io/qa.html)

**Comment by ypshenychka** [comment]
@yegor256 
According to our [QA Rules](http://www.teamed.io/qa.html):
>Some of ticket messages must mention all pull requests where the problem was actually fixed.

Please mention in any of your messages link to correpsonding PR.

**Comment by yegor256** [comment]
@ypshenychka yeah, you're right, my bad, will try to go through PRs always. There is no PR here

**Comment by ypshenychka** [comment]
@yegor256 Thank you. Let's try to avoid such situations in future.

**Comment by ypshenychka** [comment]
@davvd Quality is acceptable.

**Comment by davvd** [comment]
> @davvd Quality is acceptable.

@ypshenychka thanks a lot, next time everybody should try to make it better

**Comment by davvd** [comment]
@yegor256 I added 10 mins to @ypshenychka (for QA review) in transaction 67518097... Much obliged! I have added **1 hour** to your account in payment "000-1e513438", 16 hours and 59 mins spent... m=1019, that's why a bonus here for fast delivery... +60 added to your rating, current score is: [+12395](http://www.netbout.com/b/35008?open=rating)
