### ISSUE TITLE
versions of RESTful API

### ISSUE THREAD

**Issue by yegor256** [yegor256/takes#406]
We should introduce a mechanism for making RESTful APIs versioned. See this discussion: http://stackoverflow.com/questions/389169/best-practices-for-api-versioning

**Comment by alxn** [comment]
@yegor256 this [answer](http://stackoverflow.com/a/6750376/2782193) ?

**Comment by yegor256** [comment]
@alxn yeah, seems so... thinking about it now

**Comment by davvd** [comment]
@yegor256 since there is no milestone yet I set it to "1.0"

**Comment by davvd** [comment]
@yegor256 it's yours, budget is 30 mins, please go ahead

**Comment by davvd** [comment]
@yegor256 thanks for the report, I topped your acc for 15 mins, payment ID `000-40375d5a`

**Comment by yegor256** [comment]
@davvd pls add extra 570 minutes to @longtimeago for the review of contest participants

**Comment by davvd** [comment]
> @davvd pls add extra 570 minutes to @longtimeago for the review of contest participants

@yegor256 I've sent 9 hours and 30 mins extra to @longtimeago in transaction ID "105473311"

**Comment by paulodamaso** [comment]
@0crat in

**Comment by 0crat** [comment]
> @0crat in ([here](https://github.com/yegor256/takes/issues/406#issuecomment-455241794))

@paulodamaso Job [#406](https://github.com/yegor256/takes/issues/406) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
> @0crat in ([here](https://github.com/yegor256/takes/issues/406#issuecomment-455241794))

@paulodamaso The job [#406](https://github.com/yegor256/takes/issues/406) assigned to @yegor256[/z](https://www.0crat.com/u/yegor256), here is [why](https://www.0crat.com/footprint/C3FFK3YAY/1c0ad311-015a-48ef-b758-66aefaebd3d1); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be no monetary reward for this job

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 point(s) just awarded to @yegor256[/z](https://www.0crat.com/u/yegor256)

**Comment by paulodamaso** [comment]
@0crat resign

**Comment by 0crat** [comment]
> @0crat resign ([here](https://github.com/yegor256/takes/issues/406#issuecomment-457828369))

@paulodamaso The user @yegor256[/z](https://www.0crat.com/u/yegor256) resigned from [#406](https://github.com/yegor256/takes/issues/406), please stop working. Reason for job resignation: Order was cancelled

**Comment by 0crat** [comment]
The job [#406](https://github.com/yegor256/takes/issues/406) assigned to @marceloamadeu[/z](https://www.0crat.com/u/marceloamadeu), here is [why](https://www.0crat.com/footprint/C3FFK3YAY/34b1adb4-2139-41cf-be6a-9246d7fcf379); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be no monetary reward for this job

**Comment by marceloamadeu** [comment]
@0crat refuse

**Comment by 0crat** [comment]
> @0crat refuse ([here](https://github.com/yegor256/takes/issues/406#issuecomment-462334073))

@marceloamadeu The user @marceloamadeu[/z](https://www.0crat.com/u/marceloamadeu) resigned from [#406](https://github.com/yegor256/takes/issues/406), please stop working. Reason for job resignation: Order was cancelled

**Comment by 0crat** [comment]
Tasks refusal is discouraged, see [§6](http://www.zerocracy.com/policy.html#6): -15 point(s) just awarded to @marceloamadeu[/z](https://www.0crat.com/u/marceloamadeu)

**Comment by 0crat** [comment]
The job [#406](https://github.com/yegor256/takes/issues/406) assigned to @oridan[/z](https://www.0crat.com/u/oridan), here is [why](https://www.0crat.com/footprint/C3FFK3YAY/77862a4a-9c5b-4283-bc79-7283dda9f810); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be no monetary reward for this job

**Comment by oridan** [comment]
@0crat wait

**Comment by 0crat** [comment]
> @0crat wait  ([here](https://github.com/yegor256/takes/issues/406#issuecomment-466606581))

@oridan The impediment for [#406](https://github.com/yegor256/takes/issues/406) was registered successfully by @oridan[/z](https://www.0crat.com/u/oridan)

**Comment by oridan** [comment]
@yegor256 please, close this issue.

**Comment by oridan** [comment]
@0crat status

**Comment by 0crat** [comment]
> @0crat status ([here](https://github.com/yegor256/takes/issues/406#issuecomment-470170592))

@oridan This is what I know about this job in [C3FFK3YAY](https://www.0crat.com/p/C3FFK3YAY), as in [§32](http://www.zerocracy.com/policy.html#32):

  * The job [#406](https://github.com/yegor256/takes/issues/406) is [in scope](http://www.zerocracy.com/policy.html#14) for 2mon
  * The role is `DEV`
  * The job is assigned to @oridan[/z](https://www.0crat.com/u/oridan) for [21days](http://www.zerocracy.com/policy.html#8)
  * @oridan[/z](https://www.0crat.com/u/oridan) is on vacation!
  * There is no monetary reward attached, it's a [free](http://www.zerocracy.com/policy.html#2) job
  * The job has an [impediment](http://www.zerocracy.com/policy.html#9)
  * The [budget](http://www.zerocracy.com/policy.html#4) is 30 minutes/points
  * These users are banned and won't be assigned:
    * @yegor256[/z](https://www.0crat.com/u/yegor256): This user reported the ticket
    * @marceloamadeu[/z](https://www.0crat.com/u/marceloamadeu): User was resigned from the ticket
  * Job [footprint](https://www.0crat.com/footprint/C3FFK3YAY?q=%7Bjob%3A%27gh%3Ayegor256%2Ftakes%23406%27%2Ctype%3A%7B%24not%3A%2F%5ENotify%2F%7D%7D) (restricted area)

**Comment by oridan** [comment]
@yegor256 please, close this issue.

**Comment by oridan** [comment]
@paulodamaso ping

**Comment by paulodamaso** [comment]
@oridan Thanks!

**Comment by 0crat** [comment]
@ypshenychka[/z](https://www.0crat.com/u/ypshenychka) please review this job completed by @oridan[/z](https://www.0crat.com/u/oridan), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by 0crat** [comment]
The job [#406](https://github.com/yegor256/takes/issues/406) is now out of scope

**Comment by ypshenychka** [comment]
@oridan According to our [QA Rules](http://www.zerocracy.com/policy.html#42):
>All impediments registered in the ticket have explanations of the reasons and links to related tickets, if necessary

Please correct registered [impediment](https://github.com/yegor256/takes/issues/406#issuecomment-466606581) to include more details.

**Comment by ypshenychka** [comment]
@oridan According to our [QA Rules](http://www.zerocracy.com/policy.html#42):
>All commit messages have links to issues

None of your commits contains link to issue. Please confirm you'll try to follow this rule next time.

**Comment by oridan** [comment]
@ypshenychka I'll try to follow this rule next time.

**Comment by ypshenychka** [comment]
@oridan Also please update your impediment with more details.

**Comment by oridan** [comment]
@ypshenychka could you please point those impediments that are not clear enough and need more details?

**Comment by ypshenychka** [comment]
@oridan See my [comment](https://github.com/yegor256/takes/issues/406#issuecomment-472066251) above

**Comment by oridan** [comment]
@ypshenychka I agree with you, just saying wait to 0crat is not enough, so I just complemented the impediment saying it was about PR #970.

**Comment by ypshenychka** [comment]
@0crat quality acceptable

**Comment by 0crat** [comment]
Order was finished, quality is "acceptable": +30 point(s) just awarded to @oridan[/z](https://www.0crat.com/u/oridan)

**Comment by 0crat** [comment]
> @0crat quality acceptable ([here](https://github.com/yegor256/takes/issues/406#issuecomment-472560943))

@ypshenychka The project doesn't have enough funds, can't make a payment

**Comment by 0crat** [comment]
Quality review completed: +4 point(s) just awarded to @ypshenychka[/z](https://www.0crat.com/u/ypshenychka)
