### ISSUE TITLE
SSL support?

### ISSUE THREAD

**Issue by georgeyanev** [yegor256/takes#407]
Are there any plans for https support?

**Comment by yegor256** [comment]
@georgeyanev we have to add it, you're right

**Comment by davvd** [comment]
@georgeyanev I will find a developer for the task soon...

**Comment by davvd** [comment]
@georgeyanev milestone set to `1.0` (correct me if I am wrong)

**Comment by georgeyanev** [comment]
It should support both HTTP and HTTPS at the same time. Two different ports maybe.

**Comment by yegor256** [comment]
@georgeyanev yes, you're right, my suggestion above is not correct. This is how your `TkApp` class should look instead:

```
public class Entry {
  public static void main(final String... args) throws IOException {
    Take app = new new TkFork(
      new FkRegex("/robots.txt", ""),
      new FkRegex("/", new TkHTML("hello, world!"))
    );
    new FtBasic(app, 80).start(Exit.NEVER);
    new FtSecure(app, 80, new File("/tmp/certificate.ssl")).start(Exit.NEVER);
  }
}
```

Thus, we have to introduce new class `FtSecure`. Make sense now?

**Comment by yegor256** [comment]
@georgeyanev and, also, we have to teach FtCLI to understand a few new command line arguments:

```
--https=443
--certificate=/tmp/cert
```

Something like this...

**Comment by georgeyanev** [comment]
Yes something like that

**Comment by davvd** [comment]
@bdragan this is your task now, please help. The budget of it is **30 mins**

**Comment by bdragan** [comment]
@georgeyanev PR #425 has been merged to master. The issue can be closed.

**Comment by yegor256** [comment]
@georgeyanev maybe it would be useful to add a sample to README?

**Comment by bdragan** [comment]
@yegor256 I agree, issue #437 created.

**Comment by yegor256** [comment]
@bdragan good for me, ask @georgeyanev to close this ticket

**Comment by davvd** [comment]
@elenavolokhova please, review this task for compliance with our [quality rules](http://www.teamed.io/qa.html)

**Comment by elenavolokhova** [comment]
@bdragan 

> georgeyanev commented 19 days ago
It should support both HTTP and HTTPS at the same time. Two different ports maybe.

> georgeyanev commented 18 days ago
Yes, something like that

 According to our [quality rules](http://www.teamed.io/qa.html):
 > Messages in a ticket always start with a name of a user they are addressed to.
 
 As far as you are the performer of this ticket you are responsible for its quality. Please make sure that everyone follows this rule in your tickets in the future. Ask them to fix issues before closing the ticket.
 
 Please confirm that everything is clear and you have no questions regarding this approach.

**Comment by bdragan** [comment]
@elenavolokhova I confirm.

**Comment by elenavolokhova** [comment]
@davvd Quality is acceptable here.

**Comment by elenavolokhova** [comment]
@bdragan Thank you!

**Comment by davvd** [comment]
> @davvd Quality is acceptable here.

@elenavolokhova thank you, let's try to make it "good" next time

**Comment by davvd** [comment]
@bdragan paied 10 mins to @elenavolokhova for QA review (payment ID is `69523039`); Many thanks! **30 mins** were added to your account in Transaction ID `69523048` (task took 368 hours and 6 mins); added +30 to your rating, now it is equal to [+218](http://www.netbout.com/b/35709?open=rating)
