### ISSUE TITLE
Lombok @EqualsAndHashCode with anonymous classes

### ISSUE THREAD

**Issue by bdragan** [yegor256/takes#408]
We should identify and revisit the occurrences in which we store instances of anonymous classes to fields which are used by Lombok for `equals` and `hashCode` methods generation.

In some cases two equal objects may be considered not equal because the fields being compared are two different instances of anonymous classes which don't provide their own `equals` and `hashCode` methods.

An example of this has been resolved in the issue #120.

**Note**: We should keep in mind that not all objects are equal if all of their fields are equal. For example, if we put two such objects in a `Set` and expect to get both of them from the `Set`, then the objects must not be considered equal in terms of the `equals` and `hashCode` methods.

**Comment by davvd** [comment]
@yegor256 dispatch this issue please, see [par.21](http://www.teamed.io/policy.html#21)

**Comment by yegor256** [comment]
@bdragan which classes you're talking about specifically? The bug reported sounds valid, but we have to be more specific in order to fix it.

**Comment by bdragan** [comment]
@yegor256 The aim of this issue is to identify such classes actually.

I was hesitant to creating the issue because I also found it a bit too broad, but after a discussion with @ekondrashev in the issue #120 I concluded that we should review the other combinations of Lombok `@EqualsAndHashCode` and instances of anonymous classes.

**Comment by yegor256** [comment]
@bdragan it's difficult to define what is "done" in this ticket. What do you expect from the ticket resolver? I mean, how his/her pull request will look?

**Comment by bdragan** [comment]
@yegor256 True, this is more like a code review task. I would expect puzzles and a new issue for the cases that should be fixed. If there are none, then just a comment in this issue by the ticket resolver that he/she did not find any.

**Comment by yegor256** [comment]
@bdragan nah, it's too vague. Let's specify explicitly which objects much be tested for "equalness" and we'll implement that tests. In general, "making code better" - is not a task. We don't want to make it better, we want it to satisfy very specific requirements. This requirement, in this ticket, is not specific enough.

**Comment by ekondrashev** [comment]
@yegor256 I'd suggest to cover with tests classes extending wrapper classes(like TkWrap) and decorate it @EqualsAndHashCode(of = "origin")

**Comment by yegor256** [comment]
@ekondrashev this is a solution, but what is the problem? We have to define the problem first, explicitly, as this article explains: http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html

**Comment by ekondrashev** [comment]
@yegor256 it is more like non manifested problem category. I'd say the problem which has some risk degree. Additionally, what is the problem being solved while covering code with unit tests? I'd say same answer here.

**Comment by bdragan** [comment]
@yegor256 Suppose that we found and fixed some occurrences of `Long` comparison by reference (`long1 == long2`). Also let's assume that such errors are not covered by static code analysis tools. I would say that we should not wait for more bugs to be reported because of that, but rather to take a look at the code base to try to find more occurrences.

One of the approaches to work on this issue could be searching for code like:

```java
@EqualsAndHashCode
class SomeClass { }

SomeClass sc = ...;

Map<SomeClass, Object> map;
map.get(sc);

List<SomeClass> list;
list.contains(sc);

sc.equals(...)
```
or anything else that could be broken by a bad `equals`/`hashCode` methods implementation.

It's up to the issue assignee to find the best way to scan and inspect the code. It is also understandable if some errors are overseen because of the limited time frame for the issue resolution, but we nevertheless lower the risk of the unnoticed cases hiding in the code.

**Comment by paulodamaso** [comment]
@bdragan We will get rid of `lombok` in this project (https://github.com/yegor256/takes/issues/408), so this issue became invalid.

**Comment by 0crat** [comment]
Job `gh:yegor256/takes#408` is not assigned, can't get performer

**Comment by 0crat** [comment]
This job is not in scope
