### ISSUE TITLE
PsFacebook is not tested

### ISSUE THREAD

**Issue by yegor256** [yegor256/takes#41]
There is no unit test for `PsFacebook` class, let's create one. Let's introduce one more ctor, which will accept an instance of `com.jcabi.http.Request` and use it internally like this:

```
this.request.uri().set("https://facebook.com...")
```

This will allow us to test the class.

**Comment by davvd** [comment]
@yegor256 sure, thanks, I added bug tag to it

**Comment by davvd** [comment]
@yegor256 many thanks for the bug report, I added 15 mins to your acc, transaction `000-ad0f549f`

**Comment by davvd** [comment]
@d-molotchko could you please pick this up? This [article](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html) explains how we work. Any technical questions you may ask right here

**30 mins** is the budget of the task. This is exactly how much will be paid when the problem is [solved](http://www.xdsd.org/2014/04/15/definition-of-done.html) (no matter how much time you will actually spend). See [this](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html) for more information

**Comment by d-molotchko** [comment]
@yegor256, I don't understand how to test this class. Should I create one more ctor in PsFacebook with com.jcabi.http.Request parameter and rewrite 'token' function? Where should I  get parameter values for client_id, client_secret, redirect_uri and code? And if I have these values why do I need new ctor?

**Comment by yegor256** [comment]
@d-molotchko yes, I think we should create another ctor which will accept an instance of `Request`. you can use any fake values for all these parameters, I guess

**Comment by d-molotchko** [comment]
@yegor256 Ok, I made two new ctor and seted fake values to parameters. And got exception on user data fetching from Facebook. How to test this without facebook token?

**Comment by yegor256** [comment]
@d-molotchko I believe you have to mock the connection to Facebook. I would suggest to use fake HTTP server from jcabi-http, see http://www.yegor256.com/2014/04/18/jcabi-http-server-mocking.html

**Comment by d-molotchko** [comment]
@yegor256 thanks!

**Comment by davvd** [comment]
@d-molotchko the task is your hands for the last 15 days.. keep in mind that if it's not closed in the next 48 hours, it will be re-assigned to someone else, see [No Obligations](http://www.xdsd.org/2014/04/13/no-obligations-principle.html) principle. [This article](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html) should help if you're stuck

added -30 to your rating, now it is equal to [+60](http://www.netbout.com/b/35168?open=rating)

**Comment by d-molotchko** [comment]
@davvd ok reassign this task to another dev. thanks.

**Comment by yegor256** [comment]
@davvd give this to somebody else pls

**Comment by davvd** [comment]
> @davvd give this to somebody else pls

@yegor256 right, I'll try to find someone else for this task

**Comment by davvd** [comment]
@cyberone this task is for you, keep [these principles](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html) in mind, and don't hesitate to ask any technical questions... Task's budget is **30 mins** (see [this](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html) for explanation)

**Comment by davvd** [comment]
@yegor256 I set milestone here to `1.0`, let me know if it is wrong

**Comment by cyberone** [comment]
@davvd please review https://github.com/yegor256/takes/pull/192

**Comment by cyberone** [comment]
@yegor256 the task is merged. Close please.

**Comment by yegor256** [comment]
@cyberone thanks!

**Comment by davvd** [comment]
@elenavolokhova please, review this ticket for compliance with our [QA rules](http://www.teamed.io/qa.html)

**Comment by elenavolokhova** [comment]
@davvd This issue looks good.

**Comment by davvd** [comment]
> @davvd This issue looks good.

@elenavolokhova thanks a lot :)

**Comment by davvd** [comment]
@cyberone just added 10 mins to @elenavolokhova (for QA), payment ID is `56367945`... Thank you, I have added **1 hour** to your account in payment/transaction "`56367950`", time consumed: 224 hours and 42 mins... there is a bonus for fast delivery (age=2)... added +60 to your rating, now it is equal to [+150](http://www.netbout.com/b/35076?open=rating)
