### ISSUE TITLE
PsFacebook.fetch() uses incorrect field name

### ISSUE THREAD

**Issue by dmzaytsev** [yegor256/takes#410]
PsFacebook.fetch() uses incorrect field name
PsFacebook causes the exception 
```
java.lang.NoSuchFieldError: LATEST
	at org.takes.facets.auth.social.PsFacebook.fetch(PsFacebook.java:165)
	at org.takes.facets.auth.social.PsFacebook.enter(PsFacebook.java:131)
```
see https://github.com/yegor256/netbout/issues/820

**Comment by davvd** [comment]
@dmzaytsev I will find a developer for the task soon...

**Comment by davvd** [comment]
@dmzaytsev I set the milestone to 1.0 since there is nothing set yet

**Comment by davvd** [comment]
@dmzaytsev thanks for reporting! I topped your account for 15 mins, transaction 67817537

**Comment by dmzaytsev** [comment]
@yegor256 can you make this urgent? thanks

**Comment by yegor256** [comment]
@davvd this is urgent, pls

**Comment by davvd** [comment]
> @davvd this is urgent, pls

@yegor256 OK, I put "urgent" label here

**Comment by davvd** [comment]
@bdragan this is your task now, please help. The budget of it is **30 mins**

**Comment by bdragan** [comment]
@dmzaytsev @yegor256 This is not an issue in Takes, it is in Netbout.
netbout-web declares a dependency on restfb 1.6.15, which does not have the `LATEST` field in the [`com.restfb.Version`](http://grepcode.com/file/repo1.maven.org/maven2/com.restfb/restfb/1.6.15/com/restfb/Version.java) class.

**Comment by dmzaytsev** [comment]
@bdragan @yegor256 in this case we have a bug in the Readme instead the code.
if Takes requires a specific dependence then the requirement should be mentioned in the Readme.
Am i right?

**Comment by bdragan** [comment]
@dmzaytsev I agree, all optional dependencies should be clearly stated in the framework documentation.

**Comment by bdragan** [comment]
@dmzaytsev PR #415 has been merged to master. The issue can be closed.

**Comment by dmzaytsev** [comment]
@bdragan thanks!

**Comment by davvd** [comment]
@ypshenychka please, review this ticket for compliance with our [QA rules](http://www.teamed.io/qa.html)

**Comment by ypshenychka** [comment]
@davvd Quality is good.

**Comment by davvd** [comment]
> @davvd Quality is good.

@ypshenychka thank you

**Comment by davvd** [comment]
@bdragan paied 10 mins to @ypshenychka for QA review (payment ID is `68531568`)

**30 mins** added to your account (payment number `68531574`), many thanks for your contribution! 121 hours and 13 mins spent here.

+30 to your rating, your total score is [+203](http://www.netbout.com/b/35709?open=rating)
