### ISSUE TITLE
HmRsHeader.java:46-53: Implement additional constructors. According to...

### ISSUE THREAD

**Issue by davvd** [yegor256/takes#412]
Puzzle `260-1c71c6a2` in `src/main/java/org/takes/facets/hamcrest/HmRsHeader.java:46-53` has to be resolved: Implement additional constructors. According to #260 there should be also available such constructors public HmRsHeader(final Matcher

? extends Map.Entry

> mtchr); public HmRsHeader(final String header, final Matcher

? extends Iterable

> mtchr); public HmRsHeader(final String header, final Matcher

? extends String

mtchr); public HmRsHeader(final String header, final String value);... The puzzle was created by Eugene Kondrashev on 1-Oct-2015.

If you have any technical questions, don't ask me, submit new tickets instead

**Comment by davvd** [comment]
@yegor256 milestone set to `1.0` (correct me if I am wrong)

**Comment by davvd** [comment]
@bdragan please go ahead with this task, it's yours

**Comment by bdragan** [comment]
@davvd PR #434 has been merged.

**Comment by davvd** [comment]
> @davvd PR #434 has been merged.

@bdragan thanks

**Comment by davvd** [comment]
@yegor256 It is closed now

**Comment by davvd** [comment]
@elenavolokhova please, review this ticket for compliance with our [QA rules](http://at.teamed.io/qa.html)

**Comment by elenavolokhova** [comment]
@davvd Looks good!

**Comment by davvd** [comment]
> @davvd Looks good!

@elenavolokhova thanks for the review and a good remark

**Comment by davvd** [comment]
@bdragan I added 10 mins to @elenavolokhova (for QA review) in transaction 69643156; Thank you, I have added **30 mins** to your account in payment/transaction "`69643161`", time consumed: 334 hours and 6 mins; added +30 to your rating, now it is equal to [+331](http://www.netbout.com/b/35709?open=rating)
