### ISSUE TITLE
HmRqHeader.java:45-52: Implement additional constructors. According to...

### ISSUE THREAD

**Issue by davvd** [yegor256/takes#413]
Puzzle `260-de67913e` in `src/main/java/org/takes/facets/hamcrest/HmRqHeader.java:45-52` has to be resolved: Implement additional constructors. According to #260 there should be also available such constructors: public HmRsHeader(final Matcher

? extends Map.Entry

> mtchr); public HmRsHeader(final String header, final Matcher

? extends Iterable

> mtchr); public HmRsHeader(final String header, final Matcher

? extends String

mtchr); public HmRsHeader(final String header, final String value);... The puzzle was created by Eugene Kondrashev on 1-Oct-2015.

If you have any technical questions, don't ask me, submit new tickets instead

**Comment by davvd** [comment]
@yegor256 since there is no milestone yet I set it to "1.0"

**Comment by davvd** [comment]
@prondzyn the task is yours please proceed

**Comment by prondzyn** [comment]
@davvd I started work on the task, but there were some inconsistencies so I asked about resolving them in [260#issuecomment-152758204](https://github.com/yegor256/takes/issues/260#issuecomment-152758204). I'm blocked and waiting on the decision.

**Comment by davvd** [comment]
> @davvd I started work on the task, but there were some inconsistencies so I asked about resolving them in [260#issuecomment-152758204](https://github.com/yegor256/takes/issues/260#issuecomment-152758204). I'm blocked and waiting on the decision.

@prondzyn sure, let's wait for #260

**Comment by prondzyn** [comment]
@davvd please find someone else. Thanks.

**Comment by davvd** [comment]
> @davvd please find someone else. Thanks.

@prondzyn I deducted 30 points from your rating

**Comment by davvd** [comment]
> @davvd please find someone else. Thanks.

@prondzyn right, I will find someone else, no problem

**Comment by davvd** [comment]
@bdragan please proceed, it's yours

**Comment by bdragan** [comment]
@davvd PR #440 has been merged.

**Comment by davvd** [comment]
> @davvd PR #440 has been merged.

@bdragan thanks

**Comment by davvd** [comment]
@yegor256 Thanks, closing it now.

**Comment by davvd** [comment]
@ypshenychka please, review this issue for QA compliance, as per [par.24](http://at.teamed.io/policy.html#24)

**Comment by ypshenychka** [comment]
@davvd Quality is good.

**Comment by davvd** [comment]
> @davvd Quality is good.

@ypshenychka thanks for the review

**Comment by davvd** [comment]
@bdragan added 10 mins to @ypshenychka, for QA review, payment code is `70171877`

I just added **30 mins** to your account, many thanks for your contribution (70171882).. 117 hours and 33 mins spent here

+30 added to your rating, current score is: [+391](http://www.netbout.com/b/35709?open=rating)
