### ISSUE TITLE
BkReuseTest.java:50-53: Replace mockito statements with fake...

### ISSUE THREAD

**Issue by davvd** [yegor256/takes#417]
Puzzle `306-07904f4e` in `src/test/java/org/takes/http/BkReuseTest.java:50-53` has to be resolved: Replace mockito statements with fake sockets objects as described in http://www.yegor256.com/2014/09/23/built-in-fake-objects.html. Fake objects should improve tests readability and maintainability in the future.... The puzzle was created by Piotr Pradzynski on 25-Oct-2015.

If you have any technical questions, don't ask me, submit new tickets instead

**Comment by davvd** [comment]
@yegor256 I set the milestone to 1.0 since there is nothing set yet

**Comment by davvd** [comment]
@prondzyn the task is yours please proceed

**Comment by prondzyn** [comment]
@davvd PR #426 prepared

**Comment by davvd** [comment]
> @davvd PR #426 prepared

@prondzyn OK thanks

**Comment by prondzyn** [comment]
@davvd PR merged. Please close the ticket.

**Comment by davvd** [comment]
@yegor256 Closed, thanks all

**Comment by davvd** [comment]
@elenavolokhova please, review this task for compliance with our [quality rules](http://www.teamed.io/qa.html)

**Comment by elenavolokhova** [comment]
@davvd Looks good!

**Comment by davvd** [comment]
> @davvd PR merged. Please close the ticket.

@prondzyn sure, closed already

**Comment by davvd** [comment]
> @davvd Looks good!

@elenavolokhova many thanks

**Comment by davvd** [comment]
@prondzyn added 10 mins to @elenavolokhova, for QA review, payment code is `69560669`

thanks, paid, **30 mins** to your account, payment ID is `AP-29C98531Y9369412W`, task took 195 hours and 33 mins to complete

added +30 to your rating, now it is equal to [+75](http://www.netbout.com/b/35715?open=rating)

**Comment by HDouss** [comment]
@prondzyn  I am working on #418. I think last commit ce74f15 is not Ok. I don't see the relation between the socket and the (mocked) container. I was expecting the unit test plays client role, and BkReuse plays server role. The container seems playing server role, and made to reply with an answer I expected to be the client request.
Should I open an issue for rewriting unit test ?

**Comment by prondzyn** [comment]
@HDouss check the original issue #306 and related information. Maybe it will help you.

**Comment by HDouss** [comment]
@prondzyn thanks for replying. I checked all related context. May be my question was not clear. It was specific on the implementation of the  unit test.

**Comment by HDouss** [comment]
@prondzyn In short, I think the unit test is incorrect. In the three coded tests `BkReuse` is accepting a socket with no inputstream.
