### ISSUE TITLE
BkReuseTest.java:46-49: Implement missing BkReuse.accept method to...

### ISSUE THREAD

**Issue by davvd** [yegor256/takes#418]
Puzzle `306-0f8af5fd` in `src/test/java/org/takes/http/BkReuseTest.java:46-49` has to be resolved: Implement missing BkReuse.accept method to support HTTP persistent connections and to pass below three tests. BkReuse.accept should handles more than one HTTP requests in one connection and return correct HTTP status when Content-Length is not specified.... The puzzle was created by Piotr Pradzynski on 22-Oct-2015.

If you have any technical questions, don't ask me, submit new tickets instead

**Comment by davvd** [comment]
@yegor256 attached this issue to milestone "1.0" (let me know if this is wrong)

**Comment by davvd** [comment]
@prondzyn the task is yours, please go ahead

**Comment by prondzyn** [comment]
@davvd please find someone else. Thanks.

**Comment by davvd** [comment]
> @davvd please find someone else. Thanks.

@prondzyn -30 points to your rating

**Comment by davvd** [comment]
> @davvd please find someone else. Thanks.

@prondzyn got it, someone else will be assigned soon

**Comment by davvd** [comment]
@hdouss it's yours now, please proceed keeping in mind [our principles](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html). Feel free to ask any technical questions right here in the ticket

The budget of this task is **30 mins**. This is exactly how much time will be compensated, when the task is completed. Read about our [Definition of Done](http://www.xdsd.org/2014/04/15/definition-of-done.html)

**Comment by HDouss** [comment]
@davvd : I am a little confused about the test methods. I don't see (or I don't understand) the relation between the socket and the (mocked) container. I was expecting the unit test plays client role, and BkReuse plays server role. I may be wrong but the container seems playing server role, and made to reply with an answer I expected to be the client request.

**Comment by HDouss** [comment]
@davvd : should I open an issue for rewriting unit test ?

**Comment by HDouss** [comment]
@davvd I don't know if it is a requirement that `BkReuse` should decorate another `Back`.
Before delegating the process of the socket to the underlying Back, `BkReuse` should definitely read from the socket input stream and process some of the headers.
There is no way to reposition the socket input stream to be (correctly) processed again by the underlying Back.

**Comment by davvd** [comment]
> @davvd : I am a little confused about the test methods. I don't see (or I don't understand) the relation between the socket and the (mocked) container. I was expecting the unit test plays client role, and BkReuse plays server role. I may be wrong but the container seems playing server role, and made to reply with an answer I expected to be the client request.

@hdouss check this out: http://www.yegor256.com/2015/02/16/it-is-not-a-school.html

**Comment by davvd** [comment]
> @davvd : I think last commit `#417 - improving tests to use jcabi http	ce74f15` is not Ok. Should I open an issue for rewriting unit test ?

@hdouss address technical questions to the author of the ticket

**Comment by HDouss** [comment]
@davvd My two comments are related. I will ask the question on #417.

**Comment by davvd** [comment]
> @davvd My two comments are related. I will ask the question on #417.

@hdouss OK, sure

**Comment by HDouss** [comment]
@davvd I ask more time as I am waiting for an answer on #417 and an answer on :
>@davvd I don't know if it is a requirement that BkReuse should decorate another Back.
>Before delegating the process of the socket to the underlying Back, BkReuse should definitely read from the socket input stream and process some of the headers.
>There is no way to reposition the socket input stream to be (correctly) processed again by the underlying Back.

**Comment by davvd** [comment]
@hdouss the ticket is with you for 15 days already. If it is not finished in the next 48 hours, it will be re-assigned to someone else, see [No Obligations](http://www.xdsd.org/2014/04/13/no-obligations-principle.html) principle, [this article](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html) should help if you're stuck... as a reminder, don't forget to remove the `@todo` puzzle from the source code... -30 added to your rating, current score is: [+0](http://www.netbout.com/b/36032?open=rating)

**Comment by HDouss** [comment]
@davvd please note my last comment. I asked for more time, I think a redesign is required and I am waiting for replies.

**Comment by davvd** [comment]
> @davvd please note my last comment. I asked for more time, I think a redesign is required and I am waiting for replies. 

@hdouss sure, thanks for telling me, take your time

**Comment by HDouss** [comment]
@davvd please revoke my rating and answer my redesign question.

**Comment by yegor256** [comment]
@HDouss please, check these two articles: http://www.yegor256.com/2015/02/16/it-is-not-a-school.html and http://www.yegor256.com/2015/01/15/how-to-cut-corners.html Basically, if something is not clear it's either your problem and you should solve it on your own, or it's a problem of the project and you should report it. Nobody will help you here.

**Comment by HDouss** [comment]
@davvd I can't continue until #456 is resolved.

**Comment by davvd** [comment]
> @davvd I can't continue until #456 is resolved.

@hdouss yes, right, let's wait for #456

**Comment by davvd** [comment]
@yegor256 #456 is closed, it was an impediment

**Comment by HDouss** [comment]
@davvd I am still waiting for #454 here.

**Comment by davvd** [comment]
> @davvd I am still waiting for #454 here.

@hdouss agreed, we'll wait for #454

**Comment by davvd** [comment]
@yegor256 The issue is closed

**Comment by davvd** [comment]
@ypshenychka please, let us know what do you think about this ticket, according to our [QA rules](http://at.teamed.io/qa.html)

**Comment by HDouss** [comment]
@davvd This issue is not resolved yet. The puzzle description have just moved from `BkReuseTest` to `BkBasicTest` because `BkReuseTest` is deleted and we get rid of it. But the issue is still unresolved.

**Comment by HDouss** [comment]
@davvd The puzzle here is the same as in #519. It was just moved. I worked on this issue for a long time, so why closing it and open another (same) one ?

**Comment by HDouss** [comment]
@yegor256 Could you please help here ?

**Comment by HDouss** [comment]
@davvd Ping
>@davvd The puzzle here is the same as in #519. It was just moved. I worked on this issue for a long time, so why closing it and open another (same) one ?

**Comment by yegor256** [comment]
@HDouss it looks like the puzzle is gone and a new one showed up. you can check `PUZZLES.md` file in the root directory for a full list of puzzles currently active. yours is there?

**Comment by HDouss** [comment]
@yegor256 It is gone because BkReuseTest class was removed, but the issue is still here.

**Comment by yegor256** [comment]
@HDouss so, this issue will be fixed in a new ticket. we work with micro-tasks, remember that. we can't solve all together in one ticket. if the puzzle is gone, the problem is gone. period.

**Comment by HDouss** [comment]
@yegor256 This puzzle is not gone. he has just "moved" (and somehow reformulated) from BkReuseTest to BkBasicTest.

**Comment by yegor256** [comment]
@HDouss that's the thing - if it's "reformulated", it's a different puzzle. our puzzle detecting software can't understand whether it's the same problem or a different one. it only checks the text.

**Comment by HDouss** [comment]
@yegor256 Ok. Let's forget about it.

**Comment by ypshenychka** [comment]
@HDouss So will there be a related fix in scope of this ticket?

**Comment by HDouss** [comment]
@ypshenychka No, I don't think it has any sens.

**Comment by ypshenychka** [comment]
@HDouss got it. Thanks.

**Comment by ypshenychka** [comment]
@davvd Quality is bad here.

**Comment by davvd** [comment]
> @davvd Quality is bad here.

@ypshenychka thank you for paying attention

**Comment by davvd** [comment]
@hdouss 10 mins was added to the account of @ypshenychka (for QA review), in transaction 75134863
