### ISSUE TITLE
PsGithub is not tested

### ISSUE THREAD

**Issue by yegor256** [yegor256/takes#42]
There is no unit test for `PsGithub` class, let's create one. Let's introduce one more ctor, which will accept an instance of `com.jcabi.http.Request` and use it internally like this:

```
this.request.uri().set("https://githug.com...")
```

This will allow us to test the class.

**Comment by davvd** [comment]
@yegor256 thanks, I added the "bug" tag

**Comment by davvd** [comment]
@yegor256 thank you for reporting this, I added 15 mins to your acc, transaction `000-24fe2df1`

**Comment by davvd** [comment]
@nathansgreen it's yours,please go ahead

**Comment by davvd** [comment]
@nathansgreen this task is in your hands for 15 days already... -30 added to your rating, at the moment it is: [+0](http://www.netbout.com/b/35107?open=rating)

**Comment by davvd** [comment]
@nathansgreen the task is overdue, and I have to re-assign it to someone else. Please, stop working with it immediately. In general, we're against overdue tasks, check [this page](http://www.xdsd.org/2014/04/13/no-obligations-principle.html). added -60 to your rating, now it is equal to [-270](http://www.netbout.com/b/35107?open=rating)

**Comment by davvd** [comment]
@cyberone can you please help? Keep in mind [this](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html). If you have any technical questions, don't hesitate to ask right here. The budget here is **30 mins**, which is exactly how much time will be paid for, when the task is [completed](http://www.xdsd.org/2014/04/15/definition-of-done.html)

**Comment by cyberone** [comment]
@davvd assign someone else for this task please.

**Comment by ikhvostenkov** [comment]
@davvd @yegor256  I can take this test due to this will be similar to ```PsLinkedinTest``` I am working on now. Also I want to suggest some refactoring for productive code and if you accept this it will be possible to create these tests like piece of cake.

**Comment by davvd** [comment]
> @davvd assign someone else for this task please. 

@cyberone I deducted 30 points from your rating

**Comment by davvd** [comment]
> @davvd assign someone else for this task please. 

@cyberone no problem, I will try to find somebody else

**Comment by davvd** [comment]
@dmzaytsev the task is yours please proceed

**Comment by dmzaytsev** [comment]
@yegor256 PsGithub requires two `com.jcabi.http.Request` instances  for the token and for the user data. I suggest to create a decorator for the `com.jcabi.http.FackRequest` which
returns different instances of the RequestBody depending on the url.
What do you think about the suggestion ?

**Comment by yegor256** [comment]
@dmzaytsev yes, sounds logical

**Comment by dmzaytsev** [comment]
@yegor256 I think will be better to add new methods to `com.jcabi.http.requestFakeRequest`
```
    public FakeRequest withBody(final String regexp, final String text) {
    }

    public FakeRequest withBody(final String regexp, final byte[] body) {
    } 
```

I could do it in [jcabi-http project](https://github.com/jcabi/jcabi-http)
I will create new task in jcabi-http if you do not mind. 
Could you please assign me to this task?

**Comment by yegor256** [comment]
@dmzaytsev yes, go ahead

**Comment by dmzaytsev** [comment]
@davvd we are wating for jcabi/jcabi-http#82

**Comment by yegor256** [comment]
@davvd we need more time here

**Comment by davvd** [comment]
> @davvd we need more time here

@yegor256 yes, take your time, thanks for letting me know

**Comment by dmzaytsev** [comment]
@davvd we are waiting for #253

**Comment by davvd** [comment]
> @davvd we are waiting for #253 

@dmzaytsev yes, waiting for #253

**Comment by dmzaytsev** [comment]
@yegor256 maybe will be better to mark `@ignore` RqMultipartTest.consumesHttpRequest?
until the bug will be fixed

**Comment by yegor256** [comment]
@dmzaytsev you're right, see 77e785e

**Comment by dmzaytsev** [comment]
@yegor257 the PR #228 has been merged. Please close the task

**Comment by yegor256** [comment]
@dmzaytsev thanks!

**Comment by davvd** [comment]
@elenavolokhova please, review this ticket for compliance with our [QA rules](http://www.teamed.io/qa.html)

**Comment by elenavolokhova** [comment]
@davvd Quality is good here.

**Comment by davvd** [comment]
> @davvd Quality is good here.

@elenavolokhova thanks a lot :)

**Comment by davvd** [comment]
@dmzaytsev 10 mins was added to the account of @elenavolokhova (for QA review), in transaction 56893949. I just added **1 hour** to your account, many thanks for your contribution.. 56893952 spent here. age=2 mins, that's why a bonus here for fast delivery. added +60 to your rating, now it is equal to [+1355](http://www.netbout.com/b/35166?open=rating)
