### ISSUE TITLE
RqOnce

### ISSUE THREAD

**Issue by yegor256** [yegor256/takes#420]
Let's create a new wrapper of `Request`, which will make this code invalid:

```java
Request req = new RqOnce(req);
req.body();
req.body(); // exception here
```

Only one time we can call `body()`. All other calls will lead to runtime exception.

**Comment by davvd** [comment]
@yegor256 tagged this issue with "bug"

**Comment by davvd** [comment]
@yegor256 I set the milestone to 1.0 since there is nothing set yet

**Comment by davvd** [comment]
@yegor256 thank you for the ticket reported, I topped your account for 15 mins, transaction `000-f3b572c7`

**Comment by yegor256** [comment]
@rultor release, tag is `0.26`

**Comment by yegor256** [comment]
@rultor release, tag is `0.26`

**Comment by yegor256** [comment]
@rultor release, tag is `0.26`
