### ISSUE TITLE
PsGoogle is not tested

### ISSUE THREAD

**Issue by yegor256** [yegor256/takes#43]
There is no unit test for `PsGoogle` class, let's create one. Let's introduce one more ctor, which will accept an instance of `com.jcabi.http.Request` and use it internally like this:

```
this.request.uri().set("https://google.com...")
```

This will allow us to test the class.

**Comment by davvd** [comment]
@yegor256 right, I added the `bug` tag

**Comment by davvd** [comment]
@yegor256 many thanks for the report, I topped your account for 15 mins, transaction 000-6e853aaa

**Comment by davvd** [comment]
@nathansgreen it's yours, please go ahead

**Comment by davvd** [comment]
@nathansgreen you're working with this issue for 15 days already

-30 added to your rating, current score is: [+45](http://www.netbout.com/b/35107?open=rating)

**Comment by davvd** [comment]
@nathansgreen this task is taking too long, I have to change the performer, sorry. Please stop working with it right now. See our [no obligations](http://www.xdsd.org/2014/04/13/no-obligations-principle.html) principle... -60 added to your rating, current score is: [-180](http://www.netbout.com/b/35107?open=rating)

**Comment by davvd** [comment]
@lauresh please go ahead, it's your task now, keep [this](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html) in mind, and don't hesitate to ask any technical questions you may have... This task's budget is **30 mins**. This is exactly how much will be paid when the problem explained above is solved. See [this](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html) for more information

**Comment by davvd** [comment]
@lauresh you're holding this ticket for 15 days already. If it is not finished (and closed) in the next 48 hours, it will be re-assigned to someone else, see [No Obligations](http://www.xdsd.org/2014/04/13/no-obligations-principle.html) principle ([this article](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html) should help if you're stuck)... -30 to your rating, your total score is [-30](http://www.netbout.com/b/35288?open=rating)

**Comment by yegor256** [comment]
@davvd what is the status here?

**Comment by davvd** [comment]
@dmzaytsev it's yours, please go ahead

**Comment by dmzaytsev** [comment]
@yegor256 the PR #270  has been merged. Could you close the task please ?

**Comment by yegor256** [comment]
@dmzaytsev thanks!

**Comment by davvd** [comment]
@elenavolokhova please, review this task for compliance with our [quality rules](http://www.teamed.io/qa.html)

**Comment by elenavolokhova** [comment]
@davvd Quality is good here.

**Comment by davvd** [comment]
> @davvd Quality is good here.

@elenavolokhova thanks!

**Comment by davvd** [comment]
@dmzaytsev 10 mins was added to the account of @elenavolokhova (for QA review), in transaction 57245467. thanks, I just added **38 mins** to your account, payment `57245478`, 53 hours and 13 mins spent. the bonus for fast delivery (m=3193). +38 to your rating, your total score is [+1438](http://www.netbout.com/b/35166?open=rating)
