### ISSUE TITLE
TkRetry

### ISSUE THREAD

**Issue by yegor256** [yegor256/takes#430]
Let's create a new decorator `TkRetry`, which will not fail immediately on `IOException`, but will retry a few times:

```java
new TkRetry(
  original_take,
  3, // how many times to retry, maximum
  30 // initial delay between retries, in milliseconds
);
```

**Comment by davvd** [comment]
@yegor256 I added `bug` tag to this ticket

**Comment by davvd** [comment]
@yegor256 I set the milestone to 1.0 since there is nothing set yet

**Comment by davvd** [comment]
@yegor256 many thanks, **15 mins** added to your acc for reporting this bug, pmt ID `000-1e62e95a`

**Comment by davvd** [comment]
@aschworer This task is yours, please go ahead keeping in mind [this](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html). If any questions, don't hesitate to ask right here; **30 mins** is the budget of the task. This is exactly how much will be paid when the problem is [solved](http://www.xdsd.org/2014/04/15/definition-of-done.html) (no matter how much time you will actually spend). See [this](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html) for more information

**Comment by aschworer** [comment]
@davvd i've created a pull request, please review

**Comment by davvd** [comment]
> @davvd i've created a pull request, please review

@aschworer thanks

**Comment by davvd** [comment]
@aschworer you're holding this ticket for 15 days already. If it is not finished (and closed) in the next 48 hours, it will be re-assigned to someone else, see [No Obligations](http://www.xdsd.org/2014/04/13/no-obligations-principle.html) principle ([this article](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html) should help if you're stuck); -30 to your rating, your total score is [-30](http://www.netbout.com/b/35983?open=rating)

**Comment by aschworer** [comment]
@davvd It's been 34 hours we are waiting for the merge confirm from @yegor256 (pull request #472).

**Comment by davvd** [comment]
> @davvd It's been 34 hours we are waiting for the merge confirm from @yegor256 (pull request #472).

@aschworer it doesn't really matter, check this: http://at.teamed.io/policy.html#7 If you can't complete your task in time, inform me, see http://at.teamed.io/policy.html#10

**Comment by davvd** [comment]
@aschworer you've been working with this task for too long. I'm sorry, but I'll assign someone else. Please stop working with it. See our [no obligations](http://www.xdsd.org/2014/04/13/no-obligations-principle.html) principle; added -60 to your rating, now it is equal to [-90](http://www.netbout.com/b/35983?open=rating)

**Comment by davvd** [comment]
@hdouss the task is yours, please go ahead

**Comment by aschworer** [comment]
@davvd it is done and waiting for merge confirm for the past 7 days

**Comment by HDouss** [comment]
@davvd PR #493 reviewed and ready for merge. We wait for the architect to confirm the merge here.

**Comment by davvd** [comment]
> @davvd it is done and waiting for merge confirm for the past 7 days

@aschworer the task is "done" when it's closed by its author. this task is not done. when @yegor256 closes it, I will consider it done. see http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html

**Comment by HDouss** [comment]
@yegor256 PR #493 reviewed and merged. Please close the issue.

**Comment by yegor256** [comment]
@HDouss thanks!

**Comment by yegor256** [comment]
@rultor release, tag is `0.30`

**Comment by HDouss** [comment]
@davvd Issue closed.

**Comment by davvd** [comment]
@ypshenychka please, review this task for compliance with our [quality rules](http://at.teamed.io/qa.html)

**Comment by ypshenychka** [comment]
@davvd Quality is good.

**Comment by davvd** [comment]
> @davvd Quality is good.

@ypshenychka thanks a lot :)

**Comment by davvd** [comment]
@hdouss just added 10 mins to @ypshenychka (for QA), payment ID is `74105723`. Much appreciated! **30 mins** was added to your account, payment ID `74105742`, time spent is 211 hours and 6 mins. +30 to your rating, your total score is [+804](http://www.netbout.com/b/36032?open=rating)
