### ISSUE TITLE
PsGoogle doesn't give the user's photo

### ISSUE THREAD

**Issue by dmzaytsev** [yegor256/takes#431]
PsGoogle doesn't give the user's photo because it uses API call that not supported anymore.
I guess valid way to get a user's photo can be found here https://developers.google.com/+/web/api/rest/latest/people/get

also it possible to try  API call online

![image](https://cloud.githubusercontent.com/assets/9972909/10968802/aad60ccc-83e5-11e5-8dfa-62dcd11b8ccf.png)

**Comment by davvd** [comment]
@dmzaytsev I will ask someone to take care of this task soon

**Comment by davvd** [comment]
@dmzaytsev I set milestone here to `1.0`, let me know if it is wrong

**Comment by davvd** [comment]
@dmzaytsev thank you for the ticket reported, I topped your account for 15 mins, transaction `69049799`

**Comment by davvd** [comment]
@xupyprmv it's yours now, please proceed keeping in mind [our principles](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html). Feel free to ask any technical questions right here in the ticket; **30 mins** is the budget of the task. This is exactly how much will be paid when the problem is [solved](http://www.xdsd.org/2014/04/15/definition-of-done.html) (no matter how much time you will actually spend). See [this](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html) for more information

**Comment by xupyprmv** [comment]
@davvd assign another developer to this issue. I cannot reproduce this issue.

**Comment by davvd** [comment]
> @davvd assign another developer to this issue. I cannot reproduce this issue.

@xupyprmv -30 points to your rating

**Comment by davvd** [comment]
> @davvd assign another developer to this issue. I cannot reproduce this issue.

@xupyprmv no problem, I will try to find somebody else

**Comment by davvd** [comment]
@happy-neko can you please help? Keep in mind [this](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html). If you have any technical questions, don't hesitate to ask right here. The cost of this task is **30 mins** (this is exactly how much will be paid, not less not more), when the task is [done](http://www.xdsd.org/2014/04/15/definition-of-done.html)

**Comment by Happy-Neko** [comment]
@david PR is merged. We could close this ticker.

**Comment by dmzaytsev** [comment]
@Happy-Neko ask the ticket reporter

**Comment by dmzaytsev** [comment]
Thanks!

**Comment by dmzaytsev** [comment]
And mention PR number

**Comment by Happy-Neko** [comment]
@dmzaytsev PR #476 is merged. We could close the ticket.

**Comment by davvd** [comment]
@ypshenychka please, review this issue for QA compliance, as per [par.24](http://at.teamed.io/policy.html#24)

**Comment by ypshenychka** [comment]
@dmzaytsev 
>dmzaytsev commented a day ago
Thanks!

According to our [QA Rules](http://www.teamed.io/qa.html):
>Messages in a ticket always start with a name of a user they are addressed to.

Please correct your message by indicating an addressee in the beginning.

**Comment by dmzaytsev** [comment]
@ypshenychka done

**Comment by ypshenychka** [comment]
@dmzaytsev Thanks.

**Comment by ypshenychka** [comment]
@davvd Quality is acceptable.

**Comment by davvd** [comment]
> @davvd Quality is acceptable.

@ypshenychka thank you, let's try to make it "good" next time

**Comment by davvd** [comment]
@happy-neko added 10 mins to @ypshenychka, for QA review, payment code is `73018818`... Much obliged! I have added **38 mins** to your account in payment "73018821", 70 hours and 19 mins spent... the bonus for fast delivery (m=4219)... +38 added to your rating, current score is: [+68](http://www.netbout.com/b/36136?open=rating)
