### ISSUE TITLE
TkFallback crashes when there is no fallback

### ISSUE THREAD

**Issue by yegor256** [yegor256/takes#433]
This code:

```java
new TkFallback(
  new TkFailure(),
  new FbChain()
).act(new RqEmpty());
```

Will fail with a runtime exception, with an unclear description. But it should not. Instead, it should throw, but the exception must have a proper explanation. Something like "there is no fallback available, the original problem is this:..."

**Comment by davvd** [comment]
@yegor256 added "bug" tag to this issue

**Comment by davvd** [comment]
@yegor256 attached this issue to milestone "1.0" (let me know if this is wrong)

**Comment by davvd** [comment]
@yegor256 thanks for reporting! I topped your account for 15 mins, transaction 000-cb493e62

**Comment by HDouss** [comment]
@yegor256 please assign this to me

**Comment by davvd** [comment]
@mojojojo the task is for you now, follow [these guidelines](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html). Don't hesitate to ask any technical questions right here

Task's budget is **30 mins** (see [this](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html) for explanation)

**Comment by davvd** [comment]
@mojojojo you're working with this ticket for the last 15 days. If it is not closed within the next 48 hours, it will be re-assigned to someone else, see [No Obligations](http://www.xdsd.org/2014/04/13/no-obligations-principle.html) principle. [This article](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html) should help if you're stuck... -30 added to your rating, at the moment it is: [-30](http://www.netbout.com/b/36003?open=rating)

**Comment by davvd** [comment]
@aschworer this task is for you, keep [these principles](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html) in mind, and don't hesitate to ask any technical questions; Budget here is **30 mins** (keep [this principle](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html) in mind)

**Comment by aschworer** [comment]
@davvd @yegor256 It's been a week I waited for the merge confirm for the tasks #458 and #430 which have been completed on 26th December. The merges have not been confirmed therefore causing me to fail to close the task. Now my rating is -90. Before committing for any new task, I would like to know if this kind of situation is usual, because I need to know how to plan my work and my time. It is said, that normal time is 7 days. If this means that I need to complete my work on the first 6 hours after the task has been assigned to me, because I may wait for it to close for the next 7 days, I'm not sure that it is the same as what is written in the Work Policy. Please reassign this task to someone else if you are not able to answer my question.

**Comment by davvd** [comment]
> @davvd @yegor256 It's been a week I waited for the merge confirm for the tasks #458 and #430 which have been completed on 26th December. The merges have not been confirmed therefore causing me to fail to close the task. Now my rating is -90. Before committing for any new task, I would like to know if this kind of situation is usual, because I need to know how to plan my work and my time. It is said, that normal time is 7 days. If this means that I need to complete my work on the first 6 hours after the task has been assigned to me, because I may wait for it to close for the next 7 days, I'm not sure that it is the same as what is written in the Work Policy. Please reassign this task to someone else if you are not able to answer my question.

@aschworer keep in mind that it's your responsibility to manage your tickets. if you can't complete them in time, you have to notify me. why you can't complete - doesn't matter. if you want me to reassign this task, let me know.

**Comment by aschworer** [comment]
@davvd please reassign this task to someone else.

**Comment by davvd** [comment]
> @davvd please reassign this task to someone else.

@aschworer -30 points to your rating :(

**Comment by davvd** [comment]
> @davvd please reassign this task to someone else.

@aschworer I will try to find someone else

**Comment by davvd** [comment]
@danff please go ahead, it's your task now, keep [this](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html) in mind, and don't hesitate to ask any technical questions you may have

This task's budget is **30 mins**. This is exactly how much will be paid when the problem explained above is solved. See [this](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html) for more information

**Comment by danff** [comment]
@davvd Need more time here

**Comment by davvd** [comment]
> @davvd Need more time here

@danff agreed, take your time

**Comment by danff** [comment]
@yegor256 The PR was merged. Can the ticket be reviewed and closed?

**Comment by yegor256** [comment]
@danff thanks!

**Comment by yegor256** [comment]
@rultor release, tag is `0.31.1`

**Comment by yegor256** [comment]
@rultor release, tag is `0.31.1`

**Comment by davvd** [comment]
@ypshenychka please, review this ticket for compliance with our [QA rules](http://at.teamed.io/qa.html)

**Comment by ypshenychka** [comment]
@danff 
According to our [QA Rules](http://www.teamed.io/qa.html):
>Some of ticket messages must mention all pull requests where the problem was actually fixed.

Please provide a link to corresponding PR in any of your messages.

**Comment by danff** [comment]
@ypshenychka Sure. PR #525 has been created for this ticket and merged.

**Comment by ypshenychka** [comment]
@danff Thank you.

**Comment by ypshenychka** [comment]
@davvd Quality is acceptable.

**Comment by davvd** [comment]
> @davvd Quality is acceptable.

@ypshenychka thank you, let's try to make it "good" next time

**Comment by davvd** [comment]
@danff 10 mins was added to the account of @ypshenychka (for QA review), in transaction 75241353... I just added **30 mins** to your account, many thanks for your contribution (AP-4FK41357G3450951H).. 356 hours and 38 mins spent here... +30 to your rating, your total score is [+30](http://www.netbout.com/b/36198?open=rating)
