### ISSUE TITLE
Failing integration tests don't make the build to fail

### ISSUE THREAD

**Issue by bdragan** [yegor256/takes#436]
1. Change the assertions in an `AppITCase` test method so that the test will fail.
2. Trigger the tests: `mvn clean install -Pqulice`.

**Current:** The test failure is logged, but the build succeeds.

**Desired:** The build should fail.

**Comment by yegor256** [comment]
@bdragan that's how Maven works. try `mvn install` and the build will fail.

**Comment by bdragan** [comment]
@yegor256 I tried it, `mvn install` succeeds as well. Please reopen the issue.
Log excerpt:
```
[INFO] Running org.takes.it.fm.AppITCase
[INFO] Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 0.011 sec <<< FAILURE! - in org.takes.it.fm.AppITCase
[INFO] justWorks(org.takes.it.fm.AppITCase)  Time elapsed: 0.011 sec  <<< ERROR!
[INFO] java.net.MalformedURLException: For input string: "null"
[INFO] 	at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
[INFO] 	at java.lang.Integer.parseInt(Integer.java:492)
[INFO] 	at java.lang.Integer.parseInt(Integer.java:527)
[INFO] 	at java.net.URLStreamHandler.parseURL(URLStreamHandler.java:217)
[INFO] 	at java.net.URL.<init>(URL.java:618)
[INFO] 	at java.net.URL.<init>(URL.java:486)
[INFO] 	at java.net.URL.<init>(URL.java:435)
[INFO] 	at com.jcabi.http.request.JdkRequest$1.send(JdkRequest.java:88)
[INFO] 	at com.jcabi.http.wire.VerboseWire.send(VerboseWire.java:90)
[INFO] 	at com.jcabi.http.request.BaseRequest.fetchResponse(BaseRequest.java:299)
[INFO] 	at com.jcabi.http.request.BaseRequest.fetch(BaseRequest.java:214)
[INFO] 	at org.takes.it.fm.AppITCase.justWorks(AppITCase.java:54)
[INFO] 
[INFO] 
[INFO] Results :
[INFO] 
[INFO] Tests in error: 
[INFO]   AppITCase.justWorks:54 » MalformedURL For input string: "null"
[INFO] 
[INFO] Tests run: 1, Failures: 0, Errors: 1, Skipped: 0
[INFO] 
[INFO] [INFO] ------------------------------------------------------------------------
[INFO] [INFO] BUILD SUCCESS
[INFO] [INFO] ------------------------------------------------------------------------
[INFO] [INFO] Total time: 9.939 s
[INFO] [INFO] Finished at: 2015-11-11T04:00:12+01:00
[INFO] [INFO] Final Memory: 34M/296M
[INFO] [INFO] ------------------------------------------------------------------------
[INFO] ..SUCCESS (12.3 s)
[INFO] -------------------------------------------------
[INFO] Build Summary:
[INFO]   Passed: 1, Failed: 0, Errors: 0, Skipped: 0
[INFO] -------------------------------------------------
[INFO] 
[INFO] --- maven-install-plugin:2.5.1:install (default-install) @ takes ---
[INFO] Installing /home/dragan/git/takes/target/takes-1.0-SNAPSHOT.jar to /home/dragan/.m2/repository/org/takes/takes/1.0-SNAPSHOT/takes-1.0-SNAPSHOT.jar
[INFO] Installing /home/dragan/git/takes/pom.xml to /home/dragan/.m2/repository/org/takes/takes/1.0-SNAPSHOT/takes-1.0-SNAPSHOT.pom
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 33.957 s
[INFO] Finished at: 2015-11-11T04:00:13+01:00
[INFO] Final Memory: 22M/298M
[INFO] ------------------------------------------------------------------------
```

**Comment by bdragan** [comment]
@yegor256 I updated the issue description to avoid any potential confusion: `mvn clean install -Pqulice` succeeds although there are failing integration tests (`mvn verify` is just a shortcut to execute only tests).

`mvn clean install -Pqulice` should fail if there are any problems with tests. Please correct me if I'm wrong.

**Comment by yegor256** [comment]
@bdragan you're right, thanks

**Comment by davvd** [comment]
@bdragan this task will get someone's attention soon

**Comment by davvd** [comment]
@bdragan since the ticket has no milestone I set it to 1.0

**Comment by davvd** [comment]
@bdragan thanks for the ticket, your account was topped for 15 mins, payment 69523086

**Comment by davvd** [comment]
@mojojojo this task is yours, please help (see our key [principles of work](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html)). If you have any technical questions, don't hesitate to ask right here... The budget of this issue is **30 mins**, which is exactly how much will be paid when the task is *done* (see [this](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html) for explanation)

**Comment by davvd** [comment]
@mojojojo you're working with this ticket for the last 15 days. If it is not closed within the next 48 hours, it will be re-assigned to someone else, see [No Obligations](http://www.xdsd.org/2014/04/13/no-obligations-principle.html) principle. [This article](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html) should help if you're stuck... -30 added to your rating, at the moment it is: [-90](http://www.netbout.com/b/36003?open=rating)

**Comment by HDouss** [comment]
@yegor256 Please assign this to me.

**Comment by davvd** [comment]
@hdouss please go ahead with this task, it's yours

**Comment by HDouss** [comment]
@davvd PR #494 reviewed and ready for merge. We wait for the architect to confirm the merge here.

**Comment by davvd** [comment]
> @davvd PR #494 reviewed and ready for merge. We wait for the architect to confirm the merge here.

@hdouss I see

**Comment by HDouss** [comment]
@bdragan PR #494 reviewed and merged. Please close the issue.

**Comment by bdragan** [comment]
@HDouss Thanks. Issue closed.

**Comment by HDouss** [comment]
@davvd Issue closed

**Comment by davvd** [comment]
> @davvd Issue closed

@hdouss thanks

**Comment by davvd** [comment]
@elenavolokhova please, let us know what do you think about this ticket, according to our [QA rules](http://at.teamed.io/qa.html)

**Comment by elenavolokhova** [comment]
@davvd Looks good!

**Comment by davvd** [comment]
> @davvd Looks good!

@elenavolokhova thanks a lot :)

**Comment by davvd** [comment]
@hdouss paied 10 mins to @elenavolokhova for QA review (payment ID is `73992221`)

**30 mins** was added to your account, many thanks for your contribution (payment 73992225)! The task took 81 hours and 31 mins.

+30 added to your rating, current score is: [+654](http://www.netbout.com/b/36032?open=rating)
