### ISSUE TITLE
Document FtSecure in README

### ISSUE THREAD

**Issue by bdragan** [yegor256/takes#437]
We should provide a `FtSecure` sample in README.

The necessary certificate setup for SSL communication should also be mentioned.

**Comment by davvd** [comment]
@bdragan we will find someone to do this task, soon

**Comment by davvd** [comment]
@bdragan attached this issue to milestone "1.0" (let me know if this is wrong)

**Comment by davvd** [comment]
@bdragan many thanks for the bug report, I added 15 mins to your acc, transaction `69110553`

**Comment by davvd** [comment]
@mojojojo please pick this up, and keep in mind [these instructions](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html). Any technical questions - ask right here... Task's budget is **30 mins** (see [this](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html) for explanation)

**Comment by davvd** [comment]
@mojojojo you're working with this ticket for the last 15 days. If it is not closed within the next 48 hours, it will be re-assigned to someone else, see [No Obligations](http://www.xdsd.org/2014/04/13/no-obligations-principle.html) principle. [This article](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html) should help if you're stuck... -30 added to your rating, at the moment it is: [-60](http://www.netbout.com/b/36003?open=rating)

**Comment by davvd** [comment]
@aschworer the task is for you now, follow [these guidelines](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html). Don't hesitate to ask any technical questions right here... This task's budget is **30 mins**. This is exactly how much will be paid when the problem explained above is solved. See [this](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html) for more information

**Comment by aschworer** [comment]
@davvd I am not certain to complete this task in time. Please do not assign anything to me for the next 5 days

**Comment by davvd** [comment]
> @davvd I am not certain to complete this task in time. Please do not assign anything to me for the next 5 days

@aschworer please, send this request in Netbout, to @yegor256

**Comment by davvd** [comment]
@aschworer check this ["no obligations principle"](http://www.xdsd.org/2014/04/13/no-obligations-principle.html).. This task is on your name for at least 15 days. If you can't close it within the next 48 hours I will have to assign someone else to it. [This article](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html) should help if you're stuck

added -30 to your rating, now it is equal to [-150](http://www.netbout.com/b/35983?open=rating)

**Comment by davvd** [comment]
@aschworer you've been working with this task for too long. I'm sorry, but I'll assign someone else. Please stop working with it. See our [no obligations](http://www.xdsd.org/2014/04/13/no-obligations-principle.html) principle; -60 added to your rating, at the moment it is: [-210](http://www.netbout.com/b/35983?open=rating)

**Comment by davvd** [comment]
@alexey-krylov the task is for you now, follow [these guidelines](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html). Don't hesitate to ask any technical questions right here... Task's budget is **30 mins** (see [this](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html) for explanation)

**Comment by davvd** [comment]
@danff the task is yours, please go ahead

**Comment by davvd** [comment]
@danff you're working with this issue for 15 days already... -30 added to your rating, current score is: [+0](http://www.netbout.com/b/36198?open=rating)

**Comment by danff** [comment]
@davvd need more time

**Comment by davvd** [comment]
> @davvd need more time

@danff agreed, take your time

**Comment by yegor256** [comment]
@0crat in

**Comment by 0crat** [comment]
> @0crat in ([here](https://github.com/yegor256/takes/issues/437#issuecomment-322125361))

@yegor256 Job `gh:yegor256/takes#437` is in scope.

**Comment by 0crat** [comment]
Job `gh:yegor256/takes#437` assigned to @caarlos0, please go ahead ([policy](http://datum.zerocracy.com/pages/policy.html)).

**Comment by 0crat** [comment]
@caarlos0 this job was assigned to you 8 days ago.
It will be taken away from you after 10 days from start (this is our policy).

**Comment by 0crat** [comment]
Oops! Job `gh:yegor256/takes#437` is not assigned to anyone.

**Comment by 0crat** [comment]
Oops! Job `gh:yegor256/takes#437` is not assigned to anyone.

**Comment by 0crat** [comment]
Oops! Job `gh:yegor256/takes#437` is not assigned to anyone.

**Comment by 0crat** [comment]
The job [#437](https://github.com/yegor256/takes/issues/437) assigned to @neonailol[/z](https://www.0crat.com/u/neonailol). The budget is 30 minutes, see [§4](http://datum.zerocracy.com/pages/policy.html#4). Please, read [§8](http://datum.zerocracy.com/pages/policy.html#8) and [§9](http://datum.zerocracy.com/pages/policy.html#9). If the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html).

**Comment by neonailol** [comment]
@0crat waiting

**Comment by 0crat** [comment]
> @0crat waiting ([here](https://github.com/yegor256/takes/issues/437#issuecomment-361667777))

@neonailol The impediment for [#437](https://github.com/yegor256/takes/issues/437) was registered successfully by @neonailol[/z](https://www.0crat.com/u/neonailol)

**Comment by neonailol** [comment]
@yegor256 changes from PR #783 are accepted and ready for merge, this task can be closed after that

**Comment by yegor256** [comment]
@neonailol thanks!

**Comment by 0crat** [comment]
Order was successfully finished: +30 points just awarded to @neonailol[/z](https://www.0crat.com/u/neonailol), total is [+375](https://www.0crat.com/u/neonailol)

**Comment by yegor256** [comment]
@neonailol I closed this task by mistake. In the future, please remember that you should ask ticket reporter to close it, not project architect. Only if the reporter is not answering, the architect should help.

**Comment by 0crat** [comment]
The job [#437](https://github.com/yegor256/takes/issues/437) is now out of scope

**Comment by neonailol** [comment]
@yegor256 well it's an old task, and person in not active on github, so i go directly to you

**Comment by yegor256** [comment]
@neonailol try to not to do this in the future, I will not close tickets like that anymore
