### ISSUE TITLE
Reading from the body of a GET request blocks forever

### ISSUE THREAD

**Issue by bdragan** [yegor256/takes#438]
Start a simple application:
```java
new FtBasic(
    new Take() {
        @Override
        public Response act(Request req) throws IOException {
            new RqPrint(req).printBody();
            return new RsEmpty();
        }
    }, 8080
).start(Exit.NEVER);
```
Point the browser to: `http://localhost:8080`.

**Current:** Attempt to read the request body is blocked (waits) forever.
**Desired:** Body should be considered empty (0 bytes).

The example here demonstrates `GET` method, but the fix should include any other HTTP methods for which this same problem exists.

**Comment by davvd** [comment]
@yegor256 please take a look at it and dispatch (see [par.21](http://at.teamed.io/policy.html#21))

**Comment by davvd** [comment]
@bdragan I set the milestone to 1.0 since there is nothing set yet

**Comment by davvd** [comment]
@bdragan thanks for tis bug, I topped your account for 15 mins, transaction `71688963`

**Comment by davvd** [comment]
@hdouss the task is yours please proceed

**Comment by HDouss** [comment]
@bdragan The sample application does not compile. there is no FtBasic constructor that takes a Take as an argument.

**Comment by HDouss** [comment]
@bdragan The problem occurs when the "Content-Length" header is not specified within the request. I suggest to suppose that there is no body message when this header is absent from the request

**Comment by bdragan** [comment]
@HDouss I think you should also check for the presence of `Transfer-Encoding` header, as described [here](http://www.w3.org/Protocols/rfc2616/rfc2616-sec4.html#sec4.3):
>The presence of a message-body in a request is signaled by the inclusion of a Content-Length or Transfer-Encoding header field in the request's message-headers.

**Comment by HDouss** [comment]
@bdragan I agree. I will add another class `RqChunk` and make a puzzle for its chunk size parsing feature.

**Comment by HDouss** [comment]
@davvd This issue #463 blocks me.

**Comment by davvd** [comment]
> @davvd This issue #463 blocks me.

@hdouss OK, let's wait for #463

**Comment by HDouss** [comment]
@davvd This issue #498 (besides #463) also blocks me.

**Comment by davvd** [comment]
> @davvd This issue #498 (besides #463) also blocks me.

@hdouss right, let's wait for #498

**Comment by davvd** [comment]
@bdragan we were waiting for #463 - it is closed already

**Comment by HDouss** [comment]
@davvd waiting also for #498.

>@hdouss right, let's wait for #498

**Comment by davvd** [comment]
> @davvd waiting also for #498.
> 
> >@hdouss right, let's wait for #498

@hdouss OK, let's wait for #498

**Comment by davvd** [comment]
@bdragan FYI, the issue we were waiting for (#498) is fixed

**Comment by HDouss** [comment]
@bdragan PR #527 reviewed and merged. Please close the issue.

**Comment by bdragan** [comment]
@HDouss Thanks, issue closed.

**Comment by davvd** [comment]
@bdragan once `438-dcc4d707`/#544 puzzle is resolved (later, in another ticket), this ticket will be fully complete

**Comment by davvd** [comment]
@ypshenychka please, let us know what do you think about this ticket, according to our [QA rules](http://at.teamed.io/qa.html)

**Comment by ypshenychka** [comment]
@davvd Quality is good.

**Comment by davvd** [comment]
> @davvd Quality is good.

@ypshenychka thank you :)

**Comment by davvd** [comment]
@hdouss 10 mins was added to the account of @ypshenychka (for QA review), in transaction 75640524... thanks, I just added **30 mins** to your account, payment `75640534`, 115 hours and 51 mins spent... +30 added to your rating, at the moment it is: [+1480](http://www.netbout.com/b/36032?open=rating)

**Comment by davvd** [comment]
@bdragan the last puzzle `438-dcc4d707`/#544 solved
