### ISSUE TITLE
MainRemote should allow additional arguments to be passed

### ISSUE THREAD

**Issue by carlosmiranda** [yegor256/takes#439]
Right now, `MainRemote.exec` only passes a single argument, `--port`. This makes main classes much more complicated to test if we happened to test or require extra arguments.

Let's allow more arguments to be passed by adding a second constructor `MainRemote(Class<?> type, String... args)`. All arguments passed to `args` should be passed to the main class being tested, with the addition of `--port`.

**Comment by davvd** [comment]
@yegor256 please do something about it, see [par.21](http://at.teamed.io/policy.html#21)

**Comment by yegor256** [comment]
@carlosmiranda good idea, thanks

**Comment by davvd** [comment]
@carlosmiranda I set the milestone to 1.0 since there is nothing set yet

**Comment by davvd** [comment]
@carlosmiranda many thanks for the report, I topped your account for 15 mins, transaction 69973052

**Comment by HDouss** [comment]
@davvd assign this to me please.

**Comment by davvd** [comment]
> @davvd assign this to me please.

@hdouss ask project architect to do this (@yegor256)

**Comment by HDouss** [comment]
@yegor256 assign this to me please.

**Comment by yegor256** [comment]
@davvd assign @HDouss to this ticket pls

**Comment by davvd** [comment]
> @davvd assign @HDouss to this ticket pls

@yegor256 done. @hdouss you are assigned to this task. please proceed...

**Comment by HDouss** [comment]
@carlosmiranda PR #457 has been merged to master. The issue can be closed.

**Comment by carlosmiranda** [comment]
@HDouss thanks!

**Comment by davvd** [comment]
@ypshenychka please, let us know what do you think about this ticket, according to our [QA rules](http://at.teamed.io/qa.html)

**Comment by ypshenychka** [comment]
@davvd Quality is good here.

**Comment by davvd** [comment]
> @davvd Quality is good here.

@ypshenychka thanks for the review and a good remark

**Comment by davvd** [comment]
@hdouss I added 10 mins to @ypshenychka (for QA review) in transaction 71832201; Thanks for your contribution, **1 hour** was added to your account, payment ID is `71832210`, 21 hours and 58 mins spent total; the bonus for fast delivery (m=1318); +60 to your rating, your total score is [+105](http://www.netbout.com/b/36032?open=rating)
