### ISSUE TITLE
CcXOR is not tested

### ISSUE THREAD

**Issue by yegor256** [yegor256/takes#44]
There is no unit test for `CcXOR` class, let's create one.

**Comment by davvd** [comment]
@yegor256 sure, thanks, I added bug tag to it

**Comment by davvd** [comment]
@yegor256 many thanks for the report, I topped your account for 15 mins, transaction 000-6986eb80

**Comment by davvd** [comment]
@maxbugaenko the task is for you now, follow [these guidelines](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html). Don't hesitate to ask any technical questions right here; The cost of this task is **30 mins** (this is exactly how much will be paid, not less not more), when the task is [done](http://www.xdsd.org/2014/04/15/definition-of-done.html)

**Comment by yegor256** [comment]
@davvd assign someone else pls

**Comment by davvd** [comment]
> @davvd assign someone else pls

@yegor256 got it, someone else will be assigned soon

**Comment by davvd** [comment]
@nathansgreen it's yours, please go ahead

**Comment by davvd** [comment]
@nathansgreen you're working with this issue for 15 days already; -30 added to your rating, current score is: [+30](http://www.netbout.com/b/35107?open=rating)

**Comment by davvd** [comment]
@nathansgreen this task is taking too long, I have to change the performer, sorry. Please stop working with it right now. See our [no obligations](http://www.xdsd.org/2014/04/13/no-obligations-principle.html) principle

-60 added to your rating, current score is: [-210](http://www.netbout.com/b/35107?open=rating)

**Comment by davvd** [comment]
@dmzaytsev please proceed,it's yours

**Comment by dmzaytsev** [comment]
@davvd  the pull request here #180

**Comment by dmzaytsev** [comment]
@yegor256 see the PR  above
Close the issue if alright

**Comment by yegor256** [comment]
@dmzaytsev thanks!

**Comment by davvd** [comment]
@elenavolokhova please, let us know what do you think about this ticket, according to our [QA rules](http://www.teamed.io/qa.html)

**Comment by elenavolokhova** [comment]
@davvd This ticket is good. Thanks All!

**Comment by davvd** [comment]
> @davvd This ticket is good. Thanks All!

@elenavolokhova thank you, good quality is always good :)

**Comment by davvd** [comment]
@dmzaytsev 10 mins was added to the account of @elenavolokhova (for QA review), in transaction 55838411

thank you, added **1 hour** to your acc, payment num is `55838433`, 65 hours and 58 mins spent in total to complete

there is a bonus for fast delivery (age=2)

+60 to your rating, your total score is [+836](http://www.netbout.com/b/35166?open=rating)
