### ISSUE TITLE
inputStream in org.takes.rs.RsXSLT.consume(InputStream) never closes

### ISSUE THREAD

**Issue by simonjenga** [yegor256/takes#441]

**Comment by yegor256** [comment]
@simonjenga right, it's a bug, thanks for reporting

**Comment by davvd** [comment]
@simonjenga I am aware of the task, give me some time to find a developer...

**Comment by davvd** [comment]
@simonjenga since there is no milestone yet I set it to "1.0"

**Comment by davvd** [comment]
@simonjenga many thanks for the report, I topped your account for 15 mins, transaction 69966269

**Comment by davvd** [comment]
@happy-neko This task is yours, please go ahead keeping in mind [this](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html). If any questions, don't hesitate to ask right here; Total fixed cost of this task is **30 mins** (see [this](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html) for more info)

**Comment by Happy-Neko** [comment]
@davvd ping.

**Comment by davvd** [comment]
> @davvd ping.

@happy-neko yes, I'm here

**Comment by Happy-Neko** [comment]
@david Is anything needed from me to have this issue closed?

**Comment by Happy-Neko** [comment]
@davvd @yegor256 @elenavolokhova
Please respond what stops this ticket from being closed?

**Comment by yegor256** [comment]
@Happy-Neko only ticket reporter can close a ticket, see http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html

**Comment by Happy-Neko** [comment]
@simonjenga PR #467 is merged. We can close the ticket.

**Comment by simonjenga** [comment]
@Happy-Neko OK

**Comment by davvd** [comment]
@ypshenychka please, check this issue for QA compliance, as per [par.24](http://at.teamed.io/policy.html#24)

**Comment by ypshenychka** [comment]
@simonjenga 
According to our [QA Rules](http://www.teamed.io/qa.html):
>Ticket title and description clearly state what is broken and what kind of fix is expected, [see](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html#5.-report-when-it-is-broken)

There is no description provided. Please add appropriate description for the issue.

**Comment by simonjenga** [comment]
@ypshenychka I have updated the ticket description.

**Comment by ypshenychka** [comment]
@simonjenga thanks

**Comment by ypshenychka** [comment]
@davvd Quality is acceptable.

**Comment by davvd** [comment]
> @davvd Quality is acceptable.

@ypshenychka thanks for the review, we'll try better next time

**Comment by davvd** [comment]
@happy-neko paied 10 mins to @ypshenychka for QA review (payment ID is `73043460`)... **30 mins** added to your account (payment number `73043470`), many thanks for your contribution! 261 hours and 58 mins spent here.... added +30 to your rating, now it is equal to [+98](http://www.netbout.com/b/36136?open=rating)
