### ISSUE TITLE
inputStream in RsVelocity.render(InputStream, Map<CharSequence, Object>) never closes

### ISSUE THREAD

**Issue by simonjenga** [yegor256/takes#442]

**Comment by davvd** [comment]
@yegor256 dispatch this issue please, see [par.21](http://at.teamed.io/policy.html#21)

**Comment by yegor256** [comment]
@simonjenga seems to be a valid bug, thanks

**Comment by davvd** [comment]
@simonjenga attached this issue to milestone "1.0" (let me know if this is wrong)

**Comment by davvd** [comment]
@simonjenga many thanks for the bug report, I added 15 mins to your acc, transaction `71680633`

**Comment by gauee** [comment]
Can I start working on this issue?

**Comment by davvd** [comment]
@happy-neko please pick this up, and keep in mind [these instructions](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html). Any technical questions - ask right here. Task's budget is **30 mins** (see [this](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html) for explanation)

**Comment by Happy-Neko** [comment]
@simonjenga PR #442 can be merged to close this ticket.

**Comment by simonjenga** [comment]
@Happy-Neko ```inputStream``` in ```RsVelocity.render(InputStream, Map<CharSequence, Object>)``` is not yet closed

**Comment by simonjenga** [comment]
@Happy-Neko While i also like the design and your ideas, i expected the fix to be simply ```input.close();```. Always try to keep code to be as minimum as possible so as to avoid bloatware and future maintenance nightmares.

I also think we should also add ```input.close();``` in ```RsVelocity.render(InputStream, Map<CharSequence, Object>)``` to avoid somebody else raising a similar ticket.
Thanks!

**Comment by Happy-Neko** [comment]
@simonjenga Please see PR description. InputStream is already closed in template engine, there is no need to close it twice.

**Comment by simonjenga** [comment]
@Happy-Neko OK!

**Comment by davvd** [comment]
@ypshenychka please, review this task for compliance with our [quality rules](http://at.teamed.io/qa.html)

**Comment by ypshenychka** [comment]
@davvd Quality is good here.

**Comment by davvd** [comment]
> @davvd Quality is good here.
> 

@ypshenychka thanks a lot

**Comment by davvd** [comment]
@happy-neko I added 10 mins to @ypshenychka (for QA review) in transaction 73054749... I added **30 mins** to your account, many thanks for working with the project (73054758)! The completion time here was 268 hours and 33 mins.... +30 to your rating, your total score is [+128](http://www.netbout.com/b/36136?open=rating)
