### ISSUE TITLE
RqHref.Base reads first line of header without checking format

### ISSUE THREAD

**Issue by HDouss** [yegor256/takes#445]
`org.takes.rq.RqHref.Base` just reads first header and takes second element after space splitting :
`this.head().iterator().next().split(" ", 3)[1]`
It should check if the header format satisfies HTTP specifications.

<hr id='w'>

**Comment by davvd** [comment]
@yegor256 take a look at this issue please and dispatch it somehow, see [par.21](http://at.teamed.io/policy.html#21)

**Comment by yegor256** [comment]
@HDouss seems to be a valid bug, thanks

**Comment by davvd** [comment]
@hdouss attached this issue to milestone "1.0" (let me know if this is wrong)

**Comment by davvd** [comment]
@hdouss thanks for reporting! I topped your account for 15 mins, transaction 71676136

**Comment by davvd** [comment]
@happy-neko could you please pick this up? This [article](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html) explains how we work. Any technical questions you may ask right here

The cost of this task is **30 mins** (this is exactly how much will be paid, not less not more), when the task is [done](http://www.xdsd.org/2014/04/15/definition-of-done.html)

**Comment by davvd** [comment]
@hdouss once `445-5323c196`/#473 puzzle is resolved (later, in another ticket), this ticket will be fully complete

**Comment by HDouss** [comment]
@davvd I should anyway close this issue, right ?

**Comment by HDouss** [comment]
@Happy-Neko The pattern used assume that a "third part" of the request line is optional. I am not sure it is the case according to the specifications. The current implemented pattern will accept request lines like : `GET HTTP/1.1` or `GET /`

**Comment by Happy-Neko** [comment]
@HDouss Protocol part is required per HTTP 1.1 specs. It is optional if we want to maintain backward compatibility with HTTP 1.0.

**Comment by HDouss** [comment]
@Happy-Neko Ok. Make sense.

**Comment by HDouss** [comment]
@davvd I will close the issue as the PR is merged and accepted.

**Comment by HDouss** [comment]
@Happy-Neko Please make a reference to the PR id.

**Comment by Happy-Neko** [comment]
@HDouss issue was fixed in PR #466

**Comment by HDouss** [comment]
@Happy-Neko Thanks !

**Comment by davvd** [comment]
@ypshenychka please, check this issue for QA compliance, as per [par.24](http://at.teamed.io/policy.html#24)

**Comment by ypshenychka** [comment]
@davvd Quality is good here.

**Comment by davvd** [comment]
> @davvd Quality is good here.

@ypshenychka thank you

**Comment by davvd** [comment]
@happy-neko 10 mins was added to the account of @ypshenychka (for QA review), in transaction 72638957; thanks, I just added **30 mins** to your account, payment `72640289`, 125 hours and 51 mins spent; added +30 to your rating, now it is equal to [+30](http://www.netbout.com/b/36136?open=rating)

**Comment by davvd** [comment]
@hdouss last puzzled solved `445-5323c196`/#473
