### ISSUE TITLE
Cannot use Pass with TkRegex

### ISSUE THREAD

**Issue by pinaf** [yegor256/takes#449]
Currently we cannot use a `Pass` along with a `TkRegex` like we can with a `Take`. The reason is that `TkAuth` expects a `Take`.

Ideally we'd have a class `TkAuthRegex` that provides functionality analogous to that in `TkAuth`.

**Comment by pinaf** [comment]
@yegor256 I can provide a PR for this - without tests though. I can drop in a puzzle for that if you want.

**Comment by davvd** [comment]
@yegor256 take a look at this issue please and dispatch it somehow, see [par.21](http://at.teamed.io/policy.html#21)

**Comment by yegor256** [comment]
@pinaf I didn't understand it at all.. can you give a code example?

**Comment by pinaf** [comment]
@yegor256 sure. If `MyTake` is a `TkRegex`, one cannot do this:
```java
new TkAuth(new MyTake(), pass)
```
because `TkAuth` works with a pure `Take`, not with a `TkRegex`.

**Comment by pinaf** [comment]
@yegor256 I suggest a new class `TkAuthRegex` with does the same thing `TkAuth` does, but to a `TkRegex`

**Comment by pinaf** [comment]
@yegor256 make sense?

**Comment by yegor256** [comment]
@pinaf I got it now, thanks

**Comment by pinaf** [comment]
@yegor256 want me to do the PR with a puzzle for tests?

**Comment by pinaf** [comment]
@yegor256 here's the one I built in case you want it.
```java
/**
 * Authenticating take.
 *
 * <p>The class is immutable and thread-safe.
 *
 * @author Felipe Pina (felipe.pina@protonmail.com)
 * @version $Id$
 * @since 0.28
 */
@ToString(of = { "origin", "pass", "header" })
@EqualsAndHashCode(of = { "origin", "pass", "header" })
public final class TkAuthRegex implements TkRegex {

    /**
     * Original take.
     */
    private final transient TkRegex origin;

    /**
     * Pass.
     */
    private final transient Pass pass;

    /**
     * Header to set in case of authentication.
     */
    private final transient String header;

    /**
     * Ctor.
     * @param take Original
     * @param pss Pass
     */
    public TkAuthRegex(final TkRegex take, final Pass pss) {
        this(take, pss, TkAuth.class.getSimpleName());
    }

    /**
     * Ctor.
     * @param take Original
     * @param pss Pass
     * @param hdr Header to set
     */
    public TkAuthRegex(final TkRegex take, final Pass pss, final String hdr) {
        this.origin = take;
        this.pass = pss;
        this.header = hdr;
    }

    @Override
    public Response act(final RqRegex request) throws IOException {
        final Opt<Identity> user = this.pass.enter(request);
        final Response response;
        if (user.has()) {
            response = this.act(request, user.get());
        } else {
            response = this.origin.act(request);
        }
        return response;
    }

    /**
     * Make take.
     * @param req Request
     * @param identity Identity
     * @return Take
     * @throws IOException If fails
     */
    private Response act(final RqRegex req, final Identity identity)
        throws IOException {
        Request wrap = new RqWithoutHeader(req, this.header);
        if (!identity.equals(Identity.ANONYMOUS)) {
            wrap = new RqWithAuth(identity, this.header, wrap);
        }
        final Request effective = wrap;
        return this.pass.exit(
            this.origin.act(
                new RqRegex() {
                    @Override
                    public Matcher matcher() {
                        return req.matcher();
                    }
                    @Override
                    public Iterable<String> head() throws IOException {
                        return effective.head();
                    }
                    @Override
                    public InputStream body() throws IOException {
                        return effective.body();
                    }
                }
            ),
            identity
        );
    }

}
```

**Comment by davvd** [comment]
@pinaf milestone set to `1.0` (correct me if I am wrong)

**Comment by davvd** [comment]
@yegor256 this task is yours, go ahead

**Comment by davvd** [comment]
@pinaf thanks for tis bug, I topped your account for 15 mins, transaction `AP-19K900532P836620R`

**Comment by yegor256** [comment]
@pinaf take a look at fd2f184 I believe, this is what you need

**Comment by pinaf** [comment]
@yegor256 the problem with that solution is that you have to create the matcher externally and pass it on. For example:
```java
final Matcher matcher = ...
new FkRegex(
    matcher.pattern().pattern(),
    new TkAuth(
        new TkRegex.Fake(new MyTkRegex(), matcher),
        new MyPass()
    )
)
```

**Comment by pinaf** [comment]
@yegor256 but it does work. let me know what you think.

**Comment by yegor256** [comment]
@pinaf yes, that's how it should be, I believe. If you want to use `TkRegex` where `Take` is expected, you have to pass the matcher somehow. To fake it somehow, so to speak

**Comment by pinaf** [comment]
@yegor256 got it. thanks!

**Comment by davvd** [comment]
@elenavolokhova please, review this task for compliance with our [quality rules](http://at.teamed.io/qa.html)

**Comment by elenavolokhova** [comment]
@yegor256 
  According to our [quality rules](http://www.teamed.io/qa.html):
 > Some of ticket messages must mention all pull requests where the problem was actually fixed.
 
 There is no PR created for this ticket. Please, follow this rule in your tickets in the future.

**Comment by yegor256** [comment]
@elenavolokhova yeah, my bad, thanks for noticing

**Comment by elenavolokhova** [comment]
@davvd Quality is acceptable here.

**Comment by davvd** [comment]
> @davvd Quality is acceptable here.

@elenavolokhova thanks for the QA review, we'll work better next time

**Comment by davvd** [comment]
@yegor256 I added 10 mins to @elenavolokhova (for QA review) in transaction 71766052; Much obliged! I have added **30 mins** to your account in payment "000-99645ccc", 200 hours and 56 mins spent; +30 added to your rating, at the moment it is: [+9128](http://www.netbout.com/b/35008?open=rating)
