### ISSUE TITLE
base parameter in RsXSLT.InClasspath.resolve(String, String) is unused

### ISSUE THREAD

**Issue by simonjenga** [yegor256/takes#450]
```base``` parameter in ```RsXSLT.InClasspath.resolve(String, String)``` is unused

**Comment by davvd** [comment]
@yegor256 please do something about this issue

**Comment by yegor256** [comment]
@simonjenga it's a valid concern, you're right, thanks

**Comment by davvd** [comment]
@simonjenga I added milestone `1.0` to this issue, let me know if there has to be something else

**Comment by davvd** [comment]
@simonjenga thanks for the report, I topped your acc for 15 mins, payment ID `70732064`

**Comment by davvd** [comment]
@danff this task is for you, keep [these principles](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html) in mind, and don't hesitate to ask any technical questions. This task's budget is **30 mins**. This is exactly how much will be paid when the problem explained above is solved. See [this](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html) for more information

**Comment by danff** [comment]
@davvd Pull request has been merged

**Comment by davvd** [comment]
> @davvd Pull request has been merged

@danff which one?

**Comment by danff** [comment]
@davvd #474 - RsXSLT.InClasspath resolve() method was not using "base" parameter.

**Comment by davvd** [comment]
> @davvd #474 - RsXSLT.InClasspath resolve() method was not using "base" parameter.
> 

@danff thanks

**Comment by danff** [comment]
@simonjenga @davvd The pull request #474 for this issue was merged and closed. Can this issue be closed? Thank you.

**Comment by simonjenga** [comment]
@danff Lets add a check to see if ```base``` is empty: ```if (base == null || base.isEmpty())```

**Comment by danff** [comment]
@simonjenga Ok

**Comment by danff** [comment]
@simonjenga @davvd Pull request #479 with base.isEmpty() check has been added

**Comment by davvd** [comment]
@danff check this ["no obligations principle"](http://www.xdsd.org/2014/04/13/no-obligations-principle.html).. This task is on your name for at least 15 days. If you can't close it within the next 48 hours I will have to assign someone else to it. [This article](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html) should help if you're stuck... -30 to your rating, your total score is [-30](http://www.netbout.com/b/36198?open=rating)

**Comment by danff** [comment]
@davvd The ticket actually was implemented, and the last commit (pull request #479) is waiting for review for 9 days.

**Comment by danff** [comment]
@simonjenga @davvd At last the pull request #479 has been merged. Can the ticket be closed?

@yegor256 @davvd The last pull request for a cosmetic change has been reviewed and merged in 10 days. Process that I can not influence in any way. Why -30?

**Comment by davvd** [comment]
> @davvd The ticket actually was implemented, and the last commit (pull request #479) is waiting for review for 9 days. Why -30?

@danff the task is "done" when it's closed by its author. this task is not done. when @simonjenga closes it, I will consider it done. see http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html

**Comment by danff** [comment]
@davvd But the task can not be done/closed till the PR is merged. And PR was reviewed/merged by @yegor256 in 10 days. And I am penalized because of this??? I did not received any argument why I am penalized here. Only the link to the principles of bug tracking which does not answer my question.

**Comment by danff** [comment]
So, as I have been advised:
@davvd "I need more time here" because it took another 10 days to merge a PR for a cosmetic change and now I am waiting for the ticket to be closed or commented.

**Comment by danff** [comment]
@simonjenga Can the ticket be closed?

**Comment by simonjenga** [comment]
@danff A ticket is only closed if all requirements have been met because once closed, it cannot be opened. So, always be patient :)

I was waiting for #479 to be approved and merged by the Architect.

Closed, OK!

**Comment by danff** [comment]
@simonjenga I was already too patient and as a result have my rating -60 because of merge delays. Thank you for closing the ticket.

**Comment by davvd** [comment]
@elenavolokhova please, check this issue for QA compliance, as per [par.24](http://at.teamed.io/policy.html#24)

**Comment by elenavolokhova** [comment]
@danff 
 According to our [quality rules](http://www.teamed.io/qa.html):
 >The ticket describes one specific problem and provides a single solution.
 
 Two PRs were created for this issue. Please try to follow this rule in your tickets in the future.
 
 Please confirm that everything is clear and you have no questions regarding this approach.

**Comment by danff** [comment]
@elenavolokhova Everything clear. Thank you.

**Comment by elenavolokhova** [comment]
@danff Thanks!

**Comment by elenavolokhova** [comment]
@davvd  Quality is acceptable here.

**Comment by davvd** [comment]
> @davvd  Quality is acceptable here.

@elenavolokhova thanks for the review, we'll try better next time

**Comment by davvd** [comment]
@danff added 10 mins to @elenavolokhova, for QA review, payment code is `73998599`; I just added **30 mins** to your account, many thanks for your contribution (AP-5P373388N0205934W).. 426 hours and 58 mins spent here; +30 added to your rating, at the moment it is: [-30](http://www.netbout.com/b/36198?open=rating)
