### ISSUE TITLE
Connection reset if request body wasn't read from POST

### ISSUE THREAD

**Issue by longtimeago** [yegor256/takes#453]
For example, server expects POST request with some body
In some particular case server may be not interested in request body.
But if server didn't read the body then response is never sent - client will get connection reset.
Reading the body manually (`new RqPrint(req).printBody()`) works but not the best approach.

It would be nice if `takes` read request body somehow if it wasn't read during response generation.
As far as I know, servlets are doing this way.

**Comment by yegor256** [comment]
@longtimeago hm... interesting problem. maybe we can introduce a new Take decorator, which will work like this:

```
final class TkReadAlways implements Take {
  private final Take origin;
  public Response act(Request req) {
    Response rsp = this.origin.act(req);
    if (req.body().still_has_some_unread_data()) {
      req.body().read_everything_available();
    }
    return rsp;
  }
}
```

did I get it right?

**Comment by longtimeago** [comment]
@yegor256 in general, yes, but it would be the best to have this behavior completely transparant for the library user

**Comment by yegor256** [comment]
@longtimeago well, are you sure? some users may not need this functionality. I don't think it is part of HTTP protocol. or is it?

**Comment by longtimeago** [comment]
@yegor256 well, as far as I know, it's not a part of a protocol. But it's rather a detail to think about it each time you implement some Take or compose it from existing ones.
This is especially annoying for testing, when implementing mock server

**Comment by yegor256** [comment]
@longtimeago I understand, but we can't add it by default. there won't be any way to remove it than. everybody will just have this feature and it won't be possible to remove it ( so, the best option is to introduce `TkReadAlways` (or some other name) and let you use it when necessary.

**Comment by longtimeago** [comment]
@yegor256 OK, at least something :)

**Comment by davvd** [comment]
@longtimeago I will ask someone to take care of this task soon

**Comment by davvd** [comment]
@longtimeago I set milestone here to `1.0`, let me know if it is wrong

**Comment by davvd** [comment]
@longtimeago thanks for the ticket, your account was topped for 15 mins, payment 71645544

**Comment by davvd** [comment]
@danff This task is yours, please go ahead keeping in mind [this](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html). If any questions, don't hesitate to ask right here. The budget of this task is **30 mins**. This is exactly how much time will be compensated, when the task is completed. Read about our [Definition of Done](http://www.xdsd.org/2014/04/15/definition-of-done.html)

**Comment by davvd** [comment]
@danff you're holding this ticket for 15 days already. If it is not finished (and closed) in the next 48 hours, it will be re-assigned to someone else, see [No Obligations](http://www.xdsd.org/2014/04/13/no-obligations-principle.html) principle ([this article](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html) should help if you're stuck); -30 added to your rating, at the moment it is: [-90](http://www.netbout.com/b/36198?open=rating)

**Comment by danff** [comment]
@davvd The ticket is waiting for the pull request #489 to be merged for 7 days.

**Comment by danff** [comment]
@longtimeago @davvd The pull request has been merged. Can the ticket be closed?

@yegor256 @davvd The merging of the pull request has been made in 7-8 days, process that I can not control. So again my question. Why -30?

**Comment by longtimeago** [comment]
@danff sure, it can be closed. Thanks

**Comment by longtimeago** [comment]
@danff next time don't wait for 8 days - just ping ticket author right after PR is merged

**Comment by danff** [comment]
@longtimeago actually PR was merged after 8 days. And not me waiting.

**Comment by danff** [comment]
@longtimeago btw thank you for closing the ticket.

**Comment by longtimeago** [comment]
@danff I'd like you to read this article http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html

**Comment by longtimeago** [comment]
@danff it's your responsibility to push me as issue reporter to close the issue when it's done - just FYI :)

**Comment by danff** [comment]
@longtimeago thank you for the link. But the problem is not pushing you, I have asked to close the issue immediately after the PR have been merged. The PR was created 8 days ago and merged only 45 min ago.

**Comment by danff** [comment]
@longtimeago sorry bothering you, actually is not your problem and I am spending your time. Thanks again for the ticket.

**Comment by yegor256** [comment]
@danff don't worry about spending his time :) @longtimeago knows how to manage his time. if he doesn't, it's his fault. you should be as aggressive as possible in making sure **your** personal objectives are achieved. your goal is to earn money in this particular task. you will earn them only when the task is closed. ticket reporter (@longtimeago) is your obstacle. he is sort of "against you" in this goal. so, don't worry at all about bothering. achieve your personal goals!

**Comment by danff** [comment]
@yegor256 Thank you for comments. But my obstacle was not @longtimeago in any way. My obstacle was the "merge" of the PR which took 7-8 days. And to "be as aggressive as possible" also has some limits :)

**Comment by davvd** [comment]
> @davvd The ticket is waiting for the pull request #489 to be merged for 7 days. Why -30?

@danff see http://at.teamed.io/policy.html#10 (also, read the entire policy, it will help you understand our principles of work)

**Comment by danff** [comment]
@davvd So I had to write "waiting for #489 PR to be merged!"? Actually the correct link should be http://at.teamed.io/policy.html#11

**Comment by longtimeago** [comment]
@danff Yes, you can write so, but don't overuse this feature :)

**Comment by danff** [comment]
@longtimeago But I thought is obvious to wait for the Pull Request to be merged. Or I am missing something?

**Comment by longtimeago** [comment]
@danff Davvd is a chat-bot, not a human. He checks the issue status and doesn't care whenever PR is submitted or not :)
There are not so many corner cases, you will get used to :)

**Comment by danff** [comment]
@longtimeago That is nice. But what can I do in the future to avoid such situations, when the Pull request has been made, reviewed, and the last step of merging took 7 days (for one issue) and 10 days (for another ticket), and as a result I have -30 (and another -30 from the second tcket) down rating only because of merging delays? I did not find any answer to this particular situation I am in, how to solve this, and how to avoid it?

**Comment by longtimeago** [comment]
@danff If you see that you stuck on some step because of slow response simply ask Davv "I need more time here" in the issue (not in PR). That's it

**Comment by danff** [comment]
@longtimeago Thank you for advice. I'll do that in the future.

**Comment by longtimeago** [comment]
@danff welcome :)

**Comment by davvd** [comment]
@ypshenychka please, check this issue for QA compliance, as per [par.24](http://at.teamed.io/policy.html#24)

**Comment by ypshenychka** [comment]
@davvd Quality is good here.

**Comment by davvd** [comment]
> @davvd Quality is good here.

@ypshenychka thanks!

**Comment by davvd** [comment]
@danff just added 10 mins to @ypshenychka (for QA), payment ID is `73881114`... thanks, paid, **30 mins** to your account, payment ID is `AP-9AB08469TR470862R`, task took 408 hours and 45 mins to complete... +30 to your rating, your total score is [-60](http://www.netbout.com/b/36198?open=rating)
