### ISSUE TITLE
BkReuseTest does not send proper request

### ISSUE THREAD

**Issue by HDouss** [yegor256/takes#454]
`BkReuseTest` as implemented in #417 does not send a request to `BkReuse` to be processed. All sockets in all three methods have empty input streams.
`BkReuseTest` should send sockets with valid content to `BkReuse` in order to test it.

**Comment by yegor256** [comment]
@HDouss seems like a bug, thanks

**Comment by davvd** [comment]
@hdouss I will ask someone to take care of this task soon

**Comment by davvd** [comment]
@hdouss I added milestone `1.0` to this issue, let me know if there has to be something else

**Comment by davvd** [comment]
@hdouss thanks for reporting! I topped your account for 15 mins, transaction 71625342

**Comment by davvd** [comment]
@danff this task is for you, keep [these principles](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html) in mind, and don't hesitate to ask any technical questions... The budget of this issue is **30 mins**, which is exactly how much will be paid when the task is *done* (see [this](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html) for explanation)

**Comment by davvd** [comment]
@danff you're working with this ticket for the last 15 days. If it is not closed within the next 48 hours, it will be re-assigned to someone else, see [No Obligations](http://www.xdsd.org/2014/04/13/no-obligations-principle.html) principle. [This article](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html) should help if you're stuck; -30 to your rating, your total score is [-60](http://www.netbout.com/b/36198?open=rating)

**Comment by danff** [comment]
@davvd "Need more time"

**Comment by davvd** [comment]
> @davvd "Need more time"

@danff of course, thanks for letting me know, take your time

**Comment by danff** [comment]
@davvd waiting for #500 in order to avoid merge conflicts

**Comment by davvd** [comment]
> @davvd waiting for #500 in order to avoid merge conflicts

@danff #500 is a pull request, we can't call it an impediment

**Comment by danff** [comment]
@davvd waiting for #456 to avoid conflicts

**Comment by davvd** [comment]
> @davvd waiting for #456 to avoid conflicts
> 

@danff ok, let's wait for #456

**Comment by davvd** [comment]
@hdouss FYI, issue #456 is already closed, and we were waiting for it..

**Comment by danff** [comment]
@davvd need more time for the PR #518 to be merged

**Comment by davvd** [comment]
> @davvd need more time for the PR #518 to be merged

@danff yeah, I know, take your time

**Comment by danff** [comment]
@HDouss The PR has been merged. Can the ticket be reviewed and closed?

**Comment by HDouss** [comment]
@danff Thanks.

**Comment by davvd** [comment]
@elenavolokhova please, review this issue for QA compliance, as per [par.24](http://at.teamed.io/policy.html#24)

**Comment by elenavolokhova** [comment]
@davvd Looks good!

**Comment by davvd** [comment]
> @davvd Looks good!

@elenavolokhova thanks for the review and a good remark

**Comment by davvd** [comment]
@danff paied 10 mins to @elenavolokhova for QA review (payment ID is `75203151`); I added **30 mins** to your account, many thanks for working with the project (AP-0NK41875RE488925R)! The completion time here was 108 hours and 54 mins.; +30 to your rating, your total score is [+0](http://www.netbout.com/b/36198?open=rating)
