### ISSUE TITLE
BkReuse should not be a wrapper

### ISSUE THREAD

**Issue by HDouss** [yegor256/takes#456]
`BkReuse` should not decorate another `Back`. Persistent connections should either be handled by `BkBasic` or by a specific Back that don't decorate another Back.
**Reason:** before delegating the process of the socket to the underlying Back, BkReuse should definitely read from the socket input stream and process some of the headers.
There is no way to reposition the socket input stream to be (correctly) processed again by the underlying Back. The underlying Back would accept an already read socket.
> Let's get rid of BkReuse, move all tests from BkReuseTest to BkBasicTest and implement persistent connections inside BkBasic. Thanks for taking time to convince me.

**Comment by yegor256** [comment]
@HDouss I don't think I agree... I think that `BkReuse` should create **new** instance of class `Socket` and pass it into the underlying `back`. This is how I would implement it.

**Comment by HDouss** [comment]
@yegor256 This new instance should be a perfect clone of the original one, before being read by `BkReuse`. That won't be possible unless we implement our own (fake ?) subclass implementation of `Socket` (or `SocketImpl`).

**Comment by yegor256** [comment]
@HDouss we can just start a `ServerSocket`, connect to it, send HTTP request through it. In other words, simulate a proxy. Why not?

**Comment by yegor256** [comment]
@HDouss it doesn't need to be a "perfect clone". Just a socket with incoming data, which are identical to the data received through the original socket.

**Comment by HDouss** [comment]
@yegor256 that way, we are making assumptions that the underlying `Back` is using only the socket incoming data. For example `BkBasic` is using LocalAddress, InetAddress, LocalPort, Port. May be it is not a good example, but in general we cannot make assumptions on what properties of the socket will be used by future implementations of `Back`.
As a proxy simulator, we should also take back passed socket outputstream to report it on the original socket. That is OK but complicates `BkReuse` a little bit.
If you're OK with such assumptions, I will consider it a taken decision and close the issue.

**Comment by yegor256** [comment]
@HDouss well, that make sense... how about creating our own sub-class of `Socket`?

**Comment by HDouss** [comment]
@yegor256 That would be a solution with less overhead than simulating a proxy, but that may require further thinking about how to make a proper input stream available for the `Back`.
I still think that `BkReuse` being a wrapper is the misconception. It is rather "Basic" to handle persistent connection. We are not really decorating with an additional (outsider) feature as for `BkParallel` or `BkSafe`.

**Comment by yegor256** [comment]
@HDouss maybe. But you should propose a better solution in that case. Just placing everything into BkBasic is not an option. We want our classes to be small and solid.

**Comment by HDouss** [comment]
@yegor256 I suggest : 
1. making 2 additional types of requests : RqOngoing, RqClosing. The parse method in RqLive should return on of these implementations in case of a persistent connection.
2. BkBasic don't close the socket input stream in case of a RqOngoing, and closes the stream in case of a RqClosing or in case of another request (that does not belong to a persistent connection).
And that's it !

**Comment by yegor256** [comment]
@HDouss not a bad direction of thinking, but what exactly does this mean: "RqLive should return". `RqLive` is a class, not a method.

**Comment by HDouss** [comment]
@yegor256 return refers to **The parse method** in : 
> The parse method in RqLive should return on of these implementations in case of a persistent connection.

**Comment by yegor256** [comment]
@HDouss this is the code in `BkBasic`:

```
    @Override
    public void accept(final Socket socket) throws IOException {
        final InputStream input = socket.getInputStream();
        try {
            this.print(
                BkBasic.addSocketHeaders(
                    new RqLive(input),
                    socket
                ),
                new BufferedOutputStream(socket.getOutputStream())
            );
        } finally {
            input.close();
        }
    }
```

As you see, there is `new RqLive(input)`. We just make an instance of `RqLive`. `parse()` is a private method.

**Comment by yegor256** [comment]
@HDouss also, keep in mind that class casting and checking classes in runtime is a terrible anti-pattern, see http://www.yegor256.com/2015/04/02/class-casting-is-anti-pattern.html

**Comment by HDouss** [comment]
@yegor256 I agree. The main idea of the suggestion is that responsibility of the Back is limited to closing or not the socket stream. Every other consideration should be made elsewhere based on the nature of the request. In other words, an idea could be to add a method to the `Request` interface
`public boolean ongoing();`

**Comment by yegor256** [comment]
@HDouss maybe we should change the interface of Back...? Make it `accept(InputStream)` instead of `accept(Socket)`... what do you think?

**Comment by HDouss** [comment]
@yegor256 It is a nice idea. It gives more flexibility for the decoration of Back wrappers in general.
But I still think that BkReuse is not a good idea. Using takes in its simplest example : 
```java
import org.takes.http.Exit;
import org.takes.http.FtBasic;
import org.takes.facets.fork.FkRegex;
import org.takes.facets.fork.TkFork;
public final class App {
  public static void main(final String... args) throws Exception {
    new FtBasic(
      new TkFork(new FkRegex("/", "hello, world!")), 8080
    ).start(Exit.NEVER);
  }
}
```
have just to handle persistent connections.
May be I'm repeating myself, but I think that it is rather weird to have : 

1. A specific implementation for persistent connections, it's basic feature widely used nowadays in HTTP protocol clients and servers.
2. We have to decorate a Back to handle persistent connections.
3. Passed Input/Output streams could be closed in underlying Back (like in BKBasic).

**Comment by yegor256** [comment]
@HDouss OK, I agree. Let's get rid of `BkReuse`, move all tests from `BkReuseTest` to `BkBasicTest` and implement persistent connections inside `BkBasic`. Thanks for taking time to convince me.

**Comment by HDouss** [comment]
@yegor256 Should #418 be invalidated ?

**Comment by yegor256** [comment]
@HDouss not at all. We will fix this ticket first and then you will continue with that puzzle. We still need to implement persistence. This ticket won't solve the entire problem, but will just get rid of `BkReuse`.

**Comment by HDouss** [comment]
@yegor256 Ok

**Comment by davvd** [comment]
@hdouss I am aware of the task, give me some time to find a developer...

**Comment by davvd** [comment]
@hdouss I set the milestone to 1.0 since there is nothing set yet

**Comment by davvd** [comment]
@hdouss thank you for the ticket reported, I topped your account for 15 mins, transaction `71695368`

**Comment by davvd** [comment]
@xupyprmv it's yours now, please proceed keeping in mind [our principles](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html). Feel free to ask any technical questions right here in the ticket... This task's budget is **30 mins**. This is exactly how much will be paid when the problem explained above is solved. See [this](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html) for more information

**Comment by xupyprmv** [comment]
@davvd I can't continue until #486 is resolved.

**Comment by davvd** [comment]
> @davvd I can't continue until #486 is resolved.

@xupyprmv @davvd waiting for #486

**Comment by yegor256** [comment]
@davvd yes, we're waiting for #486 here

**Comment by davvd** [comment]
> @davvd yes, we're waiting for #486 here

@yegor256 OK, let's wait for #486

**Comment by xupyprmv** [comment]
@HDouss Can you please update ticket description? I have discussion with you inside #486. I think ticket description must be updated. After that #486 will not block current issue and I can go ahead.

**Comment by HDouss** [comment]
@xupyprmv Description updated. I added a relevant comment from this issue discussion.

**Comment by xupyprmv** [comment]
@HDouss I see next line inside issue description:

> implement persistent connections inside BkBasic

Is that comment related to current issue?

**Comment by HDouss** [comment]
@xupyprmv No. It is a suggestion to let #418 as it is and not to invalidate it (but may be update it).

**Comment by davvd** [comment]
@hdouss we were waiting for #486 - it is closed already

**Comment by xupyprmv** [comment]
@davvd I need more time here. I'm waiting for final merge in #500

**Comment by davvd** [comment]
> @davvd I need more time here. I'm waiting for final merge in #500 

@xupyprmv of course, thanks for letting me know, take your time

**Comment by xupyprmv** [comment]
@HDouss PR #500 was merged. Please, close this ticket.

**Comment by HDouss** [comment]
@xupyprmv Thanks.

**Comment by davvd** [comment]
@ypshenychka please, check this issue for QA compliance, as per [par.24](http://at.teamed.io/policy.html#24)

**Comment by ypshenychka** [comment]
@davvd Quality is good.

**Comment by davvd** [comment]
> @davvd Quality is good.

@ypshenychka thank you

**Comment by davvd** [comment]
@xupyprmv added 10 mins to @ypshenychka, for QA review, payment code is `74687392`. Thanks a lot, I just topped your account for **45 mins**, transaction ID `AP-8G752125HJ053240A`, total time was 32 hours and 9 mins. m=1929, that's why a bonus here for fast delivery. +45 to your rating, your total score is [+60](http://www.netbout.com/b/35999?open=rating)
