### ISSUE TITLE
TkProxyTest.java:40-42: We need more tests for...

### ISSUE THREAD

**Issue by davvd** [yegor256/takes#458]
Puzzle `377-e6ce369a` in `src/test/java/org/takes/tk/TkProxyTest.java:40-42` has to be resolved: We need more tests for TkProxy. The tests should verify the different HTTP methods (GET, POST, etc), as well as the different combinations of request/response headers.... The puzzle was created by bdragan on 7-Dec-2015.

If you have any technical questions, don't ask me, submit new tickets instead

<hr id='w'>

**Comment by davvd** [comment]
@yegor256 since there is no milestone yet I set it to "1.0"

**Comment by davvd** [comment]
@aschworer the task is for you now, follow [these guidelines](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html). Don't hesitate to ask any technical questions right here; The budget here is **30 mins**, which is exactly how much time will be paid for, when the task is [completed](http://www.xdsd.org/2014/04/15/definition-of-done.html)

**Comment by aschworer** [comment]
@davvd fighting with checkstyles for now. will need a bit more time, same for #430

**Comment by aschworer** [comment]
@davvd i've created a pull request, please review

**Comment by davvd** [comment]
> @davvd fighting with checkstyles for now. will need a bit more time, same for #430

@aschworer of course, thanks for letting me know, take your time

**Comment by davvd** [comment]
@alexey-krylov could you please pick this up? This [article](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html) explains how we work. Any technical questions you may ask right here. The budget of this issue is **30 mins**, which is exactly how much will be paid when the task is *done* (see [this](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html) for explanation)

**Comment by davvd** [comment]
@sebing this ticket is yours now, please proceed, and keep in mind [this](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html). Any technical questions you should ask right here

Task's budget is **30 mins** (see [this](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html) for explanation)

**Comment by sebing** [comment]
@davvd As I am new here. Let me state what I understood from the thread.
- I have to extend the functionality of testClass for `TkProxy` to support both the GET and POST Methods.

**Comment by sebing** [comment]
@davvd  I have made a pull request.
There is an error in the checkstyle.
[ERROR] \src\test\java\org\takes\tk\TkProxyTest.java[92]: Name 'httpMethod' must match pattern '^[a-z]{3,}$'. (ParameterNameCheck)

I thought, httpMethod is a valid pattern. I didn't correct it as I would like to know the problem so I won't be making it again :)

**Comment by sebing** [comment]
@yegor256 why we cannot have upper case in the parameter name? I thought httpMethod is a good name :)

**Comment by sebing** [comment]
@davvd  I changed the variable to smaller case, now the checkstyle passes.

**Comment by sebing** [comment]
I understood the answer to my questions here :) (http://www.yegor256.com/2015/01/12/compound-name-is-code-smell.html)

**Comment by sebing** [comment]
@davvd can we close this issue as the pull request is merged?

**Comment by sebing** [comment]
@davvd can you close this issue?

**Comment by davvd** [comment]
> @davvd can we close this issue as the pull request is merged?

@sebing will close soon, right after the next deployment cycle

**Comment by sebing** [comment]
@davvd any update on this issue?

**Comment by sebing** [comment]
@davvd this task is merge about a month back. Why we did not deployed this? When will we closed this issue?

**Comment by davvd** [comment]
> @davvd any update on this issue?

@sebing the task will be closed when the puzzle is removed from the source code

**Comment by davvd** [comment]
> @davvd this task is merge about a month back. Why we did not deployed this? When will we closed this issue?

@sebing I believe the puzzle is still in the source code

**Comment by sebing** [comment]
@yegor256 @davvd I see  the changes are not in the master even though the merge and deploy was success for this pr(https://github.com/yegor256/takes/pull/551/). Can I get some help for this?

**Comment by sebing** [comment]
@davvd I have made a new PR for the changes(https://github.com/yegor256/takes/pull/650)

**Comment by yegor256** [comment]
@sebing be careful with your fork. as I see, you're working in `master` branch in your branch. it's a bad idea. check this article: http://www.yegor256.com/2014/04/15/github-guidelines.html

**Comment by sebing** [comment]
@yegor256 Thanks for the article. I will be careful in the future.

**Comment by sebing** [comment]
@davvd as the PR(https://github.com/yegor256/takes/pull/650) is closed, can you close this issue?

**Comment by davvd** [comment]
@yegor256 once `458-ca123cf9` puzzle is resolved (later, in another ticket), this ticket will be fully complete

**Comment by davvd** [comment]
@yegor256 Finished, thanks, closing..

**Comment by davvd** [comment]
@ypshenychka please, review this ticket for compliance with our [QA rules](http://at.teamed.io/qa.html)

**Comment by ypshenychka** [comment]
@davvd Quality is good.

**Comment by davvd** [comment]
> @davvd Quality is good.

@ypshenychka thanks, got it, great to see high-quality tickets here

**Comment by davvd** [comment]
@sebing just added 10 mins to @ypshenychka (for QA), payment ID is `81275141`; Much appreciated! **30 mins** was added to your account, payment ID `56f25f84dfebd866f4000028`, time spent is 1277 hours and 46 mins; added +30 to your rating, now it is equal to [+135](http://www.netbout.com/b/36309?open=rating)

**Comment by davvd** [comment]
@yegor256 last puzzled solved `458-ca123cf9`/#656
