### ISSUE TITLE
RsWithCookie must reject if invalid characters

### ISSUE THREAD

**Issue by yegor256** [yegor256/takes#46]
`RsWithCookie` must reject (throw runtime exception) when its ctor is called with name or value containing invalid (unprintable) characters. Let's create a test reproducing this situation and also let's document what RFC we're using to check for character validity.

**Comment by davvd** [comment]
@yegor256 got it, tag `bug` is here

**Comment by davvd** [comment]
@yegor256 thanks for the report, I topped your acc for 15 mins, payment ID `000-873ef5af`

**Comment by davvd** [comment]
@popprem this task is yours, please help (see our key [principles of work](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html)). If you have any technical questions, don't hesitate to ask right here

The budget here is **30 mins**, which is exactly how much time will be paid for, when the task is [completed](http://www.xdsd.org/2014/04/15/definition-of-done.html)

**Comment by popprem** [comment]
davvd / Yegor,

Sorry for the delay. I'm in the process of shifting to a new house with family. I will start working on this project from Monday (30th of March 2015).

Thanks.

**Comment by davvd** [comment]
@popprem the ticket is with you for 15 days already. If it is not finished in the next 48 hours, it will be re-assigned to someone else, see [No Obligations](http://www.xdsd.org/2014/04/13/no-obligations-principle.html) principle, [this article](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html) should help if you're stuck. -30 added to your rating, current score is: [-30](http://www.netbout.com/b/35169?open=rating)

**Comment by popprem** [comment]
@davvd Sorry, got internet connection yesterday only. 
Completed this task but unable to push the changes, getting permission denied error. Could you please advice on this?

**Comment by yegor256** [comment]
@popprem you should use forks and pull requests, see http://www.yegor256.com/2014/04/15/github-guidelines.html

**Comment by popprem** [comment]
@yegor256 How do you execute local build? Earlier i did "mvn package", was successful... checked in the changes but Appveyor failed with checkstyle issues. Now i tried to execute build with com.qulice:qulice-maven-plugin:check goal, but getting loads of checkstyle issues in many classes.

**Comment by yegor256** [comment]
@popprem check README.md, there is an explanation

**Comment by davvd** [comment]
@popprem you've been working with this task for too long. I'm sorry, but I'll assign someone else. Please stop working with it. See our [no obligations](http://www.xdsd.org/2014/04/13/no-obligations-principle.html) principle... -60 added to your rating, at the moment it is: [-90](http://www.netbout.com/b/35169?open=rating)

**Comment by popprem** [comment]
@davvd But David, this fix has been waiting for #148 . Pls check the pull request #134.

**Comment by yegor256** [comment]
@popprem  see http://www.teamed.io/policy.html#7

**Comment by popprem** [comment]
@yegor256 Understood, thanks.

**Comment by YamStranger** [comment]
@yegor256. @popprem you can not wait for me. You can do next: set global .gitattributes file(download it from my commits,  "git config --global core.attributesfile file_path") -it will apply to all repositories, where .gitattributes file not exists. Next time when you clone (may for checkout too, I am not sure) git will apply correct end line char (\n) to repository, and files on them and gulice will be happy.

**Comment by popprem** [comment]
@YamStranger Thanks, applied the same. 
@davvd @yegor256 Pull request #169 created for this issue. Please review.

**Comment by davvd** [comment]
@dmzaytsev please go ahead with this task, it's yours

**Comment by dmzaytsev** [comment]
@yegor256 please see the PR #176 
close the task if alright

**Comment by yegor256** [comment]
@dmzaytsev many thanks!

**Comment by davvd** [comment]
@yegor256 since there is no milestone yet I set it to "1.0"

**Comment by davvd** [comment]
@elenavolokhova please, let us know what do you think about this ticket, according to our [QA rules](http://www.teamed.io/qa.html)

**Comment by elenavolokhova** [comment]
@dmzaytsev 
>popprem commented 24 days ago
davvd / Yegor,
Sorry for the delay. I'm in the process of shifting to a new house with family. I will start working on this project from Monday (30th of March 2015).

 According to our [quality rules](http://www.teamed.io/qa.html):
 > Messages in a ticket always start with a name of a user they are addressed to.
 
 As far as you are the performer of this ticket you are responsible for its quality. Please make sure that everyone follows this rule in your tickets in the future. Ask them to fix issues before closing the ticket.
 
 Please confirm that everything is clear and you have no questions regarding this approach.

**Comment by dmzaytsev** [comment]
@elenavolokhova everything is clear. I confirm

**Comment by elenavolokhova** [comment]
@davvd Ticket passed QA review. Quality is acceptable.

**Comment by davvd** [comment]
> @davvd Ticket passed QA review. Quality is acceptable.

@elenavolokhova thanks for the review, we'll try better next time

**Comment by davvd** [comment]
@dmzaytsev I added 10 mins to @elenavolokhova (for QA review) in transaction 55835838. Much appreciated! **1 hour** was added to your account, payment ID `55835882`, time spent is 71 hours and 13 mins. age=2, that's why a bonus here for fast delivery. +60 to your rating, your total score is [+776](http://www.netbout.com/b/35166?open=rating)
