### ISSUE TITLE
FkContentType should have a Take rather than a Response

### ISSUE THREAD

**Issue by HDouss** [yegor256/takes#461]
FkContentType is built with a Response. To handle more general use cases like `Content-Type: text/html; charset=...`, it should be built with a Take that will handle the request dynamically.

**Comment by davvd** [comment]
@yegor256 dispatch this issue please, see [par.21](http://at.teamed.io/policy.html#21)

**Comment by yegor256** [comment]
@HDouss I'm not sure I understand... can you give a code example please?

**Comment by HDouss** [comment]
@yegor256 Right now what we can do with `FkContentType` is responding with a fixed response like in this example : 
````Java
        new FtBasic(
            new TkFork(
                new FkContentType(
                    "text/html",
                    new RsText("Hi")
                )
            ),
            8080
        ).start(Exit.NEVER);
```
We don't have any mean to make the response dynamic (request dependent).
Let's say for example, responding with a text "Hello *dude*", where *dude* is a value of a request parameter *name*. Something like : 
```Java
        new FtBasic(
            new TkFork(
                new FkContentType(
                    "text/html",
                    new Take() {
                        @Override
                        public Response act(Request req) throws IOException {
                            String value = new RqHref.Smart(new RqHref.Base(req)).single("name");
                            return "Hello "+ value;
                        }
                    }
                )
            ),
            8080
        ).start(Exit.NEVER);
```

**Comment by longtimeago** [comment]
@yegor256 ping :)

**Comment by yegor256** [comment]
@HDouss got it, make sense

**Comment by davvd** [comment]
@hdouss since the ticket has no milestone I set it to 1.0

**Comment by davvd** [comment]
@hdouss thanks for the ticket, your account was topped for 15 mins, payment 79175665

**Comment by davvd** [comment]
@dalifreire the task is for you now, follow [these guidelines](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html). Don't hesitate to ask any technical questions right here. The budget of this task is **30 mins**. This is exactly how much time will be compensated, when the task is completed. Read about our [Definition of Done](http://www.xdsd.org/2014/04/15/definition-of-done.html)

**Comment by dalifreire** [comment]
@davvd I'm in. Thanks.
@HDouss Could you better explain what I have to do? Do you need that the actual constructor be replaced by another constructor that builds the FkContentType with a Take?

**Comment by HDouss** [comment]
@dalifreire Yes. The general idea is that `FkContentType`, like almost all other `Fork`s depend on a Take and not a "static" response. So, start by modifying the constructor and the implementation and investigate if there is other impacts.

**Comment by dalifreire** [comment]
@HDouss I got it, thanks! Could you take a look at PR #639. I'm on the right way?

**Comment by HDouss** [comment]
@dalifreire yes.

**Comment by dalifreire** [comment]
@HDouss @davvd PR #639 merged, could you close this issue?

**Comment by HDouss** [comment]
@dalifreire Thanks.

**Comment by dalifreire** [comment]
@davvd Please, proceed...

**Comment by davvd** [comment]
@ypshenychka please, check this issue for QA compliance, as per [par.24](http://at.teamed.io/policy.html#24)

**Comment by ypshenychka** [comment]
@davvd Quality is good.

**Comment by davvd** [comment]
> @davvd Quality is good.

@ypshenychka thanks for the review and a good remark

**Comment by davvd** [comment]
@dalifreire paied 10 mins to @ypshenychka for QA review (payment ID is `79775175`); done, I added **30 mins** in payment `79775184`, 102 hours and 46 mins spent to complete this; +30 added to your rating, current score is: [+135](http://www.netbout.com/b/36485?open=rating)
