### ISSUE TITLE
RqWithBodyTest, RqMultipartTest, RqFormTest and RqGreedyTest should precise Content-Length

### ISSUE THREAD

**Issue by HDouss** [yegor256/takes#463]
Requests on these tests : RqWithBodyTest, RqMultipartTest, RqLengthAwareTest, RqFormTest and RqGreedyTest should send a Content-Length header with proper value. More precisely, these are the tests that need to be modified : 
```
  RqFormTest.createsFormRequestWithParams
  RqFormTest.parsesHttpBody
  RqGreedyTest.makesRequestGreedy
  RqLengthAwareTest.readsByte 
  RqLengthAwareTest.readsByteArray
  RqLengthAwareTest.readsPartialArray
  RqWithBodyTest.returnsBody
  RqMultipartTest.consumesHttpRequest
  RqMultipartTest.notDistortContent
  RqMultipartTest.parsesHttpBody
  RqMultipartTest.returnsCorrectNamesSet
  RqMultipartTest.returnsCorrectPartLength
  RqMultipartTest.returnsEmptyIteratorOnInvalidPartRequest
  RqMultipartTest.satisfiesEqualsContract
```

**Comment by davvd** [comment]
@yegor256 please pay attention to this issue ([par.21](http://at.teamed.io/policy.html#21))

**Comment by yegor256** [comment]
@HDouss I don't understand what exactly is broken now... check this: http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html#5.-report-when-it-is-broken

**Comment by HDouss** [comment]
@yegor256 Actually the tests are passing because of a side effect of a bug in RqPrint (see #438). A proper request with a body must specify the body message (either by Content-Length header or by a Chunked body), so the server can know when the body is done. This become crucial with HTTP 1.1 since the client does not have to close the connection. The server side could only figure out the end of the body by : 
* The connection is closed
* The Content-Length header value
* A new line in a chuncked transfer

**Comment by HDouss** [comment]
@yegor256 In other terms, having a proper RqPrint implementation that assumes an empty body if Content-Length is not defined (in case of non-chunked message) will lead to the fail of these tests who should anyway precise Content-Length to be correctly read.

**Comment by yegor256** [comment]
@HDouss you're saying that these tests must fail when `Content-Length` is absent, but they don't. right? that's the bug?

**Comment by HDouss** [comment]
@yegor256 In some way, that's what I'm trying to say. The bug is that these tests are not sending proper requests (absence of content-length). Now, to explain why this is a bug, and why the tests were passing until now, I tried to describe the good implementation of RqPrint (which is not the case now) that will make the test fail. RqPrint have to assume empty body when content-length is not defined. Such an assumption will make the tests fail.

**Comment by HDouss** [comment]
@yegor256 updated description to exhaustively list all the test methods to modify.

**Comment by yegor256** [comment]
@HDouss got it thanks

**Comment by davvd** [comment]
@hdouss attached this issue to milestone "1.0" (let me know if this is wrong)

**Comment by davvd** [comment]
@happy-neko the task is for you now, follow [these guidelines](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html). Don't hesitate to ask any technical questions right here... Task's budget is **30 mins** (see [this](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html) for explanation)

**Comment by davvd** [comment]
@hdouss thank you for the ticket reported, I topped your account for 15 mins, transaction `72946073`

**Comment by HDouss** [comment]
@Happy-Neko PR #478 is reviewed and merged. I will close the issue. Please ask me to do it next time once your PR is merged.

**Comment by Happy-Neko** [comment]
@HDouss ok

**Comment by HDouss** [comment]
@Happy-Neko I reopened the issue. The PR lacks content-length for `RqFormTest.createsFormRequestWithParams`

**Comment by Happy-Neko** [comment]
@HDouss what the point of setting `Content-Length` header in this case if created request is not processed anywhere? What behaviour this will test?

**Comment by HDouss** [comment]
@Happy-Neko The point is to have a valid request. Every request with no content-length (or chunked) have to be considered as a bodyless request. In that case, the fact that we pass the request to `RqForm.Base` is a form of "processing" it (and we are actually processing it in `RqForm.Base`).

**Comment by davvd** [comment]
@happy-neko this task is in your hands for 15 days already. -30 to your rating, your total score is [+68](http://www.netbout.com/b/36136?open=rating)

**Comment by Happy-Neko** [comment]
@HDouss 
Ok. Header added in PR #499.

**Comment by HDouss** [comment]
@Happy-Neko That's good. Thank you !
It would be better that the value `49` would be calculated from parameter lengthes rather than hard coded.

**Comment by Happy-Neko** [comment]
@HDouss done.

**Comment by HDouss** [comment]
@Happy-Neko The point of : 
>It would be better that the value 49 would be calculated from parameter lengthes rather than hard coded.

is that when someday we would want to change the keys or the values in the unit test, we just change the value, we don't have to bother about its length and change the value 49 accordingly. So the change happen only in one place. After your last change I have to change the key (or value), and then change also the `body` variable.

**Comment by Happy-Neko** [comment]
@HDouss done.

**Comment by HDouss** [comment]
@Happy-Neko I will close the issue as soon as PR is merged. I suggest you notify PM of need of more time if reviewer is not reactive.

**Comment by HDouss** [comment]
@Happy-Neko I suggest to notify PM here, not in the PR.

**Comment by Happy-Neko** [comment]
@HDouss thanks.
@davvd consider increasing time limit until code review is done.

**Comment by Happy-Neko** [comment]
@HDouss PRs merged. 
Please close the ticket if everything is ok.

**Comment by HDouss** [comment]
@Happy-Neko Thanks.

**Comment by davvd** [comment]
@ypshenychka please, review this task for compliance with our [quality rules](http://at.teamed.io/qa.html)

**Comment by ypshenychka** [comment]
@davvd Quality is good here.

**Comment by davvd** [comment]
> @davvd Quality is good here.

@ypshenychka thank you

**Comment by davvd** [comment]
@happy-neko 10 mins was added to the account of @ypshenychka (for QA review), in transaction 74525927. Thanks so much! Your account was topped up for **30 mins** (transaction ID is `74525954`, the task took 478 hours and 18 mins). +30 added to your rating, at the moment it is: [+68](http://www.netbout.com/b/36136?open=rating)
