### ISSUE TITLE
RsFlash is not tested

### ISSUE THREAD

**Issue by yegor256** [yegor256/takes#47]
`RsFlash` is not tested, let's create a unit test for it. Besides that, the class doesn't use the logging level provided anyhow. It simply ignores this parameter. Instead, it has to package the message and the logging level together in a single string and send them in Base64 format to the cookie. Without that we may have issues with unprintable characters inside the message.

**Comment by davvd** [comment]
@yegor256 thanks, I added the "bug" tag

**Comment by davvd** [comment]
@yegor256 thanks for the report, I topped your acc for 15 mins, payment ID `000-c0865f31`

**Comment by davvd** [comment]
@mgovorischev can you please help? Keep in mind [this](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html). If you have any technical questions, don't hesitate to ask right here. Task's budget is **30 mins** (see [this](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html) for explanation)

**Comment by mgovorischev** [comment]
What is the format of the string that contains log level and message and is then sent to the cookie? What is the delimiter?

**Comment by yegor256** [comment]
@mgovorischev it's up to you to decide. now we're using a simple string without any formatting, as you see. but we should package the message and the log level somehow. maybe 

```
URLEncode(msg) + "/" + URLEncode(level)
```

in this case we won't need Base64

**Comment by davvd** [comment]
@dmzaytsev it's yours now, please proceed keeping in mind [our principles](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html). Feel free to ask any technical questions right here in the ticket

**30 mins** is the budget of the task. This is exactly how much will be paid when the problem is [solved](http://www.xdsd.org/2014/04/15/definition-of-done.html) (no matter how much time you will actually spend). See [this](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html) for more information

**Comment by dmzaytsev** [comment]
@yegor256 @davvd 
I need more time to perform additional requirements.
https://github.com/yegor256/takes/pull/78#issuecomment-86815066
May be better to create another task for this ?
What do you think ?

**Comment by yegor256** [comment]
@dmzaytsev you can try to use PDD (http://www.yegor256.com/2009/03/04/pdd.html). But we can't let these changes into the master, since they will break the entire "flash" functionality. It will basically stop working.

**Comment by dmzaytsev** [comment]
@yegor256 @davvd 
as I understand it, PDD is not suitable in this case.
Can we make a new task (TsFlash modification + unit test) and assign it to me?
I will complete both tasks(#47 and the new task)  in the same pull request.

**Comment by yegor256** [comment]
@dmzaytsev we never mix tasks, we work with them individually, always. In this case, I would add a decrypting functionality to TsFlash and that's it. If you really want to avoid that, you should step back, remove the functionality you implemented, create a test that reproduces the connectivity between TsFlash and RsFlash, and add a `@todo` puzzle requesting the implementation of the desired functionality. In my opinion, that's more work (but that would the right/perfect way)

**Comment by dmzaytsev** [comment]
@yegor256 the PR #78 merged
take a look at the changes
if you accept it close the task please

**Comment by yegor256** [comment]
@dmzaytsev thanks!

**Comment by davvd** [comment]
@elenavolokhova please, review this task for compliance with our [quality rules](http://www.teamed.io/qa.html)

**Comment by elenavolokhova** [comment]
@davvd This ticket looks good! :)

**Comment by davvd** [comment]
> @davvd This ticket looks good! :)

@elenavolokhova thanks for the QA review

**Comment by davvd** [comment]
@dmzaytsev just added 10 mins to @elenavolokhova (for QA), payment ID is `54704490`; I added **38 mins** to your account, many thanks for working with the project! The completion time here was 54704500.; the bonus for fast delivery (age=2888); +38 added to your rating, current score is: [+286](http://www.netbout.com/b/35166?open=rating)
