### ISSUE TITLE
RqHref.java:83-86: RqMethod already validates Request-Line and...

### ISSUE THREAD

**Issue by davvd** [yegor256/takes#473]
Puzzle `445-5323c196` in `src/main/java/org/takes/rq/RqHref.java:83-86` has to be resolved: RqMethod already validates Request-Line and extracts HTTP Method from it. We should extract all important information from Request-Line (HTTP method, URI and HTTP version) in one place to enforce DRY principle.... The puzzle was created by Ikar Sokolov on 15-Dec-2015.

If you have any technical questions, don't ask me, submit new tickets instead

**Comment by davvd** [comment]
@xupyprmv please go ahead, it's your task now, keep [this](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html) in mind, and don't hesitate to ask any technical questions you may have. Budget here is **30 mins** (keep [this principle](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html) in mind)

**Comment by davvd** [comment]
@yegor256 there is no milestone yet, so I set it to `1.0`

**Comment by davvd** [comment]
@xupyprmv you're holding this ticket for 15 days already. If it is not finished (and closed) in the next 48 hours, it will be re-assigned to someone else, see [No Obligations](http://www.xdsd.org/2014/04/13/no-obligations-principle.html) principle ([this article](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html) should help if you're stuck). as a reminder, don't forget to remove the `@todo` puzzle from the source code. -30 added to your rating, at the moment it is: [-30](http://www.netbout.com/b/35999?open=rating)

**Comment by xupyprmv** [comment]
@davvd The PR #484 is on CR by @yegor256. It's not my fault.

**Comment by yegor256** [comment]
@xupyprmv everything is your fault, until the task is done. this is our philosophy. when you see that the task is delayed, do something about it. ask @davvd, or me, but don't just wait. we're not managing you, you're managing yourself. I would recommend to read the policy again: http://at.teamed.io/policy

**Comment by davvd** [comment]
> @davvd The PR #484 is on CR by @yegor256. It's not my fault.

@xupyprmv everything is your fault while you're working with a ticket, see http://at.teamed.io/policy.html#7

**Comment by xupyprmv** [comment]
@davvd I need more time for that ticket. PR #484 is on CR and it will be merged soon, because last CR result doesn't contain any significant remarks.

**Comment by xupyprmv** [comment]
@davvd This issue is fixed. PR #484 was merged. Please close this ticket if you have no more remarks.

**Comment by davvd** [comment]
> @davvd I need more time for that ticket. PR #484 is on CR and it will be merged soon, because last CR result doesn't contain any significant remarks.

@xupyprmv agreed, take your time

**Comment by davvd** [comment]
> @davvd This issue is fixed. PR #484 was merged. Please close this ticket if you have no more remarks.

@xupyprmv sure, will do right after the next deployment cycle

**Comment by davvd** [comment]
@yegor256 The task is closed, thanks everybody

**Comment by davvd** [comment]
@ypshenychka please, help us to evaluate quality here, as per [par.24](http://at.teamed.io/policy.html#24)

**Comment by ypshenychka** [comment]
@davvd Quality is good.

**Comment by davvd** [comment]
> @davvd Quality is good.

@ypshenychka thank you

**Comment by davvd** [comment]
@xupyprmv I added 10 mins to @ypshenychka (for QA review) in transaction 74072046; Much appreciated! **30 mins** was added to your account, payment ID `AP-3SK1209573502924F`, time spent is 458 hours and 56 mins; added +30 to your rating, now it is equal to [+15](http://www.netbout.com/b/35999?open=rating)
