### ISSUE TITLE
why default media type has been changed?

### ISSUE THREAD

**Issue by dmzaytsev** [yegor256/takes#475]
this line 
https://github.com/yegor256/takes/commit/c6a98c9ff6ceb47f427fb1df0423fc8a3980f2e5#diff-3628fdd06e17f22ff51a01c1aa51515aR92
has been changed from 

```
list = new MediaTypes("*/*");
```

to

```
list = new MediaTypes("text/html");
```

in commit c6a98c9ff6ceb47f427fb1df0423fc8a3980f2e5
unfortunately I don't see any PR(or an issue) related to the commit
Why was this done? 
Is it bug or feature?

**Comment by yegor256** [comment]
@dmzaytsev it's a feature. if no content type is provided by the browser, we must assume that `text/html` is expected. If we put `*/*` there, `text/xml` or `application/json` will be returned, for example, which is not what the browser is ready to process.

**Comment by yegor256** [comment]
@dmzaytsev you think I should put some documentation into the code about it?

**Comment by dmzaytsev** [comment]
@yegor256 yep, it would be nice to update readme
I can update the ticket description if needed

**Comment by 0crat** [comment]
Job `gh:yegor256/takes#475` is not assigned, can't get performer

**Comment by 0crat** [comment]
This job is not in scope
