### ISSUE TITLE
RqMethod is not tested

### ISSUE THREAD

**Issue by yegor256** [yegor256/takes#48]
There is no unit test for `RqMethod` class, let's create one.

**Comment by davvd** [comment]
@yegor256 sure, thanks, I added bug tag to it

**Comment by davvd** [comment]
@yegor256 thanks for this report, I added 15 mins to your account, in transaction `000-a8e68bd6`

**Comment by davvd** [comment]
@dmzaytsev the task is for you now, follow [these guidelines](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html). Don't hesitate to ask any technical questions right here; Total fixed cost of this task is **30 mins** (see [this](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html) for more info)

**Comment by pinaf** [comment]
@dmzaytsev make sure you inform the project manager here, in the issue, of the PR.

**Comment by dmzaytsev** [comment]
@pinaf thanks

@davvd i am writing to inform you that the PR has been merged
@yegor256 could you confirm please that issue has been resolved?

**Comment by yegor256** [comment]
@dmzaytsev thanks!

**Comment by davvd** [comment]
@dmzaytsev **30 mins** was added to your account, many thanks for your contribution!

+30 added to your rating, current score is: [+60](http://www.netbout.com/b/35166?open=rating)
