### ISSUE TITLE
HmRsHeader fails match if header name is not all-lowercase

### ISSUE THREAD

**Issue by carlosmiranda** [yegor256/takes#480]
This test **succeeds**:

```java
    @Test
    public void testHmRsHeader() {
        MatcherAssert.assertThat(
            new RsWithHeader("location", "/bar/baz"),
            new HmRsHeader("location", "/bar/baz")
        );
    }
```

This test - almost exactly the same, but the first letter of `Location` is capitalized, **fails**:

```java
    @Test
    public void testHmRsHeader() {
        MatcherAssert.assertThat(
            new RsWithHeader("Location", "/bar/baz"),
            new HmRsHeader("Location", "/bar/baz")
        );
    }
```

Meanwhile, this test, with a response that has an uppercase "L" and a matcher was supplied with a lowercase "l" **succeeds**, :

```java
    @Test
    public void testHmRsHeader() {
        MatcherAssert.assertThat(
            new RsWithHeader("Location", "/bar/baz"),
            new HmRsHeader("location", "/bar/baz")
        );
    }
```

Checking of header name should be case-insensitive, in accordance with [HTTP spec](http://www.w3.org/Protocols/rfc2616/rfc2616-sec4.html#sec4.2). Note that this bug not only confusing, it precludes us from using constant values in classes such as `HttpHeaders`.

**Comment by davvd** [comment]
@carlosmiranda I will ask someone to take care of this task soon

**Comment by davvd** [comment]
@carlosmiranda attached this issue to milestone "1.0" (let me know if this is wrong)

**Comment by davvd** [comment]
@happy-neko the task is for you now, follow [these guidelines](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html). Don't hesitate to ask any technical questions right here

The cost of this task is **30 mins** (this is exactly how much will be paid, not less not more), when the task is [done](http://www.xdsd.org/2014/04/15/definition-of-done.html)

**Comment by davvd** [comment]
@carlosmiranda many thanks for the report, I topped your account for 15 mins, transaction 73019344

**Comment by davvd** [comment]
@happy-neko you're working with this issue for 15 days already... -30 to your rating, your total score is [+38](http://www.netbout.com/b/36136?open=rating)

**Comment by Happy-Neko** [comment]
@davvd PR was merged 3 days ago. What exactly do you want me to do?

**Comment by Happy-Neko** [comment]
@carlosmiranda please review this ticket and close it if problem is solved.

**Comment by carlosmiranda** [comment]
@Happy-Neko Please link to the PR that solved this, then I can close it. Thanks

**Comment by Happy-Neko** [comment]
@carlosmiranda PR https://github.com/yegor256/takes/pull/483.

**Comment by carlosmiranda** [comment]
@Happy-Neko looks good, thanks!

**Comment by Happy-Neko** [comment]
@davvd ticket is closed.

**Comment by davvd** [comment]
@ypshenychka review this ticket please, for compliance with our [quality rules](http://at.teamed.io/qa.html)

**Comment by ypshenychka** [comment]
@davvd Quality is good here.

**Comment by davvd** [comment]
> @davvd Quality is good here.

@ypshenychka thanks a lot

**Comment by davvd** [comment]
@happy-neko paied 10 mins to @ypshenychka for QA review (payment ID is `74444782`); Thanks for your contribution, **30 mins** was added to your account, payment ID is `74444794`, 403 hours and 42 mins spent total; added +30 to your rating, now it is equal to [+38](http://www.netbout.com/b/36136?open=rating)
