### ISSUE TITLE
Very confusing test failure message when using `HmRsStatus`

### ISSUE THREAD

**Issue by carlosmiranda** [yegor256/takes#481]
Consider the following test:

```java
    @Test
    public void testRsStatus() {
        MatcherAssert.assertThat(
            new RsWithStatus(500),
            new HmRsStatus(200)
        );
    }
```

Obviously, this will fail. The failure message looks something like this:

```
java.lang.AssertionError: 
Expected: <200>
     but: was <RsWithStatus(super=RsWrap(origin=org.takes.rs.RsWithStatus$1@76ccd017))>
	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:8)
...
```

This message is very confusing:

* Expected value - what is "200"? If I have just a handful of tests that test for a bunch of HTTP statuses, then it's clear. But if I have dozens of tests, this expected message does not give me any info on the significance of "200".
* Actual value - I see a bunch of generic Object descriptions, but I don't see what the actual HTTP status really is.

We should revise the code such that it looks similar to the following:

```
java.lang.AssertionError: 
Expected: <HTTP status code: 200 OK>
     but: was <HTTP status code: 500 Internal Error>
```

**Comment by davvd** [comment]
@carlosmiranda I will ask someone to take care of this task soon

**Comment by davvd** [comment]
@carlosmiranda I set milestone here to `1.0`, let me know if it is wrong

**Comment by davvd** [comment]
@carlosmiranda thanks for the ticket, your account was topped for 15 mins, payment 73018843

**Comment by davvd** [comment]
@exper0 please pick this up, and keep in mind [these instructions](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html). Any technical questions - ask right here; This task's budget is **30 mins**. This is exactly how much will be paid when the problem explained above is solved. See [this](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html) for more information

**Comment by exper0** [comment]
@davvd done @carlosmiranda now it looks like this:
Expected: HTTP status code <200>
     but: HTTP status code was <500>

**Comment by exper0** [comment]
pr #487

**Comment by carlosmiranda** [comment]
@exper0 Thanks, let's wait for PR merge.

**Comment by exper0** [comment]
@carlosmiranda done, PR #487 was reviewed, merged and closed. Please close the ticket

**Comment by carlosmiranda** [comment]
@exper0 thanks!

**Comment by davvd** [comment]
@ypshenychka please, help us to evaluate quality here, as per [par.24](http://at.teamed.io/policy.html#24)

**Comment by ypshenychka** [comment]
@davvd Quality is good.

**Comment by davvd** [comment]
> @davvd Quality is good.

@ypshenychka thanks, got it, great to see high-quality tickets here

**Comment by davvd** [comment]
@exper0 I added 10 mins to @ypshenychka (for QA review) in transaction 74039786

paid, thanks, added **30 mins** to your account, payment `AP-1PR40482MB819742B`, 306 hours and 42 mins was spent

added +30 to your rating, now it is equal to [+165](http://www.netbout.com/b/36185?open=rating)
