### ISSUE TITLE
Very confusing test failure message when using `HmRsHeader`

### ISSUE THREAD

**Issue by carlosmiranda** [yegor256/takes#482]
Consider the following test:

```java
    @Test
    public void testRsHeader() {
        MatcherAssert.assertThat(
            new RsWithHeader("content-type", "text/html"),
            new HmRsHeader("content-type", "image/png")
        );
    }
```

It fails (pretty trivial). But this is the failure message:

```
TkSwitchTest.testRsHeader
testRsHeader(com.xockets.xjm.http.TkSwitchTest)
java.lang.AssertionError: 
Expected: entry containing ["content-type"->"image/png"]
     but: was <RsWithHeader(super=RsWrap(origin=org.takes.rs.RsWithHeader$1@7637f22))>
```

The "expected" value was pretty clear in what the test was expecting. However, the actual value displayed is a generic object signature and is not useful at all. It would be much better if it outputted a list of the actual header fields in the response.

**Comment by davvd** [comment]
@carlosmiranda I will find a developer for the task soon...

**Comment by davvd** [comment]
@carlosmiranda milestone set to `1.0` (correct me if I am wrong)

**Comment by davvd** [comment]
@exper0 can you please help? Keep in mind [this](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html). If you have any technical questions, don't hesitate to ask right here; Task's budget is **30 mins** (see [this](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html) for explanation)

**Comment by davvd** [comment]
@carlosmiranda thanks for this report, I added 15 mins to your account, in transaction `73016940`

**Comment by exper0** [comment]
@davvd sure, I'll look into it

**Comment by exper0** [comment]
@davvd done @carlosmiranda now it looks like this:
Expected: header: equalToIgnoringCase("content-type") -> values: (a collection containing "image/png")
     but: header was: equalToIgnoringCase("content-type") -> values: <[text/html]>

It's not so nice but I hope it's clear enough - I tried not to over-complicate it. Let me know if you are ok with it.
It's in PR #488

**Comment by carlosmiranda** [comment]
@exper0 Thanks, much clearer than in the beginning. Let's wait for PR review and merge.

**Comment by exper0** [comment]
@carlosmiranda done, PR #488 was reviewed and close. Please close the ticket

**Comment by carlosmiranda** [comment]
@exper0 thanks!

**Comment by davvd** [comment]
@elenavolokhova please, let us know what do you think about this ticket, according to our [QA rules](http://at.teamed.io/qa.html)

**Comment by elenavolokhova** [comment]
@davvd Looks good!

**Comment by davvd** [comment]
> @davvd Looks good!

@elenavolokhova thanks a lot ;)

**Comment by davvd** [comment]
@exper0 added 10 mins to @elenavolokhova, for QA review, payment code is `74074894`. **30 mins** sent to your balance (ID `AP-6TX09999M0024681F`), many thanks! It took 312 hours and 17 mins.. +30 added to your rating, current score is: [+195](http://www.netbout.com/b/36185?open=rating)
