### ISSUE TITLE
HmRsBody matcher for checking response body

### ISSUE THREAD

**Issue by carlosmiranda** [yegor256/takes#485]
At the moment we have `HmRsHeader` and `HmRsStatus` which allows us to use Hamcrest to match against `Response` headers or status codes, respectively.

It would be good if we have a class `HmRsBody` that will allow us to match the `Response` body as well. Let's create one, with public constructors that can accept `Matcher<String>` and `Matcher<byte[]>`, to support both text and binary responses.

**Comment by exper0** [comment]
@carlosmiranda @davvd ready to take this

**Comment by carlosmiranda** [comment]
@yegor256 what do you think?

**Comment by davvd** [comment]
@yegor256 dispatch this issue please, see [par.21](http://at.teamed.io/policy.html#21)

**Comment by carlosmiranda** [comment]
@yegor256 ping

**Comment by davvd** [comment]
@carlosmiranda attached this issue to milestone "1.0" (let me know if this is wrong)

**Comment by davvd** [comment]
@carlosmiranda thanks for the report, I topped your acc for 15 mins, payment ID `73824706`

**Comment by davvd** [comment]
@rfqu this task is for you, keep [these principles](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html) in mind, and don't hesitate to ask any technical questions; **30 mins** is the budget of the task. This is exactly how much will be paid when the problem is [solved](http://www.xdsd.org/2014/04/15/definition-of-done.html) (no matter how much time you will actually spend). See [this](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html) for more information

**Comment by rfqu** [comment]
I am almost done, but one of new tests fails because of the issue #524.

**Comment by yegor256** [comment]
@rfqu keep in mind that you should address your messages to someone, by starting them with the name of the person you're talking to. otherwise, it's just noise, nobody will pay attention to what you're saying. check this out: http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html#4.-avoid-noise-—-address-your-comments

**Comment by davvd** [comment]
@rfqu the ticket is with you for 15 days already. If it is not finished in the next 48 hours, it will be re-assigned to someone else, see [No Obligations](http://www.xdsd.org/2014/04/13/no-obligations-principle.html) principle, [this article](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html) should help if you're stuck. added -30 to your rating, now it is equal to [-30](http://www.netbout.com/b/36195?open=rating)

**Comment by rfqu** [comment]
@davvd @yegor256 @carlosmiranda  fixed - see pull request #545

**Comment by carlosmiranda** [comment]
@rfqu let's wait for merge.

**Comment by davvd** [comment]
> @davvd @yegor256 @carlosmiranda  fixed - see pull request #545

@rfqu thanks, I'll take a look

**Comment by rfqu** [comment]
@yegor256 I see you "improved" code validator so that it blocks writing any complex programs - see issue #550

**Comment by davvd** [comment]
@rfqu you've been working with this task for too long. I'm sorry, but I'll assign someone else. Please stop working with it. See our [no obligations](http://www.xdsd.org/2014/04/13/no-obligations-principle.html) principle... added -60 to your rating, now it is equal to [-75](http://www.netbout.com/b/36195?open=rating)

**Comment by rfqu** [comment]
@davvd @yegor256  actually I finished this task. But your code validator rejects the solution for an idiotic reason. 
I propose to drop ConfusingTernary check and accept my solution.

**Comment by davvd** [comment]
@danff please proceed, it's yours

**Comment by danff** [comment]
@davvd need more time

**Comment by davvd** [comment]
> @davvd need more time

@danff OK, take your time

**Comment by yegor256** [comment]
@0crat in

**Comment by 0crat** [comment]
> @0crat in ([here](https://github.com/yegor256/takes/issues/485#issuecomment-322125385))

@yegor256 Job `gh:yegor256/takes#485` is in scope.

**Comment by 0crat** [comment]
Job `gh:yegor256/takes#485` assigned to @caarlos0, please go ahead ([policy](http://datum.zerocracy.com/pages/policy.html)).

**Comment by 0crat** [comment]
@caarlos0 this job was assigned to you 8 days ago.
It will be taken away from you after 10 days from start (this is our policy).

**Comment by 0crat** [comment]
Oops! Job `gh:yegor256/takes#485` is not assigned to anyone.

**Comment by 0crat** [comment]
Oops! Job `gh:yegor256/takes#485` is not assigned to anyone.

**Comment by 0crat** [comment]
Oops! Job `gh:yegor256/takes#485` is not assigned to anyone.

**Comment by 0crat** [comment]
The job [#485](https://github.com/yegor256/takes/issues/485) assigned to @t-izbassar[/z](https://www.0crat.com/u/t-izbassar). The budget is 30 minutes, see [§4](http://datum.zerocracy.com/pages/policy.html#4). Please, read [§8](http://datum.zerocracy.com/pages/policy.html#8) and [§9](http://datum.zerocracy.com/pages/policy.html#9). If the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html).

**Comment by t-izbassar** [comment]
@0crat waiting for #778

**Comment by 0crat** [comment]
> @0crat waiting for #778  ([here](https://github.com/yegor256/takes/issues/485#issuecomment-361594922))

@t-izbassar The impediment for [#485](https://github.com/yegor256/takes/issues/485) was registered successfully by @t-izbassar[/z](https://www.0crat.com/u/t-izbassar)

**Comment by t-izbassar** [comment]
@carlosmiranda can you close this one? #785 was merged and puzzles created.

**Comment by carlosmiranda** [comment]
@t-izbassar thanks!

**Comment by 0crat** [comment]
Order was successfully finished: +30 points just awarded to @t-izbassar[/z](https://www.0crat.com/u/t-izbassar), total is [+225](https://www.0crat.com/u/t-izbassar)

**Comment by 0crat** [comment]
The job [#485](https://github.com/yegor256/takes/issues/485) is now out of scope

**Comment by 0pdd** [comment]
@carlosmiranda 3 puzzles [#819](https://github.com/yegor256/takes/issues/819), [#820](https://github.com/yegor256/takes/issues/820), [#832](https://github.com/yegor256/takes/issues/832) are still not solved; solved: [#794](https://github.com/yegor256/takes/issues/794), [#795](https://github.com/yegor256/takes/issues/795).

**Comment by 0pdd** [comment]
@carlosmiranda 3 puzzles [#819](https://github.com/yegor256/takes/issues/819), [#832](https://github.com/yegor256/takes/issues/832), [#859](https://github.com/yegor256/takes/issues/859) are still not solved; solved: [#794](https://github.com/yegor256/takes/issues/794), [#795](https://github.com/yegor256/takes/issues/795), [#820](https://github.com/yegor256/takes/issues/820).

**Comment by 0pdd** [comment]
@carlosmiranda 2 puzzles [#819](https://github.com/yegor256/takes/issues/819), [#832](https://github.com/yegor256/takes/issues/832) are still not solved; solved: [#794](https://github.com/yegor256/takes/issues/794), [#795](https://github.com/yegor256/takes/issues/795), [#820](https://github.com/yegor256/takes/issues/820), [#859](https://github.com/yegor256/takes/issues/859).

**Comment by 0pdd** [comment]
@carlosmiranda the puzzle [#819](https://github.com/yegor256/takes/issues/819) is still not solved; solved: [#794](https://github.com/yegor256/takes/issues/794), [#795](https://github.com/yegor256/takes/issues/795), [#820](https://github.com/yegor256/takes/issues/820), [#832](https://github.com/yegor256/takes/issues/832), [#859](https://github.com/yegor256/takes/issues/859).

**Comment by 0pdd** [comment]
@carlosmiranda all 6 puzzles are solved here: [#794](https://github.com/yegor256/takes/issues/794), [#795](https://github.com/yegor256/takes/issues/795), [#819](https://github.com/yegor256/takes/issues/819), [#820](https://github.com/yegor256/takes/issues/820), [#832](https://github.com/yegor256/takes/issues/832), [#859](https://github.com/yegor256/takes/issues/859).
