### ISSUE TITLE
TkMeasured is not tested

### ISSUE THREAD

**Issue by yegor256** [yegor256/takes#49]
There is no unit test for `TkMeasured` class, let's create one.

**Comment by davvd** [comment]
@yegor256 sure, thanks, I added bug tag to it

**Comment by davvd** [comment]
@yegor256 thanks for tis bug, I topped your account for 15 mins, transaction `000-d480d40f`

**Comment by davvd** [comment]
@d-molotchko this ticket is yours now, please proceed, and keep in mind [this](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html). Any technical questions you should ask right here; The budget of this task is **30 mins**. This is exactly how much time will be compensated, when the task is completed. Read about our [Definition of Done](http://www.xdsd.org/2014/04/15/definition-of-done.html)

**Comment by d-molotchko** [comment]
Where I can see coding style documentation?

**Comment by yegor256** [comment]
@d-molotchko it's all here: www.qulice.com

**Comment by d-molotchko** [comment]
@yegor256 thanks for link, I was expecting to see a human description of indentation, position of blocks, sorting the imports. But it looks like everything is pretty transparently after writing the first unit test.

**Comment by d-molotchko** [comment]
@davvd I create PR #64 for this issue

**Comment by d-molotchko** [comment]
@yegor256 PR #64 was merged successfull. Could you close this issue?

**Comment by yegor256** [comment]
@d-molotchko thanks!

**Comment by davvd** [comment]
@d-molotchko **30 mins** sent to your balance (ID `54086641`), many thanks!... +30 added to your rating, current score is: [+60](http://www.netbout.com/b/35168?open=rating)
