### ISSUE TITLE
Refactoring of RqHeaders

### ISSUE THREAD

**Issue by exper0** [yegor256/takes#490]
Currently RqHeaders has following methods to work with HTTP headers:

    /**
     * Get single header.
     *
     * @param key Header name
     * @return List of values (can be empty)
     * @throws IOException If fails
     */
    Iterable<String> header(CharSequence key) throws IOException;

    /**
     * Get all header names.
     *
     * @return All names
     * @throws IOException If fails
     */
    Iterable<String> names() throws IOException;

However, working with Iterables not really convenient. Example: in order to check if some header exists I have to write something like this:

    new RqHeaders.Base(req)
                        .header(header)
                        .iterator()
                        .hasNext();

Not very clear and obvious. 
At the same time internally RqHeaders implementations contain a kind of multimap - header name to list of values. I think it would be useful to have a couple of additional methods:

    Set<String> namesSet();
    List<String> getHeader(String header);

**Comment by exper0** [comment]
Probably, it would be more suitable to have another wrapper class around Request

**Comment by exper0** [comment]
@yegor256 what do you think? Since relevant class does exist it's not so important. But may be small refactoring of existing RqHeaders.Base/Smart is good idea

**Comment by davvd** [comment]
@yegor256 please do something about this issue

**Comment by yegor256** [comment]
@exper0 can you please update ticket description, to explain how exactly you're suggesting to refactor `RqHeaders`... I'm not sure I follow now..

**Comment by exper0** [comment]
@yegor256 done, I updated ticket description

**Comment by yegor256** [comment]
@exper0 OK, I agree, let's use `Set` and `List` in `header()` and `names()` respectively. Other ideas, about multi-map, please submit in separate tickets. We are trying to use one ticket per problem.

**Comment by exper0** [comment]
@yegor256 moved multimap proposal to #497

**Comment by davvd** [comment]
@exper0 I added milestone `1.0` to this issue, let me know if there has to be something else

**Comment by davvd** [comment]
@exper0 many thanks, **15 mins** added to your acc for reporting this bug, pmt ID `AP-84536016UD845204D`

**Comment by davvd** [comment]
@rultor @exper0 please look at this issue, rultor closed it automatically

**Comment by exper0** [comment]
@davvd @aliceice looks good, thanks

**Comment by davvd** [comment]
@exper0 once `490-c74fee69`/#508 puzzle is resolved (later, in another ticket), this ticket will be fully complete

**Comment by davvd** [comment]
@exper0 last puzzled solved `490-c74fee69`/#508
