### ISSUE TITLE
ReadableByteChannel in org.takes.rq.RqMultipart.Base never closes

### ISSUE THREAD

**Issue by simonjenga** [yegor256/takes#491]
When the ```private final transient ReadableByteChannel body;``` is initialized in the constructor 
as ```this.body = Channels.newChannel(stream);```, it is never closed anywhere in the class.

Try to close it in the method ```org.takes.rq.RqMultipart.Base.copy(WritableByteChannel, byte[])``` as:
```java
//The number of bytes read, possibly zero, or -1 if the channel has reached end-of-stream
if (this.body.read(this.buffer) == -1) {
    this.body.close();
    break;
}
```

**Comment by davvd** [comment]
@yegor256 take a look at this issue please and dispatch it somehow, see [par.21](http://at.teamed.io/policy.html#21)

**Comment by davvd** [comment]
@simonjenga attached this issue to milestone "1.0" (let me know if this is wrong)

**Comment by davvd** [comment]
@simonjenga thank you for the ticket reported, I topped your account for 15 mins, transaction `73833946`

**Comment by davvd** [comment]
@xupyprmv the task is yours, please go ahead

**Comment by xupyprmv** [comment]
@simonjenga I think that closing stream inside `org.takes.rq.RqMultipart.Base.copy` is not obvious. `body` is used as a container to provide chunk of original request body to `buildRequests` method. So, may be close `body` after it is processed by `buildRequests` method? Also, I think, we must close stream if any error occurs. What do you think about next variant?

```java
        public Base(final Request req) throws IOException {
            super(req);
            final InputStream stream = new RqLengthAware(req).body();
            try {
                this.body = Channels.newChannel(stream);
                this.buffer = ByteBuffer.allocate(
                    // @checkstyle MagicNumberCheck (1 line)
                    Math.min(8192, stream.available())
                );
                this.map = this.buildRequests(req);
            } finally {
                this.body.close();
            }
        }
```

**Comment by simonjenga** [comment]
@xupyprmv The suggested fixes or ideas in tickets may not always be correct or accurate. Feel free to express your own fixes or ideas.

Yes, we should close it in the finally block:
```
finally {
    stream.close();
    this.body.close();
}
```

Also, please remove these unnecessary warnings in the two final constant fields in that class:
``` @SuppressWarnings("PMD.UnusedPrivateField") ```

**Comment by xupyprmv** [comment]
@davvd I need more time for this ticket. I'm waiting for CR in #514. I think it will be merged soon, because I already resolve all remarks according to CR.

**Comment by davvd** [comment]
> @davvd I need more time for this ticket. I'm waiting for CR in #514. I think it will be merged soon, because I already resolve all remarks according to CR.

@xupyprmv issue #514 is a pull request, we can't wait for it

**Comment by xupyprmv** [comment]
@simonjenga PR #514 was merged. Please close this ticket.

**Comment by simonjenga** [comment]
@xupyprmv If ```new RqLengthAware(req).body();``` throws an exception, ```stream``` will never be closed.
I also think we must close ```stream``` if any error occurs. What do you think?

**Comment by xupyprmv** [comment]
@simonjenga 

> If new RqLengthAware(req).body(); throws an exception, stream will never be closed.

But it will not been created.

> I also think we must close stream if any error occurs. What do you think?

Thats why there is line 145 : https://github.com/yegor256/takes/pull/514/files

**Comment by simonjenga** [comment]
@xupyprmv Line 145 will never be executed since we will never get inside the ```try-catch-finally``` block once ```new RqLengthAware(req).body();``` throws an exception.

Also, in my opinion, i really don't think we need two(2)  ```try-finally``` blocks just to perform a close. They make the code to be unreadable.

http://javarevisited.blogspot.com/2014/10/right-way-to-close-inputstream-file-resource-in-java.html

http://www.java2s.com/Code/Java/Language-Basics/Closestreaminfinally.htm

https://www.google.com/search?q=java&ie=utf-8&oe=utf-8#q=java+close+stream+in+finally

I am not requesting you do do another PR! I will close this shortly...

**Comment by xupyprmv** [comment]
@simonjenga Sure, but if  `new RqLengthAware(req).body();` throw an exception, then `stream` variable will be not initialized. That's why we don't need to close `stream` (You can try it yourself, you will get `NullPointerException`).

Using two try catch blocks instead of one was a result of CR.

**Comment by simonjenga** [comment]
@xupyprmv :thumbsup: :ok:

**Comment by davvd** [comment]
@elenavolokhova please, review this ticket for compliance with our [QA rules](http://at.teamed.io/qa.html)

**Comment by elenavolokhova** [comment]
@davvd Quality is good here.

**Comment by davvd** [comment]
> @davvd Quality is good here.

@elenavolokhova thanks a lot

**Comment by davvd** [comment]
@xupyprmv I added 10 mins to @elenavolokhova (for QA review) in transaction 75840819. **30 mins** added to your account (payment number `AP-38597566F9917563R`), many thanks for your contribution! 360 hours and 27 mins spent here.. +30 added to your rating, current score is: [+60](http://www.netbout.com/b/35999?open=rating)
