### ISSUE TITLE
default header

### ISSUE THREAD

**Issue by dmzaytsev** [yegor256/takes#492]
right now Takes doesn't allow to set the default header on the request
It would be nice to include [RqWithDefaultHeader](https://github.com/yegor256/netbout/blob/master/netbout-web/src/main/java/com/netbout/rest/RqWithDefaultHeader.java) into Takes

RqWithDefaultHeader allows add add a header if the header not exists in the request

**Comment by exper0** [comment]
@dmzaytsev ready to incorporate request to Takes. I was also thinking about adding it to Takes.

**Comment by dmzaytsev** [comment]
@exper0 ask @yegor256 assign you to this ticket when he confirm the bug

**Comment by davvd** [comment]
@yegor256 please do something about this issue

**Comment by exper0** [comment]
@yegor256 I'll be happy to implement it

**Comment by davvd** [comment]
@dmzaytsev I set the milestone to 1.0 since there is nothing set yet

**Comment by davvd** [comment]
@dmzaytsev thanks for tis bug, I topped your account for 15 mins, transaction `73869993`

**Comment by davvd** [comment]
@exper0 the task is yours plz proceed

**Comment by exper0** [comment]
@davvd it's done in PR #507, please assign reviewer

**Comment by davvd** [comment]
> @davvd it's done in PR #507, please assign reviewer

@exper0 OK, sure

**Comment by exper0** [comment]
@davvd it seems @yegor256 is too busy for the further review so the time on this task can be overdue.

**Comment by davvd** [comment]
> @davvd it seems @yegor256 is too busy for the further review so this task can be overdue. Can you give us more time?

@exper0 yes, take your time, thanks for letting me know

**Comment by exper0** [comment]
@dmzaytsev issue is resolved and the code is merged (see PR #507). Please close request

**Comment by dmzaytsev** [comment]
@exper0 thanks

**Comment by davvd** [comment]
@ypshenychka please, help us to evaluate quality here, as per [par.24](http://at.teamed.io/policy.html#24)

**Comment by ypshenychka** [comment]
@davvd Quality is good.

**Comment by davvd** [comment]
> @davvd Quality is good.

@ypshenychka thank you :)

**Comment by davvd** [comment]
@exper0 added 10 mins to @ypshenychka, for QA review, payment code is `75895324`... Many thanks! **30 mins** were added to your account in Transaction ID `AP-0HV044497G8900806` (task took 382 hours and 21 mins)... +30 added to your rating, current score is: [+603](http://www.netbout.com/b/36185?open=rating)
