### ISSUE TITLE
RsWithType.HTML, RsWithType.JSON, RsWithType.XML, RsWithType.Text

### ISSUE THREAD

**Issue by yegor256** [yegor256/takes#496]
Let's create these new classes: `RsWithType.HTML`, `RsWithType.JSON`, `RsWithType.XML`, `RsWithType.Text`. They should add these types to the response:

```
Response res = new RsWithType.HTML(
  new RsWithBody("<html/>")
);
```

**Comment by davvd** [comment]
@yegor256 tag "bug" added

**Comment by davvd** [comment]
@yegor256 attached this issue to milestone "1.0" (let me know if this is wrong)

**Comment by davvd** [comment]
@yegor256 thanks a lot for reporting, **15 mins** added to your acc, pmt ID `000-41a21de5`

**Comment by davvd** [comment]
@rajithd this task is yours, please help (see our key [principles of work](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html)). If you have any technical questions, don't hesitate to ask right here; Task's budget is **30 mins** (see [this](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html) for explanation)

**Comment by rajithd** [comment]
@davvd I'm not sure what do I need to do in here ? Because this task is already done (Adding `RsWithType.HTML`,`RsWithType.JSON`, `RsWithType.XML`, `RsWithType.Text`) ?

**Comment by davvd** [comment]
> @davvd I'm not sure what do I need to do in here ? Because this task is already done (Adding `RsWithType.HTML`,`RsWithType.JSON`, `RsWithType.XML`, `RsWithType.Text`) ?

@rajithd you should always address your technical comments to the author of the ticket, see http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html

**Comment by rajithd** [comment]
@yegor256 These types were already added in the below PR. 
https://github.com/yegor256/takes/pull/501
Do I need to do any additional thing here ? Please clarify.

**Comment by yegor256** [comment]
@rajithd indeed, it's solved already, I'm closing
