### ISSUE TITLE
RqHeaders.Base refactoring

### ISSUE THREAD

**Issue by exper0** [yegor256/takes#497]
Currently RqHeaders.Base has following method: 

    Map<String, List<String>> map()

What's wrong there:
`ConcurrentHashMap<String, List<String>>`. It's quite bad for maintainablility - not clear why concurrent thread safe collection is used locally (It seems it's just for putIfAbsent method). Also `<String, List<String>>` has multimap semantics. Having this collection as regular Map implementation instead of multimap requires more code and worse for understanding (and thus maintainability). For instance, line
`map.putIfAbsent(key, new LinkedList<String>());` will be not needed resulting in clearer code and less memory/GC overhead(right now LinkedList is being created every time)
Using multimap implementation, e.g. ListMultimap<String,String> from guava or similar collection from Apache commons collections would result in better maintainability

**Comment by yegor256** [comment]
@exper0 what exactly is wrong now? why current implementation is not good enough? see this: http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html#5.-report-when-it-is-broken

**Comment by exper0** [comment]
@yegor256 thank you comment. Rephrased initial ticket, added details. 
In further tickets will try to be clearer

**Comment by yegor256** [comment]
@exper0 we can't use Guava in this problem. are you aware of this? JDK doesn't have a multi map.

**Comment by exper0** [comment]
@yegor256 I see Apache Commons Collections available in classpath (it has `MultiMap` interface and implemenations). There is no explicit dependency in pom.xml - probably it's available as 3rd party dependency. Do you think we don't need to use it as well?

**Comment by yegor256** [comment]
@exper0 it's in "optional" dependency. we should not use any third-party libraries in "compile" scope.

**Comment by exper0** [comment]
@yegor256 if you think using any dependencies is not acceptable here let's close the task
