### ISSUE TITLE
RqMultipart parts should have Content-Length

### ISSUE THREAD

**Issue by HDouss** [yegor256/takes#498]
RqMultipart implementation decodes HTTP multipart FORM data and breaks (represents) the different parts into separate requests. These requests have bodies but don't precise a content length in the header. Every part should have its proper `Content-Length` header, in order to be treated as a valid request.

**Comment by davvd** [comment]
@yegor256 please do something about it, see [par.21](http://at.teamed.io/policy.html#21)

**Comment by davvd** [comment]
@hdouss since the ticket has no milestone I set it to 1.0

**Comment by davvd** [comment]
@hdouss many thanks, **15 mins** added to your acc for reporting this bug, pmt ID `74137078`

**Comment by exper0** [comment]
@yegor256 @davvd ready to implement.

**Comment by yegor256** [comment]
@davvd assign @exper0 to this task pls

**Comment by davvd** [comment]
> @davvd assign @exper0 to this task pls

@yegor256 OK @exper0 please start, the task is yours

**Comment by exper0** [comment]
@HDouss it's in PR #515. Please close the ticket.

**Comment by HDouss** [comment]
@exper0 Thanks.

**Comment by davvd** [comment]
@elenavolokhova please, review this ticket for compliance with our [QA rules](http://at.teamed.io/qa.html)

**Comment by elenavolokhova** [comment]
@davvd Quality is good here.

**Comment by davvd** [comment]
> @davvd Quality is good here.

@elenavolokhova thanks a lot

**Comment by davvd** [comment]
@exper0 added 10 mins to @elenavolokhova, for QA review, payment code is `75194737`. **30 mins** added to your account (payment number `AP-6PU46825X3051613C`), many thanks for your contribution! 94 hours and 12 mins spent here.. +30 to your rating, your total score is [+421](http://www.netbout.com/b/36185?open=rating)
