### ISSUE TITLE
the puzzle verification not configured in CI

### ISSUE THREAD

**Issue by dmzaytsev** [yegor256/takes#502]
Right now CI server doesn't verify puzzles and estimates. 
So we see a puzzle's error only if Rultor can't merge PR.
It would be nice to add the verification
see https://github.com/yegor256/netbout/blob/master/.travis.yml

**Comment by davvd** [comment]
@yegor256 please pay attention to this issue ([par.21](http://at.teamed.io/policy.html#21))

**Comment by yegor256** [comment]
@dmzaytsev fixed in 3e6e836 thanks!
