### ISSUE TITLE
RqHeaders.java:93-98: We need to implement a...

### ISSUE THREAD

**Issue by davvd** [yegor256/takes#508]
Puzzle `490-c74fee69` in `src/main/java/org/takes/rq/RqHeaders.java:93-98` has to be resolved: We need to implement a VerboseList and its tests like VerboseIterable. It should provide means to throw an exception with a given error message when it otherwise throws an IndexOutOfBoundsException. With this we must wrap the returned list otherwise the diagnostic messages are lost: https://github.com/yegor256/takes/pull/503/files#diff-a01b0291ad72ac6fd8e264f47f844b3bL101... The puzzle was created by Eléna Ihde-Simon on 8-Jan-2016.

If you have any technical questions, don't ask me, submit new tickets instead. The task will be "done" when the problem is fixed and the text of the puzzle is removed from the source code.

**Comment by davvd** [comment]
@yegor256 attached this issue to milestone "1.0" (let me know if this is wrong)

**Comment by davvd** [comment]
@happy-neko it's yours, please go ahead

**Comment by Happy-Neko** [comment]
@davvd Please proceed with code review (PR #513).

**Comment by davvd** [comment]
> @davvd Please proceed with code review (PR #513).

@happy-neko will check it soon, thanks

**Comment by Happy-Neko** [comment]
@davvd PR is merged, this ticket can be closed now.

**Comment by davvd** [comment]
> @davvd PR is merged, this ticket can be closed now.

@happy-neko OK

**Comment by davvd** [comment]
@yegor256 Finished, thanks, closing..

**Comment by davvd** [comment]
@elenavolokhova please, let us know what do you think about this ticket, according to our [QA rules](http://at.teamed.io/qa.html)

**Comment by elenavolokhova** [comment]
@davvd Quality is good here.

**Comment by davvd** [comment]
> @davvd Quality is good here.

@elenavolokhova thanks a lot :)

**Comment by davvd** [comment]
@happy-neko I added 10 mins to @elenavolokhova (for QA review) in transaction 75843679

thanks, I just added **30 mins** to your account, payment `AP-2H0977538X650981F`, 311 hours and 30 mins spent

+30 added to your rating, current score is: [+128](http://www.netbout.com/b/36136?open=rating)
