### ISSUE TITLE
TkWithHeaders is not tested

### ISSUE THREAD

**Issue by yegor256** [yegor256/takes#51]
There is no unit test for `TkWithHeaders` class, let's create one.

**Comment by davvd** [comment]
@yegor256 sure, thanks, I added bug tag to it

**Comment by davvd** [comment]
@yegor256 thank you for reporting this, I added 15 mins to your acc, transaction `000-294b24eb`

**Comment by davvd** [comment]
@dmzaytsev it's yours now, please proceed keeping in mind [our principles](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html). Feel free to ask any technical questions right here in the ticket

Total fixed cost of this task is **30 mins** (see [this](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html) for more info)

**Comment by dmzaytsev** [comment]
My pull request pending about 10 hours with message "Waiting for AppVeyor build to complete". Is it  OK?

**Comment by yegor256** [comment]
@dmzaytsev yeah, it's fine, it's a bug in AppVeyor, don't pay attention to it

**Comment by dmzaytsev** [comment]
@yegor256 pull request has been merged. Could you close the task please ? Or let me know why the delivery not accepted ?

**Comment by yegor256** [comment]
@dmzaytsev yes, many thanks!

**Comment by davvd** [comment]
@dmzaytsev thanks, I just added **30 mins** to your account, payment `53832751`

+30 to your rating, your total score is [+30](http://www.netbout.com/b/35166?open=rating)
