### ISSUE TITLE
Let's turn on findbugs

### ISSUE THREAD

**Issue by exper0** [yegor256/takes#517]
Currently it's excluded in [qulice configuration](https://github.com/yegor256/takes/blob/master/pom.xml#L310). Why is it?

<hr id='w'>

**Comment by yegor256** [comment]
@exper0 let's try to turn turn them on...

**Comment by davvd** [comment]
@exper0 we will find someone to do this task, soon

**Comment by davvd** [comment]
@exper0 there is no milestone yet, so I set it to `1.0`

**Comment by davvd** [comment]
@ddaanniieell01 could you please pick this up? This [article](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html) explains how we work. Any technical questions you may ask right here; The cost of this task is **30 mins** (this is exactly how much will be paid, not less not more), when the task is [done](http://www.xdsd.org/2014/04/15/definition-of-done.html)

**Comment by davvd** [comment]
@exper0 thanks a lot for reporting, **15 mins** added to your acc, pmt ID `AP-3LR38608T1136251D`

**Comment by davvd** [comment]
@alexey-krylov this task is yours, please help (see our key [principles of work](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html)). If you have any technical questions, don't hesitate to ask right here; The budget of this task is **30 mins**. This is exactly how much time will be compensated, when the task is completed. Read about our [Definition of Done](http://www.xdsd.org/2014/04/15/definition-of-done.html)

**Comment by alexey-krylov** [comment]
@davvd ok, i take this task.

**Comment by davvd** [comment]
> @davvd ok, i take this task.

@alexey-krylov thanks

**Comment by alexey-krylov** [comment]
@yegor256 FindBugs found ~50 errors in Takes. Most of them related to String-from-bytes construction without charset:
```
new String(byte[])
```

I propose three options:
1. Use StandardCharsets.UTF_8 everywhere. This option requires to change minimum supportable JDK to 1.7.
2. Use constant "UTF-8" everywhere (make it public static). 
3. Suppress this FindBugs check 

Please suggest with selection. I don't know Takes popularity level in environments based on Java6. 
As you know Oracle public support for Java6 and 7 has been stopped in 2013 and 2015 respectively (http://www.oracle.com/technetwork/java/eol-135779.html). Maybe it will be good idea to migrate Takes to Java8?

**Comment by alexey-krylov** [comment]
@yegor256, @exper0  one more question - what result expected with resolution of this issue: "enabled FindBugs" or "enabled FindBugs + code matched its checks"?

**Comment by exper0** [comment]
@alexey-krylov Ideally you should enable findbugs and fix issues it causes. If there are too many issue you need to fix at least some of them and exclude the remaining issues from check (using specific exclude filters). Also you need to create puzzle to for the other developer to fix the remaining issues (see http://www.yegor256.com/2009/03/04/pdd.html)

**Comment by alexey-krylov** [comment]
@exper0 most of issues related to 'new String(byte[])' construct. What do you think about best solution here?

**Comment by yegor256** [comment]
@alexey-krylov let's upgrade to Java 7

**Comment by davvd** [comment]
@sebing please go ahead, it's your task now, keep [this](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html) in mind, and don't hesitate to ask any technical questions you may have... The budget of this issue is **30 mins**, which is exactly how much will be paid when the task is *done* (see [this](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html) for explanation)

**Comment by sebing** [comment]
@davvd  I made a pull request.
But the build is failing as it cannot download the maven plugin for checking the java version.

**Comment by davvd** [comment]
> @davvd  I made a pull request(https://github.com/yegor256/takes/pull/552).
> But the build is failing as it cannot download the maven plugin for checking the java version.

@sebing how can I help?

**Comment by yegor256** [comment]
@sebing read this please: http://www.yegor256.com/2015/02/16/it-is-not-a-school.html

**Comment by davvd** [comment]
@exper0 there is a puzzle in this code `517-9858229b`/#574, we'll resolve it later

**Comment by sebing** [comment]
@davvd Can we close this issue as the merge request (https://github.com/yegor256/takes/issues/552) accepted?

**Comment by davvd** [comment]
> @davvd Can we close this issue as the merge request (https://github.com/yegor256/takes/issues/552) accepted? 

@sebing you should ask ticket author to close it, see http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html

**Comment by sebing** [comment]
@exper0 Can we close this issue as the merge request (https://github.com/yegor256/takes/issues/552) was accepted?

**Comment by exper0** [comment]
@sebing sure, thanks

**Comment by sebing** [comment]
@exper0 thanks.

**Comment by sebing** [comment]
@davvd This task is finished and closed.

**Comment by davvd** [comment]
> @davvd This task is finished and closed.

@sebing OK thanks

**Comment by davvd** [comment]
@elenavolokhova please, review this ticket for compliance with our [QA rules](http://at.teamed.io/qa.html)

**Comment by elenavolokhova** [comment]
@davvd Quality is good here.

**Comment by davvd** [comment]
> @davvd Quality is good here.

@elenavolokhova thanks for the review

**Comment by davvd** [comment]
@sebing just added 10 mins to @elenavolokhova (for QA), payment ID is `77172947`... done, I added **30 mins** in payment `56bca102adaf562e9b00032e`, 305 hours and 13 mins spent to complete this... added +30 to your rating, now it is equal to [+45](http://www.netbout.com/b/36309?open=rating)

**Comment by davvd** [comment]
@exper0 the last puzzle `684-70270140`/#692 solved
