### ISSUE TITLE
BkBasicTest.java:57-60: At the moment we don't...

### ISSUE THREAD

**Issue by davvd** [yegor256/takes#519]
Puzzle `306-b987400a` in `src/test/java/org/takes/http/BkBasicTest.java:57-60` has to be resolved: At the moment we don't support HTTP persistent connections. Would be great to implement this feature. BkBasic.accept should handle more than one HTTP request in one connection.... The puzzle was created by Maksimenko Vladimir on 11-Jan-2016.

If you have any technical questions, don't ask me, submit new tickets instead. The task will be "done" when the problem is fixed and the text of the puzzle is removed from the source code.

<hr id='w'>

**Comment by davvd** [comment]
@ddaanniieell01 the task is for you now, follow [these guidelines](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html). Don't hesitate to ask any technical questions right here... This task's budget is **30 mins**. This is exactly how much will be paid when the problem explained above is solved. See [this](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html) for more information

**Comment by davvd** [comment]
@yegor256 there is no milestone yet, so I set it to `1.0`

**Comment by davvd** [comment]
@exper0 it's yours,please go ahead

**Comment by exper0** [comment]
@davvd need more time here

**Comment by davvd** [comment]
> @davvd need more time here

@exper0 OK, take your time

**Comment by exper0** [comment]
@davvd please assign someone else.

**Comment by davvd** [comment]
> @davvd please assign someone else.

@exper0 I deducted 30 points from your rating

**Comment by davvd** [comment]
> @davvd please assign someone else.

@exper0 I will try to find someone else

**Comment by davvd** [comment]
@sebing the task is yours, please go ahead

**Comment by sebing** [comment]
@yegor256  I need some design help.
The problem is `org.takes.rq.RqLive#parse` hiding the `Inputstream` and creating a `ByteArrayOutputStream` So the the read in `org.takes.rs.RsPrint#printBody(java.io.OutputStream)` is happening in the new object not in the socket's Inputstream. 

Hope you understand me ;)

1) I need some guidance on why we are hiding the Inputstream.
2) Should I expose the `org.takes.rq.RqLive#data` so In `org.takes.http.BkBasic#accept` I can know the read availability by checking something like this `if (data.has())`  

Did I understand the spaghetti code? May be my understanding of the code is not enough!

**Comment by sebing** [comment]
@davvd I have made a PR(https://github.com/yegor256/takes/pull/649) can you find someone to review it?

**Comment by yegor256** [comment]
@sebing keep this in mind: http://www.yegor256.com/2015/02/16/it-is-not-a-school.html we can't teach you and help you understand our spaghetti code. we don't want to do that. we don't want you to become smarter, we want our code to become better. read the article!

**Comment by sebing** [comment]
@davvd I need more time as the task is growing. 
- With my implementation one of the other tests are breaking. I am trying to create another testcase for that bug and create a puzzle.

**Comment by sebing** [comment]
@davvd I managed to understand the stuff. So hope I will finish the task in time. I updated the PR.

**Comment by sebing** [comment]
@davvd as the PR(https://github.com/yegor256/takes/pull/649) is merged, can you close this issue?

**Comment by davvd** [comment]
@yegor256 the code made here contains a puzzle `519-af7d4687`/#655, which will be resolved soon

**Comment by davvd** [comment]
@yegor256 Thanks all, I am closing

**Comment by davvd** [comment]
@ypshenychka review this ticket please, for compliance with our [quality rules](http://at.teamed.io/qa.html)

**Comment by vbodak** [comment]
@davvd Quality is good.

**Comment by ypshenychka** [comment]
@davvd Quality is good.

**Comment by davvd** [comment]
> @davvd Quality is good.

@ypshenychka thanks for the review

**Comment by davvd** [comment]
@sebing I added 10 mins to @ypshenychka (for QA review) in transaction 81282917

**30 mins** added to your account (payment number `56f287f15eb9b73e300002c4`), many thanks for your contribution! 245 hours and 2 mins spent here.

added +30 to your rating, now it is equal to [+165](http://www.netbout.com/b/36309?open=rating)

**Comment by davvd** [comment]
@yegor256 the last puzzle `519-af7d4687`/#655 solved
