### ISSUE TITLE
TkRedirect is not tested

### ISSUE THREAD

**Issue by yegor256** [yegor256/takes#52]
There is no unit test for `TkRedirect` class, let's create one.

**Comment by davvd** [comment]
@yegor256 thanks, I added the "bug" tag

**Comment by davvd** [comment]
@yegor256 thanks for the report, I topped your acc for 15 mins, payment ID `000-71dd2671`

**Comment by davvd** [comment]
@d-molotchko This task is yours, please go ahead keeping in mind [this](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html). If any questions, don't hesitate to ask right here. The budget here is **30 mins**, which is exactly how much time will be paid for, when the task is [completed](http://www.xdsd.org/2014/04/15/definition-of-done.html)

**Comment by d-molotchko** [comment]
@davvd I added PR #65 for this issue

**Comment by d-molotchko** [comment]
@davvd PR #65 is closed, can you close this issue?

**Comment by yegor256** [comment]
@d-molotchko it's my issue, I'm the closer :)

**Comment by yegor256** [comment]
thanks!

**Comment by davvd** [comment]
@d-molotchko **30 mins** added to your account (payment number `54083321`), many thanks for your contribution!. +30 added to your rating, at the moment it is: [+30](http://www.netbout.com/b/35168?open=rating)
