### ISSUE TITLE
HmRqHeader: Very confusing error message

### ISSUE THREAD

**Issue by exper0** [yegor256/takes#520]
[HmRqHeader](https://github.com/yegor256/takes/blob/master/src/main/java/org/takes/facets/hamcrest/HmRqHeader.java) produces very confusing error message in case of mismtach:

```
java.lang.AssertionError: 
Expected: entry containing ["Content-Length"->"102"]
     but: was <org.takes.rq.RqWithHeader@5679c7b2>
```

Let's make it readable, e.g. something like:
```
java.lang.AssertionError: 
Expected: entry containing ["Content-Length"->"102"]
     but: was entry containing ["Content-Length"->"1"]
```

Ideally HmRqHeader implementation it should be very similar to [HmRsHeader](https://github.com/yegor256/takes/blob/master/src/main/java/org/takes/facets/hamcrest/HmRsHeader.java)

**Comment by davvd** [comment]
@yegor256 dispatch this issue please, see [par.21](http://at.teamed.io/policy.html#21)

**Comment by davvd** [comment]
@exper0 since the ticket has no milestone I set it to 1.0

**Comment by davvd** [comment]
@exper0 thanks for the ticket, your account was topped for 15 mins, payment AP-4EN851327Y2243444

**Comment by davvd** [comment]
@happy-neko the task is yours please proceed

**Comment by Happy-Neko** [comment]
@exper0 PR is merged. Please review and close the ticket if everything is ok.

**Comment by exper0** [comment]
@Happy-Neko Looks good, thanks

**Comment by davvd** [comment]
@ypshenychka please, check this issue for QA compliance, as per [par.24](http://at.teamed.io/policy.html#24)

**Comment by ypshenychka** [comment]
@Happy-Neko 
According to our [QA Rules](http://www.teamed.io/qa.html):
>Some of ticket messages must mention all pull requests where the problem was actually fixed.

Please provide a link to corresponding PR in any of your messages.

**Comment by Happy-Neko** [comment]
@ypshenychka done.

**Comment by ypshenychka** [comment]
@Happy-Neko Thanks.

**Comment by ypshenychka** [comment]
@davvd Quality is acceptable.

**Comment by davvd** [comment]
> @davvd Quality is acceptable.

@ypshenychka thanks a lot, next time everybody should try to make it better

**Comment by davvd** [comment]
@happy-neko added 10 mins to @ypshenychka, for QA review, payment code is `76281840`. thanks, paid, **30 mins** to your account, payment ID is `AP-9C067723X2568322V`, task took 238 hours and 43 mins to complete. +30 added to your rating, at the moment it is: [+158](http://www.netbout.com/b/36136?open=rating)
