### ISSUE TITLE
HmRqHeader refactoring

### ISSUE THREAD

**Issue by exper0** [yegor256/takes#521]
Right now [HmRqHeaders](https://github.com/yegor256/takes/blob/master/src/main/java/org/takes/facets/hamcrest/HmRqHeader.java) accepts HTTP headers only in lower case, that leads to the situation when I have to write "content-legth" instead of "Content-Legth" and "accept" instead of "Accept".

Let's refactor HmRqHeader in such a way that it can:
1) Get header name and value and matches it case-insensitive
2) Get separate matchers for header and value

**Comment by davvd** [comment]
@yegor256 please do something about this issue

**Comment by yegor256** [comment]
@0crat in

**Comment by 0crat** [comment]
> @0crat in ([here](https://github.com/yegor256/takes/issues/521#issuecomment-322125901))

@yegor256 Job `gh:yegor256/takes#521` is in scope.

**Comment by 0crat** [comment]
Job `gh:yegor256/takes#521` assigned to @caarlos0, please go ahead ([policy](http://datum.zerocracy.com/pages/policy.html)).

**Comment by 0crat** [comment]
@caarlos0 this job was assigned to you 8 days ago.
It will be taken away from you after 10 days from start (this is our policy).

**Comment by 0crat** [comment]
Oops! Job `gh:yegor256/takes#521` is not assigned to anyone.

**Comment by 0crat** [comment]
Oops! Job `gh:yegor256/takes#521` is not assigned to anyone.

**Comment by 0crat** [comment]
The job [#521](https://github.com/yegor256/takes/issues/521) assigned to @t-izbassar[/z](https://www.0crat.com/u/t-izbassar). The budget is 30 minutes, see [§4](http://datum.zerocracy.com/pages/policy.html#4). Please, read [§8](http://datum.zerocracy.com/pages/policy.html#8) and [§9](http://datum.zerocracy.com/pages/policy.html#9). If the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html).

**Comment by t-izbassar** [comment]
@exper0 I believe this issue is already fixed. Can you check it out and close this one?

**Comment by t-izbassar** [comment]
@0crat waiting for author as issue is already fixed.

**Comment by 0crat** [comment]
> @0crat waiting for author as issue is already fixed. ([here](https://github.com/yegor256/takes/issues/521#issuecomment-361964862))

@t-izbassar The impediment for [#521](https://github.com/yegor256/takes/issues/521) was registered successfully by @t-izbassar[/z](https://www.0crat.com/u/t-izbassar)

**Comment by t-izbassar** [comment]
@yegor256 I believe this one can be closed. I've checked @exper0 profile and he seems to be absent from GitHub so can you close this one? 

Issue is already fixed as current implementation of [HmHeader](https://github.com/yegor256/takes/blob/master/src/main/java/org/takes/facets/hamcrest/AbstractHmHeader.java) are indeed using case insensitive matchers and matchers for header name and header values are separated.

**Comment by 0crat** [comment]
Order was successfully finished: +30 points just awarded to @t-izbassar[/z](https://www.0crat.com/u/t-izbassar), total is [+165](https://www.0crat.com/u/t-izbassar)

**Comment by 0crat** [comment]
The job [#521](https://github.com/yegor256/takes/issues/521) is now out of scope
