### ISSUE TITLE
PsGithub doesn't handle an error from Github

### ISSUE THREAD

**Issue by dmzaytsev** [yegor256/takes#522]
PsGithub throws `com.jcabi.xml.ListWrapper$NodeNotFoundException` when the access token doesn't exist in the response from Github see https://github.com/yegor256/netbout/issues/933
I think PsGithub should handles an error from Github properly
https://developer.github.com/v3/oauth/#bad-verification-code

>com.jcabi.xml.ListWrapper$NodeNotFoundException: XPath '/OAuth/access_token/text()' not found in '\n\n <..162..#bad-verification-code\n': Index (0) is out of bounds (size=0)
at com.jcabi.xml.ListWrapper.get(ListWrapper.java:153)
at org.takes.facets.auth.social.PsGithub.token(PsGithub.java:156)
at org.takes.facets.auth.social.PsGithub.enter(PsGithub.java:115)

**Comment by davvd** [comment]
@yegor256 please dispatch this issue

**Comment by davvd** [comment]
@dmzaytsev I set milestone here to `1.0`, let me know if it is wrong

**Comment by davvd** [comment]
@sebing can you please help? Keep in mind [this](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html). If you have any technical questions, don't hesitate to ask right here

**30 mins** is the budget of the task. This is exactly how much will be paid when the problem is [solved](http://www.xdsd.org/2014/04/15/definition-of-done.html) (no matter how much time you will actually spend). See [this](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html) for more information

**Comment by sebing** [comment]
@davvd I have few questions:
1) How do I reproduce the issue, as I have no clue what the application is currently doing.(Can you guide me to a document or instruction to use the applicaiton)
2)If it is a bit difficult for me start understanding the application and fix the issue, can I get the full stack trace?
 - I am not sure where exactly the ListWrapper.get method is called.
 - PsGithub.java:156 and PsGithub.java:115 are both constructor calls

**Comment by davvd** [comment]
@dmzaytsev thanks for tis bug, I topped your account for 15 mins, transaction `75689897`

**Comment by dmzaytsev** [comment]
@sebing you can find the full stack trace here https://github.com/yegor256/netbout/issues/933

so in case of some error Github [returns](https://developer.github.com/v3/oauth/#bad-verification-code)
```
{
  "add_scopes": [
    "repo"
  ],
  "note": "admin script"
}
```
I know this is an json example not xml,  but it doesn't matter
there is no any `access_token` element, right?

but take a look [PsGithub.java#L156](https://github.com/yegor256/takes/blob/e3f1155574929fd02e79a7f0b5f1493984950d13/src/main/java/org/takes/facets/auth/social/PsGithub.java#L156)
the problem is here 
```
 .xml().xpath("/OAuth/access_token/text()").get(0);
```
we try to return the first element from the empty list

to reproduce you can create a new unit test for PsGithub like existing one
but the sample of  Github response shouldn't contains  `access_token` element

**Comment by sebing** [comment]
@dmzaytsev What is the expected behavior? 
- `access_token` should be in the xml all the time? 
  = if yes, do we have to throw a custom Exception than the generic one? And make sure the xml/json data is created with the access_token

**Comment by dmzaytsev** [comment]
@sebing I guess `HttpException` should be raised in case of empty `#xpath("/OAuth/access_token/text()")` @yegor256 what do you think?

see another Github error handling https://github.com/yegor256/takes/blob/e3f1155574929fd02e79a7f0b5f1493984950d13/src/main/java/org/takes/facets/auth/social/PsGithub.java#L110`

**Comment by sebing** [comment]
@dmzaytsev @davvd So I will split the constructor calling code[PsGithub.java#L156](https://github.com/yegor256/takes/blob/e3f1155574929fd02e79a7f0b5f1493984950d13/src/main/java/org/takes/facets/auth/social/PsGithub.java#L156), and throw the `HttpException`?

- I feel the naming of org.takes.HttpException is very confusing 
- What about using org.takes.facets.auth.codecs.DecodingException - the class in  codecs is again confusing.
- So should i create another exception in org.takes package

**Comment by dmzaytsev** [comment]
@sebing ask @yegor256 
he is the architect on this project

**Comment by sebing** [comment]
@dmzaytsev  Thanks for the guideline. 
@yegor256  Can you help me in this regard?

**Comment by sebing** [comment]
@yegor256 How do we proceed?

**Comment by sebing** [comment]
@davvd I made a pull request(https://github.com/yegor256/takes/pull/553)
But the travis-ci job is failing with 

`[ERROR] Failed to execute goal com.qulice:qulice-maven-plugin:0.14:check (jcabi-check) on project takes: Failure: 4 Checkstyle violations (see log above) -> [Help 1]

org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal com.qulice:qulice-maven-plugin:0.14:check (jcabi-check) on project takes: Failure`

how do I restart the checkstyle task?

**Comment by davvd** [comment]
> @davvd I made a pull request(https://github.com/yegor256/takes/pull/553)
> But the travis-ci job is failing with 
> 
> `[ERROR] Failed to execute goal com.qulice:qulice-maven-plugin:0.14:check (jcabi-check) on project takes: Failure: 4 Checkstyle violations (see log above) -> [Help 1]
> 
> org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal com.qulice:qulice-maven-plugin:0.14:check (jcabi-check) on project takes: Failure`
> 
> how do I restart the checkstyle task?

@sebing address your technical questions to the project architect (@yegor256)

**Comment by yegor256** [comment]
@sebing read this please: http://www.yegor256.com/2015/02/16/it-is-not-a-school.html

**Comment by sebing** [comment]
@davvd Can we close this issue as the merge request (https://github.com/yegor256/takes/pull/553) was accepted?

**Comment by davvd** [comment]
> @davvd Can we close this issue as the merge request (https://github.com/yegor256/takes/pull/553) was accepted? 

@sebing you should ask ticket author to close it, see http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html

**Comment by sebing** [comment]
@dmzaytsev Can we close this issue as the merge request (https://github.com/yegor256/takes/pull/553) was accepted?

**Comment by dmzaytsev** [comment]
@sebing thanks!

**Comment by sebing** [comment]
@dmzaytsev Thanks.

**Comment by sebing** [comment]
@davvd This task is finished and closed.

**Comment by davvd** [comment]
> @davvd This task is finished and closed.

@sebing OK thanks

**Comment by davvd** [comment]
@ypshenychka please, review this issue for QA compliance, as per [par.24](http://at.teamed.io/policy.html#24)

**Comment by ypshenychka** [comment]
@davvd Quality is good.

**Comment by davvd** [comment]
> @davvd Quality is good.

@ypshenychka many thanks

**Comment by davvd** [comment]
@sebing I added 10 mins to @ypshenychka (for QA review) in transaction 77185576; Many thanks! **30 mins** were added to your account in Transaction ID `56bcddcdadaf56566c000112` (task took 358 hours and 49 mins); +30 to your rating, your total score is [+75](http://www.netbout.com/b/36309?open=rating)
