### ISSUE TITLE
Let's update year in the header

### ISSUE THREAD

**Issue by exper0** [yegor256/takes#523]
Right now headers contains 
```
* Copyright (c) 2015 Yegor Bugayenko
```

It's 2016 already, worth updating

**Comment by exper0** [comment]
@yegor256 what about this issue? There is even PR #528 already.

**Comment by davvd** [comment]
@yegor256 dispatch this issue please, see [par.21](http://at.teamed.io/policy.html#21)

**Comment by yegor256** [comment]
@exper0 I'll think about it

**Comment by mkordas** [comment]
@yegor256 we're waiting for your resolution here, as my code review is still open

**Comment by mkordas** [comment]
@yegor256 ping

**Comment by yegor256** [comment]
@mkordas I'm waiting for a similar solution in qulice, so that we can just copy it here. I don't think this ticket is worth a full cycle. it's a minor change and a small check into deployment script. do you remember what is the ticket in qulice with the same problem?

**Comment by mkordas** [comment]
@yegor256 in qulice we had https://github.com/teamed/qulice/issues/583, but this is custom bash script. Maybe we should create our own `HeaderCheck` that would replace in license template e.g `$YEAR$` with current year? Thanks to that we would have generic solution for all projects using Qulice, no separate tickets needed to bump up years any more.

**Comment by mkordas** [comment]
@yegor256 ping

**Comment by yegor256** [comment]
@mkordas we basically need a small check that will fail Maven build when `LICENSE.txt` doesn't have `2013-2016`. that's it. we don't need to check all files. just one file for one text occurrence.

**Comment by yegor256** [comment]
@mkordas I'm closing this, in favor of #627
