### ISSUE TITLE
many implementations of org.takes.Response#body ignore charset

### ISSUE THREAD

**Issue by rfqu** [yegor256/takes#524]
HTTP response header usually has content-type header value with definition of charset. This charset must be taken into account when characters of the body are converted to bytes using the body() method.
But most (if not all) implementations of this method uses default charset, not that defined in the header.
This can happen indirectly, like in constructor 

```
public  RsWithBody(final Response res, final CharSequence body) {
        this(res, body.toString().getBytes());
    }
```

Here getBytes() use default charset instead of the charset defined in the header.

As a result, client which receives byte stream cannot reconstruct the characters of the response body.

**Comment by davvd** [comment]
@yegor256 please pay attention to this issue ([par.21](http://at.teamed.io/policy.html#21))

**Comment by davvd** [comment]
@rfqu I added milestone `1.0` to this issue, let me know if there has to be something else

**Comment by davvd** [comment]
@alexey-krylov this task is for you, keep [these principles](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html) in mind, and don't hesitate to ask any technical questions

The cost of this task is **30 mins** (this is exactly how much will be paid, not less not more), when the task is [done](http://www.xdsd.org/2014/04/15/definition-of-done.html)

**Comment by davvd** [comment]
@rfqu many thanks for the bug report, I added 15 mins to your acc, transaction `AP-4TS36903P0225481L`

**Comment by davvd** [comment]
@essobedo can you please help? Keep in mind [this](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html). If you have any technical questions, don't hesitate to ask right here. Budget here is **30 mins** (keep [this principle](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html) in mind)

**Comment by essobedo** [comment]
@rfqu Here is my pull request https://github.com/yegor256/takes/pull/565, please check it and if it is fine with you, close the ticket

**Comment by rfqu** [comment]
pull request #565 is ok

**Comment by essobedo** [comment]
@rfqu sorry my mistake this ticket should not be closed as long as the PR has not been merged, could you please reopen it?

**Comment by essobedo** [comment]
@rfqu thx

**Comment by essobedo** [comment]
@mkordas thank you for your remarks, here is my new PR https://github.com/yegor256/takes/pull/571

**Comment by mkordas** [comment]
@rfqu 
> pull request #565 is ok

Please update your comment with a name tag.

**Comment by rfqu** [comment]
pull request #571 is ok

**Comment by essobedo** [comment]
@rfqu The PR has not been merged so far, so you cannot close the ticket for now

**Comment by essobedo** [comment]
@rfqu Hi Alexei, now you can close the ticket as PR has been merged. Thank you in advance

**Comment by essobedo** [comment]
@rfqu Thank you very much

**Comment by essobedo** [comment]
@davvd the PR has been merged and the ticket has been closed, it is ready for the QA. Thank you in advance

**Comment by davvd** [comment]
@ypshenychka please, let us know what do you think about this ticket, according to our [QA rules](http://at.teamed.io/qa.html)

**Comment by ypshenychka** [comment]
@rfqu 
According to our [QA Rules](http://at.teamed.io/qa.html):
>Messages in a ticket always start with a name of a user they are addressed to.

Please correct your messages by indicating an addressee in the beginning.

**Comment by rfqu** [comment]
@essobedo closed

**Comment by essobedo** [comment]
@rfqu I guess that @ypshenychka expect from you that you modify 

> pull request #571 is ok

for something like for example

> @essobedo pull request #571 is ok

Thank you in advance

**Comment by rfqu** [comment]
@ypshenychka pull request #571 is ok

**Comment by essobedo** [comment]
@rfqu Sorry for the misunderstanding, you are not supposed to add new messages but to modify your previous messages in order to make them always start with @somebody like @essobedo for example. In other words all the messages in a ticket or a PR must have a recipient.

**Comment by essobedo** [comment]
@rfqu Sounds good now, thank you very much.

@ypshenychka It should be ok now, could you please re-check? Thank you in advance

**Comment by ypshenychka** [comment]
@rfqu @essobedo Thank you.

**Comment by ypshenychka** [comment]
@davvd Quality is acceptable.

**Comment by davvd** [comment]
> @davvd Quality is acceptable.

@ypshenychka thanks, got it. everybody, please try to make it good next time

**Comment by davvd** [comment]
@essobedo I added 10 mins to @ypshenychka (for QA review) in transaction 77332395. Many thanks! **30 mins** were added to your account in Transaction ID `77332405` (task took 220 hours and 22 mins). +30 to your rating, your total score is [+105](http://www.netbout.com/b/36421?open=rating)
