### ISSUE TITLE
Old qulice is being used

### ISSUE THREAD

**Issue by krzyk** [yegor256/takes#530]
Right now takes project uses qulice from jcab-parent, which is 0.14, but the newest one is 0.15.4.
This new release comes with new checks that can help with the review process (e.g. CascadingIndentationCheck or NonStaticMethodCheck).

**Comment by davvd** [comment]
@krzyk I will find a developer for the task soon...

**Comment by davvd** [comment]
@krzyk I set milestone here to `1.0`, let me know if it is wrong

**Comment by davvd** [comment]
@exper0 please proceed, it's yours

**Comment by davvd** [comment]
@krzyk thank you for reporting this, I added 15 mins to your acc, transaction `75203237`

**Comment by exper0** [comment]
@krzyk do you think we need just to update version of qulice and leave version of jcabi-parent as is?

**Comment by krzyk** [comment]
@exper0 you can report this upgrade to jcabi-parent, but qulice will always be ahead, so I would add version here. Waiting for parent will add unnecessary overhead.

**Comment by exper0** [comment]
@krzyk it's done in PR #535(merged). Please close the ticket

**Comment by krzyk** [comment]
@exper0 thanks

**Comment by davvd** [comment]
@krzyk once `530-0ac0fcef`/#558 puzzle is resolved (later, in another ticket), this ticket will be fully complete

**Comment by davvd** [comment]
@ypshenychka please, review this task for compliance with our [quality rules](http://at.teamed.io/qa.html)

**Comment by ypshenychka** [comment]
@davvd Quality is good.

**Comment by davvd** [comment]
> @davvd Quality is good.

@ypshenychka many thanks

**Comment by davvd** [comment]
@exper0 10 mins was added to the account of @ypshenychka (for QA review), in transaction 75966262. thanks, I just added **30 mins** to your account, payment `AP-2KJ3625987040821D`, 207 hours and 49 mins spent. +30 to your rating, your total score is [+633](http://www.netbout.com/b/36185?open=rating)

**Comment by davvd** [comment]
@krzyk the last puzzle `558-7b985928`/#600 originated from here solved
