### ISSUE TITLE
BkBasicTest.java:67-68: It will be nice to...

### ISSUE THREAD

**Issue by davvd** [yegor256/takes#533]
Puzzle `516-c8aa6c8f` in `src/test/java/org/takes/http/BkBasicTest.java:67-68` has to be resolved: It will be nice to refactor tests with Socket usage and replace them to real statements. See usage of BkBasicTest.createMockSocket.... The puzzle was created by lexx on 21-Jan-2016.

If you have any technical questions, don't ask me, submit new tickets instead. The task will be "done" when the problem is fixed and the text of the puzzle is removed from the source code.

**Comment by davvd** [comment]
@exper0 please proceed, it's yours

**Comment by davvd** [comment]
@yegor256 since the ticket has no milestone I set it to 1.0

**Comment by exper0** [comment]
@yegor256 @dmzaytsev @lexx what should I do here? I do not understand the task. What does "real statements" means?

**Comment by yegor256** [comment]
@exper0 I think that we should get rid of mocking here, since it's a bad thing in general, see http://www.yegor256.com/2014/09/23/built-in-fake-objects.html

**Comment by exper0** [comment]
@davvd need more time here.

**Comment by davvd** [comment]
> @davvd need more time here.

@exper0 no problem, thanks for letting me know

**Comment by exper0** [comment]
@davvd please assign to someone else.

**Comment by davvd** [comment]
> @davvd please assign to someone else.

@exper0 30 points deducted from your rating

**Comment by davvd** [comment]
> @davvd please assign to someone else.

@exper0 OK, I will try to assign someone else

**Comment by davvd** [comment]
@essobedo the task is yours plz proceed

**Comment by essobedo** [comment]
@davvd the [PR](https://github.com/yegor256/takes/pull/629) is ready to be reviewed thx in advance

**Comment by davvd** [comment]
> @davvd the [PR](https://github.com/yegor256/takes/pull/629) is ready to be reviewed thx in advance

@essobedo OK

**Comment by essobedo** [comment]
@davvd the PR has been merged, so could you please close the ticket and ask the QA to proceed. Thx in advance.

**Comment by essobedo** [comment]
@davvd please close the ticket

**Comment by essobedo** [comment]
@davvd please close the ticket

**Comment by essobedo** [comment]
@davvd the PR has been merged, so could you please close the ticket and ask the QA to proceed. Thx in advance.

**Comment by davvd** [comment]
@yegor256 I'm closing the issue...

**Comment by davvd** [comment]
@elenavolokhova please, check this issue for QA compliance, as per [par.24](http://at.teamed.io/policy.html#24)

**Comment by elenavolokhova** [comment]
@davvd Looks good!

**Comment by davvd** [comment]
> @davvd Looks good!

@elenavolokhova many thanks

**Comment by davvd** [comment]
@essobedo I added 10 mins to @elenavolokhova (for QA review) in transaction 79352198. done, I added **30 mins** in payment `79352218`, 100 hours and 1 min spent to complete this. +30 added to your rating, current score is: [+315](http://www.netbout.com/b/36421?open=rating)
