### ISSUE TITLE
BkBasicTest.java:69-71: Move header names from BkBasic...

### ISSUE THREAD

**Issue by davvd** [yegor256/takes#534]
Puzzle `516-ffc97ad1` in `src/test/java/org/takes/http/BkBasicTest.java:69-71` has to be resolved: Move header names from BkBasic to public constants. Reusable header names will help in many situations. For example - in new integration tests.... The puzzle was created by lexx on 21-Jan-2016.

If you have any technical questions, don't ask me, submit new tickets instead. The task will be "done" when the problem is fixed and the text of the puzzle is removed from the source code.

**Comment by davvd** [comment]
@danff the task is yours,please go ahead

**Comment by davvd** [comment]
@yegor256 I added milestone `1.0` to this issue, let me know if there has to be something else

**Comment by danff** [comment]
@davvd PR #537 for this issue created.

**Comment by davvd** [comment]
> @davvd PR #537 for this issue created.

@danff thanks

**Comment by danff** [comment]
@davvd need more time here - waiting for the PR resolution

**Comment by davvd** [comment]
> @davvd need more time here - waiting for the PR resolution

@danff sure, thanks for telling me, take your time

**Comment by davvd** [comment]
@yegor256 The task is closed, thanks everybody

**Comment by davvd** [comment]
@elenavolokhova please, help us to evaluate quality here, as per [par.24](http://at.teamed.io/policy.html#24)
