### ISSUE TITLE
RsFlash doesn't allow to set the expiration time for the cookie

### ISSUE THREAD

**Issue by dmzaytsev** [yegor256/takes#542]
Right now RsFlash doesn't allow to set the expiration time for the cookie
Default expiration time is one hour and it's hard-coded.

```
String.format(
                Locale.ENGLISH,
                "Expires=%1$ta, %1$td %1$tb %1$tY %1$tT GMT",
                new Date(
                    System.currentTimeMillis()
                        + TimeUnit.HOURS.toMillis(1L)
                )
            )
```

It would be great to be able to set the expiration time for the cookie

**Comment by davvd** [comment]
@dmzaytsev I am aware of the task, give me some time to find a developer...

**Comment by davvd** [comment]
@dmzaytsev there is no milestone yet, so I set it to `1.0`

**Comment by davvd** [comment]
@dmzaytsev thanks for reporting! I topped your account for 15 mins, transaction 75676223

**Comment by davvd** [comment]
@danff please go ahead with this task,it's yours

**Comment by danff** [comment]
@davvd waiting for #354 - expiration time is incorrect and avoid merging conflicts.

**Comment by davvd** [comment]
> @davvd waiting for #354 - expiration time is incorrect and avoid merging conflicts.

@danff OK, let's wait for #354

**Comment by yegor256** [comment]
@0crat in

**Comment by 0crat** [comment]
> @0crat in ([here](https://github.com/yegor256/takes/issues/542#issuecomment-322125923))

@yegor256 Job `gh:yegor256/takes#542` is in scope.

**Comment by 0crat** [comment]
Job `gh:yegor256/takes#542` assigned to @caarlos0, please go ahead ([policy](http://datum.zerocracy.com/pages/policy.html)).

**Comment by 0crat** [comment]
@caarlos0 this job was assigned to you 8 days ago.
It will be taken away from you after 10 days from start (this is our policy).

**Comment by 0crat** [comment]
Oops! Job `gh:yegor256/takes#542` is not assigned to anyone.

**Comment by 0crat** [comment]
Oops! Job `gh:yegor256/takes#542` is not assigned to anyone.

**Comment by 0crat** [comment]
The job [#542](https://github.com/yegor256/takes/issues/542) assigned to @t-izbassar[/z](http://www.0crat.com/u/t-izbassar). The budget is 30 minutes, see [§4](http://datum.zerocracy.com/pages/policy.html#4). Please, read [§8](http://datum.zerocracy.com/pages/policy.html#8) and [§9](http://datum.zerocracy.com/pages/policy.html#9). If the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html).

**Comment by t-izbassar** [comment]
@0crat waiting #354

**Comment by 0crat** [comment]
> @0crat waiting #354 ([here](https://github.com/yegor256/takes/issues/542#issuecomment-359910837))

@t-izbassar The impediment for [#542](https://github.com/yegor256/takes/issues/542) was registered successfully by @t-izbassar[/z](https://www.0crat.com/u/t-izbassar)

**Comment by t-izbassar** [comment]
@dmzaytsev hi. We can close this one as #789 was merged.

**Comment by 0crat** [comment]
Order was successfully finished: +30 points just awarded to @t-izbassar[/z](https://www.0crat.com/u/t-izbassar), total is [+195](https://www.0crat.com/u/t-izbassar)

**Comment by 0crat** [comment]
The job [#542](https://github.com/yegor256/takes/issues/542) is now out of scope
