### ISSUE TITLE
RqChunkTest.java:40-43: Implement reading chunked message body...

### ISSUE THREAD

**Issue by davvd** [yegor256/takes#544]
Puzzle `438-dcc4d707` in `src/test/java/org/takes/rq/RqChunkTest.java:40-43` has to be resolved: Implement reading chunked message body in {@link RqChunk} class to pass the tests. The request body should be treated as a serie of chunks and be capped to the chunks sizes sum.... The puzzle was created by HDouss on 27-Dec-2015.

If you have any technical questions, don't ask me, submit new tickets instead. The task will be "done" when the problem is fixed and the text of the puzzle is removed from the source code.

**Comment by davvd** [comment]
@alexey-krylov could you please pick this up? This [article](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html) explains how we work. Any technical questions you may ask right here... The budget of this issue is **45 mins**, which is exactly how much will be paid when the task is *done* (see [this](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html) for explanation)

**Comment by davvd** [comment]
@yegor256 I set the milestone to 1.0 since there is nothing set yet

**Comment by alexey-krylov** [comment]
@davvd  ok, i take this

**Comment by davvd** [comment]
> @davvd  ok, i take this

@alexey-krylov OK

**Comment by davvd** [comment]
@xupyprmv please proceed, it's yours

**Comment by xupyprmv** [comment]
@davvd I need more time here. My PR already approved and waits for final deploy.

**Comment by davvd** [comment]
> @davvd I need more time here. My PR was already approved and waits for final deploy.

@xupyprmv of course, thanks for letting me know, take your time

**Comment by xupyprmv** [comment]
@davvd PR #559 was merged. Please, close this ticket.

**Comment by davvd** [comment]
@yegor256 Thanks, closing it now.

**Comment by davvd** [comment]
@elenavolokhova please, help us to evaluate quality here, as per [par.24](http://at.teamed.io/policy.html#24)

**Comment by elenavolokhova** [comment]
@davvd Looks good!

**Comment by davvd** [comment]
> @davvd Looks good!

@elenavolokhova thanks for the review

**Comment by davvd** [comment]
@xupyprmv just added 10 mins to @elenavolokhova (for QA), payment ID is `78670787`

**45 mins** added to your account (payment number `AP-2KX055396L939714J`), many thanks for your contribution! 711 hours and 34 mins spent here.

+45 added to your rating, at the moment it is: [+180](http://www.netbout.com/b/35999?open=rating)
