### ISSUE TITLE
org.takes.facets.auth.PsByFlag::enter throws unchecked exception on invalid URLs

### ISSUE THREAD

**Issue by jhyle** [yegor256/takes#548]
See https://github.com/yegor256/netbout/issues/877. If PsByFlag encounters an invalid URL it throws an unchecked exception that make the request handling fail.

Therefore org.takes.misc.Href should catch the unchecked exception from URI.create in line 73 and rethrow it as a checked one so that programmers actually get informed that the method can fail. Then I a suggest a catch for this exception in org.takes.facets.auth.PsByFlag::enter. If the URI is not malformed it cannot match and so an empty Identity should be returned.

**Comment by jhyle** [comment]
@yegor256 Please review this issue.

**Comment by davvd** [comment]
@yegor256 please take a look at it and dispatch (see [par.21](http://at.teamed.io/policy.html#21))

**Comment by davvd** [comment]
@jhyle attached this issue to milestone "1.0" (let me know if this is wrong)

**Comment by davvd** [comment]
@jhyle many thanks, **15 mins** added to your acc for reporting this bug, pmt ID `AP-0TG82867UG3902633`

**Comment by davvd** [comment]
@essobedo please go ahead, it's your task now, keep [this](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html) in mind, and don't hesitate to ask any technical questions you may have. Task's budget is **30 mins** (see [this](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html) for explanation)

**Comment by essobedo** [comment]
@jhyle Here is my PR https://github.com/yegor256/takes/pull/568. Instead of throwing an exception that will require to modify a lot of code, I propose an auto fixing approach.

**Comment by jhyle** [comment]
@davvd Please ask someone to review the patch.

**Comment by davvd** [comment]
> @davvd Please ask someone to review the patch.

@jhyle OK

**Comment by essobedo** [comment]
@jhyle The PR has been merged, could you please close the ticket now? thank you in advance

**Comment by essobedo** [comment]
@davvd What is the next step knowing that the ticket is closed now?

**Comment by dmzaytsev** [comment]
@yegor256 please release whenever you have a chance

**Comment by essobedo** [comment]
@davvd the PR has been merged and the ticket has been closed, it is ready for the QA

**Comment by davvd** [comment]
@ypshenychka please, review this ticket for compliance with our [QA rules](http://at.teamed.io/qa.html)

**Comment by ypshenychka** [comment]
@davvd Quality is good.

**Comment by davvd** [comment]
> @davvd Quality is good.

@ypshenychka thank you :)

**Comment by essobedo** [comment]
@davvd the PR has been merged, the ticket has been closed, the QA approved it so could you please proceed, thank you in advance

**Comment by davvd** [comment]
@essobedo I added 10 mins to @ypshenychka (for QA review) in transaction 77176931

thank you, added **30 mins** to your acc, payment num is `77176968`, 117 hours and 22 mins spent in total to complete

+30 to your rating, your total score is [+60](http://www.netbout.com/b/36421?open=rating)

**Comment by essobedo** [comment]
@davvd thank you very much

**Comment by davvd** [comment]
> @davvd thank you very much

@essobedo you are welcome
