### ISSUE TITLE
Disable Scrutinizer for this repository

### ISSUE THREAD

**Issue by mkordas** [yegor256/takes#554]
We don't have in Takes any PHP, Python or Ruby code, so having Scrutinizer check for every PR doesn't make sense. Please disable it.

**Comment by yegor256** [comment]
@mkordas where did you find it here?

**Comment by mkordas** [comment]
@yegor256 in any open PR, see e.g. https://github.com/yegor256/takes/pull/553

**Comment by yegor256** [comment]
@mkordas disabled, thanks
