### ISSUE TITLE
Simplify instruction for Windows users

### ISSUE THREAD

**Issue by mkordas** [yegor256/takes#556]
Right now [How to contribute](https://github.com/yegor256/takes#how-to-contribute) section says that command `SET JAVA_TOOL_OPTIONS=-Dfile.encoding=UTF-8` needs to be invoked for Windows users to make build working

IMO, that's unnecessary manual step. We could just pass this env variable to surefire as JVM argument for tests, e.g.
```xml
          <plugin>
               <artifactId>maven-surefire-plugin</artifactId>
               <configuration>
                   <argLine>-Dfile.encoding=UTF-8</argLine>
               </configuration>
          </plugin>
```
Thanks to that we could also simlify AppVeyor config: https://github.com/yegor256/takes/blob/master/appveyor.yml#L23

**Comment by davvd** [comment]
@yegor256 please do something about this issue

**Comment by yegor256** [comment]
@mkordas fixed, thanks!
