### ISSUE TITLE
New qulice suppresion cleanups

### ISSUE THREAD

**Issue by krzyk** [yegor256/takes#557]
In qulice used currently in project there are two changes that result in less strict rules:
- `DoNotUseThreads` PMD check is disabled
- `UseConcurrentHashMap` PMD check is disabled.

As a result all suppressions of above rules should be removed, more over all usages of `ConcurrentMap` and `ConcurrentHashMap` should be reviewed and all unnecessary (single thread access) usages replaced with `Map` and `HashMap`.

**Comment by davvd** [comment]
@yegor256 please do something about it, see [par.21](http://at.teamed.io/policy.html#21)

**Comment by davvd** [comment]
@krzyk attached this issue to milestone "1.0" (let me know if this is wrong)

**Comment by davvd** [comment]
@krzyk thank you for the ticket reported, I topped your account for 15 mins, transaction `76462594`

**Comment by davvd** [comment]
@happy-neko please proceed, it's yours

**Comment by essobedo** [comment]
@krzyk good one! I was wondering why we had ConcurrentHashMap everywhere in the code even when it was not needed, now I understand

**Comment by Happy-Neko** [comment]
@krzyk PR #579 merged. Please close the ticket if everything is ok.

**Comment by krzyk** [comment]
@Happy-Neko thanks

**Comment by davvd** [comment]
@ypshenychka please, review this ticket for compliance with our [QA rules](http://at.teamed.io/qa.html)

**Comment by ypshenychka** [comment]
@davvd Quality is good.

**Comment by davvd** [comment]
> @davvd Quality is good.

@ypshenychka thanks for the review

**Comment by davvd** [comment]
@happy-neko added 10 mins to @ypshenychka, for QA review, payment code is `78632269`; thank you, added **30 mins** to your acc, payment num is `AP-0UA0172825302082C`, 317 hours and 10 mins spent in total to complete; added +30 to your rating, now it is equal to [+218](http://www.netbout.com/b/36136?open=rating)
