### ISSUE TITLE
pom.xml:313-317: Below excludes were created during...

### ISSUE THREAD

**Issue by davvd** [yegor256/takes#558]
Puzzle `530-0ac0fcef` in `pom.xml:313-317` has to be resolved: Below excludes were created during migration from qulice 0.13 to qulice 0.15.4. New qulice finds new additional issues in the code that need to be fixed. Checktyle issues were fixed in scope of #530, remaining PMD and XML issues to be fixed in scope of this puzzle.... The puzzle was created by Andrey Eliseev on 22-Jan-2016.

If you have any technical questions, don't ask me, submit new tickets instead. The task will be "done" when the problem is fixed and the text of the puzzle is removed from the source code.

<hr id='w'>

**Comment by davvd** [comment]
@yegor256 since there is no milestone yet I set it to "1.0"

**Comment by davvd** [comment]
@xupyprmv the task is yours, please go ahead

**Comment by xupyprmv** [comment]
@davvd PR #580 was merged. Please close this ticket.

**Comment by davvd** [comment]
@yegor256 these 11 puzzles were created in this ticket: `558-ffd45315`/#584, `558-4ea33ea6`, `558-7b985928`, `558-7db66253`, `558-b4a12ea6`, `558-12fc4eff`, `558-7c5810e9`, `558-e98f4792`, `558-d5ffb2ba`, `558-79259f7e`, `558-afc1c081`

**Comment by davvd** [comment]
@yegor256 Closed, thanks all

**Comment by davvd** [comment]
@elenavolokhova please, check this issue for QA compliance, as per [par.24](http://at.teamed.io/policy.html#24)

**Comment by elenavolokhova** [comment]
@davvd Looks good!

**Comment by davvd** [comment]
> @davvd Looks good!

@elenavolokhova thanks a lot

**Comment by davvd** [comment]
@xupyprmv just added 10 mins to @elenavolokhova (for QA), payment ID is `77191388`. Thanks a lot, I just topped your account for **30 mins**, transaction ID `AP-05J72082AC498280T`, total time was 148 hours and 9 mins. +30 added to your rating, current score is: [+120](http://www.netbout.com/b/35999?open=rating)

**Comment by yegor256** [comment]
@rultor deploy

**Comment by davvd** [comment]
@yegor256 the last puzzle `558-7b985928`/#600 solved
