### ISSUE TITLE
Takes hangs on fetching form parameter

### ISSUE THREAD

**Issue by piotrkot** [yegor256/takes#560]
Have a look at https://github.com/piotrkot/takesbug where the bug can be reproduced.

When you navigate to localhost:8080/form, provide input and submit then you will see the welcome "hello 'user'!" message.
When you go directly to localhost:8080/hello application freezes on fetching form parameter.

**Comment by davvd** [comment]
@yegor256 please pay attention to this issue ([par.21](http://at.teamed.io/policy.html#21))

**Comment by davvd** [comment]
@piotrkot attached this issue to milestone "1.0" (let me know if this is wrong)

**Comment by davvd** [comment]
@sebing the task is for you now, follow [these guidelines](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html). Don't hesitate to ask any technical questions right here. Task's budget is **30 mins** (see [this](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html) for explanation)

**Comment by sebing** [comment]
@piotrkot If the parameter ${user} is not present, I thought it is the right thing to show the error.
```
java.util.NoSuchElementException: there are no params "user" among 0 others: []
	at org.takes.misc.VerboseIterator.next(VerboseIterator.java:67)
	at Bug$1.act(Bug.java:46)
	at org.takes.facets.fork.FkRegex$1.act(FkRegex.java:152)
	at org.takes.facets.fork.FkRegex.route(FkRegex.java:189)
	at org.takes.facets.fork.TkFork.act(TkFork.java:101)
	at org.takes.http.BkBasic.print(BkBasic.java:99)
	at org.takes.http.BkBasic.accept(BkBasic.java:77)
	at org.takes.http.FtBasic.loop(FtBasic.java:116)
	at org.takes.http.FtBasic.start(FtBasic.java:102)
	at Bug.main(Bug.java:25)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:144)
```

**Comment by piotrkot** [comment]
@sebing Version I used (0.31.1 - the newest from MavenCentral) freezes. If you say you get an exception instead, you might be using a newer version. Please, confirm.
Either way, let me fetch current master and redo my test.

**Comment by sebing** [comment]
@piotrkot I used the latest version.

**Comment by piotrkot** [comment]
@sebing Indeed, the newest version does not have that issue. And `NoSuchElementException` is fine.
Thank you for the info.

**Comment by sebing** [comment]
@davvd This task is finished and closed.

**Comment by davvd** [comment]
> @davvd This task is finished and closed.

@sebing OK

**Comment by davvd** [comment]
@elenavolokhova please, review this issue for QA compliance, as per [par.24](http://at.teamed.io/policy.html#24)

**Comment by elenavolokhova** [comment]
@sebing 
  According to our [quality rules](http://www.teamed.io/qa.html):
 > Some of ticket messages must mention all pull requests where the problem was actually fixed.
 
 There is no link to related PR in comments. Please fix this issue and follow this rule in your tickets in the future.

**Comment by sebing** [comment]
@elenavolokhova There is no fix for this issue. Only the analysis, I have done and found that "this is not an issue"

**Comment by elenavolokhova** [comment]
@yegor256 Could you please help here? There was not actual fix for this issue, but performer did some investigation. Issue became outdated. What should we do in such cases?

**Comment by sebing** [comment]
@yegor256 How do we proceed here?

**Comment by yegor256** [comment]
@elenavolokhova the quality is acceptable here, I believe

**Comment by elenavolokhova** [comment]
@yegor256 Thank you very much!

**Comment by elenavolokhova** [comment]
@davvd Quality is acceptable here.

**Comment by davvd** [comment]
> @davvd Quality is acceptable here.

@elenavolokhova thanks for the review, we'll try better next time

**Comment by davvd** [comment]
@sebing 10 mins was added to the account of @elenavolokhova (for QA review), in transaction 78636580... Many thanks! **1 hour** were added to your account in Transaction ID `56d1b72e88fc154b49000006` (task took 18 hours and 54 mins)... m=1134, that's why a bonus here for fast delivery... +60 added to your rating, at the moment it is: [+105](http://www.netbout.com/b/36309?open=rating)
