### ISSUE TITLE
BkTimeableTest.stopsLongRunningBack fails randomly on jdk 1.8

### ISSUE THREAD

**Issue by essobedo** [yegor256/takes#566]
I got successively a build failure (https://travis-ci.org/yegor256/takes/jobs/107018856)  and a build success (https://travis-ci.org/yegor256/takes/jobs/107024568) with only a cosmetic change just to trigger a new build. So it seems that this particular test (BkTimeableTest.stopsLongRunningBack) is unstable.

**Comment by essobedo** [comment]
I occurred again https://travis-ci.org/yegor256/takes/jobs/107569131

**Comment by xupyprmv** [comment]
@essobedo Looks like tests are not stable for current Travis environment. I got the same error:

https://travis-ci.org/yegor256/takes/jobs/107832464

**Comment by essobedo** [comment]
I happened again https://travis-ci.org/yegor256/takes/jobs/108481815. It is getting rely anoying

**Comment by davvd** [comment]
@yegor256 dispatch this issue please, see [par.21](http://at.teamed.io/policy.html#21)

**Comment by davvd** [comment]
@essobedo since there is no milestone yet I set it to "1.0"

**Comment by davvd** [comment]
@essobedo thanks for this report, I added 15 mins to your account, in transaction `78630865`

**Comment by davvd** [comment]
@xupyprmv it's yours, please go ahead

**Comment by xupyprmv** [comment]
@essobedo It is a duplicate of #573, that was already resolved by PR #547. Nothing to do here. Please close this ticket.

**Comment by essobedo** [comment]
@xupyprmv This issue was created before #573 so it is actually the opposite but anyway if it is fixed already I can close the ticket for sure.

**Comment by xupyprmv** [comment]
@davvd ticket is closed (It is a duplicate, that was already resolved)

**Comment by davvd** [comment]
@elenavolokhova review this ticket please, for compliance with our [quality rules](http://at.teamed.io/qa.html)

**Comment by elenavolokhova** [comment]
@davvd Ticket is a duplicate, so the quality is bad here.

**Comment by davvd** [comment]
> @davvd Ticket is a duplicate, so the quality is bad here.

@elenavolokhova thanks, we'll try harder next time

**Comment by davvd** [comment]
@xupyprmv just added 10 mins to @elenavolokhova (for QA), payment ID is `79385439`
