### ISSUE TITLE
CapInputStream.java:37-40: CapInputStream should delegate all standard...

### ISSUE THREAD

**Issue by davvd** [yegor256/takes#575]
Puzzle `254-d68bc52e` in `src/main/java/org/takes/rq/CapInputStream.java:37-40` has to be resolved: CapInputStream should delegate all standard InputStream calls to it's origin. It's very important in context of closing stream - right code should close the stream but default InputStream implementation just throws IOException... The puzzle was created by Andrey Eliseev on 22-Jan-2016.

If you have any technical questions, don't ask me, submit new tickets instead. The task will be "done" when the problem is fixed and the text of the puzzle is removed from the source code.

**Comment by davvd** [comment]
@yegor256 milestone set to `1.0` (correct me if I am wrong)

**Comment by davvd** [comment]
@original-brownbear please go ahead with this task, it's yours

**Comment by original-brownbear** [comment]
@davvd PR #634 created :)

**Comment by davvd** [comment]
> @davvd PR #634 created :)

@original-brownbear thanks for that

**Comment by original-brownbear** [comment]
@davvd fix merged, can you please close this ? :)

**Comment by original-brownbear** [comment]
@davvd ping :)

**Comment by davvd** [comment]
@yegor256 Closing this issue now...

**Comment by davvd** [comment]
@ypshenychka please, review this issue for QA compliance, as per [par.24](http://at.teamed.io/policy.html#24)

**Comment by ypshenychka** [comment]
@davvd Quality is good.

**Comment by davvd** [comment]
> @davvd Quality is good.

@ypshenychka thanks!

**Comment by davvd** [comment]
@original-brownbear paied 10 mins to @ypshenychka for QA review (payment ID is `79317218`)

Thanks a lot, I just topped your account for **38 mins**, transaction ID `AP-5BD63918RA734602U`, total time was 67 hours and 42 mins

there is a bonus for fast delivery (m=4062)

added +38 to your rating, now it is equal to [+632](http://www.netbout.com/b/36646?open=rating)
