### ISSUE TITLE
RqMultipart.java:241-244: in order to delete temporary...

### ISSUE THREAD

**Issue by davvd** [yegor256/takes#576]
Puzzle `254-40a8e0fe` in `src/main/java/org/takes/rq/RqMultipart.java:241-244` has to be resolved: in order to delete temporary files InputStream instance on Request.body should be closed. In context of multipart requests that means that body of all parts should be closed once they are not needed anymore.... The puzzle was created by Andrey Eliseev on 22-Jan-2016.

If you have any technical questions, don't ask me, submit new tickets instead. The task will be "done" when the problem is fixed and the text of the puzzle is removed from the source code.

**Comment by davvd** [comment]
@yegor256 since there is no milestone yet I set it to "1.0"

**Comment by davvd** [comment]
@essobedo please go ahead with this task,it's yours

**Comment by essobedo** [comment]
@davvd here is my [PR](https://github.com/yegor256/takes/pull/644) that is ready to be reviewed. Thank you in advance.

**Comment by essobedo** [comment]
@davvd the PR has been merged so could you please proceed, thank you in advance.

**Comment by essobedo** [comment]
@davvd please proceed

**Comment by essobedo** [comment]
@davvd the PR has been merged so could you please proceed, thank you in advance.

**Comment by essobedo** [comment]
@davvd please proceed

**Comment by essobedo** [comment]
@davvd the PR has been merged so please close the ticket.

**Comment by essobedo** [comment]
@davvd the PR has been approved by the QA, so please ask the QA to validate the ticket.

**Comment by davvd** [comment]
> @davvd here is my PR #644 that is ready to be reviewed. Thank you in advance.

@essobedo OK

**Comment by davvd** [comment]
> @davvd the PR has been merged so could you please proceed, thank you in advance.

@essobedo OK

**Comment by davvd** [comment]
> @davvd please proceed

@essobedo OK

**Comment by davvd** [comment]
> @davvd the PR has been merged so could you please proceed, thank you in advance.

@essobedo OK thanks

**Comment by davvd** [comment]
> @davvd please proceed

@essobedo OK

**Comment by davvd** [comment]
> @davvd the PR has been merged so please close the ticket.

@essobedo OK

**Comment by essobedo** [comment]
@davvd sorry to insist but I'm stuck because of my false quota set to 2 instead of 5, so could you please proceed with the QA and close the ticket. Thank you in advance.

**Comment by davvd** [comment]
> @davvd here is my PR #644 that is ready to be reviewed. Thank you in advance.

@essobedo OK

**Comment by davvd** [comment]
> @davvd the PR has been merged so could you please proceed, thank you in advance.

@essobedo OK

**Comment by davvd** [comment]
> @davvd please proceed

@essobedo OK

**Comment by davvd** [comment]
> @davvd the PR has been merged so could you please proceed, thank you in advance.

@essobedo OK thanks

**Comment by davvd** [comment]
> @davvd please proceed

@essobedo OK

**Comment by davvd** [comment]
> @davvd the PR has been merged so please close the ticket.

@essobedo OK

**Comment by yegor256** [comment]
@essobedo the ticket will be closed when this puzzle disappears from the source code

**Comment by yegor256** [comment]
@rultor deploy

**Comment by essobedo** [comment]
@yegor256 Thank you for the info, I'm definitely stuck then.

**Comment by davvd** [comment]
@yegor256 Finished, thanks, closing..

**Comment by davvd** [comment]
@ypshenychka please, review this issue for QA compliance, as per [par.24](http://at.teamed.io/policy.html#24)

**Comment by ypshenychka** [comment]
@davvd Quality is good.

**Comment by davvd** [comment]
> @davvd here is my PR #644 that is ready to be reviewed. Thank you in advance.

@essobedo OK

**Comment by davvd** [comment]
> @davvd the PR has been merged so could you please proceed, thank you in advance.

@essobedo OK

**Comment by davvd** [comment]
> @davvd please proceed

@essobedo OK

**Comment by davvd** [comment]
> @davvd the PR has been merged so could you please proceed, thank you in advance.

@essobedo OK thanks

**Comment by davvd** [comment]
> @davvd please proceed

@essobedo OK

**Comment by davvd** [comment]
> @davvd the PR has been merged so please close the ticket.

@essobedo OK

**Comment by davvd** [comment]
> @davvd here is my PR #644 that is ready to be reviewed. Thank you in advance.

@essobedo OK

**Comment by davvd** [comment]
> @davvd the PR has been approved by the QA, so please ask the QA to validate the ticket.

@essobedo will do, when time comes :) thanks for reminding

**Comment by davvd** [comment]
> @davvd Quality is good.

@ypshenychka many thanks

**Comment by davvd** [comment]
@essobedo I added 10 mins to @ypshenychka (for QA review) in transaction 81148020; Thank you, I have added **30 mins** to your account in payment/transaction "`81148049`", time consumed: 138 hours and 22 mins; +30 added to your rating, at the moment it is: [+345](http://www.netbout.com/b/36421?open=rating)
