### ISSUE TITLE
Java 6 compatability

### ISSUE THREAD

**Issue by Happy-Neko** [yegor256/takes#578]
Takes promotes itself as 

> Java6 web development framework

and compiles to 1.6 bytecode. But there are usages of core APIs unavailable on JDK6 making the framework Java 6 incompatible. 

For example `StandardCharsets` in **RsVelocity**.

**Comment by yegor256** [comment]
@Happy-Neko yeah, we're not JDK6 compatible any more :(

**Comment by yegor256** [comment]
@Happy-Neko fixed in 8fa53fe
