### ISSUE TITLE
Content-Length is not added by RsWithBody

### ISSUE THREAD

**Issue by yegor256** [yegor256/takes#58]
`Content-Length` is an important header and should be added to the response by `RsWithBody`

**Comment by davvd** [comment]
@yegor256 sure, thanks, I added bug tag to it

**Comment by davvd** [comment]
@yegor256 thanks for this report, I added 15 mins to your account, in transaction `000-bd96cb88`

**Comment by davvd** [comment]
@nathansgreen it's yours, please go ahead

**Comment by davvd** [comment]
@nathansgreen this task is in your hands for 15 days already; added -30 to your rating, now it is equal to [+75](http://www.netbout.com/b/35107?open=rating)

**Comment by davvd** [comment]
@nathansgreen it takes too long. Usually, we expect any task to be finished in less than a week. I'll assign someone else. Please stop working with it right now. See our [no obligations](http://www.xdsd.org/2014/04/13/no-obligations-principle.html) principle. added -60 to your rating, now it is equal to [-120](http://www.netbout.com/b/35107?open=rating)

**Comment by davvd** [comment]
@popprem this task is for you, keep [these principles](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html) in mind, and don't hesitate to ask any technical questions. The budget of this issue is **30 mins**, which is exactly how much will be paid when the task is *done* (see [this](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html) for explanation)

**Comment by davvd** [comment]
@popprem you're holding this ticket for 15 days already. If it is not finished (and closed) in the next 48 hours, it will be re-assigned to someone else, see [No Obligations](http://www.xdsd.org/2014/04/13/no-obligations-principle.html) principle ([this article](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html) should help if you're stuck); added -30 to your rating, now it is equal to [-210](http://www.netbout.com/b/35169?open=rating)

**Comment by popprem** [comment]
@yegor256 PR #189 done for this issue. Please close this bug.

**Comment by yegor256** [comment]
@popprem thanks!

**Comment by davvd** [comment]
@elenavolokhova please, review this ticket for compliance with our [QA rules](http://www.teamed.io/qa.html)

**Comment by elenavolokhova** [comment]
@davvd Looks good!

**Comment by davvd** [comment]
> @davvd Looks good!

@elenavolokhova thanks, got it, great to see high-quality tickets here

**Comment by davvd** [comment]
> @davvd Looks good!

@elenavolokhova thank you

**Comment by davvd** [comment]
> @davvd Looks good!

@elenavolokhova thank you

**Comment by davvd** [comment]
> @davvd Looks good!

@elenavolokhova thank you :)

**Comment by davvd** [comment]
> @davvd Looks good!

@elenavolokhova thank you, good quality is always good :)

**Comment by davvd** [comment]
> @davvd Looks good!

@elenavolokhova thank you, good quality is always good :)

**Comment by davvd** [comment]
> @davvd Looks good!

@elenavolokhova thanks, got it, great to see high-quality tickets here

**Comment by davvd** [comment]
@popprem just added 10 mins to @elenavolokhova (for QA), payment ID is `56810997`
