### ISSUE TITLE
Appveyor fails when using specific features of Java 7

### ISSUE THREAD

**Issue by essobedo** [yegor256/takes#582]
According to #578, the project is no more compatible with Java 6 but Appveyor prevents to use specific features of Java 7 such as the diamond operator as you can see here https://ci.appveyor.com/project/yegor256/takes/build/2109. Is it expected or is it a bug in the pom file?

**Comment by davvd** [comment]
@yegor256 please do something about this issue

**Comment by yegor256** [comment]
@essobedo it's a bug, thanks for reporting

**Comment by davvd** [comment]
@essobedo since the ticket has no milestone I set it to 1.0

**Comment by davvd** [comment]
@essobedo many thanks, **15 mins** added to your acc for reporting this bug, pmt ID `77261952`

**Comment by davvd** [comment]
@2686747 it's yours now, please proceed keeping in mind [our principles](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html). Feel free to ask any technical questions right here in the ticket... The budget of this task is **30 mins**. This is exactly how much time will be compensated, when the task is completed. Read about our [Definition of Done](http://www.xdsd.org/2014/04/15/definition-of-done.html)

**Comment by 2686747** [comment]
@essobedo fixed, please check #613

**Comment by essobedo** [comment]
@2686747 sounds good thx

**Comment by 2686747** [comment]
@essobedo can you close ticket?

**Comment by essobedo** [comment]
@2686747 sure

**Comment by davvd** [comment]
@ypshenychka please, review this ticket for compliance with our [QA rules](http://at.teamed.io/qa.html)

**Comment by ypshenychka** [comment]
@davvd Quality is good.

**Comment by davvd** [comment]
> @davvd Quality is good.

@ypshenychka thanks a lot

**Comment by 2686747** [comment]
@davvd can you calculate this task?

**Comment by davvd** [comment]
@2686747 added 10 mins to @ypshenychka, for QA review, payment code is `78644128`. Thank you, I have added **38 mins** to your account in payment/transaction "`56d1faa59f490454a0000252`", time consumed: 51 hours and 50 mins. m=3110, that's why a bonus here for fast delivery. added +38 to your rating, now it is equal to [+8](http://www.netbout.com/b/36452?open=rating)
