### ISSUE TITLE
pom.xml:308-310: Upgrade Qulice to 0.16. Fix...

### ISSUE THREAD

**Issue by davvd** [yegor256/takes#584]
Puzzle `558-ffd45315` in `pom.xml:308-310` has to be resolved: Upgrade Qulice to 0.16. Fix all checkstyle violations (mostly `AtclauseOrderCheck`). Fix or add puzzle for PMD, findbugs and other types of violations.... The puzzle was created by Maksimenko Vladimir on 8-Feb-2016.

If you have any technical questions, don't ask me, submit new tickets instead. The task will be "done" when the problem is fixed and the text of the puzzle is removed from the source code.

**Comment by davvd** [comment]
@essobedo This task is yours, please go ahead keeping in mind [this](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html). If any questions, don't hesitate to ask right here... Task's budget is **30 mins** (see [this](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html) for explanation)

**Comment by essobedo** [comment]
@davvd the PR is ready to be reviewed thx in advance

**Comment by davvd** [comment]
@yegor256 since the ticket has no milestone I set it to 1.0

**Comment by essobedo** [comment]
@davvd The PR has been merged, could you please close the ticket and proceed with the QA. Thank you in advance.

**Comment by essobedo** [comment]
@davvd please close the ticket and proceed with the QA.

**Comment by essobedo** [comment]
@davvd please close the ticket and proceed with the QA.

**Comment by davvd** [comment]
@yegor256 The issue is closed

**Comment by davvd** [comment]
@ypshenychka please, let us know what do you think about this ticket, according to our [QA rules](http://at.teamed.io/qa.html)

**Comment by ypshenychka** [comment]
@davvd Quality is good.

**Comment by davvd** [comment]
> @davvd Quality is good.

@ypshenychka thank you, good quality is always good ;)

**Comment by essobedo** [comment]
@davvd everything is ok here could you please proceed?

**Comment by davvd** [comment]
@essobedo I added 10 mins to @ypshenychka (for QA review) in transaction 78708279... Many thanks! **30 mins** were added to your account in Transaction ID `78708285` (task took 402 hours and 21 mins)... added +30 to your rating, now it is equal to [+195](http://www.netbout.com/b/36421?open=rating)

**Comment by essobedo** [comment]
@davvd thank you very much!

**Comment by davvd** [comment]
> @davvd thank you very much!

@essobedo sure, no problem
