### ISSUE TITLE
Options.java:71-75: Options ctor. According to new...

### ISSUE THREAD

**Issue by davvd** [yegor256/takes#586]
Puzzle `558-e98f4792` in `src/main/java/org/takes/http/Options.java:71-75` has to be resolved: Options ctor. According to new qulice version, constructor must contain only variables initialization and other constructor calls. Refactor code according to that rule and remove `ConstructorOnlyInitializesOrCallOtherConstructors` warning suppression.... The puzzle was created by Maksimenko Vladimir on 7-Feb-2016.

If you have any technical questions, don't ask me, submit new tickets instead. The task will be "done" when the problem is fixed and the text of the puzzle is removed from the source code.

**Comment by davvd** [comment]
@essobedo the task is for you now, follow [these guidelines](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html). Don't hesitate to ask any technical questions right here

The cost of this task is **30 mins** (this is exactly how much will be paid, not less not more), when the task is [done](http://www.xdsd.org/2014/04/15/definition-of-done.html)

**Comment by essobedo** [comment]
@davvd the PR is ready to be reviewed thx in advance

**Comment by davvd** [comment]
@yegor256 I added milestone `1.0` to this issue, let me know if there has to be something else

**Comment by essobedo** [comment]
@davvd The PR has been merged, could you please close the ticket and proceed with the QA. Thank you in advance.

**Comment by essobedo** [comment]
@davvd please close the ticket and proceed with the QA.

**Comment by essobedo** [comment]
@davvd please close the ticket and proceed with the QA.

**Comment by essobedo** [comment]
@davvd please close the ticket and proceed with the QA.

**Comment by essobedo** [comment]
@davvd please close the ticket and proceed with the QA.

**Comment by davvd** [comment]
@yegor256 The issue is closed

**Comment by davvd** [comment]
@ypshenychka please, help us to evaluate quality here, as per [par.24](http://at.teamed.io/policy.html#24)

**Comment by ypshenychka** [comment]
@davvd Quality is good.

**Comment by davvd** [comment]
> @davvd Quality is good.

@ypshenychka thanks a lot

**Comment by essobedo** [comment]
@davvd everything is ok here could you please proceed?

**Comment by davvd** [comment]
@essobedo 10 mins was added to the account of @ypshenychka (for QA review), in transaction 78972384. Thanks so much! Your account was topped up for **30 mins** (transaction ID is `78972560`, the task took 399 hours and 41 mins). +30 added to your rating, at the moment it is: [+225](http://www.netbout.com/b/36421?open=rating)

**Comment by essobedo** [comment]
@davvd thank you very much!

**Comment by davvd** [comment]
> @davvd thank you very much!

@essobedo sure, you are welcome
