### ISSUE TITLE
Href.java:76-80: Href ctor. According to new...

### ISSUE THREAD

**Issue by davvd** [yegor256/takes#588]
Puzzle `558-d5ffb2ba` in `src/main/java/org/takes/misc/Href.java:76-80` has to be resolved: Href ctor. According to new qulice version, constructor must contain only variables initialization and other constructor calls. Refactor code according to that rule and remove `ConstructorOnlyInitializesOrCallOtherConstructors` warning suppression.... The puzzle was created by Maksimenko Vladimir on 7-Feb-2016.

If you have any technical questions, don't ask me, submit new tickets instead. The task will be "done" when the problem is fixed and the text of the puzzle is removed from the source code.

**Comment by davvd** [comment]
@essobedo it's yours now, please proceed keeping in mind [our principles](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html). Feel free to ask any technical questions right here in the ticket; The cost of this task is **30 mins** (this is exactly how much will be paid, not less not more), when the task is [done](http://www.xdsd.org/2014/04/15/definition-of-done.html)

**Comment by davvd** [comment]
@yegor256 I set the milestone to 1.0 since there is nothing set yet

**Comment by essobedo** [comment]
@davvd the PR is ready to be reviewed thx in advance

**Comment by davvd** [comment]
> @davvd the PR is ready to be reviewed thx in advance

@essobedo OK

**Comment by essobedo** [comment]
@davvd The PR has been merged, could you please close the ticket and proceed with the QA. Thank you in advance.

**Comment by essobedo** [comment]
@davvd please close the ticket and proceed with the QA.

**Comment by essobedo** [comment]
@davvd please close the ticket and proceed with the QA.

**Comment by essobedo** [comment]
@davvd please close the ticket and proceed with the QA.

**Comment by essobedo** [comment]
@davvd please close the ticket and proceed with the QA.

**Comment by davvd** [comment]
@yegor256 I'm closing the issue...

**Comment by davvd** [comment]
@elenavolokhova please, review this ticket for compliance with our [QA rules](http://at.teamed.io/qa.html)

**Comment by elenavolokhova** [comment]
@essobedo 
  According to our [quality rules](http://www.teamed.io/qa.html):
 > Some of ticket messages must mention all pull requests where the problem was actually fixed.
 
 There is no link to related PR in comments. Please fix this issue and follow this rule in your tickets in the future.

**Comment by essobedo** [comment]
@elenavolokhova Fixed, thanks for the feedback

**Comment by elenavolokhova** [comment]
@essobedo Thanks!

**Comment by elenavolokhova** [comment]
@davvd Quality is acceptable here.

**Comment by davvd** [comment]
> @davvd Quality is acceptable here.

@elenavolokhova thanks a lot, next time everybody should try to make it better

**Comment by essobedo** [comment]
@davvd everything is ok here could you please proceed?

**Comment by essobedo** [comment]
@davvd everything is ok here could you please proceed?

**Comment by davvd** [comment]
@essobedo paied 10 mins to @elenavolokhova for QA review (payment ID is `79016796`)... Thanks for your contribution, **30 mins** was added to your account, payment ID is `79016828`, 397 hours and 57 mins spent total... +30 added to your rating, at the moment it is: [+255](http://www.netbout.com/b/36421?open=rating)

**Comment by essobedo** [comment]
@davvd thank you very much!

**Comment by davvd** [comment]
> @davvd everything is ok here could you please proceed?

@essobedo OK

**Comment by davvd** [comment]
> @davvd thank you very much!

@essobedo you are welcome
