### ISSUE TITLE
FkHitRefresh.java:117-121: FkHitRefresh ctor. According to new...

### ISSUE THREAD

**Issue by davvd** [yegor256/takes#589]
Puzzle `558-b4a12ea6` in `src/main/java/org/takes/facets/fork/FkHitRefresh.java:117-121` has to be resolved: FkHitRefresh ctor. According to new qulice version, constructor must contain only variables initialization and other constructor calls. Refactor code according to that rule and remove `ConstructorOnlyInitializesOrCallOtherConstructors` warning suppression.... The puzzle was created by Maksimenko Vladimir on 7-Feb-2016.

If you have any technical questions, don't ask me, submit new tickets instead. The task will be "done" when the problem is fixed and the text of the puzzle is removed from the source code.

**Comment by davvd** [comment]
@essobedo this task is for you, keep [these principles](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html) in mind, and don't hesitate to ask any technical questions... **30 mins** is the budget of the task. This is exactly how much will be paid when the problem is [solved](http://www.xdsd.org/2014/04/15/definition-of-done.html) (no matter how much time you will actually spend). See [this](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html) for more information

**Comment by essobedo** [comment]
@davvd the PR is ready to be reviewed thx in advance

**Comment by davvd** [comment]
@yegor256 attached this issue to milestone "1.0" (let me know if this is wrong)

**Comment by essobedo** [comment]
@davvd The PR has been merged, could you please close the ticket and proceed with the QA. Thank you in advance.

**Comment by essobedo** [comment]
@davvd please close the ticket and proceed with the QA.

**Comment by essobedo** [comment]
@davvd please close the ticket and proceed with the QA.

**Comment by davvd** [comment]
@yegor256 Closing..

**Comment by davvd** [comment]
@elenavolokhova review this ticket please, for compliance with our [quality rules](http://at.teamed.io/qa.html)

**Comment by elenavolokhova** [comment]
@essobedo 
  According to our [quality rules](http://www.teamed.io/qa.html):
 > Some of ticket messages must mention all pull requests where the problem was actually fixed.
 
 There is no link to related PR in comments. Please fix this issue and follow this rule in your tickets in the future.

**Comment by essobedo** [comment]
@elenavolokhova link to the PR added thanks for the feedback

**Comment by elenavolokhova** [comment]
@davvd Quality is acceptable here.

**Comment by davvd** [comment]
> @davvd Quality is acceptable here.

@elenavolokhova thank you, let's try to make it "good" next time

**Comment by essobedo** [comment]
@davvd everything is ok here could you please proceed?

**Comment by essobedo** [comment]
@davvd everything is ok here could you please proceed?

**Comment by essobedo** [comment]
@davvd the last one please

**Comment by davvd** [comment]
@essobedo just added 10 mins to @elenavolokhova (for QA), payment ID is `79023774`; paid, thanks, added **30 mins** to your account, payment `79023789`, 396 hours and 56 mins was spent; +30 added to your rating, at the moment it is: [+285](http://www.netbout.com/b/36421?open=rating)

**Comment by essobedo** [comment]
@davvd thank you

**Comment by davvd** [comment]
> @davvd everything is ok here could you please proceed?

@essobedo I will, give it some time. we usually pay in 2-3 days after the ticket is closed

**Comment by davvd** [comment]
> @davvd thank you

@essobedo you are welcome

**Comment by essobedo** [comment]
> @essobedo I will, give it some time. we usually pay in 2-3 days after the ticket is closed

@davvd thank you for the info
