### ISSUE TITLE
Fork chain

### ISSUE THREAD

**Issue by pinaf** [yegor256/takes#590]
A useful Fork would be a Fork chain, that routes to each Fork in order until one returns a result, or until none are left.

Here is a suggested implementation. Please add unit tests.
```java
/**
 * A {@link Fork} chain. Routes to each {@link Fork} in order until one returns
 * a response or until none are left.
 * @author Felipe Pina (felipe.pina@protonmail.com)
 * @version $Id$
 * @since 0.32
 */
public final class FkChain implements Fork {

    /**
     * Forks.
     */
    private final transient Collection<Fork> forks;

    /**
     * Ctor.
     */
    public FkChain() {
        this(Collections.<Fork>emptyList());
    }

    /**
     * Ctor.
     * @param forks Forks
     */
    public FkChain(final Fork... forks) {
        this(Arrays.asList(forks));
    }

    /**
     * Ctor.
     * @param forks Forks
     */
    public FkChain(final Collection<Fork> forks) {
        this.forks = Collections.unmodifiableCollection(forks);
    }

    @Override
    public Opt<Response> route(final Request request) throws IOException {
        Opt<Response> response = new Opt.Empty<>();
        for (final Fork fork : this.forks) {
            final Opt<Response> current = fork.route(request);
            if (current.has()) {
                response = current;
                break;
            }
        }
        return response;
    }
```

Also, the implementation of `TkFork` can be simplified by the use of `FkChain`..

**Comment by davvd** [comment]
@yegor256 please do something about it, see [par.21](http://at.teamed.io/policy.html#21)

**Comment by davvd** [comment]
@pinaf since there is no milestone yet I set it to "1.0"

**Comment by davvd** [comment]
@pinaf thanks for reporting! I topped your account for 15 mins, transaction AP-1EP049084G213611F

**Comment by davvd** [comment]
@carlosgines This task is yours, please go ahead keeping in mind [this](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html). If any questions, don't hesitate to ask right here... The cost of this task is **30 mins** (this is exactly how much will be paid, not less not more), when the task is [done](http://www.xdsd.org/2014/04/15/definition-of-done.html)

**Comment by CarlosGines** [comment]
@davvd thanks. I have a question. What values should I set for `@version` and `@since` in javadoc? I see there is some kind of hash for `@version`. And then then for `@since` I don't know whether I should set `0.31.4` or `0.32` or `1.0`. Thank you.

**Comment by CarlosGines** [comment]
@davvd please check PR #636

**Comment by CarlosGines** [comment]
@davvd please check PR #636

**Comment by davvd** [comment]
> @davvd please check PR #636 

@carlosgines thanks for that

**Comment by pinaf** [comment]
@CarlosGines thanks!

**Comment by CarlosGines** [comment]
@pinaf thank you!

**Comment by CarlosGines** [comment]
@davvd the ticket is closed! Could we please move on to the QA stage? :)
I would also like to know, regarding my "speed" solving this tasks, when is it that the "timer" stops? When the PR is merged? When the ticket is closed? or any other moment? Thank you!

**Comment by davvd** [comment]
@elenavolokhova please, help us to evaluate quality here, as per [par.24](http://at.teamed.io/policy.html#24)

**Comment by davvd** [comment]
> @davvd the ticket is closed! Could we please move on to the QA stage? :)
> I would also like to know, regarding my "speed" solving this tasks, when is it that the "timer" stops? When the PR is merged? When the ticket is closed? or any other moment? Thank you!

@carlosgines sure, we do that automatically, just give us some time

**Comment by elenavolokhova** [comment]
@davvd Looks good!

**Comment by davvd** [comment]
> @davvd Looks good!

@elenavolokhova thanks, got it, great to see high-quality tickets here

**Comment by davvd** [comment]
@carlosgines I added 10 mins to @elenavolokhova (for QA review) in transaction 79792809. Thanks for your contribution, **30 mins** was added to your account, payment ID is `AP-0EH45812E3876770X`, 150 hours and 19 mins spent total. added +30 to your rating, now it is equal to [+75](http://www.netbout.com/b/36645?open=rating)

**Comment by CarlosGines** [comment]
@davvd I read [here](http://at.teamed.io/policy.html#25) that the performer gets a bonus if quality is good. What is this bonus? I did not see anything about it here.

**Comment by davvd** [comment]
> @davvd I read [here](http://at.teamed.io/policy.html#25) that the performer gets a bonus if quality is good. What is this bonus? I did not see anything about it here.

@carlosgines we don't pay that bonus yet, that's why the policy doesn't say anything specific yet

**Comment by CarlosGines** [comment]
@davvd Ok, thank you for your answer!

**Comment by davvd** [comment]
> @davvd Ok, thank you for your answer!

@carlosgines sure, no problem
