### ISSUE TITLE
FtCLITest.understandsCommandLineArgs fails randomly on Travis

### ISSUE THREAD

**Issue by essobedo** [yegor256/takes#591]
I got successively a build failure (https://travis-ci.org/yegor256/takes/jobs/108471319) and a build success (https://travis-ci.org/yegor256/takes/jobs/108472875) with only more javadoc just to trigger a new build. So it seems that this particular test (FtCLITest.understandsCommandLineArgs) is unstable on Travis environment.

**Comment by davvd** [comment]
@yegor256 please dispatch this issue

**Comment by davvd** [comment]
@essobedo attached this issue to milestone "1.0" (let me know if this is wrong)

**Comment by davvd** [comment]
@essobedo thanks for the report, I topped your acc for 15 mins, payment ID `77791203`

**Comment by davvd** [comment]
@rfqu the task is for you now, follow [these guidelines](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html). Don't hesitate to ask any technical questions right here... **30 mins** is the budget of the task. This is exactly how much will be paid when the problem is [solved](http://www.xdsd.org/2014/04/15/definition-of-done.html) (no matter how much time you will actually spend). See [this](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html) for more information

**Comment by davvd** [comment]
@rfqu this task is taking too long, I have to change the performer, sorry. Please stop working with it right now. See our [no obligations](http://www.xdsd.org/2014/04/13/no-obligations-principle.html) principle. -60 to your rating, your total score is [-135](http://www.netbout.com/b/36195?open=rating)

**Comment by davvd** [comment]
@bubelov this ticket is yours now, please proceed, and keep in mind [this](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html). Any technical questions you should ask right here

This task's budget is **30 mins**. This is exactly how much will be paid when the problem explained above is solved. See [this](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html) for more information

**Comment by davvd** [comment]
@bubelov check this ["no obligations principle"](http://www.xdsd.org/2014/04/13/no-obligations-principle.html).. This task is on your name for at least 15 days. If you can't close it within the next 48 hours I will have to assign someone else to it. [This article](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html) should help if you're stuck... -30 added to your rating, current score is: [-14](http://www.netbout.com/b/36478?open=rating)

**Comment by essobedo** [comment]
@davvd The build doesn't fail anymore, this issue has been fixed by another ticket so it is obviously out dated.

**Comment by davvd** [comment]
> @davvd The build doesn't fail anymore, this issue has been fixed by another ticket so it is obviously out dated. 

@essobedo just close it

**Comment by essobedo** [comment]
> @essobedo just close it

OK np

**Comment by davvd** [comment]
@bubelov I'm not sure who actually completed this task, since there were no messages from you above (correct me if I'm wrong)
