### ISSUE TITLE
RqMultipart.java:131-135: Base ctor. According to new...

### ISSUE THREAD

**Issue by davvd** [yegor256/takes#594]
Puzzle `558-afc1c081` in `src/main/java/org/takes/rq/RqMultipart.java:131-135` has to be resolved: Base ctor. According to new qulice version, constructor must contain only variables initialization and other constructor calls. Refactor code according to that rule and remove `ConstructorOnlyInitializesOrCallOtherConstructors` warning suppression.... The puzzle was created by Maksimenko Vladimir on 7-Feb-2016.

If you have any technical questions, don't ask me, submit new tickets instead. The task will be "done" when the problem is fixed and the text of the puzzle is removed from the source code.

**Comment by davvd** [comment]
@2686747 it's yours now, please proceed keeping in mind [our principles](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html). Feel free to ask any technical questions right here in the ticket. Task's budget is **30 mins** (see [this](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html) for explanation)

**Comment by davvd** [comment]
@yegor256 I set the milestone to 1.0 since there is nothing set yet

**Comment by 2686747** [comment]
@davvd the PR is ready to be reviewed thx in advance

**Comment by davvd** [comment]
> @davvd the [PR](https://github.com/yegor256/takes/pull/603) is ready to be reviewed thx in advance

@2686747 OK thanks

**Comment by 2686747** [comment]
@davvd Can we close this?

**Comment by davvd** [comment]
@2686747 the task is your hands for the last 15 days.. keep in mind that if it's not closed in the next 48 hours, it will be re-assigned to someone else, see [No Obligations](http://www.xdsd.org/2014/04/13/no-obligations-principle.html) principle. [This article](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html) should help if you're stuck; do not forget that the ticket will be closed once the `@todo` puzzle is removed from the code, in master branch; added -30 to your rating, now it is equal to [-30](http://www.netbout.com/b/36452?open=rating)

**Comment by 2686747** [comment]
@davvd  9 days ago i fixed all issues and there (#603) was a merge/confirm request. 7 days ago i asked you for closing. I missed something?

**Comment by 2686747** [comment]
@davvd #603 is done, need some time for [confirmation](https://github.com/yegor256/takes/pull/603#issuecomment-189946932).

**Comment by davvd** [comment]
> @davvd #603 is done, need some time for [confirmation](https://github.com/yegor256/takes/pull/603#issuecomment-189946932).

@2686747 thanks

**Comment by davvd** [comment]
@2686747 you've been working with this task for too long. I'm sorry, but I'll assign someone else. Please stop working with it. See our [no obligations](http://www.xdsd.org/2014/04/13/no-obligations-principle.html) principle. -60 added to your rating, current score is: [-37](http://www.netbout.com/b/36452?open=rating)

**Comment by davvd** [comment]
@dalifreire the task is for you now, follow [these guidelines](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html). Don't hesitate to ask any technical questions right here

The cost of this task is **30 mins** (this is exactly how much will be paid, not less not more), when the task is [done](http://www.xdsd.org/2014/04/15/definition-of-done.html)

**Comment by dalifreire** [comment]
@davvd Thanks. Please, see PR #641.

**Comment by davvd** [comment]
> @davvd Thanks. Please, see PR #641.

@dalifreire I will take a look, thanks

**Comment by dalifreire** [comment]
@davvd PR #641 merged, could you close this issue?

**Comment by dalifreire** [comment]
@davvd Ping... :)

**Comment by davvd** [comment]
@yegor256 Closed, done, thanks all

**Comment by davvd** [comment]
@ypshenychka please, check this issue for QA compliance, as per [par.24](http://at.teamed.io/policy.html#24)

**Comment by ypshenychka** [comment]
@davvd Quality is good here.

**Comment by davvd** [comment]
> @davvd Quality is good here.

@ypshenychka thanks for the review and a good remark

**Comment by davvd** [comment]
@dalifreire added 10 mins to @ypshenychka, for QA review, payment code is `79944182`

**30 mins** sent to your balance (ID `79944185`), many thanks! It took 137 hours and 14 mins.

+30 to your rating, your total score is [+165](http://www.netbout.com/b/36485?open=rating)
