### ISSUE TITLE
CcAES.java:91-95: CcAES ctor. According to new...

### ISSUE THREAD

**Issue by davvd** [yegor256/takes#595]
Puzzle `558-7db66253` in `src/main/java/org/takes/facets/auth/codecs/CcAES.java:91-95` has to be resolved: CcAES ctor. According to new qulice version, constructor must contain only variables initialization and other constructor calls. Refactor code according to that rule and remove `ConstructorOnlyInitializesOrCallOtherConstructors` warning suppression.... The puzzle was created by Maksimenko Vladimir on 7-Feb-2016.

If you have any technical questions, don't ask me, submit new tickets instead. The task will be "done" when the problem is fixed and the text of the puzzle is removed from the source code.

**Comment by davvd** [comment]
@sebing it's yours now, please proceed keeping in mind [our principles](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html). Feel free to ask any technical questions right here in the ticket. Total fixed cost of this task is **30 mins** (see [this](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html) for more info)

**Comment by davvd** [comment]
@yegor256 milestone set to `1.0` (correct me if I am wrong)

**Comment by sebing** [comment]
@davvd can you close this issue?

**Comment by davvd** [comment]
@yegor256 Thanks, closed

**Comment by davvd** [comment]
@ypshenychka review this ticket please, for compliance with our [quality rules](http://at.teamed.io/qa.html)

**Comment by ypshenychka** [comment]
@sebing 
According to our [QA Rules](http://at.teamed.io/qa.html):
>Some of ticket messages must mention all pull requests where the problem was actually fixed.

Please provide a link to PR is any of your messages.

**Comment by sebing** [comment]
@ypshenychka Thanks for the comment. 
The issue is fixed in the PR(https://github.com/yegor256/takes/pull/599)

**Comment by ypshenychka** [comment]
@sebing Thanks.

**Comment by ypshenychka** [comment]
@davvd Quality is acceptable.

**Comment by davvd** [comment]
> @davvd Quality is acceptable.

@ypshenychka thanks, got it. everybody, please try to make it good next time

**Comment by davvd** [comment]
@sebing just added 10 mins to @ypshenychka (for QA), payment ID is `79068184`

**30 mins** was added to your account, many thanks for your contribution (payment 56d5823b4b766c6fe4000111)! The task took 378 hours and 49 mins.

+30 added to your rating, at the moment it is: [+165](http://www.netbout.com/b/36309?open=rating)
