### ISSUE TITLE
String.replaceAll should never be called

### ISSUE THREAD

**Issue by essobedo** [yegor256/takes#596]
There are several places in the source code where the method _String.replaceAll_ (at least in _MediaType_ and _Href_) is called. It should be avoided mostly for performance reasons because it internally compiles the regular expression at each call. In that case we are supposed to use a field _private static final_ of type Pattern which is possible because a Pattern is Immutable/thread safe and use this field to call _matcher(input).replaceAll(replacement)_ instead of calling _input.replaceAll(replacement)_.

So for example in my laptop calling 1 M times _replaceAll("/$", "")_ takes about **30 seconds** and doing the same thing with a pre-created Pattern object takes **less than 20 seconds** which represents a performance **improvement of more than 30 %**.

**Comment by davvd** [comment]
@yegor256 dispatch this issue please, see [par.21](http://at.teamed.io/policy.html#21)

**Comment by davvd** [comment]
@essobedo I added milestone `1.0` to this issue, let me know if there has to be something else

**Comment by davvd** [comment]
@essobedo many thanks for the bug report, I added 15 mins to your acc, transaction `77683052`

**Comment by davvd** [comment]
@happy-neko the task is yours,please go ahead

**Comment by Happy-Neko** [comment]
@essobedo PR #628 merged.
Please close the ticket if everything is ok.

**Comment by davvd** [comment]
@ypshenychka please, review this issue for QA compliance, as per [par.24](http://at.teamed.io/policy.html#24)

**Comment by ypshenychka** [comment]
@davvd Quality is good.

**Comment by davvd** [comment]
> @davvd Quality is good.

@ypshenychka thank you ;)

**Comment by davvd** [comment]
@happy-neko 10 mins was added to the account of @ypshenychka (for QA review), in transaction 79306932; Thanks so much! Your account was topped up for **30 mins** (transaction ID is `AP-25H43972YB797941W`, the task took 121 hours and 43 mins); added +30 to your rating, now it is equal to [+248](http://www.netbout.com/b/36136?open=rating)
