### ISSUE TITLE
Use String.split if the separator is only one character long

### ISSUE THREAD

**Issue by essobedo** [yegor256/takes#597]
Using _String.split_ if the separator is only one character long (normal character or a backslash followed by a special character) is very fast as it is not treated internally as a regular expression but if the separator is a real regular expression it will internally compile the regular expression at each call which has a significant cost in term of performances.  In that case we are supposed to use a field _private static final_ of type Pattern which is possible because a Pattern is Immutable/thread safe and use this field to call _split(input)_ instead of doing _input.split(regexp)_.

So for example in my laptop calling 1 M times _split("\\s")_ takes **more than 20 seconds** and doing the same thing with a pre-created Pattern object takes **9.4 seconds** which represents a performance **improvement of more than 50 %**.

**Comment by davvd** [comment]
@yegor256 please dispatch this issue

**Comment by davvd** [comment]
@essobedo since there is no milestone yet I set it to "1.0"

**Comment by davvd** [comment]
@essobedo thanks for this report, I added 15 mins to your account, in transaction `77676303`

**Comment by davvd** [comment]
@dalifreire this ticket is yours now, please proceed, and keep in mind [this](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html). Any technical questions you should ask right here; The budget of this issue is **30 mins**, which is exactly how much will be paid when the task is *done* (see [this](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html) for explanation)

**Comment by dalifreire** [comment]
@davvd Could you better explain what must be done? My task must be find and replaces all occurrences (all the takes project) of the string.split("x") by a Pattern field type?

**Comment by essobedo** [comment]
@dalifreire You are supposed to identify all the places in the code where we use _String.split(regexp)_ with regexp that is at least 2 character long knowing that backslash followed by a special character is still considered as 1 character long. So for example _String.split(" ")_ is OK as it is one character long, _String.split("\.")_ is OK as it is a backslash followed by a special character which is dot in this case but _String.split("\s")_ is KO as it is at least two character long. Once you identified all the places, you will need to replace them with a private static final field. Is it clear now?

**Comment by dalifreire** [comment]
@essobedo Thanks, it's clear now.

**Comment by dalifreire** [comment]
@essobedo @davvd Fixed! 
I have a question.. We have a code formatter template for eclipse (we can avoid a lot of qulice checkstyle rules problems)??

**Comment by essobedo** [comment]
@dalifreire Your PR still violates some qulice checkstyle rules. [Here](http://www.yegor256.com/2014/08/13/strict-code-quality-control.html) you can find a link with the settings of Yegor for Intellij.

**Comment by dalifreire** [comment]
@essobedo Thanks! I'll verify the checkstyle rules.

**Comment by dalifreire** [comment]
@essobedo Please, could you take a look again? Thanks!

**Comment by essobedo** [comment]
@dalifreire sounds good now

**Comment by dalifreire** [comment]
@davvd Please, see PR #619

**Comment by davvd** [comment]
> @davvd Please, see PR #619 

@dalifreire I will take a look, thanks

**Comment by dalifreire** [comment]
@davvd The PR #619 was merged, can you close the issue?

**Comment by davvd** [comment]
> @davvd The PR #619 was merged, can you close the issue?

@dalifreire I'm not the author of the ticket, please close OP to close it

**Comment by essobedo** [comment]
@dalifreire I close it

**Comment by davvd** [comment]
@ypshenychka please, review this issue for QA compliance, as per [par.24](http://at.teamed.io/policy.html#24)

**Comment by ypshenychka** [comment]
@davvd Quality is good.

**Comment by davvd** [comment]
> @davvd Quality is good.

@ypshenychka thanks a lot

**Comment by davvd** [comment]
@dalifreire 10 mins was added to the account of @ypshenychka (for QA review), in transaction 79248795

Many thanks! **30 mins** were added to your account in Transaction ID `79248825` (task took 265 hours and 48 mins)

+30 to your rating, your total score is [+90](http://www.netbout.com/b/36485?open=rating)
