### ISSUE TITLE
BkTimeable.java:67-71: BkThreads ctor. According to new...

### ISSUE THREAD

**Issue by davvd** [yegor256/takes#598]
Puzzle `558-7c5810e9` in `src/main/java/org/takes/http/BkTimeable.java:67-71` has to be resolved: BkThreads ctor. According to new qulice version, constructor must contain only variables initialization and other constructor calls. Refactor code according to that rule and remove `ConstructorOnlyInitializesOrCallOtherConstructors` warning suppression.... The puzzle was created by Maksimenko Vladimir on 7-Feb-2016.

If you have any technical questions, don't ask me, submit new tickets instead. The task will be "done" when the problem is fixed and the text of the puzzle is removed from the source code.

**Comment by davvd** [comment]
@sebing this task is for you, keep [these principles](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html) in mind, and don't hesitate to ask any technical questions. Budget here is **30 mins** (keep [this principle](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html) in mind)

**Comment by davvd** [comment]
@yegor256 I set the milestone to 1.0 since there is nothing set yet

**Comment by sebing** [comment]
@davvd Can you close this issue as we merged the PR?

**Comment by davvd** [comment]
@yegor256 We are done here, thanks all

**Comment by davvd** [comment]
@ypshenychka please, help us to evaluate quality here, as per [par.24](http://at.teamed.io/policy.html#24)

**Comment by ypshenychka** [comment]
@sebing 
According to our [QA Rules](http://at.teamed.io/qa.html):
>Some of ticket messages must mention all pull requests where the problem was actually fixed.

Please provide a link to corresponding PR in any of your messages.

**Comment by sebing** [comment]
@ypshenychka I thought when i mention this issue while fixing the PR(https://github.com/yegor256/takes/pull/605) was enough :)

**Comment by ypshenychka** [comment]
@sebing Now you know that it's not enough :) Thank you!

**Comment by ypshenychka** [comment]
@davvd Quality is acceptable.

**Comment by davvd** [comment]
> @davvd Quality is acceptable.

@ypshenychka thanks, got it. everybody, please try to make it good next time

**Comment by davvd** [comment]
@sebing added 10 mins to @ypshenychka, for QA review, payment code is `79072048`; Thanks a lot, I just topped your account for **30 mins**, transaction ID `56d5984cdd127d7962000470`, total time was 377 hours and 25 mins; added +30 to your rating, now it is equal to [+195](http://www.netbout.com/b/36309?open=rating)
