### ISSUE TITLE
PsBasic.java:226-230: Default ctor. According to new...

### ISSUE THREAD

**Issue by davvd** [yegor256/takes#600]
Puzzle `558-7b985928` in `src/main/java/org/takes/facets/auth/PsBasic.java:226-230` has to be resolved: Default ctor. According to new qulice version, constructor must contain only variables initialization and other constructor calls. Refactor code according to that rule and remove `ConstructorOnlyInitializesOrCallOtherConstructors` warning suppression.... The puzzle was created by Maksimenko Vladimir on 7-Feb-2016.

If you have any technical questions, don't ask me, submit new tickets instead. The task will be "done" when the problem is fixed and the text of the puzzle is removed from the source code.

**Comment by davvd** [comment]
@sebing can you please help? Keep in mind [this](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html). If you have any technical questions, don't hesitate to ask right here. The budget here is **30 mins**, which is exactly how much time will be paid for, when the task is [completed](http://www.xdsd.org/2014/04/15/definition-of-done.html)

**Comment by davvd** [comment]
@yegor256 there is no milestone yet, so I set it to `1.0`

**Comment by davvd** [comment]
@sebing the ticket is with you for 15 days already. If it is not finished in the next 48 hours, it will be re-assigned to someone else, see [No Obligations](http://www.xdsd.org/2014/04/13/no-obligations-principle.html) principle, [this article](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html) should help if you're stuck. do not forget to remove the TODO puzzle from the source code. added -30 to your rating, now it is equal to [+45](http://www.netbout.com/b/36309?open=rating)

**Comment by sebing** [comment]
@davvd Sorry for not attending this issue.
waiting for (https://github.com/yegor256/takes/issues/458), (https://github.com/yegor256/takes/issues/574), (https://github.com/yegor256/takes/issues/560), (https://github.com/yegor256/takes/issues/595), and (https://github.com/yegor256/takes/issues/598)

**Comment by sebing** [comment]
@davvd all the tasks except this one is closed. Should I start on this task or you will be assigning this task to someone else?

**Comment by davvd** [comment]
> @davvd all the tasks except this one is closed. Should I start on this task or you will be assigning this task to someone else? 

@sebing this is still yours and you still have time to fix it

**Comment by sebing** [comment]
@davvd I created a PR(https://github.com/yegor256/takes/pull/632)

**Comment by davvd** [comment]
@sebing it's not yours any more, because it took too long, please stop working with it; added -60 to your rating, now it is equal to [+135](http://www.netbout.com/b/36309?open=rating)

**Comment by sebing** [comment]
@mkordas you may not have to review the change in the PR(https://github.com/yegor256/takes/pull/632) any more :(

**Comment by mkordas** [comment]
@sebing please ask for assignment again

**Comment by sebing** [comment]
@davvd please assign the task again. The work is almost done.

**Comment by davvd** [comment]
> @davvd I created a PR(https://github.com/yegor256/takes/pull/632)

@sebing thanks

**Comment by sebing** [comment]
@davvd That means @mkordas can request the merge in the PR?

**Comment by davvd** [comment]
@xupyprmv the task is yours, please go ahead

**Comment by xupyprmv** [comment]
@davvd PR #640 was merged. Please, close this ticket.

**Comment by xupyprmv** [comment]
@davvd Please, close this issue.

**Comment by davvd** [comment]
> @davvd PR #640 was merged. Please, close this ticket.

@xupyprmv OK

**Comment by davvd** [comment]
> @davvd Please, close this issue.

@xupyprmv OK

**Comment by davvd** [comment]
@yegor256 Closed, done, thanks all

**Comment by davvd** [comment]
@ypshenychka please, review this task for compliance with our [quality rules](http://at.teamed.io/qa.html)

**Comment by ypshenychka** [comment]
@xupyprmv 
According to our [QA Rules](http://at.teamed.io/qa.html):
>The ticket describes one specific problem and provides a single solution.

PR created by previous performer is also merged and deployed. I suppose you should make sure that changes are reverted. 
@yegor256 Please correct me if I'm missing anything.

**Comment by xupyprmv** [comment]
@ypshenychka 

> PR created by previous performer is also merged and deployed. I suppose you should make sure that changes are reverted. 

It is not true. PR #632 was not merged and  was not deployed. So, there is only one solution here (PR #640).

**Comment by ypshenychka** [comment]
@xupyprmv You're right. Sorry for confusion.

**Comment by ypshenychka** [comment]
@davvd Quality is good.

**Comment by davvd** [comment]
> @davvd Quality is good.

@ypshenychka thanks a lot :)

**Comment by davvd** [comment]
@xupyprmv paied 10 mins to @ypshenychka for QA review (payment ID is `81143121`)... thank you, added **30 mins** to your acc, payment num is `AP-3XY4585989241325W`, 192 hours and 55 mins spent in total to complete... +30 added to your rating, current score is: [+270](http://www.netbout.com/b/35999?open=rating)
