### ISSUE TITLE
RqForm.java:290-294: Fake ctor. According to new...

### ISSUE THREAD

**Issue by davvd** [yegor256/takes#602]
Puzzle `558-79259f7e` in `src/main/java/org/takes/rq/RqForm.java:290-294` has to be resolved: Fake ctor. According to new qulice version, constructor must contain only variables initialization and other constructor calls. Refactor code according to that rule and remove `ConstructorOnlyInitializesOrCallOtherConstructors` warning suppression.... The puzzle was created by Maksimenko Vladimir on 7-Feb-2016.

If you have any technical questions, don't ask me, submit new tickets instead. The task will be "done" when the problem is fixed and the text of the puzzle is removed from the source code.

**Comment by davvd** [comment]
@xupyprmv the task is yours please proceed

**Comment by davvd** [comment]
@yegor256 I set the milestone to 1.0 since there is nothing set yet

**Comment by xupyprmv** [comment]
@davvd need more time here

**Comment by xupyprmv** [comment]
@davvd PR #612 was merged. Please, close this ticket.

**Comment by davvd** [comment]
@yegor256 Closed, thanks all

**Comment by davvd** [comment]
@ypshenychka please, check this issue for QA compliance, as per [par.24](http://at.teamed.io/policy.html#24)

**Comment by ypshenychka** [comment]
@davvd Quality is good.

**Comment by davvd** [comment]
> @davvd Quality is good.

@ypshenychka thanks for the review and a good remark

**Comment by davvd** [comment]
@xupyprmv I added 10 mins to @ypshenychka (for QA review) in transaction 79079164; I just added **30 mins** to your account, many thanks for your contribution (AP-6U271405GT1371402).. 372 hours and 36 mins spent here; +30 added to your rating, at the moment it is: [+210](http://www.netbout.com/b/35999?open=rating)
