### ISSUE TITLE
PsAll.java:56-60: PsAll ctor. According to new...

### ISSUE THREAD

**Issue by davvd** [yegor256/takes#604]
Puzzle `558-4ea33ea6` in `src/main/java/org/takes/facets/auth/PsAll.java:56-60` has to be resolved: PsAll ctor. According to new qulice version, constructor must contain only variables initialization and other constructor calls. Refactor code according to that rule and remove `ConstructorOnlyInitializesOrCallOtherConstructors` warning suppression.... The puzzle was created by Maksimenko Vladimir on 7-Feb-2016.

If you have any technical questions, don't ask me, submit new tickets instead. The task will be "done" when the problem is fixed and the text of the puzzle is removed from the source code.

**Comment by davvd** [comment]
@xupyprmv the task is yours please proceed

**Comment by davvd** [comment]
@yegor256 milestone set to `1.0` (correct me if I am wrong)

**Comment by xupyprmv** [comment]
@davvd need more time here

**Comment by xupyprmv** [comment]
@davvd PR #611 was merged. Please, close this ticket.

**Comment by davvd** [comment]
@yegor256 We are done here, thanks all

**Comment by davvd** [comment]
@ypshenychka please, check this issue for QA compliance, as per [par.24](http://at.teamed.io/policy.html#24)

**Comment by ypshenychka** [comment]
@davvd Quality is good.

**Comment by davvd** [comment]
> @davvd Quality is good.

@ypshenychka thanks for the review

**Comment by davvd** [comment]
@xupyprmv 10 mins was added to the account of @ypshenychka (for QA review), in transaction 79081847... Much obliged! I have added **30 mins** to your account in payment "AP-2H8894255W072515F", 359 hours and 31 mins spent... added +30 to your rating, now it is equal to [+240](http://www.netbout.com/b/35999?open=rating)
