### ISSUE TITLE
MediaType.java:62-66: MediaType ctor. According to new...

### ISSUE THREAD

**Issue by davvd** [yegor256/takes#606]
Puzzle `558-12fc4eff` in `src/main/java/org/takes/facets/fork/MediaType.java:62-66` has to be resolved: MediaType ctor. According to new qulice version, constructor must contain only variables initialization and other constructor calls. Refactor code according to that rule and remove `ConstructorOnlyInitializesOrCallOtherConstructors` warning suppression.... The puzzle was created by Maksimenko Vladimir on 7-Feb-2016.

If you have any technical questions, don't ask me, submit new tickets instead. The task will be "done" when the problem is fixed and the text of the puzzle is removed from the source code.

**Comment by davvd** [comment]
@dalifreire could you please pick this up? This [article](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html) explains how we work. Any technical questions you may ask right here; The budget of this task is **30 mins**. This is exactly how much time will be compensated, when the task is completed. Read about our [Definition of Done](http://www.xdsd.org/2014/04/15/definition-of-done.html)

**Comment by davvd** [comment]
@yegor256 I added milestone `1.0` to this issue, let me know if there has to be something else

**Comment by dalifreire** [comment]
@davvd I have sent the away command to @alice. Could you assign this task to someone else?

**Comment by davvd** [comment]
> @davvd I sent the away command to @alice before you assign this task for me. Could you assign this task to someone else?

@dalifreire I deducted 30 points from your rating

**Comment by davvd** [comment]
> @davvd I sent the away command to @alice before you assign this task for me. Could you assign this task to someone else?

@dalifreire I will try to find someone else

**Comment by dalifreire** [comment]
@davvd Why?

**Comment by dalifreire** [comment]
@davvd I think there was a misunderstanding here... as you delayed to answer me, I have finished the task!

**Comment by yegor256** [comment]
@davvd pls assign @dalifreire back to this ticket

**Comment by davvd** [comment]
> @davvd Why?

@dalifreire @yegor256 will help

**Comment by davvd** [comment]
> @davvd I think there was a misunderstanding here... as you delayed to answer me, I have finished the task!

@dalifreire @yegor256 please help us here

**Comment by davvd** [comment]
> @davvd pls assign @dalifreire back to this ticket

@yegor256 OK @dalifreire please proceed, this task is yours

**Comment by dalifreire** [comment]
@davvd Thanks. PR #616 is merged, can you close the issue and revert my 30 points deducted from my rating?

**Comment by davvd** [comment]
@yegor256 The task is done, thanks all, I am closing it

**Comment by davvd** [comment]
@ypshenychka please, review this task for compliance with our [quality rules](http://at.teamed.io/qa.html)

**Comment by ypshenychka** [comment]
@davvd Quality is good.

**Comment by davvd** [comment]
> @davvd Quality is good.

@ypshenychka thanks for the review

**Comment by davvd** [comment]
@dalifreire I added 10 mins to @ypshenychka (for QA review) in transaction 79092003; **1 hour** sent to your balance (ID `79092023`), many thanks! It took zero.; there is a bonus for fast delivery (m=0); +60 added to your rating, current score is: [+60](http://www.netbout.com/b/36485?open=rating)
