### ISSUE TITLE
null value should not be placed in Opt.Single container

### ISSUE THREAD

**Issue by Happy-Neko** [yegor256/takes#609]
`TkMethodsTest` and `TkRetryTest` detected problems with passing `null` value to `Opt.Single` constructor. We should fix these problems and re-enable ignored tests.

**Comment by davvd** [comment]
@yegor256 please do something about it, see [par.21](http://at.teamed.io/policy.html#21)

**Comment by yegor256** [comment]
@Happy-Neko are there puzzles for that problems already in the code?

**Comment by Happy-Neko** [comment]
@yegor256 in PR #610.

**Comment by yegor256** [comment]
@Happy-Neko what exactly is wrong now? this ticket sounds like a task, not a bug. read this: http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html#5-report-when-it-is-broken

**Comment by Happy-Neko** [comment]
> @yegor256 what exactly is wrong now?

There are NPEs in ignored tests (PR #610).

**Comment by yegor256** [comment]
@Happy-Neko but the tests are ignored. so the build is clean. there are no bugs in the code. you're trying to un-ignore and you can't do it. it's your problem, in your own pull request. we can't blame "master" branch for that.
