### ISSUE TITLE
Can't run the Quick start example

### ISSUE THREAD

**Issue by jefferson-pessanha** [yegor256/takes#614]
Hello,

I'm trying to run the Takes App in the quick start section but i can't find the org.takes.facets.fork.TkFork class. In which jar version can I find it?

**Comment by yegor256** [comment]
@jefferson-pessanha 0.31.1 is the latest, it's there: http://www.javadoc.io/doc/org.takes/takes/0.31.1

**Comment by jefferson-pessanha** [comment]
oh, it's right! Thanks.
