### ISSUE TITLE
Code Format incorrect at pom.xml

### ISSUE THREAD

**Issue by datntvn** [yegor256/takes#617]
![codeformat](https://cloud.githubusercontent.com/assets/17193271/13101681/d8fda806-d58b-11e5-83e4-77a20c42f218.png)

https://github.com/yegor256/takes/blob/master/pom.xml#L239

This mistake was introduced at this commit:

https://github.com/yegor256/takes/blob/dcc7faacfa231a8f314b40c38759d804fbfb6708/pom.xml#L238

**Comment by davvd** [comment]
@yegor256 please do something about this issue

**Comment by yegor256** [comment]
@datntvn I don't see this issue any more in `pom.xml`...
