### ISSUE TITLE
RqForm.Smart#single() doesn't return a form parameter

### ISSUE THREAD

**Issue by dmzaytsev** [yegor256/takes#620]
the code below throws org.takes.HttpException: [400] form param "name" is mandatory
```
MatcherAssert.assertThat(
            new RqForm.Smart(
                new RqForm.Base(new RqFake(
                    "POST",
                    "/b",
                    "name=foo"
                ))
            ).single("name"), Matchers.is("foo"));
```

the test works fine on Takes  0.31.1, but fails on 0.31.2

**Comment by yegor256** [comment]
@rultor release, tag is `0.31.3`

**Comment by yegor256** [comment]
@rultor release, tag is `0.31.3`

**Comment by yegor256** [comment]
@dmzaytsev should be fine now, please check

**Comment by dmzaytsev** [comment]
@yegor256 thanks

**Comment by davvd** [comment]
@dmzaytsev once `620-91883c6a` puzzle is resolved (later, in another ticket), this ticket will be fully complete

**Comment by davvd** [comment]
@dmzaytsev the last puzzle `620-91883c6a`/#625 originated from here solved
