### ISSUE TITLE
Can't know FtCLI random assigned port

### ISSUE THREAD

**Issue by pinaf** [yegor256/takes#622]
When running `FtCLI` with `--port=0`, the socket is opened on a random port, as expected, but there is no way to know which port was actually allocated.

Let's add a method `int port()` that informs this.

**Comment by davvd** [comment]
@yegor256 dispatch this issue please, see [par.21](http://at.teamed.io/policy.html#21)

**Comment by yegor256** [comment]
@pinaf this is by design. if you want to know the port number, you should do something like this:

```
--port=/tmp/port.txt
```

This file will be created and will contain the port number.

**Comment by yegor256** [comment]
@pinaf I should probably add this to class documentation...

**Comment by yegor256** [comment]
@pinaf documented in 57b1fb9

**Comment by pinaf** [comment]
@yegor256 thank you.
