### ISSUE TITLE
PsGoogle throws NPE

### ISSUE THREAD

**Issue by dmzaytsev** [yegor256/takes#623]
PsGoogle throws Null pointer  exception 

>Caused by: java.lang.NullPointerException
    at org.glassfish.json.JsonObjectBuilderImpl$JsonObjectImpl.getString(JsonObjectBuilderImpl.java:199)
    at org.takes.facets.auth.social.PsGoogle.parse(PsGoogle.java:199)
    at org.takes.facets.auth.social.PsGoogle.fetch(PsGoogle.java:151)
    at org.takes.facets.auth.social.PsGoogle.enter(PsGoogle.java:129)
    at org.takes.facets.auth.PsByFlag.enter(PsByFlag.java:107)
    at org.takes.facets.auth.PsChain.enter(PsChain.java:70)
    at com.netbout.rest.PsTwice.enter(PsTwice.java:70)
    at org.takes.facets.auth.TkAuth.act(TkAuth.java:86)
    at org.takes.tk.TkWrap.act(TkWrap.java:61)
    at org.takes.facets.forward.TkForward.act(TkForward.java:68)
    at org.takes.facets.fallback.TkFallback.route(TkFallback.java:85)

see full stack trace https://github.com/yegor256/netbout/issues/1038

PsGoogle.java:199
```
 props.put("name", json.getString("displayName", "unknown"));
```
I guess Google's response doesn't contain `displayName` attribute
the PsGoogle source code should be checked for compliance with Google OAuth specification

Anyway PsGoogle should not throw NPE

**Comment by dmzaytsev** [comment]
@yegor256 could you put urgent tag here?

**Comment by yegor256** [comment]
@davvd it's urgent

**Comment by davvd** [comment]
@dmzaytsev I will find a developer for the task soon...

**Comment by davvd** [comment]
@dmzaytsev there is no milestone yet, so I set it to `1.0`

**Comment by davvd** [comment]
@dmzaytsev many thanks for the bug report, I added 15 mins to your acc, transaction `78661202`

**Comment by davvd** [comment]
@raphaelln This task is yours, please go ahead keeping in mind [this](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html). If any questions, don't hesitate to ask right here; The budget here is **30 mins**, which is exactly how much time will be paid for, when the task is [completed](http://www.xdsd.org/2014/04/15/definition-of-done.html)

**Comment by davvd** [comment]
> @davvd it's urgent

@yegor256 right, I added "urgent" label

**Comment by raphaelln** [comment]
@yegor256 following an example of response from google after the authentication process:

```
{
  "email" : "raphaelln@gmail.com",
  "family_name" : "Nascimento",
  "gender" : "male",
  "given_name" : "Raphael L.",
  "id" : "100803855204669656179",
  "link" : "https://plus.google.com/100803855204669656179",
  "locale" : "pt-BR",
  "name" : "Raphael L. Nascimento",
  "picture" : "http://picture.url,
  "verified_email" : true
}
```

Google doesn't have the *displayName* property, could we use the *name* property instead ? 

In case of yes, I'll change the code to:

```
if (json.containsKey("name")) {
    props.put("name", json.getString("name", "unknown"));
} else {
   props.put("name", "unknown");
}
```
I put the if just to make sure the name property is in the response, before try to use it.

**Comment by raphaelln** [comment]
@yegor256 could you please check google+ api is active in the google developer console for the netbout account ? I don't have the credentials to check it.

@davvd maybe could you find someone to check it ?

More info at: https://support.google.com/a/answer/3187191?hl=en

Thanks

**Comment by yegor256** [comment]
@raphaelln I'm sure it is active. it was active and I didn't touch it.

**Comment by raphaelln** [comment]
@yegor256 thanks, I don't know if you can share temporally with me the googleId and googleSecret and add the redirect to localhost in the netbout account. I'm trying to simulate the error but with my account the error just occurs when the google+ api is not active.

**Comment by dmzaytsev** [comment]
@raphaelln anyway we need a proper error handling  instead of NPE

**Comment by raphaelln** [comment]
@yegor256, @dmzaytsev done in PR #633, this fix is just to stop the NPE.

@yegor256 Can I open another bug to investigate why the **displayName** property is not present in the google response ? In this way, the name of the current user in this case always will be **unknown**.

**Comment by yegor256** [comment]
@raphaelln you can always open as many bugs as you want...

**Comment by raphaelln** [comment]
@yegor256 it's done in PR #633, please could you verify and close the task if everything is ok ?

**Comment by dmzaytsev** [comment]
@raphaelln thanks

**Comment by dmzaytsev** [comment]
@yegor256 please release if possible

**Comment by yegor256** [comment]
@rultor release, tag is `0.32.6`

**Comment by davvd** [comment]
@ypshenychka please, review this task for compliance with our [quality rules](http://at.teamed.io/qa.html)

**Comment by ypshenychka** [comment]
@davvd Quality is good.

**Comment by davvd** [comment]
> @davvd Quality is good.

@ypshenychka thank you, good quality is always good :)

**Comment by raphaelln** [comment]
@davvd everything is ok here could you please proceed. Thanks.

**Comment by davvd** [comment]
> @davvd everything is ok here could you please proceed. Thanks.

@raphaelln np :)

**Comment by davvd** [comment]
@raphaelln added 10 mins to @ypshenychka, for QA review, payment code is `81192323`. Thank you, I have added **30 mins** to your account in payment/transaction "`AP-7U202156LR004453N`", time consumed: 296 hours and 30 mins. +30 added to your rating, current score is: [+60](http://www.netbout.com/b/36530?open=rating)
