### ISSUE TITLE
RqMultipartTest.java:91-98: This test is using RqGreedy...

### ISSUE THREAD

**Issue by davvd** [yegor256/takes#625]
Puzzle `620-91883c6a` in `src/test/java/org/takes/rq/RqMultipartTest.java:91-98` has to be resolved: This test is using RqGreedy in order to survive. If you remove RqGreedy, the test will crash. I can't find out why exactly it's happening. But the main problem is that somehow inside RqMultipart.Fake we're reading body() of dispositions twice or more times. That's why RqGreedy is required now. I order to always return the same content. Let's find what exactly is the problem and remove RqGreedy from this test and three other test methods below.... The puzzle was created by Yegor Bugayenko on 22-Feb-2016.

If you have any technical questions, don't ask me, submit new tickets instead. The task will be "done" when the problem is fixed and the text of the puzzle is removed from the source code.

**Comment by davvd** [comment]
@yegor256 there is no milestone yet, so I set it to `1.0`

**Comment by davvd** [comment]
@2686747 the task is for you now, follow [these guidelines](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html). Don't hesitate to ask any technical questions right here

**30 mins** is the budget of the task. This is exactly how much will be paid when the problem is [solved](http://www.xdsd.org/2014/04/15/definition-of-done.html) (no matter how much time you will actually spend). See [this](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html) for more information

**Comment by 2686747** [comment]
@davvd waiting for #646

**Comment by davvd** [comment]
> @davvd waiting for #646

@2686747 yes, of course, we'll wait for #646

**Comment by 2686747** [comment]
@davvd please, check PR #653

**Comment by davvd** [comment]
> @davvd please, check PR #653 

@2686747 thanks

**Comment by davvd** [comment]
@yegor256 impediment in issue #646 is closed, we can probably try to continue here

**Comment by davvd** [comment]
@2686747 you're working with this issue for 15 days already; do not forget that you should remove the `@todo` puzzle from the source code; -30 added to your rating, current score is: [+61](http://www.netbout.com/b/36452?open=rating)

**Comment by 2686747** [comment]
@davvd ))) Do you mean [this](https://github.com/yegor256/takes/pull/653/commits/51b3b71cba8e36eee58ca0e10a3312675bc41192#diff-fe16955f17e637d59542c8cff5c6edc7L92)? I finished here 19 days ago, you have to ask somebody other.

**Comment by davvd** [comment]
@2686747 it's not yours any more,because it took too long,please stop working with it; -60 added to your rating, at the moment it is: [+1](http://www.netbout.com/b/36452?open=rating)

**Comment by davvd** [comment]
@dalifreire the task is yours please proceed

**Comment by dalifreire** [comment]
@davvd I think we have a misunderstand here. I think that this task was done once the PR #653 was created by @2686747. Maybe the same problem occurred with me in the task #624.

**Comment by dalifreire** [comment]
@yegor256 Maybe we need your help here too.

**Comment by dalifreire** [comment]
@davvd PR #663 created.

**Comment by davvd** [comment]
> @davvd PR #663 created.

@dalifreire thank you

**Comment by dalifreire** [comment]
@davvd PR #663 was merged, please proceed.

**Comment by davvd** [comment]
> @davvd PR #663 was merged, please proceed.

@dalifreire thanks for that

**Comment by dalifreire** [comment]
@davvd please close the ticket.

**Comment by davvd** [comment]
@yegor256 Done, thanks all, closing..

**Comment by davvd** [comment]
@ypshenychka please, let us know what do you think about this ticket, according to our [QA rules](http://at.teamed.io/qa.html)

**Comment by ypshenychka** [comment]
@davvd Quality is good.

**Comment by davvd** [comment]
> @davvd Quality is good.

@ypshenychka thanks, got it, great to see high-quality tickets here

**Comment by davvd** [comment]
@dalifreire paied 10 mins to @ypshenychka for QA review (payment ID is `84292132`); I just added **30 mins** to your account, many thanks for your contribution (84292156).. 185 hours and 59 mins spent here; +30 added to your rating, at the moment it is: [+45](http://www.netbout.com/b/36485?open=rating)
