### ISSUE TITLE
year check in LICENSE.txt

### ISSUE THREAD

**Issue by yegor256** [yegor256/takes#627]
Let's create a check in `pom.xml` (somehow), that will fail the build if `LICENSE.txt` doesn't have `2014-2016` text.

**Comment by davvd** [comment]
@yegor256 I tagged this as "bug"

**Comment by davvd** [comment]
@yegor256 attached this issue to milestone "1.0" (let me know if this is wrong)

**Comment by davvd** [comment]
@yegor256 thanks for tis bug, I topped your account for 15 mins, transaction `000-333acd31`

**Comment by davvd** [comment]
@raphaelln can you please help? Keep in mind [this](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html). If you have any technical questions, don't hesitate to ask right here... The cost of this task is **30 mins** (this is exactly how much will be paid, not less not more), when the task is [done](http://www.xdsd.org/2014/04/15/definition-of-done.html)

**Comment by raphaelln** [comment]
@davvd the issue was closed, could you proceed please.
thanks.

**Comment by davvd** [comment]
@rultor rultor closed it (automatically), @yegor256 please take a look

**Comment by davvd** [comment]
> @davvd the issue was closed, could you proceed please.
> thanks.

@raphaelln no problem :)

**Comment by yegor256** [comment]
@raphaelln please post a link to the pull request, where it was fixed

**Comment by yegor256** [comment]
@raphaelln thanks

**Comment by davvd** [comment]
@ypshenychka please, check this issue for QA compliance, as per [par.24](http://at.teamed.io/policy.html#24)

**Comment by ypshenychka** [comment]
@davvd Quality is good.

**Comment by davvd** [comment]
> @davvd Quality is good.

@ypshenychka thanks a lot :)

**Comment by raphaelln** [comment]
@davvd everything is ok here could you please proceed.

**Comment by davvd** [comment]
> @davvd everything is ok here could you please proceed.

@raphaelln OK

**Comment by davvd** [comment]
@raphaelln I added 10 mins to @ypshenychka (for QA review) in transaction 81197360; thanks, I just added **30 mins** to your account, payment `AP-22D74699JV219591B`, 254 hours and 34 mins spent; +30 to your rating, your total score is [+90](http://www.netbout.com/b/36530?open=rating)
