### ISSUE TITLE
Over complicated code with RsFork instead of TkFork

### ISSUE THREAD

**Issue by CarlosGines** [yegor256/takes#635]
`TkProduces` and `TkConsumes` make an over complicated use of `RsFork` that could be simplified using `TkFork`.

For example, `TkProduces` constructor could be simplified from:

```
    public TkProduces(final Take take, final String types) {
        super(
            new Take() {
                @Override
                public Response act(final Request req) throws IOException {
                    return new RsFork(
                        req,
                        new FkTypes(types, take.act(req))
                    );
                }
            }
        );
    }
```
to:
```
    public TkProduces(final Take take, final String types) {
        super(new TkFork(new FkTypes(types, take)));
    }
```
Then `FkTypes`and `FkContentType`should be refactored to use `Take` instead of `Response` in their constructor and use it to produce the `Response` that was originally provided in the constructor.

**Comment by davvd** [comment]
@yegor256 dispatch this issue please, see [par.21](http://at.teamed.io/policy.html#21)

**Comment by davvd** [comment]
@carlosgines I added milestone `1.0` to this issue, let me know if there has to be something else

**Comment by davvd** [comment]
@carlosgines thanks a lot for reporting, **15 mins** added to your acc, pmt ID `AP-2MA92366LT812032S`

**Comment by davvd** [comment]
@happy-neko the task is yours please proceed

**Comment by davvd** [comment]
@happy-neko this task is in your hands for 16 days already... -30 added to your rating, current score is: [+188](http://www.netbout.com/b/36136?open=rating)

**Comment by davvd** [comment]
@happy-neko this task is not yours any more (took too long), please stop. I'll give you something else. -60 added to your rating, current score is: [+30](http://www.netbout.com/b/36136?open=rating)

**Comment by davvd** [comment]
@essobedo the task is yours please proceed

**Comment by essobedo** [comment]
@davvd here is my PR #658 please find a reviewer.

**Comment by davvd** [comment]
> @davvd here is my PR #658 please find a reviewer.

@essobedo OK

**Comment by essobedo** [comment]
@CarlosGines the PR has been merged please close the ticket

**Comment by CarlosGines** [comment]
@essobedo Thank you!

**Comment by essobedo** [comment]
@davvd the ticket is closed, please proceed

**Comment by essobedo** [comment]
@davvd please

**Comment by essobedo** [comment]
@davvd I guess that there is a good reason that prevents you to go any further so could you please tell me what it is? Just to allow me to be aware of the entire workflow. Thank you in advance.

**Comment by essobedo** [comment]
@davvd ping

**Comment by davvd** [comment]
@ypshenychka please, let us know what do you think about this ticket, according to our [QA rules](http://at.teamed.io/qa.html)

**Comment by ypshenychka** [comment]
@davvd Quality is good.

**Comment by davvd** [comment]
> @davvd Quality is good.

@ypshenychka thanks for the review

**Comment by davvd** [comment]
@essobedo 10 mins was added to the account of @ypshenychka (for QA review), in transaction 82132883... thanks, I just added **30 mins** to your account, payment `82132897`, 93 hours and 49 mins spent... +30 added to your rating, at the moment it is: [+405](http://www.netbout.com/b/36421?open=rating)

**Comment by essobedo** [comment]
@davvd thx

**Comment by davvd** [comment]
> @davvd thx

@essobedo np
