### ISSUE TITLE
public String constants in RqMethod already exist

### ISSUE THREAD

**Issue by simonjenga** [yegor256/takes#645]
One of the dependencies to the ```takes``` project is ```jcabi-http``` as declared in the POM Build file:

```
<dependency>
    <groupId>com.jcabi</groupId>
    <artifactId>jcabi-http</artifactId>
    <version>1.14.2</version>
    <optional>true</optional>
</dependency>
```

The public String constants declared in the interface: ```org.takes.rq.RqMethod``` have already been declared and exist in the interface: ```com.jcabi.http.Request```

It is better to re-use those declared in the dependency so as to avoid code duplication.

**Comment by davvd** [comment]
@yegor256 please do something about this issue

**Comment by yegor256** [comment]
@simonjenga the dependency is `optional`, which means that not every use will have it in scope
