### ISSUE TITLE
RqWithHeaders is not immutable

### ISSUE THREAD

**Issue by 2686747** [yegor256/takes#646]
RqWithHeaders changes after new RqPrint(rqWithHeaders).print(); This [test](https://github.com/2686747/takes/commit/5a66bb78a6dc0ee867d20ecd7a8dce8881f048b8) will not pass.

**Comment by davvd** [comment]
@yegor256 please do something about this issue

**Comment by yegor256** [comment]
@2686747 it's not a bug. it's by design. this is how it should work. I created a test to confirm that: fb89dde

**Comment by 2686747** [comment]
@yegor256  ok, but what about "immutable"?

**Comment by yegor256** [comment]
@2686747 immutability doesn't mean that return values are always the same. immutable doesn't mean constant. see http://www.yegor256.com/2014/12/22/immutable-objects-not-dumb.html

**Comment by 2686747** [comment]
@yegor256 good point, but now you have to leave this link everywhere in project's javadocs, because we have [Java](http://docs.oracle.com/javase/tutorial/essential/concurrency/immutable.html) and  [wiki](https://en.wikipedia.org/wiki/Immutable_object). And all is clear here: state doesn't change. And sorry, but when i call print(smth) - i don't expect than print will change this something and i talk not just about immutable now. We're using decorators in each line practically  - do i have to check all of them for print(smth)? And i didn't start with a thread-safety yet.

**Comment by yegor256** [comment]
@2686747 but `print()` doesn't change anything. it's just an input stream, which works in a non-immutable way. not our object. we just return an input stream. how it behaves - not our area of responsibility. see?

**Comment by 2686747** [comment]
@yegor256 I understand completely but why i have to worry about implementation of some object? I don't see InputStream, i see Request which is marked as immutable and thread-safe. And of course i expect it won't change after some external method execution, especially such harmless as <code>print()</code> . And if it's impossible we have to remove all "immutable and thread-safe" and leave very clear attention in javadocs

**Comment by yegor256** [comment]
@2686747 you just misunderstand what "immutable and thread-safe" means. you think they mean "constant", while it's not true. the problem is in your understanding, not in our texts :)

**Comment by 2686747** [comment]
@yegor256 please, reread this [smart man ](http://www.yegor256.com/2014/06/09/objects-should-be-immutable.html#avoiding-side-effects))))

**Comment by yegor256** [comment]
@2686747 yeah, I read that dude, a few times :) check this out: http://www.yegor256.com/2014/12/09/immutable-object-state-and-behavior.html

**Comment by 2686747** [comment]
@yegor256 how is your own [example](http://www.yegor256.com/2014/06/09/objects-should-be-immutable.html#avoiding-side-effects) with side effect  different from RqPrint(request).print() (except syntax of course)?

**Comment by yegor256** [comment]
@2686747 we're dealing with a mutable InputStream here, that's why we inevitably have that side effect. we can't get rid of it, without breaking the entire idea of mutable input streams in Java. blame Java, not us :)
