### ISSUE TITLE
BkTimetable cannot be created directly

### ISSUE THREAD

**Issue by exper0** [yegor256/takes#652]
For some reason `BkTimetable`  is public but has package-local constructor. This lead to the situation when `BkTimetable` cannot be created from any package other than `org.takes.http`. Again, this leads to inability to create `FtBasic` the same way as it's done in `FtCLI`.
Creating `FtBasic` is needed to avoid using `FtCLI` because it would be right to decouple command line parsing and `FtBasic` creation. In application which use Takes may be much more command line arguments so using `FtCLI` leads to having two different pieces of code parsing command line.

So let's make `BkTimetable` constructor public to have more flexibility during construction of actual Takes based HTTP server.

**Comment by davvd** [comment]
@yegor256 please pay attention to this issue ([par.21](http://at.teamed.io/policy.html#21))

**Comment by yegor256** [comment]
@exper0 fixed in 9bf9e7f thanks!

**Comment by yegor256** [comment]
@rultor release, tag is `0.32.7`
