### ISSUE TITLE
RqLive.java:47-49: Refactor the parse method into...

### ISSUE THREAD

**Issue by davvd** [yegor256/takes#655]
Puzzle `519-af7d4687` in `src/main/java/org/takes/rq/RqLive.java:47-49` has to be resolved: Refactor the parse method into a new class. This method is too long and too much if-else statements. Covert this into an IfElseClass.... The puzzle was created by Sebin George on 13-Mar-2016.

If you have any technical questions, don't ask me, submit new tickets instead. The task will be "done" when the problem is fixed and the text of the puzzle is removed from the source code.

**Comment by davvd** [comment]
@dalifreire it's yours, please go ahead

**Comment by davvd** [comment]
@yegor256 since there is no milestone yet I set it to "1.0"

**Comment by dalifreire** [comment]
@davvd please, assign someone else.

**Comment by davvd** [comment]
> @davvd please, assign someone else.

@dalifreire deducted 30 from your rating :(

**Comment by davvd** [comment]
> @davvd please, assign someone else.

@dalifreire right, I will find someone else, no problem

**Comment by davvd** [comment]
@essobedo please proceed, it's yours

**Comment by essobedo** [comment]
@davvd here is my PR #657 please find a reviewer.

**Comment by davvd** [comment]
> @davvd here is my PR #657 please find a reviewer.

@essobedo OK, sure

**Comment by essobedo** [comment]
@davvd the PR has been merged, please proceed

**Comment by essobedo** [comment]
@davvd please

**Comment by essobedo** [comment]
@davvd I guess that there is a good reason that prevents you to go any further so could you please tell me what it is? Just to allow me to be aware of the entire workflow. Thank you in advance.

**Comment by essobedo** [comment]
@davvd ping

**Comment by essobedo** [comment]
@davvd please close the ticket

**Comment by davvd** [comment]
@yegor256 Thanks, closed

**Comment by davvd** [comment]
@elenavolokhova please, review this ticket for compliance with our [QA rules](http://at.teamed.io/qa.html)

**Comment by essobedo** [comment]
> @yegor256 Thanks, closed
@davvd thanks

**Comment by elenavolokhova** [comment]
@davvd Looks good!

**Comment by davvd** [comment]
> @davvd Looks good!

@elenavolokhova many thanks

**Comment by davvd** [comment]
@essobedo 10 mins was added to the account of @elenavolokhova (for QA review), in transaction 82204435

Much appreciated! **30 mins** was added to your account, payment ID `82204449`, time spent is 163 hours and 53 mins

+30 to your rating, your total score is [+435](http://www.netbout.com/b/36421?open=rating)
