### ISSUE TITLE
TkProxyTest.java:52-54: We need more tests for...

### ISSUE THREAD

**Issue by davvd** [yegor256/takes#656]
Puzzle `458-ca123cf9` in `src/test/java/org/takes/tk/TkProxyTest.java:52-54` has to be resolved: We need more tests for TkProxy. The tests should verify different combinations of request/response headers. This is the continuation of the issue #377.... The puzzle was created by Sebin George on 15-Mar-2016.

If you have any technical questions, don't ask me, submit new tickets instead. The task will be "done" when the problem is fixed and the text of the puzzle is removed from the source code.

**Comment by davvd** [comment]
@triberraar it's yours now, please proceed keeping in mind [our principles](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html). Feel free to ask any technical questions right here in the ticket

Task's budget is **30 mins** (see [this](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html) for explanation)

**Comment by davvd** [comment]
@yegor256 I set the milestone to 1.0 since there is nothing set yet

**Comment by davvd** [comment]
@triberraar the task is your hands for the last 15 days.. keep in mind that if it's not closed in the next 48 hours, it will be re-assigned to someone else, see [No Obligations](http://www.xdsd.org/2014/04/13/no-obligations-principle.html) principle. [This article](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html) should help if you're stuck

do not forget that you should remove the `@todo` puzzle from the source code

added -30 to your rating, now it is equal to [-60](http://www.netbout.com/b/36486?open=rating)

**Comment by davvd** [comment]
@triberraar it takes too long. Usually, we expect any task to be finished in less than a week. I'll assign someone else. Please stop working with it right now. See our [no obligations](http://www.xdsd.org/2014/04/13/no-obligations-principle.html) principle. added -60 to your rating, now it is equal to [-210](http://www.netbout.com/b/36486?open=rating)

**Comment by davvd** [comment]
@essobedo it's yours, please go ahead

**Comment by essobedo** [comment]
@davvd here is my PR #661 please find a reviewer

**Comment by davvd** [comment]
> @davvd here is my PR #661 please find a reviewer

@essobedo OK, sure

**Comment by essobedo** [comment]
@davvd the PR has been merged, it is ready for the QA

**Comment by essobedo** [comment]
@davvd need more time for other tasks of the puzzle to comple

**Comment by davvd** [comment]
> @davvd the PR has been merged, it is ready for the QA

@essobedo OK

**Comment by davvd** [comment]
> @davvd need more time for other tasks of the puzzle to comple

@essobedo of course, thanks for letting me know, take your time

**Comment by davvd** [comment]
@ypshenychka please, review this task for compliance with our [quality rules](http://at.teamed.io/qa.html)

**Comment by davvd** [comment]
@yegor256 The task is closed, thanks everybody

**Comment by ypshenychka** [comment]
@davvd Quality is good.

**Comment by davvd** [comment]
> @davvd Quality is good.

@ypshenychka thanks a lot :)

**Comment by davvd** [comment]
@essobedo added 10 mins to @ypshenychka, for QA review, payment code is `84301631`; I added **30 mins** to your account, many thanks for working with the project (84301655)! The completion time here was 168 hours and 10 mins.; +30 added to your rating, current score is: [+495](http://www.netbout.com/b/36421?open=rating)
