### ISSUE TITLE
Get rid of StandardCharsets.UTF_8

### ISSUE THREAD

**Issue by essobedo** [yegor256/takes#664]
There are many classes in the code base that rely on the public constant _StandardCharsets.UTF_8_ which is not a good solution for data duplication because:

1. It introduces coupling between all those classes and _StandardCharsets_ such that if the value is modified or simply removed those classes won't work properly anymore or won't even compile.
2. it reduces the global cohesion of those classes as they have to add their own semantics to this external constant with no real meaning instead of focusing on their own task .

More details [here](http://www.yegor256.com/2015/07/06/public-static-literals.html) and/or [Section 2.5 of the book Elegant Objects](http://www.amazon.com/gp/product/1519166915/ref=as_li_tl?ie=UTF8&camp=1789&creative=390957&creativeASIN=1519166915&linkCode=as2&tag=yegor256com-20&linkId=RMGEO4ESPM4CGD3O).

<hr id='w'>

**Comment by davvd** [comment]
@yegor256 please do something about this issue

**Comment by davvd** [comment]
@essobedo I added milestone `1.0` to this issue, let me know if there has to be something else

**Comment by davvd** [comment]
@xupyprmv it's yours,please go ahead

**Comment by davvd** [comment]
@essobedo many thanks for the report, I topped your account for 15 mins, transaction 84402755

**Comment by xupyprmv** [comment]
@davvd I added PR #670. Please find someone to review.

**Comment by davvd** [comment]
> @davvd I added PR #670. Please find someone to review.

@xupyprmv thank you!

**Comment by davvd** [comment]
@essobedo there is a puzzle in this code `664-ddd2c9b3`/#674, we'll resolve it later

**Comment by xupyprmv** [comment]
@essobedo PR #670 was merged. Please close this ticket.

**Comment by xupyprmv** [comment]
@davvd This ticket is closed.

**Comment by davvd** [comment]
@ypshenychka please, let us know what do you think about this ticket, according to our [QA rules](http://at.teamed.io/qa.html)

**Comment by ypshenychka** [comment]
@davvd Quality is good.

**Comment by davvd** [comment]
> @davvd Quality is good.

@ypshenychka thanks a lot

**Comment by davvd** [comment]
@xupyprmv just added 10 mins to @ypshenychka (for QA), payment ID is `85782608`; Thanks for your contribution, **30 mins** was added to your account, payment ID is `AP-0AT68670G4324460D`, 241 hours and 45 mins spent total; added +30 to your rating, now it is equal to [+315](http://www.netbout.com/b/35999?open=rating)

**Comment by davvd** [comment]
@essobedo the last puzzle `664-ddd2c9b3`/#674 originated from here solved
