### ISSUE TITLE
RqMtBase.java:80-83: This class is highly coupled,...

### ISSUE THREAD

**Issue by davvd** [yegor256/takes#666]
Puzzle `651-43df2f64` in `src/main/java/org/takes/rq/multipart/RqMtBase.java:80-83` has to be resolved: This class is highly coupled, it should be refactored in order to be able to reduce the overall coupling of this class which will allow to remove the violations ClassDataAbstractionCouplingCheck and PMD.ExcessiveImports.... The puzzle was created by Nicolas Filotto on 18-Apr-2016.

If you have any technical questions, don't ask me, submit new tickets instead. The task will be "done" when the problem is fixed and the text of the puzzle is removed from the source code.

**Comment by davvd** [comment]
@essobedo please proceed, it's yours

**Comment by davvd** [comment]
@yegor256 since the ticket has no milestone I set it to 1.0

**Comment by essobedo** [comment]
@davvd here is the PR #668 please find a reviewer

**Comment by davvd** [comment]
> @davvd here is the PR #668 please find a reviewer

@essobedo OK

**Comment by essobedo** [comment]
@davvd need more time to be validated by the architect

**Comment by davvd** [comment]
> @davvd need more time to be validated by the architect

@essobedo agreed, take your time

**Comment by essobedo** [comment]
@davvd the PR has been merged, you can proceed

**Comment by davvd** [comment]
@yegor256 Thanks, closing it now.

**Comment by davvd** [comment]
@ypshenychka please, review this issue for QA compliance, as per [par.24](http://at.teamed.io/policy.html#24)

**Comment by ypshenychka** [comment]
@davvd Quality is good.

**Comment by davvd** [comment]
> @davvd Quality is good.

@ypshenychka thanks!

**Comment by davvd** [comment]
@essobedo paied 10 mins to @ypshenychka for QA review (payment ID is `85728918`)

**30 mins** was added to your account, many thanks for your contribution (payment 85728968)! The task took 268 hours and 33 mins.

+30 to your rating, your total score is [+657](http://www.netbout.com/b/36421?open=rating)
