### ISSUE TITLE
The code base is polluted by String#toLowerCase(Locale.ENGLISH) 

### ISSUE THREAD

**Issue by essobedo** [yegor256/takes#667]
There are too many places in the code base where we call _toLowerCase(Locale.ENGLISH)_ from a _String_, I believe that is time to create a new _Class_ in the _misc_ package that will do it for us and clean up the code base by getting rid of all those calls to _String#toLowerCase(Locale.ENGLISH) _

Keep [this](http://www.yegor256.com/2014/05/05/oop-alternative-to-utility-classes.html) in mind while implementing it.

**Comment by davvd** [comment]
@yegor256 please do something about it, see [par.21](http://at.teamed.io/policy.html#21)

**Comment by yegor256** [comment]
@essobedo good idea, thanks

**Comment by davvd** [comment]
@essobedo milestone set to `1.0` (correct me if I am wrong)

**Comment by davvd** [comment]
@happy-neko please go ahead with this task, it's yours

**Comment by essobedo** [comment]
> @essobedo milestone set to 1.0 (correct me if I am wrong)

@davvd I must admit that I still don't know how versioning works in the different projects of teamed.io. When I create a new class I never know which version to set. Is there a doc somewhere that explain how the versioning works in teamed.io's project? What does it mean to set milestone to 1.0 in practice?

**Comment by davvd** [comment]
@essobedo thanks for reporting! I topped your account for 15 mins, transaction 85537942

**Comment by Happy-Neko** [comment]
@davvd Please assign someone else to this task.
I could not properly set "away" status before because netbout's google sign-in was broken.

**Comment by davvd** [comment]
> @davvd Please assign someone else to this task.
> I could not properly set "away" status before because netbout's google sign-in was broken.

@happy-neko OK, I will try to assign someone else

**Comment by davvd** [comment]
@dalifreire please go ahead with this task, it's yours

**Comment by dalifreire** [comment]
@davvd PR #676 created... please proceed.

**Comment by davvd** [comment]
> @davvd PR #676 created... please proceed.

@dalifreire thank you!

**Comment by dalifreire** [comment]
@davvd The CR was done in #676... we are waiting for @yegor256 to confirm the merge.

**Comment by dalifreire** [comment]
@davvd We need more time here. Looks like the AppVeyor container is dead, so we can`t merge the PR #676 now.

**Comment by davvd** [comment]
> @davvd The CR was done in #676... we are waiting for @yegor256 to confirm the merge.

@dalifreire OK

**Comment by davvd** [comment]
> @davvd We need more time here. Looks like the AppVeyor container is dead, so we can`t merge the PR #676 now.

@dalifreire of course, thanks for letting me know, take your time

**Comment by dalifreire** [comment]
@davvd @essobedo #676 was merged. Please, close this ticket.

**Comment by essobedo** [comment]
@dalifreire thx

**Comment by davvd** [comment]
@ypshenychka review this ticket please, for compliance with our [quality rules](http://at.teamed.io/qa.html)

**Comment by ypshenychka** [comment]
@davvd Quality is good.

**Comment by davvd** [comment]
> @davvd Quality is good.

@ypshenychka thank you, good quality is always good ;)

**Comment by davvd** [comment]
@essobedo the code made here contains a puzzle `667-ace435e8`, which will be resolved soon

**Comment by davvd** [comment]
@dalifreire I added 10 mins to @ypshenychka (for QA review) in transaction 90172554; Thanks so much! Your account was topped up for **30 mins** (transaction ID is `90172575`, the task took 1030 hours and 4 mins); +30 added to your rating, current score is: [-120](http://www.netbout.com/b/36485?open=rating)

**Comment by davvd** [comment]
@essobedo the last puzzle `687-65dc14c7`/#695 solved
