### ISSUE TITLE
TkProxy loses URL query parameters

### ISSUE THREAD

**Issue by yegor256** [yegor256/takes#671]
Originally from here: https://github.com/yegor256/jare/issues/8

**Comment by davvd** [comment]
@yegor256 I added milestone `1.0` to this issue, let me know if there has to be something else

**Comment by davvd** [comment]
@yegor256 it's yours, budget is 30 mins, please go ahead

**Comment by davvd** [comment]
@yegor256 thanks for this report, I added 15 mins to your account, in transaction `000-c8b1a6bb`

**Comment by yegor256** [comment]
@rultor try to release, tag is `0.32.8`

**Comment by davvd** [comment]
@elenavolokhova please, check this issue for QA compliance, as per [par.24](http://at.teamed.io/policy.html#24)

**Comment by elenavolokhova** [comment]
@yegor256 
 According to our [quality rules](http://www.teamed.io/qa.html):
 >Problem reporter and problem solver are two different persons.
 
 This was not a case in this ticket. Please avoid fixing your own issues.

 > Some of ticket messages must mention all pull requests where the problem was actually fixed.
 
 There is no link to related PR in comments. Please follow this rule in your tickets in the future.
 
 Please confirm that everything is clear and you have no questions regarding this approach.

**Comment by yegor256** [comment]
@elenavolokhova you're right, thanks for catching this, my bad. will try to avoid that in the future

**Comment by elenavolokhova** [comment]
@davvd Quality is acceptable here.

**Comment by davvd** [comment]
> @davvd Quality is acceptable here.

@elenavolokhova thanks a lot, next time everybody should try to make it better

**Comment by davvd** [comment]
@yegor256 I added 10 mins to @elenavolokhova (for QA review) in transaction 85549060

I added **1 hour** to your account, many thanks for working with the project (000-cfd546b6)! The completion time here was 23 hours and 59 mins.

the bonus for fast delivery (m=1439)

+60 added to your rating, at the moment it is: [+1223](http://www.netbout.com/b/35008?open=rating)

**Comment by yegor256** [comment]
@rultor deploy
