### ISSUE TITLE
Refactor class PsGithub.java

### ISSUE THREAD

**Issue by amihaiemil** [yegor256/takes#672]
[This](https://github.com/yegor256/takes/blob/master/src/main/java/org/takes/facets/auth/social/PsGithub.java) class could be refactored a lot if we use ``jcabi-github`` lib. 

1) Method ``private Identity fetch(final String token) throws IOException`` would become: 

```
private Identity fetch(final String token) throws IOException) {
    return PsGithub.parse(
        new RtGithub(token).users().self().json()
    );
}
```

2) If issue https://github.com/jcabi/jcabi-github/issues/1223 is accepted and implemented, then also method ``private String token(final String home, final String code) throws IOException`` becomes: 

```
private String token(final String home, final String code) throws IOException {
    String token = new RtGithubToken(this.app, home, this.key, code).accessToken();
    if ("".equals(token)) {
            throw new HttpException(
                HttpURLConnection.HTTP_BAD_REQUEST, "No access token"
            );
    }
    return token;
}
```

3) Attribtues ``this.github`` and ``this.api`` are no longer needed.

**Comment by davvd** [comment]
@yegor256 please dispatch this issue

**Comment by amihaiemil** [comment]
@yegor256 can you have a look here? Thanks

**Comment by yegor256** [comment]
@amihaiemil it's a good idea, but we shouldn't implement it. mostly because it will create unnecessary coupling between these two libraries. moreover, the ticket https://github.com/jcabi/jcabi-github/issues/1223 was not accepted. I don't see any problem with our current implementation of GitHub connectivity.
