### ISSUE TITLE
RsXSLT.java:143-145: continue removing usage StandardCharsets.UTF_8 from...

### ISSUE THREAD

**Issue by davvd** [yegor256/takes#674]
Puzzle `664-ddd2c9b3` in `src/main/java/org/takes/rs/RsXSLT.java:143-145` has to be resolved: continue removing usage StandardCharsets.UTF_8 from takes code (remove usage not only from this class but also from other parts of project). Please look at #664 for more details.... The puzzle was created by Maksimenko Vladimir on 25-Apr-2016.

If you have any technical questions, don't ask me, submit new tickets instead. The task will be "done" when the problem is fixed and the text of the puzzle is removed from the source code.

**Comment by davvd** [comment]
@dalifreire please go ahead with this task, it's yours

**Comment by davvd** [comment]
@yegor256 I set the milestone to 1.0 since there is nothing set yet

**Comment by dalifreire** [comment]
@davvd Thanks, I'm starting now...

**Comment by dalifreire** [comment]
@davvd PR #675 created... please proceed.

**Comment by davvd** [comment]
> @davvd Thanks, I'm starting now...

@dalifreire sure, you are welcome

**Comment by davvd** [comment]
> @davvd PR #675 created... please proceed.

@dalifreire thanks

**Comment by dalifreire** [comment]
@davvd The CR was done in #675... we are waiting for @yegor256 to confirm the merge.

**Comment by dalifreire** [comment]
@davvd The PR #675 was merged. Please, proceed.

**Comment by davvd** [comment]
> @davvd The CR was done in #675... we are waiting for @yegor256 to confirm the merge.

@dalifreire OK

**Comment by davvd** [comment]
> @davvd The PR #675 was merged. Please, proceed.

@dalifreire thank you

**Comment by davvd** [comment]
@yegor256 Thanks, closed

**Comment by davvd** [comment]
@ypshenychka please, let us know what do you think about this ticket, according to our [QA rules](http://at.teamed.io/qa.html)

**Comment by ypshenychka** [comment]
@davvd Quality is good.

**Comment by davvd** [comment]
> @davvd Quality is good.

@ypshenychka thanks a lot :)

**Comment by davvd** [comment]
@dalifreire 10 mins was added to the account of @ypshenychka (for QA review), in transaction 86361412... Many thanks! **30 mins** were added to your account in Transaction ID `86361432` (task took 121 hours and 55 mins)... +30 added to your rating, current score is: [+75](http://www.netbout.com/b/36485?open=rating)
