### ISSUE TITLE
HttpException.java:34-36: Remove the SuppressWarnings PMD.BeanMembersShouldSerialize once...

### ISSUE THREAD

**Issue by davvd** [yegor256/takes#678]
Puzzle `660-949a08e1` in `src/main/java/org/takes/HttpException.java:34-36` has to be resolved: Remove the SuppressWarnings PMD.BeanMembersShouldSerialize once the next release of Qulice will be available as it has been removed by https://github.com/teamed/qulice/issues/675... The puzzle was created by Nicolas Filotto on 24-Apr-2016.

If you have any technical questions, don't ask me, submit new tickets instead. The task will be "done" when the problem is fixed and the text of the puzzle is removed from the source code.

<hr id='w'>

**Comment by davvd** [comment]
@dalifreire the task is yours plz proceed

**Comment by davvd** [comment]
@yegor256 I set milestone here to `1.0`, let me know if it is wrong

**Comment by dalifreire** [comment]
@davvd PR #678 created... please proceed.

**Comment by davvd** [comment]
> @davvd PR #678 created... please proceed.

@dalifreire thanks for that

**Comment by dalifreire** [comment]
@davvd Looks like the next release of Qulice was not yet released ([teamed/qulice/#762](https://github.com/teamed/qulice/issues/762), [teamed/qulice/#706](https://github.com/teamed/qulice/issues/706))... maybe we are stuck here, right?

**Comment by dalifreire** [comment]
@davvd I think we need more time here... let's wait for [teamed/qulice/#706](https://github.com/teamed/qulice/issues/706), ok?

**Comment by davvd** [comment]
@dalifreire you're working with this ticket for the last 15 days. If it is not closed within the next 48 hours, it will be re-assigned to someone else, see [No Obligations](http://www.xdsd.org/2014/04/13/no-obligations-principle.html) principle. [This article](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html) should help if you're stuck; do not forget that you should remove the `@todo` puzzle from the source code; -30 added to your rating, at the moment it is: [-15](http://www.netbout.com/b/36485?open=rating)

**Comment by dalifreire** [comment]
@davvd The next release of Qulice was not yet released ([teamed/qulice/#762](https://github.com/teamed/qulice/issues/762), [teamed/qulice/#706](https://github.com/teamed/qulice/issues/706)). We can't do this task until the next release of Qulice. Please, revert my -30 penalty.

**Comment by dalifreire** [comment]
@davvd Please, revert my penalty or assign someone else

**Comment by davvd** [comment]
> @davvd Please, revert my penalty or assign someone else

@dalifreire I deducted 30 points from your rating

**Comment by davvd** [comment]
> @davvd Please, revert my penalty or assign someone else

@dalifreire all right, we'll find someone else for this task

**Comment by davvd** [comment]
@xupyprmv please proceed, it's yours

**Comment by xupyprmv** [comment]
@davvd Need more time here.

**Comment by davvd** [comment]
> @davvd Need more time here.

@xupyprmv of course, take your time

**Comment by xupyprmv** [comment]
@davvd  #681 was merged. Please, close this ticket.

**Comment by davvd** [comment]
@yegor256 2 puzzles were created here: `678-b4f3ecf4`/#684, `678-832c7c24`

**Comment by xupyprmv** [comment]
@davvd Close this ticket, please.

**Comment by davvd** [comment]
@yegor256 I'm closing the issue...

**Comment by davvd** [comment]
@elenavolokhova please, let us know what do you think about this ticket, according to our [QA rules](http://at.teamed.io/qa.html)

**Comment by elenavolokhova** [comment]
@davvd Looks good!

**Comment by davvd** [comment]
> @davvd Looks good!

@elenavolokhova thank you ;)

**Comment by davvd** [comment]
@xupyprmv 10 mins was added to the account of @elenavolokhova (for QA review), in transaction 90249069... **30 mins** was added to your account, many thanks for your contribution (payment AP-8HP110823R661183N)! The task took 361 hours and 11 mins.... +30 added to your rating, at the moment it is: [+225](http://www.netbout.com/b/35999?open=rating)

**Comment by davvd** [comment]
@yegor256 last puzzled solved `684-70270140`/#692
