### ISSUE TITLE
What is the best way to speed up the merge request?

### ISSUE THREAD

**Issue by dalifreire** [yegor256/takes#679]
All the times that the pull request is created and reviewed we need a project architect confirmation to finish the merge. Sometimes a lot of time is wasted waiting for this confirmation and the developer rating is decreased because of that (#676, #624, #653). 

So, what is the best way to speed up the merge request?

**Comment by davvd** [comment]
@yegor256 please pay attention to this issue ([par.21](http://at.teamed.io/policy.html#21))

**Comment by yegor256** [comment]
@dalifreire there is no way to speed things up. the best you can do is to ask project manager to give you "more time", see http://at.teamed.io/policy.html#10 That will help you not to lose your rating points
