### ISSUE TITLE
Duplicately declared interfaces

### ISSUE THREAD

**Issue by simonjenga** [yegor256/takes#683]
```java
/**
 * Script to execute.
 */
public interface Script {
	/**
	 * Execute it against this URI.
	 * @param home URI of the running front
	 * @throws IOException If fails
	 */
	void exec(URI home) throws IOException;
}
```

The above interface has been duplicately declared at both: ```org.takes.http.FtRemote.Script``` and at: ```org.takes.http.MainRemote.Script```

Only one declaration is needed to be done at ```org.takes.http.Script```.

The interface method also needs to be renamed to ```execute(URI home)``` so as to be meaningful.

Also, the class level documentation of ```FtRemote``` and ```MainRemote``` is also duplicated and does not provide any meaningful information as to what these two classes do!... :eyes: :flushed:

**Comment by davvd** [comment]
@yegor256 take a look at this issue please and dispatch it somehow, see [par.21](http://at.teamed.io/policy.html#21)

**Comment by yegor256** [comment]
@simonjenga it's better to keep that interface embedded and specific for each case. making it shared will create a dependency between these two classes, which is not natural
