### ISSUE TITLE
RqForm.java:69-71: Refacor this class to reduce...

### ISSUE THREAD

**Issue by davvd** [yegor256/takes#687]
Puzzle `667-ace435e8` in `src/main/java/org/takes/rq/RqForm.java:69-71` has to be resolved: Refacor this class to reduce the data abstraction coupling in order to get rid of the checkstyle suppression of ClassDataAbstractionCouplingCheck... The puzzle was created by Dalí Freire on 6-May-2016.

If you have any technical questions, don't ask me, submit new tickets instead. The task will be "done" when the problem is fixed and the text of the puzzle is removed from the source code.

<hr id='w'>

**Comment by davvd** [comment]
@rui-castro please pick this up, and keep in mind [these instructions](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html). Any technical questions - ask right here; The budget of this issue is **30 mins**, which is exactly how much will be paid when the task is *done* (see [this](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html) for explanation)

**Comment by davvd** [comment]
@yegor256 since the ticket has no milestone I set it to 1.0

**Comment by rui-castro** [comment]
@davvd The PR #690 was created.

**Comment by davvd** [comment]
> @davvd The PR #690 was created.

@rui-castro thank you!

**Comment by rui-castro** [comment]
@davvd The PR is merged, can you close this issue?

**Comment by davvd** [comment]
> @davvd The PR is merged, can you close this issue?

@rui-castro sure

**Comment by davvd** [comment]
@yegor256 these 2 puzzles were created in this ticket: `687-65dc14c7`, `687-875c0e1d`/#694

**Comment by davvd** [comment]
@yegor256 Thanks, closing it now.

**Comment by davvd** [comment]
@elenavolokhova please, review this issue for QA compliance, as per [par.24](http://at.teamed.io/policy.html#24)

**Comment by elenavolokhova** [comment]
@davvd Looks good!

**Comment by davvd** [comment]
> @davvd Looks good!

@elenavolokhova thanks, got it, great to see high-quality tickets here

**Comment by davvd** [comment]
@rui-castro paied 10 mins to @elenavolokhova for QA review (payment ID is `91818593`). Thanks for your contribution, **30 mins** was added to your account, payment ID is `AP-76U252629J0632925`, 310 hours and 33 mins spent total. added +30 to your rating, now it is equal to [+30](http://www.netbout.com/b/37013?open=rating)

**Comment by rui-castro** [comment]
@davvd thanks 😉

**Comment by davvd** [comment]
> @davvd thanks 😉

@rui-castro you are welcome

**Comment by davvd** [comment]
@yegor256 the last puzzle `687-65dc14c7`/#695 solved
