### ISSUE TITLE
Utf8String#string() does not encode a String using the given charset

### ISSUE THREAD

**Issue by simonjenga** [yegor256/takes#691]
The current implementation of ```org.takes.misc.Utf8String#string()``` does not do anything at all as in the following example scenario:

```java
Utf8String str = new Utf8String("simple example");
str.string();
```

The String passed in the constructor will not be encoded using any given ```Charset```! The method simply acts as a plain ```getter```

Also, the ```private constant``` in that class ```org.takes.misc.Utf8String.ENCODING``` is unnecessary!
https://github.com/jcabi/jcabi-xml/issues/102

The class needs to be redesigned and refactored. The following is my humble proposal:

```java
public final class Utf8String {

    /**
     * String value.
     */
    private final transient String value;
    
    /**
     * Ctor.
     * @param string String value
     */
    public Utf8String(final String string) {
        this.value = string;
    }

    /**
     * Ctor.
     * @param bytes Bytes to construct UTF-8 string value
     */
    public Utf8String(final byte... bytes) {
        this(new String(bytes));
    }

    /**
     * Encodes string value into a sequence of bytes using UTF-8 charset.
     * @return Sequence of bytes
     */
    public byte[] bytes() {
        return this.value.getBytes(Charset.forName("UTF-8"));
    }

    /**
     * Returns string value.
     * @return String value
     */
    public String string() {
    	return new String(this.bytes());
    }
}
```

**Comment by davvd** [comment]
@yegor256 please take a look at it and dispatch (see [par.21](http://at.teamed.io/policy.html#21))

**Comment by yegor256** [comment]
@simonjenga I'm not sure I understand what is the problem here. are you aware that all Strings in Java are in UTF-8?

**Comment by simonjenga** [comment]
@yegor256 I didn't remember that. The issue then looks irrelevant but the ```String``` constant should be removed. Closing it...
