### ISSUE TITLE
TkCors.java:53-56: Remove PMD.AvoidDuplicateLiterals exclude here and...

### ISSUE THREAD

**Issue by davvd** [yegor256/takes#692]
Puzzle `684-70270140` in `src/main/java/org/takes/tk/TkCors.java:53-56` has to be resolved: Remove PMD.AvoidDuplicateLiterals exclude here and in {@link RsPrettyJson}, {@link RsPrettyXml}. Note that this puzzle depends on https://github.com/teamed/qulice/issues/760. Note that this puzzle has partially overlap with https://github.com/yegor256/takes/issues/686... The puzzle was created by Maksimenko Vladimir on 18-Jun-2016.

If you have any technical questions, don't ask me, submit new tickets instead. The task will be "done" when the problem is fixed and the text of the puzzle is removed from the source code.

**Comment by davvd** [comment]
@xupyprmv the task is yours, please go ahead

**Comment by davvd** [comment]
@yegor256 since the ticket has no milestone I set it to 1.0

**Comment by xupyprmv** [comment]
@davvd I'm waiting for https://github.com/teamed/qulice/issues/760 here.

**Comment by davvd** [comment]
> @davvd I'm waiting for https://github.com/teamed/qulice/issues/760 here.

@xupyprmv OK, take your time

**Comment by xupyprmv** [comment]
@davvd I'm waiting for #697 here.

**Comment by davvd** [comment]
> @davvd I'm waiting for #697 here.

@xupyprmv yes, right, let's wait for #697

**Comment by xupyprmv** [comment]
@davvd I added PR #710. Please find someone to review.

**Comment by davvd** [comment]
> @davvd I added PR #710. Please find someone to review.

@xupyprmv thank you!

**Comment by davvd** [comment]
@yegor256 FYI, the issue we were waiting for (#697) is fixed

**Comment by xupyprmv** [comment]
@davvd #710 was merged. Please, close this thicket.

**Comment by davvd** [comment]
> @davvd #710 was merged. Please, close this thicket.

@xupyprmv sure thanks

**Comment by davvd** [comment]
@yegor256 The task is done, thanks all, I am closing it

**Comment by davvd** [comment]
@elenavolokhova please, help us to evaluate quality here, as per [par.24](http://at.teamed.io/policy.html#24)

**Comment by elenavolokhova** [comment]
@davvd  Looks good!

**Comment by davvd** [comment]
> @davvd  Looks good!

@elenavolokhova thanks!

**Comment by davvd** [comment]
@xupyprmv just added 10 mins to @elenavolokhova (for QA), payment ID is `97430079`. Many thanks! **23 mins** were added to your account in Transaction ID `AP-6WA17721YT799422D` (task took 45 hours and 4 mins). the bonus for fast delivery (m=2704). +23 added to your rating, at the moment it is: [+128](http://www.netbout.com/b/35999?open=rating)
