### ISSUE TITLE
Readme mentions throwing RsFlash

### ISSUE THREAD

**Issue by looperhacks** [yegor256/takes#693]
The part *Redirects* from the Readme contains an example that throws an instance of RsFlash (line 537). RsFlash isn't a throwable, is the example wrong?

**Comment by davvd** [comment]
@yegor256 please pay attention to this issue ([par.21](http://at.teamed.io/policy.html#21))

**Comment by yegor256** [comment]
@looperhacks fixed in 	ca2fa1e thanks!
