### ISSUE TITLE
package-info.java:38-40: Improve documentation for package org.takes.rq.form...

### ISSUE THREAD

**Issue by davvd** [yegor256/takes#694]
Puzzle `687-875c0e1d` in `src/main/java/org/takes/rq/form/package-info.java:38-40` has to be resolved: Improve documentation for package org.takes.rq.form explaining what a form is, providing code examples of usage of existing classes and other info that may be relevant.... The puzzle was created by Rui Castro on 25-Jun-2016.

If you have any technical questions, don't ask me, submit new tickets instead. The task will be "done" when the problem is fixed and the text of the puzzle is removed from the source code.

**Comment by davvd** [comment]
@yegor256 attached this issue to milestone "1.0" (let me know if this is wrong)

**Comment by davvd** [comment]
@xupyprmv could you please pick this up? This [article](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html) explains how we work. Any technical questions you may ask right here... **15 mins** is the budget of the task. This is exactly how much will be paid when the problem is [solved](http://www.xdsd.org/2014/04/15/definition-of-done.html) (no matter how much time you will actually spend). See [this](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html) for more information

**Comment by xupyprmv** [comment]
@davvd PR #702 was merged. Please close this ticket.

**Comment by davvd** [comment]
@yegor256 We are done here, thanks all

**Comment by davvd** [comment]
@ypshenychka please, help us to evaluate quality here, as per [par.24](http://at.teamed.io/policy.html#24)

**Comment by ypshenychka** [comment]
@davvd Quality is good.

**Comment by davvd** [comment]
> @davvd Quality is good.

@ypshenychka thanks a lot :)

**Comment by davvd** [comment]
@xupyprmv just added 10 mins to @ypshenychka (for QA), payment ID is `94251489`; thanks, I just added **15 mins** to your account, payment `AP-10P56631L7948443R`, 237 hours and 49 mins spent; +15 to your rating, your total score is [+135](http://www.netbout.com/b/35999?open=rating)
