### ISSUE TITLE
RqFormBase.java:56-58: Refactor this class to reduce...

### ISSUE THREAD

**Issue by davvd** [yegor256/takes#695]
Puzzle `687-65dc14c7` in `src/main/java/org/takes/rq/form/RqFormBase.java:56-58` has to be resolved: Refactor this class to reduce the data abstraction coupling in order to get rid of the checkstyle suppression of ClassDataAbstractionCouplingCheck.... The puzzle was created by Rui Castro on 25-Jun-2016.

If you have any technical questions, don't ask me, submit new tickets instead. The task will be "done" when the problem is fixed and the text of the puzzle is removed from the source code.

**Comment by davvd** [comment]
@yegor256 there is no milestone yet, so I set it to `1.0`

**Comment by davvd** [comment]
@dalifreire the task is yours,please go ahead

**Comment by dalifreire** [comment]
@davvd PR #703 was created, please proceed.

**Comment by davvd** [comment]
> @davvd PR #703 was created, please proceed.

@dalifreire thank you

**Comment by dalifreire** [comment]
@davvd We will need a bit more time here...

**Comment by davvd** [comment]
> @davvd We will need a bit more time here...

@dalifreire agreed, take your time

**Comment by dalifreire** [comment]
@davvd We are waiting for the architect approval in PR #703...

**Comment by dalifreire** [comment]
@davvd The PR #703 was merged. Please proceed.

**Comment by davvd** [comment]
> @davvd The PR #703 was merged. Please proceed.

@dalifreire thank you!

**Comment by davvd** [comment]
@yegor256 Thanks all, I am closing

**Comment by davvd** [comment]
@elenavolokhova please, review this ticket for compliance with our [QA rules](http://at.teamed.io/qa.html)

**Comment by elenavolokhova** [comment]
@davvd  Looks good!

**Comment by davvd** [comment]
> @davvd  Looks good!

@elenavolokhova thanks a lot

**Comment by davvd** [comment]
@dalifreire just added 10 mins to @elenavolokhova (for QA), payment ID is `94930964`; Thanks so much! Your account was topped up for **30 mins** (transaction ID is `94930969`, the task took 333 hours and 32 mins); +30 added to your rating, at the moment it is: [+60](http://www.netbout.com/b/36485?open=rating)
