### ISSUE TITLE
RsHTML instead of RsHtml in readme file

### ISSUE THREAD

**Issue by pchmielowski** [yegor256/takes#705]
`return new RsHTML("<html>Hello, world!</html>");`

Should be RsHtml.

**Comment by pchmielowski** [comment]
I have corrected it and created pull request https://github.com/yegor256/takes/pull/706

**Comment by davvd** [comment]
@yegor256 please take a look at it and dispatch (see [par.21](http://at.teamed.io/policy.html#21))

**Comment by yegor256** [comment]
@pchmielowski fixed, thanks
