### ISSUE TITLE
transient is not needed anymore

### ISSUE THREAD

**Issue by krzyk** [yegor256/takes#707]
`transient` requirement has been removed from qulice. Please remove it everywhere where it was not added explicitly (e.g. in case of `Serializable` classes).

Also remove `of` parameter from all `@EqualsAndHashCode`, it was there because we had transient fields and we constantly were forgetting to add new fields there, now it won't be needed. (check tests for `EqualsVerifier.ignoredFields` for cases where `of` is still needed in the class under test).

Also in case of tests that check equals/hashCode contract using `EqualsVerifier`, remove `suppress(Warning.TRANSIENT_FIELDS)`.

**Comment by davvd** [comment]
@yegor256 please pay attention to this issue ([par.21](http://at.teamed.io/policy.html#21))

**Comment by davvd** [comment]
@krzyk I added milestone `1.0` to this issue, let me know if there has to be something else

**Comment by davvd** [comment]
@dalifreire the task is yours, please go ahead

**Comment by davvd** [comment]
@krzyk many thanks, **15 mins** added to your acc for reporting this bug, pmt ID `97026785`

**Comment by dalifreire** [comment]
@davvd PR #711 was created... please, proceed.

**Comment by davvd** [comment]
> @davvd PR #711 was created... please, proceed.

@dalifreire thank you

**Comment by dalifreire** [comment]
@davvd We are waiting for architect approval in PR #711...

**Comment by davvd** [comment]
> @davvd We are waiting for architect approval in PR #711...

@dalifreire thanks for that

**Comment by dalifreire** [comment]
@davvd PR #711 was merged... please proceed.

**Comment by davvd** [comment]
> @davvd PR #711 was merged... please proceed.

@dalifreire thank you!

**Comment by krzyk** [comment]
@dalifreire you need to ask issue creator to close the issue, I noticed it by accident so I'll close it. Only after it is close you will be awared.

**Comment by davvd** [comment]
@elenavolokhova please, check this issue for QA compliance, as per [par.24](http://at.teamed.io/policy.html#24)

**Comment by elenavolokhova** [comment]
@davvd  Looks good!

**Comment by davvd** [comment]
> @davvd  Looks good!

@elenavolokhova thank you

**Comment by davvd** [comment]
@dalifreire just added 10 mins to @elenavolokhova (for QA), payment ID is `98136751`... **30 mins** added to your account (payment number `98136763`), many thanks for your contribution! 214 hours and 46 mins spent here.... +30 added to your rating, current score is: [+75](http://www.netbout.com/b/36485?open=rating)
