### ISSUE TITLE
Symlink to enable dynamic cms?

### ISSUE THREAD

**Issue by amihaiemil** [yegor256/takes#713]
As I explained in [this](http://www.yegor256.com/2014/06/25/xml-and-xslt-in-browser.html#comment-2917659498) comment, at application startup you can make a symlink and map the contents folder from the filesystem to a folder under the contextroot of the app (and it will behave exactly as if the content would be inside the deployable, under the webapp folder). 

Something like this:

```
File contextRoot = new File(servletContext.getRealPath(""));
File link = new File(contextRoot, "cms");

Path contentPath = FileSystems.getDefault().getPath("path/to/content/on/disk");

Files.createSymbolicLink(link.toPath(), contentPath);
```

Your content becomes available at path ``/cms/...`` under your context-root. So say the app has contextroot ``/app``, a link to the index page would look like this ``domain/app/cms/.../index.html``

This way, the static content can be managed inside a CMS, published on the filesystem and it would become available right away, eliminating the need for a build and deployment just for a change of text or html file or javascript clientside code.  

I think it would be nice if takes offered such functionality.

**Comment by davvd** [comment]
@yegor256 please do something about it, see [par.21](http://at.teamed.io/policy.html#21)

**Comment by yegor256** [comment]
@amihaiemil you can do it already. See how it's done here, for example: https://github.com/yegor256/jare/blob/0.7.1/src/main/java/io/jare/tk/TkApp.java#L162-L168 Or I didn't understand your question?

**Comment by amihaiemil** [comment]
@yegor256 If I understand well that code, it takes images from somewhere and then, using that refresh method, it puts them under the project's src/main/resources...

And that refresh method runs a mvn command ...? Seems very strange to me, sorry.

So the app makes static resources accesible by first looking for them, and then running mvn on-the-fly to pack them inside it... but why not simply put them on disk, in a place accessible through a symlink, like I illustrated here? 

Why do the static resources need to be part of the application?

I mean sure, it seems to achieve the dynamicity I talk about, but it seems awfully complicated ^^

**Comment by yegor256** [comment]
@amihaiemil you can do it with the help of [`TkFiles`](https://github.com/yegor256/takes/blob/1.1/src/main/java/org/takes/tk/TkFiles.java). Or I miss the idea again? :)

**Comment by amihaiemil** [comment]
@yegor256 I see. That sounds more like what I had in mind :D
