### ISSUE TITLE
Can't combine FkRegex and TkMethods

### ISSUE THREAD

**Issue by MeteorBoom** [yegor256/takes#719]
I'm begining to play with Takes framework and I'm trying to make things that I usaly do. 
In Spring I can specify `@RequestMapping(value = "/users/{id}", method = RequestMethod.GET)` annotation and then I can inject id with `@PathVariable("id")` annotation. 
But in Takes Framework when I use FkRegex I can only specify implementation of TkRegex interface to obtain RqRegex and I can't restict which http methods allowed (with TkMethods for example). It is possible now or I must implement some custom class for doing this?

**Comment by davvd** [comment]
@yegor256 please do something about this issue

**Comment by yegor256** [comment]
@MeteorBoom You can use `TkMethods`. See how it's done here, for example: https://github.com/yegor256/jare/issues/27

**Comment by MeteorBoom** [comment]
@yegor256 But constructor of TkMethods is not accept TkRegex. I can get part of request string only by manual parsing, am I?

**Comment by yegor256** [comment]
@MeteorBoom as I understood from your original problem description: you were trying to restrict certain HTTP methods. This is what `TkMethods` is for. What is the task now? If it's something else, would be better to submit another ticket.
