### ISSUE TITLE
Error installing pdd while trying to merge

### ISSUE THREAD

**Issue by essobedo** [yegor256/takes#726]
Rultor cannot merge any PR due to an error of type:

```
ERROR:  Error installing pdd:
	nokogiri requires Ruby version >= 2.1.0.
```

You can see one example of full log [here](http://www.rultor.com/t/10259-297015075)

**Comment by 0crat** [comment]
@yegor256 please, pay attention to this issue

**Comment by yegor256** [comment]
@essobedo it was an issue in Rultor, fixed already: https://github.com/yegor256/rultor/issues/1174
