### ISSUE TITLE
TkSlf4jTest.java:47-49: Refactor this class to reduce the...

### ISSUE THREAD

**Issue by 0pdd** [yegor256/takes#731]
The puzzle `712-65dc14c7` in [`src/test/java/org/takes/tk/TkSlf4jTest.java`](https://github.com/yegor256/takes/blob/master/src/test/java/org/takes/tk/TkSlf4jTest.java) (lines 47-49) has to be resolved: "Refactor this class to reduce the data abstraction coupling in order to get rid of the checkstyle suppression of ClassDataAbstractionCouplingCheck."

The puzzle was created by Piotr Pradzynski on 14-Dec-16. 

Estimate: 30 minutes, role: IMP.

If you have any technical questions, don't ask me, submit new tickets instead. The task will be "done" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0crat** [comment]
@yegor256 please, pay attention to this issue

**Comment by yegor256** [comment]
@0crat in

**Comment by 0crat** [comment]
> @0crat in ([here](https://github.com/yegor256/takes/issues/731#issuecomment-322126201))

@yegor256 Job `gh:yegor256/takes#731` is in scope.

**Comment by 0crat** [comment]
Job `gh:yegor256/takes#731` assigned to @caarlos0, please go ahead ([policy](http://datum.zerocracy.com/pages/policy.html)).

**Comment by 0crat** [comment]
@caarlos0 this job was assigned to you 8 days ago.
It will be taken away from you after 10 days from start (this is our policy).

**Comment by 0crat** [comment]
Oops! Job `gh:yegor256/takes#731` is not assigned to anyone.

**Comment by 0crat** [comment]
Oops! Job `gh:yegor256/takes#731` is not assigned to anyone.

**Comment by 0crat** [comment]
The job [#731](https://github.com/yegor256/takes/issues/731) assigned to neonailol. The budget is 30 minutes, see [§4](http://datum.zerocracy.com/pages/policy.html#4). Please, read [§8](http://datum.zerocracy.com/pages/policy.html#8) and [§9](http://datum.zerocracy.com/pages/policy.html#9). If the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html).

**Comment by 0pdd** [comment]
The puzzle `712-65dc14c7` has disappeared from the source code, that's why I closed this issue.

**Comment by 0crat** [comment]
Job `gh:yegor256/takes#731` is not assigned, can't get start time

**Comment by 0crat** [comment]
Order was successfully finished: +30 points just awarded to @neonailol[/z](http://www.0crat.com/u/neonailol), total is [+105](http://www.0crat.com/u/neonailol)

**Comment by 0crat** [comment]
The job [#731](https://github.com/yegor256/takes/issues/731) is now out of scope

**Comment by 0crat** [comment]
Job [#731](https://github.com/yegor256/takes/issues/731) was not in scope
