### ISSUE TITLE
Outdated links in Takes README.md

### ISSUE THREAD

**Issue by maxxyme** [yegor256/takes#738]
README.md visible @ https://github.com/yegor256/takes

Sentence: "These blog posts may help you too." has a link to http://www.yegor256.com/tag/takes.html which is 404

RsXembly chapter: https://github.com/yegor256/takes#rsxembly
Here is how you generate an XML page using Xembly points to www.takes.org instead of www.xembly.org

**Comment by 0crat** [comment]
@yegor256 please, pay attention to this issue

**Comment by yegor256** [comment]
@maxxyme thanks, fixed in 54461ecf1
