### ISSUE TITLE
functional interfaces for takes and responses

### ISSUE THREAD

**Issue by yegor256** [yegor256/takes#739]
Let's add them, wherever possible.

**Comment by yegor256** [comment]
@0crat assign me

**Comment by 0crat** [comment]
> @0crat assign me ([here](https://github.com/yegor256/takes/issues/739#issuecomment-317692256))

@yegor256 Job `gh:yegor256/takes#739` assigned to @yegor256, please go ahead.

**Comment by 0crat** [comment]
+15 points just awarded to @yegor256, total is [+405](http://www.0crat.com/u/yegor256).

**Comment by yegor256** [comment]
@rultor release, tag is `1.4`

**Comment by 0crat** [comment]
Job `gh:yegor256/takes#739` is out of scope.

**Comment by 0crat** [comment]
+30 points just awarded to @yegor256, total is [+435](http://www.0crat.com/u/yegor256).
