### ISSUE TITLE
Href.path() must add slash prefix by default

### ISSUE THREAD

**Issue by yegor256** [yegor256/takes#74]
This code doesn't work:

```
new Href("http://example.com").path("a").path("b").toString().equals("http://example.com/a/b")
```

In reality it's equal to `"http://example.com/ab"`

**Comment by davvd** [comment]
I am aware of the task, give me some time to find a developer...

**Comment by davvd** [comment]
@dmzaytsev it's yours, please help. The budget is **30 mins**

**Comment by davvd** [comment]
@yegor256 thanks for tis bug, I topped your account for 15 mins, transaction `000-e524ecc3`

**Comment by yegor256** [comment]
@rultor release, tag is `0.9.11`

**Comment by yegor256** [comment]
@dmzaytsev thanks!

**Comment by davvd** [comment]
@dmzaytsev I don't see any messages from you above, not sure if there was actual contribution (correct me if I'm wrong)

**Comment by dmzaytsev** [comment]
@davvd Do not quite understand what you mean.
The task #74 has been assigned to me.
I resolved it, made the pull request(#75), which has been reviewed and merged.
then  @yegor256 closed the task.

**Comment by yegor256** [comment]
@dmzaytsev every time you finish a task, don't forget to post a message into it, explaining where you made a fix (in which PR).

**Comment by yegor256** [comment]
@davvd please add extra 30 mins to @dmzaytsev

**Comment by dmzaytsev** [comment]
@yegor256 thanks for explain

**Comment by davvd** [comment]
> @davvd please add extra 30 mins to @dmzaytsev 

@yegor256 I've sent 30 mins extra to @dmzaytsev in transaction ID "54270186"
