### ISSUE TITLE
XeChain must accept a function

### ISSUE THREAD

**Issue by yegor256** [yegor256/takes#742]
Let's make it possible

**Comment by yegor256** [comment]
@0crat assign me

**Comment by 0crat** [comment]
> @0crat assign me ([here](https://github.com/yegor256/takes/issues/742#issuecomment-320870147))

@yegor256 Job `gh:yegor256/takes#742` assigned to @yegor256, please go ahead ([policy](http://datum.zerocracy.com/pages/policy.html)).

**Comment by 0crat** [comment]
+15 points just awarded to @yegor256, total is [+1245](http://www.0crat.com/u/yegor256).

**Comment by yegor256** [comment]
@rultor release, tag is `1.5`

**Comment by 0crat** [comment]
Job `gh:yegor256/takes#742` is now out of scope.

**Comment by 0crat** [comment]
+30 points just awarded to @yegor256, total is [+1275](http://www.0crat.com/u/yegor256).
