### ISSUE TITLE
Constructors of FkHitRefresh shouldn't throw any exceptions.

### ISSUE THREAD

**Issue by skapral** [yegor256/takes#744]
The issue was raised after this discussion - http://disq.us/p/1lgf1ax.

According to [this](http://www.yegor256.com/2015/05/07/ctors-must-be-code-free.html) post, constructors should not do any logic inside. For Takes framework, this rule is violated in several places. One of them is the class `org.takes.facets.fork.FkHitRefresh`, which handles with IO inside a constructor.

PS: @yegor256 please consider me as a contributor to solve this issue.

**Comment by 0crat** [comment]
@yegor256 please, pay attention to this issue

**Comment by yegor256** [comment]
@skapral thanks! Please, submit a pull request, if you can.

**Comment by yegor256** [comment]
@0crat assign @skapral

**Comment by 0crat** [comment]
> @0crat assign @skapral  ([here](https://github.com/yegor256/takes/issues/744#issuecomment-323596907))

@yegor256 Job `gh:yegor256/takes#744` assigned to @skapral, please go ahead ([policy](http://datum.zerocracy.com/pages/policy.html)). @skapral is not a member of this project yet, but can request to join. @skapral check your [Zerocracy profile](http://www.0crat.com/u/skapral) and follow the instructions.

**Comment by 0crat** [comment]
@skapral this job was assigned to you 8 days ago.
It will be taken away from you after 10 days from start (this is our policy).

**Comment by 0crat** [comment]
Oops! Job `gh:yegor256/takes#744` is not assigned to anyone.

**Comment by 0crat** [comment]
The job [#744](https://github.com/yegor256/takes/issues/744) assigned to @t-izbassar[/z](https://www.0crat.com/u/t-izbassar), here is [why](https://www.0crat.com/footprint/C3FFK3YAY/432353494). The budget is 30 minutes, see [§4](http://datum.zerocracy.com/pages/policy.html#4). Please, read [§8](http://datum.zerocracy.com/pages/policy.html#8) and [§9](http://datum.zerocracy.com/pages/policy.html#9). If the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html).

**Comment by t-izbassar** [comment]
@0crat waiting for @skapral to decide what to do with his #745 PR.

**Comment by 0crat** [comment]
> @0crat waiting for @skapral to decide what to do with his #745 PR. ([here](https://github.com/yegor256/takes/issues/744#issuecomment-365878370))

@t-izbassar The impediment for [#744](https://github.com/yegor256/takes/issues/744) was registered successfully by @t-izbassar[/z](https://www.0crat.com/u/t-izbassar)

**Comment by t-izbassar** [comment]
@skapral apparently, you are done with this one) #745 is merged, can you close it?)

**Comment by t-izbassar** [comment]
@skapral ping

**Comment by 0crat** [comment]
@elenavolokhova[/z](https://www.0crat.com/u/elenavolokhova) please review this job, as in [§30](http://datum.zerocracy.com/pages/policy.html#30)

**Comment by elenavolokhova** [comment]
@yegor256 This tickett violates QA rule:
> Problem reporter and problem solver are two different persons.

Desision to let @skapral to deliver a solution to his own ticket led to incorrect situation here: 
- actual problem solver is a bug reporter, but he is not assigned to this ticket any more and is not a member of this project. 
- @skapral assigned to this project didn't actually solve an issue and shouldn't be paid.

Please, **confirm** that you'll try to avoid assigning problem reporter to his own issue in future. 

I assume the quality of this ticket is bad. Please, **let me know**, if I'm wrong.

**Comment by t-izbassar** [comment]
@elenavolokhova can you inform 0crat about quality? Personally, I agree with you. I need this task to be closed by 0crat so that I can handle next one - thus you need to inform 0crat about the decision.

**Comment by elenavolokhova** [comment]
@t-izbassar Sure.

**Comment by elenavolokhova** [comment]
@0crat Quality is bad here.

**Comment by 0crat** [comment]
> @0crat Quality is bad here. ([here](https://github.com/yegor256/takes/issues/744#issuecomment-366657746))

@elenavolokhova Argument "is" doesn't match regex `good|bad|acceptable`

**Comment by elenavolokhova** [comment]
@0crat bad

**Comment by 0crat** [comment]
> @0crat Quality bad ([here](https://github.com/yegor256/takes/issues/744#issuecomment-366658223))

@elenavolokhova Can't understand "bad", try one of these:
  - `assign` Assign a performer to this issue
  - `boost` Set a boost for the job
  - `hello` Just say hello
  - `in` Register this issue in scope (WBS)
  - `out` Remove this issue from scope (WBS)
  - `quality` Review a task
  - `resign` Resign from this issue
  - `status` Check the status of the job
  - `version` Print current version of the bot
  - `waiting` Register an impediment for a job

**Comment by elenavolokhova** [comment]
@0crat quality bad

**Comment by 0crat** [comment]
QA review completed: +15 points just awarded to @elenavolokhova[/z](https://www.0crat.com/u/elenavolokhova), total is [+15](https://www.0crat.com/u/elenavolokhova)

**Comment by t-izbassar** [comment]
@0crat status

**Comment by 0crat** [comment]
> @0crat status ([here](https://github.com/yegor256/takes/issues/744#issuecomment-366662016))

@t-izbassar This is what I know about this job, as in [§32](http://datum.zerocracy.com/pages/policy.html#32):

  * The job [#744](https://github.com/yegor256/takes/issues/744) is not in scope
  * Job [footprint](https://www.0crat.com/footprint/C3FFK3YAY?q=%7Bjob%3A%27gh%3Ayegor256%2Ftakes%23744%27%7D) (restricted area)

**Comment by 0pdd** [comment]
@skapral the puzzle [#935](https://github.com/yegor256/takes/issues/935) is still not solved; solved: [#802](https://github.com/yegor256/takes/issues/802).
