### ISSUE TITLE
Security

### ISSUE THREAD

**Issue by eljames** [yegor256/takes#746]
Do you plan develop some security framework for Takes? For treat CSRF atack, user autentication and authorization, SSL, etc...
Congratulations, I love the way Takes was designed, it's clean and well done. Thanks!

**Comment by 0crat** [comment]
@yegor256 please, pay attention to this issue

**Comment by yegor256** [comment]
@eljames we have SSL already. As for other things, feel free to contribute or submit separate tickets, we'll try to fix, if we have resources available. The best way, of course, is to contribute with a pull request :) Thanks for using Takes!
