### ISSUE TITLE
Possible synchronization issue in RsPrettyXml

### ISSUE THREAD

**Issue by t-izbassar** [yegor256/takes#747]
Tracing [commit](https://github.com/yegor256/takes/commit/3fdfe2fa7a419fb877025f8e6a69ee0ffbdbb43e) I've noticed that completely ignoring findbugs was introduced. And in [RsPrettyXml](https://github.com/yegor256/takes/blob/master/src/main/java/org/takes/rs/RsPrettyXml.java) the new lock was introduced synchronizing on boolean variable lock:

```java
/**
* Synchronization lock.
*/
private final Boolean lock;
```

which violates another rule from findbugs: [DL_SYNCHRONIZATION_ON_BOOLEAN](http://findbugs.sourceforge.net/bugDescriptions.html#DL_SYNCHRONIZATION_ON_BOOLEAN) (that was not seen as previous findBugs supressions didn't mention that and it was introduced in exact commit when findbugs started to be completely ignored).

That is a possibility that someone will held the lock on Boolean.TRUE object which will possibly made code vulnerable.

**Comment by 0crat** [comment]
@yegor256 please, pay attention to this issue

**Comment by yegor256** [comment]
@rultor release, tag is `1.6.1`

**Comment by 0crat** [comment]
Oops! Job `gh:yegor256/takes#747` was not in scope
