### ISSUE TITLE
Split to modules

### ISSUE THREAD

**Issue by g4s8** [yegor256/takes#750]
Takes framework can be split into few modules (projects):
1. API module with base interfaces such as `Take`, `Fork`, `Request`, `Response` etc
2. Core module (depends on API) with main classes required in any web app: `FkRegex`, `RqHref`, decorators etc
3. All other stuff (depends on API) like github login, cookies encryption, gzipping content, etc can be moved to additional plugin modules - one module for one task

In such way Takes can be transformed from repository to GH organization.

It allows to develop and maintain custom modules, replace existing with own implementation,
also it will decrease complexity of web-app because not used modules will not be included.

**Comment by 0crat** [comment]
@yegor256 please, pay attention to this issue

**Comment by yegor256** [comment]
@g4s8 it is a rather small framework... I always thought that fewer artifacts is better. I don't really like huge frameworks with dozens of dependencies, which nobody can understand how to put together :) BTW, you're talking about Java 9 modules?

**Comment by g4s8** [comment]
@yegor256 you're right - small is better. But Takes can grow into one big monolithic artifact because it doesn't cover some web+http aspects at moment which most probably will be included later. For instance it can include cache-control, etags, internationalization with language tags, versioning and many other. If all this features are included, Takes will become a huge framework. To develop and maintain many small projects is better than one and big, as for me.

I think this modules will not bring lack of understanding into project, because at this moment situation is same, some parts of Takes are not well documented, e.g. auth part with `Pass`: if I hadn't read your post about cookie-auth I would not understand how it works. This auth part can be moved into new project with own readme and docs.

I didn't mean java9 modules when I was posting this issue, but I think it can be so.

**Comment by yegor256** [comment]
@g4s8 this transition will happen naturally, in the future. At the moment the framework is still small and its user base is not too big. Let's wait until it really starts to grow.
