### ISSUE TITLE
sonarcloud

### ISSUE THREAD

**Issue by yegor256** [yegor256/takes#751]
Let's integrate

**Comment by yegor256** [comment]
@rultor release, tag is `1.7.1`

**Comment by yegor256** [comment]
@rultor release, tag is `1.7.1`

**Comment by yegor256** [comment]
@rultor release, tag is `1.7.1`

**Comment by yegor256** [comment]
@rultor release, tag is `1.7.1`

**Comment by 0crat** [comment]
Oops! Job `gh:yegor256/takes#751` was not in scope
