### ISSUE TITLE
sonarcloud complains

### ISSUE THREAD

**Issue by yegor256** [yegor256/takes#753]
Let's fix them: https://sonarcloud.io/project/issues?id=org.takes%3Atakes&open=AV8XZgDkNjpKv9tuZnxi&resolved=false&types=BUG

**Comment by 0crat** [comment]
Job `gh:yegor256/takes#753` assigned to @yegor256, please go ahead ([policy](http://datum.zerocracy.com/pages/policy.html)).

**Comment by 0crat** [comment]
Bug was reported: +15 points just awarded to @yegor256, total is [+5075](http://www.0crat.com/u/yegor256).

**Comment by 0crat** [comment]
Manual assignment of issues is discouraged, see par.19: -5 points just awarded to @yegor256, total is [+5075](http://www.0crat.com/u/yegor256).

**Comment by 0crat** [comment]
Job `gh:yegor256/takes#753` is now out of scope.

**Comment by 0crat** [comment]
Order was successfully finished: +30 points just awarded to @yegor256, total is [+5135](http://www.0crat.com/u/yegor256).
