### ISSUE TITLE
Review note: use standard DCL pattern on top of volatile or final holder

### ISSUE THREAD

**Issue by vladimir-bukhtoyarov** [yegor256/takes#754]
In this line lock acquires every time
https://github.com/yegor256/takes/blob/6e4575f00f0b63baacd4b36aa47fcaefd8eaf411/src/main/java/org/takes/rq/form/RqFormBase.java#L129

It is better to eliminate the lock via stadard DCL paradigm

**Comment by paulodamaso** [comment]
@0crat in

**Comment by 0crat** [comment]
> @0crat in ([here](https://github.com/yegor256/takes/issues/754#issuecomment-430469593))

@paulodamaso Job [#754](https://github.com/yegor256/takes/issues/754) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
> @0crat in ([here](https://github.com/yegor256/takes/issues/754#issuecomment-430469593))

@paulodamaso Thanks for your contribution, @vladimir-bukhtoyarov[/z](https://www.0crat.com/u/vladimir-bukhtoyarov)! If you would be a member of [the project](https://www.0crat.com/p/C3FFK3YAY), you would now earn +15 reputation points, as explained in [§29](http://www.zerocracy.com/policy.html#29). You can join and apply to it, see [§2](http://www.zerocracy.com/policy.html#2).

**Comment by vladimir-bukhtoyarov** [comment]
@0crat thanks for advance, but I am very busy with my own projects and have no plans to work enywhere else.

**Comment by 0crat** [comment]
The job [#754](https://github.com/yegor256/takes/issues/754) assigned to @ypshenychka[/z](https://www.0crat.com/u/ypshenychka), here is [why](https://www.0crat.com/footprint/C3FFK3YAY/22a5e002-34fd-4824-bdff-2c0776636a50); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be a monetary reward for this job

**Comment by ypshenychka** [comment]
@0crat refuse

**Comment by 0crat** [comment]
> @0crat refuse ([here](https://github.com/yegor256/takes/issues/754#issuecomment-437974174))

@ypshenychka The user @ypshenychka[/z](https://www.0crat.com/u/ypshenychka) resigned from [#754](https://github.com/yegor256/takes/issues/754), please stop working. Reason for job resignation: Order was cancelled

**Comment by 0crat** [comment]
Tasks refusal is discouraged, see [§6](http://www.zerocracy.com/policy.html#6): -15 point(s) just awarded to @ypshenychka[/z](https://www.0crat.com/u/ypshenychka)

**Comment by 0crat** [comment]
Job `gh:yegor256/takes#754` is not assigned, can't get performer

**Comment by 0crat** [comment]
The job [#754](https://github.com/yegor256/takes/issues/754) is now out of scope

**Comment by ypshenychka** [comment]
@paulodamaso Noone actually worked on this issue, right?

**Comment by ypshenychka** [comment]
@paulodamaso ping

**Comment by paulodamaso** [comment]
@ypshenychka right, no one touched this

**Comment by ypshenychka** [comment]
@paulodamaso thanks!

**Comment by ypshenychka** [comment]
@0crat quality bad

**Comment by 0crat** [comment]
> @0crat quality bad ([here](https://github.com/yegor256/takes/issues/754#issuecomment-440232437))

@ypshenychka There is no quality review for [#754](https://github.com/yegor256/takes/issues/754), no performer
