### ISSUE TITLE
broken tests PsCookieTest, TsAuthTest, RsFlashTest 

### ISSUE THREAD

**Issue by dmzaytsev** [yegor256/takes#76]
build project fails when system's default locale is ru_RU.

"java.lang.IllegalArgumentException: header line of HTTP response "Set-Cookie: foo=urn%3Atest%3A99;Path=/;Expires=Пт, 27 мар 2015 00:34:57 GMT" doesn't match "[a-zA-Z\-]+:\p{Print}+" regular expression, but it should, according to RFC 7230"

Caused by using  locale specific's date format in PsCookie.exit

**Comment by yegor256** [comment]
@davvd this is definitely a bug

**Comment by davvd** [comment]
> @davvd this is definitely a bug

@yegor256 got it, tag `bug` is here

**Comment by davvd** [comment]
@d-molotchko it's your task now, the budget is **30 mins**, go ahead

**Comment by davvd** [comment]
@dmzaytsev thanks for the ticket, your account was topped for 15 mins, payment 54211899

**Comment by dmzaytsev** [comment]
@d-molotchko thanks!

**Comment by krzyk** [comment]
@yegor256 could you release new version of takes with this fix?

**Comment by yegor256** [comment]
@rultor release, tag is `0.11.2`

**Comment by davvd** [comment]
@d-molotchko I'm not sure who actually completed this task, since there were no messages from you above (correct me if I'm wrong)

**Comment by d-molotchko** [comment]
@davvd I completed this task

**Comment by yegor256** [comment]
@d-molotchko in the future, always post a short message into the ticket, explaining where you fixed the problem (in what pull request) and what exactly was done

**Comment by yegor256** [comment]
@davvd please add extra 30 mins to @d-molotchko

**Comment by d-molotchko** [comment]
@yegor256 ok

**Comment by davvd** [comment]
> @davvd please add extra 30 mins to @d-molotchko 

@yegor256 I've paid 30 mins to @d-molotchko in transaction `54668412`
