### ISSUE TITLE
Write unit tests or servlet support classes

### ISSUE THREAD

**Issue by t-izbassar** [yegor256/takes#763]
Write unit tests to that #682 issue in that #762 PR

**Comment by 0crat** [comment]
[@yegor256](http://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by 0crat** [comment]
Job `gh:yegor256/takes#763` is not assigned, can't get start time

**Comment by 0crat** [comment]
Job [#763](https://github.com/yegor256/takes/issues/763) was not in scope
