### ISSUE TITLE
Write integration test for servlet support

### ISSUE THREAD

**Issue by t-izbassar** [yegor256/takes#764]
Need to prove that #682 is working. Relates to #762 PR

**Comment by 0crat** [comment]
[@yegor256](http://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by 0crat** [comment]
Job `gh:yegor256/takes#764` is not assigned, can't get start time

**Comment by 0crat** [comment]
Job [#764](https://github.com/yegor256/takes/issues/764) was not in scope
