### ISSUE TITLE
Use Cookie from Servlet interface

### ISSUE THREAD

**Issue by t-izbassar** [yegor256/takes#765]
According to #682 task and #762 PR SvRequestWrap and SvResponseWrap probably should use Cookie from HttpServlet spec.

**Comment by 0crat** [comment]
[@yegor256](http://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by 0crat** [comment]
Job `gh:yegor256/takes#765` is not assigned, can't get start time

**Comment by 0crat** [comment]
Job [#765](https://github.com/yegor256/takes/issues/765) was not in scope
