### ISSUE TITLE
Servlet Support in Takes should able to route requests

### ISSUE THREAD

**Issue by t-izbassar** [yegor256/takes#766]
According to this #682 task and to #762 implementation `AbstractTakesServlet` should create `Fork` instead of takes so it will support routing from HttpServletRequest

**Comment by 0crat** [comment]
[@yegor256](http://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by 0crat** [comment]
Job `gh:yegor256/takes#766` is not assigned, can't get start time

**Comment by 0crat** [comment]
Job [#766](https://github.com/yegor256/takes/issues/766) was not in scope
