### ISSUE TITLE
Document ServletSupport

### ISSUE THREAD

**Issue by t-izbassar** [yegor256/takes#767]
We should document servlet support in README.md according to this #682 task and #762 PR.

**Comment by 0crat** [comment]
[@yegor256](http://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by 0crat** [comment]
Job `gh:yegor256/takes#767` is not assigned, can't get start time

**Comment by 0crat** [comment]
Job [#767](https://github.com/yegor256/takes/issues/767) was not in scope
