### ISSUE TITLE
SSL dispatching

### ISSUE THREAD

**Issue by yegor256** [yegor256/takes#769]
Let's make it possible to dispatch incoming traffic by the scheme of their URIs.

**Comment by 0crat** [comment]
Job [#769](https://github.com/yegor256/takes/issues/769) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
The job [#769](https://github.com/yegor256/takes/issues/769) assigned to @yegor256[/z](http://www.0crat.com/u/yegor256). The budget is 30 minutes, see [§4](http://datum.zerocracy.com/pages/policy.html#4). Please, read [§8](http://datum.zerocracy.com/pages/policy.html#8) and [§9](http://datum.zerocracy.com/pages/policy.html#9). If the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html).

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://datum.zerocracy.com/pages/policy.html#29): +15 points just awarded to @yegor256[/z](http://www.0crat.com/u/yegor256), total is [+7670](http://www.0crat.com/u/yegor256)

**Comment by 0crat** [comment]
Manual assignment of issues is discouraged, see [§19](http://datum.zerocracy.com/pages/policy.html#19): -5 points just awarded to @yegor256[/z](http://www.0crat.com/u/yegor256), total is [+7670](http://www.0crat.com/u/yegor256)

**Comment by 0crat** [comment]
It is strongly discouraged to assign jobs to their creators, see [§19](http://datum.zerocracy.com/pages/policy.html#19): -15 points just awarded to @yegor256[/z](http://www.0crat.com/u/yegor256), total is [+7670](http://www.0crat.com/u/yegor256)

**Comment by 0crat** [comment]
Order was successfully finished: +30 points just awarded to @yegor256[/z](http://www.0crat.com/u/yegor256), total is [+7700](http://www.0crat.com/u/yegor256)

**Comment by 0crat** [comment]
The job [#769](https://github.com/yegor256/takes/issues/769) is now out of scope

**Comment by 0crat** [comment]
Job [#769](https://github.com/yegor256/takes/issues/769) was not in scope
