### ISSUE TITLE
Seems  argument check missing in Href.path

### ISSUE THREAD

**Issue by dmzaytsev** [yegor256/takes#77]
Href.path uses Href.encode(suffix)
A result of this new Href("http://example.com").path("e/f")
return "http://example.com/e%2Ff"

Is method path allows single path to add?
If so, it should throws InvalidArgumentException in case multiple path. Is not it?

**Comment by yegor256** [comment]
@dmzaytsev why `/` should be treated differently than other symbols? say, I have this:

```
String dob = "27/11/1987";
Href href = new Href("http://example.com").path("dob").path(dob);
```

I'm expecting this: `http://example.com/dob/27%2F11%2F1987`

**Comment by dmzaytsev** [comment]
String dob = "/27/11/1987";
    Href href = new Href("http://example.com").path("dob").path(dob);

Should return `http://example.com/dob/%2F27%2F11%2F1987` 
or `http://example.com/dob/27%2F11%2F1987` ?

**Comment by yegor256** [comment]
`http://example.com/dob/%2F27%2F11%2F1987`

**Comment by dmzaytsev** [comment]
@yegor256 ok, thanks
