### ISSUE TITLE
AbstractHmHeader<T>#matchesSafely(T) should be revised

### ISSUE THREAD

**Issue by simonjenga** [yegor256/takes#770]
The method: ```org.takes.facets.hamcrest.AbstractHmHeader.matchesSafely(T)``` may have a condition
check that may not be needed. Is the following check really necessary?

```
if (headers.hasNext()) {
    headers.next();
}
```

The JUnit test's for the concrete implementation of this ```abstract``` class pass without any error!

**Comment by paulodamaso** [comment]
@0crat in

**Comment by paulodamaso** [comment]
@simonjenga The code moved from `org.takes.facets.hamcrest.AbstractHmHeader.matchesSafely(T)` to `org.takes.facets.hamcrest.HmHeader.matchesSafely(T)`

**Comment by 0crat** [comment]
> @0crat in ([here](https://github.com/yegor256/takes/issues/770#issuecomment-430474440))

@paulodamaso Job [#770](https://github.com/yegor256/takes/issues/770) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
> @0crat in ([here](https://github.com/yegor256/takes/issues/770#issuecomment-430474440))

@paulodamaso Thanks for your contribution, @simonjenga[/z](https://www.0crat.com/u/simonjenga)! If you would be a member of [the project](https://www.0crat.com/p/C3FFK3YAY), you would now earn +15 reputation points, as explained in [§29](http://www.zerocracy.com/policy.html#29). You can join and apply to it, see [§2](http://www.zerocracy.com/policy.html#2).

**Comment by 0crat** [comment]
The job [#770](https://github.com/yegor256/takes/issues/770) assigned to @ypshenychka[/z](https://www.0crat.com/u/ypshenychka), here is [why](https://www.0crat.com/footprint/C3FFK3YAY/5837e848-3536-4bd6-b1ad-ec2cee1d5103); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be a monetary reward for this job

**Comment by ypshenychka** [comment]
@0crat refuse

**Comment by 0crat** [comment]
> @0crat refuse ([here](https://github.com/yegor256/takes/issues/770#issuecomment-437974486))

@ypshenychka The user @ypshenychka[/z](https://www.0crat.com/u/ypshenychka) resigned from [#770](https://github.com/yegor256/takes/issues/770), please stop working. Reason for job resignation: Order was cancelled

**Comment by 0crat** [comment]
Tasks refusal is discouraged, see [§6](http://www.zerocracy.com/policy.html#6): -15 point(s) just awarded to @ypshenychka[/z](https://www.0crat.com/u/ypshenychka)

**Comment by simonjenga** [comment]
@paulodamaso Ok

**Comment by paulodamaso** [comment]
@simonjenga Could you please close the issue then?

**Comment by simonjenga** [comment]
@paulodamaso The original abstract class ```AbstractHmHeader``` was changed to become a concrete class ```HmHeader``` and that is OK. However, the method ```matchesSafely(T)``` still has the following condition check:
```
if (headers.hasNext()) {
    headers.next();
}
```
Is this check really needed? It should be removed.
When this check is removed from the method, the JUnit Test for this class pass without any error:

 ```../takes>mvn -Dtest=HmHeaderTest test```

:point_down: 
```
[INFO]
[INFO] --- maven-compiler-plugin:3.6.0:testCompile (default-testCompile) @ takes ---
[INFO] Nothing to compile - all classes are up to date
[INFO]
[INFO] --- maven-surefire-plugin:2.19.1:test (default-test) @ takes ---

-------------------------------------------------------
 T E S T S
-------------------------------------------------------
Running org.takes.facets.hamcrest.HmHeaderTest
Tests run: 7, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.25 sec - in org.takes.facets.hamcrest.HmHeaderTest
Picked up JAVA_TOOL_OPTIONS: -Dfile.encoding=UTF-8

Results :

Tests run: 7, Failures: 0, Errors: 0, Skipped: 0

[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
```

**Comment by 0crat** [comment]
The job [#770](https://github.com/yegor256/takes/issues/770) assigned to @olenagerasimova[/z](https://www.0crat.com/u/olenagerasimova), here is [why](https://www.0crat.com/footprint/C3FFK3YAY/78522e33-7038-4d31-9ae8-db2faf1fe450); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be a monetary reward for this job

**Comment by olenagerasimova** [comment]
@simonjenga done in PR #878, please close

**Comment by simonjenga** [comment]
@olenagerasimova OK!

**Comment by 0crat** [comment]
@ypshenychka[/z](https://www.0crat.com/u/ypshenychka) please review this job completed by @olenagerasimova[/z](https://www.0crat.com/u/olenagerasimova), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by 0crat** [comment]
The job [#770](https://github.com/yegor256/takes/issues/770) is now out of scope

**Comment by ypshenychka** [comment]
@0crat quality good

**Comment by 0crat** [comment]
Order was finished, quality is "good": +35 point(s) just awarded to @olenagerasimova[/z](https://www.0crat.com/u/olenagerasimova)

**Comment by 0crat** [comment]
Quality review completed: +8 point(s) just awarded to @ypshenychka[/z](https://www.0crat.com/u/ypshenychka)
