### ISSUE TITLE
Hello World! with Takes fails to start and launch from the command line

### ISSUE THREAD

**Issue by simonjenga** [yegor256/takes#774]
The following class works:
```
public final class HelloWorld {
    public static void main(final String... args) throws Exception {
        System.out.println("hello, world!");
    }
}
```

To compile and execute:
```
C:\javaworkspace\HelloWorldTakes>javac HelloWorld.java
Picked up JAVA_TOOL_OPTIONS: -Dfile.encoding=UTF-8

C:\javaworkspace\HelloWorldTakes>java HelloWorld
Picked up JAVA_TOOL_OPTIONS: -Dfile.encoding=UTF-8
hello, world!
```

The following class does not work:
```
import org.takes.http.Exit;
import org.takes.http.FtBasic;
import org.takes.facets.fork.FkRegex;
import org.takes.facets.fork.TkFork;

public final class HelloTakes {
    public static void main(final String... args) throws Exception {
        new FtBasic(
            new TkFork(new FkRegex("/", "hello, world!")), 8080
        ).start(Exit.NEVER);
    }
}
```

To compile and execute:
```
C:\javaworkspace\HelloWorldTakes>javac -cp takes-2.0-SNAPSHOT.jar HelloTakes.java
Picked up JAVA_TOOL_OPTIONS: -Dfile.encoding=UTF-8

C:\javaworkspace\HelloWorldTakes>java -Dfile.encoding=UTF-8 -cp takes-2.0-SNAPSHOT.jar:. HelloTakes
Picked up JAVA_TOOL_OPTIONS: -Dfile.encoding=UTF-8
Error: Could not find or load main class HelloTakes
```

The class works okay when launching and starting from the Eclipse IDE.
This is very strange and my CLASSPATH enviroment vaiables seems to be set OK.

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by yegor256** [comment]
@simonjenga I don't think it's relevant to Takes. It's something with the way you compile Java and execute it. Try StackOverflow instead.

**Comment by 0crat** [comment]
Job `gh:yegor256/takes#774` is not assigned, can't get start time

**Comment by 0crat** [comment]
Job [#774](https://github.com/yegor256/takes/issues/774) was not in scope

**Comment by simonjenga** [comment]
@yegor256 The command provided to execute is OS-dependent. In this case the command provided is for executing on all Unix-like operating systems. That is why it does not work on Windows operating systems.

http://stackoverflow.com/a/4528456/645270

https://stackoverflow.com/questions/18093928/what-does-could-not-find-or-load-main-class-mean

The command to execute on Windows bases systems is:
```java -Dfile.encoding=UTF-8 -cp takes-2.0-SNAPSHOT.jar;. App```
