### ISSUE TITLE
Auth0 authentication

### ISSUE THREAD

**Issue by piotrkot** [yegor256/takes#775]
Is it possible to use [auth0](https://auth0.com) authentication in takes?
If yes, can you please give some guidelines?

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by yegor256** [comment]
@piotrkot not at the moment, but you can contribute with a pull request.

**Comment by paulodamaso** [comment]
@yegor256 Do you think that this is a valuable feature?

**Comment by piotrkot** [comment]
@yegor256 @paulodamaso FYI I managed without this feature.

**Comment by paulodamaso** [comment]
@piotrkot So if it's not needed anymore please close the issue

**Comment by 0crat** [comment]
Job `gh:yegor256/takes#775` is not assigned, can't get performer

**Comment by 0crat** [comment]
This job is not in scope
