### ISSUE TITLE
OutputStream in RsPrint may fail to flush() incase of IOException

### ISSUE THREAD

**Issue by simonjenga** [yegor256/takes#778]
The current implementation of the methods in ```org.takes.rs.RsPrint``` should be wrapped by a ```try-finally``` block to ensure that the ```OutputStream``` makes a call the ```#flush()``` method incase of an ```IOException```.

This will ensure that data held in the ```OutputStream``` before the ```Exception``` happened is written out to their intended destination.

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by 0crat** [comment]
Job [#778](https://github.com/yegor256/takes/issues/778) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
The job [#778](https://github.com/yegor256/takes/issues/778) assigned to @t-izbassar[/z](https://www.0crat.com/u/t-izbassar), here is [why](https://www.0crat.com/footprint/C3FFK3YAY/531241701). The budget is 30 minutes, see [§4](http://datum.zerocracy.com/pages/policy.html#4). Please, read [§8](http://datum.zerocracy.com/pages/policy.html#8) and [§9](http://datum.zerocracy.com/pages/policy.html#9). If the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html).

**Comment by t-izbassar** [comment]
@simonjenga I have doubts that we really need this. If exception is happened you need to deal with exception. Can you provide a case where it might be useful?

**Comment by simonjenga** [comment]
@t-izbassar The ticket describes the possible scenario we may encounter. If you have doubts that we really need this, inform the PM that nothing needs to be done here so we can close this ticket otherwise the code ```try-finally``` is not much to do. I have seen your test case above!

**Comment by t-izbassar** [comment]
@simonjenga I have a feeling that this is violating the 0/100 principle. For example, we have putted 100 bytes to buffer, but with other 100 bytes it is throwing an exception. Do we want to have partial files with incomplete bytes written?

Yes, I've added that. However, simple `try-finally` do not gives the result as `StreamEncoder` for example will not flush if `write` is failed. It's closing internal cache - thus leading to the point, when there is no interactions with `flush()` method at all on `OutputStream`. You can close this issue if you agree with my first paragraph. Otherwise - I will create PR. Just confirm your decision. There is no PM needed for that.

**Comment by simonjenga** [comment]
@t-izbassar Agreed with first paragraph; but just create PR.

**Comment by t-izbassar** [comment]
@simonjenga can you close this one? #809 was merged, and relevant issue #812 was also created to cover what was left from implementation.

**Comment by 0crat** [comment]
@t-izbassar[/z](https://www.0crat.com/u/t-izbassar) this job was assigned to you 5 days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by t-izbassar** [comment]
@simonjenga ping

**Comment by t-izbassar** [comment]
@yegor256 I believe this one can be closed as result is delivered. @simonjenga seem to be absent.

**Comment by simonjenga** [comment]
@t-izbassar Am present! Result is delivered OK :100:

**Comment by 0crat** [comment]
@elenavolokhova[/z](https://www.0crat.com/u/elenavolokhova) please review this job, as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by t-izbassar** [comment]
@simonjenga thanks!

**Comment by elenavolokhova** [comment]
@0crat quality good

**Comment by 0crat** [comment]
`QA` review completed: +8 points just awarded to @elenavolokhova[/z](https://www.0crat.com/u/elenavolokhova), total is [+123](https://www.0crat.com/u/elenavolokhova)

**Comment by 0crat** [comment]
Order was finished, quality was "good": +35 points just awarded to @t-izbassar[/z](https://www.0crat.com/u/t-izbassar), total is [+500](https://www.0crat.com/u/t-izbassar)

**Comment by 0crat** [comment]
> @0crat quality good ([here](https://github.com/yegor256/takes/issues/778#issuecomment-369297727))

@elenavolokhova The job [#778](https://github.com/yegor256/takes/issues/778) is now out of scope

**Comment by 0pdd** [comment]
@simonjenga the only puzzle [#812](https://github.com/yegor256/takes/issues/812) is solved here.

**Comment by simonjenga** [comment]
@0pdd OK!
