### ISSUE TITLE
TkRedirect should carry on the query and the fragment

### ISSUE THREAD

**Issue by yegor256** [yegor256/takes#779]
When I'm doing this:

```
Response rsp = new TkRedirect("http://www.google.com/abc?b=2").act(
  new RqFake("GET", "/hi?a=1#test")
);
```

The `Location` header in the response should be equal to:

```
http://www.google.com/abc?b=2&a=1#test
```

At the moment it is equal to:

```
http://www.google.com/abc?b=2
```

**Comment by 0crat** [comment]
Job [#779](https://github.com/yegor256/takes/issues/779) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://datum.zerocracy.com/pages/policy.html#29): +15 points just awarded to @yegor256[/z](https://www.0crat.com/u/yegor256), total is [+8785](https://www.0crat.com/u/yegor256)

**Comment by yegor256** [comment]
@0crat assign @neonailol

**Comment by 0crat** [comment]
> @0crat assign @neonailol ([here](https://github.com/yegor256/takes/issues/779#issuecomment-361261098))

@yegor256 The job [#779](https://github.com/yegor256/takes/issues/779) assigned to @neonailol[/z](https://www.0crat.com/u/neonailol). The budget is 30 minutes, see [§4](http://datum.zerocracy.com/pages/policy.html#4). Please, read [§8](http://datum.zerocracy.com/pages/policy.html#8) and [§9](http://datum.zerocracy.com/pages/policy.html#9). If the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html).

**Comment by 0crat** [comment]
Manual assignment of issues is discouraged, see [§19](http://datum.zerocracy.com/pages/policy.html#19): -5 points just awarded to @yegor256[/z](https://www.0crat.com/u/yegor256), total is [+8780](https://www.0crat.com/u/yegor256)

**Comment by 0crat** [comment]
@neonailol[/z](https://www.0crat.com/u/neonailol) this job was assigned to you 5 days ago. It will be taken away from you soon, unless you close it, see [§8](http://datum.zerocracy.com/pages/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by neonailol** [comment]
@0crat waiting

**Comment by 0crat** [comment]
> @0crat waiting ([here](https://github.com/yegor256/takes/issues/779#issuecomment-362821649))

@neonailol The impediment for [#779](https://github.com/yegor256/takes/issues/779) was registered successfully by @neonailol[/z](https://www.0crat.com/u/neonailol)

**Comment by 0crat** [comment]
I can't do it for technical reasons, I'm very sorry.  If you don't know what to do,  submit this error as a ticket  [here](https://github.com/zerocracy/farm/issues): 

```
 1.0-SNAPSHOT 28f476b8 2018-02-09T12:00:38
IllegalStateException: java.lang.reflect.InvocationTargetException in com/zerocracy/stk/pm/cost/make_payment.groovy
java.lang.IllegalStateException: java.lang.reflect.InvocationTargetException in com/zerocracy/stk/pm/cost/make_payment.groovy
	at com.zerocracy.farm.reactive.StkGroovy.process(StkGroovy.java:125)
	at com.zerocracy.farm.StkSafe.process(StkSafe.java:89)
	at com.zerocracy.farm.reactive.StkSmart.process(StkSmart.java:66)
	at com.zerocracy.farm.reactive.Brigade.process(Brigade.java:82)
	at com.zerocracy.farm.reactive.Brigade.lambda$apply$0(Brigade.java:64)
	at org.cactoos.func.UncheckedFunc.lambda$apply$0(UncheckedFunc.java:58)
	at org.cactoos.scalar.IoCheckedScalar.value(IoCheckedScalar.java:70)
	at org.cactoos.scalar.UncheckedScalar.value(UncheckedScalar.java:58)
	at org.cactoos.func.UncheckedFunc.apply(UncheckedFunc.java:59)
	at org.cactoos.iterator.Filtered.hasNext(Filtered.java:90)
	at org.cactoos.iterator.LengthOf.lambda$new$0(LengthOf.java:52)
	at org.cactoos.scalar.IoCheckedScalar.value(IoCheckedScalar.java:70)
	at org.cactoos.scalar.UncheckedScalar.value(UncheckedScalar.java:58)... 
```

Cc @yegor256[/z](https://www.0crat.com/u/yegor256)

**Comment by 0crat** [comment]
Order was successfully finished: +30 points just awarded to @neonailol[/z](https://www.0crat.com/u/neonailol), total is [+495](https://www.0crat.com/u/neonailol)

**Comment by 0crat** [comment]
The job [#779](https://github.com/yegor256/takes/issues/779) is now out of scope
