### ISSUE TITLE
Condition.java:36-41: Implement Condition.Range that...

### ISSUE THREAD

**Issue by 0pdd** [yegor256/takes#780]
The puzzle `218-f14916a5` from #218 has to be resolved:

https://github.com/yegor256/takes/blob/38616bd926905daa347289b3243854fcce4d98e3/src/main/java/org/takes/misc/Condition.java#L36-L41

The puzzle was created by rultor on 29-Jan-18. 

Estimate: 30 minutes, role: IMP.

If you have any technical questions, don't ask me, submit new tickets instead. The task will be "done" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by 0crat** [comment]
Job [#780](https://github.com/yegor256/takes/issues/780) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
The job [#780](https://github.com/yegor256/takes/issues/780) assigned to @t-izbassar[/z](https://www.0crat.com/u/t-izbassar), here is [why](https://www.0crat.com/footprint/C3FFK3YAY/452354518). The budget is 30 minutes, see [§4](http://datum.zerocracy.com/pages/policy.html#4). Please, read [§8](http://datum.zerocracy.com/pages/policy.html#8) and [§9](http://datum.zerocracy.com/pages/policy.html#9). If the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html).

**Comment by 0crat** [comment]
@t-izbassar[/z](https://www.0crat.com/u/t-izbassar) this job was assigned to you 5 days ago. It will be taken away from you soon, unless you close it, see [§8](http://datum.zerocracy.com/pages/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by t-izbassar** [comment]
@0crat waiting

**Comment by 0crat** [comment]
> @0crat waiting ([here](https://github.com/yegor256/takes/issues/780#issuecomment-366874910))

@t-izbassar The impediment for [#780](https://github.com/yegor256/takes/issues/780) was registered successfully by @t-izbassar[/z](https://www.0crat.com/u/t-izbassar)

**Comment by t-izbassar** [comment]
@0pdd fixed in #801.

**Comment by 0pdd** [comment]
The puzzle `218-f14916a5` has disappeared from the source code, that's why I closed this issue.

**Comment by 0crat** [comment]
@elenavolokhova[/z](https://www.0crat.com/u/elenavolokhova) please review this job, as in [§30](http://datum.zerocracy.com/pages/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by elenavolokhova** [comment]
@0crat quality good.

**Comment by 0crat** [comment]
> @0crat quality good. ([here](https://github.com/yegor256/takes/issues/780#issuecomment-367598829))

@elenavolokhova Argument "good." doesn't match regex `good|bad|acceptable`

**Comment by elenavolokhova** [comment]
@0crat quality good

**Comment by 0crat** [comment]
> @0crat quality good ([here](https://github.com/yegor256/takes/issues/780#issuecomment-367600167))

@elenavolokhova There is an unrecoverable failure on my side. Please, submit it [here](https://github.com/zerocracy/farm/issues):

```
com.zerocracy.farm.reactive.StkGroovy[125] java.lang.IllegalStateException: java.lang.reflect.InvocationTargetException in com/zerocracy/stk/pm/cost/make_payment.groovy
sun.reflect.GeneratedMethodAccessor403[-1] java.lang.reflect.InvocationTargetException: null
com.zerocracy.pmo.banks.Paypal[122] java.io.IOException: Failed to pay $4.00 to elena.volokhova87@gmail.com with memo "Payment for gh:yegor256/takes#780 (15 minutes): QA review completed": java.io.IOException Failed to pay through PayPal: [ERROR APPLICATION The email account Receiver not in receive money enabled country is based in a country that isn't enabled to receive payments]
com.zerocracy.pmo.banks.Paypal[202] java.io.IOException: Failed to pay through PayPal: [ERROR APPLICATION The email account Receiver not in receive money enabled country is based in a country that isn't enabled to receive payments]
```

[1.0-SNAPSHOT](https://github.com/zerocracy/farm/tree/1.0-SNAPSHOT) /cc @yegor256

**Comment by 0crat** [comment]
QA review completed: +15 points just awarded to @elenavolokhova[/z](https://www.0crat.com/u/elenavolokhova), total is [+75](https://www.0crat.com/u/elenavolokhova)

**Comment by 0crat** [comment]
Order was finished, quality was "good": +35 points just awarded to @t-izbassar[/z](https://www.0crat.com/u/t-izbassar), total is [+380](https://www.0crat.com/u/t-izbassar)

**Comment by 0crat** [comment]
> @0crat quality good ([here](https://github.com/yegor256/takes/issues/780#issuecomment-367600167))

@elenavolokhova You can't do that, unless you have one of these roles: `ARC`, `PO`. Your current roles are: QA.

**Comment by 0crat** [comment]
The job [#780](https://github.com/yegor256/takes/issues/780) assigned to @t-izbassar[/z](https://www.0crat.com/u/t-izbassar), here is [why](https://www.0crat.com/footprint/C3FFK3YAY/530831418). The budget is 30 minutes, see [§4](http://datum.zerocracy.com/pages/policy.html#4). Please, read [§8](http://datum.zerocracy.com/pages/policy.html#8) and [§9](http://datum.zerocracy.com/pages/policy.html#9). If the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html).

**Comment by t-izbassar** [comment]
@0crat status

**Comment by 0crat** [comment]
> @0crat status ([here](https://github.com/yegor256/takes/issues/780#issuecomment-367610668))

@t-izbassar This is what I know about this job, as in [§32](http://datum.zerocracy.com/pages/policy.html#32):

  * The job [#780](https://github.com/yegor256/takes/issues/780) is [in scope](http://datum.zerocracy.com/pages/policy.html#14) for 24days
  * The role is `DEV`
  * The job is assigned to @t-izbassar[/z](https://www.0crat.com/u/t-izbassar) for [29min](http://datum.zerocracy.com/pages/policy.html#8)
  * There is a monetary reward attached
  * @t-izbassar[/z](https://www.0crat.com/u/t-izbassar) will get 50% of their hourly rate for this job
  * The job doesn't have any [impediments](http://datum.zerocracy.com/pages/policy.html#9)
  * The [budget](http://datum.zerocracy.com/pages/policy.html#4) is 30 minutes/points
  * These users are banned and won't be assigned:
    * @0pdd[/z](https://www.0crat.com/u/0pdd): This user reported the ticket
  * Job [footprint](https://www.0crat.com/footprint/C3FFK3YAY?q=%7Bjob%3A%27gh%3Ayegor256%2Ftakes%23780%27%7D) (restricted area)

**Comment by t-izbassar** [comment]
@0crat waiting

**Comment by t-izbassar** [comment]
@yegor256 can you resign this job? It is already done and it's eating 33% of my agenda.

**Comment by 0crat** [comment]
> @0crat waiting ([here](https://github.com/yegor256/takes/issues/780#issuecomment-367611434))

@t-izbassar The impediment for [#780](https://github.com/yegor256/takes/issues/780) was registered successfully by @t-izbassar[/z](https://www.0crat.com/u/t-izbassar)

**Comment by yegor256** [comment]
@0crat refuse

**Comment by 0crat** [comment]
> @0crat refuse ([here](https://github.com/yegor256/takes/issues/780#issuecomment-367665871))

@yegor256 The user @t-izbassar[/z](https://www.0crat.com/u/t-izbassar) resigned from [#780](https://github.com/yegor256/takes/issues/780), please stop working

**Comment by yegor256** [comment]
@0crat щге

**Comment by 0crat** [comment]
> @0crat out ([here](https://github.com/yegor256/takes/issues/780#issuecomment-367707514))

@yegor256 The job [#780](https://github.com/yegor256/takes/issues/780) is now out of scope

**Comment by 0pdd** [comment]
@0pdd the only puzzle [#806](https://github.com/yegor256/takes/issues/806) is solved here.
