### ISSUE TITLE
Back.java:38-40: Document usage of Back interface in...

### ISSUE THREAD

**Issue by 0pdd** [yegor256/takes#782]
The puzzle `373-5aec50f1` from #373 has to be resolved:

https://github.com/yegor256/takes/blob/db5df10a3e25863ca91e456e17e16a6810c357c8/src/main/java/org/takes/http/Back.java#L38-L40

The puzzle was created by Tolegen Izbassar on 26-Jan-18. 

Estimate: 15 minutes, role: IMP.

If you have any technical questions, don't ask me, submit new tickets instead. The task will be "done" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by 0crat** [comment]
Job [#782](https://github.com/yegor256/takes/issues/782) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
The job [#782](https://github.com/yegor256/takes/issues/782) assigned to @t-izbassar[/z](https://www.0crat.com/u/t-izbassar), here is [why](https://www.0crat.com/footprint/C3FFK3YAY/520833923). The budget is 30 minutes, see [§4](http://datum.zerocracy.com/pages/policy.html#4). Please, read [§8](http://datum.zerocracy.com/pages/policy.html#8) and [§9](http://datum.zerocracy.com/pages/policy.html#9). If the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html).

**Comment by t-izbassar** [comment]
@0pdd implemented in #807

**Comment by 0crat** [comment]
@t-izbassar[/z](https://www.0crat.com/u/t-izbassar) this job was assigned to you 5 days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by 0pdd** [comment]
The puzzle `373-5aec50f1` has disappeared from the source code, that's why I closed this issue.

**Comment by 0crat** [comment]
@elenavolokhova[/z](https://www.0crat.com/u/elenavolokhova) please review this job, as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by elenavolokhova** [comment]
@0crat quality good

**Comment by 0crat** [comment]
`QA` review completed: +8 points just awarded to @elenavolokhova[/z](https://www.0crat.com/u/elenavolokhova), total is [+99](https://www.0crat.com/u/elenavolokhova)

**Comment by 0crat** [comment]
Order was finished, quality was "good": +35 points just awarded to @t-izbassar[/z](https://www.0crat.com/u/t-izbassar), total is [+430](https://www.0crat.com/u/t-izbassar)

**Comment by 0crat** [comment]
> @0crat quality good ([here](https://github.com/yegor256/takes/issues/782#issuecomment-368753813))

@elenavolokhova The job [#782](https://github.com/yegor256/takes/issues/782) is now out of scope
