### ISSUE TITLE
Create Base interface for Request and Response

### ISSUE THREAD

**Issue by t-izbassar** [yegor256/takes#784]
`Request` and `Response` are interfaces with same methods. We can introduce additional interfaces:
```
public interface Head {
    Iterable<String> head() throws IOException;
}

public interface Body {
    InputStream body() throws IOException;
}
```

With that we can rewrite `Request` and `Response` in this way:
```
public interface Request extends Head, Body {
}

public interface Response extends Head, Body {
}
```

This might be useful for example for `AbstractHmHeader` that could be rewritten as follows:
```
public final HmHeader<T extends Head> extends TypeSafeMatcher<T> {
    // relevant methods
}
```

The difference is that we don't need `HmRsHeader` and `HmRqHeader` classes anymore as we can use `head` method directly in `HmHeader`. Those classes are duplicates of each other and they just provide `head` method which can be used directly if we have those base classes. There also might be other use cases for that.

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by 0crat** [comment]
Job [#784](https://github.com/yegor256/takes/issues/784) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://datum.zerocracy.com/pages/policy.html#29): +15 points just awarded to @t-izbassar[/z](https://www.0crat.com/u/t-izbassar), total is [+90](https://www.0crat.com/u/t-izbassar)

**Comment by 0crat** [comment]
The job [#784](https://github.com/yegor256/takes/issues/784) assigned to @paulodamaso[/z](https://www.0crat.com/u/paulodamaso), here is [why](https://www.0crat.com/footprint/C3FFK3YAY/2440054063); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be a monetary reward for this job

**Comment by paulodamaso** [comment]
@0crat wait for #845 review

**Comment by 0crat** [comment]
> @0crat wait for #845 review ([here](https://github.com/yegor256/takes/issues/784#issuecomment-419720427))

@paulodamaso The impediment for [#784](https://github.com/yegor256/takes/issues/784) was registered successfully by @paulodamaso[/z](https://www.0crat.com/u/paulodamaso)

**Comment by 0crat** [comment]
The architect of the project has changed; @yegor256[/z](https://www.0crat.com/u/yegor256) is not at this role anymore; @paulodamaso[/z](https://www.0crat.com/u/paulodamaso) is the architect now

**Comment by paulodamaso** [comment]
@t-izbassar Merged, please close

**Comment by 0crat** [comment]
The job [#784](https://github.com/yegor256/takes/issues/784) is now out of scope
