### ISSUE TITLE
HmRqHeader and HmRsHeader constructors violate the rule about primary constructor

### ISSUE THREAD

**Issue by t-izbassar** [yegor256/takes#786]
I believe we should have only one primary constructor in `AbstractHmHeader`:

```
protected AbstractHmHeader(final Matcher<String> hdrm,
        final Matcher<Iterable<String>> vlm) {
        super();
        this.header = hdrm;
        this.value = vlm;
    }
```

Other constructors should be removed. And we should construct parent by having supplementary constructors in childs.

```
public HmRqHeader(final Matcher<String> hdrm, final Matcher<String> vlm) {
        super(hdrn, vlm);
    }
```

Other constructors in `HmRqHeader` should delegate construction to this primary one:

```
public HmRqHeader(final String hdr, final Matcher<String> vlm) {
    this(Matchers.equalToIgnoringCase(hdr), vlm);
}
```

Same should be applicable for `HmRsHeader`.

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by 0crat** [comment]
Job [#786](https://github.com/yegor256/takes/issues/786) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://datum.zerocracy.com/pages/policy.html#29): +15 points just awarded to @t-izbassar[/z](https://www.0crat.com/u/t-izbassar), total is [+105](https://www.0crat.com/u/t-izbassar)

**Comment by 0crat** [comment]
The job [#786](https://github.com/yegor256/takes/issues/786) assigned to @paulodamaso[/z](https://www.0crat.com/u/paulodamaso), here is [why](https://www.0crat.com/footprint/C3FFK3YAY/2440063127); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be a monetary reward for this job

**Comment by paulodamaso** [comment]
@0crat wait for #843 merge

**Comment by 0crat** [comment]
> @0crat wait for #843 merge ([here](https://github.com/yegor256/takes/issues/786#issuecomment-419720519))

@paulodamaso The impediment for [#786](https://github.com/yegor256/takes/issues/786) was registered successfully by @paulodamaso[/z](https://www.0crat.com/u/paulodamaso)

**Comment by 0crat** [comment]
The architect of the project has changed; @yegor256[/z](https://www.0crat.com/u/yegor256) is not at this role anymore; @paulodamaso[/z](https://www.0crat.com/u/paulodamaso) is the architect now

**Comment by paulodamaso** [comment]
@t-izbassar Done and merged, please close.
