### ISSUE TITLE
Update dependencies

### ISSUE THREAD

**Issue by t-izbassar** [yegor256/takes#787]
We should update dependencies in the project. There are minor ones in test dependencies and also others regarding xml processing. Check [report](https://www.versioneye.com/user/projects/561a9c5ca193340f2f00110d).

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by 0crat** [comment]
Job [#787](https://github.com/yegor256/takes/issues/787) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://datum.zerocracy.com/pages/policy.html#29): +15 points just awarded to @t-izbassar[/z](https://www.0crat.com/u/t-izbassar), total is [+75](https://www.0crat.com/u/t-izbassar)

**Comment by 0crat** [comment]
The job [#787](https://github.com/yegor256/takes/issues/787) assigned to @neonailol[/z](https://www.0crat.com/u/neonailol), here is [why](https://www.0crat.com/footprint/C3FFK3YAY/790958138); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html)

**Comment by 0crat** [comment]
@neonailol[/z](https://www.0crat.com/u/neonailol) this job was assigned to you 5 days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by neonailol** [comment]
@crat waiting

**Comment by neonailol** [comment]
@0crat waiting

**Comment by 0crat** [comment]
> @0crat waiting ([here](https://github.com/yegor256/takes/issues/787#issuecomment-376402018))

@neonailol The impediment for [#787](https://github.com/yegor256/takes/issues/787) was registered successfully by @neonailol[/z](https://www.0crat.com/u/neonailol)

**Comment by 0crat** [comment]
The architect of the project has changed; @yegor256[/z](https://www.0crat.com/u/yegor256) is not at this role anymore; @paulodamaso[/z](https://www.0crat.com/u/paulodamaso) is the architect now

**Comment by neonailol** [comment]
@paulodamaso is, this issue no longer actual

**Comment by paulodamaso** [comment]
@neonailol thanks

**Comment by 0crat** [comment]
@ypshenychka[/z](https://www.0crat.com/u/ypshenychka) please review this job completed by @neonailol[/z](https://www.0crat.com/u/neonailol), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by 0crat** [comment]
The job [#787](https://github.com/yegor256/takes/issues/787) is now out of scope

**Comment by ypshenychka** [comment]
@0crat quality good

**Comment by 0crat** [comment]
> @0crat quality good ([here](https://github.com/yegor256/takes/issues/787#issuecomment-449544620))

@ypshenychka The project doesn't have enough funds, can't make a payment

**Comment by 0crat** [comment]
> @0crat quality good ([here](https://github.com/yegor256/takes/issues/787#issuecomment-449544620))

@ypshenychka The project doesn't have enough funds, can't make a payment

**Comment by 0crat** [comment]
Order was finished, quality is "good": +35 point(s) just awarded to @neonailol[/z](https://www.0crat.com/u/neonailol)

**Comment by 0crat** [comment]
Quality review completed: +8 point(s) just awarded to @ypshenychka[/z](https://www.0crat.com/u/ypshenychka)
