### ISSUE TITLE
TkFallback methods should be revised and cleaned up

### ISSUE THREAD

**Issue by simonjenga** [yegor256/takes#788]
The current implementation of the methods in ```org.takes.facets.fallback.TkFallback``` is a little verbose and should be revised/cleaned up by introducing some private methods that will take care of the following code repetitions:

```java
TkFallback.error(
    ex, req,
    System.currentTimeMillis() - start
)
```

and:

```java
new RqFallback.Fake(
    req, HttpURLConnection.HTTP_INTERNAL_ERROR,
    TkFallback.error(
        ex, req,
        System.currentTimeMillis() - start
    )
)
```

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by paulodamaso** [comment]
@0crat in

**Comment by 0crat** [comment]
> @0crat in ([here](https://github.com/yegor256/takes/issues/788#issuecomment-442038449))

@paulodamaso Thanks for your contribution, @simonjenga[/z](https://www.0crat.com/u/simonjenga)! If you would be a member of [the project](https://www.0crat.com/p/C3FFK3YAY), you would now earn +15 reputation points, as explained in [§29](http://www.zerocracy.com/policy.html#29). You can join and apply to it, see [§2](http://www.zerocracy.com/policy.html#2).

**Comment by 0crat** [comment]
The job [#788](https://github.com/yegor256/takes/issues/788) assigned to @krzyk[/z](https://www.0crat.com/u/krzyk), here is [why](https://www.0crat.com/footprint/C3FFK3YAY/210c3f07-5fc6-419f-85f6-1786ef0719f8); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be a monetary reward for this job

**Comment by krzyk** [comment]
@0crat wait I'm busy with other tasks

**Comment by 0crat** [comment]
> @0crat wait I'm busy with other tasks ([here](https://github.com/yegor256/takes/issues/788#issuecomment-447599446))

@krzyk The impediment for [#788](https://github.com/yegor256/takes/issues/788) was registered successfully by @krzyk[/z](https://www.0crat.com/u/krzyk)

**Comment by krzyk** [comment]
@simonjenga ping

**Comment by simonjenga** [comment]
@krzyk OK :+1:

**Comment by 0crat** [comment]
@ypshenychka[/z](https://www.0crat.com/u/ypshenychka) please review this job completed by @krzyk[/z](https://www.0crat.com/u/krzyk), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by 0crat** [comment]
The job [#788](https://github.com/yegor256/takes/issues/788) is now out of scope

**Comment by 0crat** [comment]
> @0crat quality good ([here](https://github.com/yegor256/takes/issues/788#issuecomment-450524758))

@ypshenychka The project doesn't have enough funds, can't make a payment

**Comment by 0crat** [comment]
> @0crat quality good ([here](https://github.com/yegor256/takes/issues/788#issuecomment-450524758))

@ypshenychka The project doesn't have enough funds, can't make a payment

**Comment by 0crat** [comment]
Order was finished, quality is "good": +35 point(s) just awarded to @krzyk[/z](https://www.0crat.com/u/krzyk)

**Comment by 0crat** [comment]
Quality review completed: +8 point(s) just awarded to @ypshenychka[/z](https://www.0crat.com/u/ypshenychka)
