### ISSUE TITLE
What is the reason for using Charset.defaultCharset ?

### ISSUE THREAD

**Issue by dmzaytsev** [yegor256/takes#79]
What is the reason for using Charset.defaultCharset instead platform-independed UTF-8 ?
https://github.com/yegor256/takes/search?utf8=%E2%9C%93&q=Charset.defaultCharset%28%29

**Comment by yegor256** [comment]
@davvd it's a valid bug

**Comment by davvd** [comment]
> @davvd it's a valid bug

@yegor256 sure, thanks, I added bug tag to it

**Comment by davvd** [comment]
@yegor256 the task is yours (budget is 30 mins)

**Comment by davvd** [comment]
@dmzaytsev thank you for reporting this, I added 15 mins to your acc, transaction `54248657`

**Comment by yegor256** [comment]
@dmzaytsev check these two commits: f7f548c and 36ad4ad Did I answer the question?

**Comment by dmzaytsev** [comment]
@yegor256 Yes, thank you!

**Comment by davvd** [comment]
@yegor256 Many thanks! **30 mins** were added to your account in Transaction ID `000-e30a67c0` (task took 3 hours and 11 mins); added +30 to your rating, now it is equal to [+9015](http://www.netbout.com/b/35008?open=rating)
