### ISSUE TITLE
Introduce Expires interface

### ISSUE THREAD

**Issue by t-izbassar** [yegor256/takes#791]
Now we have [ExpirationDate](https://github.com/yegor256/takes/blob/master/src/main/java/org/takes/misc/ExpirationDate.java) which is a step towards re-usability. However it can be further improved. I propose to create
```
public interface Expires {
    String print();
}
```

It should print Expires string and we can have useful implementations. We need `Expires.Never` that will print `Expires=Thu, 01 Jan 1970 00:00:00 GMT` and `Expires.Hour` that will print expiration 1 hour after creation and `Expires.Date` that will replace `ExpirationDate`.  

This interface and implementations will be useful in various cases such as: [TkFlash](https://github.com/yegor256/takes/blob/master/src/main/java/org/takes/facets/flash/TkFlash.java) and in [RsFlash](https://github.com/yegor256/takes/blob/master/src/main/java/org/takes/facets/flash/RsFlash.java). There might be other useful usages for this interface.

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by 0crat** [comment]
Job [#791](https://github.com/yegor256/takes/issues/791) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://datum.zerocracy.com/pages/policy.html#29): +15 points just awarded to @t-izbassar[/z](https://www.0crat.com/u/t-izbassar), total is [+135](https://www.0crat.com/u/t-izbassar)

**Comment by 0crat** [comment]
The job [#791](https://github.com/yegor256/takes/issues/791) assigned to @paulodamaso[/z](https://www.0crat.com/u/paulodamaso), here is [why](https://www.0crat.com/footprint/C3FFK3YAY/2451151375); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be a monetary reward for this job

**Comment by 0crat** [comment]
@paulodamaso[/z](https://www.0crat.com/u/paulodamaso) this job was assigned to you 5days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by paulodamaso** [comment]
@0crat wait for #844 merge

**Comment by 0crat** [comment]
> @0crat wait for #844 merge ([here](https://github.com/yegor256/takes/issues/791#issuecomment-419720630))

@paulodamaso The impediment for [#791](https://github.com/yegor256/takes/issues/791) was registered successfully by @paulodamaso[/z](https://www.0crat.com/u/paulodamaso)

**Comment by 0crat** [comment]
The architect of the project has changed; @yegor256[/z](https://www.0crat.com/u/yegor256) is not at this role anymore; @paulodamaso[/z](https://www.0crat.com/u/paulodamaso) is the architect now

**Comment by paulodamaso** [comment]
@t-izbassar Merged, please close

**Comment by 0crat** [comment]
The job [#791](https://github.com/yegor256/takes/issues/791) is now out of scope
