### ISSUE TITLE
Anchor part of query handled incorrectly by `Href`

### ISSUE THREAD

**Issue by neonailol** [yegor256/takes#793]
currently `Href` produces some weird results for links with anchor

### First example test case

```java
MatcherAssert.assertThat(
    new Href("http://example.com/?a=1#hello").toString(),
    Matchers.equalTo("http://example.com/?a=1#hello")
);
```
```log
java.lang.AssertionError: 
Expected: "http://example.com/?a=1#hello"
     but: was "http://example.com/?a=1#h?a=1"
Expected :http://example.com/?a=1#hello
Actual   :http://example.com/?a=1#h?a=1
 <Click to see difference>
```

### Second example test case

```java
URI uri = URI.create("http://example.com/?a=1#hello");
MatcherAssert.assertThat( // This works as intended and produces right string
    uri.toString(),
    Matchers.equalTo("http://example.com/?a=1#hello")
);
MatcherAssert.assertThat(
    new Href(uri.toString()).toString(),
    Matchers.equalTo("http://example.com/?a=1#hello")
);
```
```log
java.lang.AssertionError: 
Expected: "http://example.com/?a=1#hello"
     but: was "http://example.com/?a=1#h?a=1"
Expected :http://example.com/?a=1#hello
Actual   :http://example.com/?a=1#h?a=1
 <Click to see difference>
```

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by 0crat** [comment]
Job [#793](https://github.com/yegor256/takes/issues/793) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://datum.zerocracy.com/pages/policy.html#29): +15 points just awarded to @neonailol[/z](https://www.0crat.com/u/neonailol), total is [+345](https://www.0crat.com/u/neonailol)

**Comment by 0crat** [comment]
The job [#793](https://github.com/yegor256/takes/issues/793) assigned to @t-izbassar[/z](https://www.0crat.com/u/t-izbassar), here is [why](https://www.0crat.com/footprint/C3FFK3YAY/580563151). The budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4). Please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9). If the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html).

**Comment by t-izbassar** [comment]
@neonailol I believe this one can be closed, as PR #797 was merged to fix an issue.

**Comment by 0crat** [comment]
@elenavolokhova[/z](https://www.0crat.com/u/elenavolokhova) please review this job, as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by elenavolokhova** [comment]
@0crat quality good

**Comment by 0crat** [comment]
`QA` review completed: +8 points just awarded to @elenavolokhova[/z](https://www.0crat.com/u/elenavolokhova), total is [+115](https://www.0crat.com/u/elenavolokhova)

**Comment by 0crat** [comment]
Order was finished, quality was "good": +35 points just awarded to @t-izbassar[/z](https://www.0crat.com/u/t-izbassar), total is [+465](https://www.0crat.com/u/t-izbassar)

**Comment by 0crat** [comment]
> @0crat quality good ([here](https://github.com/yegor256/takes/issues/793#issuecomment-369127491))

@elenavolokhova The job [#793](https://github.com/yegor256/takes/issues/793) is now out of scope
