### ISSUE TITLE
AbstractHmBody.java:43-58: Right now we can only check...

### ISSUE THREAD

**Issue by 0pdd** [yegor256/takes#794]
The puzzle `485-ca1df145` from #485 has to be resolved:

https://github.com/yegor256/takes/blob/a98eb9681cd67703409dc0637dba93766676941a/src/main/java/org/takes/facets/hamcrest/AbstractHmBody.java#L43-L58

The puzzle was created by rultor on 09-Feb-18. 

Estimate: 30 minutes, role: IMP.

If you have any technical questions, don't ask me, submit new tickets instead. The task will be "done" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by 0crat** [comment]
Job [#794](https://github.com/yegor256/takes/issues/794) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
The job [#794](https://github.com/yegor256/takes/issues/794) assigned to @t-izbassar[/z](https://www.0crat.com/u/t-izbassar), here is [why](https://www.0crat.com/footprint/C3FFK3YAY/591356080). The budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4). Please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9). If the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html).

**Comment by t-izbassar** [comment]
@0pdd partially done in #813. Left puzzle to address what was left.

**Comment by t-izbassar** [comment]
@0crat waiting for #813 to be merged

**Comment by 0crat** [comment]
> @0crat waiting for #813 to be merged ([here](https://github.com/yegor256/takes/issues/794#issuecomment-370240536))

@t-izbassar The impediment for [#794](https://github.com/yegor256/takes/issues/794) was registered successfully by @t-izbassar[/z](https://www.0crat.com/u/t-izbassar)

**Comment by 0pdd** [comment]
The puzzle `485-ca1df145` has disappeared from the source code, that's why I closed this issue.

**Comment by 0crat** [comment]
@elenavolokhova[/z](https://www.0crat.com/u/elenavolokhova) please review this job, as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by elenavolokhova** [comment]
@0crat quality good

**Comment by 0crat** [comment]
> @0crat quality good ([here](https://github.com/yegor256/takes/issues/794#issuecomment-370687329))

@elenavolokhova You can't do that, unless you have one of these roles: `ARC`, `PO`. Your current roles are: `QA`.

**Comment by 0crat** [comment]
`QA` review completed: +8 points just awarded to @elenavolokhova[/z](https://www.0crat.com/u/elenavolokhova)

**Comment by 0crat** [comment]
Order was finished, quality was "good": +35 points just awarded to @t-izbassar[/z](https://www.0crat.com/u/t-izbassar)

**Comment by 0crat** [comment]
> @0crat quality good ([here](https://github.com/yegor256/takes/issues/794#issuecomment-370687329))

@elenavolokhova The job [#794](https://github.com/yegor256/takes/issues/794) is now out of scope

**Comment by 0pdd** [comment]
@0pdd 2 puzzles [#819](https://github.com/yegor256/takes/issues/819), [#859](https://github.com/yegor256/takes/issues/859) are still not solved; solved: [#820](https://github.com/yegor256/takes/issues/820).

**Comment by 0pdd** [comment]
@0pdd the puzzle [#819](https://github.com/yegor256/takes/issues/819) is still not solved; solved: [#820](https://github.com/yegor256/takes/issues/820), [#859](https://github.com/yegor256/takes/issues/859).

**Comment by 0pdd** [comment]
@0pdd all 3 puzzles are solved here: [#819](https://github.com/yegor256/takes/issues/819), [#820](https://github.com/yegor256/takes/issues/820), [#859](https://github.com/yegor256/takes/issues/859).
