### ISSUE TITLE
org.takes.misc.Href design issues

### ISSUE THREAD

**Issue by g4s8** [yegor256/takes#798]
`Href` class has a lot of code in constructors and many `private static` methods.
According to 
http://www.yegor256.com/2015/05/07/ctors-must-be-code-free.html 
and 
http://www.yegor256.com/2017/02/07/private-method-is-new-class.html 
this class should be refactored.

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by yegor256** [comment]
@g4s8 of course, it can be refactored, but it is so small and so focused, that it would be an overkill to create 3-4 new classes, just to parse the strings. I think its design is OK the way it is. We can't make each and every class perfect, just because it's Java.

**Comment by 0crat** [comment]
Job `gh:yegor256/takes#798` is not assigned, can't get start time

**Comment by 0crat** [comment]
Job [#798](https://github.com/yegor256/takes/issues/798) was not in scope
