### ISSUE TITLE
FtRemoteTest.java:55-58: Fix FtRemote for empty response...

### ISSUE THREAD

**Issue by 0pdd** [yegor256/takes#800]
The puzzle `730-80b57821` from #730 has to be resolved:

https://github.com/yegor256/takes/blob/f355160ca04157276b88e7aac57aaceeb4a016c4/src/test/java/org/takes/http/FtRemoteTest.java#L55-L58

The puzzle was created by Izbassar Tolegen on 13-Feb-18. 

Estimate: 30 minutes, role: IMP.

If you have any technical questions, don't ask me, submit new tickets instead. The task will be "done" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by 0crat** [comment]
Job [#800](https://github.com/yegor256/takes/issues/800) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
The job [#800](https://github.com/yegor256/takes/issues/800) assigned to @paulodamaso[/z](https://www.0crat.com/u/paulodamaso), here is [why](https://www.0crat.com/footprint/C3FFK3YAY/2451156593); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be a monetary reward for this job

**Comment by paulodamaso** [comment]
@yegor256 There is nothing wrong with `FtRemote` class; it is indeed returning an empty body. The problem is that `RsPrint` prints both `head` and `body` to the output string:
```
    public void print(final OutputStream output) throws IOException {
        this.printHead(output);
        this.printBody(output);
    }
```
So the aforementioned test will never be true, because 
```
new JdkRequest(home)
                        .method("POST")
                        .body().set("returnsAnEmptyResponseBody").back()
                        .fetch()
                        .body()
```
from `TkEmpty()` will never return a empty String.

Is this he expected behavior of `RsPrint` or it should be fixed?

**Comment by paulodamaso** [comment]
@yegor256 I need some definitions in this one, please take a look.

**Comment by paulodamaso** [comment]
@yegor256 ping

**Comment by 0crat** [comment]
@paulodamaso[/z](https://www.0crat.com/u/paulodamaso) this job was assigned to you 5days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by paulodamaso** [comment]
@0crat refuse due inactivity

**Comment by 0crat** [comment]
> @0crat refuse due inactivity ([here](https://github.com/yegor256/takes/issues/800#issuecomment-420125428))

@paulodamaso The user @paulodamaso[/z](https://www.0crat.com/u/paulodamaso) resigned from [#800](https://github.com/yegor256/takes/issues/800), please stop working. Reason for job resignation: Order was cancelled

**Comment by 0crat** [comment]
Tasks refusal is discouraged, see [§6](http://www.zerocracy.com/policy.html#6): -15 point(s) just awarded to @paulodamaso[/z](https://www.0crat.com/u/paulodamaso)

**Comment by 0crat** [comment]
The job [#800](https://github.com/yegor256/takes/issues/800) assigned to @paulodamaso[/z](https://www.0crat.com/u/paulodamaso), here is [why](https://www.0crat.com/footprint/C3FFK3YAY/2541342124); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be a monetary reward for this job

**Comment by paulodamaso** [comment]
@yegor256 please answer https://github.com/yegor256/takes/issues/800#issuecomment-418177938 so I can finish this task; I've already tried to refuse it, but 0crat assigned it back to me, so I need that you answer the question so I can move on resolving it.

**Comment by paulodamaso** [comment]
@yegor256 ping

**Comment by paulodamaso** [comment]
@yegor256 ping

**Comment by yegor256** [comment]
@paulodamaso why asking me? It's not my puzzle. Just remove the puzzle, if you think it's wrong and call it a day. Otherwise, ask its author.

**Comment by paulodamaso** [comment]
@yegor256 You're the `ARC`, so I thought that this kind of decision are your call. @t-izbassar please take a look to https://github.com/yegor256/takes/issues/800#issuecomment-418177938

**Comment by yegor256** [comment]
@paulodamaso it will be my call if the author of the puzzle doesn't reply. In that case, refer to me. But it's better to just submit a PR with your own opinion/code. Again, like I said, if you don't like the task/puzzle, just remove it from the code.

**Comment by paulodamaso** [comment]
@yegor256 thanks for the answer. @t-izbassar please take a look at this, comment https://github.com/yegor256/takes/issues/800#issuecomment-418177938

**Comment by paulodamaso** [comment]
@0crat wait for https://github.com/yegor256/takes/issues/800#issuecomment-418177938 answer

**Comment by paulodamaso** [comment]
@t-izbassar please take a look at this

**Comment by 0crat** [comment]
> @0crat wait for https://github.com/yegor256/takes/issues/800#issuecomment-418177938 answer ([here](https://github.com/yegor256/takes/issues/800#issuecomment-423023653))

@paulodamaso The impediment for [#800](https://github.com/yegor256/takes/issues/800) was registered successfully by @paulodamaso[/z](https://www.0crat.com/u/paulodamaso)

**Comment by paulodamaso** [comment]
@t-izbassar ping

**Comment by t-izbassar** [comment]
@paulodamaso `RsPrint` is used exactly for printing head and body. I don't understand what you want to achieve. Not to print head?

**Comment by t-izbassar** [comment]
@paulodamaso the problem is that when you use `TkEmpty` then you expect to receive empty body, but that's not the case. I think you are misunderstanding the client request from server response. The server response should be with empty body.

> .body().set("returnsAnEmptyResponseBody").back()

This line set's clients request, not server's response.

**Comment by paulodamaso** [comment]
@t-izbassar Yes, it set the request to be sent to `TkEmpty()`, I was meant that. `TkEmpty` indeed sends the correct body (""), but it is changed in `RsPrint`, and this makes that we will never ever have an empty body in this case because we have header and body being sent in this request.

I don't think that it would be a wise thing to change this behavior because this class is used in `BkBase`, which is used in a lot of other back-end classes. Besides that I don't think that this behavior is wrong: after all the `HTTP` response is a just one big String with header and body tied one to another, so our `RsPrint` implementation shouldn't be different.

So I've changed the test so it does not fails anymore.

**Comment by paulodamaso** [comment]
@0crat wait for https://github.com/yegor256/takes/pull/855 merge

**Comment by 0crat** [comment]
> @0crat wait for https://github.com/yegor256/takes/pull/855 merge ([here](https://github.com/yegor256/takes/issues/800#issuecomment-423605828))

@paulodamaso Job [#800](https://github.com/yegor256/takes/issues/800) is already on hold

**Comment by 0crat** [comment]
The architect of the project has changed; @yegor256[/z](https://www.0crat.com/u/yegor256) is not at this role anymore; @paulodamaso[/z](https://www.0crat.com/u/paulodamaso) is the architect now

**Comment by paulodamaso** [comment]
@0crat refuse

**Comment by 0crat** [comment]
> @0crat refuse ([here](https://github.com/yegor256/takes/issues/800#issuecomment-429497639))

@paulodamaso The user @paulodamaso[/z](https://www.0crat.com/u/paulodamaso) resigned from [#800](https://github.com/yegor256/takes/issues/800), please stop working. Reason for job resignation: Order was cancelled

**Comment by 0crat** [comment]
Tasks refusal is discouraged, see [§6](http://www.zerocracy.com/policy.html#6): -15 point(s) just awarded to @paulodamaso[/z](https://www.0crat.com/u/paulodamaso)

**Comment by 0crat** [comment]
@victornoel[/z](https://www.0crat.com/u/victornoel) this job was assigned to you 5days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by victornoel** [comment]
@0crat wait for #868 to be reviewed and merged

**Comment by 0crat** [comment]
> @0crat wait for #868 to be reviewed and merged ([here](https://github.com/yegor256/takes/issues/800#issuecomment-439680658))

@victornoel The impediment for [#800](https://github.com/yegor256/takes/issues/800) was registered successfully by @victornoel[/z](https://www.0crat.com/u/victornoel)

**Comment by 0pdd** [comment]
The puzzle `730-80b57821` has disappeared from the source code, that's why I closed this issue.

**Comment by 0pdd** [comment]
@0pdd the puzzle [#869](https://github.com/yegor256/takes/issues/869) is still not solved.

**Comment by 0crat** [comment]
@elenavolokhova[/z](https://www.0crat.com/u/elenavolokhova) please review this job completed by @victornoel[/z](https://www.0crat.com/u/victornoel), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by 0crat** [comment]
The job [#800](https://github.com/yegor256/takes/issues/800) is now out of scope

**Comment by elenavolokhova** [comment]
@0crat quality good

**Comment by 0crat** [comment]
Order was finished, quality is "good": +35 point(s) just awarded to @victornoel[/z](https://www.0crat.com/u/victornoel)

**Comment by 0pdd** [comment]
@0pdd the only puzzle [#869](https://github.com/yegor256/takes/issues/869) is solved here.
