### ISSUE TITLE
FkHitRefresh.java:246-248: `null` constant usage in the...

### ISSUE THREAD

**Issue by 0pdd** [yegor256/takes#802]
The puzzle `744-7f6a14c2` from #744 has to be resolved:

https://github.com/yegor256/takes/blob/326d41e2cc024b588786b9ff24272cef8c2219ba/src/main/java/org/takes/facets/fork/FkHitRefresh.java#L246-L248

The puzzle was created by Kapralov Sergey on 15-Feb-18. 

Estimate: 30 minutes, role: IMP.

If you have any technical questions, don't ask me, submit new tickets instead. The task will be "done" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by 0crat** [comment]
Job [#802](https://github.com/yegor256/takes/issues/802) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
The job [#802](https://github.com/yegor256/takes/issues/802) assigned to @g4s8[/z](https://www.0crat.com/u/g4s8), here is [why](https://www.0crat.com/footprint/C3FFK3YAY/2471842523); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be a monetary reward for this job

**Comment by 0crat** [comment]
The architect of the project has changed; @yegor256[/z](https://www.0crat.com/u/yegor256) is not at this role anymore; @paulodamaso[/z](https://www.0crat.com/u/paulodamaso) is the architect now

**Comment by paulodamaso** [comment]
@0crat assign marceloamadeu

**Comment by paulodamaso** [comment]
@0crat assign @marceloamadeu

**Comment by 0crat** [comment]
> @0crat assign @marceloamadeu ([here](https://github.com/yegor256/takes/issues/802#issuecomment-448195575))

@paulodamaso The job [#802](https://github.com/yegor256/takes/issues/802) assigned to @marceloamadeu[/z](https://www.0crat.com/u/marceloamadeu), here is [why](https://www.0crat.com/footprint/C3FFK3YAY/66e7df43-cc7c-4c0c-b601-9b17e25786bb); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be no monetary reward for this job

**Comment by marceloamadeu** [comment]
@0crat wait

**Comment by 0crat** [comment]
> @0crat wait ([here](https://github.com/yegor256/takes/issues/802#issuecomment-450355494))

@marceloamadeu The impediment for [#802](https://github.com/yegor256/takes/issues/802) was registered successfully by @marceloamadeu[/z](https://www.0crat.com/u/marceloamadeu)

**Comment by 0pdd** [comment]
The puzzle `744-7f6a14c2` has disappeared from the source code, that's why I closed this issue.

**Comment by 0pdd** [comment]
@0pdd the puzzle [#935](https://github.com/yegor256/takes/issues/935) is still not solved.

**Comment by 0crat** [comment]
@ypshenychka[/z](https://www.0crat.com/u/ypshenychka) please review this job completed by @marceloamadeu[/z](https://www.0crat.com/u/marceloamadeu), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by 0crat** [comment]
The job [#802](https://github.com/yegor256/takes/issues/802) is now out of scope

**Comment by marceloamadeu** [comment]
@ypshenychka I did not have time to solve it and it took me a long time. I will do my best to prevent this from happening again.

**Comment by ypshenychka** [comment]
@marceloamadeu Thanks. Next time please provide the reason when saying "wait" to 0crat.

**Comment by ypshenychka** [comment]
@0crat quality acceptable
