### ISSUE TITLE
Condition.java:37-39: Bring Cactoos dependency to the...

### ISSUE THREAD

**Issue by 0pdd** [yegor256/takes#806]
The puzzle `780-9da18957` from #780 has to be resolved:

https://github.com/yegor256/takes/blob/c0fc037b05e5478bc3f028f50dcc7d81fbe69547/src/main/java/org/takes/misc/Condition.java#L37-L39

The puzzle was created by Izbassar Tolegen on 16-Feb-18. 

Estimate: 30 minutes, role: IMP.

If you have any technical questions, don't ask me, submit new tickets instead. The task will be "done" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by 0crat** [comment]
Job [#806](https://github.com/yegor256/takes/issues/806) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
Thanks for your contribution, @0pdd[/z](https://www.0crat.com/u/0pdd)! If you would be a member of [the project](https://www.0crat.com/p/C3FFK3YAY), you would now earn +15 reputation points, as explained in [§29](http://datum.zerocracy.com/pages/policy.html#29). You can join and apply to it, see [§2](http://datum.zerocracy.com/pages/policy.html#2).

**Comment by 0crat** [comment]
The job [#806](https://github.com/yegor256/takes/issues/806) assigned to @paulodamaso[/z](https://www.0crat.com/u/paulodamaso), here is [why](https://www.0crat.com/footprint/C3FFK3YAY/2491956449); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be a monetary reward for this job

**Comment by 0crat** [comment]
@paulodamaso[/z](https://www.0crat.com/u/paulodamaso) this job was assigned to you 5days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by paulodamaso** [comment]
@0crat wait for https://github.com/yegor256/takes/issues/849 review and merge

**Comment by 0crat** [comment]
> @0crat wait for https://github.com/yegor256/takes/issues/849 review and merge ([here](https://github.com/yegor256/takes/issues/806#issuecomment-420422904))

@paulodamaso The impediment for [#806](https://github.com/yegor256/takes/issues/806) was registered successfully by @paulodamaso[/z](https://www.0crat.com/u/paulodamaso)

**Comment by 0crat** [comment]
The architect of the project has changed; @yegor256[/z](https://www.0crat.com/u/yegor256) is not at this role anymore; @paulodamaso[/z](https://www.0crat.com/u/paulodamaso) is the architect now

**Comment by 0pdd** [comment]
The puzzle `780-9da18957` has disappeared from the source code, that's why I closed this issue.

**Comment by 0crat** [comment]
The job [#806](https://github.com/yegor256/takes/issues/806) is now out of scope

**Comment by 0crat** [comment]
Order was finished: +30 point(s) just awarded to @paulodamaso[/z](https://www.0crat.com/u/paulodamaso)
