### ISSUE TITLE
Move to Java 8

### ISSUE THREAD

**Issue by t-izbassar** [yegor256/takes#808]
It's already Java 9 released and Java 8 is a go to java version. With Java 8 we can implement `Take` interface just in place with Lambdas:
```java
new FtBasic(
    req -> new RsTest("Hello, world!");
).start(Exit.NEVER);
```

I don't think that supporting java 7 is relevant nowadays. Many libs and frameworks already moved to Java 8. It will be more attractive, if we had Java 8. Of course this framework can be used within java 8, but official support is still important. And also the fact that Cactoos is Java 8 based will in fact leave us with no choice.

In terms of implementation: the codebase should be build with Java 8 (`jdk.version` property in maven) and also the `README.md` should mention that it is Java 8 framework. We can adopt Java 8 features lately in appropriate places.

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by 0crat** [comment]
Job [#808](https://github.com/yegor256/takes/issues/808) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 points just awarded to @t-izbassar[/z](https://www.0crat.com/u/t-izbassar), total is [+395](https://www.0crat.com/u/t-izbassar)

**Comment by krzyk** [comment]
@yegor256 I could take this

**Comment by 0crat** [comment]
The job [#808](https://github.com/yegor256/takes/issues/808) assigned to @paulodamaso[/z](https://www.0crat.com/u/paulodamaso), here is [why](https://www.0crat.com/footprint/C3FFK3YAY/2491965548); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be a monetary reward for this job

**Comment by 0crat** [comment]
@paulodamaso[/z](https://www.0crat.com/u/paulodamaso) this job was assigned to you 5days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by paulodamaso** [comment]
@0crat wait for #848 merge

**Comment by 0crat** [comment]
> @0crat wait for #848 merge ([here](https://github.com/yegor256/takes/issues/808#issuecomment-422008612))

@paulodamaso The impediment for [#808](https://github.com/yegor256/takes/issues/808) was registered successfully by @paulodamaso[/z](https://www.0crat.com/u/paulodamaso)

**Comment by 0crat** [comment]
The architect of the project has changed; @yegor256[/z](https://www.0crat.com/u/yegor256) is not at this role anymore; @paulodamaso[/z](https://www.0crat.com/u/paulodamaso) is the architect now

**Comment by 0crat** [comment]
The job [#808](https://github.com/yegor256/takes/issues/808) is now out of scope
