### ISSUE TITLE
Codacy Quality Review do not recognize Matcher.asserThat in junit tests

### ISSUE THREAD

**Issue by t-izbassar** [yegor256/takes#810]
There is Codacy, configured for the Takes project. However, it does not see assertions from hamcrest. If you look at [know issues](https://app.codacy.com/app/github_90/takes/issues/index?&filters=W3siaWQiOiJDYXRlZ29yeSIsInZhbHVlcyI6WyJDb2RlIFN0eWxlIl19XQ==) by Codacy there are 384 issues. And most of them telling that
> JUnit tests should include assert() or fail()

That's why many PRs showing that they have failing Codacy build, as we using asserts from Hamcrest, not the junit ones. This is just pointless noise in PR, so I propose to:
* Either fix Codacy, so that it will respect the assertions from hamcrest
* Or delete Codacy check from PRs as it seems to be redundant. We already have all necessary checks done by Qulice and Travis and AppVeyor builds should be enough.

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by yegor256** [comment]
@t-izbassar how can we "fix Codacy"?

**Comment by t-izbassar** [comment]
@yegor256 I'm not sure, maybe this check can be disabled or differently configured in codacy check. Actually, I think that's in not useful so much as it shows not the real problem so I personally don't even try to look and see why their build is red. But you can decide to leave it as it is.

**Comment by 0crat** [comment]
Job [#810](https://github.com/yegor256/takes/issues/810) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 points just awarded to @t-izbassar[/z](https://www.0crat.com/u/t-izbassar)

**Comment by 0crat** [comment]
> @0crat out ([here](https://github.com/yegor256/takes/issues/810#issuecomment-430476108))

@paulodamaso Job `gh:yegor256/takes#810` is not assigned, can't get performer

**Comment by 0crat** [comment]
> @0crat out ([here](https://github.com/yegor256/takes/issues/810#issuecomment-430476108))

@paulodamaso The job [#810](https://github.com/yegor256/takes/issues/810) is now out of scope

**Comment by paulodamaso** [comment]
@t-izbassar may you close this one? We'll let this as is until codacy fixes the problem on their side.

**Comment by paulodamaso** [comment]
@t-izbassar ping

**Comment by t-izbassar** [comment]
@paulodamaso I don't expect Codacy to fix the problem on their side. If you ok with the PR noise from pointless red build then feel free to close this issue.

**Comment by 0crat** [comment]
Job `gh:yegor256/takes#810` is not assigned, can't get performer

**Comment by 0crat** [comment]
This job is not in scope
