### ISSUE TITLE
Internal link to the Request Methods header is broken in README

### ISSUE THREAD

**Issue by imcaizheng** [yegor256/takes#811]
```
- [Request Methods (POST, PUT, HEAD, etc.)](#request-methods)
```
does not link to
```
## Request Methods (POST, PUT, HEAD, etc.)
```
Either change `#request-methods` to `request-methods-post-put-head-etc`
or shrink the header to `Request Methods` and it should works.

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by yegor256** [comment]
@imcaizheng fixed, thanks
