### ISSUE TITLE
AbstractHmBody.java:43-45: Current implementation of...

### ISSUE THREAD

**Issue by 0pdd** [yegor256/takes#820]
The puzzle `794-9c47f19f` from #794 has to be resolved:

https://github.com/yegor256/takes/blob/7fb524155b180e8eb35d63545e10d20ab614eb5e/src/main/java/org/takes/facets/hamcrest/AbstractHmBody.java#L43-L45

The puzzle was created by rultor on 05-Mar-18. 

Estimate: 30 minutes, role: DEV.

If you have any technical questions, don't ask me, submit new tickets instead. The task will be "done" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by 0crat** [comment]
Job [#820](https://github.com/yegor256/takes/issues/820) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
The job [#820](https://github.com/yegor256/takes/issues/820) assigned to @paulodamaso[/z](https://www.0crat.com/u/paulodamaso), here is [why](https://www.0crat.com/footprint/C3FFK3YAY/2610656453); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be a monetary reward for this job

**Comment by paulodamaso** [comment]
@0crat wait for merge of #852

**Comment by 0crat** [comment]
> @0crat wait for merge of #852  ([here](https://github.com/yegor256/takes/issues/820#issuecomment-423607084))

@paulodamaso The impediment for [#820](https://github.com/yegor256/takes/issues/820) was registered successfully by @paulodamaso[/z](https://www.0crat.com/u/paulodamaso)

**Comment by 0crat** [comment]
The architect of the project has changed; @yegor256[/z](https://www.0crat.com/u/yegor256) is not at this role anymore; @paulodamaso[/z](https://www.0crat.com/u/paulodamaso) is the architect now

**Comment by 0pdd** [comment]
The puzzle `794-9c47f19f` has disappeared from the source code, that's why I closed this issue.

**Comment by 0crat** [comment]
The job [#820](https://github.com/yegor256/takes/issues/820) is now out of scope

**Comment by 0crat** [comment]
Order was finished: +30 point(s) just awarded to @paulodamaso[/z](https://www.0crat.com/u/paulodamaso)
