### ISSUE TITLE
CcAes issues

### ISSUE THREAD

**Issue by g4s8** [yegor256/takes#821]
`CcAes` generates random `IV` and use it for all requests to encrypt identity cookie. It produces two issues:

1. On server restart old cookies becomes invalid because `IV` regenerated, and all users need re-login.
2. It has some security issues: https://security.stackexchange.com/a/1097

Suggestion:
I'd make IV random for each request and add it to cookie (because IV doesn't need to be a secret [by design](https://en.wikipedia.org/wiki/Block_cipher_modes_of_operation#Initialization_vector_.28IV.29)), it prevents any data leakage. Also I'd append HMAC of whole cookie value, including IV and encrypted data, it prevents encrypted text modification attacks.
So cookie structure may look like this:
```
[-----IV----][---aes(src)---][---hmac(IV+aes(src))---]
```

**Comment by 0crat** [comment]
Job [#821](https://github.com/yegor256/takes/issues/821) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 points just awarded to @g4s8[/z](https://www.0crat.com/u/g4s8)

**Comment by yegor256** [comment]
@g4s8 do you want to volunteer here?

**Comment by g4s8** [comment]
@yegor256 yes, I do

**Comment by yegor256** [comment]
@0crat assign @g4s8

**Comment by yegor256** [comment]
@g4s8 thanks!

**Comment by 0crat** [comment]
> @0crat assign @g4s8  ([here](https://github.com/yegor256/takes/issues/821#issuecomment-372770571))

@yegor256 The job [#821](https://github.com/yegor256/takes/issues/821) assigned to @g4s8[/z](https://www.0crat.com/u/g4s8), here is [why](https://www.0crat.com/footprint/C3FFK3YAY/721828555). The budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4). Please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9). If the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html).

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) this job was assigned to you 5 days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by g4s8** [comment]
PR #831 was merged

**Comment by 0crat** [comment]
@elenavolokhova[/z](https://www.0crat.com/u/elenavolokhova) please review this job completed by @g4s8[/z](https://www.0crat.com/u/g4s8), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by 0crat** [comment]
The job [#821](https://github.com/yegor256/takes/issues/821) is now out of scope

**Comment by 0crat** [comment]
The job is not in WBS, won't close the order

**Comment by carlosmiranda** [comment]
@yegor256 is it possible to release this fix? I need it to work with https://github.com/zerocracy/farm/issues/706

**Comment by elenavolokhova** [comment]
@g4s8 According to our Policy:
>Problem reporter and problem solver are two different persons

Please, confirm that you will try to avoid fixing your own issues in future.

**Comment by g4s8** [comment]
@elenavolokhova sure, I confirm

**Comment by elenavolokhova** [comment]
@g4s8 Thanks!

**Comment by elenavolokhova** [comment]
@0crat quality acceptable

**Comment by 0crat** [comment]
Order was finished, quality is "acceptable": +30 points just awarded to @g4s8[/z](https://www.0crat.com/u/g4s8)

**Comment by 0crat** [comment]
Quality review completed: +8 points just awarded to @elenavolokhova[/z](https://www.0crat.com/u/elenavolokhova)

**Comment by carlosmiranda** [comment]
@yegor256 ping, can we have a release of Takes with this fix?

**Comment by yegor256** [comment]
@rultor release, tag is `1.11.2`

**Comment by yegor256** [comment]
@carlosmiranda see 1.11.2
