### ISSUE TITLE
org.takes.misc.Base64 is not working propely

### ISSUE THREAD

**Issue by g4s8** [yegor256/takes#826]
`org.takes.misc.Base64` and `java.util.Base64` has different results for `encode()`:
```groovy
byte[] bytes = [(byte) 31, (byte) -62, (byte) -34, (byte) 101,
             (byte) 0, (byte) -61, (byte) -56, (byte) -112]
assert Arrays.equals(
  java.util.Base64.encoder.encode(bytes),
  new org.takes.misc.Base64().encode(bytes)
)
```
```
assert Arrays.equals( java.util.Base64.encoder.encode(bytes), new org.takes.misc.Base64().encode(bytes) )
              |                        |       |      |       |                           |      |
              false                    |       |      |       |                           |      [31, -62, -34, 101, 0, -61, -56, -112]
                                       |       |      |       |                           [72, 115, 72, 101, 90, 80, 47, 68, 120, 53, 65, 61]
                                       |       |      |       org.takes.misc.Base64@152aa092
                                       |       |      [31, -62, -34, 101, 0, -61, -56, -112]
                                       |       [72, 56, 76, 101, 90, 81, 68, 68, 121, 74, 65, 61]
                                       java.util.Base64$Encoder@1fb700ee
```
Also tested in other languages, result is equal to `java.util.Base64` result.

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by semantosoph** [comment]
This class only exists, because org.takes.misc.Base64 is not available until Java 8. The moment WE switch Java version, it's obsolete.

**Comment by semantosoph** [comment]
Silly me. I meant java.util.Base64 with Java 8.

**Comment by yegor256** [comment]
@semantosoph let's switch to Java 8 (#808) Any volunteers?

**Comment by 0crat** [comment]
Job [#826](https://github.com/yegor256/takes/issues/826) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 points just awarded to @g4s8[/z](https://www.0crat.com/u/g4s8)

**Comment by 0crat** [comment]
The job [#826](https://github.com/yegor256/takes/issues/826) assigned to @krzyk[/z](https://www.0crat.com/u/krzyk), here is [why](https://www.0crat.com/footprint/C3FFK3YAY/2501246456); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be a monetary reward for this job

**Comment by krzyk** [comment]
@0crat waiting for #808

**Comment by 0crat** [comment]
> @0crat waiting for #808 to be completed ([here](https://github.com/yegor256/takes/issues/826#issuecomment-419642086))

@krzyk The impediment for [#826](https://github.com/yegor256/takes/issues/826) was registered successfully by @krzyk[/z](https://www.0crat.com/u/krzyk)

**Comment by 0crat** [comment]
The job [#826](https://github.com/yegor256/takes/issues/826) assigned to @paulodamaso[/z](https://www.0crat.com/u/paulodamaso), here is [why](https://www.0crat.com/footprint/C3FFK3YAY/2772142067); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be a monetary reward for this job

**Comment by 0crat** [comment]
@paulodamaso[/z](https://www.0crat.com/u/paulodamaso) this job was assigned to you 5days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by paulodamaso** [comment]
@0crat wait for #808

**Comment by 0crat** [comment]
> @0crat wait for #808  ([here](https://github.com/yegor256/takes/issues/826#issuecomment-428541417))

@paulodamaso The impediment for [#826](https://github.com/yegor256/takes/issues/826) was registered successfully by @paulodamaso[/z](https://www.0crat.com/u/paulodamaso)

**Comment by 0crat** [comment]
The architect of the project has changed; @yegor256[/z](https://www.0crat.com/u/yegor256) is not at this role anymore; @paulodamaso[/z](https://www.0crat.com/u/paulodamaso) is the architect now

**Comment by paulodamaso** [comment]
@g4s8 merged, please close

**Comment by g4s8** [comment]
@paulodamaso thanks

**Comment by 0crat** [comment]
The job [#826](https://github.com/yegor256/takes/issues/826) is now out of scope

**Comment by 0crat** [comment]
Order was finished: +30 point(s) just awarded to @paulodamaso[/z](https://www.0crat.com/u/paulodamaso)
