### ISSUE TITLE
AbstractHmBody.java:65-67: Right now the describeTo...

### ISSUE THREAD

**Issue by 0pdd** [yegor256/takes#832]
The puzzle `795-077f3980` from #795 has to be resolved:

https://github.com/yegor256/takes/blob/688b1a61c0cdf6aa5922b0be74769d3934744fab/src/main/java/org/takes/facets/hamcrest/AbstractHmBody.java#L65-L67

The puzzle was created by Tolegen Izbassar on 13-Mar-18. 

Estimate: 30 minutes, role: DEV.

If you have any technical questions, don't ask me, submit new tickets instead. The task will be "done" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by 0crat** [comment]
Job [#832](https://github.com/yegor256/takes/issues/832) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
The job [#832](https://github.com/yegor256/takes/issues/832) assigned to @paulodamaso[/z](https://www.0crat.com/u/paulodamaso), here is [why](https://www.0crat.com/footprint/C3FFK3YAY/2772147196); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be a monetary reward for this job

**Comment by 0crat** [comment]
@paulodamaso[/z](https://www.0crat.com/u/paulodamaso) this job was assigned to you 5days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by 0crat** [comment]
The architect of the project has changed; @yegor256[/z](https://www.0crat.com/u/yegor256) is not at this role anymore; @paulodamaso[/z](https://www.0crat.com/u/paulodamaso) is the architect now

**Comment by 0pdd** [comment]
The puzzle `795-077f3980` has disappeared from the source code, that's why I closed this issue.

**Comment by 0crat** [comment]
The job [#832](https://github.com/yegor256/takes/issues/832) is now out of scope

**Comment by 0crat** [comment]
Order was finished: +30 point(s) just awarded to @paulodamaso[/z](https://www.0crat.com/u/paulodamaso)
