### ISSUE TITLE
Some typos in document comments for the org.takes.rs.RsXslt class

### ISSUE THREAD

**Issue by imcaizheng** [yegor256/takes#835]
```
 * <pre> new RsXSLT(
 *   new RsXembly(
 *     new XsStylesheet("/xsl/home.xsl"),
 *     new XsAppend(
 *       "page",
 *       new XsDate(),
 *       new XsLocalhost(),
 *       new XsSLA()
 *     )
 *   )
 * )</pre>
```
`Xs` should be `Xe`.

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by 0crat** [comment]
@imcaizheng[/z](https://www.0crat.com/u/imcaizheng) this project will fix the problem faster if you donate a few dollars to it; just [click here](https://www.0crat.com/contrib/C3FFK3YAY) and pay via Stripe, it's very fast, convenient and appreciated; thanks a lot!

**Comment by yegor256** [comment]
@imcaizheng fixed, thanks!

**Comment by 0crat** [comment]
The job is not in WBS, won't close the order
