### ISSUE TITLE
Close Response body input stream after printing it to socket's output stream?

### ISSUE THREAD

**Issue by jimkast** [yegor256/takes#838]
Currently, BkBasic uses RsPrint to send response bytes to socket's output stream.
However, RsPrint does not close input stream, which may be a File (FileInputStream) as in TkFiles case.
Should RsPrint close the input stream to avoid issues with resources?
Or maybe a BkBasic constructor accept a Func<Response, OutputBytes> which will be RsPrint by default in a secondary constructor?

```
public interface OutputBytes {
    void print(OutputStream output);
}
```

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by 0crat** [comment]
@jimkast[/z](https://www.0crat.com/u/jimkast) this project will fix the problem faster if you donate a few dollars to it; just [click here](https://www.0crat.com/contrib/C3FFK3YAY) and pay via Stripe, it's very fast, convenient and appreciated; thanks a lot!

**Comment by yegor256** [comment]
@jimkast I think `RsPrint` should close the stream

**Comment by yegor256** [comment]
@jimkast feel free to contribute with a PR.

**Comment by paulodamaso** [comment]
@0crat status

**Comment by 0crat** [comment]
> @0crat status ([here](https://github.com/yegor256/takes/issues/838#issuecomment-430469891))

@paulodamaso This is what I know about this job in [C3FFK3YAY](https://www.0crat.com/p/C3FFK3YAY), as in [§32](http://www.zerocracy.com/policy.html#32):

  * The job [#838](https://github.com/yegor256/takes/issues/838) is not in scope
  * Job [footprint](https://www.0crat.com/footprint/C3FFK3YAY?q=%7Bjob%3A%27gh%3Ayegor256%2Ftakes%23838%27%2Ctype%3A%7B%24not%3A%2F%5ENotify%2F%7D%7D) (restricted area)

**Comment by paulodamaso** [comment]
@0crat in

**Comment by 0crat** [comment]
> @0crat in ([here](https://github.com/yegor256/takes/issues/838#issuecomment-430483815))

@paulodamaso Job [#838](https://github.com/yegor256/takes/issues/838) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
> @0crat in ([here](https://github.com/yegor256/takes/issues/838#issuecomment-430483815))

@paulodamaso Thanks for your contribution, @jimkast[/z](https://www.0crat.com/u/jimkast)! If you would be a member of [the project](https://www.0crat.com/p/C3FFK3YAY), you would now earn +15 reputation points, as explained in [§29](http://www.zerocracy.com/policy.html#29). You can join and apply to it, see [§2](http://www.zerocracy.com/policy.html#2).

**Comment by olenagerasimova** [comment]
@0crat wait for review/merge of PR #879

**Comment by 0crat** [comment]
> @0crat wait for review/merge of PR #879  ([here](https://github.com/yegor256/takes/issues/838#issuecomment-443457005))

@olenagerasimova The impediment for [#838](https://github.com/yegor256/takes/issues/838) was registered successfully by @olenagerasimova[/z](https://www.0crat.com/u/olenagerasimova)

**Comment by olenagerasimova** [comment]
@jimkast fixed in #879 please close

**Comment by ypshenychka** [comment]
@0crat quality good

**Comment by paulodamaso** [comment]
@rultor release, tag is 1.11.4

**Comment by 0crat** [comment]
> @0crat quality good ([here](https://github.com/yegor256/takes/issues/838#issuecomment-444922341))

@ypshenychka The project doesn't have enough funds, can't make a payment

**Comment by 0crat** [comment]
Order was finished, quality is "good": +35 point(s) just awarded to @olenagerasimova[/z](https://www.0crat.com/u/olenagerasimova)

**Comment by 0crat** [comment]
Quality review completed: +8 point(s) just awarded to @ypshenychka[/z](https://www.0crat.com/u/ypshenychka)

**Comment by paulodamaso** [comment]
@rultor release, tag 1.11.4

**Comment by paulodamaso** [comment]
@rultor release, tag=`1.11.4`
