### ISSUE TITLE
How do you make an HTTP request?

### ISSUE THREAD

**Issue by llorllale** [yegor256/takes#839]
I see the `Request` interface that *parses* incoming http requests. But how do you dispatch an http request to some remote service?

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by 0crat** [comment]
@llorllale[/z](https://www.0crat.com/u/llorllale) this project will fix the problem faster if you donate a few dollars to it; just [click here](https://www.0crat.com/contrib/C3FFK3YAY) and pay via Stripe, it's very fast, convenient and appreciated; thanks a lot!

**Comment by llorllale** [comment]
@jimkast I'm looking for solutions provided by `Takes` framework itself. 

And yes, I want to send an HTTP request to some other arbitrary external service.

**Comment by jimkast** [comment]
@llorllale Yes, I agree takes can be easily extended by takes to support remote requests like [jcabi-http](https://github.com/jcabi/jcabi-http) with Jdk's HttpURLConnection, or Apache's HttpClient or even plain Socket implementations. There are already many Request/Response utilities/decorators that can be used.

**Comment by yegor256** [comment]
@llorllale there are plenty of classes in `.rq` package. Start from `RqFake()` and go up to `RqWithHeader`, etc.

**Comment by 0crat** [comment]
The job is not in WBS, won't close the order
