### ISSUE TITLE
Drop java7 support

### ISSUE THREAD

**Issue by g4s8** [yegor256/takes#841]
Java7 is too old, it is not compatible with new java libraries, e.g. [here](https://ci.appveyor.com/project/yegor256/takes/build/3033) appveyor failed due to `javac` warning which suggests to update the compiler:
```
[WARNING] /C:/projects/takes/src/main/java/org/takes/servlet/ResponseOf.java: C:\Users\appveyor\.m2\repository\javax\servlet\javax.servlet-api\4.0.0\javax.servlet-api-4.0.0.jar(javax/servlet/http/Cookie.class): major version 52 is newer than 51, the highest major version supported by this compiler.
  It is recommended that the compiler be upgraded.
```

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by 0crat** [comment]
Job [#841](https://github.com/yegor256/takes/issues/841) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 point(s) just awarded to @g4s8[/z](https://www.0crat.com/u/g4s8)

**Comment by paulodamaso** [comment]
@g4s8 Wouldn't https://github.com/yegor256/takes/issues/808 solve this one?

**Comment by g4s8** [comment]
@paulodamaso yes, it seems all CI tools are using java-8 now

**Comment by 0crat** [comment]
Job `gh:yegor256/takes#841` is not assigned, can't get performer

**Comment by 0crat** [comment]
The job [#841](https://github.com/yegor256/takes/issues/841) is now out of scope
