### ISSUE TITLE
Support for Velocity 2.0, since it does not work

### ISSUE THREAD

**Issue by esteveboix** [yegor256/takes#842]
I'm starting a new project with Takes (first use). For some front-end pages, I'd prefer to use Velocity over XML/XSL.

I'm using a Take that returns this (simplified):

```
return new RsVelocity(
            "hi, ${user}!",
            new RsVelocity.Pair("user", "Esteve")
        );
```

If I use velocity 2.0, I get an Exception: org.apache.velocity.runtime.log.NullLogChute ClassDefNotFound.
The exception origin is at RsVelocity.java line 157 when trying to initialize the Log class:

```
engine.setProperty(
            RuntimeConstants.RUNTIME_LOG_LOGSYSTEM,
            new NullLogChute()
);
```

...which is not supported anymore in Velocity 2.0.

I haven't found any reference of Velocity 2.0 being unsupported, but downgrading from 2.0 to 1.7 in Maven solved the issue. Since 2.0 came out nearly a year ago we should start considering support for it in Takes.

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by 0crat** [comment]
@esteveboix[/z](https://www.0crat.com/u/esteveboix) this project will fix the problem faster if you donate a few dollars to it; just [click here](https://www.0crat.com/contrib/C3FFK3YAY) and pay via Stripe, it's very fast, convenient and appreciated; thanks a lot!

**Comment by paulodamaso** [comment]
@0crat in

**Comment by 0crat** [comment]
> @0crat in ([here](https://github.com/yegor256/takes/issues/842#issuecomment-430480458))

@paulodamaso Job [#842](https://github.com/yegor256/takes/issues/842) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
> @0crat in ([here](https://github.com/yegor256/takes/issues/842#issuecomment-430480458))

@paulodamaso Thanks for your contribution, @esteveboix[/z](https://www.0crat.com/u/esteveboix)! If you would be a member of [the project](https://www.0crat.com/p/C3FFK3YAY), you would now earn +15 reputation points, as explained in [§29](http://www.zerocracy.com/policy.html#29). You can join and apply to it, see [§2](http://www.zerocracy.com/policy.html#2).

**Comment by 0crat** [comment]
The job [#842](https://github.com/yegor256/takes/issues/842) assigned to @ypshenychka[/z](https://www.0crat.com/u/ypshenychka), here is [why](https://www.0crat.com/footprint/C3FFK3YAY/87f8272a-86ce-4875-8341-fda30f2776e7); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be a monetary reward for this job

**Comment by ypshenychka** [comment]
@0crat refuse

**Comment by 0crat** [comment]
> @0crat refuse ([here](https://github.com/yegor256/takes/issues/842#issuecomment-437974533))

@ypshenychka The user @ypshenychka[/z](https://www.0crat.com/u/ypshenychka) resigned from [#842](https://github.com/yegor256/takes/issues/842), please stop working. Reason for job resignation: Order was cancelled

**Comment by 0crat** [comment]
Tasks refusal is discouraged, see [§6](http://www.zerocracy.com/policy.html#6): -15 point(s) just awarded to @ypshenychka[/z](https://www.0crat.com/u/ypshenychka)

**Comment by 0crat** [comment]
The job [#842](https://github.com/yegor256/takes/issues/842) assigned to @olenagerasimova[/z](https://www.0crat.com/u/olenagerasimova), here is [why](https://www.0crat.com/footprint/C3FFK3YAY/7b3c8738-ee51-428f-bbbf-bc563a562299); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be a monetary reward for this job

**Comment by olenagerasimova** [comment]
@paulodamaso what is our approach here? Migrating to velocity 2?

**Comment by paulodamaso** [comment]
@olenagerasimova Yes, let's upgrade to velocity to 2.0

**Comment by 0crat** [comment]
@olenagerasimova[/z](https://www.0crat.com/u/olenagerasimova) this job was assigned to you 5days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by olenagerasimova** [comment]
@0crat please wait busy on other tasks

**Comment by 0crat** [comment]
> @0crat please wait busy on other tasks ([here](https://github.com/yegor256/takes/issues/842#issuecomment-444947743))

@olenagerasimova Can't understand "please", try one of these:
  - `assign` Assign a performer to this issue
  - `boost` Set a boost for the job
  - `continue` Remove a job's impediment
  - `hello` Just say hello
  - `in` Register this issue in scope (WBS)
  - `out` Close the order and remove this job from scope
  - `pay` Pay a user some extra cash
  - `quality` Review a task
  - `resign` Resign from this issue
  - `status` Check the status of the job
  - `version` Print current version of the bot
  - `wait` Register an impediment for a job

**Comment by olenagerasimova** [comment]
@0crat wait please busy on other tasks

**Comment by 0crat** [comment]
> @0crat wait please busy on other tasks ([here](https://github.com/yegor256/takes/issues/842#issuecomment-444949606))

@olenagerasimova The impediment for [#842](https://github.com/yegor256/takes/issues/842) was registered successfully by @olenagerasimova[/z](https://www.0crat.com/u/olenagerasimova)

**Comment by olenagerasimova** [comment]
@paulodamaso 2 questions:
- `VelocityContext` ctor's argument in version 2.0 in `Map<String, Object>` instead of `Map<CharSequence, Object>` - so, what should I do? Change ctors signature in `RsVelocity` and `RsVelocity.Pair` or leave them as is and just convert params map before creating `VelocityContext` instance?
- velocity logging is currently disabled by setting `RUNTIME_LOG_LOGSYSTEM` property to `NullLogChute`. Velocity 2.0 [uses](http://velocity.apache.org/engine/2.0/upgrading.html) SLF4J logging facade and I do not see any reasons to disable it, is there really anything against it?

**Comment by paulodamaso** [comment]
@olenagerasimova Let's do the following:
- I think that you should add a new constructor `Map<String, Object>` that will be called from `Map<CharSequence, Object>`, so we do not break compatibility with older versions
- I don't know, let's enable it and see what happens

**Comment by olenagerasimova** [comment]
@0crat wait please for PR #891 review/merge

**Comment by 0crat** [comment]
> @0crat wait please for PR #891 review/merge ([here](https://github.com/yegor256/takes/issues/842#issuecomment-446168112))

@olenagerasimova Job [#842](https://github.com/yegor256/takes/issues/842) is already on hold

**Comment by olenagerasimova** [comment]
@esteveboix we migrated to velocity 2.0 in #891, so could you please close this issue?

**Comment by esteveboix** [comment]
Closing issue. Thanks a lot for your help!

**Comment by 0crat** [comment]
@ypshenychka[/z](https://www.0crat.com/u/ypshenychka) please review this job completed by @olenagerasimova[/z](https://www.0crat.com/u/olenagerasimova), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by 0crat** [comment]
The job [#842](https://github.com/yegor256/takes/issues/842) is now out of scope

**Comment by ypshenychka** [comment]
@0crat quality good

**Comment by 0crat** [comment]
> @0crat quality good ([here](https://github.com/yegor256/takes/issues/842#issuecomment-446752374))

@ypshenychka The project doesn't have enough funds, can't make a payment

**Comment by 0crat** [comment]
> @0crat quality good ([here](https://github.com/yegor256/takes/issues/842#issuecomment-446752374))

@ypshenychka The project doesn't have enough funds, can't make a payment

**Comment by 0crat** [comment]
Order was finished, quality is "good": +35 point(s) just awarded to @olenagerasimova[/z](https://www.0crat.com/u/olenagerasimova)

**Comment by 0crat** [comment]
Quality review completed: +8 point(s) just awarded to @ypshenychka[/z](https://www.0crat.com/u/ypshenychka)
