### ISSUE TITLE
flash managing mechanism has incompleted java doc 

### ISSUE THREAD

**Issue by dmzaytsev** [yegor256/takes#85]
Flash managing mechanism has incompleted java doc.
Сlasses RsFlash, TsFlash, XeFlash needs more explanation.

**Comment by yegor256** [comment]
@davvd this is definitely a bug, let's dispatch it

**Comment by davvd** [comment]
> @davvd this is definitely a bug, let's dispatch it

@yegor256 thanks, I added the "bug" tag

**Comment by davvd** [comment]
@yegor256 the task is yours (budget is 30 mins)

**Comment by davvd** [comment]
@dmzaytsev thanks for reporting! I topped your account for 15 mins, transaction 54263086

**Comment by yegor256** [comment]
@dmzaytsev take a look at the changes I've made in a9db501 good enough?

**Comment by dmzaytsev** [comment]
@yegor256  thanks!

**Comment by davvd** [comment]
@yegor256 I just added **1 hour** to your account, many thanks for your contribution.. 000-149044a5 spent here. age=6 is a bonus here for fast delivery. +60 added to your rating, at the moment it is: [+8771](http://www.netbout.com/b/35008?open=rating)
