### ISSUE TITLE
AppVeyor build failing due parent config

### ISSUE THREAD

**Issue by paulodamaso** [yegor256/takes#850]
AppVeyor build is failing due some parent-pom configuration:

```
[INFO] Scanning for projects...
[INFO] Downloading: https://repo.maven.apache.org/maven2/com/jcabi/parent/0.49.1/parent-0.49.1.pom
[ERROR] The build could not read 1 project -> [Help 1]
[ERROR]   
[ERROR]   The project org.takes:takes:2.0-SNAPSHOT (C:\projects\takes\pom.xml) has 1 error
[ERROR]     Non-resolvable parent POM: Could not transfer artifact com.jcabi:parent:pom:0.49.1 from/to central (https://repo.maven.apache.org/maven2): Received fatal alert: protocol_version and 'parent.relativePath' points at wrong local POM @ line 27, column 11 -> [Help 2]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/ProjectBuildingException
[ERROR] [Help 2] http://cwiki.apache.org/confluence/display/MAVEN/UnresolvableModelException
Command exited with code 1
```

This is happening in the following PRs:
https://github.com/yegor256/takes/pull/843
https://github.com/yegor256/takes/pull/844
https://github.com/yegor256/takes/pull/845
https://github.com/yegor256/takes/pull/846
https://github.com/yegor256/takes/pull/848
https://github.com/yegor256/takes/pull/849

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by 0crat** [comment]
Job [#850](https://github.com/yegor256/takes/issues/850) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 point(s) just awarded to @paulodamaso[/z](https://www.0crat.com/u/paulodamaso)

**Comment by 0crat** [comment]
Job `gh:yegor256/takes#850` is not assigned, can't get performer

**Comment by 0crat** [comment]
The job [#850](https://github.com/yegor256/takes/issues/850) is now out of scope
