### ISSUE TITLE
HTTP requests are processed in wrong order

### ISSUE THREAD

**Issue by driver733** [yegor256/takes#851]
I am developing a backend API that processes chat messages (from vk.com) using Takes web framework. I have noticed that the http requests containing chat messages are passed to my Take instance in incorrect order. The expectation is that they are processed (passed to the specified Take instance) in the order that they were initiated. However, this expectation is sometimes not fulfilled. What can I do to resolve this issue?

p.s. The Take instance has no code other than a log message statement.

> VK:

```
1
2
3
4
```

> Server log:

```
// Notice the order does not match the aforementioned message sequence

2018-09-13 17:57:57 INFO  TkVkontakte:106 - Message "2" received
2018-09-13 17:57:57 INFO  TkVkontakte:106 - Message "1" received
2018-09-13 17:57:57 INFO  TkVkontakte:106 - Message "3" received
2018-09-13 17:57:57 INFO  TkVkontakte:106 - Message "4" received
```

> Server.java:

```
new FtBasic(
    new TkFork(
        new FkRegex(
            "/vkontakte",
            new TkRegex() {
                @Override
                public Response act(final RqRegex req) throws IOException {
                    final String res = new RqPrint(req).printBody();
                    final JsonReader reader = Json.createReader(
                        new StringReader(res)
                    );
                    final JsonObject root = reader.readObject();
                    final JsonObject message = root.getJsonObject("object");
                    final int from = message.getInt("from_id");
                    final String text = message.getString("text");
                    Logger.info(
                        this,
                        "Message \"%s\" received",
                        text,
                        from
                    );
                }
            }
        )
    ),
    8080
).start(
    Exit.NEVER
);
```

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by 0crat** [comment]
@driver733[/z](https://www.0crat.com/u/driver733) this project will fix the problem faster if you donate a few dollars to it; just [click here](https://www.0crat.com/contrib/C3FFK3YAY) and pay via Stripe, it's very fast, convenient and appreciated; thanks a lot!

**Comment by 0crat** [comment]
Job `gh:yegor256/takes#851` is not assigned, can't get performer

**Comment by 0crat** [comment]
This job is not in scope
