### ISSUE TITLE
How do you read a response's status code?

### ISSUE THREAD

**Issue by llorllale** [yegor256/takes#856]
How do you read the status code of a `Response`?

**Comment by llorllale** [comment]
@g4s8 do you know the answer to this by any chance?

**Comment by g4s8** [comment]
@llorllale if you need it for unit test you can use `HmRsStatus` Hamcrest-matcher:
```java
MatcherAssert.assertThat(
  new SomeTake().act(new RqRegex.Fake()),
  new HmRsStatus(200)
);
```

**Comment by llorllale** [comment]
@g4s8 that's what I needed, thanks

**Comment by 0crat** [comment]
Job `gh:yegor256/takes#856` is not assigned, can't get performer

**Comment by 0crat** [comment]
This job is not in scope
