### ISSUE TITLE
ProhibitPlainJunitAssertionsRule reports AssertJ assertion as plain JUnit assertion

### ISSUE THREAD

**Issue by grzechol** [yegor256/takes#858]
I'm getting **Avoid using Plain JUnit assertions (ProhibitPlainJunitAssertionsRule)** PMD error for the following code:
```
import static org.assertj.core.api.Assertions.assertThat;
import org.junit.Test;

public class DummyTest {
    @Test
    public void test() {
        assertThat(Boolean.TRUE).isTrue();
    }
}
```
My assertion however is not a plain JUnit assertion, but it comes from [AssertJ](http://joel-costigliola.github.io/assertj/) framework.

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by 0crat** [comment]
@grzechol[/z](https://www.0crat.com/u/grzechol) this project will fix the problem faster if you donate a few dollars to it; just [click here](https://www.0crat.com/contrib/C3FFK3YAY) and pay via Stripe, it's very fast, convenient and appreciated; thanks a lot!

**Comment by grzechol** [comment]
Sorry guys, I meant to report this in quile project instead of this one.

**Comment by 0crat** [comment]
Job `gh:yegor256/takes#858` is not assigned, can't get performer

**Comment by 0crat** [comment]
This job is not in scope
