### ISSUE TITLE
HmBody.java:48-50: Current implementation of `HmBody`...

### ISSUE THREAD

**Issue by 0pdd** [yegor256/takes#859]
The puzzle `794-c85dda7b` from #794 has to be resolved: 

https://github.com/yegor256/takes/blob/13bbd4eab3ef44f54c44512e3c1d7d7a4ddea4c6/src/main/java/org/takes/facets/hamcrest/HmBody.java#L48-L50

The puzzle was created by Paulo Lobo on 04-Sep-18. 

  

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0crat** [comment]
@paulodamaso[/z](https://www.0crat.com/u/paulodamaso) please, pay attention to this issue

**Comment by 0crat** [comment]
Job [#859](https://github.com/yegor256/takes/issues/859) is now in scope, role is `DEV`

**Comment by paulodamaso** [comment]
@0crat close

**Comment by 0crat** [comment]
> @0crat close ([here](https://github.com/yegor256/takes/issues/859#issuecomment-429050771))

@paulodamaso Can't understand "close", try one of these:
  - `assign` Assign a performer to this issue
  - `boost` Set a boost for the job
  - `continue` Remove a job's impediment
  - `hello` Just say hello
  - `in` Register this issue in scope (WBS)
  - `out` Close the order and remove this job from scope
  - `pay` Pay a user some extra cash
  - `quality` Review a task
  - `resign` Resign from this issue
  - `status` Check the status of the job
  - `version` Print current version of the bot
  - `wait` Register an impediment for a job

**Comment by 0pdd** [comment]
The puzzle `794-c85dda7b` has disappeared from the source code, that's why I closed this issue.

**Comment by 0crat** [comment]
Job `gh:yegor256/takes#859` is not assigned, can't get performer

**Comment by 0crat** [comment]
This job is not in scope
