### ISSUE TITLE
TkMethods returns 404 on unsupported method

### ISSUE THREAD

**Issue by g4s8** [yegor256/takes#861]
`TkMethods` take returns 404 error if method is not supported. 
It would be more logical to return `405: Method Not Allowed` here.

```java
new FtRemote(new TkMethods(new TkEmpty(), "PUT")).exec(
    url -> new JdkRequest(url)
        .method("POST")
        .fetch().as(RestResponse.class)
        // expecting 405: Method Not Allowed.
        .assertStatus(HttpURLConnection.HTTP_BAD_METHOD)
);
// java.lang.AssertionError: HTTP response status is not equal to 405: 404 Not Found
```

**Comment by paulodamaso** [comment]
@0crat in

**Comment by 0crat** [comment]
> @0crat in ([here](https://github.com/yegor256/takes/issues/861#issuecomment-430471995))

@paulodamaso Job [#861](https://github.com/yegor256/takes/issues/861) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 point(s) just awarded to @g4s8[/z](https://www.0crat.com/u/g4s8)

**Comment by 0crat** [comment]
The job [#861](https://github.com/yegor256/takes/issues/861) assigned to @ypshenychka[/z](https://www.0crat.com/u/ypshenychka), here is [why](https://www.0crat.com/footprint/C3FFK3YAY/0a18eecb-3af8-49a6-9e16-c7c1f9d89a95); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be a monetary reward for this job

**Comment by ypshenychka** [comment]
@0crat refuse

**Comment by 0crat** [comment]
> @0crat refuse ([here](https://github.com/yegor256/takes/issues/861#issuecomment-437974245))

@ypshenychka The user @ypshenychka[/z](https://www.0crat.com/u/ypshenychka) resigned from [#861](https://github.com/yegor256/takes/issues/861), please stop working. Reason for job resignation: Order was cancelled

**Comment by 0crat** [comment]
Tasks refusal is discouraged, see [§6](http://www.zerocracy.com/policy.html#6): -15 point(s) just awarded to @ypshenychka[/z](https://www.0crat.com/u/ypshenychka)

**Comment by victornoel** [comment]
@0crat wait for review/merge of #875

**Comment by 0crat** [comment]
> @0crat wait for review/merge of #875 ([here](https://github.com/yegor256/takes/issues/861#issuecomment-442565494))

@victornoel The impediment for [#861](https://github.com/yegor256/takes/issues/861) was registered successfully by @victornoel[/z](https://www.0crat.com/u/victornoel)

**Comment by victornoel** [comment]
@g4s8 the PR was merged, can you close the issue? Thanks

**Comment by 0crat** [comment]
@ypshenychka[/z](https://www.0crat.com/u/ypshenychka) please review this job completed by @victornoel[/z](https://www.0crat.com/u/victornoel), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by 0crat** [comment]
The job [#861](https://github.com/yegor256/takes/issues/861) is now out of scope

**Comment by ypshenychka** [comment]
@0crat quality good

**Comment by 0crat** [comment]
Order was finished, quality is "good": +35 point(s) just awarded to @victornoel[/z](https://www.0crat.com/u/victornoel)

**Comment by 0crat** [comment]
Quality review completed: +8 point(s) just awarded to @ypshenychka[/z](https://www.0crat.com/u/ypshenychka)
