### ISSUE TITLE
Remove nulls

### ISSUE THREAD

**Issue by paulodamaso** [yegor256/takes#863]
There are a lot of `null` usages in the project violating the key principles defined README.md file. These `null` constant references must be eliminated.

**Comment by 0crat** [comment]
The job [#863](https://github.com/yegor256/takes/issues/863) assigned to @krzyk[/z](https://www.0crat.com/u/krzyk), here is [why](https://www.0crat.com/footprint/C3FFK3YAY/71eb402a-a86b-4a76-ac0a-013df4150bf0); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be a monetary reward for this job

**Comment by krzyk** [comment]
@paulodamaso What to do in case of receiving `null` from external libraries, or a call to external library requires `null` in params to enable some option?
In case of return params we could hide `null` inside `Optional` or `Opt`

I think the last time nulls were being removed (https://github.com/yegor256/takes/issues/555) here we stopped at those boundaries.

**Comment by paulodamaso** [comment]
@krzyk I think that we have to evaluate each case of null when communicating with other libraries, so let's not assume any default behavior for now.

Takes code deteriorated from last `null` removal to now; we have a lot of "new nulls" lurking in our own code right now. Let's take care of these ones first.

**Comment by krzyk** [comment]
@0crat wait I'm busy with other tasks

**Comment by 0crat** [comment]
> @0crat wait I'm busy with other tasks ([here](https://github.com/yegor256/takes/issues/863#issuecomment-447599418))

@krzyk The impediment for [#863](https://github.com/yegor256/takes/issues/863) was registered successfully by @krzyk[/z](https://www.0crat.com/u/krzyk)

**Comment by krzyk** [comment]
@paulodamaso please close this issue, it has been merged to master in #907

**Comment by paulodamaso** [comment]
@krzyk Great, thanks!

**Comment by ypshenychka** [comment]
@0crat quality good

**Comment by 0crat** [comment]
> @0crat quality good ([here](https://github.com/yegor256/takes/issues/863#issuecomment-450104987))

@ypshenychka The project doesn't have enough funds, can't make a payment

**Comment by 0crat** [comment]
> @0crat quality good ([here](https://github.com/yegor256/takes/issues/863#issuecomment-450104987))

@ypshenychka The project doesn't have enough funds, can't make a payment

**Comment by 0crat** [comment]
Order was finished, quality is "good": +35 point(s) just awarded to @krzyk[/z](https://www.0crat.com/u/krzyk)

**Comment by 0crat** [comment]
Quality review completed: +8 point(s) just awarded to @ypshenychka[/z](https://www.0crat.com/u/ypshenychka)

**Comment by 0pdd** [comment]
@paulodamaso the puzzle [#unknown]() is still not solved.
