### ISSUE TITLE
FtRemoteTest.java:55-59: We can't assert if FtRemote...

### ISSUE THREAD

**Issue by 0pdd** [yegor256/takes#869]
The puzzle `800-fe5f523c` from #800 has to be resolved: 

https://github.com/yegor256/takes/blob/4ccecced024e64cc5b5efb19db56144b15af03d8/src/test/java/org/takes/http/FtRemoteTest.java#L55-L59

The puzzle was created by Victor Noël on 18-Nov-18. 

  

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0crat** [comment]
@paulodamaso[/z](https://www.0crat.com/u/paulodamaso) please, pay attention to this issue

**Comment by 0crat** [comment]
Job [#869](https://github.com/yegor256/takes/issues/869) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
The job [#869](https://github.com/yegor256/takes/issues/869) assigned to @olenagerasimova[/z](https://www.0crat.com/u/olenagerasimova), here is [why](https://www.0crat.com/footprint/C3FFK3YAY/57fbdab0-55b9-44dc-8659-54ee70048894); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be a monetary reward for this job

**Comment by olenagerasimova** [comment]
@0crat wait please for https://github.com/jcabi/jcabi-http/issues/177 to be resolved

**Comment by 0crat** [comment]
> @0crat wait please for https://github.com/jcabi/jcabi-http/issues/177 to be resolved ([here](https://github.com/yegor256/takes/issues/869#issuecomment-439893780))

@olenagerasimova The impediment for [#869](https://github.com/yegor256/takes/issues/869) was registered successfully by @olenagerasimova[/z](https://www.0crat.com/u/olenagerasimova)

**Comment by olenagerasimova** [comment]
@0crat refuse

**Comment by 0crat** [comment]
> @0crat refuse ([here](https://github.com/yegor256/takes/issues/869#issuecomment-448705642))

@olenagerasimova The user @olenagerasimova[/z](https://www.0crat.com/u/olenagerasimova) resigned from [#869](https://github.com/yegor256/takes/issues/869), please stop working. Reason for job resignation: Order was cancelled

**Comment by 0crat** [comment]
Tasks refusal is discouraged, see [§6](http://www.zerocracy.com/policy.html#6): -15 point(s) just awarded to @olenagerasimova[/z](https://www.0crat.com/u/olenagerasimova)

**Comment by 0crat** [comment]
The job [#869](https://github.com/yegor256/takes/issues/869) assigned to @fabriciofx[/z](https://www.0crat.com/u/fabriciofx), here is [why](https://www.0crat.com/footprint/C3FFK3YAY/ac8ecdef-1128-4c32-834c-f3b6bd99ab8a); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be no monetary reward for this job

**Comment by 0crat** [comment]
Job `gh:yegor256/takes#869` already assigned to @fabriciofx, can't assign to @fabriciofx

**Comment by fabriciofx** [comment]
@0crat wait for [jcabi-http#177](https://github.com/jcabi/jcabi-http/issues/177) to be resolved.

**Comment by 0crat** [comment]
> @0crat wait for [jcabi-http#177](https://github.com/jcabi/jcabi-http/issues/177) to be resolved. ([here](https://github.com/yegor256/takes/issues/869#issuecomment-451524291))

@fabriciofx The impediment for [#869](https://github.com/yegor256/takes/issues/869) was registered successfully by @fabriciofx[/z](https://www.0crat.com/u/fabriciofx)

**Comment by fabriciofx** [comment]
@0crat refuse

**Comment by 0crat** [comment]
> @0crat refuse ([here](https://github.com/yegor256/takes/issues/869#issuecomment-457246172))

@fabriciofx The user @fabriciofx[/z](https://www.0crat.com/u/fabriciofx) resigned from [#869](https://github.com/yegor256/takes/issues/869), please stop working. Reason for job resignation: Order was cancelled

**Comment by 0crat** [comment]
Tasks refusal is discouraged, see [§6](http://www.zerocracy.com/policy.html#6): -15 point(s) just awarded to @fabriciofx[/z](https://www.0crat.com/u/fabriciofx)

**Comment by 0crat** [comment]
The job [#869](https://github.com/yegor256/takes/issues/869) assigned to @serranya[/z](https://www.0crat.com/u/serranya), here is [why](https://www.0crat.com/footprint/C3FFK3YAY/a3011296-bea7-45f5-b20d-8a84a5c74be3); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be no monetary reward for this job

**Comment by 0crat** [comment]
Job `gh:yegor256/takes#869` already assigned to @serranya, can't assign to @serranya

**Comment by Serranya** [comment]
@0crat wait for https://github.com/jcabi/jcabi-http/issues/177

**Comment by 0crat** [comment]
> @0crat wait for https://github.com/jcabi/jcabi-http/issues/177 ([here](https://github.com/yegor256/takes/issues/869#issuecomment-458110819))

@Serranya The impediment for [#869](https://github.com/yegor256/takes/issues/869) was registered successfully by @serranya[/z](https://www.0crat.com/u/serranya)

**Comment by Serranya** [comment]
@0crat refuse

**Comment by 0crat** [comment]
> @0crat refuse ([here](https://github.com/yegor256/takes/issues/869#issuecomment-466074733))

@Serranya The user @serranya[/z](https://www.0crat.com/u/serranya) resigned from [#869](https://github.com/yegor256/takes/issues/869), please stop working. Reason for job resignation: Order was cancelled

**Comment by 0crat** [comment]
The job [#869](https://github.com/yegor256/takes/issues/869) assigned to @lucasmessias9898[/z](https://www.0crat.com/u/lucasmessias9898), here is [why](https://www.0crat.com/footprint/C3FFK3YAY/3c1a30a9-8535-4a98-ad24-d6e7204040a7); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be no monetary reward for this job

**Comment by lucasmessias9898** [comment]
@0crat refuse

**Comment by 0crat** [comment]
> @0crat refuse ([here](https://github.com/yegor256/takes/issues/869#issuecomment-469448471))

@lucasmessias9898 The user @lucasmessias9898[/z](https://www.0crat.com/u/lucasmessias9898) resigned from [#869](https://github.com/yegor256/takes/issues/869), please stop working. Reason for job resignation: Order was cancelled

**Comment by 0crat** [comment]
Tasks refusal is discouraged, see [§6](http://www.zerocracy.com/policy.html#6): -15 point(s) just awarded to @lucasmessias9898[/z](https://www.0crat.com/u/lucasmessias9898)

**Comment by 0crat** [comment]
The job [#869](https://github.com/yegor256/takes/issues/869) assigned to @marceloamadeu[/z](https://www.0crat.com/u/marceloamadeu), here is [why](https://www.0crat.com/footprint/C3FFK3YAY/da363e0e-fb15-4f7f-bf63-9731c03d0d76); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be no monetary reward for this job

**Comment by marceloamadeu** [comment]
@0crat refuse

**Comment by 0crat** [comment]
> @0crat refuse ([here](https://github.com/yegor256/takes/issues/869#issuecomment-480664038))

@marceloamadeu The user @marceloamadeu[/z](https://www.0crat.com/u/marceloamadeu) resigned from [#869](https://github.com/yegor256/takes/issues/869), please stop working. Reason for job resignation: Order was cancelled

**Comment by 0crat** [comment]
Tasks refusal is discouraged, see [§6](http://www.zerocracy.com/policy.html#6): -15 point(s) just awarded to @marceloamadeu[/z](https://www.0crat.com/u/marceloamadeu)

**Comment by 0crat** [comment]
The job [#869](https://github.com/yegor256/takes/issues/869) assigned to @protagores[/z](https://www.0crat.com/u/protagores), here is [why](https://www.0crat.com/footprint/C3FFK3YAY/f2b877c5-cede-422c-bb50-3d669a94d2d3); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be no monetary reward for this job

**Comment by Protagores** [comment]
@0crat wait for jcabi/jcabi-http#177

**Comment by 0crat** [comment]
> @0crat wait for jcabi/jcabi-http#177 ([here](https://github.com/yegor256/takes/issues/869#issuecomment-483183174))

@Protagores The impediment for [#869](https://github.com/yegor256/takes/issues/869) was registered successfully by @protagores[/z](https://www.0crat.com/u/protagores)

**Comment by Protagores** [comment]
@0crat refuse

**Comment by 0crat** [comment]
> @0crat refuse ([here](https://github.com/yegor256/takes/issues/869#issuecomment-508723894))

@Protagores The user @protagores[/z](https://www.0crat.com/u/protagores) resigned from [#869](https://github.com/yegor256/takes/issues/869), please stop working. Reason for job resignation: Order was cancelled

**Comment by 0crat** [comment]
Tasks refusal is discouraged, see [§6](http://www.zerocracy.com/policy.html#6): -15 point(s) just awarded to @protagores[/z](https://www.0crat.com/u/protagores)

**Comment by 0crat** [comment]
The job [#869](https://github.com/yegor256/takes/issues/869) assigned to @fanifieiev[/z](https://www.0crat.com/u/fanifieiev), here is [why](https://www.0crat.com/footprint/C3FFK3YAY/1c3200ae-ba77-4350-beb6-9d66367d8aa0); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be no monetary reward for this job

**Comment by fanifieiev** [comment]
@0crat status

**Comment by 0crat** [comment]
> @0crat status  ([here](https://github.com/yegor256/takes/issues/869#issuecomment-556021642))

@fanifieiev This is what I know about this job in [C3FFK3YAY](https://www.0crat.com/p/C3FFK3YAY), as in [§32](http://www.zerocracy.com/policy.html#32):

  * The job [#869](https://github.com/yegor256/takes/issues/869) is [in scope](http://www.zerocracy.com/policy.html#14) for 12mon
  * The role is `DEV`
  * The job is assigned to @fanifieiev[/z](https://www.0crat.com/u/fanifieiev) for [8days](http://www.zerocracy.com/policy.html#8)
  * There is no monetary reward attached, it's a [free](http://www.zerocracy.com/policy.html#2) job
  * The job doesn't have any [impediments](http://www.zerocracy.com/policy.html#9)
  * The [budget](http://www.zerocracy.com/policy.html#4) is 30 minutes/points
  * These users are banned and won't be assigned:
    * @0pdd[/z](https://www.0crat.com/u/0pdd): This user reported the ticket
    * @olenagerasimova[/z](https://www.0crat.com/u/olenagerasimova): User was resigned from the ticket
    * @fabriciofx[/z](https://www.0crat.com/u/fabriciofx): User was resigned from the ticket
    * @serranya[/z](https://www.0crat.com/u/serranya): User was resigned from the ticket
    * @lucasmessias9898[/z](https://www.0crat.com/u/lucasmessias9898): User was resigned from the ticket
    * @marceloamadeu[/z](https://www.0crat.com/u/marceloamadeu): User was resigned from the ticket
    * @protagores[/z](https://www.0crat.com/u/protagores): User was resigned from the ticket
  * Job [footprint](https://www.0crat.com/footprint/C3FFK3YAY?q=%7Bjob%3A%27gh%3Ayegor256%2Ftakes%23869%27%2Ctype%3A%7B%24not%3A%2F%5ENotify%2F%7D%7D) (restricted area)

**Comment by fanifieiev** [comment]
@0crat wait for #996 to be merged

**Comment by 0crat** [comment]
> @0crat wait for #996 to be merged ([here](https://github.com/yegor256/takes/issues/869#issuecomment-556029934))

@fanifieiev The impediment for [#869](https://github.com/yegor256/takes/issues/869) was registered successfully by @fanifieiev[/z](https://www.0crat.com/u/fanifieiev)

**Comment by 0pdd** [comment]
The puzzle `800-fe5f523c` has disappeared from the source code, that's why I closed this issue.

**Comment by 0crat** [comment]
@sereshqua[/z](https://www.0crat.com/u/sereshqua) please review this job completed by @fanifieiev[/z](https://www.0crat.com/u/fanifieiev), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by 0crat** [comment]
The job [#869](https://github.com/yegor256/takes/issues/869) is now out of scope

**Comment by sereshqua** [comment]
@0crat quality good

**Comment by 0crat** [comment]
Order was finished, quality is "good": +35 point(s) just awarded to @fanifieiev[/z](https://www.0crat.com/u/fanifieiev)

**Comment by 0crat** [comment]
Quality review completed: +4 point(s) just awarded to @sereshqua[/z](https://www.0crat.com/u/sereshqua)
