### ISSUE TITLE
Upgrade JUnit to version5 

### ISSUE THREAD

**Issue by krzyk** [yegor256/takes#877]
JUnit 5 has been out for a while, let's upgrade all tests to use it.
It will allow usage of lambdas in few cases, like asserting thrown exception - we should get rid of ExpectedExceptions in the code during the upgrade process and upgrade surefire and failsafe to the latest versions available (there were issues relatetd to JUnit 5 there).

**Comment by 0crat** [comment]
@paulodamaso[/z](https://www.0crat.com/u/paulodamaso) please, pay attention to this issue

**Comment by 0crat** [comment]
Manual assignment of issues is discouraged, see [§19](http://www.zerocracy.com/policy.html#19): -5 point(s) just awarded to @paulodamaso[/z](https://www.0crat.com/u/paulodamaso)

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 point(s) just awarded to @krzyk[/z](https://www.0crat.com/u/krzyk)

**Comment by 0pdd** [comment]
@krzyk the puzzle [#895](https://github.com/yegor256/takes/issues/895) is still not solved.

**Comment by krzyk** [comment]
@oridan almost, but junit-platform-surefire-provider and the other dependency in surefire/failsafe is not needed since surefire/failsafe version 2.22.0 AFAIR

**Comment by oridan** [comment]
@0crat wait for PR #896 be merged.

**Comment by 0crat** [comment]
> @0crat wait for PR #896 be merged. ([here](https://github.com/yegor256/takes/issues/877#issuecomment-447378880))

@oridan The impediment for [#877](https://github.com/yegor256/takes/issues/877) was registered successfully by @oridan[/z](https://www.0crat.com/u/oridan)

**Comment by oridan** [comment]
@krzyk please close this issue.

**Comment by krzyk** [comment]
@oridan thanks

**Comment by 0crat** [comment]
@ypshenychka[/z](https://www.0crat.com/u/ypshenychka) please review this job completed by @oridan[/z](https://www.0crat.com/u/oridan), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by 0crat** [comment]
The job [#877](https://github.com/yegor256/takes/issues/877) is now out of scope

**Comment by ypshenychka** [comment]
@oridan According to our [QA Rules](http://www.zerocracy.com/policy.html#42):
>All commit messages have links to issues

Please add link to this issue into all related commits.

**Comment by oridan** [comment]
@ypshenychka ok, just added.

**Comment by ypshenychka** [comment]
@oridan Did you? I don't see links in most of the commits [here](https://github.com/yegor256/takes/pull/892/commits) and [here](https://github.com/yegor256/takes/pull/896/commits)

**Comment by ypshenychka** [comment]
@oridan Valid point. Then let's leave them as they are now. But please confirm you'll try to follow this rule next time.

**Comment by oridan** [comment]
@ypshenychka I'll follow this rule next time.

**Comment by ypshenychka** [comment]
@oridan thanks

**Comment by ypshenychka** [comment]
@0crat quality acceptable

**Comment by 0crat** [comment]
> @0crat quality acceptable  ([here](https://github.com/yegor256/takes/issues/877#issuecomment-448184291))

@ypshenychka The project doesn't have enough funds, can't make a payment

**Comment by 0crat** [comment]
Order was finished, quality is "acceptable": +30 point(s) just awarded to @oridan[/z](https://www.0crat.com/u/oridan)

**Comment by 0crat** [comment]
Quality review completed: +8 point(s) just awarded to @ypshenychka[/z](https://www.0crat.com/u/ypshenychka)

**Comment by 0pdd** [comment]
@krzyk the only puzzle [#895](https://github.com/yegor256/takes/issues/895) is solved here.
