### ISSUE TITLE
pom.xml:378-383: Finish the upgrade to qulice 0.17.5 by...

### ISSUE THREAD

**Issue by 0pdd** [yegor256/takes#881]
The puzzle `837-e35739d6` from #837 has to be resolved: 

https://github.com/yegor256/takes/blob/c8f3ef2740506815b9c6398f50fb968462ee17d4/pom.xml#L378-L383

The puzzle was created by Victor Noël on 01-Dec-18. 

  

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0crat** [comment]
@paulodamaso[/z](https://www.0crat.com/u/paulodamaso) please, pay attention to this issue

**Comment by 0crat** [comment]
Job [#881](https://github.com/yegor256/takes/issues/881) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
The job [#881](https://github.com/yegor256/takes/issues/881) assigned to @victornoel[/z](https://www.0crat.com/u/victornoel), here is [why](https://www.0crat.com/footprint/C3FFK3YAY/f56df3bb-bafe-47d5-8170-79be2905a9e4); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be a monetary reward for this job

**Comment by victornoel** [comment]
@0crat refuse

**Comment by 0crat** [comment]
> @0crat refuse ([here](https://github.com/yegor256/takes/issues/881#issuecomment-444217628))

@victornoel The user @victornoel[/z](https://www.0crat.com/u/victornoel) resigned from [#881](https://github.com/yegor256/takes/issues/881), please stop working. Reason for job resignation: Order was cancelled

**Comment by 0crat** [comment]
Tasks refusal is discouraged, see [§6](http://www.zerocracy.com/policy.html#6): -15 point(s) just awarded to @victornoel[/z](https://www.0crat.com/u/victornoel)

**Comment by 0crat** [comment]
The job [#881](https://github.com/yegor256/takes/issues/881) assigned to @krzyk[/z](https://www.0crat.com/u/krzyk), here is [why](https://www.0crat.com/footprint/C3FFK3YAY/4a01eef3-6219-4799-bfd6-b5979034f5cb); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be a monetary reward for this job

**Comment by krzyk** [comment]
@0crat waiting for review of PR #883

**Comment by 0crat** [comment]
> @0crat waiting for review of PR #883  ([here](https://github.com/yegor256/takes/issues/881#issuecomment-444819472))

@krzyk The impediment for [#881](https://github.com/yegor256/takes/issues/881) was registered successfully by @krzyk[/z](https://www.0crat.com/u/krzyk)

**Comment by 0pdd** [comment]
The puzzle `837-e35739d6` has disappeared from the source code, that's why I closed this issue.

**Comment by 0crat** [comment]
@ypshenychka[/z](https://www.0crat.com/u/ypshenychka) please review this job completed by @krzyk[/z](https://www.0crat.com/u/krzyk), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by 0crat** [comment]
The job [#881](https://github.com/yegor256/takes/issues/881) is now out of scope

**Comment by ypshenychka** [comment]
@0crat quality good
