### ISSUE TITLE
Body.java:41-45: Make Body extends Cactoos's Input and...

### ISSUE THREAD

**Issue by 0pdd** [yegor256/takes#887]
The puzzle `804-84fdf636` from #804 has to be resolved: 

https://github.com/yegor256/takes/blob/1d43de35261ec3d5a3ee11ce6f156e35a752131a/src/main/java/org/takes/rs/Body.java#L41-L45

The puzzle was created by Victor Noël on 24-Nov-18. 

  

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0crat** [comment]
@paulodamaso[/z](https://www.0crat.com/u/paulodamaso) please, pay attention to this issue

**Comment by 0crat** [comment]
Job [#887](https://github.com/yegor256/takes/issues/887) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
The job [#887](https://github.com/yegor256/takes/issues/887) assigned to @serranya[/z](https://www.0crat.com/u/serranya), here is [why](https://www.0crat.com/footprint/C3FFK3YAY/fcb3fae3-fba0-4d03-8475-797e6bf57f35); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be no monetary reward for this job

**Comment by Serranya** [comment]
@paulodamaso 0crat is having a problem with the order because it was not closed by 0pdd.

**Comment by paulodamaso** [comment]
@

**Comment by 0crat** [comment]
@paulodamaso[/z](https://www.0crat.com/u/paulodamaso) please, pay attention to this issue

**Comment by 0crat** [comment]
There is an unrecoverable failure on my side. Please, submit it [here](https://github.com/zerocracy/farm/issues):

```
PID: 4@5ecee4b5-963f-435a-bf76-8ef766d115fe, thread: AsyncProc-7
com.jcabi.xml.StrictXML[124] java.lang.IllegalArgumentException: 1 error(s) in XML document: -1:-1: Duplicate unique value [gh:yegor256/takes#887] declared for identity constraint of element "verbosity".
```

[0.40.7](https://github.com/zerocracy/farm): CID: [43a64dc6-a15c-4d64-a4cd-7920c3d2a040](https://www.0crat.com/footprint/C3FFK3YAY/43a64dc6-a15c-4d64-a4cd-7920c3d2a040), Type: "Close job"

**Comment by 0crat** [comment]
@ypshenychka[/z](https://www.0crat.com/u/ypshenychka) please review this job completed by @serranya[/z](https://www.0crat.com/u/serranya), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by 0crat** [comment]
The job [#887](https://github.com/yegor256/takes/issues/887) is now out of scope

**Comment by ypshenychka** [comment]
@Serranya According to our [QA Rules](http://www.zerocracy.com/policy.html#42):
>All commit messages have links to issues

Your commits don't contain link to issue. Please confirm you'll try to follow this rule in future.

**Comment by Serranya** [comment]
@ypshenychka Will do. I mistakingly thought it's enough to link from the PR to the issue.

**Comment by ypshenychka** [comment]
@Serranya thanks

**Comment by ypshenychka** [comment]
@0crat quality acceptable
