### ISSUE TITLE
Utf8String.java:31-35: Make this implements Cactoos Bytes...

### ISSUE THREAD

**Issue by 0pdd** [yegor256/takes#889]
The puzzle `804-8078cfde` from #804 has to be resolved: 

https://github.com/yegor256/takes/blob/1d43de35261ec3d5a3ee11ce6f156e35a752131a/src/main/java/org/takes/misc/Utf8String.java#L31-L35

The puzzle was created by Victor Noël on 24-Nov-18. 

  

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0crat** [comment]
@paulodamaso[/z](https://www.0crat.com/u/paulodamaso) please, pay attention to this issue

**Comment by 0crat** [comment]
Job [#889](https://github.com/yegor256/takes/issues/889) is now in scope, role is `DEV`

**Comment by 0pdd** [comment]
The puzzle `804-8078cfde` has disappeared from the source code, that's why I closed this issue.

**Comment by 0crat** [comment]
Job `gh:yegor256/takes#889` is not assigned, can't get performer

**Comment by 0crat** [comment]
The job [#889](https://github.com/yegor256/takes/issues/889) is now out of scope
