### ISSUE TITLE
Make tests OO

### ISSUE THREAD

**Issue by paulodamaso** [yegor256/takes#893]
Right now we are using a lot of static matchers from hamcrest. Let's make those tests more object-oriented. See https://github.com/yegor256/cactoos/issues/588 , where this was applied to cactoos project.

**Comment by 0crat** [comment]
> @0crat in ([here](https://github.com/yegor256/takes/issues/893#issuecomment-446426826))

@paulodamaso Job [#893](https://github.com/yegor256/takes/issues/893) is now in scope, role is `DEV`

**Comment by paulodamaso** [comment]
@0crat assign @marceloamadeu

**Comment by 0crat** [comment]
> @0crat in ([here](https://github.com/yegor256/takes/issues/893#issuecomment-446426826))

@paulodamaso There is an unrecoverable failure on my side. Please, submit it [here](https://github.com/zerocracy/farm/issues):

```
PID: 4@041da5f8-f9e0-45ec-8176-7f0140d878bb, thread: AsyncProc-4
com.zerocracy.farm.reactive.StkRuntime[76] java.lang.IllegalStateException: org.codehaus.groovy.runtime.InvokerInvocationException in com.zerocracy.stk.pm.cost.funding.send_zold
org.codehaus.groovy.reflection.CachedMethod[105] org.codehaus.groovy.runtime.InvokerInvocationException: groovy.lang.MissingMethodException: No signature of method: com.zerocracy.pmo.banks.Zold.pay() is applicable for argument types: (java.lang.String, com.zerocracy.cash.Cash$S, java.lang.String) values: [paulodamaso, $4.00, none]
Possible solutions: pay(java.lang.String, com.zerocracy.cash.Cash, java.lang.String, java.lang.String), any(), wait(), find(), dump(), grep()
org.codehaus.groovy.runtime.ScriptBytecodeAdapter[71] groovy.lang.MissingMethodException: No signature of method: com.zerocracy.pmo.banks.Zold.pay() is applicable for argument types: (java.lang.String, com.zerocracy.cash.Cash$S, java.lang.String) values: [paulodamaso, $4.00, none]
Possible solutions: pay(java.lang.String, com.zerocracy.cash.Cash, java.lang.String, java.lang.String), any(), wait(), find(), dump(), grep()
```

[0.39.6](https://github.com/zerocracy/farm): CID: [d4286ab9-e35d-4cbb-857a-be32f05f5f95](https://www.0crat.com/footprint/C3FFK3YAY/d4286ab9-e35d-4cbb-857a-be32f05f5f95), Type: "Send zold"

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 point(s) just awarded to @paulodamaso[/z](https://www.0crat.com/u/paulodamaso)

**Comment by 0crat** [comment]
> @0crat assign @marceloamadeu ([here](https://github.com/yegor256/takes/issues/893#issuecomment-446427469))

@paulodamaso The job [#893](https://github.com/yegor256/takes/issues/893) assigned to @marceloamadeu[/z](https://www.0crat.com/u/marceloamadeu), here is [why](https://www.0crat.com/footprint/C3FFK3YAY/3acef4f6-2180-4264-9386-874233d96c3f); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be no monetary reward for this job

**Comment by 0crat** [comment]
Manual assignment of issues is discouraged, see [§19](http://www.zerocracy.com/policy.html#19): -5 point(s) just awarded to @paulodamaso[/z](https://www.0crat.com/u/paulodamaso)

**Comment by marceloamadeu** [comment]
@0crat wait

**Comment by 0crat** [comment]
> @0crat wait ([here](https://github.com/yegor256/takes/issues/893#issuecomment-449218379))

@marceloamadeu The impediment for [#893](https://github.com/yegor256/takes/issues/893) was registered successfully by @marceloamadeu[/z](https://www.0crat.com/u/marceloamadeu)

**Comment by 0pdd** [comment]
@paulodamaso the puzzle [#948](https://github.com/yegor256/takes/issues/948) is still not solved.

**Comment by marceloamadeu** [comment]
@0crat status

**Comment by 0crat** [comment]
> @0crat status ([here](https://github.com/yegor256/takes/issues/893#issuecomment-454918069))

@marceloamadeu This is what I know about this job in [C3FFK3YAY](https://www.0crat.com/p/C3FFK3YAY), as in [§32](http://www.zerocracy.com/policy.html#32):

  * The job [#893](https://github.com/yegor256/takes/issues/893) is [in scope](http://www.zerocracy.com/policy.html#14) for 1mon
  * The role is `DEV`
  * The job is assigned to @marceloamadeu[/z](https://www.0crat.com/u/marceloamadeu) for [1mon](http://www.zerocracy.com/policy.html#8)
  * There is no monetary reward attached, it's a [free](http://www.zerocracy.com/policy.html#2) job
  * The job has an [impediment](http://www.zerocracy.com/policy.html#9)
  * The [budget](http://www.zerocracy.com/policy.html#4) is 30 minutes/points
  * These users are banned and won't be assigned:
    * @paulodamaso[/z](https://www.0crat.com/u/paulodamaso): This user reported the ticket
  * Job [footprint](https://www.0crat.com/footprint/C3FFK3YAY?q=%7Bjob%3A%27gh%3Ayegor256%2Ftakes%23893%27%2Ctype%3A%7B%24not%3A%2F%5ENotify%2F%7D%7D) (restricted area)

**Comment by marceloamadeu** [comment]
@paulodamaso Done!

**Comment by paulodamaso** [comment]
@marceloamadeu thanks!

**Comment by paulodamaso** [comment]
@0crat status

**Comment by 0crat** [comment]
> @0crat status ([here](https://github.com/yegor256/takes/issues/893#issuecomment-456481040))

@paulodamaso This is what I know about this job in [C3FFK3YAY](https://www.0crat.com/p/C3FFK3YAY), as in [§32](http://www.zerocracy.com/policy.html#32):

  * The job [#893](https://github.com/yegor256/takes/issues/893) is [in scope](http://www.zerocracy.com/policy.html#14) for 1mon
  * The role is `DEV`
  * The job is assigned to @marceloamadeu[/z](https://www.0crat.com/u/marceloamadeu) for [1mon](http://www.zerocracy.com/policy.html#8)
  * There is no monetary reward attached, it's a [free](http://www.zerocracy.com/policy.html#2) job
  * The job has an [impediment](http://www.zerocracy.com/policy.html#9)
  * The [budget](http://www.zerocracy.com/policy.html#4) is 30 minutes/points
  * These users are banned and won't be assigned:
    * @paulodamaso[/z](https://www.0crat.com/u/paulodamaso): This user reported the ticket
  * Job [footprint](https://www.0crat.com/footprint/C3FFK3YAY?q=%7Bjob%3A%27gh%3Ayegor256%2Ftakes%23893%27%2Ctype%3A%7B%24not%3A%2F%5ENotify%2F%7D%7D) (restricted area)

**Comment by ypshenychka** [comment]
@marceloamadeu ping

**Comment by marceloamadeu** [comment]
> @marceloamadeu According to our [QA Rules](http://www.zerocracy.com/policy.html#42):
> 
> > All commit messages have links to issues
> 
> Your commits do not contain link to this issue. Please confirm you'll tro to follow this rule next time.

@ypshenychka Confirmed.

**Comment by marceloamadeu** [comment]
> @marceloamadeu According to our [QA Rules](http://www.zerocracy.com/policy.html#42):
> 
> > All impediments registered in the ticket have explanations of the reasons and links to related tickets, if necessary
> 
> Please add more details to the registered [impediment](https://github.com/yegor256/takes/issues/893#issuecomment-449218379).

@ypshenychka I am still adapting the way I work and so I asked for more time to complete the task. I will try to do it as soon as possible in the next tasks.

**Comment by marceloamadeu** [comment]
@ypshenychka ping

**Comment by ypshenychka** [comment]
@marceloamadeu Then please edit your "wait" comment to contain more details (e.g. "wait. Need more time for investigation") or anything that is applicable to your specific situation, to explain, why you suspended 10 days rule

**Comment by marceloamadeu** [comment]
@ypshenychka ping

**Comment by ypshenychka** [comment]
@marceloamadeu thanks

**Comment by ypshenychka** [comment]
@0crat quality acceptable

**Comment by 0crat** [comment]
> @0crat quality acceptable ([here](https://github.com/yegor256/takes/issues/893#issuecomment-457209510))

@ypshenychka The project doesn't have enough funds, can't make a payment

**Comment by 0crat** [comment]
Order was finished, quality is "acceptable": +30 point(s) just awarded to @marceloamadeu[/z](https://www.0crat.com/u/marceloamadeu)

**Comment by 0crat** [comment]
Quality review completed: +8 point(s) just awarded to @ypshenychka[/z](https://www.0crat.com/u/ypshenychka)

**Comment by 0pdd** [comment]
@paulodamaso the puzzle [#unknown]() is still not solved.

**Comment by 0pdd** [comment]
@paulodamaso the only puzzle [#948](https://github.com/yegor256/takes/issues/948) is solved here.
