### ISSUE TITLE
CcStrictTest.java:42-46: replace all org.junit.Test...

### ISSUE THREAD

**Issue by 0pdd** [yegor256/takes#895]
The puzzle `877-052482c8` from #877 has to be resolved: 

https://github.com/yegor256/takes/blob/bdec6c9601b2e13c16633669525e9dde8958bbf5/src/test/java/org/takes/facets/auth/codecs/CcStrictTest.java#L42-L46

The puzzle was created by oridan on 14-Dec-18. 

  

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0crat** [comment]
@paulodamaso[/z](https://www.0crat.com/u/paulodamaso) please, pay attention to this issue

**Comment by 0crat** [comment]
The job [#895](https://github.com/yegor256/takes/issues/895) assigned to @marceloamadeu[/z](https://www.0crat.com/u/marceloamadeu), here is [why](https://www.0crat.com/footprint/C3FFK3YAY/b92283da-e5d9-4862-82f8-f37e0fe0e25f); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be no monetary reward for this job

**Comment by marceloamadeu** [comment]
@0crat status

**Comment by 0crat** [comment]
> @0crat status ([here](https://github.com/yegor256/takes/issues/895#issuecomment-462324472))

@marceloamadeu This is what I know about this job in [C3FFK3YAY](https://www.0crat.com/p/C3FFK3YAY), as in [§32](http://www.zerocracy.com/policy.html#32):

  * The job [#895](https://github.com/yegor256/takes/issues/895) is [in scope](http://www.zerocracy.com/policy.html#14) for 2mon
  * The role is `DEV`
  * The job is assigned to @marceloamadeu[/z](https://www.0crat.com/u/marceloamadeu) for [5days](http://www.zerocracy.com/policy.html#8)
  * There is no monetary reward attached, it's a [free](http://www.zerocracy.com/policy.html#2) job
  * The job doesn't have any [impediments](http://www.zerocracy.com/policy.html#9)
  * The [budget](http://www.zerocracy.com/policy.html#4) is 30 minutes/points
  * These users are banned and won't be assigned:
    * @0pdd[/z](https://www.0crat.com/u/0pdd): This user reported the ticket
  * Job [footprint](https://www.0crat.com/footprint/C3FFK3YAY?q=%7Bjob%3A%27gh%3Ayegor256%2Ftakes%23895%27%2Ctype%3A%7B%24not%3A%2F%5ENotify%2F%7D%7D) (restricted area)

**Comment by marceloamadeu** [comment]
@paulodamaso please take a look at this

**Comment by marceloamadeu** [comment]
@paulodamaso please take a look at this

**Comment by marceloamadeu** [comment]
@0crat status

**Comment by 0crat** [comment]
> @0crat status ([here](https://github.com/yegor256/takes/issues/895#issuecomment-468631394))

@marceloamadeu This is what I know about this job in [C3FFK3YAY](https://www.0crat.com/p/C3FFK3YAY), as in [§32](http://www.zerocracy.com/policy.html#32):

  * The job [#895](https://github.com/yegor256/takes/issues/895) is [in scope](http://www.zerocracy.com/policy.html#14) for 3mon
  * The role is `DEV`
  * The job is assigned to @marceloamadeu[/z](https://www.0crat.com/u/marceloamadeu) for [23days](http://www.zerocracy.com/policy.html#8)
  * There is no monetary reward attached, it's a [free](http://www.zerocracy.com/policy.html#2) job
  * The job doesn't have any [impediments](http://www.zerocracy.com/policy.html#9)
  * The [budget](http://www.zerocracy.com/policy.html#4) is 30 minutes/points
  * These users are banned and won't be assigned:
    * @0pdd[/z](https://www.0crat.com/u/0pdd): This user reported the ticket
  * Job [footprint](https://www.0crat.com/footprint/C3FFK3YAY?q=%7Bjob%3A%27gh%3Ayegor256%2Ftakes%23895%27%2Ctype%3A%7B%24not%3A%2F%5ENotify%2F%7D%7D) (restricted area)

**Comment by marceloamadeu** [comment]
@0crat refuse

**Comment by 0crat** [comment]
> @0crat refuse ([here](https://github.com/yegor256/takes/issues/895#issuecomment-477388829))

@marceloamadeu The user @marceloamadeu[/z](https://www.0crat.com/u/marceloamadeu) resigned from [#895](https://github.com/yegor256/takes/issues/895), please stop working. Reason for job resignation: Order was cancelled

**Comment by 0crat** [comment]
Tasks refusal is discouraged, see [§6](http://www.zerocracy.com/policy.html#6): -15 point(s) just awarded to @marceloamadeu[/z](https://www.0crat.com/u/marceloamadeu)

**Comment by 0crat** [comment]
The job [#895](https://github.com/yegor256/takes/issues/895) assigned to @fabriciofx[/z](https://www.0crat.com/u/fabriciofx), here is [why](https://www.0crat.com/footprint/C3FFK3YAY/1b042e14-e560-4385-975d-f23309b94672); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be no monetary reward for this job

**Comment by andreoss** [comment]
@0crat wait for #1077

**Comment by andreoss** [comment]
@0crat wait for 1077

**Comment by 0crat** [comment]
> @0crat wait for 1077 ([here](https://github.com/yegor256/takes/issues/895#issuecomment-697632030))

@andreoss Job [#895](https://github.com/yegor256/takes/issues/895) is already on hold

**Comment by andreoss** [comment]
@0crat in

**Comment by 0crat** [comment]
> @0crat in ([here](https://github.com/yegor256/takes/issues/895#issuecomment-799133730))

@andreoss You can't do "Add job to WBS", unless you have one of these roles: `ARC`, `PO`; current roles of @andreoss[/z](https://www.0crat.com/u/andreoss) are: `DEV`, `REV`

**Comment by andreoss** [comment]
@0crat status

**Comment by 0crat** [comment]
> @0crat status ([here](https://github.com/yegor256/takes/issues/895#issuecomment-826362930))

@andreoss This is what I know about this job in C3FFK3YAY, as in [§32](http://www.zerocracy.com/policy.html#32):

  * The job [#895](https://github.com/yegor256/takes/issues/895) is [in scope](http://www.zerocracy.com/policy.html#14) for 29mon
  * The role is `DEV`
  * The job is assigned to @andreoss[/z](https://www.0crat.com/u/andreoss) for [7mon](http://www.zerocracy.com/policy.html#8)
  * There is no monetary reward attached, it's a [free](http://www.zerocracy.com/policy.html#2) job
  * The job has an [impediment](http://www.zerocracy.com/policy.html#9)
  * The [budget](http://www.zerocracy.com/policy.html#4) is 30 minutes/points
  * These users are banned and won't be assigned:
    * @0pdd[/z](https://www.0crat.com/u/0pdd): This user reported the ticket
    * @marceloamadeu[/z](https://www.0crat.com/u/marceloamadeu): User was resigned from the ticket
    * @fabriciofx[/z](https://www.0crat.com/u/fabriciofx): User was resigned from the ticket
  * Job [footprint](https://www.0crat.com/footprint/C3FFK3YAY?q=%7Bjob%3A%27gh%3Ayegor256%2Ftakes%23895%27%2Ctype%3A%7B%24not%3A%2F%5ENotify%2F%7D%7D) (restricted area)

**Comment by 0pdd** [comment]
The puzzle `877-052482c8` has disappeared from the source code, that's why I closed this issue.

**Comment by 0crat** [comment]
@sereshqua[/z](https://www.0crat.com/u/sereshqua) please review this job completed by @andreoss[/z](https://www.0crat.com/u/andreoss), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed
