### ISSUE TITLE
log4j appender implemented as JUnit rule

### ISSUE THREAD

**Issue by dmzaytsev** [yegor256/takes#90]
log4j appender implemented as JUnit rule

I use mocked log4j appender in the unit test and check log output like this

    Mockito.verify(appender)
       .doAppend(
           Matchers.argThat(
              new ArgumentMatcher<LoggingEvent>() {
                  @Override
                  public boolean matches(final Object argument) {
                      return ((LoggingEvent) argument)
                              .getRenderedMessage()
                              .matches("^.*accept.*$");

I got comment from my reviewer that "matching looks a bit glibly".

He suggest to create custom log4j appender as JUnit rule [see more](https://github.com/yegor256/takes/pull/89#discussion_r27354036)

**Comment by yegor256** [comment]
@dmzaytsev again, the description of the ticket sounds like a **task**, but it should be a **bug**. You should say what is broken and it's up to "us" how to solve it. You should say that you miss something in the project, or something doesn't work as you expect, etc.

**Comment by dmzaytsev** [comment]
This is no longer necessary
