### ISSUE TITLE
There are some classes not closed to inheritance (final)

### ISSUE THREAD

**Issue by fabriciofx** [yegor256/takes#911]
The classes `PsAll`, `TkMethods`, `RsFailure`, `Transform`, `Utf8InputStreamReader`, `Utf8InputStreamWriter`, `Utf8PrintStream`, `RqSimple` and `RsSimple` aren't close to inheritance (`final` keyword). So, following the EO principles, they should be.

**Comment by 0crat** [comment]
@paulodamaso[/z](https://www.0crat.com/u/paulodamaso) please, pay attention to this issue

**Comment by 0crat** [comment]
Job [#911](https://github.com/yegor256/takes/issues/911) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 point(s) just awarded to @fabriciofx[/z](https://www.0crat.com/u/fabriciofx)

**Comment by 0crat** [comment]
The job [#911](https://github.com/yegor256/takes/issues/911) assigned to @serranya[/z](https://www.0crat.com/u/serranya), here is [why](https://www.0crat.com/footprint/C3FFK3YAY/01808984-542e-469d-b29f-7be6bcb35d80); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be no monetary reward for this job

**Comment by Serranya** [comment]
@fabriciofx With #969 merged can this be closed?

**Comment by paulodamaso** [comment]
@Serranya I'll close it, thanks for the resolution

**Comment by 0crat** [comment]
@ypshenychka[/z](https://www.0crat.com/u/ypshenychka) please review this job completed by @serranya[/z](https://www.0crat.com/u/serranya), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by 0crat** [comment]
Job [#911](https://github.com/yegor256/takes/issues/911) is not in the agenda of @serranya[/z](https://www.0crat.com/u/serranya), can't inspect

**Comment by 0crat** [comment]
The job [#911](https://github.com/yegor256/takes/issues/911) is now out of scope

**Comment by ypshenychka** [comment]
@0crat quality good

**Comment by 0crat** [comment]
> @0crat quality good ([here](https://github.com/yegor256/takes/issues/911#issuecomment-468027163))

@ypshenychka The project doesn't have enough funds, can't make a payment

**Comment by 0crat** [comment]
Order was finished, quality is "good": +35 point(s) just awarded to @serranya[/z](https://www.0crat.com/u/serranya)

**Comment by 0crat** [comment]
Quality review completed: +8 point(s) just awarded to @ypshenychka[/z](https://www.0crat.com/u/ypshenychka)
