### ISSUE TITLE
Remove EqualsVerifier from tests

### ISSUE THREAD

**Issue by fabriciofx** [yegor256/takes#918]
There are some tests using EqualsVerifier framework. IMHO, it can be substituted using tools already used, as hamcrest and others.

**Comment by 0crat** [comment]
@paulodamaso[/z](https://www.0crat.com/u/paulodamaso) please, pay attention to this issue

**Comment by paulodamaso** [comment]
@yegor256 I agree, I think that we should depend a little as possible of non-elegant frameworks. WDYT?

**Comment by yegor256** [comment]
@paulodamaso I agree, let's get rid of that

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 point(s) just awarded to @fabriciofx[/z](https://www.0crat.com/u/fabriciofx)

**Comment by 0crat** [comment]
The job [#918](https://github.com/yegor256/takes/issues/918) assigned to @lucasmessias9898[/z](https://www.0crat.com/u/lucasmessias9898), here is [why](https://www.0crat.com/footprint/C3FFK3YAY/e29cf176-3068-4ac9-ad5a-216e9dd40e17); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be no monetary reward for this job

**Comment by lucasmessias9898** [comment]
@0crat refuse

**Comment by 0crat** [comment]
> @0crat refuse ([here](https://github.com/yegor256/takes/issues/918#issuecomment-490999213))

@lucasmessias9898 The user @lucasmessias9898[/z](https://www.0crat.com/u/lucasmessias9898) resigned from [#918](https://github.com/yegor256/takes/issues/918), please stop working. Reason for job resignation: Order was cancelled

**Comment by 0crat** [comment]
Tasks refusal is discouraged, see [§6](http://www.zerocracy.com/policy.html#6): -15 point(s) just awarded to @lucasmessias9898[/z](https://www.0crat.com/u/lucasmessias9898)

**Comment by 0crat** [comment]
The job [#918](https://github.com/yegor256/takes/issues/918) assigned to @ebercamargo[/z](https://www.0crat.com/u/ebercamargo), here is [why](https://www.0crat.com/footprint/C3FFK3YAY/9a5ca876-477f-49e0-a89d-4079944bed54); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be no monetary reward for this job

**Comment by ebercamargo** [comment]
@0crat wait I'm short on time, I ask you to wait so I can handle it in the near future.

**Comment by 0crat** [comment]
> @0crat wait I'm short on time, I ask you to wait so I can handle it in the near future. ([here](https://github.com/yegor256/takes/issues/918#issuecomment-496538535))

@ebercamargo The impediment for [#918](https://github.com/yegor256/takes/issues/918) was registered successfully by @ebercamargo[/z](https://www.0crat.com/u/ebercamargo)

**Comment by 0crat** [comment]
The job [#918](https://github.com/yegor256/takes/issues/918) assigned to @marceloamadeu[/z](https://www.0crat.com/u/marceloamadeu), here is [why](https://www.0crat.com/footprint/C3FFK3YAY/11289e1f-0eae-409b-9f40-09789aed1c01); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be no monetary reward for this job

**Comment by marceloamadeu** [comment]
@0crat refuse

**Comment by 0crat** [comment]
> @0crat refuse ([here](https://github.com/yegor256/takes/issues/918#issuecomment-506023974))

@marceloamadeu The user @marceloamadeu[/z](https://www.0crat.com/u/marceloamadeu) resigned from [#918](https://github.com/yegor256/takes/issues/918), please stop working. Reason for job resignation: Order was cancelled

**Comment by 0crat** [comment]
Tasks refusal is discouraged, see [§6](http://www.zerocracy.com/policy.html#6): -15 point(s) just awarded to @marceloamadeu[/z](https://www.0crat.com/u/marceloamadeu)

**Comment by 0crat** [comment]
The job [#918](https://github.com/yegor256/takes/issues/918) assigned to @protagores[/z](https://www.0crat.com/u/protagores), here is [why](https://www.0crat.com/footprint/C3FFK3YAY/ce9c46cf-2675-456d-9f77-8630154453ad); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be no monetary reward for this job

**Comment by 0crat** [comment]
> @0crat refuse ([here](https://github.com/yegor256/takes/issues/918#issuecomment-547117675))

@Protagores The user @protagores[/z](https://www.0crat.com/u/protagores) resigned from [#918](https://github.com/yegor256/takes/issues/918), please stop working. Reason for job resignation: Order was cancelled

**Comment by 0crat** [comment]
Tasks refusal is discouraged (job refused in 149 hours), see [§6](http://www.zerocracy.com/policy.html#6): -20 point(s) just awarded to @protagores[/z](https://www.0crat.com/u/protagores)

**Comment by 0crat** [comment]
The job [#918](https://github.com/yegor256/takes/issues/918) assigned to @fanifieiev[/z](https://www.0crat.com/u/fanifieiev), here is [why](https://www.0crat.com/footprint/C3FFK3YAY/d2b49d4c-6e03-4aa3-9e35-1a0ec8911740); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be no monetary reward for this job

**Comment by 0pdd** [comment]
@fabriciofx 3 puzzles [#1000](https://github.com/yegor256/takes/issues/1000), [#998](https://github.com/yegor256/takes/issues/998), [#999](https://github.com/yegor256/takes/issues/999) are still not solved.

**Comment by 0crat** [comment]
@sereshqua[/z](https://www.0crat.com/u/sereshqua) please review this job completed by @fanifieiev[/z](https://www.0crat.com/u/fanifieiev), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by 0crat** [comment]
The job [#918](https://github.com/yegor256/takes/issues/918) is now out of scope

**Comment by sereshqua** [comment]
@0crat quality good

**Comment by 0crat** [comment]
Order was finished, quality is "good": +35 point(s) just awarded to @fanifieiev[/z](https://www.0crat.com/u/fanifieiev)

**Comment by 0crat** [comment]
Quality review completed: +4 point(s) just awarded to @sereshqua[/z](https://www.0crat.com/u/sereshqua)

**Comment by 0pdd** [comment]
@fabriciofx 15 puzzles [#1000](https://github.com/yegor256/takes/issues/1000), [#1008](https://github.com/yegor256/takes/issues/1008), [#1009](https://github.com/yegor256/takes/issues/1009), [#1010](https://github.com/yegor256/takes/issues/1010), [#1011](https://github.com/yegor256/takes/issues/1011), [#1012](https://github.com/yegor256/takes/issues/1012), [#1013](https://github.com/yegor256/takes/issues/1013), [#1014](https://github.com/yegor256/takes/issues/1014), [#1015](https://github.com/yegor256/takes/issues/1015), [#1016](https://github.com/yegor256/takes/issues/1016), [#1017](https://github.com/yegor256/takes/issues/1017), [#1018](https://github.com/yegor256/takes/issues/1018), [#1019](https://github.com/yegor256/takes/issues/1019), [#998](https://github.com/yegor256/takes/issues/998), [#999](https://github.com/yegor256/takes/issues/999) are still not solved.

**Comment by 0pdd** [comment]
@fabriciofx 14 puzzles [#1000](https://github.com/yegor256/takes/issues/1000), [#1008](https://github.com/yegor256/takes/issues/1008), [#1009](https://github.com/yegor256/takes/issues/1009), [#1010](https://github.com/yegor256/takes/issues/1010), [#1011](https://github.com/yegor256/takes/issues/1011), [#1012](https://github.com/yegor256/takes/issues/1012), [#1013](https://github.com/yegor256/takes/issues/1013), [#1014](https://github.com/yegor256/takes/issues/1014), [#1015](https://github.com/yegor256/takes/issues/1015), [#1016](https://github.com/yegor256/takes/issues/1016), [#1017](https://github.com/yegor256/takes/issues/1017), [#1018](https://github.com/yegor256/takes/issues/1018), [#1019](https://github.com/yegor256/takes/issues/1019), [#999](https://github.com/yegor256/takes/issues/999) are still not solved; solved: [#998](https://github.com/yegor256/takes/issues/998).

**Comment by 0pdd** [comment]
@fabriciofx 13 puzzles [#1000](https://github.com/yegor256/takes/issues/1000), [#1008](https://github.com/yegor256/takes/issues/1008), [#1009](https://github.com/yegor256/takes/issues/1009), [#1011](https://github.com/yegor256/takes/issues/1011), [#1012](https://github.com/yegor256/takes/issues/1012), [#1013](https://github.com/yegor256/takes/issues/1013), [#1014](https://github.com/yegor256/takes/issues/1014), [#1015](https://github.com/yegor256/takes/issues/1015), [#1016](https://github.com/yegor256/takes/issues/1016), [#1017](https://github.com/yegor256/takes/issues/1017), [#1018](https://github.com/yegor256/takes/issues/1018), [#1019](https://github.com/yegor256/takes/issues/1019), [#999](https://github.com/yegor256/takes/issues/999) are still not solved; solved: [#1010](https://github.com/yegor256/takes/issues/1010), [#998](https://github.com/yegor256/takes/issues/998).

**Comment by 0pdd** [comment]
@fabriciofx 12 puzzles [#1000](https://github.com/yegor256/takes/issues/1000), [#1008](https://github.com/yegor256/takes/issues/1008), [#1009](https://github.com/yegor256/takes/issues/1009), [#1011](https://github.com/yegor256/takes/issues/1011), [#1012](https://github.com/yegor256/takes/issues/1012), [#1014](https://github.com/yegor256/takes/issues/1014), [#1015](https://github.com/yegor256/takes/issues/1015), [#1016](https://github.com/yegor256/takes/issues/1016), [#1017](https://github.com/yegor256/takes/issues/1017), [#1018](https://github.com/yegor256/takes/issues/1018), [#1019](https://github.com/yegor256/takes/issues/1019), [#999](https://github.com/yegor256/takes/issues/999) are still not solved; solved: [#1010](https://github.com/yegor256/takes/issues/1010), [#1013](https://github.com/yegor256/takes/issues/1013), [#998](https://github.com/yegor256/takes/issues/998).

**Comment by 0pdd** [comment]
@fabriciofx 11 puzzles [#1000](https://github.com/yegor256/takes/issues/1000), [#1009](https://github.com/yegor256/takes/issues/1009), [#1011](https://github.com/yegor256/takes/issues/1011), [#1012](https://github.com/yegor256/takes/issues/1012), [#1014](https://github.com/yegor256/takes/issues/1014), [#1015](https://github.com/yegor256/takes/issues/1015), [#1016](https://github.com/yegor256/takes/issues/1016), [#1017](https://github.com/yegor256/takes/issues/1017), [#1018](https://github.com/yegor256/takes/issues/1018), [#1019](https://github.com/yegor256/takes/issues/1019), [#999](https://github.com/yegor256/takes/issues/999) are still not solved; solved: [#1008](https://github.com/yegor256/takes/issues/1008), [#1010](https://github.com/yegor256/takes/issues/1010), [#1013](https://github.com/yegor256/takes/issues/1013), [#998](https://github.com/yegor256/takes/issues/998).

**Comment by 0pdd** [comment]
@fabriciofx 10 puzzles [#1000](https://github.com/yegor256/takes/issues/1000), [#1009](https://github.com/yegor256/takes/issues/1009), [#1012](https://github.com/yegor256/takes/issues/1012), [#1014](https://github.com/yegor256/takes/issues/1014), [#1015](https://github.com/yegor256/takes/issues/1015), [#1016](https://github.com/yegor256/takes/issues/1016), [#1017](https://github.com/yegor256/takes/issues/1017), [#1018](https://github.com/yegor256/takes/issues/1018), [#1019](https://github.com/yegor256/takes/issues/1019), [#999](https://github.com/yegor256/takes/issues/999) are still not solved; solved: [#1008](https://github.com/yegor256/takes/issues/1008), [#1010](https://github.com/yegor256/takes/issues/1010), [#1011](https://github.com/yegor256/takes/issues/1011), [#1013](https://github.com/yegor256/takes/issues/1013), [#998](https://github.com/yegor256/takes/issues/998).

**Comment by 0pdd** [comment]
@fabriciofx 9 puzzles [#1000](https://github.com/yegor256/takes/issues/1000), [#1009](https://github.com/yegor256/takes/issues/1009), [#1014](https://github.com/yegor256/takes/issues/1014), [#1015](https://github.com/yegor256/takes/issues/1015), [#1016](https://github.com/yegor256/takes/issues/1016), [#1017](https://github.com/yegor256/takes/issues/1017), [#1018](https://github.com/yegor256/takes/issues/1018), [#1019](https://github.com/yegor256/takes/issues/1019), [#999](https://github.com/yegor256/takes/issues/999) are still not solved; solved: [#1008](https://github.com/yegor256/takes/issues/1008), [#1010](https://github.com/yegor256/takes/issues/1010), [#1011](https://github.com/yegor256/takes/issues/1011), [#1012](https://github.com/yegor256/takes/issues/1012), [#1013](https://github.com/yegor256/takes/issues/1013), [#998](https://github.com/yegor256/takes/issues/998).

**Comment by 0pdd** [comment]
@fabriciofx 8 puzzles [#1000](https://github.com/yegor256/takes/issues/1000), [#1009](https://github.com/yegor256/takes/issues/1009), [#1014](https://github.com/yegor256/takes/issues/1014), [#1015](https://github.com/yegor256/takes/issues/1015), [#1017](https://github.com/yegor256/takes/issues/1017), [#1018](https://github.com/yegor256/takes/issues/1018), [#1019](https://github.com/yegor256/takes/issues/1019), [#999](https://github.com/yegor256/takes/issues/999) are still not solved; solved: [#1008](https://github.com/yegor256/takes/issues/1008), [#1010](https://github.com/yegor256/takes/issues/1010), [#1011](https://github.com/yegor256/takes/issues/1011), [#1012](https://github.com/yegor256/takes/issues/1012), [#1013](https://github.com/yegor256/takes/issues/1013), [#1016](https://github.com/yegor256/takes/issues/1016), [#998](https://github.com/yegor256/takes/issues/998).

**Comment by 0pdd** [comment]
@fabriciofx 7 puzzles [#1000](https://github.com/yegor256/takes/issues/1000), [#1009](https://github.com/yegor256/takes/issues/1009), [#1014](https://github.com/yegor256/takes/issues/1014), [#1015](https://github.com/yegor256/takes/issues/1015), [#1018](https://github.com/yegor256/takes/issues/1018), [#1019](https://github.com/yegor256/takes/issues/1019), [#999](https://github.com/yegor256/takes/issues/999) are still not solved; solved: [#1008](https://github.com/yegor256/takes/issues/1008), [#1010](https://github.com/yegor256/takes/issues/1010), [#1011](https://github.com/yegor256/takes/issues/1011), [#1012](https://github.com/yegor256/takes/issues/1012), [#1013](https://github.com/yegor256/takes/issues/1013), [#1016](https://github.com/yegor256/takes/issues/1016), [#1017](https://github.com/yegor256/takes/issues/1017), [#998](https://github.com/yegor256/takes/issues/998).

**Comment by 0pdd** [comment]
@fabriciofx 6 puzzles [#1000](https://github.com/yegor256/takes/issues/1000), [#1009](https://github.com/yegor256/takes/issues/1009), [#1014](https://github.com/yegor256/takes/issues/1014), [#1018](https://github.com/yegor256/takes/issues/1018), [#1019](https://github.com/yegor256/takes/issues/1019), [#999](https://github.com/yegor256/takes/issues/999) are still not solved; solved: [#1008](https://github.com/yegor256/takes/issues/1008), [#1010](https://github.com/yegor256/takes/issues/1010), [#1011](https://github.com/yegor256/takes/issues/1011), [#1012](https://github.com/yegor256/takes/issues/1012), [#1013](https://github.com/yegor256/takes/issues/1013), [#1015](https://github.com/yegor256/takes/issues/1015), [#1016](https://github.com/yegor256/takes/issues/1016), [#1017](https://github.com/yegor256/takes/issues/1017), [#998](https://github.com/yegor256/takes/issues/998).

**Comment by 0pdd** [comment]
@fabriciofx 5 puzzles [#1000](https://github.com/yegor256/takes/issues/1000), [#1009](https://github.com/yegor256/takes/issues/1009), [#1014](https://github.com/yegor256/takes/issues/1014), [#1018](https://github.com/yegor256/takes/issues/1018), [#999](https://github.com/yegor256/takes/issues/999) are still not solved; solved: [#1008](https://github.com/yegor256/takes/issues/1008), [#1010](https://github.com/yegor256/takes/issues/1010), [#1011](https://github.com/yegor256/takes/issues/1011), [#1012](https://github.com/yegor256/takes/issues/1012), [#1013](https://github.com/yegor256/takes/issues/1013), [#1015](https://github.com/yegor256/takes/issues/1015), [#1016](https://github.com/yegor256/takes/issues/1016), [#1017](https://github.com/yegor256/takes/issues/1017), [#1019](https://github.com/yegor256/takes/issues/1019), [#998](https://github.com/yegor256/takes/issues/998).

**Comment by 0pdd** [comment]
@fabriciofx 4 puzzles [#1000](https://github.com/yegor256/takes/issues/1000), [#1009](https://github.com/yegor256/takes/issues/1009), [#1018](https://github.com/yegor256/takes/issues/1018), [#999](https://github.com/yegor256/takes/issues/999) are still not solved; solved: [#1008](https://github.com/yegor256/takes/issues/1008), [#1010](https://github.com/yegor256/takes/issues/1010), [#1011](https://github.com/yegor256/takes/issues/1011), [#1012](https://github.com/yegor256/takes/issues/1012), [#1013](https://github.com/yegor256/takes/issues/1013), [#1014](https://github.com/yegor256/takes/issues/1014), [#1015](https://github.com/yegor256/takes/issues/1015), [#1016](https://github.com/yegor256/takes/issues/1016), [#1017](https://github.com/yegor256/takes/issues/1017), [#1019](https://github.com/yegor256/takes/issues/1019), [#998](https://github.com/yegor256/takes/issues/998).

**Comment by 0pdd** [comment]
@fabriciofx 4 puzzles [#1000](https://github.com/yegor256/takes/issues/1000), [#1009](https://github.com/yegor256/takes/issues/1009), [#1018](https://github.com/yegor256/takes/issues/1018), [#1080](https://github.com/yegor256/takes/issues/1080) are still not solved; solved: [#1008](https://github.com/yegor256/takes/issues/1008), [#1010](https://github.com/yegor256/takes/issues/1010), [#1011](https://github.com/yegor256/takes/issues/1011), [#1012](https://github.com/yegor256/takes/issues/1012), [#1013](https://github.com/yegor256/takes/issues/1013), [#1014](https://github.com/yegor256/takes/issues/1014), [#1015](https://github.com/yegor256/takes/issues/1015), [#1016](https://github.com/yegor256/takes/issues/1016), [#1017](https://github.com/yegor256/takes/issues/1017), [#1019](https://github.com/yegor256/takes/issues/1019), [#998](https://github.com/yegor256/takes/issues/998), [#999](https://github.com/yegor256/takes/issues/999).

**Comment by 0pdd** [comment]
@fabriciofx 4 puzzles [#1000](https://github.com/yegor256/takes/issues/1000), [#1009](https://github.com/yegor256/takes/issues/1009), [#1018](https://github.com/yegor256/takes/issues/1018), [#1117](https://github.com/yegor256/takes/issues/1117) are still not solved; solved: [#1008](https://github.com/yegor256/takes/issues/1008), [#1010](https://github.com/yegor256/takes/issues/1010), [#1011](https://github.com/yegor256/takes/issues/1011), [#1012](https://github.com/yegor256/takes/issues/1012), [#1013](https://github.com/yegor256/takes/issues/1013), [#1014](https://github.com/yegor256/takes/issues/1014), [#1015](https://github.com/yegor256/takes/issues/1015), [#1016](https://github.com/yegor256/takes/issues/1016), [#1017](https://github.com/yegor256/takes/issues/1017), [#1019](https://github.com/yegor256/takes/issues/1019), [#1080](https://github.com/yegor256/takes/issues/1080), [#998](https://github.com/yegor256/takes/issues/998), [#999](https://github.com/yegor256/takes/issues/999).

**Comment by 0pdd** [comment]
@fabriciofx the puzzle [#unknown]() is still not solved.

**Comment by 0pdd** [comment]
@fabriciofx 3 puzzles [#1000](https://github.com/yegor256/takes/issues/1000), [#1117](https://github.com/yegor256/takes/issues/1117), [#1603](https://github.com/yegor256/takes/issues/1603) are still not solved; solved: [#1008](https://github.com/yegor256/takes/issues/1008), [#1009](https://github.com/yegor256/takes/issues/1009), [#1010](https://github.com/yegor256/takes/issues/1010), [#1011](https://github.com/yegor256/takes/issues/1011), [#1012](https://github.com/yegor256/takes/issues/1012), [#1013](https://github.com/yegor256/takes/issues/1013), [#1014](https://github.com/yegor256/takes/issues/1014), [#1015](https://github.com/yegor256/takes/issues/1015), [#1016](https://github.com/yegor256/takes/issues/1016), [#1017](https://github.com/yegor256/takes/issues/1017), [#1018](https://github.com/yegor256/takes/issues/1018), [#1019](https://github.com/yegor256/takes/issues/1019), [#1080](https://github.com/yegor256/takes/issues/1080), [#1451](https://github.com/yegor256/takes/issues/1451), [#998](https://github.com/yegor256/takes/issues/998), [#999](https://github.com/yegor256/takes/issues/999).

**Comment by 0pdd** [comment]
@fabriciofx 2 puzzles [#1000](https://github.com/yegor256/takes/issues/1000), [#1603](https://github.com/yegor256/takes/issues/1603) are still not solved; solved: [#1008](https://github.com/yegor256/takes/issues/1008), [#1009](https://github.com/yegor256/takes/issues/1009), [#1010](https://github.com/yegor256/takes/issues/1010), [#1011](https://github.com/yegor256/takes/issues/1011), [#1012](https://github.com/yegor256/takes/issues/1012), [#1013](https://github.com/yegor256/takes/issues/1013), [#1014](https://github.com/yegor256/takes/issues/1014), [#1015](https://github.com/yegor256/takes/issues/1015), [#1016](https://github.com/yegor256/takes/issues/1016), [#1017](https://github.com/yegor256/takes/issues/1017), [#1018](https://github.com/yegor256/takes/issues/1018), [#1019](https://github.com/yegor256/takes/issues/1019), [#1080](https://github.com/yegor256/takes/issues/1080), [#1117](https://github.com/yegor256/takes/issues/1117), [#1451](https://github.com/yegor256/takes/issues/1451), [#998](https://github.com/yegor256/takes/issues/998), [#999](https://github.com/yegor256/takes/issues/999).

**Comment by 0pdd** [comment]
@fabriciofx the puzzle [#1000](https://github.com/yegor256/takes/issues/1000) is still not solved; solved: [#1008](https://github.com/yegor256/takes/issues/1008), [#1009](https://github.com/yegor256/takes/issues/1009), [#1010](https://github.com/yegor256/takes/issues/1010), [#1011](https://github.com/yegor256/takes/issues/1011), [#1012](https://github.com/yegor256/takes/issues/1012), [#1013](https://github.com/yegor256/takes/issues/1013), [#1014](https://github.com/yegor256/takes/issues/1014), [#1015](https://github.com/yegor256/takes/issues/1015), [#1016](https://github.com/yegor256/takes/issues/1016), [#1017](https://github.com/yegor256/takes/issues/1017), [#1018](https://github.com/yegor256/takes/issues/1018), [#1019](https://github.com/yegor256/takes/issues/1019), [#1080](https://github.com/yegor256/takes/issues/1080), [#1117](https://github.com/yegor256/takes/issues/1117), [#1451](https://github.com/yegor256/takes/issues/1451), [#1603](https://github.com/yegor256/takes/issues/1603), [#998](https://github.com/yegor256/takes/issues/998), [#999](https://github.com/yegor256/takes/issues/999).
