### ISSUE TITLE
RqFrom.java:39-41: Servlet request adapter is not...

### ISSUE THREAD

**Issue by 0pdd** [yegor256/takes#938]
The puzzle `866-ccba7032` from #866 has to be resolved: 

https://github.com/yegor256/takes/blob/7b495e78044afbecd2e17d09f5b5e4560de450f1/src/main/java/org/takes/servlet/RqFrom.java#L39-L41

The puzzle was created by @rultor on 11-Jan-19. 

  

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0crat** [comment]
Job [#938](https://github.com/yegor256/takes/issues/938) is now in scope, role is `DEV`

**Comment by 0pdd** [comment]
The puzzle `866-ccba7032` has disappeared from the source code, that's why I closed this issue.

**Comment by 0crat** [comment]
The job [#938](https://github.com/yegor256/takes/issues/938) is now out of scope
