### ISSUE TITLE
BkTimeable

### ISSUE THREAD

**Issue by yegor256** [yegor256/takes#94]
Let's create a new decorator of `Back`, which will allow any particular call to `accept()` last for less than X milliseconds. Something like this:

```java
new BkTimeable(new BkParallel(new BkBasic(takes)), 5000);
```

I think we should start "watching" threads for each call to `accept()` and terminate them when time is running out.

Also, let's add a new argument to `FtCLI`: `--max-latency` to configure this behavior from command line

**Comment by davvd** [comment]
@yegor256 OK, I labeled it as `bug`

**Comment by davvd** [comment]
@eg04lt3r This task is yours, please go ahead keeping in mind [this](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html). If any questions, don't hesitate to ask right here

The budget of this task is **30 mins**. This is exactly how much time will be compensated, when the task is completed. Read about our [Definition of Done](http://www.xdsd.org/2014/04/15/definition-of-done.html)

**Comment by davvd** [comment]
@yegor256 thanks for this report, I added 15 mins to your account, in transaction `000-882bb1bd`

**Comment by eg04lt3r** [comment]
@yegor256 fixed in #123 pull request

**Comment by davvd** [comment]
@eg04lt3r the ticket is with you for 15 days already. If it is not finished in the next 48 hours, it will be re-assigned to someone else, see [No Obligations](http://www.xdsd.org/2014/04/13/no-obligations-principle.html) principle, [this article](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html) should help if you're stuck... -30 added to your rating, current score is: [+8](http://www.netbout.com/b/35234?open=rating)

**Comment by davvd** [comment]
@eg04lt3r it takes too long. Usually, we expect any task to be finished in less than a week. I'll assign someone else. Please stop working with it right now. See our [no obligations](http://www.xdsd.org/2014/04/13/no-obligations-principle.html) principle

-60 added to your rating, at the moment it is: [-82](http://www.netbout.com/b/35234?open=rating)

**Comment by davvd** [comment]
@dmzaytsev the task is yours please proceed

**Comment by dmzaytsev** [comment]
@davvd I created the PR #197  for this task. Could you please find someone to review ?

**Comment by dmzaytsev** [comment]
@yegor256 the PR #197 merged. Please close the task if alright

**Comment by yegor256** [comment]
@dmzaytsev thanks a lot!

**Comment by yegor256** [comment]
@rultor release, tag is `0.15`

**Comment by davvd** [comment]
@elenavolokhova review this ticket please, for compliance with our [quality rules](http://www.teamed.io/qa.html)

**Comment by elenavolokhova** [comment]
@davvd Looks good.

**Comment by davvd** [comment]
> @davvd Looks good.

@elenavolokhova thanks a lot :)

**Comment by davvd** [comment]
@dmzaytsev I added 10 mins to @elenavolokhova (for QA review) in transaction 56370009; thanks, paid, **1 hour** to your account, payment ID is `56370016`, task took 108 hours and 51 mins to complete; age=2 mins, that's why a bonus here for fast delivery; +60 added to your rating, at the moment it is: [+1054](http://www.netbout.com/b/35166?open=rating)
