### ISSUE TITLE
Move all classes inside interfaces to outside

### ISSUE THREAD

**Issue by fabriciofx** [yegor256/takes#945]
Let's move all classes inside interfaces to outside. For example, `RqHeaders.Base`. We should extract the class `Base` to outside, renaming it to ´RqHeadersBase`. Reasons:
- It will simplify the interfaces a lot
- It will separate interfaces and interfaces
- It will standardize all classes names, avoiding "dot" in the middle of name
- Cactoos project already doing it

**Comment by 0crat** [comment]
@paulodamaso[/z](https://www.0crat.com/u/paulodamaso) please, pay attention to this issue

**Comment by yegor256** [comment]
@fabriciofx even though this may be a good idea, current design is pretty consistent as is
