### ISSUE TITLE
HmBodyTest.java:96-99: Continue removing static class...

### ISSUE THREAD

**Issue by 0pdd** [yegor256/takes#948]
The puzzle `893-3412ae8c` from #893 has to be resolved: 

https://github.com/yegor256/takes/blob/8b068621f157ff283a44f5c4b44d34e9bf74072c/src/test/java/org/takes/facets/hamcrest/HmBodyTest.java#L96-L99

The puzzle was created by @rultor on 16-Jan-19. 

  

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0crat** [comment]
@paulodamaso[/z](https://www.0crat.com/u/paulodamaso) please, pay attention to this issue

**Comment by 0crat** [comment]
Job [#948](https://github.com/yegor256/takes/issues/948) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
The job [#948](https://github.com/yegor256/takes/issues/948) assigned to @danilomo[/z](https://www.0crat.com/u/danilomo), here is [why](https://www.0crat.com/footprint/C3FFK3YAY/7bbd4389-ea2b-4fe4-83b6-bd7779785d6a); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be no monetary reward for this job

**Comment by danilomo** [comment]
@0crat wait

**Comment by 0crat** [comment]
> @0crat wait ([here](https://github.com/yegor256/takes/issues/948#issuecomment-466702300))

@danilomo The impediment for [#948](https://github.com/yegor256/takes/issues/948) was registered successfully by @danilomo[/z](https://www.0crat.com/u/danilomo)

**Comment by 0pdd** [comment]
The puzzle `893-3412ae8c` has disappeared from the source code, that's why I closed this issue.

**Comment by 0crat** [comment]
Job [#948](https://github.com/yegor256/takes/issues/948) is not in the agenda of @danilomo[/z](https://www.0crat.com/u/danilomo), can't set title

**Comment by 0crat** [comment]
Job [#948](https://github.com/yegor256/takes/issues/948) is not in the agenda of @danilomo[/z](https://www.0crat.com/u/danilomo), can't set title

**Comment by 0crat** [comment]
@sereshqua[/z](https://www.0crat.com/u/sereshqua) please review this job completed by @danilomo[/z](https://www.0crat.com/u/danilomo), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed
