### ISSUE TITLE
RsEmpty status should be 204 not 200

### ISSUE THREAD

**Issue by g4s8** [yegor256/takes#952]
Empty success response should have the status `204 NoContent` according to https://tools.ietf.org/html/rfc7230 see "3.3.  Message Body" section

>    All 1xx (Informational), 204 (No Content), and 304 (Not Modified)
   responses do not include a message body.  All other responses do
   include a message body, although the body might be of zero length.

so it would be more logical to use 204 status for `RsEmpty` and use `200` status as default only in `RsWithBody`.

**Comment by 0crat** [comment]
@paulodamaso[/z](https://www.0crat.com/u/paulodamaso) please, pay attention to this issue

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 point(s) just awarded to @g4s8[/z](https://www.0crat.com/u/g4s8)

**Comment by 0crat** [comment]
The job [#952](https://github.com/yegor256/takes/issues/952) assigned to @serranya[/z](https://www.0crat.com/u/serranya), here is [why](https://www.0crat.com/footprint/C3FFK3YAY/79ab85d4-3423-4c7a-bbc1-b9b95b8ddb88); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be no monetary reward for this job

**Comment by Serranya** [comment]
@0crat wait for Review on #971

**Comment by 0crat** [comment]
> @0crat wait for Review on #971  ([here](https://github.com/yegor256/takes/issues/952#issuecomment-468159939))

@Serranya The impediment for [#952](https://github.com/yegor256/takes/issues/952) was registered successfully by @serranya[/z](https://www.0crat.com/u/serranya)

**Comment by Serranya** [comment]
@g4s8 The PR #971 was merged to address this issue. Please close this ticket if the problem is solved to your satisfaction.

**Comment by g4s8** [comment]
@Serranya thanks

**Comment by 0crat** [comment]
The job [#952](https://github.com/yegor256/takes/issues/952) is now out of scope

**Comment by 0crat** [comment]
Order was finished: +30 point(s) just awarded to @serranya[/z](https://www.0crat.com/u/serranya)
