### ISSUE TITLE
SrvTake.java:42-44: Continue to integrate with Servlet...

### ISSUE THREAD

**Issue by 0pdd** [yegor256/takes#953]
The puzzle `865-bfce408b` from #865 has to be resolved: 

https://github.com/yegor256/takes/blob/afd95b0d5c40d0c40ad0fcfa9b21998268a37b87/src/main/java/org/takes/servlet/SrvTake.java#L42-L44

The puzzle was created by Fabricio Cabral on 24-Jan-19. 

  

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0crat** [comment]
@paulodamaso[/z](https://www.0crat.com/u/paulodamaso) please, pay attention to this issue

**Comment by 0crat** [comment]
Job [#953](https://github.com/yegor256/takes/issues/953) is now in scope, role is `DEV`

**Comment by fabriciofx** [comment]
@paulodamaso assigne to me

**Comment by paulodamaso** [comment]
@0crat assign @fabriciofx

**Comment by 0crat** [comment]
> @0crat assign @fabriciofx  ([here](https://github.com/yegor256/takes/issues/953#issuecomment-457312294))

@paulodamaso The job [#953](https://github.com/yegor256/takes/issues/953) assigned to @fabriciofx[/z](https://www.0crat.com/u/fabriciofx), here is [why](https://www.0crat.com/footprint/C3FFK3YAY/ab1db2e4-acb3-4c04-8303-7eafa380aa40); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be no monetary reward for this job

**Comment by 0crat** [comment]
Manual assignment of issues is discouraged, see [§19](http://www.zerocracy.com/policy.html#19): -5 point(s) just awarded to @paulodamaso[/z](https://www.0crat.com/u/paulodamaso)

**Comment by 0pdd** [comment]
The puzzle `865-bfce408b` has disappeared from the source code, that's why I closed this issue.

**Comment by 0pdd** [comment]
@0pdd the puzzle [#955](https://github.com/yegor256/takes/issues/955) is still not solved.

**Comment by 0crat** [comment]
Job was finished in 24 hours, bonus for fast delivery is possible (see [§36](http://www.zerocracy.com/policy.html#36))

**Comment by 0crat** [comment]
@ypshenychka[/z](https://www.0crat.com/u/ypshenychka) please review this job completed by @fabriciofx[/z](https://www.0crat.com/u/fabriciofx), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by 0crat** [comment]
The job [#953](https://github.com/yegor256/takes/issues/953) is now out of scope

**Comment by ypshenychka** [comment]
@0crat quality good

**Comment by 0pdd** [comment]
@0pdd the puzzle [#unknown]() is still not solved.
