### ISSUE TITLE
Update PR guidelines in PULL_REQUEST_TEMPLATE

### ISSUE THREAD

**Issue by fabriciofx** [yegor256/takes#957]
Cactoos project [updated PR guidelines](https://github.com/yegor256/cactoos/commit/b8bf44e4ddbe0b5a9b13e006208327358931c0cd) and I think it would be nice if we do that too. The new rules are:

- You made changes related to only one bug (create separate PRs for separate problems, or leave puzzles)
- You ran the build locally and it passed
- Title begins with the issue's number, then a short title
- Description begins with the issue's number, then enumerates the changes - summarized - in bulletpoints
- Description does not contain GitHub keywords (https://help.github.com/articles/closing-issues-using-keywords/).

**Comment by 0crat** [comment]
@paulodamaso[/z](https://www.0crat.com/u/paulodamaso) please, pay attention to this issue

**Comment by paulodamaso** [comment]
@0crat in

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 point(s) just awarded to @fabriciofx[/z](https://www.0crat.com/u/fabriciofx)

**Comment by 0crat** [comment]
The job [#957](https://github.com/yegor256/takes/issues/957) assigned to @lucasmessias9898[/z](https://www.0crat.com/u/lucasmessias9898), here is [why](https://www.0crat.com/footprint/C3FFK3YAY/dad6ff61-718d-4382-9706-a64e36bbb9af); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be no monetary reward for this job

**Comment by lucasmessias9898** [comment]
@0crat  refuse

**Comment by 0crat** [comment]
> @0crat refuse ([here](https://github.com/yegor256/takes/issues/957#issuecomment-469470113))

@lucasmessias9898 The user @lucasmessias9898[/z](https://www.0crat.com/u/lucasmessias9898) resigned from [#957](https://github.com/yegor256/takes/issues/957), please stop working. Reason for job resignation: Order was cancelled

**Comment by 0crat** [comment]
Tasks refusal is discouraged, see [§6](http://www.zerocracy.com/policy.html#6): -15 point(s) just awarded to @lucasmessias9898[/z](https://www.0crat.com/u/lucasmessias9898)

**Comment by 0crat** [comment]
The job [#957](https://github.com/yegor256/takes/issues/957) assigned to @serranya[/z](https://www.0crat.com/u/serranya), here is [why](https://www.0crat.com/footprint/C3FFK3YAY/3e2e82c0-a77f-4acd-bc63-4c2ac9275511); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be no monetary reward for this job

**Comment by Serranya** [comment]
@fabriciofx https://github.com/yegor256/takes/pull/974 is merged. Please close the issue if its addressed to your satisfaction.

**Comment by paulodamaso** [comment]
@Serranya Thanks!

**Comment by 0crat** [comment]
Job [#957](https://github.com/yegor256/takes/issues/957) is not in the agenda of @serranya[/z](https://www.0crat.com/u/serranya), can't inspect

**Comment by 0crat** [comment]
@sereshqua[/z](https://www.0crat.com/u/sereshqua) please review this job completed by @serranya[/z](https://www.0crat.com/u/serranya), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by 0crat** [comment]
The job [#957](https://github.com/yegor256/takes/issues/957) is now out of scope

**Comment by sereshqua** [comment]
@0crat quality good

**Comment by 0crat** [comment]
Order was finished, quality is "good": +35 point(s) just awarded to @serranya[/z](https://www.0crat.com/u/serranya)

**Comment by 0crat** [comment]
Quality review completed: +4 point(s) just awarded to @sereshqua[/z](https://www.0crat.com/u/sereshqua)
