### ISSUE TITLE
Update to cactoos 0.39

### ISSUE THREAD

**Issue by fabriciofx** [yegor256/takes#959]
Let's update to `cactoos` version `0.39`. This update brings many important corrections and improvements.

**Comment by 0crat** [comment]
@paulodamaso[/z](https://www.0crat.com/u/paulodamaso) please, pay attention to this issue

**Comment by golszewski86** [comment]
I believe #978 makes this issue invalid as cactoos will be upgraded to version 0.41

**Comment by paulodamaso** [comment]
@golszewski86 You are right, @fabriciofx  I'll close this issue

**Comment by 0crat** [comment]
Job `gh:yegor256/takes#959` is not assigned, can't get performer

**Comment by 0crat** [comment]
This job is not in scope
