### ISSUE TITLE
Identity with empty fields shall not be valid

### ISSUE THREAD

**Issue by ikhvostenkov** [yegor256/takes#97]
We mark as invalid ```Identity``` in ```Codec``` only ```Identity``` which we are not able to decode. But this could be such situation when we can decode, but get ```Identity``` object with empty URN and empty Properties (e.g. using Base64 decoding) and we handle it like valid ```Identity```. Lets make it as invalid as well.

**Comment by yegor256** [comment]
@ikhvostenkov can you give an example of a code that works now but should fail in your opinion?

**Comment by ikhvostenkov** [comment]
@yegor256 

 ```new CcSafe(new CcBase64(new CcPlain())).decode(
                " ^^^".getBytes())```

Will return Identity object with name="" and props=0map.
I suggest to return ```Identity.ANONYMOUS``` if there is no other reason to have ```Identity``` with empty fields.

**Comment by ikhvostenkov** [comment]
@yegor256 If to go deep in realization, actually following code just return ```Identity``` with empty fields:

```public Identity decode(final byte[] bytes) throws IOException {
        final String[] parts = new String(bytes).split(";");
        final ConcurrentMap<String, String> map =
            new ConcurrentHashMap<String, String>(parts.length);
        for (int idx = 1; idx < parts.length; ++idx) {
            final String[] pair = parts[idx].split("=");
            try {
                map.put(pair[0], CcPlain.decode(pair[1]));
            } catch (final IllegalArgumentException ex) {
                throw new DecodingException(ex);
            }
        }
        return new Identity.Simple(CcPlain.decode(parts[0]), map);
    }```
if ```bytes[]``` is 0 length.

**Comment by davvd** [comment]
we will find someone to do this task, soon

**Comment by davvd** [comment]
@dmzaytsev the task is yours, please go ahead

**Comment by davvd** [comment]
@ikhvostenkov thank you for the ticket reported, I topped your account for 15 mins, transaction `54559870`

**Comment by dmzaytsev** [comment]
@ikhvostenkov there is no CcBase64 class in the master branch.

@yegor256 implementations Codecs interface can be use without CcSafe decorator, right ?
If so I think we'll have to throws DecodingException in case of an empty Identity in each class. What do you think ?

**Comment by yegor256** [comment]
@dmzaytsev how about we create a new decorator `CcStrict`, which will apply strict rules to incoming and outgoing identities. If someone wants to be strict, he will use our decorator.

**Comment by dmzaytsev** [comment]
@yegor256 How to make rules for this decorator ? via implementations of IdentityCheck Interface ? e.g.
```
public interface IdentityCheck{
void check(final Identity identity) throws IOException
}
```

**Comment by yegor256** [comment]
@dmzaytsev I wouldn't make this design so complicated. Just a set of simple rules right inside `CcStrict`, something like:

```
if (identity.urn().isEmpty()) {
  throw...
}
if (!identity.urn().matches("urn:[a-z]+:.+")) {
  throw ...
}
```

**Comment by dmzaytsev** [comment]
@ikhvostenkov the PR #103 has been merged
take a look at the changes
if you  accept it close the task please

**Comment by dmzaytsev** [comment]
@ikhvostenkov close the task please

**Comment by ikhvostenkov** [comment]
@dmzaytsev issue resolved. Thank you.

**Comment by davvd** [comment]
@elenavolokhova please, let us know what do you think about this ticket, according to our [QA rules](http://www.teamed.io/qa.html)

**Comment by elenavolokhova** [comment]
@dmzaytsev 
>davvd commented 10 days ago
we will find someone to do this task, soon

 According to our [quality rules](http://www.teamed.io/qa.html):
 > Messages in a ticket always start with a name of a user they are addressed to.
 
 As far as you are the performer of this ticket you are responsible for its quality. Please make sure that everyone follows this rule in your tickets in the future. Ask them to fix issues before closing the ticket.
 
 Please confirm that everything is clear and you have no questions regarding this approach.

**Comment by dmzaytsev** [comment]
@elenavolokhova I confirm

**Comment by dmzaytsev** [comment]
@davvd  According to our [quality rules](http://www.teamed.io/qa.html):
>Messages in a ticket always start with a name of a user they are addressed to.

please fix your messages, thank you

**Comment by elenavolokhova** [comment]
@dmzaytsev Your confirmation is enough here. Let's prevent this in the future. Thank you!

**Comment by elenavolokhova** [comment]
@davvd Ticket passed QA review. Quality is acceptable.

**Comment by davvd** [comment]
> @davvd Ticket passed QA review. Quality is acceptable.

@elenavolokhova thank you, let's try to make it "good" next time

**Comment by davvd** [comment]
@dmzaytsev 10 mins was added to the account of @elenavolokhova (for QA review), in transaction 55483182; I added **38 mins** to your account, many thanks for working with the project! The completion time here was 55483208.; there is a bonus for fast delivery (age=3002); added +38 to your rating, now it is equal to [+430](http://www.netbout.com/b/35166?open=rating)
