### ISSUE TITLE
Missing method referenced in documentation

### ISSUE THREAD

**Issue by sz332** [yegor256/takes#975]
In the documentation the following snippet is provided for getting the URI based on the request.

```
Href href = new RqHref.Base(request).href();
URI uri = href.uri();
Iterable<String> values = href.param("key");
```

However, the current source code (1.16) does not contain href.uri() method.

**Comment by 0crat** [comment]
@paulodamaso[/z](https://www.0crat.com/u/paulodamaso) please, pay attention to this issue

**Comment by 0crat** [comment]
@sz332[/z](https://www.0crat.com/u/sz332) this project will fix the problem faster if you donate a few dollars to it; just [click here](https://www.0crat.com/contrib/C3FFK3YAY) and pay via Stripe, it's very fast, convenient and appreciated; thanks a lot!

**Comment by sz332** [comment]
Also tried to check the matching unit test (HrefTest) but found no example about how to get the query parameters.

**Comment by sz332** [comment]
Until there is a fix in the documentation, this is how I did it.

href.param("filter")

returns an Iterable<String> for filter parameter. However, in our case, the parameters are unique, and if by some reason the user provides multiple parameter with the same name, we will use the first one. So the solution is to convert the Iterable to a stream, get the first result, or if no result is present, return a default value, or throw an exception.

String fValue = StreamSupport.stream(href.param("filter").spliterator(), false)
.findFirst()
.orElse("");

**Comment by paulodamaso** [comment]
@0crat in

**Comment by 0crat** [comment]
> @0crat in ([here](https://github.com/yegor256/takes/issues/975#issuecomment-483264927))

@paulodamaso Job [#975](https://github.com/yegor256/takes/issues/975) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
> @0crat in ([here](https://github.com/yegor256/takes/issues/975#issuecomment-483264927))

@paulodamaso Thanks for your contribution, @sz332[/z](https://www.0crat.com/u/sz332)! If you would be a member of [the project](https://www.0crat.com/p/C3FFK3YAY), you would now earn +15 reputation points, as explained in [§29](http://www.zerocracy.com/policy.html#29). You can join and apply to it, see [§2](http://www.zerocracy.com/policy.html#2).

**Comment by 0crat** [comment]
The job [#975](https://github.com/yegor256/takes/issues/975) assigned to @fabriciofx[/z](https://www.0crat.com/u/fabriciofx), here is [why](https://www.0crat.com/footprint/C3FFK3YAY/a3df2ebc-612b-4994-a234-cd6b6ae448ce); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be no monetary reward for this job

**Comment by baudoliver7** [comment]
@yegor256 please, could you close this ticket ? It has already been resolved :)

**Comment by yegor256** [comment]
@sz332 I'm closing

**Comment by baudoliver7** [comment]
@yegor256 thx :)
