### ISSUE TITLE
Update maven-compiler-plugin and fix bug on it to allow incremental compilation

### ISSUE THREAD

**Issue by fabriciofx** [yegor256/takes#976]
Let's update `maven-compiler-plugin` to `3.8.0` version and fix a bug in this plugin which doesn't allow incremental compilation that increase compile and running time. To fix both we need change `pom.xml` to:
```
<plugin>
  <artifactId>maven-compiler-plugin</artifactId>
  <version>3.8.0</version>
  <configuration>
    <source>${jdk.version}</source>
    <target>${jdk.version}</target>
    <useIncrementalCompilation>false</useIncrementalCompilation>
  </configuration>
</plugin>
```
Please, pay attention to `<version>` and `<useIncrementalCompilation>` tag.

**Comment by 0crat** [comment]
@paulodamaso[/z](https://www.0crat.com/u/paulodamaso) please, pay attention to this issue

**Comment by 0crat** [comment]
@fabriciofx[/z](https://www.0crat.com/u/fabriciofx) this project will fix the problem faster if you donate a few dollars to it; just [click here](https://www.0crat.com/contrib/C3FFK3YAY) and pay via Stripe, it's very fast, convenient and appreciated; thanks a lot!

**Comment by paulodamaso** [comment]
@fabriciofx good catch let's do it

**Comment by paulodamaso** [comment]
@0crat in

**Comment by 0crat** [comment]
> @0crat in ([here](https://github.com/yegor256/takes/issues/976#issuecomment-486013160))

@paulodamaso Job [#976](https://github.com/yegor256/takes/issues/976) is now in scope, role is `DEV`

**Comment by fabriciofx** [comment]
@paulodamaso For more details: https://stackoverflow.com/a/19653164

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 point(s) just awarded to @fabriciofx[/z](https://www.0crat.com/u/fabriciofx)

**Comment by 0crat** [comment]
The job [#976](https://github.com/yegor256/takes/issues/976) assigned to @vzurauskas[/z](https://www.0crat.com/u/vzurauskas), here is [why](https://www.0crat.com/footprint/C3FFK3YAY/8b85d0a9-e6a0-4c76-95b3-cde8aba4c12e); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be no monetary reward for this job

**Comment by vzurauskas** [comment]
@0crat wait for https://github.com/yegor256/takes/pull/977 to be merged.

**Comment by 0crat** [comment]
> @0crat wait for https://github.com/yegor256/takes/pull/977 to be merged. ([here](https://github.com/yegor256/takes/issues/976#issuecomment-486661198))

@vzurauskas The impediment for [#976](https://github.com/yegor256/takes/issues/976) was registered successfully by @vzurauskas[/z](https://www.0crat.com/u/vzurauskas)

**Comment by vzurauskas** [comment]
@fabriciofx https://github.com/yegor256/takes/pull/977 was merged, can this issue be closed now?

**Comment by 0crat** [comment]
The job [#976](https://github.com/yegor256/takes/issues/976) assigned to @serranya[/z](https://www.0crat.com/u/serranya), here is [why](https://www.0crat.com/footprint/C3FFK3YAY/45dc2f96-f7d0-4fcc-bf0a-c4e0354c9780); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be no monetary reward for this job

**Comment by Serranya** [comment]
@paulodamaso Why was asigned to me? @vzurauskas seems to be working on this.

**Comment by paulodamaso** [comment]
@Serranya Looks like @0crat removed the impediment and re-assigned the issue. I'll return it to the original performer

**Comment by 0crat** [comment]
Are you speaking to me or about me [here](https://github.com/yegor256/takes/issues/976#issuecomment-490287226); you must always start your message with my name if you want to address it to me, see [§1](http://www.zerocracy.com/policy.html#1)

**Comment by paulodamaso** [comment]
@0crat assign @vzurauskas

**Comment by 0crat** [comment]
> @0crat assign @vzurauskas  ([here](https://github.com/yegor256/takes/issues/976#issuecomment-490287343))

@paulodamaso The job [#976](https://github.com/yegor256/takes/issues/976) assigned to @vzurauskas[/z](https://www.0crat.com/u/vzurauskas), here is [why](https://www.0crat.com/footprint/C3FFK3YAY/cf338946-f26b-4c23-8841-9c45e9e1c1f9); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); @vzurauskas[/z](https://www.0crat.com/u/vzurauskas) is not a member of this project yet, but they can request to join, as [§1](http://www.zerocracy.com/policy.html#1) explains; there will be no monetary reward for this job

**Comment by paulodamaso** [comment]
@vzurauskas Thanks!

**Comment by 0crat** [comment]
Manual assignment of issues is discouraged, see [§19](http://www.zerocracy.com/policy.html#19): -5 point(s) just awarded to @paulodamaso[/z](https://www.0crat.com/u/paulodamaso)

**Comment by paulodamaso** [comment]
@Serranya actually @vzurauskas Exited the project, that's why @0crat assigned the issue to you.

**Comment by 0crat** [comment]
Are you speaking to me or about me [here](https://github.com/yegor256/takes/issues/976#issuecomment-490288548); you must always start your message with my name if you want to address it to me, see [§1](http://www.zerocracy.com/policy.html#1)

**Comment by 0crat** [comment]
Job was finished in 0 hours, bonus for fast delivery is possible (see [§36](http://www.zerocracy.com/policy.html#36))

**Comment by 0crat** [comment]
Job [#976](https://github.com/yegor256/takes/issues/976) is not in the agenda of @vzurauskas[/z](https://www.0crat.com/u/vzurauskas), can't inspect

**Comment by 0crat** [comment]
@sereshqua[/z](https://www.0crat.com/u/sereshqua) please review this job completed by @vzurauskas[/z](https://www.0crat.com/u/vzurauskas), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by 0crat** [comment]
The job [#976](https://github.com/yegor256/takes/issues/976) is now out of scope

**Comment by sereshqua** [comment]
@0crat status

**Comment by 0crat** [comment]
> @0crat status ([here](https://github.com/yegor256/takes/issues/976#issuecomment-490352645))

@sereshqua This is what I know about this job in [C3FFK3YAY](https://www.0crat.com/p/C3FFK3YAY), as in [§32](http://www.zerocracy.com/policy.html#32):

  * The job [#976](https://github.com/yegor256/takes/issues/976) is not in scope
  * The job is waiting quality review verdict by @sereshqua[/z](https://www.0crat.com/u/sereshqua) for 6hr
  * @vzurauskas[/z](https://www.0crat.com/u/vzurauskas) will receive 35 minutes after quality review
  * Job [footprint](https://www.0crat.com/footprint/C3FFK3YAY?q=%7Bjob%3A%27gh%3Ayegor256%2Ftakes%23976%27%2Ctype%3A%7B%24not%3A%2F%5ENotify%2F%7D%7D) (restricted area)

**Comment by sereshqua** [comment]
@0crat quality good

**Comment by 0crat** [comment]
Quality review completed: +4 point(s) just awarded to @sereshqua[/z](https://www.0crat.com/u/sereshqua)

**Comment by 0crat** [comment]
Order was finished, quality is "good": +40 point(s) just awarded to @vzurauskas[/z](https://www.0crat.com/u/vzurauskas)
