### ISSUE TITLE
Travis CI build failed with ERROR: Error installing pdd

### ISSUE THREAD

**Issue by zCRUSADERz** [yegor256/takes#980]
Travis CI [build](https://travis-ci.org/yegor256/takes/builds/536102679) failed on installing pdd.

We need update Ruby version.

**Comment by 0crat** [comment]
@paulodamaso[/z](https://www.0crat.com/u/paulodamaso) please, pay attention to this issue

**Comment by 0crat** [comment]
@zcrusaderz[/z](https://www.0crat.com/u/zcrusaderz) this project will fix the problem faster if you donate a few dollars to it; just [click here](https://www.0crat.com/contrib/C3FFK3YAY) and pay via Stripe, it's very fast, convenient and appreciated; thanks a lot!

**Comment by 0crat** [comment]
Job `gh:yegor256/takes#980` is not assigned, can't get performer

**Comment by 0crat** [comment]
This job is not in scope
