### ISSUE TITLE
FkRegex removes trailing slash from URL

### ISSUE THREAD

**Issue by mreiche** [yegor256/takes#990]
Removing trailing slashes in FkRegex is IMHO a bad idea.

- It's magic besides the regex
- You can't have trailing slashes in your URL, even if you want. Ea.: as identifier for index (/) because `/path/resources` is the same like `/path/resources/`
- There is no reason to support such a feature. If you want to support optional trailing slashes, just add `\/?$` to your regex.
- It's undocumented

**Comment by 0crat** [comment]
@paulodamaso[/z](https://www.0crat.com/u/paulodamaso) please, pay attention to this issue

**Comment by 0crat** [comment]
@mreiche[/z](https://www.0crat.com/u/mreiche) this project will fix the problem faster if you donate a few dollars to it; just [click here](https://www.0crat.com/contrib/C3FFK3YAY) and pay via Stripe, it's very fast, convenient and appreciated; thanks a lot!

**Comment by paulodamaso** [comment]
@mreiche Please help me understand what happened in this issue: you did it before the pull request before the issue were open?

**Comment by mreiche** [comment]
Where do you need help? The PR in reference to the issue should describe
everything.

Paulo Lobo <notifications@github.com> schrieb am Do., 4. Juli 2019, 20:11:

**Comment by paulodamaso** [comment]
@0crat in

**Comment by 0crat** [comment]
> @0crat in ([here](https://github.com/yegor256/takes/issues/990#issuecomment-511120193))

@paulodamaso Job [#990](https://github.com/yegor256/takes/issues/990) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
> @0crat in ([here](https://github.com/yegor256/takes/issues/990#issuecomment-511120193))

@paulodamaso Thanks for your contribution, @mreiche[/z](https://www.0crat.com/u/mreiche)! If you would be a member of [the project](https://www.0crat.com/p/C3FFK3YAY), you would now earn +15 reputation points, as explained in [§29](http://www.zerocracy.com/policy.html#29). You can join and apply to it, see [§2](http://www.zerocracy.com/policy.html#2).

**Comment by paulodamaso** [comment]
@0crat assign @mreiche

**Comment by 0crat** [comment]
> @0crat assign @mreiche  ([here](https://github.com/yegor256/takes/issues/990#issuecomment-511120305))

@paulodamaso The job [#990](https://github.com/yegor256/takes/issues/990) assigned to @mreiche[/z](https://www.0crat.com/u/mreiche), here is [why](https://www.0crat.com/footprint/C3FFK3YAY/02321522-9c60-4530-9365-1db4de3a420c); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); @mreiche[/z](https://www.0crat.com/u/mreiche) is not a member of this project yet, but they can request to join, as [§1](http://www.zerocracy.com/policy.html#1) explains; there will be no monetary reward for this job

**Comment by 0crat** [comment]
It is strongly discouraged to assign jobs to their creators, see [§19](http://www.zerocracy.com/policy.html#19): -15 point(s) just awarded to @paulodamaso[/z](https://www.0crat.com/u/paulodamaso)

**Comment by 0crat** [comment]
Manual assignment of issues is discouraged, see [§19](http://www.zerocracy.com/policy.html#19): -5 point(s) just awarded to @paulodamaso[/z](https://www.0crat.com/u/paulodamaso)

**Comment by 0crat** [comment]
Job [#990](https://github.com/yegor256/takes/issues/990) is not in the agenda of @mreiche[/z](https://www.0crat.com/u/mreiche), can't inspect

**Comment by 0crat** [comment]
@sereshqua[/z](https://www.0crat.com/u/sereshqua) please review this job completed by @mreiche[/z](https://www.0crat.com/u/mreiche), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by 0crat** [comment]
The job [#990](https://github.com/yegor256/takes/issues/990) is now out of scope

**Comment by sereshqua** [comment]
@mreiche please make sure you start the messages with the name of the user there are addressed to, [see](https://github.com/yegor256/takes/issues/990#issuecomment-508961756)

**Comment by sereshqua** [comment]
@0crat quality acceptable

**Comment by 0crat** [comment]
Quality review completed: +4 point(s) just awarded to @sereshqua[/z](https://www.0crat.com/u/sereshqua)

**Comment by 0crat** [comment]
Order was finished, quality is "acceptable": +30 point(s) just awarded to @mreiche[/z](https://www.0crat.com/u/mreiche)
