### ISSUE TITLE
Builds in Travis fail on installing JDK

### ISSUE THREAD

**Issue by piotrkot** [yegor256/takes#991]
```
Expected feature release number in range of 9 to 14, but got: 8
The command "~/bin/install-jdk.sh --target "/home/travis/oraclejdk8" --workspace "/home/travis/.cache/install-jdk" --feature "8" --license "BCL"" failed and exited with 3 during .
```
See https://github.com/yegor256/takes/pull/985

**Comment by 0crat** [comment]
@paulodamaso[/z](https://www.0crat.com/u/paulodamaso) please, pay attention to this issue

**Comment by 0crat** [comment]
@piotrkot[/z](https://www.0crat.com/u/piotrkot) this project will fix the problem faster if you donate a few dollars to it; just [click here](https://www.0crat.com/contrib/C3FFK3YAY) and pay via Stripe, it's very fast, convenient and appreciated; thanks a lot!

**Comment by piotrkot** [comment]
@yegor256 @paulodamaso I think this is a task for administrator.

**Comment by paulodamaso** [comment]
@0crat assign @piotrkot

**Comment by paulodamaso** [comment]
@piotrkot It is a `oraclejdk8` image problem. Please take a look at https://travis-ci.community/t/install-of-oracle-jdk-8-failing/3038/2

**Comment by 0crat** [comment]
> @0crat assign @piotrkot  ([here](https://github.com/yegor256/takes/issues/991#issuecomment-528174367))

@paulodamaso The job [#991](https://github.com/yegor256/takes/issues/991) assigned to @piotrkot[/z](https://www.0crat.com/u/piotrkot), here is [why](https://www.0crat.com/footprint/C3FFK3YAY/b5436122-7f27-46cf-b709-b12af9a491e0); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); @piotrkot[/z](https://www.0crat.com/u/piotrkot) is not a member of this project yet, but they can request to join, as [§1](http://www.zerocracy.com/policy.html#1) explains; there will be no monetary reward for this job

**Comment by 0crat** [comment]
It is strongly discouraged to assign jobs to their creators, see [§19](http://www.zerocracy.com/policy.html#19): -15 point(s) just awarded to @paulodamaso[/z](https://www.0crat.com/u/paulodamaso)

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 point(s) just awarded to @piotrkot[/z](https://www.0crat.com/u/piotrkot)

**Comment by 0crat** [comment]
Manual assignment of issues is discouraged, see [§19](http://www.zerocracy.com/policy.html#19): -5 point(s) just awarded to @paulodamaso[/z](https://www.0crat.com/u/paulodamaso)

**Comment by piotrkot** [comment]
@paulodamaso Thank you for the hint. It builds successfully now.

**Comment by piotrkot** [comment]
Merged into master

**Comment by 0crat** [comment]
Job was finished in 26 hours, bonus for fast delivery is possible (see [§36](http://www.zerocracy.com/policy.html#36))

**Comment by 0crat** [comment]
@sereshqua[/z](https://www.0crat.com/u/sereshqua) please review this job completed by @piotrkot[/z](https://www.0crat.com/u/piotrkot), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by 0crat** [comment]
The job [#991](https://github.com/yegor256/takes/issues/991) is now out of scope

**Comment by sereshqua** [comment]
@piotrkot please make sure that you always start your messages with the name of the user they are addressed to, thanks

**Comment by sereshqua** [comment]
@piotrkot ping

**Comment by piotrkot** [comment]
@sereshqua pong

**Comment by sereshqua** [comment]
@0crat quality acceptable

**Comment by 0crat** [comment]
Quality review completed: +4 point(s) just awarded to @sereshqua[/z](https://www.0crat.com/u/sereshqua)

**Comment by 0crat** [comment]
Order was finished, quality is "acceptable": +35 point(s) just awarded to @piotrkot[/z](https://www.0crat.com/u/piotrkot)

**Comment by paulodamaso** [comment]
@rultor release tag is `1.19`
