### ISSUE TITLE
Copying bytes in RqMtBase is broken

### ISSUE THREAD

**Issue by piotrkot** [yegor256/takes#997]
It's broken `copy` function in `RqMtBase`.
This function is private and procedural so difficult to both test and understand. But let me explain.

Assume the boundary is `byte[] {13, 10, 45, 45, 102}` and the buffer is [position: 8190, limit: 8192, cap: 8192] with last two bytes in buffer are equal 13. Current byte read from the buffer is not equal to 13.
Now the code is:

```
      while (cont) {
            if (!this.buffer.hasRemaining()) {
                this.buffer.clear();
(3)           for (int idx = 0; idx < match; ++idx) {
(4)                  this.buffer.put(boundary[idx]);
                }
                match = 0;
                if (body.read(this.buffer) == -1) {
                    break;
                }
                this.buffer.flip();
            }
            final ByteBuffer btarget = this.buffer.slice();
            final int offset = this.buffer.position();
            btarget.limit(0);
            while (this.buffer.hasRemaining()) {
               final byte data = this.buffer.get();
(1)           if (data == boundary[match]) {
                    ++match;
(2)             } else if (data == boundary[0]) {
                    match = 1;
                } else {
                    match = 0;
                    btarget.limit(this.buffer.position() - offset);
                }
                if (match == boundary.length) {
                    cont = false;
                    break;
                }
            }
            target.write(btarget);
        }
```
When reading last but one byte from buffer we get 13 which satisfies (1), so `match = 1`.
Reading last byte we get 13 which satisfies (2), so `match = 1`.
There is no more bytes in the buffer, we write the result to the target and go to iteration (3). But since match is 1 we iterate just once, and only one byte 13 is put into the buffer (4). However, we should put two bytes 13 into the buffer.

**Comment by 0crat** [comment]
@paulodamaso[/z](https://www.0crat.com/u/paulodamaso) please, pay attention to this issue

**Comment by 0crat** [comment]
@piotrkot[/z](https://www.0crat.com/u/piotrkot) this project will fix the problem faster if you donate a few dollars to it; just [click here](https://www.0crat.com/contrib/C3FFK3YAY) and pay via Stripe, it's very fast, convenient and appreciated; thanks a lot!

**Comment by paulodamaso** [comment]
@0crat in

**Comment by 0crat** [comment]
> @0crat in ([here](https://github.com/yegor256/takes/issues/997#issuecomment-556843158))

@paulodamaso Job [#997](https://github.com/yegor256/takes/issues/997) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 point(s) just awarded to @piotrkot[/z](https://www.0crat.com/u/piotrkot)

**Comment by 0crat** [comment]
The job [#997](https://github.com/yegor256/takes/issues/997) assigned to @marceloamadeu[/z](https://www.0crat.com/u/marceloamadeu), here is [why](https://www.0crat.com/footprint/C3FFK3YAY/4858d139-39cc-485d-b578-4cd38cefdafd); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be no monetary reward for this job

**Comment by piotrkot** [comment]
@paulodamaso In case you don't find a developer for the task, please assign to me.

**Comment by piotrkot** [comment]
@paulodamaso How long can we wait for a developer to start or reject the task?

**Comment by paulodamaso** [comment]
@piotrkot Each ticket has a deadline of 10 days before @0crat assigns it to another developer.

**Comment by 0crat** [comment]
Are you speaking to me or about me [here](https://github.com/yegor256/takes/issues/997#issuecomment-559467225); you must always start your message with my name if you want to address it to me, see [§1](http://www.zerocracy.com/policy.html#1)

**Comment by piotrkot** [comment]
@paulodamaso It's been 11 days now.

**Comment by paulodamaso** [comment]
@0crat status

**Comment by 0crat** [comment]
> @0crat status ([here](https://github.com/yegor256/takes/issues/997#issuecomment-560957798))

@paulodamaso This is what I know about this job in [C3FFK3YAY](https://www.0crat.com/p/C3FFK3YAY), as in [§32](http://www.zerocracy.com/policy.html#32):

  * The job [#997](https://github.com/yegor256/takes/issues/997) is [in scope](http://www.zerocracy.com/policy.html#14) for 12days
  * The role is `DEV`
  * The job is assigned to @marceloamadeu[/z](https://www.0crat.com/u/marceloamadeu) for [12days](http://www.zerocracy.com/policy.html#8)
  * There is no monetary reward attached, it's a [free](http://www.zerocracy.com/policy.html#2) job
  * The job doesn't have any [impediments](http://www.zerocracy.com/policy.html#9)
  * The [budget](http://www.zerocracy.com/policy.html#4) is 30 minutes/points
  * These users are banned and won't be assigned:
    * @piotrkot[/z](https://www.0crat.com/u/piotrkot): This user reported the ticket
  * Job [footprint](https://www.0crat.com/footprint/C3FFK3YAY?q=%7Bjob%3A%27gh%3Ayegor256%2Ftakes%23997%27%2Ctype%3A%7B%24not%3A%2F%5ENotify%2F%7D%7D) (restricted area)

**Comment by piotrkot** [comment]
@paulodamaso Where can I file a bug that 0crat incorrectly keeps the job assigned for longer than it should?

**Comment by paulodamaso** [comment]
@piotrkot Please file it [here](https://github.com/zerocracy/farm)

**Comment by piotrkot** [comment]
@paulodamaso Can you reassign manually or we need to wait until 0crat is fixed?

**Comment by paulodamaso** [comment]
@0crat refuse

**Comment by 0crat** [comment]
> @0crat refuse ([here](https://github.com/yegor256/takes/issues/997#issuecomment-562090612))

@paulodamaso The user @marceloamadeu[/z](https://www.0crat.com/u/marceloamadeu) resigned from [#997](https://github.com/yegor256/takes/issues/997), please stop working. Reason for job resignation: Order was cancelled

**Comment by 0crat** [comment]
The job [#997](https://github.com/yegor256/takes/issues/997) assigned to @fanifieiev[/z](https://www.0crat.com/u/fanifieiev), here is [why](https://www.0crat.com/footprint/C3FFK3YAY/9746ca56-39ce-4ae7-8f23-010cabdc2cd4); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be no monetary reward for this job

**Comment by 0crat** [comment]
Job `gh:yegor256/takes#997` already assigned to @fanifieiev, can't assign to @fanifieiev

**Comment by fanifieiev** [comment]
@0crat refuse

**Comment by 0crat** [comment]
> @0crat refuse ([here](https://github.com/yegor256/takes/issues/997#issuecomment-565066803))

@fanifieiev The user @fanifieiev[/z](https://www.0crat.com/u/fanifieiev) resigned from [#997](https://github.com/yegor256/takes/issues/997), please stop working. Reason for job resignation: Order was cancelled

**Comment by 0crat** [comment]
Tasks refusal is discouraged (job refused in 34 hours), see [§6](http://www.zerocracy.com/policy.html#6): -10 point(s) just awarded to @fanifieiev[/z](https://www.0crat.com/u/fanifieiev)

**Comment by 0crat** [comment]
The job [#997](https://github.com/yegor256/takes/issues/997) assigned to @fabriciofx[/z](https://www.0crat.com/u/fabriciofx), here is [why](https://www.0crat.com/footprint/C3FFK3YAY/22320254-db20-43b0-897b-47dc1d37bba0); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be no monetary reward for this job

**Comment by fabriciofx** [comment]
@0crat refuse

**Comment by 0crat** [comment]
> @0crat refuse ([here](https://github.com/yegor256/takes/issues/997#issuecomment-675139944))

@fabriciofx The user @fabriciofx[/z](https://www.0crat.com/u/fabriciofx) resigned from [#997](https://github.com/yegor256/takes/issues/997), please stop working. Reason for job resignation: Order was cancelled

**Comment by piotrkot** [comment]
@paulodamaso I have a fix for this bug with test (actually I have it for half a year). Is there a way I can resolve it?

**Comment by piotrkot** [comment]
@yegor256 I found a bug here and have a solution. Why is it so difficult to fix it here?

**Comment by paulodamaso** [comment]
@0crat status

**Comment by 0crat** [comment]
> @0crat status ([here](https://github.com/yegor256/takes/issues/997#issuecomment-769264097))

@paulodamaso This is what I know about this job in C3FFK3YAY, as in [§32](http://www.zerocracy.com/policy.html#32):

  * The job [#997](https://github.com/yegor256/takes/issues/997) is [in scope](http://www.zerocracy.com/policy.html#14) for 14mon
  * The role is `DEV`
  * The job is not assigned to anyone
  * The [budget](http://www.zerocracy.com/policy.html#4) is not set yet
  * These users are banned and won't be assigned:
    * @piotrkot[/z](https://www.0crat.com/u/piotrkot): This user reported the ticket
    * @marceloamadeu[/z](https://www.0crat.com/u/marceloamadeu): User was resigned from the ticket
    * @fanifieiev[/z](https://www.0crat.com/u/fanifieiev): User was resigned from the ticket
    * @fabriciofx[/z](https://www.0crat.com/u/fabriciofx): User was resigned from the ticket
  * Job [footprint](https://www.0crat.com/footprint/C3FFK3YAY?q=%7Bjob%3A%27gh%3Ayegor256%2Ftakes%23997%27%2Ctype%3A%7B%24not%3A%2F%5ENotify%2F%7D%7D) (restricted area)

**Comment by 0pdd** [comment]
@piotrkot the puzzle [#1108](https://github.com/yegor256/takes/issues/1108) is still not solved.

**Comment by baudoliver7** [comment]
@0crat status

**Comment by baudoliver7** [comment]
@yegor256 It has been resolved in #1101. Please, close it.

**Comment by yegor256** [comment]
@baudoliver7 thanks!

**Comment by 0crat** [comment]
@sereshqua[/z](https://www.0crat.com/u/sereshqua) please review this job completed by @baudoliver7[/z](https://www.0crat.com/u/baudoliver7), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by sereshqua** [comment]
@0crat quality good

**Comment by 0pdd** [comment]
@piotrkot the puzzle [#unknown]() is still not solved.

**Comment by 0pdd** [comment]
@piotrkot the only puzzle [#1108](https://github.com/yegor256/takes/issues/1108) is solved here.
