### ISSUE TITLE
EnglishLowerCase.java:31-34: Remove this class in favour...

### ISSUE THREAD

**Issue by 0pdd** [yegor256/takes#998]
The puzzle `918-4b25f3bd` from #918 has to be resolved: 

https://github.com/yegor256/takes/blob/5a7041763ed2b59d9ea142c54a25dbea1596a5a2/src/main/java/org/takes/misc/EnglishLowerCase.java#L31-L34

The puzzle was created by @fanifieiev on 20-Nov-19. 

Estimate: 30 minutes,  role: DEV. 

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0crat** [comment]
@paulodamaso[/z](https://www.0crat.com/u/paulodamaso) please, pay attention to this issue

**Comment by 0crat** [comment]
Job [#998](https://github.com/yegor256/takes/issues/998) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
The job [#998](https://github.com/yegor256/takes/issues/998) assigned to @fanifieiev[/z](https://www.0crat.com/u/fanifieiev), here is [why](https://www.0crat.com/footprint/C3FFK3YAY/9137de27-1d14-4b3a-80c5-d575e71320d2); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be no monetary reward for this job

**Comment by 0crat** [comment]
Job `gh:yegor256/takes#998` already assigned to @fanifieiev, can't assign to @fanifieiev

**Comment by fanifieiev** [comment]
@0crat wait for merge

**Comment by 0crat** [comment]
> @0crat wait for merge ([here](https://github.com/yegor256/takes/issues/998#issuecomment-562319131))

@fanifieiev The impediment for [#998](https://github.com/yegor256/takes/issues/998) was registered successfully by @fanifieiev[/z](https://www.0crat.com/u/fanifieiev)

**Comment by fanifieiev** [comment]
@0crat Wait for [#1001 ](https://github.com/yegor256/takes/pull/1001) to be merged

**Comment by 0crat** [comment]
> @0crat Wait for [#1001 ](https://github.com/yegor256/takes/pull/1001) to be merged ([here](https://github.com/yegor256/takes/issues/998#issuecomment-562605268))

@fanifieiev Job [#998](https://github.com/yegor256/takes/issues/998) is already on hold

**Comment by 0pdd** [comment]
@0pdd 12 puzzles [#1008](https://github.com/yegor256/takes/issues/1008), [#1009](https://github.com/yegor256/takes/issues/1009), [#1010](https://github.com/yegor256/takes/issues/1010), [#1011](https://github.com/yegor256/takes/issues/1011), [#1012](https://github.com/yegor256/takes/issues/1012), [#1013](https://github.com/yegor256/takes/issues/1013), [#1014](https://github.com/yegor256/takes/issues/1014), [#1015](https://github.com/yegor256/takes/issues/1015), [#1016](https://github.com/yegor256/takes/issues/1016), [#1017](https://github.com/yegor256/takes/issues/1017), [#1018](https://github.com/yegor256/takes/issues/1018), [#1019](https://github.com/yegor256/takes/issues/1019) are still not solved.

**Comment by fanifieiev** [comment]
@0crat status

**Comment by 0crat** [comment]
> @0crat status ([here](https://github.com/yegor256/takes/issues/998#issuecomment-574194102))

@fanifieiev This is what I know about this job in [C3FFK3YAY](https://www.0crat.com/p/C3FFK3YAY), as in [§32](http://www.zerocracy.com/policy.html#32):

  * The job [#998](https://github.com/yegor256/takes/issues/998) is [in scope](http://www.zerocracy.com/policy.html#14) for 2mon
  * The role is `DEV`
  * The job is assigned to @fanifieiev[/z](https://www.0crat.com/u/fanifieiev) for [2mon](http://www.zerocracy.com/policy.html#8)
  * There is no monetary reward attached, it's a [free](http://www.zerocracy.com/policy.html#2) job
  * The job has an [impediment](http://www.zerocracy.com/policy.html#9)
  * The [budget](http://www.zerocracy.com/policy.html#4) is 30 minutes/points
  * These users are banned and won't be assigned:
    * @0pdd[/z](https://www.0crat.com/u/0pdd): This user reported the ticket
  * Job [footprint](https://www.0crat.com/footprint/C3FFK3YAY?q=%7Bjob%3A%27gh%3Ayegor256%2Ftakes%23998%27%2Ctype%3A%7B%24not%3A%2F%5ENotify%2F%7D%7D) (restricted area)

**Comment by fanifieiev** [comment]
@sereshqua Do you know who should close this issue??? The relevant [PR](https://github.com/yegor256/takes/pull/1001) has been merged already.
Thanks.

**Comment by sereshqua** [comment]
@fanifieiev if it is pdd it is either 0pdd or 0crat :) if smth is wrong - you can submit a bug and win 15 points, or just ask project architect to close it manually

**Comment by fanifieiev** [comment]
> @fanifieiev if it is pdd it is either 0pdd or 0crat :) if smth is wrong - you can submit a bug and win 15 points, or just ask project architect to close it manually

@sereshqua Thanks, got it.

**Comment by 0pdd** [comment]
The puzzle `918-4b25f3bd` has disappeared from the source code, that's why I closed this issue.

**Comment by 0crat** [comment]
@sereshqua[/z](https://www.0crat.com/u/sereshqua) please review this job completed by @fanifieiev[/z](https://www.0crat.com/u/fanifieiev), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by sereshqua** [comment]
@0crat quality good

**Comment by 0crat** [comment]
Order was finished, quality is "good": +35 point(s) just awarded to @fanifieiev[/z](https://www.0crat.com/u/fanifieiev)

**Comment by 0crat** [comment]
Quality review completed: +4 point(s) just awarded to @sereshqua[/z](https://www.0crat.com/u/sereshqua)

**Comment by 0pdd** [comment]
@0pdd 11 puzzles [#1008](https://github.com/yegor256/takes/issues/1008), [#1009](https://github.com/yegor256/takes/issues/1009), [#1011](https://github.com/yegor256/takes/issues/1011), [#1012](https://github.com/yegor256/takes/issues/1012), [#1013](https://github.com/yegor256/takes/issues/1013), [#1014](https://github.com/yegor256/takes/issues/1014), [#1015](https://github.com/yegor256/takes/issues/1015), [#1016](https://github.com/yegor256/takes/issues/1016), [#1017](https://github.com/yegor256/takes/issues/1017), [#1018](https://github.com/yegor256/takes/issues/1018), [#1019](https://github.com/yegor256/takes/issues/1019) are still not solved; solved: [#1010](https://github.com/yegor256/takes/issues/1010).

**Comment by 0pdd** [comment]
@0pdd 10 puzzles [#1008](https://github.com/yegor256/takes/issues/1008), [#1009](https://github.com/yegor256/takes/issues/1009), [#1011](https://github.com/yegor256/takes/issues/1011), [#1012](https://github.com/yegor256/takes/issues/1012), [#1014](https://github.com/yegor256/takes/issues/1014), [#1015](https://github.com/yegor256/takes/issues/1015), [#1016](https://github.com/yegor256/takes/issues/1016), [#1017](https://github.com/yegor256/takes/issues/1017), [#1018](https://github.com/yegor256/takes/issues/1018), [#1019](https://github.com/yegor256/takes/issues/1019) are still not solved; solved: [#1010](https://github.com/yegor256/takes/issues/1010), [#1013](https://github.com/yegor256/takes/issues/1013).

**Comment by 0pdd** [comment]
@0pdd 9 puzzles [#1009](https://github.com/yegor256/takes/issues/1009), [#1011](https://github.com/yegor256/takes/issues/1011), [#1012](https://github.com/yegor256/takes/issues/1012), [#1014](https://github.com/yegor256/takes/issues/1014), [#1015](https://github.com/yegor256/takes/issues/1015), [#1016](https://github.com/yegor256/takes/issues/1016), [#1017](https://github.com/yegor256/takes/issues/1017), [#1018](https://github.com/yegor256/takes/issues/1018), [#1019](https://github.com/yegor256/takes/issues/1019) are still not solved; solved: [#1008](https://github.com/yegor256/takes/issues/1008), [#1010](https://github.com/yegor256/takes/issues/1010), [#1013](https://github.com/yegor256/takes/issues/1013).

**Comment by 0pdd** [comment]
@0pdd 8 puzzles [#1009](https://github.com/yegor256/takes/issues/1009), [#1012](https://github.com/yegor256/takes/issues/1012), [#1014](https://github.com/yegor256/takes/issues/1014), [#1015](https://github.com/yegor256/takes/issues/1015), [#1016](https://github.com/yegor256/takes/issues/1016), [#1017](https://github.com/yegor256/takes/issues/1017), [#1018](https://github.com/yegor256/takes/issues/1018), [#1019](https://github.com/yegor256/takes/issues/1019) are still not solved; solved: [#1008](https://github.com/yegor256/takes/issues/1008), [#1010](https://github.com/yegor256/takes/issues/1010), [#1011](https://github.com/yegor256/takes/issues/1011), [#1013](https://github.com/yegor256/takes/issues/1013).

**Comment by 0pdd** [comment]
@0pdd 7 puzzles [#1009](https://github.com/yegor256/takes/issues/1009), [#1014](https://github.com/yegor256/takes/issues/1014), [#1015](https://github.com/yegor256/takes/issues/1015), [#1016](https://github.com/yegor256/takes/issues/1016), [#1017](https://github.com/yegor256/takes/issues/1017), [#1018](https://github.com/yegor256/takes/issues/1018), [#1019](https://github.com/yegor256/takes/issues/1019) are still not solved; solved: [#1008](https://github.com/yegor256/takes/issues/1008), [#1010](https://github.com/yegor256/takes/issues/1010), [#1011](https://github.com/yegor256/takes/issues/1011), [#1012](https://github.com/yegor256/takes/issues/1012), [#1013](https://github.com/yegor256/takes/issues/1013).

**Comment by 0pdd** [comment]
@0pdd 6 puzzles [#1009](https://github.com/yegor256/takes/issues/1009), [#1014](https://github.com/yegor256/takes/issues/1014), [#1015](https://github.com/yegor256/takes/issues/1015), [#1017](https://github.com/yegor256/takes/issues/1017), [#1018](https://github.com/yegor256/takes/issues/1018), [#1019](https://github.com/yegor256/takes/issues/1019) are still not solved; solved: [#1008](https://github.com/yegor256/takes/issues/1008), [#1010](https://github.com/yegor256/takes/issues/1010), [#1011](https://github.com/yegor256/takes/issues/1011), [#1012](https://github.com/yegor256/takes/issues/1012), [#1013](https://github.com/yegor256/takes/issues/1013), [#1016](https://github.com/yegor256/takes/issues/1016).

**Comment by 0pdd** [comment]
@0pdd 5 puzzles [#1009](https://github.com/yegor256/takes/issues/1009), [#1014](https://github.com/yegor256/takes/issues/1014), [#1015](https://github.com/yegor256/takes/issues/1015), [#1018](https://github.com/yegor256/takes/issues/1018), [#1019](https://github.com/yegor256/takes/issues/1019) are still not solved; solved: [#1008](https://github.com/yegor256/takes/issues/1008), [#1010](https://github.com/yegor256/takes/issues/1010), [#1011](https://github.com/yegor256/takes/issues/1011), [#1012](https://github.com/yegor256/takes/issues/1012), [#1013](https://github.com/yegor256/takes/issues/1013), [#1016](https://github.com/yegor256/takes/issues/1016), [#1017](https://github.com/yegor256/takes/issues/1017).

**Comment by 0pdd** [comment]
@0pdd 4 puzzles [#1009](https://github.com/yegor256/takes/issues/1009), [#1014](https://github.com/yegor256/takes/issues/1014), [#1018](https://github.com/yegor256/takes/issues/1018), [#1019](https://github.com/yegor256/takes/issues/1019) are still not solved; solved: [#1008](https://github.com/yegor256/takes/issues/1008), [#1010](https://github.com/yegor256/takes/issues/1010), [#1011](https://github.com/yegor256/takes/issues/1011), [#1012](https://github.com/yegor256/takes/issues/1012), [#1013](https://github.com/yegor256/takes/issues/1013), [#1015](https://github.com/yegor256/takes/issues/1015), [#1016](https://github.com/yegor256/takes/issues/1016), [#1017](https://github.com/yegor256/takes/issues/1017).

**Comment by 0pdd** [comment]
@0pdd 3 puzzles [#1009](https://github.com/yegor256/takes/issues/1009), [#1014](https://github.com/yegor256/takes/issues/1014), [#1018](https://github.com/yegor256/takes/issues/1018) are still not solved; solved: [#1008](https://github.com/yegor256/takes/issues/1008), [#1010](https://github.com/yegor256/takes/issues/1010), [#1011](https://github.com/yegor256/takes/issues/1011), [#1012](https://github.com/yegor256/takes/issues/1012), [#1013](https://github.com/yegor256/takes/issues/1013), [#1015](https://github.com/yegor256/takes/issues/1015), [#1016](https://github.com/yegor256/takes/issues/1016), [#1017](https://github.com/yegor256/takes/issues/1017), [#1019](https://github.com/yegor256/takes/issues/1019).

**Comment by 0pdd** [comment]
@0pdd 2 puzzles [#1009](https://github.com/yegor256/takes/issues/1009), [#1018](https://github.com/yegor256/takes/issues/1018) are still not solved; solved: [#1008](https://github.com/yegor256/takes/issues/1008), [#1010](https://github.com/yegor256/takes/issues/1010), [#1011](https://github.com/yegor256/takes/issues/1011), [#1012](https://github.com/yegor256/takes/issues/1012), [#1013](https://github.com/yegor256/takes/issues/1013), [#1014](https://github.com/yegor256/takes/issues/1014), [#1015](https://github.com/yegor256/takes/issues/1015), [#1016](https://github.com/yegor256/takes/issues/1016), [#1017](https://github.com/yegor256/takes/issues/1017), [#1019](https://github.com/yegor256/takes/issues/1019).

**Comment by 0pdd** [comment]
@0pdd 2 puzzles [#unknown](), [#unknown]() are still not solved.

**Comment by 0pdd** [comment]
@0pdd the puzzle [#1603](https://github.com/yegor256/takes/issues/1603) is still not solved; solved: [#1008](https://github.com/yegor256/takes/issues/1008), [#1009](https://github.com/yegor256/takes/issues/1009), [#1010](https://github.com/yegor256/takes/issues/1010), [#1011](https://github.com/yegor256/takes/issues/1011), [#1012](https://github.com/yegor256/takes/issues/1012), [#1013](https://github.com/yegor256/takes/issues/1013), [#1014](https://github.com/yegor256/takes/issues/1014), [#1015](https://github.com/yegor256/takes/issues/1015), [#1016](https://github.com/yegor256/takes/issues/1016), [#1017](https://github.com/yegor256/takes/issues/1017), [#1018](https://github.com/yegor256/takes/issues/1018), [#1019](https://github.com/yegor256/takes/issues/1019), [#1451](https://github.com/yegor256/takes/issues/1451).

**Comment by 0pdd** [comment]
@0pdd all 14 puzzles are solved here: [#1008](https://github.com/yegor256/takes/issues/1008), [#1009](https://github.com/yegor256/takes/issues/1009), [#1010](https://github.com/yegor256/takes/issues/1010), [#1011](https://github.com/yegor256/takes/issues/1011), [#1012](https://github.com/yegor256/takes/issues/1012), [#1013](https://github.com/yegor256/takes/issues/1013), [#1014](https://github.com/yegor256/takes/issues/1014), [#1015](https://github.com/yegor256/takes/issues/1015), [#1016](https://github.com/yegor256/takes/issues/1016), [#1017](https://github.com/yegor256/takes/issues/1017), [#1018](https://github.com/yegor256/takes/issues/1018), [#1019](https://github.com/yegor256/takes/issues/1019), [#1451](https://github.com/yegor256/takes/issues/1451), [#1603](https://github.com/yegor256/takes/issues/1603).
